/* ============================================================
   Ficha: dewey  ·  tradición: americana
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"dewey", trad:"americana", nombre:"John Dewey", fechas:"1859–1952 · EE. UU.", escuela:"Pragmatismo / instrumentalismo", icon:"🛠️", profundizada:true,
 tesis:"Pensar no es contemplar desde afuera una realidad ya hecha, sino intervenir en ella: las ideas son instrumentos que se forjan cuando una situación se vuelve problemática y se evalúan por su capacidad de reorganizarla. De ese mismo esquema salen su teoría del conocimiento, su pedagogía y su política, porque la indagación científica, el aprendizaje y la democracia son para Dewey la misma estructura —problema, hipótesis, prueba, revisión— desplegada a tres escalas.",
 obras:[
   {t:"Democracia y educación (1916)", d:"El libro donde su filosofía entera se vuelve legible de una vez: epistemología, pedagogía y teoría política sostenidas por un solo argumento. Dewey define la educación como la reconstrucción o reorganización de la experiencia que da sentido a la experiencia y aumenta la capacidad de dirigir el curso de la experiencia siguiente, y descarta expresamente las tres definiciones rivales de su época: la educación como preparación para una vida futura, como recapitulación del pasado cultural y como despliegue espontáneo de facultades innatas. Sobre esa base construye su criterio de sociedad democrática mediante dos preguntas comprobables —cuántos intereses se comparten conscientemente entre los miembros de un grupo y cuán plena y libre es la interacción de ese grupo con otros— y muestra que una sociedad de castas falla en ambas. La tesis que enlaza el título es que la democracia necesita educación no para instruir votantes, sino porque una forma de vida basada en la comunicación y el ajuste mutuo requiere personas capaces de revisar sus propios fines. Es también el libro donde rastrea los dualismos escolares vigentes —saber y hacer, cultura y oficio, trabajo y ocio— hasta la división griega entre clases ociosas y clases laboriosas, un movimiento genealógico que muchos lectores pasan por alto."},
   {t:"Cómo pensamos (1910, revisado en 1933)", d:"Su libro más práctico y el de mayor penetración real en las escuelas, escrito explícitamente para maestros. Distingue el pensamiento en sentido laxo —la corriente de ocurrencias, la creencia heredada sin examen, la fantasía— del pensamiento reflexivo, que define como el examen activo, persistente y cuidadoso de una creencia a la luz de los fundamentos que la sostienen y de las conclusiones a las que tiende. Su aporte más citado son las cinco fases de la reflexión: la perplejidad ante una dificultad sentida, su delimitación como problema, la sugerencia de hipótesis, el razonamiento que desarrolla sus consecuencias y la comprobación por la acción. Conviene leer la edición de 1933, porque en ella Dewey corrige la lectura mecánica que sus propios seguidores habían hecho del libro e insiste en que las fases no son pasos de un procedimiento a seguir en orden, sino aspectos que se entrelazan y reaparecen. También es el texto donde sostiene que la actitud reflexiva depende de disposiciones de carácter —mente abierta, dedicación sincera al asunto, responsabilidad por las consecuencias— y no solo de habilidades técnicas."},
   {t:"La búsqueda de la certeza (1929)", d:"Las conferencias Gifford dictadas en Edimburgo, y su ajuste de cuentas más frontal con la tradición filosófica occidental. Su hipótesis es histórica y antropológica antes que lógica: el ser humano vive en un mundo peligroso e inestable, y frente a esa inseguridad tuvo dos caminos, cambiar el mundo mediante la acción o cambiarse a sí mismo buscando refugio en un orden inmutable al que solo se accede por el pensamiento puro. La filosofía eligió sistemáticamente el segundo, y de ahí salieron la jerarquía entre teoría y práctica, el desprecio por el trabajo manual, la identificación de lo real con lo eterno y la idea de que conocer es contemplar. Dewey sostiene que el experimentalismo moderno, de Bacon a la física de su tiempo, desmintió esa imagen en los hechos —el laboratorio conoce interviniendo, no mirando— y que la filosofía no terminó de sacar las consecuencias. Su conclusión es una inversión programática: no hay que buscar certeza, hay que buscar seguridad mediante métodos de acción falibles y controlables, y el valor de una idea está en lo que permite hacer, no en la tranquilidad que ofrece."},
   {t:"Experiencia y naturaleza (1925)", d:"Su obra metafísica más ambiciosa y la más difícil de leer; el propio Dewey reconoció después que la palabra experiencia le había causado tantos malentendidos que habría preferido titularla Cultura y naturaleza. Su tesis central es la continuidad: la experiencia no es un velo interior tendido entre un sujeto y un mundo, sino algo que ocurre en la naturaleza, el modo en que un organismo vivo se relaciona con un entorno del que forma parte. De ahí su método, que llama empírico denotativo: partir de la experiencia gruesa y ordinaria, ir a las distinciones refinadas de la filosofía y volver a la experiencia ordinaria para comprobar si esas distinciones la iluminan o la desfiguran. Con ese procedimiento ataca lo que llama la falacia filosófica —tomar el resultado refinado de una indagación y proyectarlo hacia atrás como si hubiera sido el fundamento previo de todo— y desarma uno por uno los dualismos de mente y cuerpo, medio y fin, individuo y sociedad. Es también donde formula la fórmula que resume su naturalismo: las cosas son, antes que objetos de conocimiento, cosas de las que se goza y se padece, cosas usadas y hechas."},
   {t:"Lógica: teoría de la investigación (1938)", d:"El tratado de su vejez, a los setenta y nueve años, y su obra más técnica: el intento de fundar una lógica que no sea ni psicología del razonar ni un cálculo formal desconectado del mundo. Dewey define la indagación como la transformación controlada o dirigida de una situación indeterminada en otra que resulte tan determinada en sus distinciones y relaciones constitutivas que convierta los elementos de la situación original en un todo unificado. Cada pieza de esa definición hace trabajo: indeterminada no significa que alguien esté psicológicamente en duda, sino que la situación misma es objetivamente confusa, desequilibrada, abierta; y unificar no es descubrir una verdad preexistente sino producir una situación nueva. De allí sale su reemplazo más discutido: en vez de hablar de proposiciones verdaderas, propone hablar de aserción garantizada, el estatuto que alcanza un enunciado cuando ha sido efectivamente sometido a una indagación competente. También sostiene que las formas lógicas no son estructuras eternas sino que surgen en el curso de la propia indagación, tesis que lo enfrentó de lleno con Bertrand Russell y con la lógica formal de su tiempo."},
   {t:"El público y sus problemas (1927)", d:"Su libro político más denso, escrito como respuesta directa a Walter Lippmann, que en Opinión pública y en El público fantasma acababa de argumentar que el ciudadano común no puede conocer los asuntos de una sociedad compleja y que el gobierno debía quedar en manos de expertos. Dewey concede casi todo el diagnóstico y rechaza la conclusión. Su punto de partida es una definición funcional: un público no preexiste, se forma cuando las consecuencias indirectas de una transacción entre particulares afectan de manera duradera a terceros que entonces necesitan organizarse para regularlas; el Estado es el público organizado, no una entidad con dignidad propia. El problema de la época, dice, es que las consecuencias se han vuelto tan extensas y técnicas que el público no consigue identificarse a sí mismo: es una Gran Sociedad que todavía no es una Gran Comunidad. Su respuesta no es reemplazar al ciudadano por el experto sino mejorar radicalmente la comunicación, y su frase más conocida del libro pone el peso en el lugar exacto: el experto puede saber dónde aprieta el zapato, pero solo quien lo usa sabe que aprieta."}
 ],
 conceptos:[
   {t:"Instrumentalismo", d:"Es su nombre propio para el pragmatismo, y la etiqueta es deliberada: las ideas, los conceptos y las teorías son instrumentos, herramientas que un organismo fabrica para reorganizar una situación que se le volvió problemática, y se juzgan como se juzga cualquier herramienta, por lo que permiten hacer. Una idea no es una copia ni un espejo de una realidad previa, del mismo modo que un martillo no se parece al clavo. Esto no significa que dé lo mismo cualquier idea: un instrumento puede fallar, y falla objetivamente, porque la situación no se reorganiza. Conviene separar dos lecturas que se confunden. En su versión débil, el instrumentalismo dice que el valor de una idea se mide por sus consecuencias en la indagación, lo que casi nadie discutiría. En su versión fuerte, dice que no hay nada más que eso, que preguntar si además la idea corresponde a los hechos es volver a la imagen contemplativa que el instrumentalismo rechaza. Bertrand Russell atacó la versión fuerte durante décadas, y la discusión sobre si la segunda se sigue de la primera sigue abierta."},
   {t:"Indagación (inquiry) y situación indeterminada", d:"El concepto técnico que articula toda su obra tardía. Toda indagación empieza en una situación indeterminada: no en una duda mental que alguien decide tener, sino en una constelación objetiva de organismo y entorno que está desequilibrada, confusa, bloqueada. El primer paso, y el más difícil, no es responder sino convertir esa perplejidad difusa en un problema formulado, porque un problema bien planteado ya está medio resuelto y un problema mal planteado condena toda la investigación posterior. Siguen la formulación de hipótesis, que son planes de acción y no descripciones, el desarrollo de sus consecuencias y la prueba efectiva, que no es solo mirar sino intervenir. El resultado no es el descubrimiento de una verdad que estaba ahí esperando, sino una situación nueva, unificada. Desde aquí Dewey lanza su objeción más filosa a Descartes: la duda metódica es artificial porque nadie duda de todo, ni puede; la duda real es específica, la provoca una situación y desaparece cuando la situación se resuelve."},
   {t:"Educación progresiva y aprender haciendo", d:"Su tesis pedagógica no es que los chicos deban estar activos en vez de quietos, sino que el conocimiento se constituye en la reconstrucción reflexiva de una actividad. Dewey lo formula con precisión: aprender de la experiencia es establecer una conexión hacia atrás y hacia adelante entre lo que hacemos a las cosas y lo que gozamos o sufrimos como consecuencia, de modo que el hacer se convierta en ensayo y el padecer en instrucción. Dos advertencias son decisivas y casi siempre se pierden al citarlo. La primera es que una actividad sin reflexión sobre sus consecuencias no educa en absoluto: el activismo escolar sin pensamiento le parecía tan estéril como la memorización. La segunda es que no toda experiencia educa; en Experiencia y educación, de 1938, habla de experiencias deseducativas, las que embotan la sensibilidad o vuelven a alguien incapaz de experiencias posteriores más ricas. La escuela, para él, no prepara para la vida social futura: es ya una comunidad, una forma embrionaria de vida en común donde se practica lo que se predica."},
   {t:"Democracia como forma de vida", d:"La tesis por la que más se lo cita y la que más fácilmente se degrada en consigna. Democracia, escribe, es más que una forma de gobierno: es primariamente un modo de vivir asociado, de experiencia comunicada conjuntamente. El voto y las instituciones representativas son para él dispositivos históricos, valiosos pero derivados, y juzgarlos es preguntar si amplían o estrechan dos cosas medibles: la cantidad de intereses conscientemente compartidos dentro de un grupo y la plenitud de la interacción entre grupos distintos. Por eso su concepto se aplica a la familia, la fábrica, el sindicato y el aula tanto como al parlamento, y por eso critica sin rodeos la oposición entre una democracia política nominal y una organización industrial autoritaria. La objeción evidente es que una definición tan amplia corre el riesgo de disolver lo específicamente político —los derechos, los procedimientos, los contrapesos— en un ideal de convivencia; sus defensores responden que Dewey nunca propuso eliminarlos sino fundamentarlos en algo que los explique."},
   {t:"Continuidad entre experiencia y naturaleza", d:"El principio metafísico que sostiene todo lo demás y el que le permite negarse a elegir entre idealismo y materialismo. No hay dos reinos, uno mental y otro físico, unidos después por algún puente: hay grados de complejidad dentro de un mismo continuo natural, y lo mental aparece cuando un organismo suficientemente complejo interactúa con un entorno mediante el lenguaje y la cultura. De ahí el término que prefirió en su vejez, transacción: no es que primero exista un sujeto y por otro lado un objeto y luego se relacionen, sino que ambos se constituyen en el intercambio, como la respiración no es algo que el pulmón hace al aire sino un proceso que incluye a los dos. Con este principio disuelve en serie los dualismos de mente y cuerpo, sujeto y objeto, individuo y sociedad, naturaleza y cultura. La pregunta crítica que le hacen sus lectores es si disolver un dualismo cuenta como resolverlo, o si la continuidad se afirma con más frecuencia de la que se demuestra."},
   {t:"Crítica a la teoría del espectador", d:"Es el blanco central de La búsqueda de la certeza. La epistemología occidental, sostiene, concibió el conocer según el modelo de la visión: un sujeto situado fuera contempla un objeto ya hecho, y conocer bien es no alterar nada, ser un espectador fiel. De ahí que el error se explicara siempre por interferencia del cuerpo, de los intereses o de la acción, y que lo más real fuera lo más inmóvil. Dewey argumenta que la ciencia experimental refutó esa imagen en la práctica antes que ningún filósofo: el químico conoce una sustancia sometiéndola a operaciones que la modifican, y el conocimiento resultante no es una imagen de lo que la cosa era antes sino de lo que hace bajo condiciones controladas. Conocer es, entonces, una forma de hacer. Su tesis de la determinación práctica de los objetos de conocimiento fue el punto donde más críticas recibió, incluida la de sus amigos: si conocer transforma, cuesta explicar en qué sentido averiguamos algo sobre el mundo tal como es independientemente de nosotros. Dewey responde que la pregunta misma hereda el supuesto que se está discutiendo."},
   {t:"Crecimiento (growth)", d:"Su respuesta al problema de los fines educativos, y la más elegante y la más vulnerable de sus tesis. Dewey rechaza que la educación tenga un fin externo a ella —formar ciudadanos útiles, transmitir una cultura, preparar trabajadores— porque todo fin externo se vuelve un criterio impuesto desde afuera que interrumpe el proceso. El único fin legítimo, dice, es el crecimiento mismo, entendido como el aumento de la capacidad de seguir creciendo: el resultado más importante de la educación es la capacidad de continuar educándose. Y su criterio para distinguir crecimiento de mera modificación es formal pero no vacío: una experiencia es educativa cuando abre la posibilidad de experiencias posteriores más ricas, y deseducativa cuando la cierra. La objeción clásica la formuló con crudeza el propio Dewey al citarla: un ladrón también puede crecer como ladrón. Su respuesta es que ese crecimiento en una dirección estrecha clausura otras, y que por eso no es crecimiento en el sentido pleno; si esa respuesta basta o si introduce de contrabando un criterio externo es una de las discusiones vivas sobre su obra."},
   {t:"Formación y eclipse del público", d:"Su teoría de lo político, construida desde abajo y sin apelar a contratos, soberanías ni voluntades generales. Toda acción conjunta tiene consecuencias, y esas consecuencias son de dos tipos: las que afectan solo a quienes participaron directamente, que son asunto privado, y las que afectan de manera seria y duradera a terceros. Cuando esas últimas son percibidas, quienes las padecen tienen un interés común en regularlas, y al organizarse para hacerlo se constituyen como público; el Estado es simplemente ese público dotado de funcionarios y procedimientos. El diagnóstico de 1927 es que la Gran Sociedad creada por la industria y las comunicaciones produce consecuencias tan extensas, tan indirectas y tan técnicas que el público no logra reconocerse a sí mismo, y queda eclipsado. Contra Lippmann, Dewey no concluye que haya que entregar el gobierno a los expertos: la información técnica es necesaria, pero quién es afectado y cómo es algo que solo los afectados pueden decir, y de ahí su imagen del zapato que aprieta. Su salida es la mejora de la comunicación pública y la vida de comunidad local, lo que muchos lectores consideran su punto más débil por falta de mecanismos concretos."},
   {t:"El arte como experiencia", d:"El libro de 1934 que muchos consideran su obra maestra, y que aplica el principio de continuidad al terreno donde parecía más improbable. Su punto de partida es una crítica institucional: el museo separó las obras de la vida que las produjo, las convirtió en objetos de contemplación aislada y creó la ilusión de que lo estético es una esfera aparte. Dewey propone restaurar la continuidad entre la obra refinada y los acontecimientos cotidianos que reconocemos como experiencia: una conversación que se completa, una comida memorable, una tormenta seguida hasta el final, una partida jugada hasta el último punto. A eso llama una experiencia con artículo indefinido —un episodio que tiene desarrollo, tensión y consumación, en lugar de escurrirse como la rutina difusa— y sostiene que lo estético es precisamente esa cualidad de plenitud, intensificada y clarificada en la obra de arte pero no exclusiva de ella. De ahí dos consecuencias fuertes: la obra de arte no es el objeto físico sino lo que ese objeto hace en la experiencia de quien lo recibe, y el receptor no contempla pasivamente sino que ejecuta un trabajo comparable al del artista."}
 ],
 conexion:"Hacia atrás, <b>William James</b> le da la base pragmatista y <b>Peirce</b> el modelo de la indagación, pero Dewey reemplaza el vocabulario individual de la experiencia de una vida por el de organismo y medio, y el largo plazo de la comunidad de investigadores de Peirce por comunidades concretas resolviendo problemas concretos. Su versión de la verdad como aserción garantizada es el tercer camino dentro del pragmatismo, y es la que retomará <b>Richard Rorty</b> para llevarla mucho más lejos de lo que Dewey habría aceptado. Su insistencia en que el significado está en el uso y en la práctica compartida lo acerca al segundo <b>Wittgenstein</b>, y su ética de la formación del carácter por el hábito y la práctica encuentra un interlocutor inesperado en <b>Confucio</b> y en <b>Wang Yangming</b>, con quien comparte la tesis de que saber y hacer no son dos cosas separables.",
 dialogo:{titulo:"El zapato que aprieta", lineas:[
   {quien:"Docente", texto:"Le voy a hablar desde el aula y sin diplomacia. Llevo veinte años enseñando historia y sé lo que pasa cuando se aplica lo suyo: los chicos hacen maquetas, se divierten, trabajan en grupo, y al terminar el año no saben ubicar una revolución en un siglo. El aprender haciendo suena hermoso y en la práctica es desorden con buena prensa."},
   {quien:"Dewey", texto:"Si eso es lo que vio, tiene razón en rechazarlo, y le agrego algo: yo lo rechacé antes que usted y por escrito. Una actividad que no se conecta hacia atrás y hacia adelante con sus consecuencias no enseña nada. El movimiento se convirtió en una liturgia de la actividad, y confundió estar ocupado con estar aprendiendo."},
   {quien:"Docente", texto:"Entonces reconoce que la educación progresiva fracasó."},
   {quien:"Dewey", texto:"Reconozco que muchas de las escuelas que se llamaron progresivas hicieron exactamente lo contrario de lo que yo sostuve. Cuando en 1938 escribí Experiencia y educación, la mitad del libro es una advertencia contra mis propios seguidores: les digo que organizar la enseñanza en torno a la experiencia es más difícil que dictar lecciones, no más fácil, y que abandonar al alumno a lo que se le ocurra no es libertad sino abandono.", nota:"Este punto es histórico y conviene no suavizarlo en ninguna de las dos direcciones. Dewey criticó explícitamente la versión romántica del progresismo escolar que se le atribuía, y su propia escuela experimental de Chicago era intensamente estructurada. Pero tampoco es del todo justo declararlo inocente: su vocabulario —interés, actividad, necesidad del niño— se prestaba a esa lectura, y él no proporcionó los criterios prácticos que habrían impedido el deslizamiento. El debate entre educación centrada en el contenido y educación centrada en la indagación sigue abierto hoy, con evidencia empírica que no favorece a ninguno de los dos extremos."},
   {quien:"Docente", texto:"Vamos a lo concreto. Yo tengo que enseñar la Revolución Francesa en tres semanas. Si dicto, en tres semanas la cubro. Si hago indagar, cubro un tercio."},
   {quien:"Dewey", texto:"Pregúntese qué significa cubrir. Si al terminar el año sus alumnos pueden repetir fechas y no reconocen una situación revolucionaria cuando la tienen delante, usted cubrió el programa y no enseñó historia. Yo no le pido que elimine la exposición: le pido que la ponga donde sirve, que es después de que el problema exista para el alumno, no antes."},
   {quien:"Docente", texto:"Eso supone que el alumno tenga un problema. La mayoría no tiene ninguno y no quiere tenerlo."},
   {quien:"Dewey", texto:"Ahí está el trabajo del maestro, y es el más exigente de todos. No consiste en entretener ni en esperar que la curiosidad aparezca sola: consiste en construir la situación en la que una dificultad genuina se hace sentir, con materiales elegidos, con restricciones, con preguntas que no tengan respuesta disponible. Eso requiere saber mucho más de historia que dictar un resumen, no menos."},
   {quien:"Docente", texto:"Cambio de tema, porque hay algo más grave. Usted confía en que el método experimental, aplicado a los asuntos sociales, va a resolver nuestros conflictos como resolvió los problemas de la física. Yo vi dos guerras mundiales y campos de exterminio. Su fe en la inteligencia colectiva me parece la ilusión de un profesor que nunca miró de frente el mal humano."},
   {quien:"Dewey", texto:"Esa objeción tiene nombre y apellido, y me la hicieron en vida. Niebuhr sostuvo que confundo el egoísmo individual, que la educación puede moderar, con el egoísmo de los grupos, que solo cede ante el poder; y que la desigualdad no se disuelve con mejor comunicación porque nadie renuncia a un privilegio por argumentos."},
   {quien:"Docente", texto:"¿Y qué le responde?"},
   {quien:"Dewey", texto:"Le respondo dos cosas y le concedo una. Le concedo que subestimé el peso del conflicto de intereses y que escribí demasiado como si la ignorancia fuera el obstáculo principal. Lo que no le concedo es la alternativa: si el método inteligente no sirve para lo social, lo único que queda es la fuerza, y quien apela a la fuerza para corregir la injusticia necesita después algún criterio para distinguir su fuerza de la del adversario, y no tiene ninguno que no sea el que yo propongo.", nota:"El intercambio entre Dewey y Reinhold Niebuhr es real y vale la pena leerlo en las fuentes: Niebuhr publicó El hombre moral y la sociedad inmoral en 1932, y Dewey respondió sin nombrarlo en Liberalismo y acción social en 1935. El fondo teológico importa: Niebuhr apoya su realismo en la doctrina del pecado original y considera la fe de Dewey en la perfectibilidad por el método una secularización ingenua del progreso. Los lectores actuales tienden a dar por ganada la descripción de Niebuhr sobre el comportamiento de los grupos, y por ganada la de Dewey sobre lo que corresponde hacer después."},
   {quien:"Docente", texto:"Queda un problema práctico. Usted dice que los expertos no deben gobernar solos, pero los asuntos son técnicos. Yo no puedo opinar sobre política monetaria."},
   {quien:"Dewey", texto:"No le pido que la diseñe. Le pido que diga dónde le duele. El experto puede saber mejor que nadie dónde aprieta el zapato y cómo repararlo; el que sabe que aprieta, y dónde, es el que lo lleva puesto. Una clase de especialistas separada de los intereses comunes deja de ser experta en lo que importa: se vuelve experta en sus propios asuntos privados."},
   {quien:"Docente", texto:"Suena bien. Pero han pasado cien años y el público que usted esperaba no terminó de formarse."},
   {quien:"Dewey", texto:"No lo discuto. Escribí que la Gran Sociedad todavía no era una Gran Comunidad y no dije cuándo lo sería. Mi apuesta no es una predicción sino una condición: mientras la comunicación siga siendo el único modo de que las consecuencias compartidas se vuelvan visibles para quienes las padecen, cualquier salida que no pase por ahí va a reproducir el problema con otros dueños."}
 ]},
 actividades:[
   {t:"Rediseñar una clase que diste o recibiste", d:"Elegí un tema concreto que hayas enseñado o que te hayan enseñado de forma expositiva, y que recuerdes bien: un teorema, un período histórico, una regla gramatical, un procedimiento de laboratorio. Escribí primero, en cinco líneas, cómo se dio: qué dijo el docente, qué hicieron los estudiantes, cómo se evaluó. Después rediseñalo en clave de Dewey con tres exigencias estrictas. La primera es empezar por una situación indeterminada real, no por una pregunta retórica: una dificultad que el estudiante sienta antes de que le den la herramienta para resolverla. La segunda es decir explícitamente dónde entra la exposición del docente, porque Dewey no la elimina sino que la reubica. La tercera es describir cómo se cierra el ciclo, es decir, en qué momento la actividad se conecta hacia atrás con lo que se hizo y hacia adelante con las consecuencias, que es lo que la vuelve educativa y no mero entretenimiento. Cerrá con el párrafo más honesto del ejercicio: enumerá qué es concretamente más difícil en tu versión que en la clase expositiva —tiempo, control del grupo, dominio del tema, evaluación, imprevisibilidad— y decidí si esa dificultad es un costo aceptable o una objeción real a Dewey."},
   {t:"Mapear una indagación propia", d:"Identificá una situación reciente de tu vida que empezó confusa y terminó resuelta por investigación activa y no por suerte: una falla que diagnosticaste, un conflicto laboral que desarmaste, una decisión difícil, un problema de salud, una dificultad de aprendizaje de alguien a tu cargo. Reconstruila por escrito mapeando las fases del pensamiento reflexivo de Cómo pensamos: cuál fue la perplejidad inicial y cómo se sentía antes de tener nombre; cómo la convertiste en un problema formulado y qué formulaciones descartaste en el camino; qué hipótesis generaste; cómo razonaste sus consecuencias; y cómo las pusiste a prueba en la acción. Prestá especial atención a dos cosas que Dewey subraya y que el relato retrospectivo suele borrar. La primera: la formulación del problema no estaba dada al principio, la construiste, y una formulación distinta habría llevado a otra investigación entera. La segunda: al final no descubriste algo que ya estaba ahí, sino que la situación quedó transformada. Terminá indicando en qué punto tu caso no encaja con el esquema, porque ese desajuste vale más que la coincidencia."},
   {t:"Espectador o participante", d:"Elegí dos aprendizajes tuyos que hayan resultado igual de duraderos pero que hayas adquirido de maneras opuestas: uno donde fuiste espectador —leíste, escuchaste, miraste un video, estudiaste para un examen— y otro donde participaste en producir el conocimiento, es decir, donde tuviste que intervenir, equivocarte y corregir. Describí ambos en detalle y después comparalos según cuatro criterios: cuánto retuviste al año siguiente; si podés transferirlo a una situación distinta de aquella en que lo aprendiste; si sabés cuáles son sus límites y en qué casos no se aplica; y si podrías explicárselo a otro que no sepa nada. Con ese material escribí un párrafo de evaluación de la tesis de Dewey de que conocer es una forma de hacer. Y después escribí el párrafo contrario, que es el más interesante: buscá en tu propia experiencia un contraejemplo, algo importante que aprendiste de manera puramente receptiva y que sostenés igual de bien. Si lo encontrás, preguntate qué tenía de particular ese caso, y si eso obliga a corregir la tesis o solo a acotarla."}
 ],
 cuestionario:[
   {q:"El aprender haciendo, ¿no sacrifica el conocimiento estructurado en favor de la actividad abierta? Es la acusación que la educación progresiva recibe desde hace un siglo.", p:"Hay que separar tres cosas que la discusión suele mezclar. La primera es qué dijo Dewey. Su posición no es que la actividad reemplace al contenido: en Experiencia y educación, de 1938, dedica medio libro a criticar a las escuelas progresivas por creer que basta con dejar hacer, insiste en que organizar la enseñanza desde la experiencia exige más preparación del docente y más dominio del contenido que dictar una lección, y sostiene que sin organización progresiva de la materia la experiencia se dispersa. Su escuela experimental de Chicago era muy estructurada. La segunda es qué se hizo con eso. Muchas implementaciones se quedaron con el eslogan, y el propio Dewey lo denunció; en ese terreno la acusación es correcta pero no lo alcanza a él. La tercera es qué dice la evidencia, y aquí conviene no tomar partido antes de tiempo. La investigación en psicología cognitiva sobre carga cognitiva y sobre instrucción mínimamente guiada, con trabajos como los de Kirschner, Sweller y Clark, sostiene que los principiantes aprenden mejor con instrucción explícita y que el descubrimiento no guiado es ineficiente; los defensores de la indagación responden que esos estudios miden retención a corto plazo y no transferencia, comprensión profunda ni motivación sostenida. El resultado razonable hoy es que la instrucción directa es superior para adquirir conocimiento de base y que la indagación rinde más cuando ya hay base sobre la que indagar, lo que no es exactamente ninguna de las dos posiciones originales. Lo que sí queda en pie de Dewey es su punto más fuerte y menos discutido: que un conocimiento que nunca se usó para resolver nada es un signo repetido, no un saber."},
   {q:"Después del siglo XX, ¿no resulta ingenua la confianza de Dewey en que el método experimental y la comunicación democrática pueden resolver los conflictos sociales?", p:"La crítica más seria es la de Reinhold Niebuhr en El hombre moral y la sociedad inmoral, de 1932, y conviene tomarla en su forma fuerte. Niebuhr concede que los individuos pueden ser educados hacia la consideración de los demás, y sostiene que los grupos no: las naciones, las clases y las corporaciones tienen un egoísmo colectivo que ninguna educación disuelve, porque el privilegio no se abandona por comprensión sino cuando se lo obliga. Añade que Dewey trata la injusticia como un problema de ignorancia, cuando es un problema de poder, y que su fe en la perfectibilidad mediante el método es una versión secularizada de la doctrina del progreso que la teología cristiana ya había desmentido con el concepto de pecado original. La historia del siglo le dio a Niebuhr una fuerza retórica enorme. Dewey tiene tres respuestas, de valor desigual. La primera es que él nunca prometió éxito, sino que sostuvo que no hay alternativa mejor: quien renuncia al método inteligente queda con la fuerza, y la fuerza no trae consigo ningún criterio para distinguir su uso justo del injusto. La segunda es que el propio Niebuhr, cuando pasa de diagnosticar a proponer, necesita deliberación, negociación y persuasión, es decir, exactamente lo que Dewey llama inteligencia aplicada a lo social. La tercera, más débil, es que el fracaso de la democracia en el siglo XX se debió a que no fue lo bastante democrática. El saldo honesto es que Niebuhr gana la descripción del comportamiento de los grupos y Dewey conserva la pregunta por qué hacer después de aceptarla; y también que Dewey, al final de su vida y tras el ascenso del fascismo, escribió con menos optimismo que en 1916."},
   {q:"Si las ideas son instrumentos que se juzgan por lo que permiten hacer, ¿no queda la verdad reducida a utilidad y se pierde la idea de que una afirmación es objetivamente correcta?", p:"Es la objeción central al pragmatismo y Dewey intentó esquivarla de un modo que a algunos les parece una solución y a otros una retirada: dejó de hablar de verdad y propuso hablar de aserción garantizada, el estatuto que alcanza un enunciado cuando resistió una indagación competente. La ventaja es que evita las dos trampas, la de definir la verdad como copia de un hecho, que él considera inexplicable, y la de definirla como satisfacción, que sería relativismo. La aserción garantizada no es subjetiva: depende de que la situación problemática efectivamente se haya unificado, y eso puede fallar, falla a menudo y no lo decide quien investiga. Además Dewey nunca sostuvo que útil quiera decir cómodo o ventajoso para alguien; quiere decir eficaz para resolver el problema que originó la indagación, criterio duro y público. Ahora bien, quedan dos objeciones serias. La primera, formulada por Russell, es que si toda indagación transforma la situación, entonces no sabemos nada sobre el mundo tal como era antes de indagar, y la ciencia parece pretender justamente eso. La segunda es que la aserción garantizada se relativiza a una indagación concreta, mientras que verdadero parece no relativizarse: lo que estuvo garantizado en 1900 podía estar mal, y decimos que estaba mal, no que estaba garantizado entonces y no ahora. Bertrand Russell y Dewey discutieron esto durante cuarenta años sin acercarse. Quien quiera ver hasta dónde llega la línea de Dewey debería leer a Rorty, que la lleva al extremo de abandonar la noción de objetividad, y preguntarse si esa consecuencia estaba ya contenida en el punto de partida."},
   {q:"Si el único fin de la educación es el crecimiento y no hay un fin externo que lo oriente, ¿cómo se evita que la propuesta quede vacía o que cualquier dirección valga lo mismo?", p:"La objeción se formula desde hace un siglo con el mismo ejemplo, y es tan obvia que el propio Dewey la anticipó: un ladrón también puede crecer como ladrón, un fanático puede crecer en fanatismo. Su respuesta tiene dos partes. La primera es que el crecimiento no se mide por el avance en una dirección cualquiera sino por el aumento de la capacidad de seguir creciendo: el desarrollo del ladrón como ladrón estrecha su mundo, clausura relaciones, vuelve inaccesibles experiencias posteriores más ricas, y por eso no es crecimiento en el sentido que él le da. La segunda es que un fin externo, por bueno que sea, se impone desde afuera del proceso y detiene la revisión: si la meta está fijada de antemano, la indagación no puede corregirla. Hay dos maneras de evaluar la respuesta. A favor: el criterio no está tan vacío como parece, porque prohíbe algo concreto y comprobable, a saber, las experiencias que reducen la capacidad de tener experiencias, lo que Dewey llama deseducativas. En contra: para decidir que una dirección clausura más de lo que abre hace falta algún juicio sobre qué vale la pena abrir, y ese juicio parece venir de afuera del proceso; críticos como Richard Peters argumentaron que el criterio de crecimiento es parasitario de una concepción sustantiva de la buena vida que Dewey no quiso explicitar. La defensa disponible es que ninguna concepción sustantiva es definitiva y que todas deben quedar expuestas a revisión, lo que devuelve la pelota pero no cierra el punto."},
   {q:"Confucio también sostiene que el carácter se forma por la práctica y no por el discurso. ¿En qué se diferencian entonces su pedagogía y la de Dewey?", p:"El acuerdo es genuino y vale marcarlo antes que la diferencia: los dos rechazan que saber el bien sea suficiente para hacerlo, los dos ponen la formación del carácter en la repetición de prácticas concretas y no en la asimilación de doctrinas, y los dos entienden la educación como un asunto político y no como una técnica privada. Wang Yangming, con su tesis de la unidad de saber y hacer, está todavía más cerca de Dewey, hasta el punto de que Dewey dio conferencias en China entre 1919 y 1921 y fue leído allí como alguien que decía en vocabulario moderno algo ya familiar. Las diferencias son tres y son profundas. La primera es la dirección del tiempo: el aprendizaje confuciano se orienta hacia atrás, hacia los ritos y los modelos de los reyes sabios, y la autoridad del pasado es constitutiva; para Dewey el pasado es material para reconstruir y ninguna forma heredada tiene autoridad por ser heredada. La segunda es qué se hace con el conflicto: el li confuciano busca la armonía mediante formas compartidas, mientras Dewey considera que el conflicto es el motor de la indagación, porque sin situación problemática no hay pensamiento. La tercera es el estatuto de la jerarquía: los roles confucianos son asimétricos y recíprocos, y en Dewey la asimetría entre maestro y alumno es un hecho transitorio que la relación debe ir reduciendo. Hay un punto donde Confucio le hace a Dewey una objeción fuerte y no retórica: si todo está sujeto a revisión experimental, ¿de dónde sale la estabilidad de carácter que hace falta para poder experimentar sin desintegrarse? El hábito, que en Dewey es también un concepto central, podría ser el terreno donde los dos se encuentren."}
 ],
 cadena:{ titulo:"¿Para qué educar, si no hay un fin fuera de la educación?", intro:"Un razonamiento en ramas sobre la tesis más elegante y más vulnerable de Democracia y educación (1916): la educación no tiene un fin fuera de ella misma; su fin es el crecimiento. Las ramas siguen la objeción del ladrón, que Dewey mismo se planteó en Experiencia y educación (1938), y su crítica a las escuelas progresistas que lo invocaban.", inicio:"n1", nodos:{
   n1:{ pregunta:"Dewey escribe que, como el crecimiento es la característica de la vida, la educación es lo mismo que crecer y no tiene un fin más allá de sí misma. ¿Qué se sigue de eso?", opciones:[
     {texto:"Que la educación no tiene fines, y entonces cualquier cosa vale como educación.", va:"n2a"},
     {texto:"Que el fin es que cada experiencia haga posibles otras experiencias más ricas: más crecimiento.", va:"n2b"} ]},
   n2a:{ pregunta:"La objeción más famosa la formula el propio Dewey: un hombre puede crecer como ladrón, volverse cada vez más hábil y eficiente en su oficio. Si el fin es el crecimiento, ¿eso es educación?", opciones:[
     {texto:"No: ese crecimiento cierra otras líneas de crecimiento; el criterio es si crea condiciones para seguir creciendo en general.", va:"n3a"},
     {texto:"Dewey no tiene respuesta: para él, crecer es solo volverse más eficiente.", final:{tipo:"revisar", texto:"Dewey sí responde, en Experiencia y educación. Pregunta si el crecimiento en esa dirección promueve o retarda el crecimiento en general: el ladrón se vuelve más hábil, pero se cierra a otras experiencias, a otras relaciones, a otros oficios. El crecimiento, para Dewey, no es eficiencia en una línea, sino ampliación de las posibilidades. Volvé un paso y probá la otra respuesta."}} ]},
   n3a:{ pregunta:"¿Alcanza ese criterio para orientar la educación?", opciones:[
     {texto:"Sí: los principios de continuidad e interacción dan un criterio interno, sin necesidad de un fin impuesto desde afuera.", final:{tipo:"bien", texto:"Es la respuesta de Experiencia y educación: una experiencia es educativa si abre experiencias posteriores (continuidad) y si responde a la vez a las condiciones del que aprende y a las del medio (interacción). Es un criterio exigente y verificable en el aula. Su fuerza es que no depende de una idea fija de ser humano que haya que fabricar."}},
     {texto:"No del todo: sin alguna idea sustantiva de lo bueno, «crecer más» queda vago.", final:{tipo:"bien", texto:"Es la crítica más común, y tiene peso: para decidir qué crecimiento abre más posibilidades hace falta algún criterio de qué posibilidades valen. Dewey respondería que ese criterio es la democracia como forma de vida, la que hace posible el crecimiento de todos y no solo de algunos. Si esa respuesta es suficiente, o solo traslada el problema, sigue en discusión."}} ]},
   n2b:{ pregunta:"Si el fin es el crecimiento, ¿qué le toca hacer al docente?", opciones:[
     {texto:"Organizar experiencias que tengan continuidad: ni dejar hacer cualquier cosa ni imponer contenidos desde afuera.", va:"n3b"},
     {texto:"Retirarse: el estudiante aprende solo, siguiendo su interés espontáneo.", final:{tipo:"revisar", texto:"Es lo que hacían algunas escuelas progresistas en nombre de Dewey, y él las criticó con dureza en Experiencia y educación: rechazar la escuela tradicional no basta para tener una filosofía de la educación, y una reacción no es un método. El docente, para Dewey, tiene más responsabilidad, no menos, porque tiene que conocer a sus estudiantes y organizar experiencias que los lleven más lejos. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"¿Cómo sabe el docente si una experiencia fue educativa?", opciones:[
     {texto:"Si aumentó la capacidad del estudiante para enfrentar situaciones nuevas y respondió a sus condiciones reales y a las del medio.", final:{tipo:"bien", texto:"Son los dos principios de Experiencia y educación, continuidad e interacción, usados como criterio de evaluación. El costo es que no se ven en un examen de fin de periodo: hay que mirar qué hace el estudiante después, con problemas que no estaban en la clase."}},
     {texto:"Si los estudiantes la disfrutaron y estuvieron activos.", final:{tipo:"revisar", texto:"Dewey advierte justamente contra eso: una experiencia puede ser muy agradable y, sin embargo, deseducativa, si fomenta la dispersión o el descuido, o si no lleva a ningún lado. La actividad tampoco basta: estar ocupado no es lo mismo que reconstruir la experiencia. Volvé un paso y probá la otra respuesta."}} ]}
 }},
 reconstruccion:[
   { titulo:"Contra la teoría del espectador (La búsqueda de la certeza, 1929)",
     consigna:"Reconstruí el argumento de Dewey contra el modelo del conocimiento como contemplación. Una pieza saca una conclusión antiintelectual que Dewey no sostiene: dejala afuera.",
     piezas:[
       {id:"d1", texto:"La filosofía griega separó el conocer, contemplación de lo inmutable, del hacer, práctico e incierto, y puso al primero por encima.", tipo:"premisa"},
       {id:"d2", texto:"Esa separación reflejaba un orden social: los hombres libres con ocio contemplaban, y los esclavos y artesanos trabajaban.", tipo:"premisa"},
       {id:"d3", texto:"La ciencia experimental moderna no conoce contemplando: conoce interviniendo, modificando condiciones y observando qué consecuencias tiene la modificación.", tipo:"premisa"},
       {id:"d4", texto:"Conocer es, entonces, un modo de hacer dirigido y controlado, no la mirada de un espectador desde afuera.", tipo:"premisa"},
       {id:"d5", texto:"Por lo tanto, hay que abandonar la teoría del espectador: las ideas son hipótesis y planes de acción, y se validan por las consecuencias de las operaciones que dirigen.", tipo:"conclusion"},
       {id:"dx", texto:"Por lo tanto, la teoría no sirve para nada y lo único que importa es la práctica.", tipo:"distractor"}
     ],
     ordenCorrecto:["d1","d2","d3","d4","d5"],
     explicacion:"El argumento combina una genealogía histórica (d1-d2) con un análisis de cómo trabaja de hecho la ciencia (d3-d4). El punto débil es d3: generaliza desde las ciencias de laboratorio a todo conocimiento, pero la astronomía, la historia o la matemática no intervienen en su objeto: nadie puede experimentar con el pasado. Dewey respondería que se interviene en la situación de investigación —se buscan documentos, se construyen pruebas—, no necesariamente en el objeto, pero eso afloja bastante la tesis. Notá también que d2 explica el origen de una idea, y el origen no basta para refutarla. La pieza sobrante invierte a Dewey: él no desprecia la teoría, la redefine como instrumento; sin ideas, la práctica es rutina."},
   { titulo:"El público y sus problemas (1927)",
     consigna:"Reconstruí la respuesta de Dewey a Walter Lippmann sobre la crisis de la democracia. Una pieza es, justamente, la tesis de Lippmann: dejala afuera.",
     piezas:[
       {id:"q1", texto:"Toda acción humana tiene consecuencias: algunas afectan solo a quienes participan en ella; otras afectan, de manera indirecta y extensa, a terceros.", tipo:"premisa"},
       {id:"q2", texto:"El público está formado por todos los afectados por esas consecuencias indirectas, en la medida en que se considera necesario ocuparse de ellas de manera sistemática.", tipo:"premisa"},
       {id:"q3", texto:"El Estado es el público organizado, a través de funcionarios, para cuidar esos intereses.", tipo:"premisa"},
       {id:"q4", texto:"Con la sociedad industrial, las consecuencias indirectas se volvieron tan vastas y complejas que el público no logra reconocerse a sí mismo: es el eclipse del público.", tipo:"premisa"},
       {id:"q5", texto:"Por lo tanto, el problema de la democracia no es entregarles el poder a los expertos, sino mejorar los métodos y las condiciones del debate, la discusión y la persuasión, para que el público pueda encontrarse.", tipo:"conclusion"},
       {id:"qx", texto:"Por lo tanto, como el público no puede entender los asuntos complejos, las decisiones deben quedar en manos de expertos.", tipo:"distractor"}
     ],
     ordenCorrecto:["q1","q2","q3","q4","q5"],
     explicacion:"Dewey acepta el diagnóstico de Lippmann (q4), pero no su remedio. La conclusión está casi literal en el libro: el problema del público es la mejora de los métodos y condiciones del debate, la discusión y la persuasión. Su argumento contra el gobierno de expertos es la imagen del diálogo de esta ficha: el que usa el zapato sabe mejor que nadie dónde le aprieta, aunque el zapatero sepa mejor cómo arreglarlo. El punto débil es que el remedio es mucho más vago que el diagnóstico: Dewey no explica qué instituciones concretas mejorarían el debate público, y casi un siglo después la pregunta sigue abierta. La pieza sobrante es la posición de Lippmann, el adversario del libro."}
 ],
 dilemas:[
   { titulo:"El proyecto del parque",
     intro:"Dewey sostuvo que se aprende reconstruyendo experiencias reales, no acumulando contenidos para un futuro abstracto, y que la escuela debía ser una forma de vida democrática. También criticó a quienes, en su nombre, abandonaban la enseñanza sistemática. Este caso lleva esas ideas a un colegio colombiano con las Pruebas Saber 11 en el horizonte.",
     pasos:[
       { id:"p1", situacion:"Sos docente de ciencias sociales en grado décimo, en Ibagué. El parque del barrio está abandonado y los estudiantes hablan de él todo el tiempo. Querés hacer un proyecto: diagnosticar el problema y presentar una propuesta a la Junta de Acción Comunal. La coordinación te recuerda que hay que cubrir el plan de estudios para el Saber 11. ¿Qué hacés?", opciones:[
         {texto:"Me quedo con el plan de estudios tradicional: el Saber 11 es lo que les abre puertas.", consecuencia:"Es una preocupación legítima: el examen tiene consecuencias reales para el futuro de tus estudiantes. Pero Dewey te preguntaría si preparar para el futuro sacrificando el presente prepara de verdad: un contenido sin experiencia que lo sostenga se olvida rápido.", va:"p2"},
         {texto:"Reemplazo las clases por el proyecto: lo real enseña más que cualquier temario.", consecuencia:"Es lo que Dewey criticó en las escuelas progresistas de su época: tomar el polo opuesto de la escuela tradicional y llamarlo pedagogía. Un proyecto sin organización ni contenidos sistemáticos puede ser muy entretenido y dejar poco.", va:"p2"},
         {texto:"Diseño el proyecto para que pase por los contenidos del plan: participación ciudadana, lectura de normas, estadística, argumentación escrita.", consecuencia:"Es la propuesta de Dewey: no elegir entre experiencia y contenido, sino organizar una experiencia que exija los contenidos. Es más difícil de planear, y te exige conocer muy bien el plan de estudios.", va:"p2"} ]},
       { id:"p2", situacion:"A mitad del proyecto, los estudiantes descubren que el parque está abandonado por un conflicto entre la Junta de Acción Comunal y la alcaldía sobre quién debe mantenerlo. Algunos padres te reclaman que estás metiendo a sus hijos en política. ¿Qué hacés?", opciones:[
         {texto:"Cierro el tema del conflicto y me quedo con la parte técnica: medir, fotografiar, proponer.", consecuencia:"Evitás el conflicto, pero quitás la parte del problema que más enseña. Para Dewey, la democracia es una forma de vida que se aprende viviéndola, y averiguar quién es responsable de un bien común es exactamente lo que hace un público que se reconoce a sí mismo.", va:"p3"},
         {texto:"Reúno a los padres, explico qué se está aprendiendo y sigo, cuidando que los estudiantes escuchen a las dos partes.", consecuencia:"Tomaste en serio la objeción de los padres sin abandonar el problema. Que escuchen a la Junta y a la alcaldía no es neutralidad vacía: es el método de la investigación aplicado a un conflicto público.", va:"p3"},
         {texto:"Sigo adelante sin consultar: el proyecto es pedagógicamente válido y no tengo que justificarlo.", consecuencia:"Puede que sea válido, pero Dewey no pensaba la escuela como un espacio aislado: es parte de la comunidad, y los padres son parte del público afectado por lo que pasa en ella. Decidir sin ellos es una forma poco democrática de enseñar democracia.", va:"p3"} ]},
       { id:"p3", situacion:"Al final del año, los resultados del simulacro del Saber 11 en tu curso son parecidos a los de los otros cursos. La coordinadora te pregunta si el proyecto valió la pena. ¿Qué le respondés?", opciones:[
         {texto:"«Sí, porque los resultados del simulacro no bajaron.»", consecuencia:"Es un buen argumento para la coordinación, pero mide el proyecto con la vara del examen. Dewey te preguntaría qué pasó con lo que el examen no mide: si tus estudiantes ahora saben enfrentar un problema público que no está en el temario.", va:null},
         {texto:"«Sí: además de los contenidos, aprendieron a investigar un problema real y a participar en él. Esto es lo que vi que pueden hacer ahora y antes no podían.»", consecuencia:"Usaste el criterio de continuidad: qué capacidades nuevas quedaron abiertas. Y lo respaldaste con evidencia, no con entusiasmo, que es lo que Dewey le pedía a la evaluación.", va:null},
         {texto:"«No sé: no tengo cómo medirlo.»", consecuencia:"Es una respuesta honesta y señala un problema real: la pedagogía de Dewey es difícil de evaluar con los instrumentos que tenemos. Pero también es una invitación a diseñar la evaluación desde el comienzo, no al final.", va:null} ]}
     ],
     rubrica:[
       "Evité el falso dilema entre escuela tradicional y proyecto sin contenidos, que Dewey criticó en Experiencia y educación.",
       "Puedo explicar con este caso los principios de continuidad e interacción.",
       "Tomé en serio la preocupación por el Saber 11 sin dejar que fuera la única medida del aprendizaje.",
       "Pensé el conflicto del parque como una oportunidad para que los estudiantes aprendan qué es un público, en el sentido de Dewey.",
       "Incluí a los padres y a la comunidad como parte de la experiencia educativa, no como obstáculos.",
       "Propuse alguna forma de evidencia para saber si la experiencia fue educativa.",
       "Formulé la objeción más fuerte: que esta pedagogía exige docentes con un tiempo y una formación que el sistema escolar rara vez les da."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.dewey = { lecturas:[
 {titulo:"Democracia y educación: experiencia, investigación y democracia como forma de vida", fuente:"Internet Archive — Democracia y educación (John Dewey)", url:"https://archive.org/details/democracia-y-educacion-una-introduccion-a-la-filosofia-de-educacion-john-dewey",
  extracto:`Dewey define la educación de un modo que desplaza por completo la imagen de transmisión de contenidos: «la educación es aquella reconstrucción o reorganización de la experiencia que da sentido a la experiencia y que aumenta la capacidad para dirigir el curso de la experiencia subsiguiente». No es preparación para una vida futura, ni recapitulación del pasado, ni desarrollo espontáneo: es reconstrucción continua, y por eso no termina nunca.

Su crítica al modelo tradicional apunta a la separación entre saber y hacer, que él rastrea hasta la división griega entre clases ociosas y clases laboriosas. «Una onza de experiencia es mejor que una tonelada de teoría, simplemente porque solo en la experiencia cualquier teoría tiene significación vital y verificable.» El estudiante que memoriza una fórmula sin haberla usado para resolver nada no la sabe: repite un signo.

De ahí su célebre análisis de qué cuenta como experiencia educativa. «Aprender de la experiencia es establecer una conexión hacia atrás y hacia adelante entre lo que hacemos a las cosas y lo que gozamos o sufrimos de las cosas como consecuencia. En tales condiciones, el hacer se convierte en un ensayar, un experimento con el mundo para averiguar cómo es; y el padecer se convierte en instrucción, en el descubrimiento de la conexión entre las cosas.» Una actividad sin reflexión sobre sus consecuencias no educa; una reflexión sin actividad tampoco.

Ese mismo esquema lo desarrolla como teoría de la investigación (inquiry): toda indagación parte de una «situación indeterminada», genuinamente problemática — no de una duda psicológica arbitraria, como la de Descartes, que Dewey considera artificial. La indagación transforma esa situación en otra «determinada» mediante hipótesis que son planes de acción a probar. Las ideas, por tanto, son instrumentos: se evalúan por su capacidad de resolver la situación, no por su parecido con una realidad previa. Esto es el instrumentalismo, y de ahí su crítica a «la búsqueda de la certeza»: la filosofía occidental privilegió lo inmutable porque temía la contingencia práctica.

Sobre la democracia, Dewey da su definición más citada: «una democracia es más que una forma de gobierno; es primariamente un modo de vivir asociado, de experiencia comunicada conjuntamente». Y propone dos criterios medibles para juzgar cualquier forma social: cuántos intereses se comparten conscientemente entre los miembros del grupo, y cuán plena y libre es la interacción con otros grupos. Una sociedad de castas falla en ambos; una sociedad democrática los amplía.

La conexión entre las dos tesis es el núcleo del libro: la democracia necesita educación no porque haga falta instruir votantes, sino porque una forma de vida basada en la comunicación y el ajuste mutuo exige personas capaces de reconstruir su experiencia, escuchar consecuencias imprevistas y revisar sus fines. «El resultado más importante de la educación es la capacidad de seguir educándose.»`,
  comentario:"Dewey reúne epistemología, pedagogía y política en un solo movimiento: la investigación, el aprendizaje y la democracia son la misma estructura —problema, hipótesis, prueba, revisión— a tres escalas. Prestá atención a su crítica a Descartes: para Dewey la duda metódica es artificial porque no nace de una situación real. Y su definición de democracia por dos criterios comprobables es una herramienta excelente para analizar instituciones concretas, incluida la escuela."}
], preguntasLectura:[
 {q:"¿Cómo define Dewey la educación?", opciones:["Como preparación para la vida adulta","Como reconstrucción continua de la experiencia que aumenta la capacidad de dirigir la experiencia siguiente","Como transmisión de la herencia cultural","Como desarrollo espontáneo de facultades innatas"], r:"Como reconstrucción continua de la experiencia que aumenta la capacidad de dirigir la experiencia siguiente", why:"Dewey descarta expresamente las otras tres definiciones en el mismo capítulo."},
 {q:"Según Dewey, ¿qué hace que una actividad sea educativa?", opciones:["Que sea entretenida","Que se conecte hacia atrás y adelante con sus consecuencias, volviendo el hacer un ensayo y el padecer una instrucción","Que la dirija un maestro titulado","Que se evalúe con examen"], r:"Que se conecte hacia atrás y adelante con sus consecuencias, volviendo el hacer un ensayo y el padecer una instrucción", why:"Actividad sin reflexión no educa, y reflexión sin actividad tampoco."},
 {q:"¿Qué dos criterios propone Dewey para juzgar una forma social?", opciones:["Riqueza y estabilidad","Intereses conscientemente compartidos e interacción libre con otros grupos","Número de escuelas y de leyes","Igualdad económica y seguridad"], r:"Intereses conscientemente compartidos e interacción libre con otros grupos", why:"Son los dos criterios con que contrasta la sociedad de castas y la democracia como «modo de vivir asociado»."}
]};
