/* ============================================================
   Ficha: james  ·  tradición: americana
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"james", trad:"americana", nombre:"William James", fechas:"1842–1910 · EE. UU.", escuela:"Pragmatismo", icon:"🌉", profundizada:true,
 tesis:"El pragmatismo es primero un método para disolver disputas metafísicas preguntando qué diferencia práctica hay en juego, y después una teoría de la verdad: una idea no es verdadera de antemano, se vuelve verdadera en la medida en que nos conduce con éxito por la experiencia. Y en las cuestiones vivas que la evidencia no alcanza a zanjar, suspender el juicio tampoco es neutral: también es apostar.",
 obras:[
   {t:"Pragmatismo (1907)", d:"Su libro más leído y el que instaló la palabra en el vocabulario común. Son ocho conferencias dictadas en el Lowell Institute de Boston y en la Universidad de Columbia entre 1906 y 1907, pensadas para un público amplio y con la prosa más brillante que dio la filosofía norteamericana: la anécdota de la ardilla y el cazador, el pragmatismo como corredor de hotel al que dan habitaciones donde uno reza y otro escribe un tratado ateo, las teorías convertidas en instrumentos y no en respuestas donde descansar. La dedicatoria es una declaración de linaje: a la memoria de John Stuart Mill, de quien dice que aprendió el temperamento pragmatista y a quien le gustaría imaginar como jefe de la escuela si aún viviera. Conviene leerlo sabiendo lo que es y lo que no es: es una obra de divulgación, deliberadamente escrita para persuadir, y su rapidez es a la vez la causa de su influencia enorme y de casi todos los malentendidos que arrastra, empezando por la fórmula verdadero igual a útil que James nunca sostuvo en la forma cruda en que se le atribuye."},
   {t:"Principios de psicología (1890)", d:"Doce años de trabajo, mil cuatrocientas páginas y la obra fundacional de la psicología en lengua inglesa: cuando James empezó a enseñarla en Harvard, decía, la primera clase de psicología que escuchó fue la primera que dio. El libro es anterior a toda su filosofía pública y sin embargo la contiene entera en germen. Allí aparece la corriente de conciencia, la crítica al asociacionismo británico que descomponía la mente en átomos de sensación, la teoría de la emoción que hoy lleva su nombre y el de Lange, el capítulo sobre el hábito como volante de inercia de la sociedad, el análisis del yo desdoblado en material, social y espiritual, y un tratamiento de la atención y de la voluntad que sigue citándose. Su método es doble y esa es su marca: introspección honesta más fisiología de laboratorio, sin subordinar ninguna a la otra. Casi todo lo que James dirá después sobre la verdad, la creencia y la religión presupone esta descripción previa de cómo es de hecho la experiencia."},
   {t:"Las variedades de la experiencia religiosa (1902)", d:"Las conferencias Gifford dictadas en Edimburgo, con un plan de trabajo tan explícito como polémico: estudiar la religión no como institución, doctrina ni teología, sino como fenómeno de primera mano en la vida de individuos concretos, y hacerlo con método empírico, reuniendo documentos personales —diarios, cartas, testimonios de conversión, relatos de éxtasis— igual que un naturalista reúne especímenes. De ahí salen sus tipologías más citadas: el alma sana frente al alma enferma, el yo dividido y su unificación, la conversión súbita y la gradual, los rasgos recurrentes de la experiencia mística. Su regla de juicio es la que ordena todo el libro: hay que juzgar por los frutos, no por las raíces. Que una experiencia tenga un origen fisiológico explicable no decide nada sobre su valor, porque con ese criterio también habría que descartar el descubrimiento científico del que sabemos qué comió el descubridor. El libro incomoda por igual a creyentes y a ateos, y esa es probablemente la señal de que hizo lo que se proponía."},
   {t:"La voluntad de creer (1896)", d:"Conferencia dirigida a estudiantes de Yale y Brown, publicada como ensayo y convertida en el texto más discutido y más maltratado de James. Es una respuesta explícita al matemático W. K. Clifford, que once años antes había sostenido en La ética de la creencia que está mal siempre, en todas partes y para cualquiera creer algo con evidencia insuficiente. James no defiende el derecho a creer lo que a uno le convenga: acota el terreno con tres condiciones estrictas. La opción debe ser viva (las dos alternativas tienen que ser candidatas reales para esa persona), forzosa (no hay una tercera salida, y abstenerse equivale prácticamente a decidir) y de peso vital (algo importante se juega y la ocasión no se repite). Solo cuando además la cuestión no puede resolverse por medios intelectuales, dice, nuestra naturaleza pasional no solo puede sino que debe decidir. El propio James reconoció después que el título fue un error y que debió llamarlo El derecho a creer, porque no habla de un acto de voluntad sino de la legitimidad de una creencia adoptada bajo riesgo."},
   {t:"Un universo pluralista (1909)", d:"Las conferencias Hibbert de Oxford, su metafísica tardía y su ajuste de cuentas con el idealismo absoluto de F. H. Bradley en Inglaterra y de su amigo y colega Josiah Royce en Harvard. Contra el monismo, que concibe el universo como un bloque único donde todo está internamente relacionado con todo y donde ya está decidido lo que hay, James defiende un mundo genuinamente múltiple, con junturas y relaciones externas, un universo de tipo distributivo y no colectivo, donde las cosas están conectadas de muchos modos pero ninguna está conectada con todas. De ahí su fórmula del universo inacabado: la realidad está todavía haciéndose, hay novedad real y por eso la acción humana cuenta de verdad y no solo aparentemente. Es también el libro donde defiende una filosofía de lo inmediato inspirada en Bergson y donde reconoce que un mundo pluralista es más inseguro, porque admite la posibilidad de una pérdida definitiva que ningún Absoluto vendrá a compensar."}
 ],
 conceptos:[
   {t:"El pragmatismo como método", d:"Antes que una doctrina, un procedimiento: ante dos posiciones enfrentadas, preguntar qué diferencia práctica concreta habría en el mundo si fuera verdadera una u otra. Si no se encuentra ninguna, la disputa es verbal y se disuelve, como en la discusión de campamento sobre si el hombre da la vuelta alrededor de la ardilla. Hasta aquí James se declara discípulo de Peirce, y hay que ser honestos sobre lo que agrega y lo que pierde en el camino. La máxima de Peirce era una regla para aclarar el significado de conceptos generales, formulada en términos de efectos concebibles y apoyada en un realismo sobre las leyes; James la ensancha hasta convertirla también en una teoría de la verdad, la aplica a creencias singulares y la escribe en un registro que invita a leer las consecuencias prácticas como consecuencias para el creyente. Peirce reaccionó rebautizando su propia posición como pragmaticismo. Quien estudie a los dos debería resistir tanto la versión que presenta a James como un simple divulgador que malentendió, como la que borra la diferencia: es un desacuerdo filosófico real sobre si el criterio se ancla en la comunidad a largo plazo o en la experiencia de una vida concreta."},
   {t:"La corriente de conciencia", d:"La imagen es suya y cambió el modo de describir la mente: la conciencia no se presenta troceada, no aparece en pedazos, y palabras como cadena o serie la describen mal; lo que fluye es un río, una corriente. El blanco explícito es el asociacionismo británico de Locke, Hume y los Mill, que reconstruía la vida mental como una combinación de átomos de sensación enlazados por leyes de asociación. James objeta que esa descripción no se corresponde con lo que encontramos al mirar: la conciencia es continua aunque haya interrupciones como el sueño, es siempre personal, es selectiva y cambia sin repetir nunca dos veces el mismo estado, porque cada pensamiento llega teñido por todo lo anterior. Su aporte más fino son los estados transitivos: no solo hay sustantivos en la corriente, también hay sentimientos de y, de si, de pero, y el sentimiento de una tendencia es tan real como el sentimiento de una cosa. La expresión pasó a la literatura —Joyce, Woolf, Faulkner— por una vía indirecta, pero nació como una tesis psicológica argumentada."},
   {t:"La voluntad de creer", d:"En las cuestiones donde la evidencia no alcanza a decidir y sin embargo hay que decidir igual, es legítimo que factores no intelectuales inclinen la creencia. La tesis suele citarse sin sus condiciones, y sin ellas es indefendible. James exige que la opción sea viva, forzosa y de peso vital, y que además sea genuinamente indecidible por medios intelectuales: ninguna de las tres condiciones se cumple en la mayoría de las creencias corrientes, de modo que el permiso es mucho más estrecho de lo que sugiere la caricatura. Su argumento central es que el escéptico que suspende el juicio no ocupa una posición neutral: quien dice mejor no arriesgarse a creer una falsedad está eligiendo, por temor al error, perder la posibilidad de una verdad, y eso también es una apuesta, tomada con otra emoción de fondo. Añade un caso donde la creencia es literalmente condición del hecho: la confianza en otra persona, la decisión de saltar un precipicio, el compromiso con una causa colectiva, situaciones donde creer que se puede es parte de lo que hace que se pueda."},
   {t:"Empirismo radical", d:"Es su tesis filosófica más técnica y la que él consideraba más importante, aunque quedara a la sombra del pragmatismo. Consta de un postulado, un hecho y una conclusión. El postulado: solo deben discutirse entre filósofos cosas definibles en términos tomados de la experiencia. El hecho: las relaciones entre las cosas son tan directamente experimentadas como las cosas mismas; no percibimos primero objetos sueltos a los que la razón añade después vínculos de causa, de semejanza o de continuidad, sino que la conjunción y la disyunción se sienten en la corriente igual que los términos. La conclusión: por eso el mundo tiene estructura conjuntiva propia y no hace falta ningún principio trascendental que la aporte desde afuera. Con esto James pretende quedar a la vez fuera del empirismo clásico, que se queda con átomos desconectados y termina en escepticismo, y fuera del idealismo, que para recuperar las conexiones postula un Absoluto. La objeción evidente está a la vista: cuando alguien dice experimentar directamente las relaciones, ¿describe un hallazgo o amplía por decreto el significado de la palabra experiencia?"},
   {t:"Pluralismo y universo inacabado", d:"Su metafísica tardía, dirigida contra el monismo absolutista de Bradley y de Royce. La pregunta no es si el mundo está conectado, que obviamente lo está, sino si está totalmente conectado: si toda cosa se relaciona internamente con toda otra en un único sistema, de modo que nada podría ser distinto sin que todo lo fuera. James responde que no. El universo es de tipo distributivo, un cada uno y no un todo, un mundo con junturas reales, donde las relaciones son externas y algo puede cambiar sin arrastrar consigo la totalidad. La consecuencia decisiva es temporal: si el bloque no está cerrado, el futuro está genuinamente abierto, hay novedad real y las decisiones humanas agregan algo al mundo en vez de desplegar lo que ya estaba. James llama meliorismo a la actitud correspondiente, a medio camino entre el optimismo, que garantiza la salvación del mundo, y el pesimismo, que la declara imposible: el mundo puede mejorar, y si mejora será en parte por lo que hagamos. El precio, que él acepta explícitamente, es que en un universo así también la pérdida puede ser definitiva."},
   {t:"Teoría James-Lange de la emoción", d:"Formulada con independencia por James en 1884 y por el fisiólogo danés Carl Lange en 1885, invierte el orden que da por supuesto el sentido común. La secuencia habitual sería: percibimos al oso, sentimos miedo y por eso temblamos y corremos. James sostiene lo contrario: percibimos al oso, el cuerpo reacciona —corre, tiembla, se acelera el pulso, se contrae el estómago— y la emoción es la percepción de esos cambios corporales. De ahí su formulación provocadora de que no lloramos porque estamos tristes, sino que estamos tristes porque lloramos, y su experimento mental decisivo: quítesele a la emoción todo su contenido corporal y fíjese qué queda. Su respuesta es que no queda nada, solo un juicio frío e incoloro. La historia posterior de la teoría es complicada y vale la pena conocerla: Walter Cannon la atacó en los años veinte con objeciones fuertes, después vino la teoría de los dos factores de Schachter y Singer, y desde los años noventa autores como Antonio Damasio recuperaron el núcleo corporal de James por otra vía, mientras la investigación actual discute hasta qué punto los patrones corporales son específicos de cada emoción. No es una teoría simplemente refutada ni simplemente vigente."},
   {t:"El valor en efectivo de las ideas", d:"La metáfora económica más famosa y más costosa de James: hay que preguntar por el cash value de una idea, su valor en efectivo dentro de la experiencia, es decir, qué produce concretamente si se la pone a trabajar. Completa la imagen con la distinción entre crédito y pago: vivimos casi todo el tiempo de creencias que no verificamos personalmente, como quien usa billetes sin pasar por el banco, y el sistema se sostiene porque en algún punto de la red la verificación es posible y alguien efectivamente la hizo. La metáfora hace un trabajo filosófico real —vuelve concreta la pregunta por qué diferencia hace creer esto— pero le costó más malentendidos que ninguna otra frase suya, porque invita a leer el valor en términos de provecho personal. Bertrand Russell hizo con ella una parodia demoledora, y G. E. Moore y Peirce objetaron por caminos distintos. Conviene tener presente la defensa de James: conveniente quiere decir conveniente a la larga y en conjunto, y ninguna creencia que choque con la experiencia futura sigue funcionando."},
   {t:"Los múltiples yoes sociales", d:"En los Principios, James descompone el yo empírico en tres capas: el yo material (el cuerpo, la ropa, la familia, las posesiones, todo aquello cuya pérdida se siente como una disminución de uno mismo), el yo social y el yo espiritual. Y sobre el social escribe la frase que más carrera hizo: un hombre tiene tantos yoes sociales como individuos que lo reconocen y llevan una imagen de él en la mente, de modo que mostramos un lado distinto a nuestros padres, a nuestros jefes, a nuestros amigos de club y a nuestros clientes. No lo trata como hipocresía sino como estructura normal de la vida social, y observa que la división puede ser armoniosa o discordante, y que hay una violencia particular en tener que reunir en una misma escena a dos públicos ante los que somos personas distintas. Agrega su fórmula sobre la autoestima, escrita como una fracción: el éxito dividido por las pretensiones, lo que implica que la autoestima puede aumentarse tanto en el numerador como reduciendo el denominador. La idea anticipa buena parte de la sociología posterior, de Cooley y Mead hasta la presentación de la persona en la vida cotidiana de Goffman."},
   {t:"Frutos y no raíces", d:"Es la regla metodológica con la que James estudia la experiencia religiosa y mística, y sirve mucho más allá de ese tema. Dice que una experiencia no se juzga por su origen sino por sus efectos en la vida de quien la tiene: la santidad, la serenidad ante la muerte, la capacidad de sostener un sacrificio, la reorganización de una vida antes dividida. Al origen lo llama despectivamente materialismo médico cuando se lo usa como argumento: descartar la visión de un místico porque era un degenerado, o las convicciones de un reformador porque tenía mala digestión, es un procedimiento que aplicado con coherencia también invalidaría la ciencia, porque todo estado mental tiene condiciones orgánicas. Sobre la experiencia mística describe cuatro rasgos recurrentes —inefabilidad, cualidad noética, transitoriedad y pasividad— y saca una conclusión escrupulosamente acotada: esas experiencias tienen autoridad para quien las vive, no la tienen sobre quien no las tuvo, y sin embargo rompen la pretensión del racionalismo de que solo hay un tipo de acceso a lo real. La crítica más seria que recibe el libro es que, al privilegiar la experiencia individual de primera mano, trata la dimensión institucional, ritual y comunitaria de las religiones como si fuera un sedimento de segunda mano."}
 ],
 conexion:"<b>John Dewey</b> tomará esta base pragmatista y la llevará hacia la educación y la teoría democrática, reemplazando el vocabulario individual de James por el de organismo y medio. Hacia atrás, su interlocutor obligado es <b>Peirce</b>, que lo sostuvo económicamente durante años y al mismo tiempo consideró que su popularización deformaba la máxima pragmática. Y su adversario declarado en metafísica es el idealismo absoluto de Bradley y Royce, contra el que escribe <i>Un universo pluralista</i>.",
 dialogo:{titulo:"La apuesta de Clifford", lineas:[
   {quien:"Estudiante", texto:"Quiero empezar por lo que me parece más indefendible. Clifford escribió que está mal siempre, en todas partes y para cualquiera creer algo con evidencia insuficiente. Suena a higiene intelectual básica. Usted le responde que a veces se puede. ¿Cómo no es eso una licencia para creer lo que a uno le convenga?"},
   {quien:"James", texto:"Empecemos por darle a Clifford todo lo que le corresponde, que es mucho. Su ejemplo es el armador que manda al mar un barco viejo convencido, sin revisarlo, de que aguantará el viaje, y el barco se hunde con todos. Tiene razón: ese hombre es culpable, y no de un error de cálculo sino de una falta moral. En esa clase de casos suscribo su regla sin reservas."},
   {quien:"Estudiante", texto:"Entonces la discusión se termina."},
   {quien:"James", texto:"No, porque su regla pretende cubrir todos los casos y hay casos que no se parecen al del armador. Fíjese qué particular es ese ejemplo: había evidencia disponible, el hombre podía haberla buscado, la cuestión era decidible y él eligió no mirar. Mi tesis no dice nada sobre ese terreno. Habla de opciones que son a la vez vivas, forzosas y de peso vital, y que además el intelecto no puede zanjar."},
   {quien:"Estudiante", texto:"Definame esas tres palabras, porque sospecho que ahí está la trampa."},
   {quien:"James", texto:"Viva quiere decir que las dos alternativas son candidatas reales para usted; proponerle que crea en la mitología escandinava no es una opción viva, no importa qué argumentos le dé. Forzosa quiere decir que no hay una tercera salida: si le digo ámeme u ódieme, usted puede abstenerse; si le digo acepte esta verdad o quédese sin ella, no hay afuera. De peso quiere decir que algo se juega y la ocasión no se repite."},
   {quien:"Estudiante", texto:"Casi ninguna creencia mía cumple las tres cosas."},
   {quien:"James", texto:"Exactamente, y eso es lo que quería que notara. El permiso es estrecho. La caricatura me hace decir que uno puede creer lo que le resulte agradable; lo que digo es que en un puñado de encrucijadas, donde la evidencia se agotó y hay que jugar igual, nuestra naturaleza pasional no solo puede legítimamente decidir: ya está decidiendo, y lo único que cambia es si lo admitimos."},
   {quien:"Estudiante", texto:"Ahí no lo sigo. El que suspende el juicio no decide nada. Se queda quieto."},
   {quien:"James", texto:"Se queda quieto del lado de una de las dos alternativas, que es distinto. Mire las dos órdenes que nos damos como investigadores: busque la verdad y evite el error. No son la misma orden, y en ciertos casos chocan. Clifford elige la segunda: prefiere quedarse sin una verdad antes que arriesgar una falsedad. Es una elección respetable, pero es una elección, y está movida por una pasión, el miedo a equivocarse. Yo no le pido que la abandone; le pido que no la disfrace de neutralidad."},
   {quien:"Estudiante", texto:"Sigo viendo un problema. Si admito eso, cualquiera puede decir que su creencia favorita cae en la zona indecidible y quedar a salvo de la crítica."},
   {quien:"James", texto:"Ese es el punto débil y no lo voy a esconder. Quien decide si la evidencia se agotó es la misma persona que quiere creer, y no di ningún procedimiento independiente para controlarlo. Lo más que puedo ofrecer son dos exigencias: que la cuestión resista de hecho el examen intelectual, no que a usted le canse examinarla; y que después acepte las consecuencias en la experiencia, porque una creencia que choca con lo que va pasando deja de funcionar, y yo estoy obligado por mi propio pragmatismo a soltarla.", nota:"El intercambio es histórico y conviene leer los dos textos juntos: Clifford publicó La ética de la creencia en 1877 y James responde en 1896. La discusión sigue viva en la epistemología contemporánea bajo el rótulo de razones pragmáticas para creer, y hoy la mayoría de los comentaristas concede que Clifford gana el terreno público —evidencia, ciencia, decisiones que afectan a terceros— y que James gana, si gana, solo en la zona angosta que él mismo delimitó."},
   {quien:"Estudiante", texto:"Cambio de frente. Peirce, que fue su amigo, sostuvo que usted convirtió su máxima en otra cosa y terminó rebautizando su posición como pragmaticismo para no quedar pegado a usted."},
   {quien:"James", texto:"Tiene razón en el hecho, y la discusión fue filosófica, no personal: seguimos siendo amigos y yo le conseguí conferencias y dinero hasta el final. Su máxima aclara qué significa un concepto general en términos de efectos concebibles. Yo la usé además para decidir qué creencias sostener, y la apliqué a casos singulares y a la vida de una persona que no tiene tiempo infinito."},
   {quien:"Estudiante", texto:"¿Y no es eso simplemente haberla debilitado?"},
   {quien:"James", texto:"Es haber cambiado el sujeto de la pregunta. Peirce piensa en una comunidad ilimitada de investigadores y define la verdad por aquello en lo que convergerían al final de la indagación. Esa definición es más rigurosa que la mía, se lo concedo sin problema. También es inservible para alguien que tiene que decidir esta tarde si confía en alguien, si sostiene un compromiso o si vale la pena vivir. Yo escribo para ese alguien.", nota:"Aquí está la diferencia real entre los dos módulos: no es que uno haya entendido mal al otro, sino que Peirce ancla la verdad en el largo plazo de una comunidad y James en la experiencia verificable de una vida individual finita. Casi todas las objeciones clásicas a James —Russell, Moore, el propio Peirce— apuntan al costo de ese desplazamiento."},
   {quien:"Estudiante", texto:"Una última. Si la verdad es lo que funciona, ¿qué le impide a alguien llamar verdadera a una mentira cómoda?"},
   {quien:"James", texto:"El tiempo. Conveniente quiere decir conveniente a la larga y en conjunto, no cómodo esta semana. Una creencia falsa es un crédito que tarde o temprano alguien presenta al cobro, y cuando llega ese momento no paga. Si me acusan de haber escrito frases que invitan a la lectura fácil, acepto el cargo: escribí para que me leyeran, y ese fue el precio."}
 ]},
 actividades:[
   {t:"Buscar una opción viva, forzosa y de peso", d:"Identificá una encrucijada real de tu vida actual —no un ejemplo de manual— donde tengas que decidir sin que la evidencia alcance: confiar o no en alguien, sostener o abandonar un proyecto largo, aceptar o rechazar una mudanza o un trabajo, comprometerte o no con una causa. Escribila en una frase y después sometela una por una a las tres condiciones de James. ¿Las dos alternativas son vivas para vos, o una de ellas ya estaba descartada de antemano? ¿Es forzosa, o existe realmente la salida de esperar, y esperar no equivale a decidir? ¿Es de peso, o la ocasión se repite? Si tu caso falla alguna condición, James diría que ahí no tenés su permiso y que corresponde buscar más evidencia. Si las cumple las tres, escribí el párrafo difícil: ¿la justificación de James te parece correcta, o te suena a una manera elegante de llamar razonable a lo que ya querías hacer? Terminá formulando cómo te respondería Clifford, y sé justo con él."},
   {t:"Poner a prueba la teoría James-Lange en un caso propio", d:"Elegí un episodio emocional reciente y fuerte del que te acuerdes con detalle: un susto, un enojo repentino, una vergüenza, una alegría inesperada. Reconstruí la secuencia con la mayor precisión que puedas y, sobre todo, con honestidad sobre lo que realmente recordás y lo que estás reconstruyendo después. ¿Qué notaste primero: el pulso, la respiración, el calor en la cara, la tensión en el estómago, el impulso de moverte, o el sentimiento ya con nombre? Después hacé el experimento mental de James: sacale al episodio todos los componentes corporales y fijate qué queda. ¿Queda una emoción o queda un juicio frío del tipo esto es peligroso? Cerrá con la objeción de Cannon: las mismas reacciones viscerales aparecen en emociones distintas y los cambios corporales son lentos comparados con la rapidez del sentimiento. Escribí en qué medida tu propio caso apoya a James, a Cannon o a ninguno de los dos."},
   {t:"Inventario de yoes sociales", d:"Hacé una lista de los grupos ante los cuales aparecés regularmente: familia de origen, pareja, amistades de la infancia, compañeros de trabajo o de estudio, superiores, gente que apenas te conoce, redes sociales. Para cada uno anotá tres cosas concretas y verificables, no adjetivos: qué temas no aparecen nunca ahí, cómo cambia tu manera de hablar, qué parte de tu historia contás y cuál omitís. Después respondé tres preguntas. ¿Cuál de esos yoes sentís más real, y en qué te basás para decirlo, ya que James sostiene que ninguno es la máscara de otro? ¿Hay dos públicos que te resultaría violento reunir en la misma mesa, y qué dice esa incomodidad? Y por último aplicá su fórmula de la autoestima, éxito dividido por pretensiones: elegí un ámbito donde te sientas insuficiente y escribí qué cambiaría si en lugar de aumentar el numerador bajaras el denominador, y si eso sería sabiduría o resignación."}
 ],
 cuestionario:[
   {q:"Clifford sostiene que está mal siempre, en todas partes y para cualquiera creer algo con evidencia insuficiente. James responde que en ciertos casos es legítimo. ¿Quién tiene la mejor parte del intercambio?", p:"Conviene separar los terrenos, porque cada uno gana en uno distinto. Clifford gana claramente donde hay evidencia disponible, donde la cuestión es decidible y donde la creencia afecta a terceros: su ejemplo del armador que despacha un barco podrido es imbatible, y la ética de la investigación, la salud pública y el periodismo funcionan con su regla y no con la de James. Su punto más fuerte es que las creencias no son privadas, que forman el patrimonio común del que actuamos todos, y que creer mal daña a otros aunque uno no lo note. James gana en dos puntos concretos. El primero es que la regla de Clifford, aplicada literalmente, es autodestructiva: la propia regla no se sostiene sobre evidencia suficiente, y nuestras creencias más básicas —la confianza en la inducción, en la memoria, en la fiabilidad de otros— tampoco. El segundo es que el escepticismo no es una posición neutral, sino la elección de una de las dos órdenes que rigen la investigación, evitar el error antes que alcanzar la verdad, y esa elección tampoco se demuestra. El saldo honesto es un empate desigual: Clifford tiene razón en casi todo el territorio, James tiene razón en que ese casi no es un todo, y buena parte de la discusión posterior consistió en pelear por el tamaño exacto de la excepción. La objeción que James nunca respondió del todo es quién certifica que una cuestión es de verdad indecidible, cuando el juez es la misma persona que desea creer."},
   {q:"Si lo verdadero es lo que funciona, ¿no se derrumba la verdad en utilidad, y de ahí en pensar lo que uno quiere?", p:"Es la objeción estándar y la formularon Russell, Moore y Lovejoy con más ingenio que caridad. Pero conviene examinarla despacio, porque la versión popular es una simplificación que James no sostiene. Su tesis no es que una creencia sea verdadera porque me conviene, sino que llamamos verdadera a la idea que resiste el proceso de verificación en la experiencia, y que llamar a eso correspondencia estática no explica nada: decir que una idea concuerda con la realidad es prometer algo, y el pragmatismo pregunta en qué consiste concretamente cumplir esa promesa, es decir, qué cadena de experiencias nos conduce del pensamiento al objeto. Agrega dos restricciones que se suelen omitir: conveniente significa conveniente a la larga y en conjunto, no cómodo hoy, y una idea no puede funcionar en contra del resto del cuerpo de creencias ya verificadas. Con eso responde a la caricatura de que bastaría con creer algo agradable. Lo que la objeción conserva es un núcleo duro que James no desactivó: hay creencias falsas que funcionan durante toda una vida y nunca son presentadas al cobro, y hay verdades que no le sirven a nadie. Mientras la verificación quede como criterio y no solo como síntoma, sigue faltando la explicación de qué hace verdadera a una proposición sobre la que nadie actuará jamás. Russell lo resumió con crueldad preguntando si la afirmación Papá Noel existe se vuelve verdadera cuando creerla produce felicidad."},
   {q:"James y Peirce no pueden tener los dos razón. ¿La verdad se define por la convergencia de una comunidad ilimitada o por lo que verifica una vida individual?", p:"La tensión es real y no se resuelve diciendo que se complementan. Peirce define lo verdadero como la opinión destinada a ser aceptada por todos los que investigan, lo que le da tres ventajas: la verdad no depende de nadie en particular, es compatible con que todos los vivos se equivoquen, y explica por qué la convergencia ocurre, a saber, porque lo real resiste. Su costo es la inutilidad práctica: una verdad definida en un límite ideal no orienta a quien debe decidir hoy, y hay cuestiones sobre las que la indagación podría no converger jamás. James define lo verdadero por el proceso de verificación en la experiencia de agentes concretos y finitos, lo que le da la ventaja inversa —dice algo sobre el presente, se aplica a la vida práctica y a la religión— al costo de acercar peligrosamente la verdad a la satisfacción del individuo, que es justamente lo que Peirce llamaba el método a priori, creer lo que resulta agradable a la razón. Hay tres salidas posibles y ninguna es cómoda. Una es sostener que James solo describía la marca o el síntoma por el cual reconocemos verdades, y Peirce su definición, con lo cual el conflicto se disuelve pero James pierde lo que quería afirmar. Otra es la de Dewey, que reemplaza el problema: deja de hablar de verdad y habla de asertabilidad garantizada, obtenida por una comunidad en una investigación concreta. La tercera es admitir que el pragmatismo nunca fue una escuela unificada sino una familia con un método compartido y teorías de la verdad incompatibles, que es probablemente lo más exacto."},
   {q:"¿Sigue en pie la teoría James-Lange de la emoción, casi ciento cuarenta años después?", p:"La historia es más interesante que un simple sí o no, y conviene contarla en tres tiempos. Primer tiempo: en los años veinte Walter Cannon la ataca con cinco objeciones que parecieron letales —separar quirúrgicamente las vísceras del sistema nervioso central no elimina la conducta emocional, las mismas respuestas viscerales aparecen en emociones distintas, las vísceras son poco sensibles y responden con lentitud, y la inyección de adrenalina produce cambios corporales sin emoción genuina— y propone junto a Bard una explicación centrada en el tálamo. Durante décadas el manual repitió que James estaba refutado. Segundo tiempo: Schachter y Singer muestran en 1962 que la activación fisiológica es real pero necesita una interpretación cognitiva del contexto para convertirse en una emoción determinada, lo que rescata la mitad corporal de James sin devolverle la teoría entera. Tercer tiempo: desde los años noventa, Antonio Damasio reintroduce el cuerpo en el centro con la hipótesis del marcador somático y el concepto de bucle corporal, y la investigación en interocepción muestra que la percepción del estado interno modula fuertemente el sentimiento; los estudios sobre retroalimentación facial y sobre pacientes con lesiones medulares dan resultados mixtos y a menudo débiles. Hoy la posición mayoritaria es que James acertó en que el cuerpo es constitutivo y no un mero acompañamiento, y se equivocó en creer que cada emoción tiene un patrón visceral específico y suficiente. Las teorías construccionistas de Lisa Feldman Barrett llevan esa corrección más lejos aún. No es una teoría refutada ni vigente: es una hipótesis parcialmente absorbida."},
   {q:"Cuando James dice que experimentamos directamente las relaciones entre las cosas, ¿hace un descubrimiento empírico o amplía por decreto la palabra experiencia?", p:"La sospecha está bien planteada y es la objeción central al empirismo radical. A favor de que se trata de un hallazgo descriptivo: James ofrece casos concretos que cualquiera puede revisar en su propia experiencia, como el sentimiento de pero o de si, la expectativa de una palabra que está por venir y la sensación de que un razonamiento va hacia alguna parte antes de que llegue. Su argumento es que el empirismo clásico no describió la experiencia sino que la recortó de antemano según un supuesto atomista heredado, y que luego tuvo que inventar mecanismos —la asociación en Hume, las categorías en Kant, el Absoluto en los idealistas— para reponer unas conexiones que nunca habían faltado. Si eso es correcto, la ampliación no es un decreto sino la corrección de un recorte arbitrario. En contra: el término experiencia hace en James un trabajo enorme y variable, y cuando se dice que la relación de causalidad se experimenta directamente cuesta distinguir eso de decir que se la juzga rápido y con confianza; además, el criterio no permite adjudicar los casos difíciles, que son precisamente los que la tradición discute, ni explica por qué a veces percibimos conexiones que no existen. Hay un modo de avanzar sin decidir a ciegas: tratar la tesis como una hipótesis con consecuencias contrastables sobre la percepción. La psicología de la Gestalt, los trabajos de Michotte sobre la percepción de la causalidad en los años cuarenta y buena parte de la fenomenología posterior fueron en esa dirección y dieron a James más apoyo del que sus críticos lógicos esperaban, aunque sin llegar a saldar la discusión."}
 ],
 cadena:{ titulo:"¿Es inmoral creer sin pruebas suficientes?", intro:"Un razonamiento en ramas sobre la polémica entre W. K. Clifford y William James. Clifford sostuvo que es incorrecto, siempre y en todas partes, creer algo con evidencia insuficiente. James le respondió en «La voluntad de creer» (1896). Las ramas recorren las condiciones de James, el caso del armador y los límites de su doctrina.", inicio:"n1", nodos:{
   n1:{ pregunta:"Clifford cuenta el caso de un armador que acalla sus dudas sobre un barco viejo, se convence de que es seguro y lo deja zarpar con inmigrantes; el barco se hunde. Concluye que creer con evidencia insuficiente es siempre incorrecto. ¿Qué pensás?", opciones:[
     {texto:"Clifford tiene razón: ante la duda, hay que suspender el juicio, siempre.", va:"n2a"},
     {texto:"Depende del tipo de decisión: no todos los casos son como el del armador.", va:"n2b"} ]},
   n2a:{ pregunta:"James responde que la regla de Clifford no es neutral: prefiere evitar el error antes que ganar la verdad, y esa preferencia también es una pasión. ¿Suspender el juicio es siempre una manera de no decidir?", opciones:[
     {texto:"Sí: no creer no compromete a nada.", final:{tipo:"revisar", texto:"James muestra que no siempre. Hay opciones forzosas, donde no decidir tiene las mismas consecuencias que decidir que no: si espero a tener pruebas de que alguien va a ser mi amigo antes de tratarlo como amigo, nunca lo va a ser. El escepticismo, en esos casos, también es una apuesta: la de perder la verdad antes que arriesgar el error. Volvé un paso y probá la otra respuesta."}},
     {texto:"No: en algunas opciones, no decidir equivale a decidir que no.", va:"n3a"} ]},
   n3a:{ pregunta:"James acota cuándo vale su doctrina: la opción tiene que ser viva (las dos alternativas te resultan creíbles), forzosa (no hay una tercera salida) y trascendental (está en juego algo importante), y además la evidencia no tiene que poder decidirla. Con esas condiciones, ¿qué permite?", opciones:[
     {texto:"Que la pasión decida legítimamente; por ejemplo, confiar en alguien antes de que esa confianza esté probada, cuando la confianza misma ayuda a que se cumpla.", final:{tipo:"bien", texto:"Es el caso más defendible de James: hay hechos que no ocurren si nadie cree antes en ellos —una amistad, un equipo, una empresa entre socios—. La fe en un hecho puede ayudar a crearlo. En esos casos, exigir pruebas previas no es prudencia, es asegurarse de que el hecho no ocurra."}},
     {texto:"Que se crea lo que uno quiera, mientras sea importante para uno.", final:{tipo:"revisar", texto:"Te quedaste con la tercera condición y soltaste la cuarta. James no autoriza a creer lo que uno quiere cuando la evidencia puede decidir: lo dice expresamente, y por eso su texto no es un permiso para el autoengaño. Además, la opción tiene que ser forzosa, y la mayoría de las cosas importantes admiten esperar. Volvé un paso y revisá las condiciones."}} ]},
   n2b:{ pregunta:"Volvamos al armador de Clifford. Según la doctrina de James, ¿quedaría excusado?", opciones:[
     {texto:"No: la cuestión podía decidirse con evidencia —inspeccionar el barco—, así que no se aplica la voluntad de creer.", va:"n3b"},
     {texto:"Sí: la decisión era forzosa e importante.", final:{tipo:"revisar", texto:"No era forzosa: el armador podía postergar el viaje o hacer revisar el barco. Y sobre todo, la evidencia estaba disponible; él eligió no buscarla. James estaría de acuerdo con Clifford en este caso. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Si el armador queda afuera, ¿dónde se aplica legítimamente la voluntad de creer?", opciones:[
     {texto:"En la hipótesis religiosa, que es el caso en el que James estaba pensando.", final:{tipo:"bien", texto:"Es fiel al texto: el ensayo se escribió sobre todo para defender el derecho a la fe religiosa frente al agnosticismo de Clifford. Las críticas más fuertes apuntan ahí: la opción religiosa no es una sola —¿qué religión?—, así que no es claro que sea forzosa, y muchos sostienen que la evidencia sí es relevante para ella. Ganás fidelidad histórica; tenés que defender que la opción religiosa cumple de verdad las cuatro condiciones."}},
     {texto:"En los casos en que la fe ayuda a crear el hecho: la confianza, la cooperación, el coraje.", final:{tipo:"bien", texto:"Es la aplicación menos discutida y la más útil fuera de la religión. James da el ejemplo de los pasajeros de un tren asaltado por pocos bandidos: si cada uno confiara en que los demás se van a levantar, el robo no ocurriría. Ahí la creencia no es una apuesta sobre un hecho que ya está, sino parte de lo que lo produce."}} ]}
 }},
 reconstruccion:[
   { titulo:"La ardilla y el árbol (Pragmatismo, segunda conferencia)",
     consigna:"Reconstruí cómo James usa una discusión de campamento para presentar el método pragmático. Una pieza generaliza el método más allá de lo que James dice: dejala afuera.",
     piezas:[
       {id:"s1", texto:"Una ardilla se aferra al tronco de un árbol; un hombre da la vuelta al árbol, y la ardilla se mueve al mismo ritmo, siempre con el tronco en el medio. ¿Da el hombre la vuelta a la ardilla?", tipo:"premisa"},
       {id:"s2", texto:"Si «dar la vuelta» significa pasar por el norte, el este, el sur y el oeste de la ardilla, sí; si significa estar delante, al costado y detrás de ella, no.", tipo:"premisa"},
       {id:"s3", texto:"Una vez distinguidos los dos sentidos, no queda ninguna diferencia práctica sobre la que discutir: los dos bandos tenían razón, cada uno en su sentido.", tipo:"premisa"},
       {id:"s4", texto:"Por lo tanto, ante una disputa hay que preguntar qué diferencia práctica concreta haría que una u otra posición fuera verdadera; si no hay ninguna, la disputa es ociosa.", tipo:"conclusion"},
       {id:"sx", texto:"Por lo tanto, todas las disputas metafísicas son puramente verbales y carecen de sentido.", tipo:"distractor"}
     ],
     ordenCorrecto:["s1","s2","s3","s4"],
     explicacion:"El ejemplo es trivial a propósito: muestra el método en un caso donde todos pueden ver que la discusión era de palabras. El punto débil está en el salto de s3 a s4: en la ardilla, distinguir sentidos disuelve la disputa; pero de ahí no se sigue que el significado de toda afirmación se agote en sus consecuencias prácticas. Hay afirmaciones sobre el pasado remoto, por ejemplo, que parecen tener sentido sin consecuencias para nadie. La pieza sobrante exagera: James aplica el método justamente para distinguir las disputas metafísicas que tienen diferencias prácticas —en la tercera conferencia sostiene que materialismo y teísmo sí las tienen, hacia el futuro— de las que no."},
   { titulo:"La verdad le sucede a una idea (Pragmatismo, sexta conferencia)",
     consigna:"Reconstruí la teoría pragmatista de la verdad tal como la expone James. Una pieza recoge la caricatura que le hicieron sus críticos: dejala afuera.",
     piezas:[
       {id:"v1", texto:"El pragmatismo pregunta qué diferencia concreta hace, en la vida de alguien, que una idea sea verdadera.", tipo:"premisa"},
       {id:"v2", texto:"La respuesta: las ideas verdaderas son las que podemos asimilar, validar, corroborar y verificar; las falsas, las que no.", tipo:"premisa"},
       {id:"v3", texto:"La verificación es un proceso: la verdad le sucede a una idea, que se vuelve verdadera por los acontecimientos.", tipo:"premisa"},
       {id:"v4", texto:"La mayoría de las verdades viven a crédito: las aceptamos sin verificarlas mientras nada las contradiga, como se acepta un billete mientras nadie lo rechaza.", tipo:"premisa"},
       {id:"v5", texto:"Por lo tanto, la verdad no es una copia estática de la realidad, sino lo que nos guía satisfactoriamente en la experiencia: lo verdadero es lo conveniente en nuestro modo de pensar, a la larga y en conjunto.", tipo:"conclusion"},
       {id:"vx", texto:"Por lo tanto, una idea es verdadera si me hace sentir bien creerla.", tipo:"distractor"}
     ],
     ordenCorrecto:["v1","v2","v3","v4","v5"],
     explicacion:"El argumento traduce la verdad a su función en la experiencia. El punto débil es v3: si la verdad le sucede a una idea cuando se verifica, ¿era falsa la idea de que César cruzó el Rubicón antes de que alguien lo verificara? James responde que la verdad se va haciendo y que hablamos de verdades a crédito, pero la objeción sigue siendo seria. La pieza sobrante es la lectura que hicieron Russell y Moore, y que James rechazó: «conveniente», para él, quiere decir conveniente a la larga y en conjunto, en concordancia con la realidad y con el resto de nuestras verdades, no agradable para quien cree."}
 ],
 dilemas:[
   { titulo:"La sociedad con Camilo",
     intro:"James sostiene que hay hechos que no ocurren si nadie cree antes en ellos, y que en esos casos exigir pruebas previas no es prudencia, sino una manera de asegurar el fracaso. Este caso pone a prueba esa idea donde más se juega: cuando hay dinero y amistad de por medio.",
     pasos:[
       { id:"p1", situacion:"Camilo, tu amigo de la universidad, te propone montar juntos una empresa de asesoría financiera para tiendas de barrio en Ibagué. Tiene experiencia comercial; vos sabés de finanzas. No hay forma de saber de antemano si la sociedad va a funcionar. ¿Qué hacés?", opciones:[
         {texto:"Espero a tener pruebas suficientes de que va a funcionar antes de entrar.", consecuencia:"Es la regla de Clifford. El problema es que la prueba que pedís —que la sociedad funcione— solo existe si la sociedad empieza. Para James, es una opción forzosa: esperar indefinidamente equivale a decir que no.", va:"p2"},
         {texto:"Me lanzo con todo: si creo en el proyecto, el proyecto va a funcionar.", consecuencia:"Tomaste la mitad de James. La confianza puede ayudar a crear el hecho, pero James no autoriza a ignorar la evidencia que sí está disponible: el mercado, los costos, la experiencia de Camilo con otros socios. Eso se puede averiguar, y lo que se puede averiguar no se decide con la voluntad.", va:"p2"},
         {texto:"Averiguo lo que se puede averiguar y, para lo que no, confío: empezamos con un piloto de tres meses y pocas tiendas.", consecuencia:"Separaste lo que decide la evidencia (el mercado, las cuentas) de lo que solo puede decidir la confianza (si la sociedad entre ustedes va a funcionar). Es la aplicación más fiel de James, y el piloto agrega algo de Peirce y de Dewey: convertir la apuesta en un experimento.", va:"p2"} ]},
       { id:"p2", situacion:"A los seis meses, los números son ambiguos: hay clientes, pero el flujo de caja es apretado. Camilo te pide que pongan más capital cada uno y te dice: «Necesito que creas en esto conmigo». ¿Qué hacés?", opciones:[
         {texto:"Pongo el dinero: la confianza en el socio es parte de lo que hace funcionar la empresa.", consecuencia:"Es la voluntad de creer, pero fijate si se cumplen las condiciones. El flujo de caja no es una cuestión que la evidencia no pueda decidir: se pueden proyectar las cuentas. Usar la fe donde hay números disponibles es lo que James no permite.", va:"p3"},
         {texto:"Antes de decidir, revisamos juntos la proyección del flujo de caja; la confianza va donde los números no llegan.", consecuencia:"Mantuviste la distinción del comienzo. Lo que James defiende es creer donde la evidencia no puede decidir, no en lugar de buscarla. Además, revisar las cuentas juntos es una forma de cuidar la confianza, no de negarla.", va:"p3"},
         {texto:"Me retiro: «Necesito que creas» es una señal de alarma.", consecuencia:"Puede ser prudente. Pero notá que James te preguntaría si la frase de Camilo es una señal de alarma o una descripción exacta de cómo funcionan las sociedades: ninguna sobrevive sin que sus miembros confíen unos en otros más allá de lo que pueden probar.", va:"p3"} ]},
       { id:"p3", situacion:"Un año después, una amiga que está por asociarse con alguien te pide un consejo. ¿Qué le decís?", opciones:[
         {texto:"«Confiá en tu instinto: si lo sentís, va a funcionar.»", consecuencia:"Es la versión de autoayuda de James. Le falta la condición más importante: que la evidencia no pueda decidir. El instinto sirve para lo que no se puede averiguar, no para ahorrarse averiguarlo.", va:null},
         {texto:"«Averiguá todo lo que se pueda averiguar, y en lo que no se pueda, decidí si estás dispuesta a creer primero.»", consecuencia:"Es «La voluntad de creer» completa: evidencia donde la hay, y una decisión consciente, sin autoengaño, donde no la hay.", va:null},
         {texto:"«No te asocies con nadie hasta estar segura.»", consecuencia:"Es Clifford llevado a los negocios, y garantiza que nunca te equivoques al asociarte, porque nunca te vas a asociar. James diría que eso también tiene un costo: perder la verdad por miedo al error.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar la diferencia entre la regla de Clifford y la posición de James con el caso del armador.",
       "Comprobé si mi decisión cumplía las condiciones de James: opción viva, forzosa, trascendental e indecidible con evidencia.",
       "Distinguí lo que se podía averiguar (el mercado, el flujo de caja) de lo que solo podía decidir la confianza.",
       "Entendí por qué, en algunas decisiones, esperar pruebas equivale a decir que no.",
       "Evité usar la voluntad de creer como excusa para no mirar los números.",
       "Pensé cómo convertir una apuesta en un experimento que me diera evidencia.",
       "Formulé la objeción más fuerte: que la gente rara vez sabe distinguir cuándo la evidencia no alcanza y cuándo simplemente no quiere buscarla."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.james = { lecturas:[
 {titulo:"Pragmatismo (1907): la ardilla, el método y la verdad que «funciona»", fuente:"Pensamiento Penal — El pragmatismo, William James (PDF)", url:"https://www.pensamientopenal.com.ar/system/files/2014/12/doctrina39204.pdf",
  extracto:`James abre la segunda conferencia con una anécdota de campamento. Un grupo discute acaloradamente sobre una ardilla que se aferra a un tronco y siempre mantiene el árbol entre ella y un hombre que gira alrededor. La pregunta: ¿el hombre da la vuelta alrededor de la ardilla o no? El grupo está dividido en dos bandos irreconciliables. James propone: «depende de lo que prácticamente queráis decir con dar la vuelta alrededor de la ardilla. Si queréis decir pasar del norte al este, luego al sur, luego al oeste y de nuevo al norte de ella, evidentemente el hombre da la vuelta. Pero si queréis decir estar primero delante de ella, luego a su derecha, luego detrás, luego a su izquierda, entonces evidentemente el hombre no da la vuelta».

De ahí extrae el método pragmático: «el método pragmático es, ante todo, un método para zanjar disputas metafísicas que de otro modo serían interminables. ¿Es el mundo uno o múltiple? ¿Es determinado o libre? ¿Material o espiritual? El método pragmático en tales casos consiste en tratar de interpretar cada noción rastreando sus respectivas consecuencias prácticas. Si no se puede rastrear ninguna diferencia práctica, entonces las alternativas significan prácticamente lo mismo, y toda disputa es vana».

James toma esto de Peirce pero enseguida lo lleva más lejos que él. Define las teorías no como respuestas a enigmas sino como instrumentos: «las teorías se convierten así en instrumentos, no en respuestas a enigmas sobre las cuales podamos descansar». Y agrega la imagen del corredor: el pragmatismo «no representa resultados especiales, sino solo un método»; es «un corredor en un hotel» al que dan innumerables habitaciones — en una hay un hombre escribiendo un tratado ateo, en otra alguien reza de rodillas, en otra un químico investiga — y todos deben pasar por el corredor para entrar y salir.

En la sexta conferencia formula su teoría de la verdad. Parte de una definición que acepta como punto de partida: la verdad es la concordancia de nuestras ideas con la realidad. Pero pregunta qué significa concordar. «Las ideas verdaderas son aquellas que podemos asimilar, hacer válidas, corroborar y verificar. Las ideas falsas son aquellas con las que no podemos hacerlo. La verdad de una idea no es una propiedad estancada inherente a ella. La verdad ACONTECE a una idea. Se hace verdadera, es hecha verdadera por los acontecimientos.» Y luego la frase que más críticas le costó: «lo verdadero, para decirlo brevemente, es solo lo conveniente en nuestra manera de pensar, así como lo correcto es solo lo conveniente en nuestra manera de comportarnos».

James anticipa la acusación de subjetivismo y responde que «conveniente» significa conveniente a largo plazo y en conjunto, no cómodo hoy: una creencia que choque con la experiencia futura dejará de funcionar. También introduce la distinción entre el «crédito» y el «pago en efectivo» de las ideas: vivimos de creencias verificables que no verificamos personalmente, como quien usa billetes sin ir al banco, pero el sistema entero se apoya en que en algún punto la verificación sea posible.

En La voluntad de creer completa el cuadro para los casos que la evidencia no decide. Cuando una opción es «viva, forzosa y de peso», y no puede resolverse por medios intelectuales, «nuestra naturaleza pasional no solo puede legítimamente, sino que debe decidir entre proposiciones». Suspender el juicio no es neutral: también es una apuesta, y en ciertos casos —la confianza en otro, el compromiso con una causa— creer es condición para que el hecho creído se vuelva verdadero.`,
  comentario:"La anécdota de la ardilla es la mejor entrada posible al método: muchas disputas filosóficas se disuelven al precisar qué diferencia práctica está en juego. Lo importante al comparar con Peirce es que James convierte un criterio de SIGNIFICADO en un criterio de VERDAD, y ahí está el origen de casi todas las objeciones que recibió. Su defensa —que «conveniente» se mide a largo plazo— es exactamente la respuesta a la pregunta del cuestionario."}
], preguntasLectura:[
 {q:"¿Cómo resuelve James la disputa de la ardilla?", opciones:["Dando la razón al primer bando","Mostrando que «dar la vuelta» tiene dos sentidos prácticos distintos","Midiendo la trayectoria del hombre","Declarando la pregunta insoluble"], r:"Mostrando que «dar la vuelta» tiene dos sentidos prácticos distintos", why:"Es la ilustración del método pragmático: precisar la diferencia práctica disuelve la disputa verbal."},
 {q:"Según James, ¿qué relación tiene la verdad con el tiempo?", opciones:["La verdad es eterna e inmutable","La verdad «acontece» a una idea: es hecha verdadera por los acontecimientos","La verdad se decide por votación","La verdad depende solo de la lógica"], r:"La verdad «acontece» a una idea: es hecha verdadera por los acontecimientos", why:"Para James la verdad no es una propiedad estancada sino un proceso de verificación."},
 {q:"En «La voluntad de creer», ¿cuándo tenemos derecho a creer sin evidencia suficiente?", opciones:["Siempre que nos resulte agradable","Cuando la opción es viva, forzosa y de peso, y el intelecto no puede decidirla","Nunca, bajo ninguna circunstancia","Cuando lo aprueba la comunidad científica"], r:"Cuando la opción es viva, forzosa y de peso, y el intelecto no puede decidirla", why:"James subraya además que suspender el juicio tampoco es neutral: también es una apuesta."}
]};
