/* ============================================================
   Ficha: peirce  ·  tradición: americana
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"peirce", trad:"americana", nombre:"Charles Sanders Peirce", fechas:"1839–1914 · EE. UU.", escuela:"Pragmatismo (fundador)", icon:"🔬", profundizada:true,
 tesis:"El significado de un concepto se agota en sus efectos prácticos concebibles. La verdad es aquello en lo que convergería idealmente una comunidad de investigadores tras indagación indefinida.",
 obras:[
   {t:"La fijación de la creencia", d:"Primer ensayo de la serie Illustrations of the Logic of Science, publicado en Popular Science Monthly en 1877. No arranca por la verdad sino por un hecho psicológico y social: la duda es un estado incómodo del que queremos salir, y la creencia un estado de calma que establece un hábito de acción. Desde ahí compara cuatro métodos históricamente reales para fijar creencias —tenacidad, autoridad, a priori y el método científico— y los evalúa no por su nobleza sino por su capacidad de producir creencias que no se derrumben al chocar con la experiencia o con otras personas. El giro decisivo es que el método científico se elige por una razón pragmática y no por una garantía metafísica: es el único que incorpora un mecanismo de autocorrección. Conviene leerlo antes que el ensayo famoso de 1878, porque la máxima pragmática es la continuación técnica de este planteo."},
   {t:"Cómo esclarecer nuestras ideas", d:"Segundo ensayo de la misma serie, de 1878, donde Peirce ataca de frente la herencia cartesiana de las ideas claras y distintas: la claridad cartesiana, dice, es familiaridad subjetiva, y la distinción es solo la capacidad de dar una definición verbal. Ninguna de las dos asegura que sepamos de qué hablamos. Propone entonces un tercer grado de claridad, la máxima pragmática, y la pone a prueba con conceptos concretos —duro, pesado, fuerza— y con la disputa teológica sobre la transubstanciación, donde ambas partes esperan del vino exactamente los mismos efectos sensibles. El texto termina definiendo lo real como aquello sobre lo que la investigación llevada suficientemente lejos haría converger a todos, lo que convierte un criterio de significado en una teoría de la verdad. Es el acta de nacimiento del pragmatismo, aunque Peirce no usa allí la palabra en público."},
   {t:"Escritos de lógica de los signos", d:"No hay un libro de semiótica de Peirce: hay cuarenta años de manuscritos, cartas —sobre todo la correspondencia con Victoria Welby— y borradores donde va construyendo la teoría general de los signos como una rama de la lógica, no de la lingüística. Su núcleo es que la significación es irreductiblemente triádica: un signo está por un objeto para un interpretante, y esa relación de tres términos no se descompone en pares. De ahí sale la tricotomía más citada, icono, índice y símbolo, según el signo se vincule a su objeto por semejanza, por conexión física real o por hábito convencional. Peirce multiplicó las clasificaciones hasta llegar a sesenta y seis clases de signos que nunca terminó de ordenar, y esa exuberancia inacabada es tan característica de su obra como la potencia de la idea inicial, que reaparecerá en la lingüística, la semiótica literaria y la filosofía de la mente del siglo XX."},
   {t:"Collected Papers", d:"Recopilación póstuma en ocho volúmenes, publicada entre 1931 y 1958, que reunió una fracción de los más de cien mil folios manuscritos que Peirce dejó al morir en la pobreza. Conviene ser honesto sobre lo que es: no un sistema que el autor haya publicado, sino un montaje hecho por editores que agruparon fragmentos de décadas distintas por temas, cortando textos y mezclando versiones incompatibles entre sí. Peirce publicó en vida ensayos, reseñas y trabajos científicos, pero nunca el gran libro de lógica que proyectó una y otra vez. Eso explica dos cosas a la vez: por qué su influencia fue tan tardía, y por qué cualquier exposición ordenada de su pensamiento, incluida esta ficha, es en parte una reconstrucción de los intérpretes. La edición cronológica moderna (Writings of Charles S. Peirce) existe justamente para corregir ese problema."},
   {t:"Investigaciones fotométricas y trabajos geodésicos", d:"Peirce trabajó más de treinta años en el United States Coast and Geodetic Survey midiendo la gravedad con péndulos, y publicó en 1878 Photometric Researches, su único libro en vida, sobre el brillo de las estrellas. Fue además el primero en proponer definir el metro a partir de una longitud de onda de la luz. Esto no es una anécdota biográfica: es la fuente de su epistemología. Quien pasa décadas corrigiendo errores sistemáticos de instrumentos, comparando mediciones de distintos observatorios y publicando márgenes de error, aprende en la práctica que ninguna medición es exacta, que el conocimiento lo produce una comunidad que se corrige y que un concepto vale lo que valen las operaciones que permite. El falibilismo y la comunidad de investigadores salieron del laboratorio antes que del escritorio."}
 ],
 conceptos:[
   {t:"Máxima pragmática", d:"Formulada en 1878: consideremos qué efectos, que puedan tener concebiblemente repercusiones prácticas, concebimos que tenga el objeto de nuestra concepción; nuestra concepción de esos efectos es la totalidad de nuestra concepción del objeto. Es una regla de clarificación, no una teoría de la verdad ni una definición de lo útil. Dice que si dos supuestas ideas no difieren en ningún efecto concebible, no son dos ideas sino una sola con dos nombres, y que la disputa entre ellas es verbal. Dos precisiones que suelen perderse: los efectos son concebibles, no efectivamente observados, de modo que la máxima no exige verificación actual; y la máxima se aplica a conceptos generales, no a hechos singulares. Con ella Peirce no elimina la metafísica, la depura."},
   {t:"Los cuatro métodos para fijar la creencia", d:"La tenacidad consiste en aferrarse a lo que uno ya cree y evitar toda información contraria: funciona hasta que aparece alguien que cree lo opuesto y la duda vuelve. La autoridad delega la creencia en una institución que la impone: es el método más eficaz históricamente, dice Peirce sin ironía, pero ninguna autoridad puede regular todas las cuestiones y siempre hay quien compara con otras épocas o pueblos. El método a priori acepta lo que resulta agradable a la razón, y produce filosofía que oscila como un péndulo entre modas intelectuales, porque en el fondo también decide por gusto. Solo el cuarto método, el científico, supone que hay cosas reales cuyos caracteres son independientes de lo que opinemos, y por eso permite que la creencia sea corregida por algo externo al creyente. Su superioridad no es que garantice acertar, sino que es el único que puede descubrir que se equivocó."},
   {t:"Indagación y duda genuina", d:"La indagación es la lucha por pasar de la duda a la creencia, y solo empieza cuando hay una duda real, viva, que efectivamente irrita y paraliza la acción. Aquí Peirce rompe explícitamente con Descartes: la duda metódica universal es, para él, una duda de papel, una ceremonia. Nadie duda de verdad de la existencia de su propio cuerpo por haber leído un argumento; declarar que se duda no es dudar, igual que escribir la palabra fuego no incendia nada. De esa crítica sale un programa distinto: no hay un punto cero desde el que fundar el saber, siempre partimos de un enorme fondo de creencias heredadas que no cuestionamos porque no tenemos motivo, y la crítica es local, se ejerce sobre aquello que un choque concreto con la experiencia puso en cuestión. La filosofía, dirá, no debe pretender dudar en su estudio de lo que no duda en la calle."},
   {t:"Semiótica triádica", d:"Un signo es algo que está por un objeto para alguien, es decir, produce en un intérprete otro signo equivalente o más desarrollado al que Peirce llama interpretante. La relación tiene tres términos y es irreductible: no se explica como una relación entre signo y objeto más otra entre signo e intérprete. Como el interpretante es a su vez un signo que pide otro interpretante, la significación es un proceso abierto, la semiosis, que no se detiene en un significado último. La tricotomía más usada clasifica al signo por su relación con el objeto: el icono se parece a él (un plano, un diagrama, una ecuación), el índice está realmente conectado con él (el humo, una huella, una veleta, la palabra esto) y el símbolo lo representa por un hábito o convención (casi todas las palabras). La mayoría de los signos reales mezclan los tres aspectos, y saber cuál domina es lo que hace útil la clasificación."},
   {t:"Falibilismo", d:"Ninguna creencia, ni siquiera la mejor establecida de la ciencia, es absolutamente cierta: toda afirmación queda abierta a revisión, y los números que damos son siempre aproximaciones con un margen. Peirce lo extiende incluso a la matemática y a la lógica en cuanto ejercidas por seres humanos falibles. Lo importante es que el falibilismo no es escepticismo: no dice que no sepamos nada, dice que lo que sabemos lo sabemos sin garantía última y que por eso la investigación debe seguir abierta. Su enemigo declarado es el bloqueo del camino de la indagación, que para él es el único pecado filosófico imperdonable, y se comete tanto al afirmar que ya se alcanzó la verdad final como al declarar que algo es incognoscible por principio."},
   {t:"Comunidad de investigadores", d:"La verdad es la opinión destinada a ser finalmente aceptada por todos los que investigan, y lo real es el objeto representado en esa opinión. La definición desplaza la verdad del individuo al proceso: nadie la posee, y sin embargo no es arbitraria, porque la convergencia la produce la resistencia de las cosas y no un acuerdo entre personas. Peirce agrega un componente casi ético: el investigador debe estar dispuesto a subordinar su interés al de una comunidad ilimitada que se extiende más allá de su vida y de su época, lo que convierte la lógica en una cuestión de carácter tanto como de método. La idea permite ser falibilista sin ser relativista, pero paga un precio que él acepta: la verdad queda definida por un límite ideal que quizá nunca se alcance."},
   {t:"Realismo escolástico", d:"Contra el nominalismo dominante en la modernidad, Peirce sostiene que los generales son reales. Se declaró seguidor de Duns Escoto y usó esa etiqueta medieval a propósito, en pleno siglo XIX, para marcar distancia. La tesis no es que exista un mundo platónico de universales separados, sino algo más sobrio y más raro: las leyes, las disposiciones y los hábitos son reales porque son efectivos, hacen diferencia en cómo se comportan las cosas. Que este diamante sea duro significa que resistiría el rayado si se lo intentara, y ese condicional es verdadero aunque nadie lo pruebe nunca; si negamos la realidad de lo que ocurriría, no queda nada que las leyes de la naturaleza describan. Peirce vio que su propia máxima pragmática, entendida en clave nominalista, se degradaría en la doctrina de que solo lo efectivamente experimentado significa algo, y dedicó buena parte de su obra tardía a bloquear esa lectura."},
   {t:"Abducción", d:"Es su aporte más original a la lógica: junto a la deducción, que extrae lo que ya está contenido en las premisas, y a la inducción, que generaliza a partir de casos, hay un tercer tipo de inferencia que introduce ideas nuevas. Su forma es: se observa un hecho sorprendente; ahora bien, si la hipótesis H fuera verdadera, ese hecho sería una consecuencia natural; luego hay razón para sospechar que H es verdadera. Solo la abducción amplía el conocimiento, porque es el único momento en que aparece una explicación que antes no estaba; la deducción extrae sus consecuencias y la inducción las pone a prueba, de modo que las tres forman un ciclo. Peirce era consciente de que la conclusión abductiva es débil y falible, y de que su verdadero problema es la economía de la investigación: dado que las hipótesis posibles son infinitas, lo decisivo es qué hace que a un investigador se le ocurra justamente la buena."},
   {t:"Sinequismo y tiquismo", d:"Son sus dos doctrinas metafísicas tardías y las más difíciles de digerir para quien llega por el lado lógico. El sinequismo es el principio de que la continuidad es real y explicativa: no hay saltos absolutos entre mente y materia, entre una persona y otra, entre pasado y futuro, y toda explicación que postule una discontinuidad última está en realidad renunciando a explicar. El tiquismo sostiene que el azar es objetivo, un ingrediente real del universo y no una medida de nuestra ignorancia; las leyes naturales no son eternas sino hábitos que el cosmos fue adquiriendo y sigue adquiriendo, de modo que el orden es un resultado evolutivo. Ambas ideas chocan con la imagen del Peirce sobrio y científico, y por eso muchos lectores las descartan como excentricidad; pero son coherentes con su realismo sobre las leyes y con el falibilismo, y anticipan discusiones sobre indeterminismo que la física del siglo XX volvería inevitables."}
 ],
 conexion:"<b>William James</b> popularizará y transformará su pragmatismo, para disgusto del propio Peirce.",
 dialogo:{titulo:"Un nombre lo bastante feo", lineas:[
   {quien:"Estudiante", texto:"Entonces usted es el que dijo que una creencia es verdadera si funciona."},
   {quien:"Peirce", texto:"No. Eso lo dice mi amigo James, y por esa frase llevo años sin dormir bien. Yo nunca definí la verdad por el éxito. Mi máxima es una regla para aclarar qué significa un concepto, no para decidir cuál es verdadero."},
   {quien:"Estudiante", texto:"¿Y cuál es la diferencia? Si el significado está en los efectos prácticos, lo que da buenos efectos sería lo verdadero."},
   {quien:"Peirce", texto:"Fíjese en el salto que acaba de dar. Yo dije efectos concebibles del objeto concebido, no efectos agradables para el que cree. Que llamar duro a un diamante signifique que resistiría el rayado no depende de que a usted le convenga creerlo. La máxima aclara el contenido; después la experiencia decide."},
   {quien:"Estudiante", texto:"Igual suena a lo mismo cuando se lo cuenta rápido."},
   {quien:"Peirce", texto:"Por eso me rendí con la palabra. Cuando vi que pragmatismo andaba suelto por las revistas queriendo decir cualquier cosa, anuncié que le daba un beso de despedida a mi criatura y bauticé mi posición pragmaticismo, un nombre lo bastante feo como para estar a salvo de secuestradores.", nota:"La frase es literal de un artículo de 1905 en The Monist. El desacuerdo con James fue real y no personal: siguieron siendo amigos, y James lo sostuvo económicamente durante años."},
   {quien:"Estudiante", texto:"Entonces usted empieza como Descartes, dudando de todo para encontrar el fundamento."},
   {quien:"Peirce", texto:"Al contrario. Descartes propone dudar de todo, pero nadie hace eso. Escribir en un papel que dudo de que tengo un cuerpo no me pone en duda, del mismo modo que escribir la palabra fuego no incendia la hoja. La duda de papel es una ceremonia."},
   {quien:"Estudiante", texto:"Pero si no dudo de todo, arranco lleno de prejuicios heredados."},
   {quien:"Peirce", texto:"Arranca lleno de creencias, sí, y no hay otro comienzo posible. Lo que corresponde no es fingir que las abandonó todas, sino soltarlas una por una cuando alguna choque de verdad con la experiencia. No pretendamos dudar en filosofía de lo que no dudamos en el corazón."},
   {quien:"Estudiante", texto:"¿Cómo sé si mi duda es de las verdaderas?"},
   {quien:"Peirce", texto:"Por si le cambia la conducta. La creencia es un hábito de acción y la duda es la interrupción de ese hábito, un estado de irritación que uno busca terminar. Si después de dudar usted actúa exactamente igual que antes, no estaba dudando: estaba conversando."},
   {quien:"Estudiante", texto:"Una última cosa. Si todo esto es tan claro, ¿por qué en la facultad leemos a James y a Dewey y a usted casi nada?"},
   {quien:"Peirce", texto:"Porque ellos escribieron libros y yo dejé cien mil papeles. Porque di conferencias que el público no entendió y perdí el único puesto universitario que tuve. Y porque mi prosa exige del lector una paciencia que la de James no exige, lo cual no es una virtud mía sino un defecto.", nota:"Es un autorretrato exacto: Peirce murió en la pobreza y sin haber publicado nunca el sistema que proyectaba, y su reconocimiento como el lógico más riguroso de los tres llegó decenios después, con la edición de los Collected Papers."},
   {quien:"Estudiante", texto:"¿Y qué le pido entonces a alguien que quiere empezar por usted?"},
   {quien:"Peirce", texto:"Que lea los dos ensayos de 1877 y 1878 en orden y que no busque un sistema. Y que no bloquee el camino de la indagación, que es el único consejo que me atrevería a dar como si fuera una regla."}
 ]},
 actividades:[
   {t:"La máxima pragmática aplicada a una creencia propia", d:"Elegí una creencia abstracta que sostengas de verdad y que no sea fácil de contrastar: que existe el libre albedrío, que tal persona te quiere, que el mercado se autorregula, que hay vida después de la muerte, que tu trabajo tiene sentido. Escribí primero la creencia en una frase. Después listá todos los efectos prácticos concebibles que se seguirían de que sea verdadera, en la forma de condicionales: si es verdadera, entonces en tal situación ocurriría tal cosa observable. Hacé la misma lista suponiéndola falsa. Ahora compará las dos listas. Si son idénticas, según Peirce no estás sosteniendo una creencia sino repitiendo una fórmula, y la discusión con quien piense lo contrario es verbal. Si difieren, subrayá el condicional más barato de poner a prueba. Cerrá con un párrafo honesto: ¿la máxima te ayudó a aclarar la creencia o te dejó afuera algo que igual te parece que significa?"},
   {t:"Duda genuina contra duda actuada", d:"Recuperá dos episodios reales de las últimas semanas. En el primero dudaste de algo y seguiste actuando exactamente igual que antes: una discusión donde concediste que quizá tenías razón el otro, un momento de escepticismo filosófico en clase, una crisis declarada en voz alta que no cambió ninguna rutina. En el segundo la duda te frenó de verdad: no supiste qué hacer, buscaste información, probaste algo, preguntaste. Describí ambos en detalle y anotá en cada caso qué hábito de acción estaba en juego y si quedó interrumpido. Terminá con la pregunta incómoda: ¿en qué proporción de tus dudas declaradas hay algo en juego? Y una réplica a Peirce: ¿no puede una duda empezar siendo de papel y volverse real a fuerza de pensarla, como parece que le pasó a más de un científico?"},
   {t:"Cazar una abducción propia", d:"Identificá un caso concreto y reciente en el que hayas explicado un hecho sorprendente con una conjetura: alguien no contestó un mensaje, un aparato dejó de funcionar, un estudiante cambió de actitud, un gasto no cuadró. Reconstruilo en la forma exacta de Peirce: se observa el hecho sorprendente H; si la hipótesis X fuera verdadera, H sería natural; luego hay razón para sospechar X. Después mostrá por qué no es una deducción (la conclusión puede ser falsa con premisas verdaderas) ni una inducción (no generalizaste a partir de casos repetidos). Lo más importante viene al final: listá al menos otras tres hipótesis que también explicarían el mismo hecho y preguntate por qué se te ocurrió justamente la que se te ocurrió. Ahí está el problema que a Peirce le costó treinta años, el de la economía de la investigación, y sirve para discutir si la abducción es una inferencia o el nombre de un momento creativo que la lógica no captura."}
 ],
 cuestionario:[
   {q:"¿La máxima pragmática pasa su propia prueba? ¿Cuáles son sus efectos prácticos concebibles?", p:"La autoaplicación es la objeción clásica y Peirce la habría aceptado como legítima. Una respuesta directa: la máxima sí tiene efectos concebibles, porque prescribe una conducta intelectual distinta. Quien la adopta disuelve ciertas disputas como verbales, reformula los conceptos en condicionales contrastables y deja de buscar significados ocultos detrás de los efectos; quien no la adopta discute la transubstanciación o la sustancia inmaterial como si algo dependiera de ello. Sea cual sea la posición, la máxima no es un enunciado sobre el mundo sino una regla de método, y las reglas se evalúan por su rendimiento y no por su verdad. Pero ahí aparece la réplica fuerte: si la máxima se defiende por su rendimiento, entonces se está evaluando pragmáticamente a sí misma, y el criterio último termina siendo el éxito de la investigación, que es justamente lo que Peirce no quería conceder a James. La salida peirceana pasa por su realismo: la máxima funciona porque hay leyes reales que hacen verdaderos los condicionales, no al revés."},
   {q:"Si la verdad es aquello en lo que convergería la comunidad al final de la indagación, ¿no queda la verdad dependiendo de una comunidad idealizada en lugar de la realidad?", p:"La objeción tiene dos filos y conviene separarlos. El primero es contrafáctico: la humanidad puede extinguirse mañana, así que no hay tal comunidad final, y una verdad definida por un límite que nadie alcanzará parece una ficción. El segundo es de orden: intuitivamente las cosas son como son y por eso terminaríamos coincidiendo, de modo que la convergencia sería un síntoma de la verdad y no su definición. Peirce responde al primero que el destinado a ser aceptado no es una predicción sobre la historia real sino un condicional sobre lo que ocurriría si la indagación se prolongara indefinidamente, y que ese condicional es verdadero por las mismas razones por las que es verdadero que el diamante resistiría el rayado. Al segundo responde que su definición no invierte el orden, porque lo que fuerza la convergencia es la resistencia de lo real. Aun así queda un resto incómodo: hay cuestiones sobre las que la indagación podría no converger nunca, ni siquiera idealmente, y sobre ellas la definición no dice si hay verdad o no la hay. Royce y Putnam trabajaron sobre esta misma dificultad."},
   {q:"¿Cómo se concilia el lógico riguroso del falibilismo con la metafísica del azar cósmico y la continuidad universal?", p:"Muchos lectores resuelven la tensión amputando: se quedan con el Peirce de 1877 y descartan el sinequismo y el tiquismo como una deriva especulativa de sus años de aislamiento y pobreza. Es una lectura cómoda y probablemente injusta. Hay un hilo real entre ambas etapas. Si las leyes de la naturaleza fueran exactas y necesarias, cada desviación en una medición tendría que atribuirse por completo al error del instrumento; Peirce, que medía gravedad con péndulos, argumenta que nada en la experiencia respalda esa exactitud absoluta y que es más económico suponer que las leyes son estadísticas y que el azar es real. El tiquismo es así una consecuencia de tomarse en serio el falibilismo aplicado a la física, no una excepción a él. Con el sinequismo pasa algo parecido: su realismo sobre los generales necesita continuidad para que las leyes sean algo más que colecciones de casos. Dicho esto, la crítica sigue en pie en un punto: las especulaciones cosmológicas sobre el amor evolutivo y sobre las leyes como hábitos adquiridos del universo exceden con mucho lo que sus propios estándares de contrastación permitirían, y Peirce nunca explicó del todo por qué su máxima no debía aplicarse ahí con el mismo rigor."},
   {q:"¿En qué se diferencia realmente el pragmatismo de Peirce de la voluntad de creer de James?", p:"En el sujeto y en el objeto. Para Peirce el sujeto de la indagación es una comunidad ilimitada y el criterio es la convergencia a largo plazo; el individuo es, en el mejor de los casos, un miembro que debe subordinar su interés al proceso. Para James el sujeto es una persona concreta, con una vida y un tiempo limitados, que en ciertas situaciones debe decidir antes de que la evidencia esté completa. Y el objeto difiere: la máxima de Peirce es un criterio de significado, mientras que James la convierte en una teoría de la verdad, donde verdadero es lo que resulta bueno en el orden de la creencia. La voluntad de creer, además, está acotada por James a opciones vivas, forzosas y de peso vital que la evidencia no puede zanjar, lo que es más restrictivo de lo que sugiere la caricatura; pero incluso así Peirce lo consideraría una licencia para el método a priori, es decir, para creer lo que resulte agradable. Lo interesante es que James tiene una ventaja de la que Peirce carece: ofrece una respuesta a qué hacer hoy, mientras que una verdad definida al final de la indagación no orienta a nadie que tenga que decidir esta tarde."},
   {q:"¿Es la abducción una forma de inferencia o solo una corazonada con nombre técnico?", p:"La sospecha es razonable. Su forma lógica, tal como Peirce la escribe, es la falacia de afirmar el consecuente: si X entonces H, se da H, luego quizá X. Peirce lo sabía perfectamente y por eso insistía en que la abducción no pretende validez sino que solo autoriza a sospechar y a poner la hipótesis en la lista de candidatas a prueba. El problema serio es otro: dado un hecho sorprendente, infinitas hipótesis lo explicarían, y la abducción por sí sola no dice cuál elegir. Peirce intentó dos respuestas. Una es la economía de la investigación, un conjunto de criterios prácticos —costo, verificabilidad, alcance, simplicidad— para ordenar las candidatas, que es más una metodología de la investigación que una lógica. La otra es mucho más arriesgada: sostuvo que la mente humana tiene una afinidad natural con las leyes del universo, il lume naturale, que explica por qué acertamos con hipótesis correctas con una frecuencia estadísticamente asombrosa. La primera respuesta es sensata y modesta; la segunda es difícil de sostener sin una metafísica pesada. Aun así, la distinción sigue siendo útil, porque señala un momento real del razonamiento científico que ni la deducción ni la inducción describen, y toda la discusión contemporánea sobre la inferencia a la mejor explicación arranca de ahí."}
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.peirce = { lecturas:[
 {titulo:"«Cómo esclarecer nuestras ideas» (1878): la máxima pragmática", fuente:"Grupo de Estudios Peirceanos, Universidad de Navarra — traducción de José Vericat", url:"https://www.unav.es/gep/HowMakeIdeas.html",
  extracto:`Peirce empieza atacando una herencia cartesiana: la idea de que basta con tener ideas «claras y distintas». Para él esa doctrina describe una claridad meramente subjetiva — la familiaridad con que reconocemos un concepto cuando lo vemos — y una distinción meramente verbal, la capacidad de dar una definición abstracta. Ninguna de las dos garantiza que sepamos de qué estamos hablando.

Antes de proponer su remedio, Peirce ofrece una teoría de la creencia que vale por sí sola. La duda es un estado de irritación e insatisfacción del que intentamos salir; la creencia, un estado de calma. «La esencia de la creencia es el establecimiento de un hábito, y las diferentes creencias se distinguen por los diferentes modos de acción a que dan lugar.» De ahí una consecuencia cortante: «si las creencias no difieren en este aspecto, si apaciguan la misma duda produciendo la misma regla de acción, entonces ninguna diferencia en la manera de ser conscientes de ellas puede convertirlas en creencias diferentes, como tampoco tocar una melodía en distintos tonos es tocar melodías distintas».

Peirce ilustra el punto con la disputa sobre la transubstanciación: católicos y protestantes discuten si el vino es sangre, pero ambos esperan de ese vino exactamente los mismos efectos sensibles. «Podemos decir que el vino participa de la naturaleza de la sangre... pero hablar de algo como teniendo todos los caracteres sensibles del vino, y siendo sin embargo realmente sangre, es un sinsentido puro.»

Entonces enuncia la máxima que dará nombre al pragmatismo: «consideremos qué efectos, que puedan tener concebiblemente repercusiones prácticas, concebimos que tenga el objeto de nuestra concepción; nuestra concepción de estos efectos es la totalidad de nuestra concepción del objeto». No hay un resto de significado más allá de esos efectos.

Aplicada a «duro», la máxima dice que llamar duro a algo es afirmar que no será rayado por muchas otras sustancias. Aplicada a «peso», que en ausencia de fuerzas contrarias caerá. Aplicada a «fuerza», Peirce sostiene que toda la metafísica de las fuerzas se agota en la ley de composición de aceleraciones.

El caso más interesante es «realidad». Definida abstractamente, real es lo que tiene los caracteres que tiene con independencia de lo que alguien piense de ello. Pero ¿cuál es su efecto práctico? Aquí Peirce introduce la comunidad de investigadores: lo real es aquello sobre lo que la investigación, llevada suficientemente lejos, terminaría por hacer converger a todos. «La opinión destinada a ser finalmente aceptada por todos los que investigan es lo que entendemos por verdad, y el objeto representado en esta opinión es lo real.»

Esa definición tiene dos consecuencias que Peirce acepta explícitamente. La primera es el falibilismo: ninguna creencia actual es la opinión final, y toda afirmación queda abierta a revisión. La segunda es que la verdad no es propiedad de un individuo ni de una época, sino un límite ideal de un proceso social e indefinido de indagación. La realidad no depende de lo que vos o yo pensemos, pero sí depende de lo que el pensamiento, en el largo plazo, sea.`,
  comentario:"Este texto es el acta de nacimiento del pragmatismo, y conviene leerlo notando que Peirce NO dice que la verdad sea lo útil — eso será James. Su criterio es de significado, no de verdad: una diferencia sin consecuencias concebibles no es una diferencia de significado. La definición de lo real por convergencia es lo que permite ser falibilista sin caer en relativismo, y responde a la pregunta del cuestionario sobre ideas hoy inverificables."}
], preguntasLectura:[
 {q:"¿Qué es la esencia de la creencia según Peirce?", opciones:["Una representación mental clara","El establecimiento de un hábito de acción","Un sentimiento de certeza","Un acuerdo social explícito"], r:"El establecimiento de un hábito de acción", why:"Por eso dos creencias que producen la misma regla de acción son, para Peirce, la misma creencia."},
 {q:"¿Cómo define Peirce la realidad en términos pragmáticos?", opciones:["Lo que percibimos con los sentidos","Aquello sobre lo que la investigación indefinida haría converger a todos","Lo que Dios ha creado","Lo que es útil creer"], r:"Aquello sobre lo que la investigación indefinida haría converger a todos", why:"«La opinión destinada a ser finalmente aceptada por todos los que investiguen es lo que entendemos por verdad»."},
 {q:"¿Qué ejemplo usa Peirce para mostrar una disputa sin diferencia práctica?", opciones:["La existencia de Dios","La transubstanciación del vino","La redondez de la Tierra","El origen de las especies"], r:"La transubstanciación del vino", why:"Ambas partes esperan del vino los mismos efectos sensibles, así que la disputa carece de contenido pragmático."}
]};
