/* ============================================================
   Ficha: rorty  ·  tradición: americana
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"rorty", trad:"americana", nombre:"Richard Rorty", fechas:"1931–2007 · EE. UU.", escuela:"Neopragmatismo", icon:"🪢", profundizada:true,
 tesis:"La filosofía moderna se construyó sobre una metáfora, no sobre un descubrimiento: la de la mente como un espejo que contiene representaciones más o menos fieles del mundo. Descartes la instaló al inventar un espacio interior, Locke la volvió psicología de las ideas y Kant la convirtió en sistema; desde entonces la epistemología se dedicó a pulir el espejo. Rorty sostiene que esa imagen no se refuta, se abandona: no hay un tribunal neutral donde comparar nuestras oraciones con la realidad desnuda, porque toda comparación se hace ya dentro de algún vocabulario. Nos relacionamos causalmente con el mundo —nos golpea, nos resiste— pero de ahí no se sigue que nuestras frases se correspondan con hechos. La verdad no es una relación entre lenguaje y mundo sino un cumplido que hacemos a las creencias que nos resultan justificadas ante alguien. Si esto es así, la filosofía deja de ser la disciplina que juzga a las demás y pasa a ser una voz más en la conversación de la humanidad, y la meta deja de ser la objetividad para pasar a ser la solidaridad: ampliar el nosotros hasta incluir a más gente cuyo dolor nos importe. Lo notable, y lo que vuelve a Rorty un caso difícil, es que sostiene a la vez dos cosas que parecen no aguantarse juntas: que la crueldad es lo peor que hacemos, y que esa convicción no tiene ningún fundamento último. A eso llama ironismo liberal, y su defensa es que solo nos parece una contradicción porque seguimos esperando que los compromisos vengan respaldados por metafísica.",
 obras:[
   {t:"La filosofía y el espejo de la naturaleza (1979)", d:"Su obra más influyente y la más devastadora, escrita desde adentro de la filosofía analítica por alguien que había editado El giro lingüístico y que conocía el oficio como pocos. No es un tratado sistemático sino una historia crítica de una metáfora: Rorty muestra cómo los problemas que la epistemología consideró eternos —el mundo exterior, otras mentes, la relación entre lo mental y lo físico— no son problemas perennes de la razón humana sino el efecto de una imagen instalada en el siglo XVII, la de un ojo interior que inspecciona representaciones. El libro se apoya en tres autores analíticos para desarmar la tradición analítica desde dentro: Wittgenstein, Quine y Sellars, y en particular el ataque de Sellars al mito de lo dado y el de Quine a la distinción analítico-sintético, que juntos dejan sin piso la idea de una base incorregible del conocimiento. La tercera parte es la más constructiva y la menos leída: propone reemplazar la epistemología por la hermenéutica, entendida no como un método rival sino como lo que hacemos cuando no hay conmensurabilidad, es decir, cuando conversamos con quien no comparte nuestros criterios en lugar de someterlo a los nuestros. Su efecto en el mundo académico fue inmediato y feroz: Rorty terminó dejando el departamento de filosofía de Princeton para enseñar humanidades en Virginia, un movimiento que él mismo leía como la consecuencia institucional de su tesis."},
   {t:"Consecuencias del pragmatismo (1982)", d:"Colección de ensayos escritos entre 1972 y 1980 donde Rorty saca las conclusiones del libro anterior y bautiza su posición. Aquí formula la definición de pragmatismo que después repetirá siempre: es simplemente antiesencialismo aplicado a nociones como verdad, conocimiento, lenguaje y moralidad, más la tesis de que no hay ninguna diferencia epistemológica entre la verdad sobre lo que debe ser y la verdad sobre lo que es, más la idea de que no hay más restricciones a la investigación que las conversacionales. El volumen contiene su lectura de James y Dewey como los verdaderos superadores de la metafísica, muy por delante de Heidegger y de Derrida en su opinión, y un ensayo célebre sobre el destino de la filosofía profesional que sostiene que la disciplina tal como se enseña es un género literario que ya dio lo que tenía para dar. También está aquí la distinción que organiza toda su obra posterior entre filosofía sistemática, que busca fundamentos, y filosofía edificante, que busca mantener abierta la conversación e impedir que ninguna descripción se cierre sobre sí misma. Es el libro donde queda claro que su antifundacionalismo no es escepticismo: Rorty no duda de que sepamos cosas, duda de que saber consista en reflejar algo."},
   {t:"Contingencia, ironía y solidaridad (1989)", d:"Su síntesis política y existencial, y el libro por el que se lo lee fuera de la filosofía académica. Está organizado en tres movimientos que replican el mismo argumento en escalas crecientes: la contingencia del lenguaje —ningún vocabulario está más cerca de la realidad que otro, los vocabularios se inventan como se inventan herramientas—, la contingencia del yo —no hay un núcleo verdadero que descubrir, hay una red de creencias y deseos que puede redescribirse— y la contingencia de la comunidad liberal —nuestras instituciones no derivan de la naturaleza humana ni de la razón, son un logro histórico frágil y local. Sobre esa base construye dos figuras. El ironista es quien tiene dudas radicales y permanentes sobre su propio vocabulario final y sabe que ningún argumento formulado en ese vocabulario puede disolverlas. El liberal, en la definición que toma de Judith Shklar, es quien piensa que la crueldad es lo peor que hacemos. El ironista liberal es ambos a la vez, y la tesis central del libro es que esa combinación no solo es posible sino que no necesita ninguna teoría que la unifique. La segunda mitad es un ejercicio de crítica literaria filosófica: lee a Proust, Nabokov y Orwell como pensadores morales, y sostiene que Lolita y 1984 hicieron más contra la crueldad que cualquier tratado de ética."},
   {t:"Objetivismo, relativismo y verdad (1991) y Verdad y progreso (1998)", d:"Los volúmenes de sus Philosophical Papers, donde se encuentra el Rorty más técnico y el que discute cara a cara con sus críticos, y por eso mismo los más útiles para evaluarlo en serio. En el primero están los ensayos sobre la prioridad de la democracia sobre la filosofía —la tesis de que una sociedad liberal no necesita una justificación filosófica de sus prácticas, igual que Jefferson no necesitaba una teología para defender la tolerancia religiosa— y sobre solidaridad u objetividad, donde defiende abiertamente el etnocentrismo como la única posición honesta disponible. En el segundo están sus largas réplicas a Hilary Putnam, a Donald Davidson y a Jürgen Habermas, y el ensayo sobre derechos humanos, racionalidad y sentimentalismo donde sostiene que el progreso moral no vino de mejores argumentos sino de una educación sentimental que amplió el repertorio de gente a la que somos capaces de imaginar como semejante. La discusión con Putnam es la más instructiva porque ambos partían del mismo rechazo al realismo metafísico y llegaron a lugares opuestos: Putnam sostiene que abandonar la verdad como norma hace ininteligible la propia idea de afirmar algo, y Rorty responde que la norma es la justificación ante una audiencia cada vez más amplia, no una correspondencia."},
   {t:"Forjar nuestro país (Achieving Our Country, 1998)", d:"Su intervención política más directa, nacida de unas conferencias en Harvard, y un libro que se volvió famoso veinte años después de publicado por razones que Rorty no habría festejado. Su tesis es un reproche a la izquierda estadounidense: entre los años treinta y los sesenta hubo una izquierda reformista que consiguió cosas concretas —sindicatos, seguridad social, derechos civiles— y que se sentía parte del país que quería reformar; después de Vietnam esa izquierda fue reemplazada por una izquierda cultural, académica y espectadora, experta en detectar la complicidad de todo con todo, orgullosa de su distancia respecto de una nación que consideraba irredimible. Rorty reconoce los logros reales de esa izquierda en materia de sadismo social —hoy es mucho más costoso humillar públicamente a alguien por su raza, su sexo o su orientación—, pero sostiene que abandonó el terreno del egoísmo económico y dejó sin lenguaje a los trabajadores. El pasaje que circuló masivamente después de 2016 predice que llegará un momento en que el electorado suburbano y obrero decidirá que el sistema falló y buscará un hombre fuerte al que votar, alguien que les asegure que los burócratas engreídos y los abogados serviles ya no mandarán, y que entonces se perderá de golpe lo ganado en cuatro décadas de buenos modales públicos."}
 ],
 conceptos:[
   {t:"La filosofía como espejo de la naturaleza", d:"El blanco de toda su obra no es una tesis sino una imagen: la de la mente como una superficie que contiene representaciones, algunas exactas y otras deformadas, y la del conocimiento como la inspección de esas representaciones para verificar su fidelidad. Rorty rastrea su invención histórica: Descartes crea el espacio interior al agrupar bajo un mismo rótulo el dolor de muelas y la idea de triángulo, algo que a un griego le habría parecido raro; Locke confunde la explicación causal de cómo se forman las ideas con su justificación; Kant sistematiza el conjunto convirtiendo la epistemología en la disciplina que fija de antemano las condiciones de cualquier conocimiento posible, y por lo tanto en el tribunal que juzga a las demás. La objeción de Rorty no es que la metáfora sea falsa —una metáfora no es ni verdadera ni falsa— sino que nos tiene presos: mientras la aceptemos, los problemas del escepticismo, del mundo exterior y de la relación mente-cuerpo parecerán descubrimientos sobre la condición humana, cuando son consecuencias de una manera particular de hablar que alguna vez fue útil y ya no lo es. La salida no es una teoría mejor de la representación sino dejar de hablar de representaciones, igual que dejamos de hablar de flogisto sin haber demostrado que no existía."},
   {t:"El antifundacionalismo", d:"No hay un piso último que legitime nuestras creencias desde fuera de nuestras prácticas: ni la razón pura, ni la experiencia sensible incorregible, ni una estructura del lenguaje, ni la naturaleza humana. Rorty llega a esta conclusión apoyándose en dos ataques analíticos que considera decisivos y que conviene distinguir. El de Sellars contra el mito de lo dado muestra que no existe ningún contenido perceptivo puro, anterior a todo concepto, que pueda funcionar como base incuestionable: percibir algo como algo ya es ubicarlo en el espacio de las razones. El de Quine contra la distinción entre enunciados analíticos y sintéticos muestra que no hay verdades garantizadas solo por el significado, y que cualquier creencia puede revisarse si se ajusta el resto de la red. Juntos dejan sin candidatos al puesto de fundamento. Lo importante es lo que Rorty concluye y lo que no concluye. No concluye que no sepamos nada ni que cualquier opinión valga lo mismo: la justificación sigue existiendo y sigue siendo exigente, solo que es siempre justificación ante alguien, dentro de una práctica, y no ante el tribunal de la Realidad. El fundamento que buscaba la epistemología no falta: nunca hizo falta."},
   {t:"El vocabulario final o léxico último", d:"Es el conjunto de palabras con las que cada persona justifica en última instancia sus acciones, sus creencias y su vida: bueno, decente, profesional, la revolución, la Iglesia, Cristo, el libre mercado, los derechos humanos, la patria. Se llama final no porque sea correcto ni porque sea el mejor, sino porque es donde se acaba la argumentación: si alguien pone en duda esas palabras, su usuario no tiene nada más profundo a lo que apelar y solo puede repetirlas, describirlas mejor o cambiar de conversación. Todo intento de justificar el vocabulario final dentro del propio vocabulario final es circular, y eso vale tanto para el ironista como para el metafísico; la diferencia entre ellos no está en la circularidad, que es inevitable, sino en si la reconocen. Rorty distingue dentro de cada léxico una parte pequeña y flexible —palabras de uso corriente— y un núcleo duro que suele ser lo último que uno estaría dispuesto a perder. Un ejercicio útil que él mismo sugiere: si lo llevan a uno al límite de lo que puede defender con razones, las tres o cuatro palabras que quedan en pie son su vocabulario final, y el hecho de no poder fundamentarlas no significa que haya que abandonarlas."},
   {t:"El ironista liberal", d:"Es la figura central de Contingencia, ironía y solidaridad y la más malinterpretada. El ironista cumple tres condiciones: tiene dudas radicales y permanentes sobre su vocabulario final porque conoce otros que lo impresionaron; sabe que ningún argumento formulado en su propio vocabulario puede disolver esas dudas; y no cree que su léxico esté más cerca de la realidad que los demás. El liberal, en la definición de Judith Shklar que Rorty adopta, es quien piensa que la crueldad es lo peor que hacemos. El ironista liberal es las dos cosas a la vez: se compromete políticamente contra el sufrimiento y la humillación sabiendo perfectamente que ese compromiso no está respaldado por nada más profundo que la historia contingente que lo formó. Rorty insiste una y otra vez en que ironismo no es cinismo ni relativismo frívolo: no dice que todas las opiniones valgan igual, dice que la suya no viene garantizada. Su argumento a favor de que esto es vivible es psicológico antes que lógico: nadie deja de amar a su hija al enterarse de que ese amor tiene causas contingentes, y no está claro por qué el compromiso contra la tortura debería ser más frágil que el amor."},
   {t:"La separación entre lo público y lo privado", d:"Es su movimiento estratégico más discutido y el que le permite sostener las dos mitades de su posición sin unificarlas. La autocreación irónica —redescribirse, inventar un vocabulario propio, hacer de la vida algo que no sea una mera copia— es para Rorty un proyecto privado, admirable pero no político, y sus héroes son Nietzsche, Proust, Nabokov, Heidegger, Foucault. La solidaridad —reducir el sufrimiento, evitar la humillación, ampliar la libertad— es un proyecto público, y sus héroes son Mill, Dewey, Orwell, Habermas. El error de casi toda la filosofía, dice, fue querer una única teoría que respondiera a la vez cómo debo vivir y qué le debo a los demás, y de ese afán salieron tanto los metafísicos que convierten su proyecto privado en obligación universal como los críticos que exigen a la literatura una política. Rorty no afirma que las dos esferas nunca choquen; afirma algo más modesto y más incómodo: que cuando chocan no hay teoría que resuelva el conflicto, solo decisiones concretas, y que la exigencia pública tiene un límite claro —no hacer sufrir a otros con tu autocreación— que no necesita justificarse filosóficamente. La objeción obvia, que vuelve una y otra vez, es que la línea entre lo público y lo privado no es natural sino política, y que decidir dónde ponerla ya es tomar partido."},
   {t:"La solidaridad sin fundamento metafísico", d:"La solidaridad humana no depende de descubrir una esencia común bajo las diferencias, porque no hay tal esencia esperando ser descubierta; es algo que se hace, no que se encuentra. Rorty lo formula como la ampliación progresiva del nosotros: partimos siempre de un círculo estrecho —mi familia, mi pueblo, mi clase, los de mi religión— y el progreso moral consiste en que ese círculo se agrande hasta incluir a gente que antes aparecía como ellos. Lo decisivo es cómo se consigue esa ampliación, y aquí su tesis es fuerte y verificable: no se consigue con argumentos que demuestren que todos los seres humanos comparten una dignidad racional, sino con descripciones detalladas del dolor y la humillación ajenos. La novela, el reportaje, la etnografía, el documental y el cine hacen el trabajo moral que la teoría no puede hacer, porque no convencen a nadie de nada: lo obligan a notar detalles. De ahí su tesis sobre los derechos humanos: no se expandieron porque Kant tuviera razón sino por una larga educación sentimental, desde La cabaña del tío Tom hasta las fotografías de guerra, que fue volviendo imaginables como semejantes a personas antes invisibles. Y de ahí también su reformulación de la meta filosófica: cambiar la objetividad por la solidaridad."},
   {t:"El neopragmatismo", d:"Rorty se declara heredero de James y de Dewey y retoma de ellos la idea de que una creencia verdadera es la que funciona, que las ideas son instrumentos para lidiar con el entorno y que la filosofía debe servir a la mejora social y no a la contemplación. Pero su pragmatismo pasa por el giro lingüístico y sale cambiado: donde Dewey hablaba de experiencia, Rorty habla de vocabularios, y donde Dewey conservaba una confianza en el método de la inteligencia modelado en la ciencia experimental, Rorty ve un último residuo de la idea de que hay una manera privilegiada de acercarse a lo real. Su instrumento decisivo es Davidson, de quien toma la tesis de que no tiene sentido postular esquemas conceptuales que organicen un contenido neutral, y con ella cancela de un golpe tanto el realismo como el relativismo, que necesitan ambos esa distinción. La diferencia con Peirce es la más clara y la más importante: Peirce definía la verdad como la opinión destinada a ser aceptada por la comunidad de investigadores al final de la indagación, lo cual conserva una norma que trasciende cualquier consenso actual; Rorty considera que ese final ideal es un sustituto laico de Dios y que no hace ningún trabajo, porque nunca podremos saber si ya llegamos. Por eso él mismo reconoce que Peirce lo tendría por un sofista."},
   {t:"La crítica a la izquierda cultural", d:"En Forjar nuestro país distingue dos izquierdas estadounidenses y toma partido sin ambigüedad. La izquierda reformista, que va de los progresistas de principios de siglo a los sindicatos, el New Deal y el movimiento por los derechos civiles, se caracterizaba por querer mejorar el país desde adentro, por aceptar el marco constitucional y por medir su éxito en leyes conseguidas. La izquierda cultural que la reemplazó después de Vietnam se instaló en la universidad, cambió la política por la teoría, la reforma por la crítica de las representaciones y la acción por la denuncia de la complicidad, y adoptó frente a su propio país una postura de espectador avergonzado. Rorty le reconoce un logro enorme y real —redujo drásticamente el sadismo social, volvió inaceptable humillar públicamente a alguien por su raza, su sexo o su orientación— y le reprocha un abandono igual de grande: dejó de hablar de dinero, de empleo y de desigualdad, y dejó a los trabajadores sin un lenguaje de izquierda para nombrar lo que les pasaba. La consecuencia que anticipa es su página más citada: cuando el resentimiento acumulado encuentre voz, buscará un hombre fuerte, y los avances culturales serán lo primero que se lleve puesto. Conviene discutir esta crítica en serio y no solo celebrar su puntería, porque los reproches contra ella —que subestima que raza y clase no se separan, que su nosotros nacional es precisamente el problema— son sólidos."},
   {t:"El etnocentrismo asumido y sus polémicas", d:"Rorty se declaraba etnocéntrico sin pedir disculpas, y conviene entender exactamente qué afirmaba porque es su posición más provocadora. Sostenía que no hay manera de salir de la propia piel para juzgar desde ningún lugar: cuando justificamos algo, lo justificamos ante alguna comunidad concreta con sus criterios, y la comunidad de referencia de un intelectual atlántico contemporáneo son las democracias liberales ricas del Atlántico Norte. Su matiz era que se trata de un etnocentrismo peculiar, el de una cultura que tiene entre sus valores el de escuchar a los extraños y ampliarse, de modo que la única superioridad que reclamaba para el liberalismo era la de estar abierto a su propia transformación. Con Dewey su relación es de herencia y de recorte: lo reivindica como el gran superador de la metafísica y le quita el naturalismo y la fe en el método. Con Habermas y Apel el desacuerdo es genuino y no verbal: ellos sostienen que la crítica social necesita una norma de validez que trascienda cualquier consenso fáctico, porque sin ella no se puede decir que una comunidad entera esté equivocada; Rorty responde que esa norma no hace falta y que basta con la conversación abierta y con la comparación entre vocabularios. Con Putnam la discusión es la más filosa, y es la que mejor muestra qué hay en juego."}
 ],
 conexion:"Retoma y radicaliza a <b>John Dewey</b>, a quien considera el mayor filósofo del siglo XX, pero le quita el residuo de fe en el método de la inteligencia científica. De <b>William James</b> hereda la verdad como lo que funciona y la lleva más lejos de lo que James la habría llevado. Se separa explícitamente de <b>Peirce</b>, cuya comunidad ideal de investigadores le parece un sustituto laico de Dios. Debe a <b>Wittgenstein</b> la idea de que los problemas filosóficos son efectos del lenguaje, y a Sellars, Quine y Davidson las herramientas analíticas con las que desarma el representacionalismo. Discute frontalmente con <b>Habermas</b> y Apel sobre si la crítica social necesita una norma de validez que trascienda el consenso, y con Hilary Putnam sobre si se puede abandonar la verdad como norma sin volver ininteligible el acto de afirmar. Y frente a <b>Dussel</b> y al pensamiento de la liberación su etnocentrismo asumido es el punto de choque: para Rorty el nosotros liberal se amplía escuchando relatos; para Dussel ese nosotros es exactamente el que produjo la exclusión.",
 dialogo:{titulo:"Sin espejo, ¿por qué la crueldad importa?", lineas:[
   {quien:"Estudiante", texto:"Profesor, lo acompaño hasta la mitad. Acepto que la mente no es un espejo y que ningún vocabulario está más cerca de la realidad que otro. Pero entonces su rechazo de la crueldad es un vocabulario más entre otros. ¿Por qué habría yo de preferirlo al del torturador?"},
   {quien:"Rorty", texto:"No tengo ninguna razón que convenza a un torturador que ya decidió serlo, y no pretendo tenerla. Pero fíjese qué extraña es su pregunta. ¿Usted está esperando que le dé un argumento que lo haga desear que no torturen a la gente? ¿De verdad hoy no le importa y espera que yo lo convenza?"},
   {quien:"Estudiante", texto:"Claro que me importa. Lo que le pido es el fundamento de que me importe."},
   {quien:"Rorty", texto:"Ahí está el problema. Usted ya tiene el compromiso y va a buscar después el fundamento, como quien ya está casado y sale a conseguir el certificado. Yo le digo que el certificado nunca existió y que su matrimonio funciona igual. Su horror ante la crueldad no lo puso ahí Kant: lo pusieron una educación, unos libros, unas caras que vio."},
   {quien:"Estudiante", texto:"Pero eso lo vuelve frágil. Si es contingente, otra educación me habría hecho indiferente, y entonces no puedo decir que el torturador esté equivocado. Solo puedo decir que no es de los míos."},
   {quien:"Rorty", texto:"Puede decir bastante más: puede describirlo, mostrar lo que hace, contar lo que sienten sus víctimas, negarse a colaborar, organizarse para impedírselo. Lo único que no puede es demostrárselo desde una premisa que él también acepte. Pero dígame una cosa: ¿alguna vez alguien dejó de torturar porque le refutaron la premisa mayor?", nota:"Este es el núcleo de su tesis sobre el progreso moral: en Derechos humanos, racionalidad y sentimentalismo sostiene que la expansión de los derechos no vino de mejores argumentos filosóficos sino de una educación sentimental de largo plazo —novelas, crónicas, fotografías— que volvió imaginables como semejantes a personas antes invisibles. Es una tesis empírica sobre historia moral, no una deducción, y por lo tanto puede discutirse con historia."},
   {quien:"Estudiante", texto:"Le concedo el punto práctico. Voy al otro, que me interesa más. Usted dice que somos etnocéntricos y que su comunidad de referencia son las democracias liberales ricas del Atlántico Norte. ¿No es eso exactamente lo que denuncia Dussel? Un nosotros particular que se presenta como el horizonte dentro del cual todos deberíamos querer entrar."},
   {quien:"Rorty", texto:"Es lo que denuncia, y le concedo que soy el caso que él describe. Solo que yo no digo que mi nosotros sea el humano sin más: digo que es el mío y que no tengo otro desde donde hablar. Mi etnocentrismo es de un tipo raro: pertenezco a una cultura que hizo de escuchar a los extraños uno de sus valores. Lo único que reclamo para el liberalismo es que está abierto a ser cambiado por quienes deja afuera."},
   {quien:"Estudiante", texto:"Ese es justamente el movimiento que Dussel llamaría el mito de la modernidad. Usted dice: somos los más abiertos, por lo tanto los demás deberían querer conversar con nosotros en nuestros términos. La apertura sigue siendo una propiedad que usted se atribuye y que administra."},
   {quien:"Rorty", texto:"Es una objeción buena y no tengo una respuesta que la deje afuera. Le respondo lo que puedo: no hay ningún lugar neutral desde donde comparar culturas, y eso también vale para Dussel. Cuando él dice que el criterio último es la vida concreta del excluido, está hablando desde una tradición —profética, cristiana, levinasiana— que tampoco cayó del cielo. La diferencia entre nosotros no es que yo tenga un punto de partida particular y él uno universal: es que yo lo admito."},
   {quien:"Estudiante", texto:"Dussel diría que hay una diferencia mayor. Que el hambre no es una preferencia cultural, que es un hecho que cualquiera puede constatar, y que por eso su criterio no es un vocabulario más."},
   {quien:"Rorty", texto:"Y yo le diría que estoy de acuerdo en que el hambre es un hecho, y que discrepo en que constatar el hecho decida qué hacer. Millones de personas constatan el hambre todos los días y no se conmueven. Lo que las mueve, cuando algo las mueve, no es la constatación sino la descripción. Ahí seguimos discutiendo, y ese desacuerdo me parece más honesto que un acuerdo de palabra sobre fundamentos.", nota:"Vale registrar que esta objeción no es solo latinoamericana. Hilary Putnam, desde el realismo interno, y Norman Geras, desde el marxismo, formularon una versión análoga: que el nosotros de Rorty universaliza silenciosamente una perspectiva liberal occidental mientras niega estar haciendo metafísica, y que sin alguna noción de verdad que trascienda el consenso no queda manera de decir que una comunidad entera esté equivocada —lo que hace falta, por ejemplo, para condenar a una sociedad esclavista desde dentro de sus propios criterios. Rorty nunca concedió el punto, pero admitía que era la objeción más seria contra él."},
   {quien:"Estudiante", texto:"Una última. Usted separa lo privado de lo público: la ironía y la autocreación de este lado, la solidaridad del otro. ¿No es esa separación un lujo? El que es humillado no puede irse a redescribirse en privado."},
   {quien:"Rorty", texto:"No es un lujo, es un reparto de tareas. Nunca dije que todos puedan hacer ambas cosas ni que la línea sea natural. Dije que no hace falta una teoría que unifique cómo quiero vivir yo con lo que le debo al resto, y que buscar esa teoría fue lo que llevó a la filosofía a exigirle a la política que fuera profunda y a la literatura que fuera correcta."},
   {quien:"Estudiante", texto:"Pero decidir dónde pasa la línea entre lo público y lo privado es una decisión política, y de las más disputadas. El feminismo hizo su carrera mostrando eso."},
   {quien:"Rorty", texto:"Tiene razón y lo acepto sin pelear. La línea se mueve y se discute, y las cosas que hoy llamamos privadas fueron públicas y al revés. Lo que yo sostengo es más chico de lo que se me atribuye: no que exista una frontera fija, sino que cuando una persona se inventa a sí misma no le debe a nadie que esa invención sea además un programa político, y que cuando actúa políticamente no le debe a nadie que su programa exprese su alma."}
 ]},
 actividades:[
   {t:"Excavar el propio vocabulario final", d:"Escribí en una hoja tres convicciones que orienten tu vida, formuladas en tus palabras y no en las de un manual: por ejemplo que hay que ser leal a los amigos, que la educación pública es un derecho, que no hay que aprovecharse del que está peor. Ahora tomá la primera y preguntate por qué, y anotá la respuesta. Repetí la pregunta sobre esa respuesta, y otra vez, y otra, hasta que llegues a un punto donde ya no puedas justificar sin usar alguna de las palabras que estás tratando de justificar. Esas palabras finales son tu léxico último, y el momento en que la cadena se cierra sobre sí misma es exactamente lo que Rorty describe. Anotá las tres o cuatro palabras que quedaron en pie. Después vienen las dos partes difíciles del ejercicio. Primero: reconstruí de dónde vinieron. Qué persona, qué libro, qué experiencia, qué barrio te las puso ahí, y qué habría pasado si hubieras nacido en otro lado. Segundo, y esto es lo que decide si entendiste a Rorty o no: respondé por escrito si haber descubierto que no podés fundamentarlas te dejó con menos ganas de sostenerlas. Si la respuesta es que no, explicá por qué, porque acabás de dar el argumento central del ironismo liberal. Si la respuesta es que sí, explicá qué esperabas encontrar al final de la cadena y por qué creías que estaba ahí."},
   {t:"Poner a prueba la tesis de la educación sentimental", d:"Rorty afirma que el progreso moral no lo hicieron los argumentos sino los relatos: que una novela, una crónica o una película amplían el círculo de quienes cuentan como nosotros mucho más que un tratado de ética. Es una afirmación empírica sobre vos y podés verificarla. Buscá en tu propia biografía un caso real en que hayas empezado a que te importara un grupo de personas que antes te resultaban abstractas: migrantes, desplazados, presos, personas trans, habitantes de calle, víctimas de una guerra lejana, trabajadores de un oficio que despreciabas. Reconstruí con precisión qué produjo el cambio y en qué orden: qué leíste, qué viste, a quién escuchaste, cuánto tiempo pasó. Ahora compará: buscá también un argumento filosófico correcto sobre el mismo tema —la fórmula de la humanidad de Kant, el velo de ignorancia de Rawls, el argumento de Singer sobre el niño que se ahoga— y preguntate honestamente si ese argumento hizo algo por vos que el relato no hubiera hecho. Escribí media página con tu veredicto. Y agregá una objeción contra Rorty: buscá un caso donde la descripción detallada del sufrimiento haya producido lo contrario de solidaridad —morbo, resignación, fatiga compasiva, consumo de la desgracia ajena— y explicá qué le falta a su tesis para distinguir los dos casos."},
   {t:"Un choque real entre autocreación y solidaridad", d:"Identificá un episodio concreto de tu propia vida en que lo que querías ser y lo que le debías a otros tiraron para lados distintos: irte a estudiar lejos dejando a alguien que te necesitaba, dedicarle tiempo a un proyecto propio en vez de a una causa colectiva, negarte a participar de algo que la familia o el grupo esperaba, callarte una opinión para no romper un vínculo, o al revés, decirla y romperlo. Contá el caso en un párrafo, sin moraleja. Después aplicá el esquema de Rorty en serio: ¿el conflicto fue realmente entre un proyecto privado de autocreación y una obligación pública de solidaridad, o esa descripción no le calza bien y hay que forzarla? ¿Qué te habría dicho Rorty, que no hay teoría que lo resuelva y que solo había que decidir, y te sirve de algo esa respuesta? Terminá con la parte crítica, que es la que vale nota: argumentá en un párrafo a favor de que la separación público-privado te ayudó a ver el caso con más claridad, y en otro párrafo en contra, mostrando dónde la línea entre lo privado y lo público resultó ser justamente lo que estaba en disputa. Si podés, conectá ese segundo párrafo con la objeción feminista clásica de que lo personal es político."}
 ],
 cuestionario:[
   {q:"Si no hay verdad moral objetiva, ¿el compromiso de Rorty contra la crueldad no queda sin fundamento y por lo tanto es arbitrario?", p:"Conviene separar dos cosas que la pregunta junta: sin fundamento no es lo mismo que arbitrario. Arbitrario sería un compromiso adoptado al azar o intercambiable por cualquier otro; el de Rorty es el resultado de una historia larga y específica —la tradición liberal, Mill, Shklar, la experiencia del siglo XX— y está tan firmemente instalado en él como podría estarlo si creyera que Dios lo ordena. Su argumento es que la expectativa de fundamentación es un residuo teológico: esperamos que nuestros compromisos vengan respaldados por algo más grande porque durante siglos creímos que los mandaba alguien, y cuando eso se cayó salimos a buscar un sustituto —la Razón, la Naturaleza Humana, la Estructura del Lenguaje— en lugar de notar que el compromiso seguía funcionando sin respaldo. La analogía que él usa: nadie deja de querer a sus hijos al enterarse de que ese amor tiene una explicación evolutiva y biográfica. Ahora la objeción seria, que Rorty nunca despachó del todo. Lo que se pierde al abandonar la verdad moral no es la motivación propia sino la posibilidad de decir que otra comunidad, entera y coherente, está equivocada. Una sociedad esclavista con criterios internamente consistentes no comete ningún error según sus propias normas, y si la justificación es siempre justificación ante alguna comunidad, no queda claro desde dónde se la condena. Rorty responde que basta con decir que nosotros no somos así y con tratar de ampliar el nosotros, y hay que evaluar con honestidad si eso alcanza o si es un cambio de tema."},
   {q:"¿Es compatible su etnocentrismo declarado con escuchar de verdad críticas no occidentales como la de Dussel?", p:"Rorty tiene una respuesta preparada y hay que darle su mejor versión antes de atacarla. Dice que nadie puede salir de su propia piel: toda justificación se dirige a alguna audiencia concreta con criterios concretos, y quien afirma hablar desde ningún lugar simplemente no examinó desde dónde habla. Su etnocentrismo sería entonces la posición honesta, no la arrogante, y además se trataría de un etnocentrismo peculiar: el de una cultura que incorporó entre sus valores el de escuchar a los extraños, de modo que puede ser transformada por quienes excluye. La réplica desde Dussel es precisa y no se contesta sola. Primero, el mito de la modernidad consiste exactamente en eso: una cultura particular se atribuye una apertura o un desarrollo superior y de ahí deriva que los demás deban entrar en su conversación, en sus términos y a su ritmo. Segundo, la ampliación del nosotros mantiene la iniciativa del lado de quien amplía: los excluidos son incorporados cuando la comunidad decide incorporarlos, nunca interpelan desde afuera obligando a rehacer las reglas. Eso es justamente lo que Dussel llama la diferencia entre incluir y escuchar analécticamente. La defensa más fuerte de Rorty es su acusación de simetría: Dussel tampoco habla desde ningún lugar, su criterio de la vida viene de una tradición profética y levinasiana, y la diferencia es que Rorty admite su particularidad. La contradefensa de Dussel es que el hambre no es una preferencia cultural sino una negatividad constatable. Ahí el desacuerdo es real y no se disuelve: se trata de si hay hechos que obliguen moralmente por sí mismos o si siempre hace falta una descripción que los vuelva significativos."},
   {q:"La separación entre lo público y lo privado, ¿resuelve el problema o lo esconde?", p:"El dispositivo es elegante: la autocreación irónica va a lo privado, la solidaridad a lo público, y la filosofía se ahorra la pretensión de una teoría única que responda a la vez cómo vivir y qué debo a los demás. Rorty argumenta que esa pretensión produjo dos monstruos simétricos, el metafísico que convierte su proyecto privado en obligación para todos y el crítico que le exige a la literatura que sea políticamente correcta. Pero la objeción se impone rápido y viene de varios frentes. La primera es feminista y es la más fuerte: lo personal es político, y trazar la línea entre las dos esferas no es un gesto descriptivo sino una decisión política de primer orden, porque históricamente lo que se declaró privado —la familia, el cuerpo, el trabajo doméstico, la violencia dentro de la casa— fue precisamente lo que quedó fuera del alcance de la justicia. La segunda es de clase: la autocreación irónica requiere tiempo, lectura, seguridad material y una vida lo bastante protegida como para poder jugar con las propias descripciones, de modo que la esfera privada de Rorty se parece bastante a la biografía de un profesor universitario. La tercera es interna: si el ironista no puede exponer públicamente sus dudas radicales sin desmoralizar a la comunidad liberal, entonces la ironía se vuelve un secreto de élite, y una posición que debe ocultarse para no hacer daño es filosóficamente sospechosa. Rorty concedía parte de esto: nunca sostuvo que la línea fuera natural ni fija, solo que no hace falta unificar las dos esferas en una teoría. La pregunta que queda abierta es si esa modestia le alcanza o si, como sostienen sus críticos, evita el problema al declararlo mal planteado."},
   {q:"Su predicción de 1998 sobre un hombre fuerte elegido por el resentimiento obrero resultó asombrosamente acertada. ¿Eso valida su filosofía?", p:"Conviene resistir el entusiasmo, porque el propio Rorty sería el primero en no aceptar el argumento. El pasaje de Forjar nuestro país que circuló tanto después de 2016 es una previsión política sobre el efecto de haber abandonado el discurso económico y nacional a la derecha, y su acierto habla bien de su olfato sociológico, no de su antifundacionalismo. Ninguna de sus tesis filosóficas centrales —que la mente no es un espejo, que la verdad no es correspondencia, que no hay fundamentos últimos— gana ni pierde nada con que un pronóstico electoral se haya cumplido. Peor todavía: tratar el acierto como validación sería exactamente la clase de movimiento que Rorty rechaza, el de suponer que una teoría es verdadera porque se corresponde con lo que después ocurrió. Un pragmatista consecuente diría, como mucho, que el vocabulario con el que describió a la izquierda estadounidense resultó ser una herramienta útil para anticipar un proceso, y que esa utilidad es todo lo que puede pedirse; pero también debería agregar que muchos otros lo anticiparon desde marcos teóricos incompatibles con el suyo. Y hay una segunda cuestión, más interesante: el diagnóstico puede ser correcto y la receta discutible. Que la izquierda cultural haya desatendido la desigualdad económica es defendible; que raza y clase puedan separarse como él sugiere lo es mucho menos, y ahí las críticas de Cornel West y de buena parte de la tradición afroamericana tienen bastante que decirle."},
   {q:"¿En qué se separa Rorty de Peirce, y quién sale mejor parado de esa separación?", p:"Los dos son pragmatistas y los dos rechazan que la verdad sea una copia de la realidad, pero la diferencia es de fondo. Peirce define la verdad como la opinión destinada a ser aceptada por todos los que investiguen, al final de una indagación indefinidamente prolongada, y la realidad como el objeto de esa opinión. Esa definición hace un trabajo preciso: conserva una norma que va más allá de cualquier consenso actual, de modo que toda la comunidad presente puede estar equivocada, y explica por qué la investigación tiene sentido como esfuerzo autocorrectivo y no como conversación indefinida. Rorty considera que ese final ideal es un sustituto laico de Dios: nunca podremos saber si llegamos, la idea no orienta ninguna decisión concreta y lo único que agrega es consuelo metafísico. Para él basta con la justificación ante audiencias cada vez más amplias y exigentes, sin punto de llegada. El costo de su posición es el que sus críticos señalan sin descanso: si la verdad no es más que justificación ante los nuestros, se pierde la diferencia entre estar justificado y tener razón, y con ella la posibilidad de decir que una comunidad completa se equivoca —que es justo lo que Peirce quería preservar y lo que Putnam le reclamaba. El costo de la posición de Peirce es que su final de la indagación es un ideal regulativo del que no hay ninguna evidencia y que, como concepto operativo, no le dice a ningún investigador qué hacer hoy. La discusión no está cerrada, y el mejor modo de tomarle el peso es preguntarse qué se estaría dispuesto a decirle a una sociedad entera que considera justo lo que nosotros consideramos monstruoso."}
 ],
 cadena:{ titulo:"Sin fundamento, ¿por qué la crueldad importa?", intro:"Un razonamiento en ramas sobre la objeción que más se le hizo a Rorty: si no hay una naturaleza humana ni derechos fundados en la razón, ¿con qué se condena la crueldad? Rorty adoptó la definición de Judith Shklar: liberal es quien cree que la crueldad es lo peor que hacemos. Las ramas recorren su respuesta —el etnocentrismo asumido y la educación sentimental— y sus límites.", inicio:"n1", nodos:{
   n1:{ pregunta:"Rorty niega que haya un fundamento metafísico para los derechos humanos o la solidaridad: no hay una esencia humana que descubrir. Si eso es cierto, ¿qué razón queda para oponerse a la crueldad?", opciones:[
     {texto:"Ninguna: sin fundamento, todo vale lo mismo.", va:"n2a"},
     {texto:"No hace falta un fundamento: alcanza con volverse más sensible al sufrimiento de otros.", va:"n2b"} ]},
   n2a:{ pregunta:"Rorty responde que nadie sostiene en serio que toda creencia valga lo mismo que cualquier otra. Lo que él sostiene es que la justificación es siempre ante alguien, en algún vocabulario, y que no hay un punto de vista fuera de todos los vocabularios. ¿Eso es relativismo?", opciones:[
     {texto:"Sí: si no hay fundamento, todo es cuestión de cultura y nada más.", final:{tipo:"revisar", texto:"Rorty rechaza esa etiqueta, y no por cortesía. El relativismo, en el sentido en que se lo critica, dice que todas las creencias son igual de buenas. Rorty dice algo distinto: que justificamos desde donde estamos —lo llama etnocentrismo— y que desde ahí algunas creencias son mejores que otras, y se puede argumentar por qué. Lo que niega es que esa mejora se pueda medir contra la realidad tal como es en sí. Volvé un paso y probá la otra respuesta."}},
     {texto:"No: sin fundamento último, sigue habiendo razones mejores y peores dentro de una comunidad que conversa.", va:"n3a"} ]},
   n3a:{ pregunta:"Pero si la justificación es siempre ante un «nosotros», ¿qué pasa con quien está fuera de ese «nosotros», en una comunidad que aprueba la crueldad?", opciones:[
     {texto:"Rorty propone ampliar el «nosotros»: el progreso moral consiste en incluir a cada vez más gente en el círculo de quienes nos importan.", final:{tipo:"bien", texto:"Es la respuesta de Contingencia, ironía y solidaridad: la solidaridad no se descubre, se construye, ampliando el círculo. La crítica más fuerte es que solo convence a quien ya es liberal: a quien no quiere ampliar su círculo, Rorty no tiene un argumento que no presuponga lo que se discute. Y él lo admite."}},
     {texto:"Rorty no tiene un argumento contra el torturador que no comparte su vocabulario.", final:{tipo:"bien", texto:"Es cierto, y Rorty lo reconoce sin vueltas: no hay un argumento neutral que obligue a cualquiera a dejar de ser cruel. Lo que discute es que los fundamentalistas sí lo tengan: el torturador tampoco se convence con la razón pura o con la naturaleza humana. Lo que te queda es decidir si esa honestidad es una virtud de su posición o una confesión de que le falta algo. Putnam y Habermas pensaban lo segundo."}} ]},
   n2b:{ pregunta:"En «Derechos humanos, racionalidad y sentimentalismo» (1993), Rorty sostiene que el progreso moral lo hicieron menos los argumentos que las historias tristes y sentimentales: relatos que nos hacen ver a otros como personas que sufren. ¿Por qué historias y no argumentos?", opciones:[
     {texto:"Porque los argumentos convencen a quien ya comparte las premisas; las historias hacen que el otro aparezca como alguien que puede sufrir como nosotros.", va:"n3b"},
     {texto:"Porque los sentimientos son más verdaderos que la razón.", final:{tipo:"revisar", texto:"Rorty no dice eso: no cree que los sentimientos sean más verdaderos, porque no cree en la verdad como correspondencia con la realidad, ni para la razón ni para el sentimiento. Su punto es de eficacia histórica: qué cambió de hecho la manera en que la gente trata a otros. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Si el progreso moral se hace con historias, ¿cuál es el riesgo?", opciones:[
     {texto:"Que las historias también deshumanizan: la propaganda funciona con el mismo mecanismo.", final:{tipo:"bien", texto:"Es la objeción más seria: el sentimiento no trae su propio criterio, y la misma técnica narrativa que amplía el círculo puede achicarlo. Rorty respondería que el criterio es reducir la crueldad, y que eso no se deduce de las historias, sino que es la apuesta liberal. Te queda preguntar si esa apuesta no es un fundamento disfrazado."}},
     {texto:"Que las historias amplían el «nosotros» solo hacia quienes ya se parecen a nosotros.", final:{tipo:"bien", texto:"Es una crítica cercana a la de Cornel West: la empatía tiene sesgos, y responde mejor a quien nos resulta familiar. Si el progreso moral depende de la empatía, avanza más lento justo donde más falta hace. Rorty diría que por eso hacen falta más y mejores historias; sus críticos dirían que por eso hacen falta también instituciones y derechos que no dependan de que alguien nos conmueva."}} ]}
 }},
 reconstruccion:[
   { titulo:"Contra el espejo de la naturaleza (1979)",
     consigna:"Reconstruí el argumento central de La filosofía y el espejo de la naturaleza. Una pieza saca una conclusión idealista que Rorty no sostiene: dejala afuera y ordená el resto.",
     piezas:[
       {id:"p1", texto:"Desde Descartes, la filosofía moderna pensó la mente como un espejo que contiene representaciones, más o menos fieles, del mundo.", tipo:"premisa"},
       {id:"p2", texto:"Con esa imagen, la tarea de la filosofía pasó a ser la epistemología: decidir qué representaciones son exactas y servir así de tribunal para el resto de la cultura.", tipo:"premisa"},
       {id:"p3", texto:"Pero Sellars mostró que no hay un dato dado que justifique por sí solo, y Quine, que no hay verdades que dependan solo del significado: no hay un piso firme para ese tribunal.", tipo:"premisa"},
       {id:"p4", texto:"Entonces, justificar una creencia es una práctica social: dar razones ante otros, no comparar la creencia con la realidad.", tipo:"premisa"},
       {id:"p5", texto:"Por lo tanto, la filosofía debe abandonar la epistemología como fundamento de la cultura y pasar a ser una voz más en la conversación.", tipo:"conclusion"},
       {id:"px", texto:"Por lo tanto, el mundo externo no existe y todo es lenguaje.", tipo:"distractor"}
     ],
     ordenCorrecto:["p1","p2","p3","p4","p5"],
     explicacion:"El argumento toma dos críticas técnicas de la filosofía analítica (p3) y saca de ellas una conclusión sobre la filosofía entera. El punto débil está en el paso de p3 a p4: Sellars y Quine desmontan ciertos fundamentos, pero no necesariamente toda relación entre creencia y mundo. Autores como McDowell o el último Putnam sostienen que el mundo sí pone límites a lo que podemos justificar. Rorty responde con una distinción: el mundo causa nuestras creencias, pero no las justifica; justificar es algo que hacen las personas. La pieza sobrante confunde esto con idealismo: Rorty nunca negó que haya un mundo, sino que tenga un vocabulario propio que debamos copiar."},
   { titulo:"La ironista liberal (Contingencia, ironía y solidaridad, 1989)",
     consigna:"Reconstruí por qué, para Rorty, la ironía tiene que quedar en el ámbito privado. Una pieza atribuye a la ironista una consecuencia que Rorty rechaza: dejala afuera.",
     piezas:[
       {id:"i1", texto:"Toda persona tiene un vocabulario final: las palabras con las que justifica, en última instancia, sus acciones y su vida.", tipo:"premisa"},
       {id:"i2", texto:"La ironista tiene dudas radicales sobre su propio vocabulario final, porque conoció otros —por libros, por personas— que la impresionaron.", tipo:"premisa"},
       {id:"i3", texto:"Sabe que ningún argumento formulado en su vocabulario puede disolver esas dudas, y no cree que su vocabulario esté más cerca de la realidad que los otros.", tipo:"premisa"},
       {id:"i4", texto:"Una sociedad no puede organizarse sobre la duda radical acerca de su propio vocabulario: necesita un lenguaje público compartido.", tipo:"premisa"},
       {id:"i5", texto:"Por lo tanto, la ironía es asunto privado, de la creación de uno mismo; en lo público, la ironista liberal no ofrece fundamentos, sino la esperanza de reducir la crueldad y ampliar la solidaridad.", tipo:"conclusion"},
       {id:"ix", texto:"Por lo tanto, la ironista no puede sostener ninguna convicción con firmeza.", tipo:"distractor"}
     ],
     ordenCorrecto:["i1","i2","i3","i4","i5"],
     explicacion:"El argumento separa dos tareas: crearse a uno mismo, que es privado e irónico, y no ser cruel con los demás, que es público y liberal. El punto débil es i4 y la división que produce: muchas críticas, sobre todo feministas como la de Nancy Fraser, sostienen que lo privado también es político, y que la frontera entre lo público y lo privado es ella misma objeto de disputa. La pieza sobrante es lo que Rorty niega expresamente: en la introducción del libro retoma una frase que Isaiah Berlin toma de Schumpeter, según la cual lo propio de una persona civilizada es reconocer la validez relativa de sus convicciones y, aun así, defenderlas sin vacilar."}
 ],
 dilemas:[
   { titulo:"Los vecinos nuevos",
     intro:"Rorty sostiene que el progreso moral consiste en ampliar el círculo de quienes nos importan, y que eso se logra más con historias que con argumentos sobre la naturaleza humana. Este caso pone a prueba esa idea en un tema actual en Colombia: la xenofobia contra los migrantes venezolanos.",
     pasos:[
       { id:"p1", situacion:"En tu clase de once, varios estudiantes repiten frases despectivas sobre los venezolanos que llegaron al barrio: «vienen a quitar trabajo», «son todos ladrones». Querés trabajar el tema. ¿Cómo lo hacés?", opciones:[
         {texto:"Con datos: cifras de empleo, de delitos y de aporte económico de la migración.", consecuencia:"Los datos son necesarios y pueden desmontar afirmaciones falsas. Pero Rorty te advertiría que los argumentos convencen a quien ya está dispuesto a escucharlos: un estudiante que no ve al migrante como alguien como él va a encontrar la manera de discutir las cifras.", va:"p2"},
         {texto:"Con historias: crónicas y testimonios de familias migrantes, y si es posible, con la visita de alguien que cuente su experiencia.", consecuencia:"Es la educación sentimental de Rorty: hacer que el otro aparezca como alguien que puede sufrir, tener miedo y esperanza, como nosotros. No prueba nada; cambia quién cuenta como «nosotros».", va:"p2"},
         {texto:"Con los derechos humanos: todos somos iguales en dignidad, y la Constitución y los tratados lo dicen.", consecuencia:"Es lo que Rorty llamaría el camino fundacionalista. No está mal recordarlo, y las instituciones importan; pero para quien no siente al otro como igual, la frase «todos somos iguales en dignidad» suena a sermón, no a razón.", va:"p2"} ]},
       { id:"p2", situacion:"Un estudiante te responde: «Con historias tristes nos manipulan. Yo también le puedo contar historias de venezolanos que robaron». ¿Qué le contestás?", opciones:[
         {texto:"«Tenés razón: mejor quedémonos con los datos.»", consecuencia:"Tu estudiante encontró la objeción seria al método de Rorty: las historias también sirven para deshumanizar. Pero volver solo a los datos no la resuelve: las historias de robos ya están circulando, y los datos no las borran.", va:"p3"},
         {texto:"«Contalas. Y después preguntémonos qué hace cada historia: si te muestra a una persona o te vende una categoría entera.»", consecuencia:"Convertiste la objeción en un criterio: una historia que amplía el círculo te muestra a alguien en particular; una que lo achica convierte a una persona en ejemplo de un grupo. Es una distinción que Rorty no formula así, pero que su posición necesita.", va:"p3"},
         {texto:"«Esas historias son excepciones, no la regla.»", consecuencia:"Puede ser cierto, pero volviste a los datos sin decirlo, y él puede contestar con otra anécdota. Rorty te diría que la discusión no se gana demostrando que la mayoría es buena, sino logrando que le importe lo que le pasa a una persona concreta.", va:"p3"} ]},
       { id:"p3", situacion:"Al final del periodo, el ambiente del curso cambió un poco, pero dos estudiantes siguen igual. Te preguntás si fallaste. ¿Qué concluís?", opciones:[
         {texto:"«Fallé con ellos: no encontré la historia que les llegara.»", consecuencia:"Es la conclusión rortiana más honesta: no hay un argumento que obligue a cualquiera, y la ampliación del círculo es lenta y parcial. No significa que no haya que seguir intentándolo.", va:null},
         {texto:"«Algunos no cambian con historias. Por eso también hacen falta reglas: en el aula no se permite humillar a nadie, crea lo que crea.»", consecuencia:"Combinaste a Rorty con algo que él mismo defendía en lo público: instituciones liberales que protegen a las personas aunque no todos sientan solidaridad. La educación sentimental no reemplaza a las reglas.", va:null},
         {texto:"«Sin fundamento, no tengo derecho a imponerles lo que tienen que sentir.»", consecuencia:"Confundiste no tener fundamento metafísico con no tener razones. Rorty no diría que no tenés derecho a enseñar contra la crueldad: diría que lo hacés desde tu tradición liberal, sin pedir disculpas por eso.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar por qué, para Rorty, el progreso moral se hace más con historias que con argumentos sobre la naturaleza humana.",
       "Distinguí el etnocentrismo asumido de Rorty del relativismo según el cual todo vale lo mismo.",
       "Tomé en serio la objeción de que las historias también sirven para deshumanizar.",
       "Encontré un criterio para distinguir las historias que amplían el «nosotros» de las que lo achican.",
       "No confundí la falta de fundamento metafísico con la falta de razones para actuar.",
       "Pensé el papel de las reglas y las instituciones donde la empatía no alcanza.",
       "Formulé la objeción más fuerte a Rorty: que su posición solo convence a quien ya es liberal."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.rorty = { lecturas:[
 {titulo:"El espejo de la naturaleza, el vocabulario final y el ironista liberal", fuente:"Adolfo Vásquez Rocca, «Rorty: pragmatismo, ironismo liberal y solidaridad», Nómadas 12 (2005) — revista de acceso abierto, Universidad Complutense de Madrid", url:"https://revistas.ucm.es/index.php/NOMA/article/view/NOMA0505220273A",
  extracto:`La filosofía y el espejo de la naturaleza (1979) es una historia crítica de una metáfora. Según Rorty, la epistemología moderna se construyó sobre la imagen de la mente como un gran espejo que contiene representaciones, algunas exactas y otras no; conocer sería inspeccionar esas representaciones para verificar su fidelidad. Descartes la instaló al inventar la mente como espacio interior; Locke la convirtió en psicología de las ideas; Kant la sistematizó al hacer del conocimiento una relación entre conceptos e intuiciones.

Rorty sostiene que esa metáfora no es un error refutable sino una imagen de la que hay que salir: «no es que la imagen sea falsa, es que nos tiene atrapados». Su alternativa es el anti-representacionalismo: el lenguaje no representa el mundo, se usa para lidiar con él. Nos relacionamos causalmente con la realidad —el mundo nos golpea, nos resiste, nos condiciona— pero de ahí no se sigue que nuestras oraciones «se correspondan» con hechos. La verdad, dice retomando a Davidson, no es una relación de correspondencia sino un cumplido que hacemos a las oraciones que nos resultan justificadas.

De ahí una consecuencia sobre el papel de la filosofía, que este estudio formula sin rodeos: «los filósofos no tienen un conocimiento peculiar, superior». Si no hay un tribunal neutral de la razón, la filosofía deja de ser la disciplina que juzga a las otras y pasa a ser una voz más en la conversación de la humanidad: hermenéutica en lugar de epistemología, mantener viva la conversación en lugar de fundamentarla.

Contingencia, ironía y solidaridad (1989) traslada esto a la ética y la política. Rorty llama vocabulario final —o léxico último, según la traducción— al «conjunto de palabras que emplean para justificar sus acciones»: «bueno», «justo», «decente», «la revolución», «la Iglesia», «Cristo», «el libre mercado». Es final no porque sea correcto, sino porque más allá de él no hay argumento: solo queda repetirlo o cambiar de tema. Y lo que el ironista reconoce es precisamente «la contingencia y la fragilidad de sus léxicos últimos».

El ironista es quien alberga «dudas radicales y permanentes» sobre el vocabulario final que usa, sabe que los argumentos formulados en ese vocabulario no pueden disolver esas dudas, y acepta que «los términos mediante los cuales se describen a sí mismos están sujetos a cambio». Es lo contrario del metafísico, que cree que hay una verdad allí afuera que su vocabulario capta. Rorty insiste en que el ironismo no es cinismo: uno puede comprometerse firmemente con sus convicciones sabiendo que son contingentes.

El liberal, en la definición que Rorty toma de Judith Shklar, es quien piensa que la crueldad es lo peor que hacemos; el ironista liberal sostiene que «no hay nada más repugnante que el sufrimiento y la crueldad» y, a la vez, que esa convicción no tiene fundamento metafísico alguno — en esa doble conciencia consiste toda la ironía. De ahí su reformulación de la solidaridad: «la solidaridad humana no es cosa que dependa de la participación en una verdad común». No se descubre una naturaleza humana compartida; se amplía el «nosotros», incluyendo a más gente en el círculo de quienes cuentan como uno de los nuestros.

Para eso sirven más la novela, la etnografía y el reportaje que la teoría moral: «las principales contribuciones del intelectual moderno al progreso moral son las descripciones detalladas de variedades de dolor y humillación». No se convence a nadie con un argumento de que el dolor ajeno importa; se lo consigue haciéndole notar detalles concretos del sufrimiento de personas que antes le eran invisibles. Por eso Rorty puede decir que autores como Proust y James ofrecen «una redención a sus lectores, pero no una verdad redentora», y por eso propone reemplazar la meta de la objetividad por la de la solidaridad.`,
  comentario:"Rorty no argumenta que la epistemología sea falsa: argumenta que es una conversación que ya no vale la pena continuar, lo que es él mismo un movimiento pragmatista. La separación entre lo privado (la ironía, la autocreación) y lo público (la solidaridad, evitar la crueldad) es la clave de su liberalismo y también su punto más criticado. La pregunta del cuestionario sobre ciencia y astrología es exactamente donde sus críticos sostienen que su respuesta —preferimos vocabularios por sus consecuencias— resulta insuficiente."}
], preguntasLectura:[
 {q:"¿Qué metáfora critica Rorty en «La filosofía y el espejo de la naturaleza»?", opciones:["La del contrato social","La de la mente como espejo que contiene representaciones exactas del mundo","La de la caverna platónica","La del árbol del conocimiento"], r:"La de la mente como espejo que contiene representaciones exactas del mundo", why:"Rorty dice que no es una imagen falsa sino una que «nos tiene atrapados», instalada por Descartes y sistematizada por Kant."},
 {q:"¿Qué es un «vocabulario final» (o léxico último)?", opciones:["El último libro que uno lee","El conjunto de palabras que uno emplea para justificar sus acciones en última instancia","Un diccionario técnico de filosofía","El lenguaje de la ciencia madura"], r:"El conjunto de palabras que uno emplea para justificar sus acciones en última instancia", why:"Es final no porque sea correcto, sino porque más allá de él no queda argumento sino repetición; el ironista reconoce «la contingencia y la fragilidad de sus léxicos últimos»."},
 {q:"¿En qué consiste la ironía del «ironista liberal»?", opciones:["En burlarse de las convicciones ajenas","En sostener que la crueldad es lo peor que hacemos y a la vez que esa convicción carece de fundamento metafísico","En no tener convicciones","En creer que todo vale lo mismo"], r:"En sostener que la crueldad es lo peor que hacemos y a la vez que esa convicción carece de fundamento metafísico", why:"Rorty insiste en que ironismo no es cinismo: se puede estar firmemente comprometido con lo que se sabe contingente."},
 {q:"Según Rorty, ¿cómo se amplía la solidaridad?", opciones:["Demostrando una naturaleza humana común","Ampliando el «nosotros» mediante relatos concretos —novela, reportaje, etnografía— que hacen visible el sufrimiento ajeno","Mediante leyes internacionales","Con argumentos morales universales"], r:"Ampliando el «nosotros» mediante relatos concretos —novela, reportaje, etnografía— que hacen visible el sufrimiento ajeno", why:"De ahí su propuesta de reemplazar la meta de objetividad por la de solidaridad."}
]};
