/* ============================================================
   Ficha: sorjuana  ·  tradición: americana
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"sorjuana", trad:"americana", nombre:"Sor Juana Inés de la Cruz", fechas:"c. 1648–1695 · Nueva España (México)", escuela:"Pensamiento novohispano / barroco", icon:"🪶", profundizada:true,
 tesis:"El deseo de saber es una inclinación natural que Dios puso en el entendimiento, y no distingue entre hombres y mujeres: negárselo a las mujeres no tiene fundamento ni en la razón ni en la Escritura. Sor Juana lo defendió con su vida y con su obra, desde un convento de la Nueva España, en el siglo XVII, y lo argumentó con las herramientas de la teología, la historia y la experiencia. Su poesía filosófica, sobre todo el Primero sueño, muestra a la vez la grandeza y el límite del conocimiento humano: el entendimiento intenta abarcarlo todo, fracasa, y sin embargo vuelve a intentarlo.",
 obras:[
   {t:"Respuesta a sor Filotea de la Cruz (1691)", d:"La carta más famosa de la literatura colonial americana, y uno de los primeros textos de defensa del derecho de las mujeres al conocimiento escritos en América. El obispo de Puebla, Manuel Fernández de Santa Cruz, había publicado sin permiso una crítica teológica de Sor Juana y la había precedido de una carta firmada con el seudónimo «sor Filotea», que la elogiaba y al mismo tiempo le aconsejaba dedicarse a temas religiosos en lugar de profanos. Sor Juana responde con una autobiografía intelectual: cuenta cómo aprendió a leer a los tres años, cómo quería vestirse de hombre para ir a la universidad, cómo estudiaba en todas partes, incluso en la cocina. Y argumenta, con ejemplos de la Biblia y de la historia, que las mujeres pueden y deben estudiar."},
   {t:"Primero sueño (publicado en 1692)", d:"Su poema filosófico más ambicioso, casi mil versos en silvas, y uno de los grandes poemas del barroco en lengua española. Narra una noche en la que el cuerpo duerme y el alma, libre, intenta conocer el universo entero. Primero lo intenta de golpe, con una sola mirada intuitiva que abarque todo, y fracasa, deslumbrada por la inmensidad. Después lo intenta con método, subiendo paso a paso por las categorías de los seres, como enseñaba la escolástica, y también se detiene, abrumada por la dificultad de conocer siquiera una sola cosa. El poema termina con el amanecer y el despertar. Es una meditación sobre los límites del conocimiento, pero también sobre la audacia de intentar conocer."},
   {t:"Carta atenagórica o Crisis sobre un sermón (1690)", d:"Es la crítica teológica que desencadenó la Respuesta. Sor Juana discute un sermón del famoso predicador jesuita portugués Antonio Vieira sobre cuál fue la mayor fineza, es decir, la mayor prueba de amor, de Cristo. Vieira había corregido a varios Padres de la Iglesia; Sor Juana lo corrige a él, con argumentos escolásticos rigurosos. Que una monja criolla discutiera de teología con uno de los predicadores más célebres de su tiempo fue un escándalo. El obispo de Puebla la publicó con el título de «atenagórica», digna de la sabiduría de Atenea, y con la carta de sor Filotea."},
   {t:"Redondillas «Hombres necios que acusáis» y la lírica", d:"Su poesía amorosa y satírica circuló ampliamente en su época. Las redondillas que empiezan «Hombres necios que acusáis / a la mujer sin razón, / sin ver que sois la ocasión / de lo mismo que culpáis» son un argumento en verso contra la doble moral sexual: los hombres desean a las mujeres, las presionan, y después las acusan por haber cedido o las desprecian por no haberlo hecho. La pregunta final —quién tiene más culpa, «la que peca por la paga, o el que paga por pecar»— es un ejemplo de lógica aplicada a la crítica social. Escribió también sonetos filosóficos sobre el engaño de las apariencias, como el dedicado a su retrato."},
   {t:"Teatro, villancicos y el Neptuno alegórico", d:"Sor Juana fue también dramaturga y poeta de la corte virreinal. Escribió comedias, como Los empeños de una casa; autos sacramentales, como El divino Narciso, que incluye una loa donde aparecen la religión de los mexicas y la conquista; y numerosos villancicos para las catedrales, algunos con versos en náhuatl y en el habla de los esclavos africanos. El Neptuno alegórico (1680) es un arco triunfal de erudición mitológica para recibir al virrey. Estas obras muestran el mundo mestizo de la Nueva España, y su mezcla de la cultura europea con la indígena y la africana."}
 ],
 conceptos:[
   {t:"El derecho de las mujeres al saber", d:"Es la tesis central de la Respuesta, y una de las primeras defensas argumentadas de ese derecho en América. Sor Juana sostiene que la inclinación a saber es natural, puesta por Dios en el entendimiento, y que no hay razón para que se ejerza en los hombres y se prohíba en las mujeres. Lo argumenta con ejemplos: mujeres sabias de la Biblia, como Débora o la reina de Saba; de la Antigüedad, como Hipatia; y de la Iglesia, como santa Paula. Propone incluso que mujeres ancianas y doctas enseñen a las niñas, para evitar los peligros de que lo hagan maestros varones. Su argumento no rompe con la teología de su tiempo: la usa para abrir un espacio que esa misma teología cerraba."},
   {t:"El pasaje de san Pablo reinterpretado", d:"El principal argumento contra el estudio femenino era la frase de san Pablo: que las mujeres callen en la iglesia (mulieres in ecclesia taceant). Sor Juana no la niega, porque no podía hacerlo, sino que la interpreta: Pablo se refería a la predicación pública en el templo, no al estudio privado ni a la escritura. Y si fuera una prohibición general, ¿cómo explicar a las santas doctas que la Iglesia celebra? Es un ejemplo notable de cómo argumentar dentro de una autoridad que no se puede rechazar: no oponerse al texto, sino disputar su sentido."},
   {t:"El saber como camino hacia la teología", d:"En la Respuesta, Sor Juana explica que estudió todas las ciencias —lógica, retórica, física, aritmética, historia, música— porque las consideraba escalones necesarios para llegar a la teología, la reina de las ciencias. ¿Cómo entender la Escritura sin saber lógica, retórica, historia o música, si la Biblia está llena de argumentos, figuras, hechos y proporciones? El argumento es estratégico, porque justifica sus estudios profanos ante la Iglesia, pero también expresa una idea seria: el conocimiento es una unidad en la que todas las disciplinas se conectan."},
   {t:"«Si Aristóteles hubiera guisado...»", d:"Es una de las frases más citadas de la Respuesta. Le habían prohibido estudiar durante un tiempo, y Sor Juana cuenta que no podía dejar de observar: el trompo de unas niñas que jugaban le enseñaba sobre el movimiento circular; en la cocina, veía que el huevo se une y se fríe en la manteca y se despedaza en el almíbar. Y concluye: «si Aristóteles hubiera guisado, mucho más hubiera escrito». La frase hace dos cosas: muestra que la curiosidad no necesita libros, y reivindica como lugar de conocimiento un espacio asignado a las mujeres y despreciado por los filósofos."},
   {t:"Primero sueño: los dos métodos del conocimiento", d:"El poema pone en escena dos maneras de conocer, y las dos fracasan. La primera es la intuición: el alma intenta abarcar el universo entero de una sola mirada, y queda deslumbrada, como el ojo que mira el sol. La segunda es el método discursivo, el de la escolástica: subir paso a paso por las categorías, de los seres más simples a los más complejos. Pero el alma descubre que no puede comprender del todo ni siquiera una flor o una fuente. El fracaso no es una condena del conocimiento: es la conciencia de su límite, y el poema celebra la audacia de intentarlo, con la figura de Faetón, que se atrevió a conducir el carro del sol."},
   {t:"El silencio", d:"El silencio atraviesa la obra y la vida de Sor Juana. En la Respuesta dice que no ha escrito más sobre temas sagrados por respeto, y juega con la idea de callar: no callar por no tener qué decir, sino por tener demasiado. En 1693 y 1694, pocos años antes de morir, renunció a sus estudios, se deshizo de su biblioteca y de sus instrumentos, según la tradición, y firmó documentos de penitencia; uno de ellos con la fórmula «yo, la peor de todas». Si fue una conversión sincera o el resultado de una presión de la jerarquía eclesiástica, con el arzobispo Aguiar y Seijas como figura central, es uno de los debates más vivos sobre ella. Octavio Paz defendió la segunda lectura; otros estudiosos matizan."},
   {t:"La crítica de la doble moral", d:"Las redondillas «Hombres necios» son un argumento en verso. Los hombres reprochan a las mujeres lo que ellos mismos provocan: si ceden, son ligeras; si resisten, son crueles. Sor Juana muestra que el reproche es contradictorio, porque se condena a la mujer en todos los casos, y termina con un dilema: quién tiene más culpa, la que peca por la paga o el que paga por pecar. Es una crítica de la estructura social del deseo, que deja en los hombres el poder y en las mujeres la culpa. El poema fue muy popular y todavía se recita en las escuelas de América Latina."},
   {t:"El conocimiento y el cuerpo", d:"Sor Juana vivió en una época que asociaba a las mujeres con el cuerpo y a los hombres con la razón. En el Primero sueño, el conocimiento ocurre cuando el cuerpo duerme y el alma se libera; pero el poema también describe con detalle la fisiología del sueño y de la digestión, según la medicina de su tiempo. En la Respuesta cuenta que se cortaba el pelo si no aprendía algo en el plazo que se había fijado, porque no le parecía bien que una cabeza tan desnuda de saber estuviera vestida de cabello. La relación entre el cuerpo, la mente y el género es un hilo de su obra."},
   {t:"Criolla y novohispana", d:"Sor Juana nació en San Miguel Nepantla, al pie de los volcanes, hija natural de un militar español y de una mujer criolla. Vivió en la corte virreinal antes de entrar al convento de San Jerónimo, en la Ciudad de México, donde pudo leer y escribir. Su obra pertenece al barroco hispánico, pero también expresa una conciencia americana: incorpora la cultura mexica en El divino Narciso, el náhuatl y el habla de los africanos en sus villancicos, y fue llamada en su tiempo la Décima Musa y el Fénix de América. Es una de las figuras fundadoras del pensamiento latinoamericano, siglos antes de la independencia."}
 ],
 conexion:"Dialoga con la tradición escolástica y con <b>Aristóteles</b>, al que cita y corrige con humor desde la cocina. Su Primero sueño recoge el neoplatonismo y la ciencia hermética de su tiempo, en especial la de Athanasius Kircher, y anticipa la pregunta moderna por los límites del conocimiento que <b>Kant</b> formularía un siglo después. Su defensa del derecho de las mujeres al saber la conecta con <b>Simone de Beauvoir</b>, que sostuvo tres siglos más tarde que la situación de las mujeres es histórica y no natural. Fue reivindicada por <b>Leopoldo Zea</b> y por toda la historia de las ideas latinoamericanas como figura fundadora, y su biografía más influyente es Sor Juana Inés de la Cruz o las trampas de la fe (1982), de Octavio Paz. Los debates sobre su silencio final y sobre la autenticidad de algunos documentos siguen abiertos: conviene leer las fuentes con cuidado.",
 dialogo:{titulo:"«Que callen las mujeres»", lineas:[
   {quien:"Visitante", texto:"Madre Juana, vengo de parte de personas que la aprecian. Le aconsejan, con cariño, que deje los libros profanos y se dedique a lo que corresponde a una religiosa. San Pablo lo dijo: que las mujeres callen en la iglesia."},
   {quien:"Sor Juana", texto:"Agradezco el cariño, y respeto a san Pablo más que a nadie. Pero le pregunto: ¿dónde estamos? ¿En la iglesia, predicando desde el púlpito? Porque eso es lo que el apóstol prohíbe. Yo no predico: estudio en mi celda y escribo cuando me lo piden."},
   {quien:"Visitante", texto:"Es una sutileza. El sentido es que la mujer no debe enseñar ni discutir de cosas altas."},
   {quien:"Sor Juana", texto:"Si ese fuera el sentido, la Iglesia tendría que condenar a santa Paula, que sabía hebreo y griego, o a santa Catalina, que disputó con los sabios. Y la Escritura alaba a Débora, que juzgaba a Israel. O san Pablo se contradice con la Iglesia, o se refería a otra cosa. Yo prefiero pensar que no se contradice."},
   {quien:"Visitante", texto:"Pero, ¿para qué necesita una monja saber de astronomía, de música, de lógica?"},
   {quien:"Sor Juana", texto:"Para entender la teología, que es la reina de las ciencias. ¿Cómo leer las Escrituras sin lógica, si están llenas de argumentos? ¿Sin retórica, si están llenas de figuras? ¿Sin historia, si cuentan hechos? ¿Sin música, si hablan de proporciones y armonías? Todas las ciencias son escalones para llegar a la que las corona."},
   {quien:"Visitante", texto:"Dicen que una vez le prohibieron estudiar, y que usted no obedeció."},
   {quien:"Sor Juana", texto:"Obedecí: no toqué un libro. Pero no me pudieron prohibir que mirara. Veía a unas niñas jugar con un trompo y pensaba en el movimiento circular. Veía en la cocina que el huevo se une en la manteca y se despedaza en el almíbar. Si Aristóteles hubiera guisado, mucho más hubiera escrito."},
   {quien:"Visitante", texto:"Eso suena a soberbia, madre."},
   {quien:"Sor Juana", texto:"Llámelo como quiera. Yo no estudio para escribir ni para enseñar, sino para ver si estudiando ignoro menos. Esta inclinación me la dio Dios; si es un defecto, es de Él, no mío. Y si alguien piensa que el entendimiento de una mujer vale menos, que me lo demuestre con razones, no con costumbres."},
   {quien:"Visitante", texto:"¿Y si un día le pidieran que dejara todo?"},
   {quien:"Sor Juana", texto:"No sé qué haría. Sé que hay silencios que no son de quien calla, sino de quien obliga a callar.", nota:"Las respuestas sobre san Pablo, las santas doctas, la teología como reina de las ciencias, el trompo, la cocina y Aristóteles siguen de cerca la Respuesta a sor Filotea. La última línea es una reconstrucción: alude a su renuncia de 1693-1694, cuyo sentido —conversión o presión— sigue en discusión."}
 ]},
 actividades:[
   {t:"Si Aristóteles hubiera guisado: filosofía en la cocina", d:"Durante una tarde, observá con atención un espacio cotidiano que la filosofía suele ignorar: la cocina de tu casa, un taller, un mercado, un cultivo. Anotá tres fenómenos que te hagan preguntas —por qué el arroz se infla, por qué el azúcar se vuelve caramelo, por qué el agua hierve más rápido con tapa— y, para cada uno, escribí qué te pregunta y qué hipótesis tenés. Terminá con una página sobre la frase de Sor Juana: ¿qué conocimientos se pierden cuando la filosofía desprecia los lugares y los trabajos asignados a las mujeres o a los pobres?"},
   {t:"Reinterpretar una autoridad que no se puede rechazar", d:"Sor Juana no rechaza la frase de san Pablo: disputa su sentido. Elegí una norma o frase de autoridad que hoy se use para limitar algo —una regla del manual de convivencia de tu colegio, un dicho familiar, una interpretación de la ley—. Escribí un texto en el que, sin rechazarla, propongas una interpretación distinta y más justa, con argumentos: ¿a qué se refería originalmente?, ¿hay casos que la contradicen?, ¿qué consecuencias absurdas tendría la lectura más restrictiva? Al final, evaluá si tu estrategia es más eficaz que el rechazo frontal."},
   {t:"Las redondillas como argumento", d:"Leé completas las redondillas «Hombres necios que acusáis» y reconstruí su argumento en prosa: cuáles son las premisas, cuál es la contradicción que Sor Juana denuncia y cuál es la conclusión. Después, buscá un ejemplo actual de doble moral sobre el comportamiento de las mujeres —en canciones, redes sociales o conversaciones— y escribí una estrofa o un párrafo que lo critique con la misma lógica. Terminá con una reflexión: ¿por qué un argumento en verso puede tener más efecto que uno en prosa?"}
 ],
 cuestionario:[
   {q:"¿Es Sor Juana feminista, o es un anacronismo leerla así?", p:"La palabra «feminismo» no existía en el siglo XVII, y aplicarla sin matices es un anacronismo: Sor Juana no pedía derechos políticos ni cuestionaba la autoridad de la Iglesia. Pero su defensa del derecho de las mujeres al conocimiento tiene rasgos que el feminismo posterior reconoció como propios: sostiene que la capacidad de entender no depende del sexo, denuncia la doble moral de los hombres, y critica que se use la costumbre en lugar de la razón para limitar a las mujeres. Lo más preciso es decir que es una precursora: argumenta dentro de los marcos de su tiempo —la teología, la Escritura, la autoridad de los santos— para abrir un espacio que esos mismos marcos cerraban. Su estrategia, interpretar la autoridad en vez de rechazarla, es en sí misma una enseñanza sobre cómo pensar en condiciones de poca libertad."},
   {q:"¿Qué muestra el Primero sueño sobre los límites del conocimiento?", p:"El poema narra dos intentos del alma de conocer el universo. El primero es intuitivo: abarcar todo de una sola mirada, que fracasa porque el entendimiento queda deslumbrado. El segundo es metódico, siguiendo las categorías de la escolástica, y fracasa porque el alma descubre que ni siquiera puede comprender del todo una sola cosa, como una flor o una fuente. Pero el poema no es una renuncia al conocimiento: celebra la audacia de intentarlo, con la figura de Faetón, que fracasó intentando conducir el carro del sol y, sin embargo, dejó un ejemplo de valor. En ese sentido, Sor Juana anticipa preguntas de la filosofía moderna sobre los límites de la razón. El poema termina con el amanecer: el despertar del cuerpo y la vuelta al mundo cotidiano, sin una conclusión triunfal. Es una de las grandes meditaciones sobre el deseo de saber escritas en español."},
   {q:"¿Fue la renuncia final de Sor Juana una conversión o una derrota?", p:"Es uno de los debates más vivos. Los hechos que se conocen son que, entre 1693 y 1694, Sor Juana renovó sus votos, firmó documentos de penitencia y, según la tradición, se deshizo de su biblioteca y de sus instrumentos científicos; murió en 1695, durante una epidemia, cuidando a otras monjas. Octavio Paz sostuvo que fue una derrota: la presión del arzobispo Aguiar y Seijas, conocido por su misoginia, y la pérdida de sus protectores en la corte, la obligaron a callar. Otros estudiosos sostienen que hubo una conversión sincera, en un contexto de crisis —hambrunas, motines— que pudo llevarla a un giro espiritual. Investigaciones recientes discuten también si realmente se deshizo de toda su biblioteca. La pregunta no tiene una respuesta cerrada, y las dos lecturas pueden ser parcialmente ciertas. Lo que sí muestra es lo frágil que era el espacio que había conquistado."},
   {q:"¿Por qué Sor Juana usa argumentos teológicos para defender el estudio de las mujeres, en lugar de argumentos puramente racionales?", p:"Porque escribía en una sociedad donde la teología era la autoridad suprema, y donde un argumento contra la Iglesia no solo habría sido ineficaz, sino peligroso: la Inquisición estaba activa en la Nueva España. Pero sería un error ver su uso de la teología solo como estrategia. Sor Juana era creyente, y su argumento es coherente dentro de ese marco: si Dios dio a las mujeres un entendimiento y una inclinación a saber, prohibirles ejercerlos va contra el orden divino. A la vez, su argumento tiene una parte racional que no depende de la fe: la capacidad de entender no varía con el sexo, y la costumbre no es una razón. Su estrategia muestra algo útil para cualquier época: cómo argumentar dentro de un marco que no se puede abandonar, disputando la interpretación de sus autoridades."},
   {q:"¿Qué aporta Sor Juana a la historia del pensamiento latinoamericano?", p:"Sor Juana es una de las figuras fundadoras del pensamiento americano, siglo y medio antes de la independencia. Su obra muestra que la Nueva España no era solo un lugar donde llegaban las ideas europeas, sino donde se pensaba con ellas de manera propia: su teología discute con los mayores predicadores europeos, su poesía filosófica está a la altura de la de Góngora, y su obra incorpora la cultura indígena y africana del mundo colonial. Para Leopoldo Zea y la historia de las ideas latinoamericanas, ella encarna una conciencia criolla que empezaba a reconocerse distinta de España. Su defensa del derecho de las mujeres al saber, además, abre una línea que llega hasta hoy. Que una mujer, monja y criolla, del siglo XVII, haya escrito con esa audacia es en sí mismo un hecho que desmiente la idea de que en América no hubo filosofía."}
 ],
 cadena:{ titulo:"¿Por qué calló Sor Juana?", intro:"Un razonamiento en ramas sobre el final de la vida de Sor Juana: entre 1693 y 1694, después de la polémica que desencadenó la Respuesta a sor Filotea, renunció a sus estudios y firmó documentos de penitencia. Las ramas recorren las interpretaciones y lo que cada una enseña sobre el poder y el conocimiento.", inicio:"n1", nodos:{
   n1:{ pregunta:"Sor Juana defendió en 1691 el derecho de las mujeres al saber. Dos años después, renovó sus votos, firmó una penitencia con la fórmula «yo, la peor de todas» y, según la tradición, se deshizo de su biblioteca. ¿Cómo explicarlo?", opciones:[
     {texto:"Fue una conversión sincera: una crisis espiritual la llevó a abandonar lo profano.", va:"n2a"},
     {texto:"Fue una derrota: la presión de la jerarquía eclesiástica la obligó a callar.", va:"n2b"} ]},
   n2a:{ pregunta:"Esos años fueron de crisis en la Ciudad de México: hambrunas, epidemias y el motín de 1692. Sor Juana era creyente. ¿Basta eso para explicar la renuncia como conversión?", opciones:[
     {texto:"Sí: no hay que suponer una presión externa si la explicación religiosa alcanza.", final:{tipo:"bien", texto:"Es una lectura que varios estudiosos defienden, y que tiene la virtud de tomar en serio la fe de Sor Juana, en lugar de verla solo como una intelectual atrapada. El costo es que deja de lado la coincidencia temporal: la renuncia llega justo después de una polémica pública y en un momento en que perdía a sus protectores. Una conversión sincera y una presión real no son incompatibles."}},
     {texto:"No del todo: una conversión puede ser sincera y, al mismo tiempo, haber ocurrido bajo presión.", va:"n3a"} ]},
   n3a:{ pregunta:"Si conversión y presión pueden coexistir, ¿qué enseña el caso sobre el conocimiento?", opciones:[
     {texto:"Que el espacio para pensar depende de condiciones que no controla quien piensa: protectores, instituciones, el clima de una época.", final:{tipo:"bien", texto:"Es la lección más amplia del caso. Sor Juana pudo estudiar mientras tuvo el apoyo de la corte virreinal y un margen de tolerancia en la Iglesia; cuando ese apoyo se debilitó, el espacio se cerró. El conocimiento no es solo una facultad individual: necesita condiciones sociales, y esas condiciones han sido históricamente más frágiles para las mujeres."}},
     {texto:"Que no se puede saber nada de las intenciones de una persona del pasado, y que hay que dejar de especular.", final:{tipo:"bien", texto:"Es una prudencia metodológica razonable: los documentos son escasos y algunos se discuten. Pero no impide interpretar: se puede reconstruir el contexto, comparar fuentes y proponer hipótesis más o menos plausibles, que es lo que hace la historia. La prudencia no debe volverse una manera de no preguntar por el poder."}} ]},
   n2b:{ pregunta:"Octavio Paz sostuvo que el arzobispo Aguiar y Seijas, conocido por su desprecio por las mujeres, y la pérdida de sus protectores en la corte, la obligaron a callar. ¿Qué apoya esa lectura?", opciones:[
     {texto:"La coincidencia temporal con la polémica, la fragilidad de su posición y el tono de los documentos de penitencia.", va:"n3b"},
     {texto:"Una carta en la que Sor Juana dice expresamente que la obligaron.", final:{tipo:"revisar", texto:"No se conoce una carta así. La lectura de Paz es una interpretación del contexto, no la lectura de una confesión explícita. Es importante no atribuir a las fuentes lo que no dicen. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Si fue una derrota, ¿qué queda de su defensa del derecho al saber?", opciones:[
     {texto:"Queda intacta como argumento: que la hayan obligado a callar no refuta lo que dijo.", final:{tipo:"bien", texto:"Es la distinción entre la validez de un argumento y el destino de quien lo formula. Los argumentos de la Respuesta siguen siendo tan buenos como en 1691. Y su silencio forzado, si lo fue, se convierte en una prueba de lo que denunciaba: que a las mujeres se les negaba el derecho a pensar en público."}},
     {texto:"Queda debilitada: si ella misma renunció, quizá no estaba tan convencida.", final:{tipo:"revisar", texto:"Confundís el argumento con la conducta posterior de quien lo formuló. Que alguien abandone una posición bajo presión, o incluso por convicción, no la vuelve falsa: hay que evaluar sus razones. Volvé un paso y probá la otra respuesta."}} ]}
 }},
 reconstruccion:[
   { titulo:"El derecho de las mujeres a estudiar (Respuesta a sor Filotea)",
     consigna:"Reconstruí el argumento de Sor Juana a favor del estudio de las mujeres. Una pieza contradice la estrategia de Sor Juana, que interpreta la autoridad en lugar de rechazarla: dejala afuera y ordená el resto.",
     piezas:[
       {id:"s1", texto:"La inclinación a saber es natural y fue puesta por Dios en el entendimiento humano, sin distinción de sexo.", tipo:"premisa"},
       {id:"s2", texto:"La Escritura y la historia de la Iglesia celebran a mujeres sabias, como Débora, santa Paula o santa Catalina.", tipo:"premisa"},
       {id:"s3", texto:"La frase de san Pablo que manda callar a las mujeres se refiere a la predicación pública en el templo, no al estudio privado ni a la escritura.", tipo:"premisa"},
       {id:"s4", texto:"Si se la entendiera como una prohibición general, la Iglesia tendría que condenar a las santas doctas que ella misma celebra.", tipo:"premisa"},
       {id:"s5", texto:"Por lo tanto, no hay razón ni en la naturaleza ni en la Escritura para prohibir que las mujeres estudien, y la costumbre que lo prohíbe no es una razón.", tipo:"conclusion"},
       {id:"sx", texto:"Por lo tanto, las palabras de san Pablo no tienen autoridad y pueden ignorarse.", tipo:"distractor"}
     ],
     ordenCorrecto:["s1","s2","s3","s4","s5"],
     explicacion:"El argumento combina una premisa sobre la naturaleza (s1), ejemplos (s2) y una interpretación de la autoridad bíblica (s3) apoyada en una reducción al absurdo (s4). El punto débil es s3: la interpretación es plausible, pero discutible, y un adversario podría sostener que Pablo quería decir algo más amplio. Sor Juana no puede rechazar la autoridad del texto, así que su fuerza depende de que su lectura sea más convincente que la otra. La pieza sobrante es lo que ella no podía ni quería decir: su estrategia es disputar el sentido de la autoridad, no negarla."},
   { titulo:"La doble moral (redondillas «Hombres necios que acusáis»)",
     consigna:"Reconstruí en prosa el argumento de las redondillas de Sor Juana. Una pieza invierte la conclusión del poema: dejala afuera.",
     piezas:[
       {id:"r1", texto:"Los hombres desean a las mujeres y las presionan para que cedan a ese deseo.", tipo:"premisa"},
       {id:"r2", texto:"Si una mujer cede, la acusan de ligera; si resiste, la acusan de cruel o de ingrata.", tipo:"premisa"},
       {id:"r3", texto:"Por lo tanto, la mujer es condenada en todos los casos: haga lo que haga, el reproche está asegurado.", tipo:"premisa"},
       {id:"r4", texto:"Además, el hombre es la ocasión de aquello mismo que culpa: provoca la conducta que después condena.", tipo:"premisa"},
       {id:"r5", texto:"Por lo tanto, la culpa recae sobre todo en quien provoca y paga, más que en quien cede: «¿o cuál es más de culpar... la que peca por la paga, o el que paga por pecar?».", tipo:"conclusion"},
       {id:"rx", texto:"Por lo tanto, las mujeres son responsables de las tentaciones de los hombres.", tipo:"distractor"}
     ],
     ordenCorrecto:["r1","r2","r3","r4","r5"],
     explicacion:"Las redondillas muestran una contradicción (r2-r3): una norma que condena en todos los casos no es una norma moral, sino una forma de poder. Después atribuyen la responsabilidad a quien provoca (r4-r5). El punto débil es que el poema reparte culpas dentro del mismo marco moral que critica —habla de «pecar»—, y no cuestiona el marco mismo. Para su época, sin embargo, invertir la dirección de la culpa era una audacia. La pieza sobrante es exactamente la doble moral que el poema denuncia."}
 ],
 dilemas:[
   { titulo:"Daniela y la olimpiada",
     intro:"Sor Juana defendió que la inclinación a saber no distingue entre hombres y mujeres, y que la costumbre no es una razón para limitarla. Este caso lleva esa idea a una estudiante de un municipio del Tolima, hoy.",
     pasos:[
       { id:"p1", situacion:"Daniela, de quince años, vive en un municipio del Tolima y ayuda en la tienda familiar. Su profesor la invitó a prepararse para las olimpiadas regionales de matemáticas, lo que le exige dos tardes por semana. Su padre dice que «eso no le sirve para nada» y que la necesitan en la tienda; a su hermano menor, en cambio, lo dejan ir a entrenar fútbol. Daniela te pide consejo. ¿Qué le decís?", opciones:[
         {texto:"«Tu familia te necesita. Hay que obedecer a los padres.»", consecuencia:"Es el argumento de la costumbre y la autoridad que Sor Juana discutió. No dice que obedecer esté mal, pero no responde a la pregunta de fondo: por qué lo que se le permite al hermano se le niega a ella.", va:"p2"},
         {texto:"«Andá a las olimpiadas aunque tu papá no quiera.»", consecuencia:"Defendés su derecho a estudiar, pero proponés un enfrentamiento abierto, que puede tener costos para Daniela. Sor Juana eligió otro camino: no rechazar la autoridad, sino disputar sus razones.", va:"p2"},
         {texto:"«Preguntémosle a tu papá por qué el fútbol de tu hermano sí sirve y las matemáticas tuyas no.»", consecuencia:"Es la estrategia de Sor Juana: no rechazar la autoridad del padre, sino pedirle razones y mostrar la contradicción. Si la diferencia es solo «porque es mujer», la costumbre queda al descubierto.", va:"p2"} ]},
       { id:"p2", situacion:"El padre responde: «Las matemáticas no le van a dar de comer. En cambio, la tienda sí». ¿Qué le respondés?", opciones:[
         {texto:"«Tiene razón: hay que ser práctico.»", consecuencia:"Aceptaste un criterio de utilidad inmediata. Sor Juana diría que el saber no se mide solo por lo que da de comer hoy, y que, además, la curiosidad de Daniela es una inclinación que merece cultivarse. También podrías recordarle que estudiar puede abrirle caminos que la tienda no le abre.", va:"p3"},
         {texto:"«Puede que la tienda le dé de comer hoy. Pero el estudio le puede dar opciones que ni usted ni yo imaginamos. ¿Y si probamos un semestre, organizando los turnos?»", consecuencia:"Respondiste dentro del marco del padre —la utilidad—, pero ampliándolo, y propusiste un acuerdo concreto. Es la estrategia de Sor Juana: argumentar con las razones del otro para abrir un espacio que él cerraba.", va:"p3"},
         {texto:"«Daniela es buena en matemáticas. Es un desperdicio que no lo aproveche.»", consecuencia:"Es verdad, pero el argumento del talento puede volverse un problema: ¿y si Daniela fuera solo curiosa, sin ser la mejor? Sor Juana defendía el derecho a saber de cualquier mujer, no solo de las excepcionales.", va:"p3"} ]},
       { id:"p3", situacion:"Daniela va a las olimpiadas y no gana. Su padre le dice: «Ya ve, perdió el tiempo». Ella te pregunta si valió la pena. ¿Qué le decís?", opciones:[
         {texto:"«Sí, porque aprendiste mucho, aunque no hayas ganado.»", consecuencia:"Es la idea de Sor Juana: no estudiaba para ganar ni para enseñar, sino para ver si, estudiando, ignoraba menos. El valor del saber no depende de un premio.", va:null},
         {texto:"«No, si no ganaste.»", consecuencia:"Mediste el estudio por el resultado, como el padre. Sor Juana celebraba en el Primero sueño la audacia de intentar conocer aunque se fracase: el valor está en el intento.", va:null},
         {texto:"«Valió la pena, y lo que más valió fue que te dejaron intentarlo. Eso hay que defenderlo para tu hermana menor también.»", consecuencia:"Sumaste a la experiencia de Daniela la dimensión social: el derecho a intentar no es solo individual, y Sor Juana lo defendió para todas las mujeres, no solo para ella.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar el argumento de Sor Juana sobre el derecho de las mujeres al saber.",
       "Identifiqué en el caso la diferencia entre una razón y una costumbre.",
       "Usé la estrategia de Sor Juana: disputar las razones de una autoridad en lugar de rechazarla sin más.",
       "Reconocí la doble medida entre lo que se le permite al hermano y a Daniela.",
       "Valoré el saber por sí mismo, no solo por su utilidad inmediata o por un premio.",
       "Pensé en las condiciones familiares y económicas, sin despreciar las razones del padre.",
       "Formulé la objeción más fuerte: que en una familia con necesidades económicas reales, la estrategia de Sor Juana puede no alcanzar."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.sorjuana = { lecturas:[
 {titulo:"Respuesta a sor Filotea de la Cruz: la inclinación a saber", fuente:"Síntesis de trabajo sobre la Respuesta a sor Filotea de la Cruz (1691); para la vida y la obra, Wikipedia en español", url:"https://es.wikipedia.org/wiki/Juana_In%C3%A9s_de_la_Cruz",
  extracto:`En 1690, el obispo de Puebla publicó sin permiso un texto teológico de Sor Juana, en el que ella discutía un sermón del famoso predicador jesuita Antonio Vieira. Lo precedió de una carta firmada con un seudónimo femenino, «sor Filotea de la Cruz», que elogiaba su inteligencia y, al mismo tiempo, le aconsejaba dedicarla a los asuntos sagrados en lugar de los profanos.

Sor Juana respondió en 1691 con una larga carta que es, a la vez, una autobiografía intelectual y una defensa del derecho de las mujeres al conocimiento. Cuenta que aprendió a leer a los tres años, siguiendo a escondidas a una hermana mayor a la escuela; que, de niña, pidió que la vistieran de hombre para poder ir a la universidad de México; y que se cortaba el pelo si no había aprendido algo en el plazo que se había fijado, porque no le parecía bien que una cabeza tan desnuda de saber estuviera vestida de cabello.

Explica que entró al convento porque era lo más compatible con su deseo de estudiar, y que esa inclinación le vino de Dios. Estudió todas las ciencias —lógica, retórica, física, aritmética, historia, música— porque las consideraba escalones para llegar a la teología. Y cuenta que, cuando le prohibieron estudiar durante un tiempo, no pudo dejar de observar: el trompo de unas niñas le enseñaba sobre el movimiento, y la cocina sobre las transformaciones de las sustancias. «Si Aristóteles hubiera guisado, mucho más hubiera escrito.»

La segunda parte de la carta es argumentativa. Sor Juana cita a mujeres sabias de la Biblia y de la historia, y discute la frase de san Pablo según la cual las mujeres deben callar en la iglesia: se refiere, dice, a la predicación pública, no al estudio privado. Propone incluso que mujeres mayores y doctas enseñen a las niñas.`,
  comentario:"Fijate en la estrategia: Sor Juana nunca rechaza la autoridad de la Iglesia ni de la Escritura; disputa su interpretación. Y fijate en cómo combina dos registros: la autobiografía, que muestra que su inclinación es natural, y el argumento, que muestra que no hay razón para prohibirla. Pocos años después de esta carta, Sor Juana renunció a sus estudios; el sentido de esa renuncia sigue en discusión."}
], preguntasLectura:[
 {q:"¿Por qué escribió Sor Juana la Respuesta a sor Filotea?", opciones:["Para pedir permiso para salir del convento","Para responder a una carta que le aconsejaba abandonar los asuntos profanos","Para criticar al virrey","Para renunciar a la escritura"], r:"Para responder a una carta que le aconsejaba abandonar los asuntos profanos", why:"El obispo de Puebla, bajo el seudónimo de sor Filotea, la elogiaba y a la vez le aconsejaba dedicarse a lo sagrado."},
 {q:"¿Cómo interpreta Sor Juana la frase de san Pablo que manda callar a las mujeres?", opciones:["Como una prohibición absoluta de estudiar","Como una frase sin autoridad","Como una prohibición referida a la predicación pública, no al estudio privado","Como un error del traductor"], r:"Como una prohibición referida a la predicación pública, no al estudio privado", why:"Sor Juana no rechaza la autoridad del texto: disputa su sentido."},
 {q:"¿Qué quiere mostrar con la frase «Si Aristóteles hubiera guisado, mucho más hubiera escrito»?", opciones:["Que Aristóteles cocinaba mal","Que la curiosidad no necesita libros y que la cocina también es un lugar de conocimiento","Que las mujeres deben quedarse en la cocina","Que la filosofía es inútil"], r:"Que la curiosidad no necesita libros y que la cocina también es un lugar de conocimiento", why:"Reivindica como lugar de saber un espacio asignado a las mujeres y despreciado por los filósofos."}
]};
