/* ============================================================
   Ficha: vasconcelos  ·  tradición: americana
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"vasconcelos", trad:"americana", nombre:"José Vasconcelos", fechas:"1882–1959 · México", escuela:"Filosofía latinoamericana", icon:"🌎", profundizada:true,
 tesis:"América Latina no es un continente fallido por su mezcla, sino el laboratorio de una síntesis futura: la quinta raza o raza cósmica, formada por el cruce de las cuatro razas históricas y destinada a inaugurar un tercer período de la humanidad regido por la estética y no por la fuerza ni por el cálculo utilitario. La tesis fue escrita contra las ideologías de pureza racial de su época y contra el expansionismo anglosajón, y sin embargo está formulada en el mismo vocabulario racial, eugenésico y jerárquico que dice combatir: esa tensión no se resuelve leyéndolo con simpatía ni descartándolo de un plumazo, y es el motivo por el que sigue discutiéndose un siglo después.",
 obras:[
   {t:"La raza cósmica (1925)", d:"Su obra más célebre, más influyente y más incómoda. El libro reúne un ensayo doctrinal y un diario de viaje por Brasil, Argentina y Uruguay, y su marco es una filosofía de la historia: cuatro troncos raciales —el negro, el indio, el mongólico y el blanco— habrían protagonizado sucesivamente la historia humana y estarían convergiendo en una quinta raza síntesis, hecha con la sangre y el genio de todos los pueblos y por eso, sostiene Vasconcelos, más capaz de fraternidad y de visión universal que cualquiera de sus componentes. La cuna de esa quinta raza sería Iberoamérica, porque la colonización ibérica, con toda su violencia, produjo mezcla donde la anglosajona produjo exclusión y exterminio. El argumento es doblemente polémico para su momento: niega la tesis entonces dominante de que el mestizaje degenera, y niega el destino manifiesto estadounidense que justificaba la tutela del norte sobre el sur. Pero el mismo libro contiene los pasajes que hoy resultan indefendibles, donde habla de tipos inferiores que irían desapareciendo voluntariamente por obra de la ley del gusto, y donde el ascenso hacia la síntesis se describe con un lenguaje de mejoramiento y selección tomado directamente de la eugenesia de los años veinte. Leerlo entero, y no en citas sueltas, es la única manera de sostener un juicio informado sobre él."},
   {t:"Indología (1926)", d:"Conjunto de conferencias dictadas en Puerto Rico, Santo Domingo y Panamá, publicadas al año siguiente, donde Vasconcelos desarrolla y matiza lo que había comprimido en el ensayo anterior. El título es deliberado: propone una indología —un estudio de lo indoamericano— como disciplina propia frente a la indología orientalista europea y frente a la sociología positivista importada. Aquí el peso se desplaza de la biología a la cultura: discute el paisaje, la economía, la lengua, la religión y el arte de Iberoamérica como factores que producen un tipo humano distinto, y responde a las objeciones que había recibido, entre ellas la de que su quinta raza era una fantasía sin base científica. Es el libro donde su antiimperialismo se vuelve más explícito y más concreto, y donde formula con mayor claridad la idea de que el continente necesita una filosofía que no sea traducción de la europea. También es donde queda expuesto el punto ciego: reconoce el aporte indígena a la cultura común, pero lo trata casi siempre como sustrato o materia prima de una síntesis futura, no como una tradición intelectual viva con derecho a continuar siendo ella misma."},
   {t:"Ulises criollo (1935)", d:"Primer volumen de su gran autobiografía y, para muchos lectores, su mejor libro en términos puramente literarios. Narra su infancia en la frontera de Piedras Negras —donde cruzaba a diario a estudiar a Estados Unidos y aprendió a discutir de patria con sus compañeros de escuela—, su formación de abogado, su entrada en el Ateneo de la Juventud junto a Antonio Caso, Alfonso Reyes y Pedro Henríquez Ureña, y su participación directa en la Revolución Mexicana. Importa filosóficamente por dos razones. La primera es que muestra de dónde vienen sus categorías: la oposición entre lo sajón y lo latino no es para él una tesis de gabinete sino una experiencia biográfica temprana, lo que explica a la vez su fuerza retórica y su falta de rigor comparativo. La segunda es que es un documento de primera mano sobre la generación que derribó el positivismo oficial del porfiriato, y sobre cómo un grupo de jóvenes intelectuales pasó de leer a Bergson y a Schopenhauer a ocupar ministerios. La continúan La tormenta, El desastre y El proconsulado, cada vez más amargas, y ese ensombrecimiento progresivo es él mismo un dato sobre su trayectoria política."},
   {t:"Estética (1935)", d:"Su sistema filosófico más extenso y ambicioso, y el menos leído de todos sus libros. Tras haber sido secretario de Educación, candidato presidencial derrotado y exiliado, Vasconcelos intentó aquí lo que ninguna de sus obras anteriores había hecho: construir una filosofía completa y arquitectónica, con su metafísica, su teoría del conocimiento y su ética, todas ordenadas bajo una categoría estética. La tesis del monismo estético sostiene que la realidad última es energía en ritmo, que el universo asciende por planos —físico, biológico, espiritual— y que la coordinación de esos planos se realiza según leyes de armonía más parecidas a la composición musical que a la deducción lógica. Su valor está en que aquí el famoso lema de la estética por encima de la lógica deja de ser consigna y se convierte en un argumento desarrollado y por lo tanto discutible. Su límite es evidente para cualquier lector formado: el sistema no dialoga con la filosofía técnica de su tiempo, se apoya en analogías más que en pruebas y buena parte de su física es ya obsoleta al escribirse. Vale la pena conocerlo aunque sea para medir la distancia entre el Vasconcelos ensayista, que tuvo enorme influencia, y el Vasconcelos sistemático, que casi no tuvo ninguna."},
   {t:"Su gestión como Secretario de Educación Pública (1921–1924)", d:"No es un libro, y sin embargo es la obra donde estas ideas se pusieron a prueba en la realidad: Vasconcelos es el raro caso de un filósofo que dispuso de un presupuesto estatal para aplicar su programa. Creó la Secretaría de Educación Pública, multiplicó el gasto educativo del país, fundó bibliotecas por miles, lanzó campañas masivas de alfabetización con maestros voluntarios llamados honoríficos, y organizó las misiones culturales, brigadas que recorrían el campo formando maestros rurales y llevando higiene, música, oficios y lectura a comunidades sin escuela. Editó por decenas de miles ejemplares baratos de Homero, Platón, Dante, Goethe y Cervantes, con el argumento —discutido entonces y ahora— de que el pueblo merecía los clásicos y no versiones simplificadas. Encargó a Diego Rivera, José Clemente Orozco y David Alfaro Siqueiros los muros de los edificios públicos, decisión que fundó el muralismo mexicano y convirtió al Estado en el mayor mecenas artístico del continente. Para la Universidad Nacional escribió el lema que todavía lleva: por mi raza hablará el espíritu. Todo esto es coherente con su filosofía —si la estética es la vía superior, educar es antes que nada formar sensibilidad— y todo esto es también el mejor argumento a favor de que su pensamiento no se agota en los pasajes que hoy rechazamos."}
 ],
 conceptos:[
   {t:"La raza cósmica o quinta raza", d:"Su tesis central y la fuente de toda la controversia. Vasconcelos sostiene que la historia ha sido protagonizada por cuatro troncos raciales y que en América Latina se está gestando, por mestizaje biológico y cultural simultáneo, una quinta raza que los sintetiza y los supera, no por eliminación sino por fusión. Hay que ser exacto sobre dos cosas a la vez. La primera es lo que la tesis niega: niega la jerarquía fija de razas, niega que la mezcla degenere y niega que exista una raza destinada a dominar, tres negaciones que en 1925 iban contra la corriente principal de la antropología y la política internacional. La segunda es lo que la tesis conserva: conserva la raza como unidad real de análisis histórico, describe a las poblaciones con adjetivos valorativos y proyecta la síntesis como un mejoramiento, es decir, mantiene intacto el supuesto de que existen tipos humanos mejores y peores y solo cambia la ruta para llegar al mejor. El vocabulario es explícitamente eugenésico en varios pasajes y no tiene sentido disimularlo: habla de selección, de eliminación de tipos inferiores y de un cruce dirigido por el gusto. Un lector honesto debe poder enunciar las dos mitades sin que la segunda anule su interés por la primera ni la primera lo absuelva de la segunda."},
   {t:"El mestizaje como valor y no como defecto", d:"Es el núcleo que sobrevivió a la crítica y el que explica su influencia continental. En su época la tesis dominante, sostenida por la antropología europea, por la eugenesia estadounidense y por buena parte de las élites latinoamericanas, era que el cruce racial producía degeneración y que el atraso del continente se explicaba por su población mestiza; en Argentina, Brasil y México se diseñaron políticas de inmigración europea con el objetivo declarado de blanquear la población. Contra eso, Vasconcelos afirma que la mezcla no es la enfermedad de América sino su aporte al mundo, y que la colonización ibérica, precisamente por no haber logrado separar poblaciones como sí lo hizo la anglosajona, produjo algo nuevo. La motivación es antirracista en su contexto, y también antiimperialista: el blanco de su polémica es la doctrina Monroe, el destino manifiesto y el panamericanismo tutelado desde Washington. La objeción posterior no niega ese mérito, sino que muestra lo que el elogio del mestizaje hizo políticamente en México y en el resto del continente: convertirse en ideología de Estado que declara resuelto el problema racial y vuelve invisible la desigualdad concreta que siguen padeciendo poblaciones indígenas y afrodescendientes."},
   {t:"La estética por encima de la lógica", d:"Vasconcelos propone una periodización de la historia humana en tres estados. El primero es el material o guerrero, donde rige la fuerza bruta y las uniones se deciden por conquista. El segundo es el intelectual o político, el de la razón, la norma jurídica y el cálculo, que él identifica con la modernidad y con la hegemonía anglosajona. El tercero, todavía por venir, es el estético o espiritual, en el que las decisiones humanas se guiarán por el gusto y por el amor, y donde lo que él llama la ley del gusto sustituirá tanto a la coerción como a la selección natural darwiniana. La idea filosófica de fondo es que el conocimiento estético no es un adorno del racional sino una forma superior de aprehensión, porque capta lo concreto y singular allí donde el concepto solo captura lo general. En su Estética esto se convierte en el monismo estético, con la idea de que la realidad es energía en ritmo y que la armonía, y no la deducción, es la ley de coordinación del universo. La objeción obvia es que la periodización se afirma más que se prueba, y que un tercer estado guiado por el gusto ofrece muchas menos garantías contra el abuso que el aburrido segundo estado de las normas jurídicas."},
   {t:"Crítica al utilitarismo y al pragmatismo anglosajón", d:"Vasconcelos lee el pragmatismo de James y de Dewey como la expresión filosófica de un tipo cultural: una filosofía sajona centrada en la eficacia, el rendimiento y el resultado medible, incapaz por principio de reconocer un valor que no se traduzca en utilidad. A eso opone un espíritu latino más contemplativo, más estético y más religioso, para el que la belleza y la emoción no son medios de nada. La contraposición tuvo una enorme fortuna retórica en América Latina y conviene examinarla en lugar de repetirla, porque es débil en las dos direcciones. Hacia el pragmatismo: Dewey no reduce el valor a la ganancia, su criterio de utilidad es la resolución efectiva de un problema y su obra sobre el arte como experiencia dedica un libro entero a sostener que lo estético es la plenitud de la experiencia ordinaria, justo lo contrario del utilitarismo que se le atribuye. Hacia lo latino: la caracterización de un espíritu compartido por todos los pueblos de lengua ibérica es una generalización cultural tan gruesa como las que Vasconcelos denuncia cuando las aplican en su contra. Lo que sí queda en pie, y merece discutirse en serio, es su sospecha de que una cultura organizada íntegramente en torno a la eficiencia carece de criterios para decidir para qué sirve la eficiencia."},
   {t:"La educación como misión civilizatoria", d:"Es el punto donde su filosofía se convirtió en política pública y el que mejor resiste el paso del tiempo. Si la estética es la vía superior de conocimiento, entonces educar no es instruir ni capacitar para el mercado, sino formar sensibilidad y ponerla en contacto con lo mejor que se ha producido. De ahí decisiones concretas y verificables: campañas de alfabetización con voluntarios, misiones culturales que llevaban maestros itinerantes al campo, bibliotecas populares, ediciones baratas y masivas de los clásicos griegos y europeos, y el encargo de los grandes murales públicos a Rivera, Orozco y Siqueiros, que hizo del muro del edificio estatal el libro de quien no sabía leer. La coherencia con su filosofía es completa. Las objeciones también son reales y vale conocerlas: el programa era misionero y vertical, llevaba la cultura hacia abajo en vez de partir de la que ya existía en las comunidades; la elección de Homero y Dante antes que de las tradiciones locales muestra qué cultura contaba como cultura; y varios de sus propios muralistas terminaron enfrentados con él por razones políticas. Aun así, es difícil encontrar en el siglo XX otro caso en que un filósofo haya transformado tan directamente la vida cultural de un país."},
   {t:"Indigenismo ambivalente", d:"Vasconcelos reivindica lo indígena como uno de los componentes indispensables de la síntesis americana, en abierto contraste con las élites que lo consideraban un lastre, y su gestión educativa dedicó recursos reales a las comunidades rurales indígenas. Pero el modo en que lo reivindica contiene una subordinación estructural: lo indígena aparece casi siempre como aporte, sustrato o materia de una síntesis futura cuya forma final no será indígena, y la lengua, la religión y la organización política propias no se presentan como tradiciones con derecho a continuar sino como elementos que se integran. Por eso su indigenismo se distingue del que vendrá después. El indigenismo autonomista posterior, y con mucha más fuerza los movimientos indígenas contemporáneos, reclaman exactamente lo contrario: no ser integrados en una identidad mestiza nacional sino ser reconocidos como pueblos con instituciones, territorios y filosofías propias. Desde esa perspectiva, el elogio del mestizaje deja de ser una defensa y pasa a ser un mecanismo de asimilación, y la crítica se vuelve más incisiva porque no lo acusa de despreciar lo indígena sino de celebrarlo mientras planifica su desaparición en el conjunto."},
   {t:"Monismo estético", d:"El sistema metafísico de su vejez, poco leído incluso entre especialistas. Su punto de partida es que la unidad del universo no es material ni lógica sino rítmica: lo real es energía que asciende por planos sucesivos —el físico, donde predomina la caída y la dispersión; el biológico, donde aparece la organización; y el espiritual, donde la energía se coordina según armonía— y el método adecuado para captar esa coordinación no es la deducción sino algo más cercano a la composición musical. De ahí que llame a su filosofía monismo estético: no hay dos sustancias ni una materia y una forma, hay un solo proceso cuya ley interna es estética. El sistema tiene el mérito de dar contenido argumentativo a lo que en sus ensayos era proclama, y de intentar una metafísica escrita desde América y no importada. Sus problemas son serios: apoya pasos decisivos en analogías, se vale de una física ya superada al momento de escribirse, y no discute con ninguna de las corrientes filosóficas técnicas de su tiempo, de modo que quedó al margen de toda conversación posterior. Es, en cierto modo, el reverso exacto de su destino público: el libro donde más filosofía hay es el que nadie leyó."},
   {t:"El giro político posterior", d:"Después de perder la elección presidencial de 1929 en un proceso que consideró fraudulento, y tras un largo exilio, Vasconcelos se desplazó hacia posiciones cada vez más conservadoras, nacionalistas e hispanistas, con un catolicismo militante y una hostilidad creciente hacia la Revolución que él mismo había servido. El episodio más grave es la revista Timón, que dirigió en 1940 y que recibió financiamiento de la legación alemana, en cuyas páginas aparecieron artículos de simpatía hacia el régimen nazi y su política. Vasconcelos minimizó después el asunto y hay discusión entre historiadores sobre cuánto escribió él de lo publicado, pero la dirección de la revista y la orientación general no están en duda. Esto complica su legado de un modo que no se puede eludir: el mismo autor que había escrito el alegato continental contra la pureza racial terminó, quince años más tarde, dirigiendo una publicación favorable al régimen que llevó esa pureza a su consecuencia extrema. Hay dos maneras razonables de leerlo. Una sostiene que se trata de una deriva biográfica de un hombre amargado, sin relación lógica con su obra anterior. La otra sostiene que un pensamiento que nunca abandonó la categoría de raza y que confiaba en el espíritu antes que en las instituciones ofrecía menos resistencia a ese deslizamiento de la que él creía. Ninguna de las dos se ha impuesto."},
   {t:"Por mi raza hablará el espíritu", d:"El lema que escribió en 1921 para la Universidad Nacional Autónoma de México y que la institución conserva hasta hoy es el mejor resumen de todo el problema en cinco palabras. Su sentido original es antirracista y espiritualista: contra quienes decían que la raza mestiza americana estaba condenada por su sangre, Vasconcelos responde que lo que definirá a esa raza no será su biología sino su cultura, y que hablará por ella el espíritu, es decir, la educación y la creación artística. Leído así, el lema niega el determinismo racial en el acto mismo de invocar la raza. Pero también se le puede leer en otra clave: conserva la raza como el sujeto de la historia, le asigna una misión y una voz colectiva, y sitúa a la universidad como el órgano por el que esa misión se cumple, un esquema que en la Europa de esos mismos años producía consecuencias muy distintas. Que el lema siga vigente en la universidad más grande del continente, y que se lo discuta periódicamente, muestra que este módulo no trata un debate cerrado de historia de las ideas sino algo que sigue en uso."}
 ],
 conexion:"Su pregunta —si América Latina puede pensar desde su propia circunstancia en vez de traducir sistemas europeos— será retomada por <b>Leopoldo Zea</b>, que la conserva y le quita el marco racial, reemplazando la raza por la historia y la circunstancia como sujeto del pensamiento americano. <b>Enrique Dussel</b> irá más lejos y desplazará el centro de gravedad del mestizaje a la víctima y al excluido, con lo que la síntesis vasconceliana aparece ya no como solución sino como parte del problema. Su crítica al pragmatismo lo enfrenta directamente con <b>Dewey</b> y <b>James</b>, aunque la caricatura que hace de ellos debilita su propio argumento, y su ambición de una filosofía sistemática nacida de una cultura no europea lo vuelve comparable con <b>Nishida Kitarō</b>, incluidas las zonas oscuras: ambos construyeron una filosofía de la identidad cultural que después mostró poca resistencia frente a los nacionalismos de los años cuarenta.",
 dialogo:{titulo:"El vocabulario que se hereda", lineas:[
   {quien:"Estudiante", texto:"Maestro, vengo con una incomodidad y no con una pregunta cortés. Leí La raza cósmica entera, no en citas. Usted dice que quiere terminar con el racismo, y sin embargo escribe de mejorar la raza, de seleccionar, de tipos inferiores que irían desapareciendo. ¿No es eso exactamente el mismo paradigma que dice rechazar, con el signo cambiado?"},
   {quien:"Vasconcelos", texto:"Escuche primero contra quién escribí. En 1925 los tratados de antropología que se estudiaban en su facultad y en la mía decían que el mestizo era un degenerado y que América Latina estaba condenada por su sangre. Los gobiernos de este continente, incluido el mío, importaban europeos con el propósito declarado de blanquear a su propia población. Yo dije lo contrario: que la mezcla era nuestra ventaja y nuestro aporte al mundo."},
   {quien:"Estudiante", texto:"Le concedo eso entero. Pero mi objeción no es sobre su intención, es sobre su vocabulario. Usted podía haber dicho que la raza no existe como categoría explicativa. No lo dijo. Dijo que la nuestra va a ser la mejor."},
   {quien:"Vasconcelos", texto:"Nadie escribe fuera de su siglo. Los términos que usted me reprocha eran los únicos disponibles para discutir el asunto en público, y si yo hubiera declarado inexistente la raza, mi libro no habría entrado en la discusión que quería ganar. Se usa el idioma del adversario para vencerlo."},
   {quien:"Estudiante", texto:"Ahí es donde no lo sigo. Hay una diferencia entre usar una palabra y aceptar el criterio que la sostiene. Usted no solo dice raza: dice que hay tipos superiores e inferiores y que los inferiores irán desapareciendo. Eso no es un término prestado, es una tesis suya. Y si es suya, entonces no cambió de paradigma, cambió de favorito dentro del mismo paradigma."},
   {quien:"Vasconcelos", texto:"Yo no propuse eliminar a nadie. Escribí que esa desaparición sería voluntaria, por obra de la ley del gusto, porque en el tercer estado nadie será obligado a unirse con nadie y las uniones se harán por amor y por belleza. Es lo contrario de la esterilización forzosa que en esos mismos años se practicaba en los Estados Unidos con respaldo legal."},
   {quien:"Estudiante", texto:"Eso empeora el argumento en vez de salvarlo, y le digo por qué. Si el gusto es libre, usted no puede predecir su resultado; y si usted predice que el resultado será la desaparición de ciertos tipos, es porque supone que el gusto es universal y que coincide con cierto ideal de belleza. ¿De dónde salió ese ideal? Porque en su siglo, y en el mío, se parece bastante al europeo."},
   {quien:"Vasconcelos", texto:"Es la objeción más seria que me han hecho y no voy a fingir que tengo una respuesta redonda. Le respondo lo que puedo: mi ley del gusto quiere ser lo opuesto de la selección darwiniana, que premia al fuerte. Quiere que la historia deje de decidirse por la fuerza y pase a decidirse por lo que se ama.", nota:"Conviene detenerse aquí porque este es el punto exacto donde se abre el debate académico vivo sobre cómo leer el libro hoy, y las dos posiciones son defendibles con el texto en la mano. Una sostiene que se trata de un texto genuinamente progresista para su tiempo: ataca la pureza racial, el darwinismo social y el imperialismo estadounidense cuando eso era una posición minoritaria y costosa, y su marco racial es el envoltorio de época de una tesis integracionista. La otra sostiene que el marco no es envoltorio sino estructura: mientras la raza siga siendo el sujeto de la historia y la síntesis se describa como mejora, el pensamiento sigue siendo jerárquico aunque invierta el orden de los puestos, y el resultado práctico fue una ideología del mestizaje que en México y en el resto del continente sirvió para declarar inexistente un racismo que seguía operando. Ninguna de las dos lecturas ha desplazado a la otra, y el estudiante que se quede solo con una de ellas habrá entendido la mitad del problema."},
   {quien:"Estudiante", texto:"Le acepto la intención. Ahora déjeme mostrarle qué pasó después con su libro, que es lo que a mí me toca. En mi país y en el suyo se enseñó durante décadas que somos todos mestizos y que por eso aquí no hay racismo. Mientras tanto el color de la piel siguió prediciendo el ingreso, la escuela y el trato policial. Su celebración de la mezcla terminó siendo la coartada perfecta para no mirar eso."},
   {quien:"Vasconcelos", texto:"Un autor no responde por todos los usos de su obra."},
   {quien:"Estudiante", texto:"Responde por los usos que su obra facilita. Si usted declara que la síntesis ya está en marcha y que es nuestra gloria continental, le está entregando a cualquier gobierno el argumento para decir que el problema está resuelto. Y responde también por otra cosa: los pueblos indígenas de los que usted habla con respeto no querían ser ingredientes de una síntesis. Querían seguir siendo ellos mismos, con su lengua y su territorio."},
   {quien:"Vasconcelos", texto:"Ahí me toca de veras. Yo llevé maestros y libros a comunidades que el Estado había abandonado durante cuatro siglos, y estoy orgulloso de eso. Pero es cierto que fui a llevar y no a aprender. Pensé la misión cultural como quien lleva la luz, no como quien va a encontrarse con algo que ya estaba encendido."},
   {quien:"Estudiante", texto:"Y queda una última cosa, la más dura. En 1940 usted dirigió la revista Timón, con dinero de la legación alemana y con simpatías hacia el régimen nazi. El hombre que escribió contra la pureza racial terminó dirigiendo una publicación favorable al gobierno que la llevó al exterminio. ¿Cómo se lee su libro después de eso?"},
   {quien:"Vasconcelos", texto:"No le voy a pedir que separe al hombre de la obra, porque esa separación siempre le conviene al acusado. Le pido otra cosa, que es más difícil: que lea el libro preguntándose en qué puntos exactos mi manera de pensar no ofreció resistencia a aquello en lo que terminé.", nota:"El episodio de Timón es documentado y no está en discusión en lo esencial, aunque los historiadores debaten cuánto del contenido escribió él personalmente y cómo pesaron su amargura tras la derrota electoral de 1929 y su antiamericanismo. Lo que importa filosóficamente es la pregunta que el propio diálogo deja abierta y que se le hace también a Heidegger y a Nishida: si una obra que conserva la categoría de destino colectivo de un pueblo ofrece o no algún freno interno frente a ese deslizamiento. Sostener que no hay ninguna relación es tan cómodo como sostener que la obra entera queda anulada; el trabajo serio consiste en señalar los puntos concretos de contacto y también los pasajes que resisten."}
 ]},
 actividades:[
   {t:"Leer un pasaje y separar las dos mitades", d:"Buscá en La raza cósmica un pasaje donde Vasconcelos describa la formación de la quinta raza —el capítulo del ensayo doctrinal sirve, y la edición está disponible completa en la sección de Lecturas de esta ficha— y copiá textualmente entre diez y quince líneas. Después armá dos columnas sobre ese mismo fragmento, sin salirte de él. En la primera anotá todo lo que en 1925 era una posición minoritaria y valiente: la negación de que la mezcla degenere, el rechazo de la jerarquía fija de razas, la crítica al expansionismo del norte, el reconocimiento del aporte indígena y africano. En la segunda anotá cada expresión que hoy resulta indefendible, y al lado escribí por qué: no basta con marcarla, tenés que decir qué supuesto la sostiene. Terminá con dos párrafos. En el primero respondé si las dos columnas pueden convivir en un mismo autor sin contradicción, o si una anula a la otra. En el segundo hacé el ejercicio incómodo: identificá una idea tuya, actual, formulada con el vocabulario disponible hoy, que dentro de cien años podría aparecer en la segunda columna."},
   {t:"El mestizaje en tu propio país, hoy", d:"Vasconcelos escribió sobre México, pero la ideología del mestizaje se volvió discurso oficial en casi toda América Latina, Colombia incluida. Reuní tres fuentes actuales y reales de tu entorno: un texto escolar de ciencias sociales, un discurso político o una campaña publicitaria que hable de la identidad nacional, y una nota periodística o un informe sobre desigualdad racial o sobre comunidades indígenas o afrodescendientes. Analizá las tres con dos preguntas fijas. Primera: ¿la mezcla aparece como un hecho consumado que ya resolvió el problema de la desigualdad, o como un proceso que convive con jerarquías vigentes? Segunda: ¿los pueblos indígenas y afrodescendientes aparecen en presente, con voz propia y demandas concretas, o aparecen en pasado, como ingredientes de lo que hoy somos todos? Escribí dos páginas contrastando lo que encontrás con lo que Vasconcelos sostiene, y cerrá tomando partido de forma explícita sobre una sola pregunta: en tu país, el discurso del mestizaje hoy, ¿protege contra el racismo o lo vuelve más difícil de nombrar?"},
   {t:"Poner a prueba la estética por encima de la lógica", d:"Vasconcelos sostiene que hay un modo estético de conocer que capta lo que el concepto no alcanza. En vez de discutir la tesis en abstracto, ponela a prueba con un caso propio. Elegí una situación de tu vida en la que hayas comprendido algo importante —sobre una persona, sobre una decisión, sobre vos mismo— por una vía que no fue el razonamiento: una obra, una música, un duelo, una imagen, una experiencia que no supiste argumentar y sin embargo te reorganizó. Describila en detalle, sin adornarla. Después hacé tres cosas. Primero, intentá reconstruir en forma de argumento explícito lo que aprendiste, y anotá cuánto se pierde en la traducción y qué es exactamente lo que se pierde. Segundo, buscá un caso opuesto y sé honesto: una ocasión en que una convicción fuerte, emocionalmente intensa y estéticamente convincente resultó ser simplemente falsa, y el análisis frío tuvo razón contra ella. Tercero, escribí un párrafo de conclusión respondiendo si de tu experiencia se sigue que lo estético es una forma superior de conocimiento, o una forma distinta con sus propios modos de fallar; y si es lo segundo, explicá qué queda en pie de la tesis de Vasconcelos y qué no."}
 ],
 cuestionario:[
   {q:"¿Puede una intención antirracista sobrevivir a un lenguaje racial y eugenésico, o el lenguaje deshace la intención sin importar lo que el autor quiso decir?", p:"Conviene empezar por los hechos, que no están en disputa. Vasconcelos escribe contra la tesis dominante de que el mestizaje degenera, contra las políticas de blanqueamiento por inmigración que aplicaban varios gobiernos del continente, contra el darwinismo social y contra el expansionismo estadounidense; en 1925 eso era una posición minoritaria y tuvo costos. También es un hecho que el libro habla de mejoramiento, de selección y de tipos inferiores que irían desapareciendo, y que conserva la raza como sujeto real de la historia. A partir de ahí hay tres respuestas posibles y todas tienen defensores serios. La primera dice que el vocabulario es envoltorio de época y que la tesis integracionista se sostiene sin él; su debilidad es que los pasajes eugenésicos no son adjetivos sueltos sino afirmaciones sustantivas del autor. La segunda dice que el lenguaje es la estructura y que un pensamiento que sigue clasificando y jerarquizando tipos humanos es racista aunque invierta el orden de los puestos; su debilidad es que, llevada al extremo, ese criterio descalifica a casi todo autor anterior a 1950 y vuelve imposible cualquier historia de las ideas. La tercera, que es la más trabajosa y probablemente la más honesta, sostiene que no hay que elegir: el texto hace las dos cosas a la vez, y lo que corresponde es indicar en qué puntos concretos la intención antirracista se cumple y en cuáles el marco la traiciona. Hay además un argumento independiente de la intención y que pesa mucho: lo que la obra hizo históricamente. La ideología del mestizaje se convirtió en política de Estado y sirvió durante décadas para declarar inexistente un racismo que seguía operando, y eso cuenta aunque no fuera lo que Vasconcelos quería."},
   {q:"El contraste entre pragmatismo utilitario anglosajón y espíritu estético latino, ¿es una distinción filosófica sostenible o un estereotipo en las dos direcciones?", p:"Es mayormente un estereotipo, y lo interesante es que se lo puede refutar con los propios textos. Contra la caricatura del pragmatismo: Peirce funda el pragmatismo como método para fijar el significado de los conceptos, no como filosofía del provecho; James dedica buena parte de su obra a la experiencia religiosa y sostiene que una creencia puede ser legítima sin evidencia suficiente cuando la cuestión es vital; y Dewey escribió El arte como experiencia, un libro entero dedicado a mostrar que lo estético no es una esfera separada sino la cualidad de plenitud de la experiencia ordinaria, lo cual es prácticamente lo contrario de lo que Vasconcelos le atribuye. Su criterio de utilidad significa resolución efectiva de una situación problemática, no rentabilidad. Contra la idealización de lo latino: describir un espíritu común a todos los pueblos de lengua ibérica, de Chiapas a Montevideo, es una generalización cultural exactamente del mismo tipo que las que Vasconcelos denuncia cuando se aplican en su contra; y la historia intelectual muestra positivismos vigorosos, tecnocracias y utilitarismos muy eficientes en América Latina, además de corrientes espiritualistas y estéticas potentes en Inglaterra y en Estados Unidos, de Emerson y Thoreau al trascendentalismo entero. Lo que sí merece rescatarse es una pregunta que su formulación esconde: si una cultura organiza todas sus instituciones en torno a la eficiencia, ¿con qué criterio decide para qué quiere ser eficiente? Esa pregunta es legítima y no necesita ninguna tipología nacional para plantearse; de hecho se la plantean, con más herramientas, los propios pragmatistas."},
   {q:"¿Cómo se pesan sus logros concretos como Secretario de Educación frente a los elementos problemáticos de su obra teórica?", p:"Lo primero es no fabricar una balanza única, porque son dos preguntas distintas y mezclarlas produce mala historia y mala filosofía. La pregunta sobre la gestión es empírica y tiene respuestas verificables: entre 1921 y 1924 se creó la Secretaría de Educación Pública, se multiplicó el presupuesto educativo, se fundaron miles de bibliotecas, se lanzaron campañas de alfabetización, se organizaron las misiones culturales rurales, se editaron clásicos por decenas de miles de ejemplares y se financió el muralismo. Ese balance es en conjunto positivo y difícil de igualar en el siglo XX latinoamericano, aunque admite críticas internas serias: el modelo era misionero y vertical, llevaba cultura a comunidades en vez de partir de la que ya tenían, y su canon era abiertamente europeo. La pregunta sobre la obra teórica es filosófica y no se salda con obras realizadas: que alguien haya hecho un bien enorme no vuelve verdadera su antropología. Ahora bien, hay una conexión real entre ambas que sí importa: la gestión es la aplicación de la misma filosofía, y examinar cómo funcionó en la práctica es una prueba empírica de la teoría. Y el resultado es mixto de un modo instructivo: la parte estética y educativa funcionó notablemente, mientras que la parte integracionista produjo exactamente el efecto que hoy se le critica, una cultura nacional mestiza en la que las culturas indígenas entraron como pasado y no como presente. El único juicio que hay que rechazar sin más es el que usa cualquiera de los dos platillos para no mirar el otro."},
   {q:"Su indigenismo, ¿respeta a las culturas indígenas en sus propios términos o las subordina a una síntesis mestiza que las hace desaparecer?", p:"La honestidad obliga a reconocer primero lo que hizo, porque es real y contrasta con sus contemporáneos: Vasconcelos afirmó el valor del componente indígena cuando la opinión ilustrada lo consideraba un lastre, destinó recursos públicos a las comunidades rurales indígenas y promovió un arte que las puso en los muros del Estado. Dicho eso, la estructura de su pensamiento las subordina, y no por descuido sino por diseño. Lo indígena aparece como componente de una síntesis cuya forma final no es indígena; la lengua, la religión y la organización política propias no figuran como tradiciones con derecho a continuar sino como aportes que se integran; y el horizonte deseable es que todos seamos la quinta raza, no que existan pueblos distintos conviviendo. La diferencia con el indigenismo posterior es nítida. El indigenismo autonomista, y más aún los movimientos indígenas contemporáneos —del zapatismo a las organizaciones del Cauca colombiano y a los movimientos andinos—, no reclaman ser mejor integrados sino ser reconocidos como pueblos con territorio, instituciones, lengua y filosofía propias. Desde ese punto de vista, la crítica más filosa no es que Vasconcelos despreciara lo indígena, sino lo contrario: que lo celebró mientras describía su disolución en el conjunto como el desenlace deseable. Hay una defensa parcial disponible y conviene enunciarla: el pluralismo cultural fuerte es un marco posterior, y exigirle a un autor de 1925 categorías de 1990 es anacrónico. La respuesta a esa defensa es que en 1925 también existían pueblos indígenas diciendo en voz alta lo que querían, y que no haberlos escuchado es una elección y no una imposibilidad histórica."},
   {q:"Su giro político hacia la derecha y el episodio de la revista Timón en 1940, ¿obligan a releer su obra anterior o son un capítulo biográfico separado?", p:"Los hechos primero, sin adorno. Tras la derrota electoral de 1929, que consideró fraudulenta, Vasconcelos se exilió y se desplazó hacia un hispanismo católico y conservador cada vez más hostil a la Revolución Mexicana. En 1940 dirigió la revista Timón, financiada por la legación alemana en México, en la que se publicaron artículos favorables al régimen nazi; la revista fue clausurada. Los historiadores discuten cuánto del contenido escribió él directamente y cuánto pesaron su amargura y su antiamericanismo, pero la dirección y la orientación no están en discusión. La pregunta filosófica es la misma que se le plantea a Heidegger con su afiliación de 1933 y a Nishida con sus escritos de guerra, y admite las mismas tres respuestas. La primera separa la obra del hombre: La raza cósmica es de 1925, su argumento se evalúa por sus razones y la deriva posterior no las toca. La segunda sostiene que el episodio revela lo que estaba latente, y tiene un argumento concreto y no meramente insinuante: un pensamiento que conserva la raza como sujeto de la historia, que le asigna una misión y que confía en el espíritu de un pueblo más que en instituciones y procedimientos, ofrece menos resistencia frente a un nacionalismo racial de la que su autor suponía. La tercera, que hoy es la posición mayoritaria entre especialistas y también la más exigente, rechaza las dos salidas limpias: ni contaminación total ni compartimentos estancos, sino la tarea concreta de señalar en qué puntos exactos el aparato conceptual no ofreció resistencia y en cuáles sí la ofreció, porque también hay pasajes suyos que son directamente incompatibles con el racismo de exclusión. El detalle que ninguna de las tres puede ignorar es el contraste: el mismo hombre escribió el alegato continental contra la pureza racial y, quince años después, dirigió una revista favorable al régimen que llevó esa pureza al exterminio."}
 ],
 cadena:{ titulo:"¿Se puede combatir el racismo con el lenguaje de la raza?", intro:"Un razonamiento en ramas sobre la contradicción central de La raza cósmica (1925): un libro escrito contra la tesis racista de que el mestizaje degenera, que al mismo tiempo propone su propio programa de selección racial. Las ramas no buscan absolver ni condenar de antemano: buscan ver con exactitud qué dice el texto.", inicio:"n1", nodos:{
   n1:{ pregunta:"En 1925, la tesis dominante —en la antropología europea, en la eugenesia estadounidense y en buena parte de las élites latinoamericanas— era que la mezcla de razas degeneraba a los pueblos y condenaba a América Latina. Vasconcelos la invierte: el mestizaje es el camino hacia una raza superior. ¿Es eso una tesis antirracista?", opciones:[
     {texto:"Sí: invierte la jerarquía que condenaba a los pueblos mestizos.", va:"n2a"},
     {texto:"No del todo: conserva la idea de que hay razas, con rasgos y valores distintos.", va:"n2b"} ]},
   n2a:{ pregunta:"El mismo ensayo describe así lo que ocurrirá en el período estético: «Los tipos bajos de la especie serán absorbidos por el tipo superior. De esta suerte podría redimirse, por ejemplo, el negro, y poco a poco, por extinción voluntaria, las estirpes más feas irán cediendo el paso a las más hermosas». ¿Cómo leer ese pasaje?", opciones:[
     {texto:"Como un desliz de la época, que no afecta la tesis central del libro.", final:{tipo:"revisar", texto:"No es un desliz: es el mecanismo de la tesis. La quinta raza se forma, según Vasconcelos, por la ley del gusto, y el pasaje explica qué hace esa ley: hace desaparecer a quienes él considera feos y nombra a las personas negras como algo que hay que redimir por absorción. Si se quita el pasaje, se quita el programa. Además, «de la época» no alcanza: Vasconcelos escribía contra el racismo de su época, así que se lo puede medir con su propio criterio. Volvé un paso y probá la otra respuesta."}},
     {texto:"Como la prueba de que la inversión es parcial: valora la mezcla, pero conserva la jerarquía de qué tiene que desaparecer en ella.", va:"n3a"} ]},
   n3a:{ pregunta:"Si el libro es a la vez antirracista y racista, ¿qué se hace con él?", opciones:[
     {texto:"Leerlo como lección: se puede combatir una jerarquía racial con otra, y la crítica tiene que mirar los mecanismos de una tesis, no solo sus intenciones.", final:{tipo:"bien", texto:"Es la lectura más útil para el aula. Muestra un error que se repite: el que impugna una jerarquía tiende a reemplazarla por otra en lugar de abandonar la idea de jerarquía. El valor del mestizaje sobrevivió y fue decisivo para el continente; la escala de razas superiores e inferiores tiene que caer entera. Leer así exige separar las dos cosas con precisión, no con un balance de virtudes y defectos."}},
     {texto:"Descartarlo: un autor que escribe eso no merece ser leído.", final:{tipo:"bien", texto:"Es una posición defendible, y tiene la virtud de no relativizar. Pero tiene costos que conviene ver. Vasconcelos fue también el secretario de Educación que llevó a México las campañas de alfabetización, las bibliotecas populares y el muralismo, y su pregunta por un pensamiento propio de América Latina la retomó Leopoldo Zea, que le quitó el marco racial. Si no se lo lee, no se entiende de dónde viene esa pregunta ni por qué hubo que desmontarla."}} ]},
   n2b:{ pregunta:"Vasconcelos no habla solo de cultura: habla de cuatro troncos raciales —el negro, el indio, el mongol y el blanco—, de cruces biológicos y de qué aporta cada uno. ¿Qué conserva, exactamente, del pensamiento racial de su época?", opciones:[
     {texto:"La idea de que las razas tienen aptitudes propias y de que la mezcla debe mejorar la especie por selección.", va:"n3b"},
     {texto:"Solo el vocabulario: para él, «raza» significa cultura.", final:{tipo:"revisar", texto:"Es la defensa más frecuente, y es parcialmente cierta: Vasconcelos mezcla todo el tiempo lo biológico y lo cultural. Pero el texto habla de cruces, de procreación, de tipos que dejarán de reproducirse. El lema que escribió para la UNAM, «Por mi raza hablará el espíritu», tiene un sentido más cultural; La raza cósmica no se limita a eso. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Vasconcelos insiste en que su selección no será impuesta: en el período estético cada uno se unirá libremente con quien ame, por gusto. ¿Eso la distingue de la eugenesia de Estado que se practicaba en Estados Unidos?", opciones:[
     {texto:"Sí: no hay coerción; nadie es esterilizado ni obligado.", final:{tipo:"bien", texto:"La diferencia es real: en Estados Unidos había leyes de esterilización forzada, y Vasconcelos no propone nada parecido. Pero mirá qué supone su libertad de gusto: que el gusto es neutral. En sociedades que heredaron la jerarquía colonial, lo que se considera hermoso no es neutral, y el propio texto dice qué tipos espera que desaparezcan. Sin coerción y con el mismo resultado deseado, la diferencia es de medios, no de fines."}},
     {texto:"No en el fin: el resultado buscado es la desaparición de ciertos tipos; cambia el medio, no el objetivo.", final:{tipo:"bien", texto:"Es la lectura más dura y tiene apoyo textual en la expresión «extinción voluntaria». Para ser exacto, hay que reconocer también la diferencia de medios, que no es menor: no es lo mismo esperar que algo ocurra por gusto que imponerlo por ley. Pero el objetivo de una humanidad sin los que él llama feos es el mismo, y eso es lo que hay que nombrar."}} ]}
 }},
 reconstruccion:[
   { titulo:"La tesis de La raza cósmica",
     consigna:"Reconstruí el argumento con que Vasconcelos sostiene que América Latina producirá la quinta raza. Una pieza contradice su idea de que la mezcla será libre: dejala afuera y ordená el resto.",
     piezas:[
       {id:"r1", texto:"La historia pasa por tres estados: el material o guerrero, regido por la fuerza; el intelectual o político, regido por la razón y la norma; y el estético, regido por el gusto y el amor.", tipo:"premisa"},
       {id:"r2", texto:"En el estado material, las uniones entre pueblos se deciden por conquista; en el intelectual, por cálculo y por leyes, como las que prohíben los matrimonios mixtos; en el estético, por la libre inclinación de la belleza.", tipo:"premisa"},
       {id:"r3", texto:"La colonización anglosajona exterminó o segregó a los pueblos que encontró; la ibérica, según Vasconcelos, se mezcló con ellos.", tipo:"premisa"},
       {id:"r4", texto:"En América Latina se encuentran los cuatro troncos raciales y no hay leyes que impidan su mezcla.", tipo:"premisa"},
       {id:"r5", texto:"Por lo tanto, América Latina está llamada a producir la quinta raza, la raza cósmica, e inaugurar el período estético de la humanidad.", tipo:"conclusion"},
       {id:"rx", texto:"Por lo tanto, la mezcla racial debe imponerse por ley para acelerar la llegada de la quinta raza.", tipo:"distractor"}
     ],
     ordenCorrecto:["r1","r2","r3","r4","r5"],
     explicacion:"Es una filosofía de la historia: una sucesión necesaria de estados (r1-r2) aplicada a un lugar privilegiado (r3-r4). Tiene dos puntos débiles. El primero es r3: presenta la colonización ibérica como mezcla armónica, cuando el mestizaje colonial se produjo en buena parte por violencia sexual, servidumbre y un sistema de castas que clasificaba a las personas por su mezcla. El segundo es la teleología misma: nada garantiza que la historia avance hacia un estado estético. La pieza sobrante contradice el programa: para Vasconcelos la ley pertenece al estado intelectual, y el estético se define justamente por no necesitarla."},
   { titulo:"El mecanismo de la ley del gusto",
     consigna:"Reconstruí lo que, según el propio Vasconcelos, ocurre con la reproducción humana en el período estético. Una pieza recoge lo que su tesis promete en su cara antirracista, y que el mecanismo contradice: dejala afuera.",
     piezas:[
       {id:"e1", texto:"En el período estético, las uniones no se decidirán por necesidad ni por cálculo, sino por gusto y amor.", tipo:"premisa"},
       {id:"e2", texto:"Vasconcelos supone que lo bello coincide con lo que él llama «tipos superiores» de la especie.", tipo:"premisa"},
       {id:"e3", texto:"Quienes sean considerados feos no serán elegidos ni desearán procrear.", tipo:"premisa"},
       {id:"e4", texto:"Por lo tanto, en sus palabras, «por extinción voluntaria, las estirpes más feas irán cediendo el paso a las más hermosas», y los tipos bajos serán absorbidos por el tipo superior.", tipo:"conclusion"},
       {id:"ex", texto:"Por lo tanto, todas las razas aportarán por igual a la quinta raza, sin que ninguna desaparezca.", tipo:"distractor"}
     ],
     ordenCorrecto:["e1","e2","e3","e4"],
     explicacion:"Este es el corazón eugenésico del libro, y conviene verlo como argumento, no solo como frase escandalosa. El punto débil es e2: que la belleza coincida con la superioridad es una premisa que Vasconcelos no defiende, y sin ella la conclusión no se sigue. Además, lo que se considera bello en una sociedad está modelado por quién tuvo poder en ella, de modo que una selección por gusto en una sociedad poscolonial tiende a reproducir la jerarquía colonial. El mismo pasaje nombra a las personas negras como ejemplo de lo que podría redimirse por absorción. La pieza sobrante es lo que el libro promete cuando habla de síntesis de las cuatro razas, y es lo que el mecanismo desmiente: en la síntesis de Vasconcelos no todos llegan."}
 ],
 dilemas:[
   { titulo:"La cita del mural",
     intro:"Este caso trata un problema que aparece en cualquier institución que hereda autores: qué hacer con un texto que dice algo valioso y algo inaceptable a la vez. No hay una respuesta correcta automática, pero sí respuestas mejor y peor fundadas.",
     pasos:[
       { id:"p1", situacion:"Tu colegio en Ibagué prepara un mural por su aniversario, dedicado a la diversidad de Colombia. El comité propone una frase de La raza cósmica sobre la síntesis de todos los pueblos en América. Una estudiante afrocolombiana de once leyó el libro completo para una tarea y encontró el pasaje que dice que «podría redimirse, por ejemplo, el negro», por extinción voluntaria de las estirpes «más feas». Te lo muestra. ¿Qué hacés?", opciones:[
         {texto:"Defiendo la frase: es un clásico de la identidad latinoamericana, y la cita elegida no dice nada malo.", consecuencia:"La cita aislada puede no decir nada malo, pero el mural la presenta como palabra de un autor sobre la diversidad, y en ese libro la diversidad termina con la desaparición de algunos. La estudiante leyó más que el comité. Defender la frase sin responderle a ella es decirle que su lectura no cuenta.", va:"p2"},
         {texto:"Propongo cambiar la cita por otra de un autor que no tenga ese problema.", consecuencia:"Resolvés el mural y evitás que el colegio celebre algo que ofende a una parte de sus estudiantes. Lo que se pierde es la oportunidad de que el colegio entero aprenda lo que la estudiante descubrió: cómo un texto antirracista puede tener un programa racista adentro.", va:"p2"},
         {texto:"Llevo el caso al comité con la estudiante, y propongo que ella presente lo que encontró.", consecuencia:"Le diste a la lectora más atenta el lugar que le corresponde. Ahora la decisión sobre el mural se toma con el texto completo a la vista, no con una frase suelta.", va:"p2"} ]},
       { id:"p2", situacion:"El rector responde: «No podemos juzgar a un autor de 1925 con los ojos de hoy. En esa época todos pensaban así». ¿Qué le contestás?", opciones:[
         {texto:"«Tiene razón, era otra época.»", consecuencia:"El argumento suena prudente, pero no se sostiene en este caso. Vasconcelos escribía precisamente contra el racismo de su época, así que conocía la crítica. Medirlo con un criterio antirracista es medirlo con el criterio que él mismo declaraba. Y «todos pensaban así» no incluye a las personas negras de 1925, que no pensaban que debían desaparecer.", va:"p3"},
         {texto:"«Él mismo escribía contra el racismo de su época. Lo estoy midiendo con su propio criterio, no con uno de hoy.»", consecuencia:"Es la respuesta más fuerte al argumento del anacronismo: la contradicción no la inventamos nosotros, está dentro del texto. No hace falta saber nada de hoy para verla; basta leer el libro completo.", va:"p3"},
         {texto:"«Entonces no lo pongamos en un mural que celebra la diversidad, porque en su libro la diversidad desaparece.»", consecuencia:"Dejaste de discutir si se puede juzgar a Vasconcelos y fuiste a la pregunta práctica: si su frase sirve para este mural. Es una decisión concreta, que no exige condenar al autor en todo, solo no usarlo para algo que su libro contradice.", va:"p3"} ]},
       { id:"p3", situacion:"Buscando más, la estudiante descubre que en 1940 Vasconcelos dirigió en México la revista Timón, financiada por la embajada alemana y con artículos favorables a la Alemania nazi. Te pregunta: «¿Entonces por qué lo enseñamos?». ¿Qué le respondés?", opciones:[
         {texto:"«Porque lo que importa son sus ideas, no su vida.»", consecuencia:"La separación entre obra y vida no funciona bien acá: lo que la estudiante encontró en La raza cósmica no es un dato biográfico, es una tesis del libro. Y Timón no es una anécdota privada: es una intervención pública con contenido político.", va:null},
         {texto:"«Porque para entender de dónde viene la pregunta por lo latinoamericano, hay que saber qué decía él y por qué hubo que desmontarlo. Enseñarlo no es celebrarlo.»", consecuencia:"Es la distinción entre estudiar un autor y homenajearlo. Un mural es un homenaje; una clase puede ser un examen crítico. Vasconcelos es indispensable para la historia del problema y no tiene por qué ser un modelo.", va:null},
         {texto:"«Tenés razón: no deberíamos enseñarlo.»", consecuencia:"Es una conclusión posible y respetable. Pero fijate que lo que ella sabe ahora lo aprendió leyéndolo críticamente: si no se lo enseña, la próxima estudiante va a encontrar la frase bonita en un mural, sin el resto.", va:null} ]}
     ],
     rubrica:[
       "Puedo citar o reconstruir con exactitud el pasaje eugenésico de La raza cósmica y explicar su función en el argumento.",
       "Distinguí lo que sobrevivió de Vasconcelos (el valor del mestizaje, la pregunta por un pensamiento propio) de lo que hay que rechazar entero (la escala de razas y la selección).",
       "Respondí al argumento del anacronismo mostrando que la contradicción está dentro del texto.",
       "Diferencié estudiar un autor de rendirle homenaje.",
       "Le di a la lectura de la estudiante el peso que tenía, sin hablar por ella.",
       "Incluí en el juicio los hechos posteriores (Timón, 1940) sin usarlos para reemplazar el análisis del libro.",
       "Formulé la objeción más fuerte a mi propia decisión."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.vasconcelos = { lecturas:[
 {titulo:"La raza cósmica (1925): mestizaje, estética y crítica al darwinismo social", fuente:"Internet Archive — La raza cósmica: misión de la raza iberoamericana", url:"https://archive.org/details/larazacosmicamis00vasc_0",
  extracto:`Vasconcelos escribe en 1925, en pleno auge de las teorías raciales europeas y del panamericanismo anglosajón, y su tesis es deliberadamente contraria a ambos: lo que las ciencias raciales de su tiempo veían como la debilidad de América Latina —la mezcla— él lo declara su ventaja histórica.

Su filosofía de la historia divide el proceso humano en cuatro etapas raciales (negra, india, mongólica y blanca) que, según él, tienden a fundirse en una quinta: «la raza definitiva, la raza síntesis o raza integral, hecha con el genio y con la sangre de todos los pueblos y, por lo mismo, más capaz de verdadera fraternidad y de visión realmente universal». A esa quinta la llama raza cósmica, y sostiene que su cuna será Iberoamérica por su historia de mezcla.

La crítica al modelo anglosajón es explícita y política. Vasconcelos argumenta que la colonización inglesa de América del Norte se basó en la exclusión y la eliminación del indígena, mientras que la ibérica, con toda su violencia, produjo mezcla. De ahí su rechazo al «criterio de la dominación» y a la doctrina Monroe, y su reivindicación de la unidad iberoamericana frente al expansionismo estadounidense.

Contra el darwinismo social, que dominaba la sociología de la época, opone lo que llama la ley de los tres estados sociales: el material o guerrero, donde rige la fuerza bruta; el intelectual o político, donde rigen la razón y la norma jurídica; y el estético o espiritual, donde la elección se guiaría «por el gusto y por el amor», y donde las uniones no obedecerían ni a la coerción ni al cálculo. «La ley del gusto» sustituiría a la ley de la selección natural. Por eso su lema como secretario de Educación fue «por mi raza hablará el espíritu», y por eso su monismo estético sostiene que el arte, y no la ciencia, es la forma superior de conocimiento.

Su concepto de cultura acompaña esa apuesta: Vasconcelos impulsó desde el Estado mexicano el muralismo, las misiones culturales rurales y las ediciones masivas de clásicos, convencido de que la estética es el vehículo de la integración nacional.

La crítica contemporánea al texto es tan importante como el texto mismo. Por un lado, Vasconcelos rompe con el racismo de exclusión y afirma el valor del mestizaje en un momento en que eso era una posición minoritaria y valiente. Por otro, conserva la categoría de «raza» como unidad de análisis, describe a las poblaciones en términos jerárquicos y llega a hablar de la desaparición voluntaria de los «tipos inferiores» por la ley del gusto — es decir, sostiene una forma de blanqueamiento estético. Su celebración del mestizaje también tiende a invisibilizar a los pueblos indígenas y afrodescendientes vivos, subsumiéndolos en una síntesis futura que nunca los reconoce en presente.`,
  comentario:"Este texto es un caso ideal para trabajar lectura crítica: un autor que combate una ideología racista con otra que también piensa en términos raciales. La «ley del gusto» que reemplaza a la selección natural es donde el monismo estético se vuelve programa político, y también donde la crítica actual encuentra el blanqueamiento implícito. Leelo junto a Zea y Dussel, que retoman su pregunta por la identidad pero abandonan su marco racial."}
], preguntasLectura:[
 {q:"¿Cuál es la tesis central de La raza cósmica?", opciones:["Que las razas deben mantenerse puras","Que el mestizaje iberoamericano dará lugar a una quinta raza síntesis","Que la raza blanca es superior","Que América debe imitar a Estados Unidos"], r:"Que el mestizaje iberoamericano dará lugar a una quinta raza síntesis", why:"Vasconcelos invierte el diagnóstico racista de su época: la mezcla es ventaja, no debilidad."},
 {q:"¿Qué reemplaza a la selección natural en el tercer estado social de Vasconcelos?", opciones:["La ley jurídica","La ley del gusto y del amor (criterio estético)","La planificación económica","La autoridad religiosa"], r:"La ley del gusto y del amor (criterio estético)", why:"Es la aplicación de su monismo estético a la historia, contra el darwinismo social."},
 {q:"¿Cuál es la principal crítica contemporánea a Vasconcelos?", opciones:["Que era demasiado científico","Que sigue pensando en categorías raciales jerárquicas y difumina a indígenas y afrodescendientes en una síntesis futura","Que ignoró la educación","Que defendía la doctrina Monroe"], r:"Que sigue pensando en categorías raciales jerárquicas y difumina a indígenas y afrodescendientes en una síntesis futura", why:"Combate el racismo de exclusión sin abandonar la raza como unidad de análisis — de ahí el reproche de blanqueamiento estético."}
]};
