/* ============================================================
   Ficha: zea  ·  tradición: americana
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"zea", trad:"americana", nombre:"Leopoldo Zea", fechas:"1912–2004 · México", escuela:"Filosofía de la historia latinoamericana", icon:"🧭", profundizada:true,
 tesis:"No existe una filosofía universal escrita desde ningún lugar: toda filosofía, incluida la europea, nace de una circunstancia histórica concreta y responde a los problemas de esa circunstancia. Lo que ocurrió con la filosofía europea no fue que naciera universal, sino que logró que su circunstancia pasara por la circunstancia humana sin más. De ahí la consigna de Zea: el latinoamericano no tiene que pedir permiso ni acreditar credenciales para filosofar, tiene que partir de sí mismo y hacer pura y simplemente filosofía, que lo americano se dará por añadidura. La apuesta es elegante y tiene un costo que conviene medir: al declarar disuelto el tribunal europeo, ¿desarma efectivamente la dependencia o solo decreta que ya no existe?",
 obras:[
   {t:"América como conciencia (1953)", d:"Es el libro donde formula por primera vez, de manera compacta, la idea que va a organizar toda su obra posterior: América no es solamente un territorio ni un conjunto de pueblos, es una conciencia, es decir, un modo de saberse a sí misma en relación con una historia que la incluyó de forma subordinada. Zea reconstruye cómo la pregunta por lo americano aparece desde la Independencia, atraviesa a Bolívar, a Sarmiento, a Martí, a Rodó, y llega a su propia generación convertida en una interrogación angustiada sobre si aquí se puede pensar. Su diagnóstico es que esa angustia no es un problema filosófico sino un síntoma histórico: el resto que dejó la colonia en la cabeza de los colonizados una vez que se retiró el ejército colonial. El libro tiene además un valor de método, porque muestra que la historia de las ideas no es un inventario de influencias recibidas sino el estudio de qué preguntas se hicieron los americanos, en qué momento y contra quién, y por qué eligieron ciertos instrumentos europeos y no otros para responderlas."},
   {t:"La filosofía americana como filosofía sin más (1969)", d:"Su ensayo más famoso, más citado y más discutido, y el que contiene su tesis metodológica en la forma más radical. El punto de partida es un desplazamiento de la pregunta: en vez de responder si existe una filosofía latinoamericana, Zea muestra que la pregunta misma es el problema, porque nadie que esté filosofando de verdad se detiene a pedir un certificado de existencia. El argumento comparativo cabe en una línea que él repite y que conviene memorizar: a ningún griego se le ocurrió preguntarse por la existencia de una filosofía griega, simplemente pensaba. La conclusión práctica es la que da título al libro: hay que hacer filosofía sin más, sin adjetivo y sin disculpa, partiendo de la propia circunstancia como partió de la suya cualquier filósofo que hoy consideramos universal. El libro distingue también, con precisión que después se usó mucho, entre imitar y asimilar, y usa el positivismo mexicano del porfiriato como caso ejemplar de una doctrina europea adoptada menos para pensar el país que para justificar un orden político determinado. Está disponible íntegro en la sección de Lecturas de esta ficha y vale la pena leerlo entero antes de discutirlo."},
   {t:"El pensamiento latinoamericano (1965)", d:"Su gran obra de investigación histórica, que amplía y reorganiza trabajos anteriores sobre el positivismo y recorre de forma sistemática el desarrollo de las ideas filosóficas en el continente desde la escolástica colonial hasta el siglo XX. Su valor no es solo informativo. Zea sostiene que las corrientes europeas que llegaron a América —escolástica, ilustración, romanticismo, positivismo, marxismo, existencialismo— no se entienden mirando su origen sino mirando para qué fueron usadas aquí: la misma doctrina positivista sirvió en un país para desmontar el poder eclesiástico y en otro para blindar a una dictadura modernizadora. Ese desplazamiento del origen al uso es lo que convierte a la historia de las ideas en filosofía y no en erudición, y es la contribución metodológica por la que Zea influyó en generaciones de investigadores. El libro tiene también un límite que los lectores actuales notan enseguida: su América Latina está poblada casi exclusivamente por intelectuales criollos y letrados, y las tradiciones de pensamiento indígenas y afrodescendientes aparecen apenas, lo que muestra hasta dónde llegaba el horizonte de la disciplina en su momento."},
   {t:"Dependencia y liberación en la cultura latinoamericana (1974)", d:"Escrito en el clima intelectual de la teoría de la dependencia y del surgimiento de la Filosofía de la Liberación, es el libro donde Zea traslada su análisis del plano de la conciencia al plano de las estructuras. Sostiene que la dependencia cultural no es un reflejo automático de la dependencia económica ni algo separado de ella, sino un mecanismo con lógica propia: el colonizado interioriza la escala de valores del colonizador y termina midiendo su propia producción con una vara que no fabricó, de modo que la dominación se sostiene sin necesidad de imposición externa. Aquí Zea discute abiertamente con el marxismo y con las lecturas más confrontativas de su tiempo, y toma partido por una liberación entendida como recuperación de la capacidad de decidir el propio proyecto, no como ruptura total con Occidente, del que considera que América Latina forma parte aunque sea desde el margen. Es el texto más útil para medir con precisión la distancia real que lo separa de Dussel, porque comparte el vocabulario de la liberación y sin embargo no comparte del todo su diagnóstico ni su desenlace."},
   {t:"Filosofía de la historia americana (1978)", d:"Su obra más ambiciosa y probablemente la más filosófica en sentido estricto, porque ya no se limita a estudiar cómo pensaron los americanos sino que propone una interpretación de la historia universal desde América. Su blanco explícito es la filosofía de la historia de Hegel, que había dejado a América fuera de la historia propiamente dicha relegándola a tierra del futuro, y a los pueblos americanos a la condición de material aún no maduro para el espíritu. Zea invierte la operación sin negar el hecho: acepta que América fue incorporada tarde y en posición subordinada al relato occidental, y argumenta que precisamente esa posición marginal es un mirador privilegiado, porque desde el borde se ve lo que el centro no puede ver de sí mismo, empezando por la violencia fundacional que su relato de progreso necesita omitir. Así, la historia universal deja de ser el despliegue del espíritu europeo y pasa a ser una historia que solo puede escribirse completa si incluye la voz de quienes fueron su instrumento y su costo."}
 ],
 conceptos:[
   {t:"La filosofía americana como filosofía sin más", d:"Es su tesis central y conviene enunciarla con exactitud, porque se la suele reducir a una consigna. Zea no afirma que exista una filosofía latinoamericana con contenidos propios que haya que descubrir, ni propone una filosofía alternativa a la europea. Afirma algo más sutil: que la pregunta por la legitimidad está mal planteada desde el principio, porque presupone un tribunal ante el cual habría que acreditarse, y ese tribunal es un producto histórico de la colonia y no una instancia neutral. El argumento comparativo es simple y filoso: ningún griego se preguntó si había filosofía griega antes de hacerla, ningún alemán del siglo XIX pidió autorización para pensar desde Jena o desde Königsberg; filosofaban desde su circunstancia y su producto pasó a llamarse filosofía a secas. Por eso la salida no es reclamar un lugar especial sino dejar de pedirlo: hacer filosofía sin adjetivo, sobre problemas reales, y dejar que lo americano aparezca como resultado y no como propósito. La fuerza de la tesis está en que iguala el terreno sin conceder nada; su punto débil, que el propio módulo discute, es que una desigualdad institucional muy concreta no desaparece porque se la declare mal planteada."},
   {t:"La conciencia histórica americana", d:"América no es para Zea un dato geográfico sino una conciencia, y la palabra está usada en sentido fuerte, casi hegeliano: es el saber que un pueblo tiene de su propia situación dentro de una historia que no empezó eligiendo. Su tesis más audaz es que América funciona como conciencia de Occidente, es decir, como el lugar donde se hacen visibles las contradicciones que Occidente no puede ver de sí mismo. Europa pudo narrarse como el despliegue de la razón, la libertad y el progreso porque mantuvo fuera del relato lo que ese despliegue costó; pero ese costo tiene domicilio, y su domicilio es América y las demás regiones colonizadas. Desde el margen, entonces, no se ve menos que desde el centro: se ve más, porque se ve el centro junto con aquello que el centro necesita omitir. La operación es doblemente hegeliana y antihegeliana a la vez: toma de Hegel la idea de que la historia es un proceso de la conciencia que avanza por contradicciones, y la vuelve contra él al sostener que el momento de verdad de ese proceso no está en el Estado europeo sino en quien fue su instrumento."},
   {t:"Colonialismo mental y dependencia intelectual", d:"Zea insiste en que la independencia política del siglo XIX no produjo independencia mental, y que la segunda es más difícil precisamente porque no tiene un enemigo externo a quien expulsar. El colonizado interioriza la escala de valores del colonizador y sigue midiéndose con ella después de que el colonizador se retiró: por eso el intelectual latinoamericano se pregunta angustiado si lo que hace es realmente filosofía, mientras un colega europeo nunca se hace esa pregunta sobre sí mismo. El mecanismo tiene consecuencias verificables en la vida académica: el prestigio se importa, la bibliografía local se cita al final o no se cita, la teoría viene de afuera y de aquí se espera que salgan solo los datos o los casos. Zea llama a esto una forma de dominación que funciona sin necesidad de imposición, porque el dominado la administra por su cuenta. Importa señalar que no propone como remedio el rechazo de lo europeo: sostiene que eso sería seguir definiéndose por oposición, es decir, seguir dependiendo. El remedio es la autonomía del punto de partida, no el aislamiento del material."},
   {t:"Partir de nosotros mismos", d:"Es la formulación positiva de su programa y la que evita los dos extremos que él considera igualmente estériles. Un extremo es el universalismo abstracto, que pretende filosofar sin circunstancia, desde ningún lugar, y que en la práctica consiste en adoptar la circunstancia europea creyendo que es la circunstancia humana. El otro extremo es el particularismo cerrado, que reclama una filosofía exótica y autóctona, definida por su diferencia, y que termina encerrando al pensamiento americano en una reserva folclórica donde nadie le discute nada precisamente porque nadie lo toma en serio. Partir de nosotros mismos significa tomar la propia situación —histórica, social, lingüística, política— como punto de partida legítimo y como fuente de problemas reales, exactamente como hizo cualquier filosofía que hoy leemos como universal. Lo americano, entonces, no es un tema que haya que elegir sino una marca que deja el trabajo honesto, del mismo modo que la circunstancia alemana está en Kant sin que Kant se lo haya propuesto. La consigna que resume todo esto es la más citada de Zea: hay que hacer pura y simplemente filosofía, que lo americano se dará."},
   {t:"La filosofía de la historia americana", d:"Es la aplicación de su marco a la pregunta por el lugar de América en la historia universal, y su interlocutor es siempre Hegel. En las lecciones hegelianas América aparece como tierra del porvenir, todavía fuera de la historia efectiva, un continente cuya naturaleza y cuyos pueblos serían inmaduros para el espíritu; el juicio no es un descuido sino una pieza necesaria de un relato donde la historia culmina en el mundo germánico. Zea no responde reclamando un asiento en esa mesa, que sería aceptar el criterio del anfitrión. Responde mostrando que la incorporación tardía y subordinada de América es un hecho histórico producido por la propia expansión europea, y que ese hecho, lejos de descalificar a América como sujeto histórico, la constituye como el punto desde el cual la historia universal puede reescribirse de forma más completa. La consecuencia metodológica es concreta: la historia de las ideas latinoamericana no es un capítulo provincial de la historia de la filosofía europea, es un observatorio sobre lo que le pasa a las ideas europeas cuando salen del lugar donde se produjeron y tienen que funcionar en otro."},
   {t:"Asimilismo frente a autenticidad filosófica", d:"Zea describe el pensamiento latinoamericano como una sucesión de olas importadas —escolástica, ilustración, romanticismo, positivismo, marxismo, existencialismo, y podríamos seguir la lista hasta hoy— y señala que muchas de ellas fueron adoptadas como modas, es decir, como respuestas a preguntas que nadie se había hecho aquí. A esa actitud la llama, entre otros nombres, asimilismo o mentalidad imitativa, y su marca distintiva es que el valor de una idea se decide por su prestigio de origen y no por lo que permite entender. Frente a eso pone la asimilación genuina, que no consiste en rechazar el instrumento europeo sino en usarlo para responder una pregunta propia, aceptando que en ese uso el instrumento se transforma. Su caso de estudio preferido es el positivismo mexicano: la misma doctrina que en Francia acompañaba un programa científico y anticlerical sirvió aquí para dar cobertura intelectual al orden porfirista, lo que prueba que el sentido de una teoría no está en su texto sino en la función que cumple donde se la usa. El criterio práctico que se desprende es exigente y aplicable hoy: preguntar siempre qué problema real resuelve aquí la teoría que estamos citando, y qué pasaría si no la citáramos."},
   {t:"Relación con la Filosofía de la Liberación", d:"Zea es a la vez antecedente y adversario amistoso de la Filosofía de la Liberación que surge en los años setenta con Enrique Dussel, Juan Carlos Scannone, Rodolfo Kusch y otros, y conviene precisar en qué coinciden y en qué no. Coinciden en el diagnóstico de la dependencia, en el rechazo del universalismo abstracto y en la idea de que la filosofía debe partir de la situación histórica concreta; de hecho la generación de la liberación se formó leyendo a Zea y a la historia de las ideas que él impulsó. Difieren en tres puntos que no son de matiz. Primero, el sujeto: en Zea el sujeto del filosofar es América como conciencia histórica, un nosotros cultural amplio; en Dussel es el oprimido, la víctima, el excluido, categoría que corta transversalmente a ese nosotros y lo divide. Segundo, la relación con Occidente: Zea considera que América Latina es parte de Occidente y que se trata de participar en él con voz propia; Dussel propone un exterior, una transmodernidad que no se define desde el proyecto moderno. Tercero, la meta: Zea busca que la filosofía hecha aquí sea reconocida como filosofía sin más, es decir, incorporación en pie de igualdad; Dussel sospecha que ese reconocimiento es la trampa, porque quien fija qué cuenta como filosofía sigue siendo el mismo centro que produjo la exclusión."},
   {t:"Diálogo crítico con el marxismo, Frankfurt y el indigenismo", d:"Zea trabajó siempre en conversación con las corrientes críticas europeas sin adherir a ninguna, y esa posición intermedia explica tanto su alcance como sus límites. Del marxismo tomó la idea de que las ideas cumplen funciones sociales y de que la dependencia tiene base material, pero rechazó reducir la conciencia cultural a reflejo de la estructura económica, entre otras cosas porque su propio objeto —la persistencia del colonialismo mental después de la independencia política y bajo regímenes económicos distintos— no se explica bien así. Con la teoría crítica de Frankfurt comparte la sospecha de que la razón ilustrada llevaba dentro su propia forma de dominio, pero mientras Adorno y Horkheimer localizan esa dialéctica dentro de Europa, Zea señala que su escenario decisivo fue la colonia, y que una crítica de la razón occidental escrita sin América está incompleta por las mismas razones que denuncia. Con el indigenismo su relación es la más incómoda: reconoce el despojo, integra lo indígena en el nosotros americano, y sin embargo su sujeto filosófico sigue siendo mayormente criollo y letrado, de modo que las filosofías indígenas aparecen como parte del pasado común más que como tradiciones vivas con derecho a hablar en primera persona. Es la crítica que le harán, desde ángulos distintos, Rodolfo Kusch y buena parte del pensamiento decolonial posterior."},
   {t:"La obra institucional y la formación de una disciplina", d:"Reducir a Zea a un conjunto de tesis sería perder la mitad de su importancia, porque buena parte de su influencia consistió en construir las condiciones materiales para que existiera lo que él defendía. Formado en el grupo Hiperión y discípulo de José Gaos, el filósofo español transterrado que le transmitió la noción orteguiana de circunstancia, Zea dirigió durante décadas proyectos de investigación en la Universidad Nacional Autónoma de México, impulsó desde el Fondo de Cultura Económica la colección Tierra Firme, que puso en circulación continental la historia de las ideas latinoamericanas, dirigió el Centro Coordinador y Difusor de Estudios Latinoamericanos y la revista Cuadernos Americanos, y organizó congresos y redes que conectaron a investigadores de todo el continente en una época sin correo electrónico. El resultado es que la historia de las ideas en América Latina existe como disciplina universitaria, con revistas, cátedras y tesis, en gran medida por su gestión. Ese dato tiene una cara crítica que el módulo discute más adelante: un pensamiento que denuncia la dependencia y que al mismo tiempo se vuelve la voz oficial de la filosofía latinoamericana en las instituciones plantea por sí mismo la pregunta de si el reconocimiento obtenido midió el éxito de la crítica o su domesticación."}
 ],
 conexion:"Recibe de <b>José Vasconcelos</b> la pregunta por un pensamiento propio y le quita el marco racial, reemplazando la raza por la historia y la circunstancia como sujeto. De <b>Hegel</b> toma el aparato de la conciencia histórica y lo vuelve contra su exclusión de América de la historia universal. Su noción de circunstancia viene de Ortega y Gasset a través de su maestro José Gaos. Y su heredero más discutido es <b>Enrique Dussel</b>, que acepta el diagnóstico de la dependencia pero reemplaza el nosotros americano por la víctima y la incorporación en lo universal por una crítica a lo que cuenta como universal — el desacuerdo entre ambos es el eje vivo de la filosofía latinoamericana contemporánea.",
 dialogo:{titulo:"Filosofía sin adjetivo", lineas:[
   {quien:"Estudiante", texto:"Maestro, vengo de una facultad donde se lee a Kant en alemán y a Frege con lápiz. Leí su ensayo y le confieso mi impresión: filosofía sin más me suena a consigna. Me dice que deje de preguntarme si esto es filosofía y me ponga a trabajar, pero no me dice qué diferencia hay entre filosofar desde un lugar y filosofar poniendo ejemplos locales en un marco ajeno."},
   {quien:"Zea", texto:"Es la objeción correcta y le agradezco que no la disfrace. Empecemos por el diagnóstico antes que por el método. Dígame: sus colegas de Heidelberg, ¿se preguntan alguna vez si lo que hacen es realmente filosofía o es solo filosofía alemana?"},
   {quien:"Estudiante", texto:"Nunca. Ni se les ocurriría."},
   {quien:"Zea", texto:"Y usted se lo pregunta todos los días. Esa asimetría no es un accidente psicológico ni un defecto de su carácter: es lo que quedó después de que se fueron los barcos. A ningún griego se le ocurrió preguntarse por la existencia de una filosofía griega. Simplemente pensaba. Mi primer punto no es metodológico, es histórico: quiero mostrarle de dónde salió su pregunta, porque mientras la crea natural va a seguir contestándola con la cabeza del que la inventó."},
   {quien:"Estudiante", texto:"Concedido el diagnóstico. Pero el diagnóstico no es el método. Suponga que mañana me libero de la angustia y me siento a trabajar. ¿Qué hago distinto? Si escribo sobre la justicia usando a Rawls y pongo de ejemplo la reforma agraria colombiana, ¿eso es partir de mí mismo o es seguir importando el marco y cambiando la decoración?"},
   {quien:"Zea", texto:"Depende enteramente de en qué dirección corre la pregunta. Si usted parte de Rawls y busca un caso que lo ilustre, está decorando: el problema ya estaba resuelto antes de que llegara Colombia, y su país entró como material. Si en cambio parte de algo que le duele y que no entiende —por qué medio siglo de reforma agraria no cambió la estructura de la tierra— y en el camino descubre que Rawls le sirve para tres pasos y le falla en el cuarto, entonces el marco está al servicio de la pregunta y no al revés. Y ese cuarto paso, donde el instrumento europeo no alcanza, es exactamente el lugar donde empieza a haber filosofía y no comentario."},
   {quien:"Estudiante", texto:"Eso ya es un criterio y me sirve. Pero fíjese en lo que acaba de conceder: el criterio no es geográfico. Un alemán podría partir de algo que le duele en Alemania y descubrir que Rawls le falla en el cuarto paso. Entonces su filosofía americana no tiene nada de americana, es simplemente buena filosofía."},
   {quien:"Zea", texto:"Y eso es precisamente lo que yo sostengo, aunque a usted le suene a rendición. No hay dos clases de filosofía. Lo americano no es una propiedad del texto que se pueda verificar leyéndolo: es lo que queda en el texto cuando alguien piensa en serio desde donde está. Hay que intentar hacer pura y simplemente filosofía, que lo americano se dará. Buscarlo como tema es la manera más segura de no encontrarlo, y de terminar produciendo folclore para exportación."},
   {quien:"Estudiante", texto:"Ahora déjeme traerle la objeción que me hicieron a mí cuando defendí su posición. Un compañero que lee a Dussel me dijo: Zea quiere que nos dejen entrar. Quiere que lo que hacemos aquí sea aceptado como filosofía sin más, y para eso hay que satisfacer un criterio de lo que cuenta como filosofía que sigue fijándose en otra parte. Él no quiere entrar: quiere discutir quién reparte las entradas."},
   {quien:"Zea", texto:"Su compañero tiene un argumento serio y no lo voy a esquivar. Le respondo dos cosas. La primera es que yo no pido permiso para entrar: sostengo que nunca hubo una puerta, que el tribunal es imaginario y que la manera de probarlo es trabajar como si no existiera. La segunda es que América Latina es Occidente, aunque sea el Occidente que quedó del lado del instrumento y no del lado de la mano. Renunciar a esa herencia no nos libera, nos empobrece: sería regalarle a Europa lo que también es nuestro.", nota:"Este intercambio reproduce un desacuerdo histórico real y no una tensión inventada para el diálogo. La Filosofía de la Liberación que surge alrededor de 1971 con Dussel, Scannone, Cerutti Guldberg y otros se formó leyendo a Zea, y sin embargo le reprochó tres cosas: que su sujeto sea un nosotros americano culturalmente homogéneo en lugar del oprimido, categoría que divide a ese nosotros por dentro; que acepte la pertenencia a Occidente en vez de buscar un exterior o una transmodernidad; y que su meta sea el reconocimiento como filosofía sin más, cuando quien otorga ese reconocimiento es el mismo centro que produjo la exclusión. Zea respondió en varias ocasiones, sobre todo en Dependencia y liberación en la cultura latinoamericana, que definirse por oposición a Europa es otra forma de seguir dependiendo de ella. El debate no está cerrado, y Horacio Cerutti Guldberg mostró además que la propia Filosofía de la Liberación se dividió internamente en al menos cuatro corrientes sobre este mismo punto."},
   {quien:"Estudiante", texto:"Hay algo en su respuesta que me inquieta, y prefiero decirlo. Usted dirigió centros, revistas, colecciones, congresos. Su filosofía se volvió el programa de la materia que yo curso. Una crítica de la dependencia que termina siendo el contenido oficial de la asignatura, ¿no es sospechosa? A los que quedaron afuera nadie les dio una cátedra."},
   {quien:"Zea", texto:"Es una sospecha legítima y no tengo cómo refutarla desde adentro, porque cualquier respuesta mía sería la respuesta del que ocupó el cargo. Le doy el único argumento que me parece honesto: sin colección, sin revista y sin cátedra, esta discusión que usted y yo estamos teniendo no existiría, porque no habría dónde tenerla ni con quién. Construir las condiciones para que alguien pueda criticarme es también parte del trabajo. Ahora bien, el que usted debería vigilar no soy yo sino el efecto: cuando una crítica se vuelve programa, deja de incomodar y empieza a evaluarse en un examen."},
   {quien:"Estudiante", texto:"Última pregunta, y es la que más me cuesta. Usted dice que América es la conciencia de Occidente, el lugar donde se ven sus contradicciones. ¿No es eso concederle a Hegel demasiado? Seguimos siendo un momento de la historia de Europa, aunque ahora sea el momento lúcido."},
   {quien:"Zea", texto:"Le concedo que uso su aparato, y lo hago a propósito: no hay manera de discutir con Hegel desde afuera de Hegel sin quedarse en la injuria. Pero mire qué le hago a ese aparato. Él coloca el momento de verdad de la historia en el Estado europeo y deja a América como tierra del futuro, todavía inmadura. Yo digo que la verdad de un proceso no se ve donde el proceso se celebra a sí mismo, sino donde se pagan sus costos; y que por eso quien fue instrumento entiende la operación mejor que quien la dirigió.", nota:"Conviene marcar con precisión qué toma Zea de Hegel y qué invierte, porque es el nudo filosófico del módulo y suele resumirse mal. Toma la idea de que la historia es un proceso de la conciencia que avanza por contradicciones y que un pueblo puede ser el lugar donde una época se hace consciente de sí. Invierte quién ocupa ese lugar: en Hegel el espíritu llega a sí en el mundo europeo y América queda excluida de la historia efectiva; en Zea el punto de máxima lucidez es el margen, porque desde allí se ve a la vez el relato del centro y aquello que el relato omite. La estructura del argumento recuerda además a la dialéctica del amo y el esclavo, donde es el esclavo —el que trabaja y el que teme— quien accede a la verdad de la relación, y esa deuda es reconocida por el propio Zea. La objeción del estudiante sigue en pie y es discutida en serio por el pensamiento decolonial posterior: una inversión hecha con las categorías del adversario, ¿rompe el marco o lo confirma?"}
 ]},
 actividades:[
   {t:"Auditoría de asimilismo en un texto real", d:"Elegí un documento real y reciente de tu entorno: una política pública educativa colombiana, un lineamiento curricular del Ministerio, el plan de estudios de tu propia carrera, un informe de un organismo internacional sobre la región, o una columna de opinión de un diario nacional. Subrayá todos los marcos teóricos, indicadores, autores y modelos que provienen de otro contexto, y armá una tabla con tres columnas. En la primera anotá el marco importado. En la segunda, qué problema resolvía en el lugar donde se produjo. En la tercera, qué problema real del contexto colombiano resuelve aquí, si es que resuelve alguno, y con qué evidencia lo sabés. Después clasificá cada fila con el par de Zea: imitación, si el marco llegó por prestigio y el caso local entró solo como ilustración, o asimilación, si fue transformado para responder una pregunta que ya existía aquí. Cerrá con una página que responda dos cosas: cuál fue la fila más difícil de clasificar y por qué, y si alguna vez encontraste el caso inverso —un marco producido en la región que se exporta o se usa afuera— porque su presencia o su ausencia dice bastante sobre el estado de la dependencia que Zea describe."},
   {t:"Reescribir una pregunta propia partiendo de vos mismo", d:"Tomá una pregunta académica o personal que estés trabajando de verdad ahora mismo: el tema de un ensayo, una decisión sobre tu profesión, un problema de tu práctica docente, una discusión que tenés pendiente con alguien. Escribila primero en su versión neutra y universal, como la formularías en un examen, sin mencionar tu país, tu clase social, tu lengua, tu institución ni tu biografía. Escribila después en versión situada, obligándote a nombrar todo eso de forma explícita: desde dónde la hacés, quién más la hace en tu contexto, qué le debe a tu historia particular. Ahora comparalas con tres preguntas de control. ¿Cambian los datos que necesitás para responderla? ¿Cambian los autores que te resultan útiles? ¿Cambia la respuesta misma, o solo el decorado? Si al final resulta que no cambia nada, ese es un resultado valioso y hay que decirlo: significa que en ese caso la pregunta era efectivamente transportable, y eso es una objeción real contra la lectura fuerte de Zea. Si cambia la respuesta, identificá el paso exacto donde el marco heredado dejó de servir, porque según Zea ahí es donde empieza el trabajo filosófico propio."},
   {t:"Hegel contra Zea, con los textos a la vista", d:"Conseguí el pasaje de la introducción a las Lecciones sobre la filosofía de la historia universal donde Hegel trata de América como tierra del porvenir y sostiene la inmadurez de su naturaleza y de sus pueblos, y ponelo al lado de un pasaje de Zea sobre América como conciencia. Hacé tres tareas en orden. Primera, reconstruí el argumento de Hegel en forma de premisas y conclusión, del modo más fuerte posible y sin ironía, porque una versión caricaturizada no sirve para discutir. Segunda, mostrá con precisión qué elemento conserva Zea de ese aparato —la conciencia, la contradicción, la idea de que un pueblo puede ser el lugar donde una época se sabe a sí misma— y cuál invierte. Tercera, escribí dos párrafos finales enfrentados: en el primero defendé que la inversión de Zea es un golpe demoledor porque usa la propia maquinaria del adversario para mostrar que el resultado que él extrajo no se sigue; en el segundo defendé la objeción contraria, que quien acepta el aparato ya aceptó lo esencial y solo discute el lugar que le asignan dentro de él. Terminá tomando partido de manera explícita y argumentada, no diciendo que ambas tienen algo de razón."}
 ],
 cuestionario:[
   {q:"La consigna de la filosofía sin más, ¿resuelve el problema de la legitimidad o simplemente lo declara resuelto por decreto?", p:"La objeción es fuerte y conviene formularla en su mejor versión antes de responderla. Zea constata que el latinoamericano se pregunta si lo que hace es filosofía mientras el europeo no se lo pregunta, y concluye que la pregunta está mal planteada y hay que dejar de hacérsela. Pero una asimetría institucional no desaparece porque una de las partes deje de reconocerla: si las revistas indexadas, los comités editoriales, los criterios de evaluación y las bibliografías obligatorias siguen situados mayoritariamente en el norte, declarar imaginario el tribunal no cambia quién decide qué se publica y qué se cita. En ese sentido la maniobra parece terapéutica más que estructural: cura al filósofo de su angustia sin tocar el aparato que la produce. La defensa de Zea tiene dos movimientos. El primero es que su tesis no es solo un consejo psicológico sino una afirmación sobre la naturaleza de toda filosofía: si es verdad que ningún sistema se produjo fuera de una circunstancia, entonces la pretensión europea de universalidad sin lugar es filosóficamente falsa, y eso vale con independencia de quién administre las revistas. El segundo es pragmático y es el que él prefiere: la legitimidad no se obtiene discutiéndola sino produciendo obra, igual que nadie acreditó por adelantado el derecho de los griegos o de los alemanes a filosofar. La evaluación honesta es intermedia: como argumento filosófico, la tesis se sostiene; como estrategia frente a una división internacional del trabajo intelectual muy material, es insuficiente por sí sola, y la generación siguiente lo señaló."},
   {q:"¿Es Zea demasiado conciliador frente a la posición más radical de Dussel, o su moderación esconde una ventaja que la radicalidad pierde?", p:"Hay que empezar por precisar el desacuerdo, porque decir que uno es moderado y el otro radical no explica nada. Difieren en el sujeto: Zea filosofa desde un nosotros americano entendido como comunidad histórica y cultural; Dussel desde la víctima, el oprimido, categoría que atraviesa ese nosotros y lo divide, de modo que el latifundista y el campesino no comparten circunstancia por el hecho de compartir continente. Difieren en la relación con Occidente: Zea sostiene que América Latina es parte de Occidente, aunque sea desde el margen, y que renunciar a esa herencia es empobrecerse; Dussel propone una exterioridad y una transmodernidad que no se define desde el proyecto moderno. Y difieren en la meta: incorporación en pie de igualdad frente a impugnación de quién fija el criterio. A favor de la radicalidad de Dussel: la crítica de Zea puede quedar contenida dentro del marco que critica, y su diagnóstico es demasiado culturalista para un problema que también es económico y geopolítico. A favor de la moderación de Zea: al negarse a construir una identidad americana definida por oposición a Europa, evita el esencialismo en el que cayeron otros latinoamericanismos, evita la trampa de convertir a la víctima en una figura pura e incuestionable, y conserva el derecho a usar cualquier instrumento útil venga de donde venga. Una manera productiva de cerrar es notar que la distancia entre ambos es menor de lo que sugieren sus tonos: ambos rechazan el universalismo abstracto, ambos parten de la situación histórica, y el propio Cerutti Guldberg mostró que la Filosofía de la Liberación se dividió internamente en corrientes que reproducen este mismo debate."},
   {q:"Si toda filosofía parte de una circunstancia particular, ¿cómo puede aspirar a decir algo válido para quienes no comparten esa circunstancia?", p:"Este es el problema metodológico de fondo del módulo y no tiene solución fácil, aunque sí tiene formulaciones mejores y peores. La versión débil de la tesis dice que toda filosofía tiene un origen situado pero que sus argumentos, una vez formulados, se evalúan por razones accesibles a cualquiera; en esa versión la circunstancia explica de dónde viene la pregunta y no qué hace verdadera la respuesta, y no hay ningún problema de comunicación entre tradiciones. La versión fuerte dice que la circunstancia determina también los criterios de validez, y entonces aparece la dificultad clásica del relativismo: si cada quien juzga con criterios propios, no hay desacuerdo posible sino coexistencia de monólogos, y la propia crítica de Zea al eurocentrismo pierde fuerza, porque el europeo podría contestarle que desde su circunstancia su universalismo es perfectamente válido. Zea evita explícitamente la versión fuerte: su argumento es que reconocer la propia circunstancia es la condición del diálogo entre iguales y no su obstáculo, porque el falso universalismo es justamente lo que impide dialogar, al presentar como neutral lo que es particular. El paralelo más útil para pensarlo es la teoría del punto de vista en la epistemología feminista, con Sandra Harding y Donna Haraway, que enfrentó exactamente este dilema y respondió con la noción de objetividad fuerte: partir explícitamente de una posición situada produce mejor conocimiento que fingir una vista desde ninguna parte, porque permite auditar los supuestos que la falsa neutralidad esconde. La pregunta que queda abierta, en Zea y en Harding, es cómo se arbitra un desacuerdo entre dos posiciones situadas sin apelar a un criterio que no esté situado."},
   {q:"La tesis de América como conciencia de Occidente, ¿es una refutación de Hegel o una prolongación suya con los papeles cambiados?", p:"Las dos cosas, y ese es exactamente el interés del caso. Lo que Zea conserva de Hegel es sustancial: la historia como proceso de la conciencia que avanza por contradicciones, la idea de que una época puede hacerse consciente de sí en un lugar determinado, y la estructura de la dialéctica del amo y el esclavo, donde es el que trabaja y el que teme quien accede a la verdad de la relación mientras el amo permanece en la ilusión de su propia autonomía. Lo que invierte es quién ocupa el lugar de la lucidez: Hegel deja a América fuera de la historia efectiva, como tierra del porvenir cuya naturaleza y cuyos pueblos serían inmaduros, y hace culminar el proceso en el mundo europeo; Zea sostiene que la verdad de un proceso no se ve donde el proceso se celebra a sí mismo sino donde se pagan sus costos, y que por eso el margen es un mirador y no una carencia. La objeción de que esto concede demasiado es real y la sostiene buena parte del pensamiento decolonial posterior: quien discute dentro del aparato del adversario ya aceptó el terreno, el vocabulario y la idea misma de una historia universal con un sentido único. La respuesta disponible es doble. Primero, que no hay crítica interna posible sin usar las categorías del criticado, y que las críticas puramente externas suelen ser inaudibles para quien debería escucharlas. Segundo, y más importante, que la inversión no deja el aparato intacto: si el lugar de la verdad es el margen, entonces desaparece la jerarquía que era el punto de todo el sistema hegeliano, y lo que queda ya no es la filosofía de la historia de Hegel con otro protagonista, sino una historia que no puede escribirse completa sin las voces que aquella necesitaba omitir."},
   {q:"Su éxito institucional y su aceptación académica, ¿dicen algo sobre cuán inofensiva resultó finalmente su crítica?", p:"La pregunta es incómoda y merece una respuesta que no sea ni cínica ni devota. Los hechos son claros: Zea dirigió proyectos en la Universidad Nacional Autónoma de México, impulsó desde el Fondo de Cultura Económica la colección Tierra Firme, dirigió el Centro Coordinador y Difusor de Estudios Latinoamericanos y Cuadernos Americanos, organizó congresos continentales y recibió honores en vida, mientras otros pensadores más confrontativos trabajaron desde la marginalidad o el exilio, como el propio Dussel tras el atentado que sufrió en 1973 y su salida de Argentina. Hay una lectura sospechosa y tiene argumentos: una crítica que se convierte en programa oficial de la asignatura deja de incomodar y pasa a evaluarse en un examen; el culturalismo de Zea, al tratar la dependencia como asunto de conciencia más que de estructura económica, era compatible con casi cualquier gobierno, incluido el mexicano de partido único que financiaba sus instituciones; y su afirmación de que América Latina pertenece a Occidente removía el aguijón más filoso de la crítica anticolonial. Hay también una lectura contraria, y es seria: institucionalizar es la única manera de que una tradición sobreviva a su fundador, y la historia de las ideas latinoamericana existe hoy como disciplina, con cátedras, revistas y tesis, en buena medida por su gestión; muchos de quienes lo critican se formaron en espacios que él creó, lo que es a la vez una ironía y una prueba de eficacia. La conclusión razonable no elige un bando sino que separa dos preguntas que la sospecha mezcla. Que una crítica sea aceptada no prueba que sea falsa, porque también las buenas ideas se institucionalizan; pero sí obliga a preguntar qué partes fueron aceptadas y cuáles quedaron fuera. En el caso de Zea la respuesta es instructiva: lo que entró al programa fue la historia de las ideas como disciplina y la consigna de partir de nosotros mismos; lo que quedó afuera fue la pregunta por quiénes, dentro de ese nosotros, siguen sin tener voz propia, y esa es justamente la pregunta que retomaron la Filosofía de la Liberación y el pensamiento decolonial."}
 ],
 cadena:{ titulo:"¿Existe una filosofía latinoamericana?", intro:"Un razonamiento en ramas sobre la polémica de 1968-1969. El peruano Augusto Salazar Bondy publicó ¿Existe una filosofía de nuestra América?, y respondió que no: la nuestra sería una filosofía imitativa, reflejo de una cultura dominada. Leopoldo Zea le respondió al año siguiente con La filosofía americana como filosofía sin más. Las ramas recorren los dos lados.", inicio:"n1", nodos:{
   n1:{ pregunta:"Salazar Bondy sostiene que no hay una filosofía auténtica en América Latina porque somos culturas dependientes: copiamos sistemas ajenos, y la autenticidad solo llegará cuando se supere la dominación. ¿Qué pensás?", opciones:[
     {texto:"Tiene razón: mientras haya dependencia, solo hay imitación.", va:"n2a"},
     {texto:"La pregunta está mal planteada: toda filosofía nace de una circunstancia, y la nuestra también.", va:"n2b"} ]},
   n2a:{ pregunta:"Zea objeta algo concreto: aun cuando los latinoamericanos adoptaron ideas ajenas, las adoptaron por razones propias y las usaron para sus propios problemas. ¿Adoptar es lo mismo que copiar?", opciones:[
     {texto:"Sí: adoptar un sistema europeo no es filosofar.", final:{tipo:"revisar", texto:"Zea lo discute con un caso que estudió a fondo en El positivismo en México: el positivismo de Comte, en México, fue usado para justificar el orden del porfiriato y los intereses de una burguesía naciente. El mismo sistema hizo allá otra cosa que en Francia. Elegir qué adoptar, cómo y para qué es ya una respuesta a una circunstancia. Volvé un paso y probá la otra respuesta."}},
     {texto:"No necesariamente: el modo de adoptar ideas ajenas ya responde a problemas propios.", va:"n3a"} ]},
   n3a:{ pregunta:"Si la manera de adoptar es propia, la historia de esas adopciones dice algo sobre nosotros. ¿Qué se sigue para la filosofía latinoamericana?", opciones:[
     {texto:"Que la historia de las ideas en América Latina es ya filosofía: muestra cómo pensamos nuestros problemas, aun con herramientas ajenas.", final:{tipo:"bien", texto:"Es la apuesta de Zea, y le dio a toda una generación una tarea: reconstruir la historia de las ideas del continente como historia de una conciencia. El valor es enorme; él y su seminario la hicieron posible como disciplina."}},
     {texto:"Que la filosofía latinoamericana es, sobre todo, historia de las ideas.", final:{tipo:"bien", texto:"Es la crítica que muchos le hicieron a Zea: que hizo más historia que filosofía, y que describir cómo se pensó no es pensar los problemas. Salazar Bondy podría responder que eso confirma su punto: tenemos historiadores de ideas ajenas, no filósofos. Zea respondería que pensar la propia historia es el problema filosófico de una cultura colonizada. La discusión sigue abierta."}} ]},
   n2b:{ pregunta:"Zea propone una «filosofía sin más»: sin el adjetivo «latinoamericana». ¿Qué significa eso en la práctica?", opciones:[
     {texto:"Que no hay que buscar contenidos exclusivamente latinoamericanos: basta filosofar con rigor sobre nuestros problemas, y el resultado será filosofía.", va:"n3b"},
     {texto:"Que hay que rechazar la filosofía europea y crear una propia desde cero.", final:{tipo:"revisar", texto:"Zea rechaza ese extremo con la misma fuerza que el otro. Partir de nosotros mismos no es partir de la nada: es partir de una circunstancia que incluye a Europa, porque la colonización la metió dentro de nuestra historia. Rechazar la filosofía europea sería otra manera de no asumir el propio pasado. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Zea critica el eurocentrismo, pero sostiene que la filosofía aspira a valer para todos. ¿Son compatibles esas dos cosas?", opciones:[
     {texto:"Sí: lo universal no es el punto de partida sino el resultado; todo filosofar es desde algún lugar y aspira a valer para todos.", final:{tipo:"bien", texto:"Es la tesis de Zea en su forma más clara. Lo que critica del eurocentrismo no es la aspiración a lo universal, sino que Europa haya confundido su circunstancia con la de la humanidad. La tarea no es renunciar a lo universal, sino no confundirlo con un lugar particular."}},
     {texto:"Hay una tensión: Zea usa el aparato de Hegel —la conciencia, la historia universal— para criticar a Hegel.", final:{tipo:"bien", texto:"Es la crítica que le hizo la Filosofía de la Liberación, y Dussel en particular: Zea pide incluir a América Latina en la historia universal, pero sin cuestionar del todo el marco que la había excluido. Dussel buscó, con la exterioridad, un punto de partida fuera de ese marco. Zea respondería que no hay un afuera desde el cual empezar de cero."}} ]}
 }},
 reconstruccion:[
   { titulo:"La filosofía americana como filosofía sin más (1969)",
     consigna:"Reconstruí el argumento central del ensayo. Una pieza saca una conclusión que Zea rechaza: dejala afuera y ordená el resto.",
     piezas:[
       {id:"z1", texto:"Preguntar si existe una filosofía latinoamericana presupone un modelo de filosofía —el europeo— con el cual se mide la nuestra.", tipo:"premisa"},
       {id:"z2", texto:"Pero la filosofía europea también nació de circunstancias concretas: la polis griega, la cristiandad medieval, la ciencia moderna, y respondió a sus propios problemas.", tipo:"premisa"},
       {id:"z3", texto:"Su universalidad no fue un punto de partida: fue el resultado de pensar con rigor esos problemas y de su peso en la historia.", tipo:"premisa"},
       {id:"z4", texto:"Quien piense con rigor los problemas de América Latina —la dependencia, la identidad, la libertad— está haciendo lo mismo que hicieron los europeos.", tipo:"premisa"},
       {id:"z5", texto:"Por lo tanto, no hace falta preguntar si existe una filosofía latinoamericana: hace falta filosofar desde nuestra circunstancia, y lo que resulte será filosofía sin más.", tipo:"conclusion"},
       {id:"zx", texto:"Por lo tanto, la filosofía europea no tiene validez para América Latina.", tipo:"distractor"}
     ],
     ordenCorrecto:["z1","z2","z3","z4","z5"],
     explicacion:"El argumento desarma la pregunta mostrando que el modelo con que se nos medía tiene el mismo origen situado que se nos reprochaba (z2). El punto débil está en z3: si la universalidad europea fue también el resultado de su peso en la historia —es decir, de su poder—, entonces la universalidad de una filosofía latinoamericana no dependería solo de su rigor, sino también de que alguien la reconozca. El argumento mostraría que podemos filosofar, pero no que el mundo nos vaya a escuchar. La pieza sobrante es el extremo que Zea rechaza: para él, Europa es parte de nuestra circunstancia, no algo ajeno que haya que expulsar."},
   { titulo:"Colonialismo mental y yuxtaposición",
     consigna:"Reconstruí el diagnóstico de Zea sobre la historia intelectual latinoamericana. Una pieza propone una salida que Zea considera otra forma del mismo error: dejala afuera.",
     piezas:[
       {id:"c1", texto:"La independencia política del siglo XIX no trajo independencia mental.", tipo:"premisa"},
       {id:"c2", texto:"Las élites intentaron librarse de la herencia española adoptando modelos franceses, ingleses o estadounidenses.", tipo:"premisa"},
       {id:"c3", texto:"Cada ola importada quiso borrar la anterior sin asumirla: la historia latinoamericana se fue yuxtaponiendo, en lugar de asimilarse en el sentido hegeliano de conservar superando.", tipo:"premisa"},
       {id:"c4", texto:"Un pasado que no se asume no desaparece: vuelve, como problema no resuelto.", tipo:"premisa"},
       {id:"c5", texto:"Por lo tanto, la liberación exige asumir la propia historia, incluida la colonial, no negarla.", tipo:"conclusion"},
       {id:"cx", texto:"Por lo tanto, hay que volver a la cultura precolombina y rechazar toda la herencia europea.", tipo:"distractor"}
     ],
     ordenCorrecto:["c1","c2","c3","c4","c5"],
     explicacion:"El diagnóstico usa una categoría de Hegel —la asimilación como superación que conserva— para leer una historia que Hegel había dejado fuera de la historia universal. El punto débil es c3: supone que América Latina es un solo sujeto con una sola historia que asumir. Los pueblos indígenas o las comunidades afrodescendientes podrían no reconocerse en ese «nosotros» que asume el pasado colonial como propio. La pieza sobrante repite el error que Zea diagnostica: querer borrar una etapa de la historia, solo que ahora la europea en lugar de la española."}
 ],
 dilemas:[
   { titulo:"El plan de estudios",
     intro:"Zea pasó buena parte de su vida construyendo las instituciones —seminarios, revistas, cátedras— que hicieron posible estudiar filosofía latinoamericana. Este caso lleva su tesis a una decisión institucional concreta.",
     pasos:[
       { id:"p1", situacion:"Formás parte del comité que revisa el plan de estudios de la licenciatura en filosofía de una universidad del Tolima. Los diez cursos obligatorios de historia de la filosofía son todos de autores europeos. ¿Qué proponés?", opciones:[
         {texto:"Agregar un curso optativo de filosofía latinoamericana.", consecuencia:"Es lo más fácil de aprobar, y es lo que Zea llamaría yuxtaposición: lo latinoamericano queda al lado, como un tema especial, mientras el resto del plan sigue igual. El mensaje implícito es que la filosofía sin adjetivo es la europea.", va:"p2"},
         {texto:"Organizar los cursos por problemas —la libertad, la justicia, el conocimiento— e incluir en cada uno autores europeos, latinoamericanos y de otras tradiciones.", consecuencia:"Es la «filosofía sin más» llevada al currículo: los autores latinoamericanos entran como filósofos que discuten los mismos problemas, no como una categoría aparte. Es más difícil de diseñar y exige docentes que conozcan varias tradiciones.", va:"p2"},
         {texto:"Reemplazar la mitad de los cursos europeos por cursos latinoamericanos.", consecuencia:"Corregís el desequilibrio de golpe, pero mantenés la separación entre lo europeo y lo nuestro como dos bloques. Zea no quería sustituir una tradición por otra, sino dejar de pensar en bloques.", va:"p2"} ]},
       { id:"p2", situacion:"Un colega del comité objeta: «Lo latinoamericano no es filosofía: es historia de las ideas, ensayo o literatura. Bajaríamos el nivel». ¿Qué le respondés?", opciones:[
         {texto:"«Tiene razón en parte: hay que elegir bien a los autores.»", consecuencia:"Concediste algo razonable: no todo texto latinoamericano es buena filosofía, como no todo texto europeo lo es. Pero dejaste en pie el supuesto de fondo: que el nivel se mide con una vara europea. Zea te diría que esa vara es la pregunta que hay que discutir.", va:"p3"},
         {texto:"«¿Con qué criterio decide qué es filosofía? Si es el rigor con que se piensa un problema, apliquémoslo a todos los autores por igual.»", consecuencia:"Llevaste la discusión al argumento de Zea: el criterio de lo filosófico no puede ser el origen del autor. Si el criterio es el rigor, se aplica a todos; si es la pertenencia a una tradición, eso no es un criterio de calidad.", va:"p3"},
         {texto:"«Eso es eurocentrismo.»", consecuencia:"Puede ser cierto, pero ponerle una etiqueta no lo refuta. Tu colega va a sentir que lo acusaste en lugar de responderle, y la discusión se cierra antes de empezar.", va:"p3"} ]},
       { id:"p3", situacion:"El plan se aprueba con cambios. Una estudiante de primer semestre te pregunta para qué le sirve estudiar a Zea si quiere dedicarse a la filosofía de la mente. ¿Qué le decís?", opciones:[
         {texto:"«Para tener cultura general sobre el continente.»", consecuencia:"Es una razón válida, pero pequeña, y confirma lo que Zea criticaba: que lo latinoamericano es contexto, no filosofía.", va:null},
         {texto:"«Porque te enseña a preguntarte desde dónde se formulan los problemas que vas a estudiar, también los de la filosofía de la mente.»", consecuencia:"Es la lección metodológica de Zea, aplicable a cualquier área: ningún problema filosófico se plantea desde ningún lugar.", va:null},
         {texto:"«Si no te interesa, no hace falta.»", consecuencia:"Respetás su interés, pero el plan nuevo se hizo para que lo latinoamericano no sea opcional. Si cada docente lo vuelve opcional en la práctica, el cambio queda en el papel.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar la polémica entre Salazar Bondy y Zea, y qué tiene de razonable cada posición.",
       "Distinguí entre yuxtaponer lo latinoamericano y asimilarlo dentro de la filosofía sin adjetivo.",
       "Evité los dos extremos que Zea rechaza: el universalismo abstracto y el rechazo de lo europeo.",
       "Respondí a la objeción del nivel con un criterio de calidad que se aplica a todos los autores por igual.",
       "Tuve en cuenta las condiciones institucionales concretas: docentes, bibliografía, tiempo.",
       "Pensé qué «nosotros» suponía mi propuesta, y si incluía a las tradiciones indígenas y afrodescendientes.",
       "Formulé la objeción más fuerte a mi propuesta."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.zea = { lecturas:[
 {titulo:"La filosofía americana como filosofía sin más", fuente:"Leopoldo Zea, La filosofía americana como filosofía sin más (Siglo XXI) — PDF íntegro alojado por un curso de la FFyL", url:"https://cursosluispatinoffyl.wordpress.com/wp-content/uploads/2014/01/leopoldo-zea-la-filosofc3ada-latinoamericana-como-filosofc3ada-sin-mc3a1s.pdf",
  extracto:`Zea parte de una pregunta que considera mal planteada: ¿existe una filosofía de nuestra América? Detrás de ella detecta un complejo de inferioridad heredado de la colonia, que obliga al pensamiento americano a justificar su derecho a existir ante un tribunal europeo. El libro registra hasta el tono angustiado de esa autointerrogación —«¿qué clase de hombres somos que no somos capaces de crear un sistema?»— y su respuesta consiste en desarmar el tribunal, no en ganar el juicio.

El argumento decisivo es comparativo y cabe en una frase: «a ningún griego se le ocurrió preguntarse por la existencia de una filosofía griega»; simplemente pensaban, creaban, filosofaban. Ninguna filosofía es universal por venir de ningún lugar: toda filosofía nace de una circunstancia concreta y responde a los problemas de esa circunstancia. Lo que hizo el europeo fue filosofar desde su propia situación y lograr, además, que su filosofía valiera como filosofía sin más. Descartes escribe desde la crisis de la escolástica y las guerras de religión; Kant, desde el problema de la ciencia newtoniana y el pietismo prusiano; Hegel, desde la Revolución Francesa y el Estado alemán. Que su pensamiento se haya vuelto universal no significa que naciera universal: significa que fue capaz de plantear su circunstancia con hondura suficiente para que otros se reconocieran en ella.

Por eso el latinoamericano no tiene que elegir entre imitar a Europa o inventar una filosofía exótica. Se trata, dice Zea, de «partir de nosotros mismos, de nuestras circunstancias, de nuestros límites, de nuestro ser americanos, al igual que el griego ha partido de una circunstancia llamada Grecia». Lo americano no se busca como tema, aparece como resultado: si uno piensa con honestidad su propia situación, lo propio sale solo, igual que a los europeos les salió lo suyo sin proponérselo. De ahí también su tesis antropológica: «ser hombre no es ser yanqui, francés o inglés; ser hombre es ser, simplemente, lo que se es».

Zea insiste en la diferencia entre imitación y asimilación —«si no se puede dejar de imitar, al menos inventar un poco, asimilar»—. El pensamiento latinoamericano pasó por olas sucesivas —escolástica, ilustración, positivismo, marxismo, existencialismo— muchas veces adoptadas como modas que no respondían a problemas propios. El positivismo mexicano del porfiriato es su caso de estudio preferido: una doctrina importada que sirvió menos para pensar el país que para legitimar un orden político. Asimilar, en cambio, significa usar el instrumento europeo para responder una pregunta americana, transformándolo en el proceso.

De ahí su filosofía de la historia latinoamericana. América Latina es hija de la modernidad pero desde el lado del que fue instrumentalizado; es «occidental» y a la vez marginal a Occidente. Esa posición ambigua no es una carencia sino un punto de vista privilegiado: desde ahí se ve lo que la modernidad no dice de sí misma. Zea llama a asumir el pasado colonial críticamente, sin negarlo (como hacía el liberalismo) ni idealizarlo (como hacía el hispanismo conservador), porque «solo asumiendo el pasado es posible trascenderlo».

Su conclusión práctica es un programa de una línea, y es la frase con la que suele citárselo: «hay que intentar hacer pura y simplemente filosofía, que lo americano se dará». La originalidad, advierte tomando la idea de Francovich, no puede buscarse como un fin; aparece como subproducto de un trabajo honesto. La pregunta por la autenticidad se resuelve trabajando, no discutiendo la licencia para trabajar.`,
  comentario:"El giro de Zea es elegante: en lugar de reclamar un lugar especial para la filosofía latinoamericana, universaliza la situacionalidad y así iguala el terreno — también Kant filosofaba desde una circunstancia. Fijate en la distinción imitación/asimilación, que es una herramienta crítica aplicable a cualquier recepción de teoría. Su respuesta a la pregunta del cuestionario sobre el diálogo entre circunstancias es que reconocer la propia es justamente lo que permite hablar de igual a igual."}
], preguntasLectura:[
 {q:"¿Cuál es el argumento central de Zea contra la pregunta «¿existe una filosofía de nuestra América?»", opciones:["Que no existe y hay que aceptarlo","Que toda filosofía, incluida la europea, nace de una circunstancia concreta","Que solo la filosofía indígena es auténtica","Que la filosofía debe ser universal y abstracta"], r:"Que toda filosofía, incluida la europea, nace de una circunstancia concreta", why:"«A ningún griego se le ocurrió preguntarse por la existencia de una filosofía griega»: el punto es igualar el terreno, no pedir permiso."},
 {q:"¿Qué diferencia establece Zea entre imitación y asimilación?", opciones:["Ninguna: son sinónimos","Imitar es adoptar doctrinas como moda; asimilar es usarlas para responder preguntas propias, transformándolas","Imitar es copiar textos; asimilar es traducirlos","Imitar es europeo; asimilar es indígena"], r:"Imitar es adoptar doctrinas como moda; asimilar es usarlas para responder preguntas propias, transformándolas", why:"Su caso de estudio es el positivismo del porfiriato, adoptado más para legitimar un orden que para pensar el país."},
 {q:"¿Cómo aparece «lo americano» en una filosofía auténtica, según Zea?", opciones:["Como tema explícito que hay que buscar","Como resultado espontáneo de pensar con honestidad la propia circunstancia","Por decreto de las universidades","Imitando a los autores europeos"], r:"Como resultado espontáneo de pensar con honestidad la propia circunstancia", why:"Igual que a los europeos «les salió lo suyo» sin proponérselo; por eso propone dejar de discutir la licencia y trabajar."},
 {q:"¿Con qué consigna resume Zea su programa?", opciones:["«Primero la identidad, después la filosofía»","«Hay que intentar hacer pura y simplemente filosofía, que lo americano se dará»","«Imitar mejor a Europa»","«La filosofía debe ser nacional antes que humana»"], r:"«Hay que intentar hacer pura y simplemente filosofía, que lo americano se dará»", why:"La originalidad no puede buscarse como fin: aparece como subproducto de un trabajo filosófico honesto sobre problemas reales."}
]};
