/* ============================================================
   Ficha: zuleta  ·  tradición: americana
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"zuleta", trad:"americana", nombre:"Estanislao Zuleta", fechas:"1935–1990 · Colombia", escuela:"Pensamiento crítico colombiano", icon:"📖", profundizada:true,
 tesis:"Deseamos la facilidad: un amor sin conflictos, una sociedad reconciliada, una verdad que no nos exija cambiar. Ese deseo de un paraíso sin dificultades no es inocente: nos vuelve incapaces de soportar al otro tal como es, y nos lleva a idealizar a los nuestros y a convertir en enemigo absoluto a quien difiere. Zuleta propone lo contrario: un elogio de la dificultad, que acepte el conflicto como parte constitutiva de la vida en común y que aprenda a vivirlo sin destruir al otro. Pensar, leer, amar y hacer democracia son, para él, formas de trabajar con la dificultad en lugar de huir de ella.",
 obras:[
   {t:"Elogio de la dificultad (1980)", d:"Su texto más conocido, y uno de los ensayos más leídos de la filosofía colombiana. Lo pronunció como discurso cuando la Universidad del Valle le otorgó un doctorado honoris causa en psicología, a él, que nunca terminó el bachillerato. Es breve, de unas pocas páginas, y desarrolla una crítica del deseo de facilidad que atraviesa la vida amorosa, la política y el conocimiento. Deseamos, dice, una relación sin riesgos, una sociedad sin conflictos y un saber sin esfuerzo, y esos ideales de felicidad terminan justificando la intolerancia, porque todo lo que los perturba aparece como un enemigo. Frente a eso, propone reconocer la dificultad como condición de lo humano."},
   {t:"Sobre la lectura", d:"Una conferencia, publicada después en varias recopilaciones, en la que Zuleta sostiene que leer no es consumir información, sino un trabajo: el lector tiene que dejarse cuestionar por el texto, interpretarlo y arriesgarse a ser transformado por él. Critica la escuela que obliga a leer por obligación y para el examen, y que así enseña a odiar la lectura. Leer bien es leer desde una pregunta propia, y aceptar que el texto puede responder otra cosa. Para Zuleta, la lectura es una relación con otro, con las mismas dificultades que cualquier relación."},
   {t:"Sobre la idealización en la vida personal y colectiva", d:"Un ensayo que desarrolla la crítica de la idealización. Idealizar es atribuir a algo o a alguien una perfección que no tiene, y dividir el mundo en buenos absolutos y malos absolutos. Zuleta muestra cómo funciona en el amor, cuando se idealiza a la pareja y después se la odia por no cumplir la imagen, y en la política, cuando un grupo se idealiza a sí mismo y sataniza a sus adversarios. La idealización, dice, es la raíz psicológica del sectarismo y de la violencia, y su antídoto es la capacidad de reconocer la ambivalencia: que el otro, y uno mismo, no son ni ángeles ni demonios."},
   {t:"Colombia: violencia, democracia y derechos humanos (1991, póstumo)", d:"Recopilación de textos en los que Zuleta piensa la violencia colombiana. Uno de los más conocidos es «Sobre la guerra», donde sostiene que la guerra es una fiesta: une a un grupo contra un enemigo, suprime las dudas y las ambivalencias, y le da a la vida un sentido simple. Por eso es tan difícil combatirla: no basta con mostrar sus horrores. Para combatir la guerra, dice, hay que reconocer que el conflicto y la hostilidad son tan constitutivos de la sociedad como la cooperación, y aprender a vivirlos sin aniquilar al otro. Un pueblo maduro para la paz sería un pueblo maduro para el conflicto."},
   {t:"Educación y democracia: un campo de combate (1995, póstumo)", d:"Una larga conversación con el sociólogo Hernán Suárez, publicada después de su muerte, en la que Zuleta critica el sistema educativo. La escuela, dice, enseña respuestas a preguntas que los estudiantes nunca se han hecho, y así mata el deseo de saber. Separa el conocimiento de la experiencia del que aprende, y lo convierte en algo que se memoriza para aprobar. Una educación democrática, en cambio, partiría de las preguntas de los estudiantes, aceptaría el conflicto de ideas y enseñaría a pensar por cuenta propia. Es uno de los textos más leídos por docentes colombianos."}
 ],
 conceptos:[
   {t:"El elogio de la dificultad", d:"Es su idea central. Deseamos la facilidad: un amor sin conflictos, en el que el otro adivine nuestros deseos; una sociedad sin tensiones, en la que todos piensen igual; un saber que no nos exija transformarnos. Zuleta llama a esos deseos ideales de felicidad, y muestra que son peligrosos: cuando la realidad no se parece a ellos, culpamos a algo o a alguien, y lo convertimos en enemigo. El elogio de la dificultad no es una apología del sufrimiento, sino una invitación a aceptar que la vida con otros es difícil, y que esa dificultad, bien vivida, es la condición de la libertad y del reconocimiento mutuo."},
   {t:"La idealización", d:"Idealizar es atribuir a algo una perfección que no tiene. Zuleta, influido por el psicoanálisis, muestra que la idealización tiene un reverso: la satanización. Quien idealiza a su grupo, a su partido o a su pareja necesita encontrar un culpable de todo lo malo, y lo pone afuera. Así se forma el pensamiento binario: nosotros, los buenos; ellos, los malos. La idealización impide ver la ambivalencia, que es la condición real de las personas y de los grupos: nadie es solo bueno ni solo malo. Para Zuleta, esta estructura explica buena parte del sectarismo político colombiano, en la izquierda y en la derecha."},
   {t:"El conflicto como constitutivo", d:"Frente a los ideales de una sociedad reconciliada, Zuleta sostiene que el conflicto no es una anomalía que haya que eliminar, sino una parte constitutiva del vínculo social, tan real como la cooperación. Donde hay seres humanos distintos, hay intereses, deseos y valores en tensión. El problema no es el conflicto, sino la manera de vivirlo: la guerra lo resuelve eliminando al otro; la democracia lo resuelve reconociéndolo y dándole formas para expresarse sin violencia. La paz, en este sentido, no es la ausencia de conflicto, sino la capacidad de tramitarlo."},
   {t:"La guerra como fiesta", d:"Es una de sus tesis más inquietantes. La guerra no es solo horror: también ofrece una experiencia que la vida cotidiana no da. Une a un grupo contra un enemigo, suprime las dudas y las ambivalencias, simplifica el mundo en amigos y enemigos, y le da a cada uno un lugar y un sentido. Por eso es tan difícil combatirla: mostrar sus horrores no alcanza, porque la gente también la desea. Para Zuleta, solo un pueblo capaz de vivir sin esa simplificación, que acepte la complejidad y el conflicto, puede renunciar a la guerra."},
   {t:"Leer como trabajo", d:"Zuleta critica la idea de la lectura como consumo de información. Leer, dice, es un trabajo: hay que interpretar, ponerse en relación con el texto, dejarse cuestionar por él y arriesgarse a cambiar. Un buen lector no busca en el texto la confirmación de lo que ya piensa, sino una pregunta. Por eso critica la escuela que obliga a leer para el examen: así se aprende a odiar la lectura. Lo que propone no es leer más, sino leer de otra manera, desde las propias preguntas, y aceptar que un texto puede decir algo distinto de lo que esperábamos."},
   {t:"Educación y deseo de saber", d:"La escuela, dice Zuleta, enseña respuestas a preguntas que el estudiante nunca se hizo. Le entrega un conocimiento ya terminado, separado de su experiencia, que debe memorizar para aprobar, y así mata la curiosidad. Para él, el deseo de saber es lo más valioso, y la educación debería partir de él: de las preguntas reales de los estudiantes, del conflicto de ideas, de la posibilidad de equivocarse. Una educación democrática no es la que transmite contenidos sobre la democracia, sino la que practica el pensamiento propio y el debate."},
   {t:"Democracia como respeto por la diferencia", d:"Para Zuleta, la democracia no es solo un procedimiento electoral, sino una forma de vida que acepta la diferencia y el conflicto. Implica reconocer que el otro puede tener razón, que uno puede equivocarse y que el adversario no es un enemigo que haya que eliminar. Es exigente, porque obliga a renunciar a la comodidad de las certezas absolutas y de los grupos que piensan igual. Esta idea de democracia, desarrollada en los años ochenta, en medio de la violencia política, sigue siendo una de las referencias del pensamiento sobre la paz en Colombia."},
   {t:"Marx, Freud y Nietzsche", d:"Zuleta fue un lector apasionado de los tres grandes críticos de la modernidad, a los que Paul Ricoeur llamó los maestros de la sospecha. De Marx tomó la crítica de la sociedad y de la ideología, aunque se alejó del marxismo dogmático y de los partidos que lo practicaban. De Freud, la atención al deseo, a la ambivalencia y a lo que no sabemos de nosotros mismos. De Nietzsche, la crítica de los ideales que disfrazan el resentimiento. Su originalidad estuvo en usarlos para pensar la vida cotidiana y la realidad colombiana, y en hacerlo en conferencias y conversaciones más que en tratados."},
   {t:"Un autodidacta y la palabra hablada", d:"Zuleta dejó el colegio a los dieciséis años y nunca obtuvo un título académico ordinario; se formó leyendo por su cuenta y discutiendo en grupos de estudio. Fue profesor en varias universidades, sobre todo en la Universidad del Valle, en Cali, y su obra es en gran parte oral: conferencias, clases y conversaciones que otros transcribieron y publicaron, muchas después de su muerte. Esa forma de trabajo es coherente con su pensamiento: el saber como diálogo, como lectura compartida y como trabajo con otros, y no como producto terminado."}
 ],
 conexion:"Lee a <b>Nietzsche</b>, cuya crítica de los ideales retoma, a Marx y a Freud, y los usa para pensar la vida cotidiana y la realidad colombiana. Su idea de que el conflicto es constitutivo de lo social lo acerca a <b>Hannah Arendt</b>, que pensó la pluralidad, y su crítica de la escuela que enseña respuestas sin preguntas lo acerca a <b>Dewey</b>. Comparte con <b>Dussel</b> y con <b>Zea</b> la pregunta por pensar desde América Latina, aunque Zuleta no se inscribió en la filosofía de la liberación y desconfió de los discursos que idealizan a un sujeto histórico. Su influencia es enorme entre docentes, psicoanalistas y activistas por la paz en Colombia. Murió en Cali en 1990. Una parte de su obra son transcripciones de conferencias editadas después de su muerte, así que conviene leer las ediciones con atención a su origen.",
 dialogo:{titulo:"¿Y la paz no era acabar con el conflicto?", lineas:[
   {quien:"Estudiante", texto:"Profesor Zuleta, en el colegio nos dicen que la paz es vivir sin conflictos. Usted dice lo contrario. ¿No es una contradicción querer la paz y defender el conflicto?"},
   {quien:"Zuleta", texto:"Defiendo el conflicto, no la guerra, que es otra cosa. Mirá tu casa: ¿hay conflictos?"},
   {quien:"Estudiante", texto:"Claro. Con mi hermana peleamos todo el tiempo. Y mis papás discuten."},
   {quien:"Zuleta", texto:"¿Y eso significa que se odian, que alguien tiene que irse?"},
   {quien:"Estudiante", texto:"No. Nos queremos. Pero pensamos distinto y queremos cosas distintas."},
   {quien:"Zuleta", texto:"Ahí está. Donde hay personas distintas hay conflicto, y donde no hay conflicto es porque alguien se calló o fue callado. Una familia sin conflictos sería una familia donde uno manda y los demás obedecen. La paz no es que se acabe el conflicto: es aprender a vivirlo sin destruir al otro."},
   {quien:"Estudiante", texto:"Pero entonces, ¿por qué hay guerra? Si todos sabemos que es horrible."},
   {quien:"Zuleta", texto:"Porque no es solo horrible. La guerra también es una fiesta: une a un grupo contra un enemigo, borra las dudas, le da a cada uno un lugar y un sentido. En la guerra todo es simple: nosotros, los buenos; ellos, los malos. La vida en paz, en cambio, es complicada: el vecino que no me gusta tiene derechos, mi grupo también se equivoca, el adversario a veces tiene razón."},
   {quien:"Estudiante", texto:"O sea que para que haya paz, la gente tiene que aguantar la complicación."},
   {quien:"Zuleta", texto:"Exactamente. Por eso hablo de elogio de la dificultad. Queremos que todo sea fácil: un amor sin peleas, una sociedad donde todos piensen como nosotros. Y cuando la realidad no se parece a ese sueño, buscamos un culpable y lo convertimos en enemigo. Un pueblo maduro para la paz es un pueblo maduro para el conflicto."},
   {quien:"Estudiante", texto:"¿Y qué tiene que ver eso con la escuela?"},
   {quien:"Zuleta", texto:"Todo. La escuela les da respuestas a preguntas que ustedes nunca se hicieron, y les enseña a no discutir. Si nunca aprendiste a pensar distinto de tu profesor sin que eso sea una falta de respeto, ¿cómo vas a aprender a vivir con un vecino que piensa distinto de vos?", nota:"Las ideas siguen de cerca el Elogio de la dificultad, «Sobre la guerra» y Educación y democracia. La forma del diálogo es una reconstrucción: Zuleta pensaba mucho en conversación, y buena parte de su obra son conferencias transcritas."}
 ]},
 actividades:[
   {t:"Inventario de mis ideales de felicidad", d:"Escribí, con honestidad, tres ideales de felicidad que tengas: cómo imaginás el amor perfecto, la familia ideal, el país que querrías. Para cada uno, preguntate con Zuleta: ¿qué conflictos o dificultades excluye ese ideal?, ¿qué pasa conmigo cuando la realidad no se le parece?, ¿a quién culpo? Terminá con una página sobre cómo sería una versión de esos ideales que incluyera la dificultad, en lugar de excluirla, y si te parece más o menos deseable."},
   {t:"Desmontar una idealización", d:"Elegí un caso de pensamiento binario en tu entorno: una discusión política en redes, una rivalidad entre barrios, colegios o equipos, una pelea familiar en la que cada parte se ve como la buena. Describí cómo cada lado se idealiza a sí mismo y sataniza al otro: qué palabras usa, qué hechos ve y cuáles ignora. Después, escribí un párrafo en el que intentes describir a cada parte con su ambivalencia: lo que tiene de razón y lo que tiene de error. Evaluá: ¿cambia algo en el conflicto si se lo mira así?"},
   {t:"Leer desde una pregunta", d:"Elegí un texto que te hayan obligado a leer en el colegio o la universidad y que no te haya interesado. Antes de releerlo, escribí una pregunta que te importe de verdad y que el texto podría ayudarte a pensar. Releelo desde esa pregunta, tomando notas de lo que te responde, de lo que te contradice y de lo que no esperabas. Escribí una página comparando las dos lecturas: la obligada y la que hiciste desde tu pregunta. ¿Leíste el mismo texto?"}
 ],
 cuestionario:[
   {q:"El elogio de la dificultad, ¿no es una manera de aceptar el sufrimiento o de resignarse a la injusticia?", p:"No, y la diferencia es importante. Zuleta no elogia el sufrimiento ni pide aceptar la injusticia: critica el deseo de un mundo sin dificultades, que imagina una armonía total —en el amor, en la sociedad, en el conocimiento— y que, al no encontrarla, busca culpables. La dificultad que elogia es la de vivir con otros que son distintos, la de pensar por cuenta propia, la de amar a alguien que no es la imagen ideal que teníamos. Esa dificultad no es una injusticia, sino la condición de la libertad. De hecho, su crítica de los ideales de felicidad apunta también contra las utopías políticas que justificaron la violencia en nombre de una sociedad perfecta. Combatir la injusticia, para Zuleta, requiere precisamente aceptar la dificultad: el conflicto, la negociación y el reconocimiento de que el adversario no es un demonio."},
   {q:"¿Qué quiere decir que la guerra es una fiesta? ¿No es una frase cínica?", p:"La frase no celebra la guerra: intenta explicar por qué es tan difícil terminarla. Si la guerra fuera solo horror, bastaría con mostrar sus consecuencias para que la gente la rechazara. Pero la guerra ofrece algo que la vida en paz no ofrece: une a un grupo contra un enemigo, simplifica el mundo en amigos y enemigos, suprime las dudas y las ambivalencias, y le da a cada persona un lugar y un propósito. Por eso hay quienes la desean, aunque no lo digan. Zuleta concluye que para combatir la guerra no basta condenarla moralmente: hay que construir una sociedad capaz de vivir la complejidad, el conflicto y la duda sin necesitar un enemigo absoluto. Para Colombia, esta tesis ayuda a entender por qué los acuerdos de paz no bastan si persiste la lógica del enemigo en la política y en la vida cotidiana."},
   {q:"¿Cómo se relaciona la crítica de la idealización con la violencia política colombiana?", p:"Zuleta sostiene que la idealización tiene un reverso: quien idealiza a su propio grupo necesita poner todo lo malo afuera, en un enemigo. Así se forma un pensamiento binario que divide el mundo en buenos y malos absolutos, y que justifica la eliminación del otro, porque el otro deja de ser una persona con razones y se convierte en la encarnación del mal. Esta estructura atraviesa la historia colombiana: la violencia entre liberales y conservadores, la guerra entre el Estado, las guerrillas y los paramilitares, y también la polarización política actual. Zuleta la criticó en todas sus formas, incluida la izquierda a la que él mismo había pertenecido, que también idealizaba a la revolución y satanizaba a sus adversarios. Su propuesta no es la tibieza, sino la capacidad de reconocer la ambivalencia: el otro tiene razones, y uno también se equivoca."},
   {q:"¿Qué critica Zuleta de la escuela, y qué propone?", p:"Critica que la escuela enseñe respuestas a preguntas que los estudiantes no se han hecho: entrega un conocimiento ya terminado, separado de la experiencia y del deseo de saber, que se memoriza para aprobar. Así mata la curiosidad, que es lo más valioso. Critica también que la escuela enseñe a obedecer y no a pensar, a evitar el desacuerdo con la autoridad en lugar de practicarlo con respeto. Propone una educación que parta de las preguntas de los estudiantes, que acepte el conflicto de ideas, que enseñe a leer como un trabajo y no como un consumo, y que forme para la democracia practicándola en el aula. La crítica es fuerte y sigue vigente, aunque se le puede objetar que un sistema educativo masivo, con docentes sobrecargados y evaluaciones estandarizadas como el Saber 11, tiene dificultades enormes para funcionar así. Zuleta respondería que precisamente por eso es un campo de combate."},
   {q:"¿Por qué buena parte de la obra de Zuleta son conferencias transcritas, y qué implica eso para leerlo?", p:"Zuleta dejó el colegio a los dieciséis años, se formó leyendo por su cuenta y pensó sobre todo en conversación: en clases, conferencias, grupos de estudio y diálogos. Muchos de sus textos más leídos son transcripciones de esas intervenciones, editadas por otros, varias de ellas después de su muerte en 1990. Esto tiene dos consecuencias. La primera es que su estilo es oral: claro, directo, con ejemplos de la vida cotidiana, lo que lo vuelve muy accesible. La segunda es que hay que leer con atención a las ediciones: algunas frases que circulan como citas suyas pueden no corresponder exactamente a lo que dijo, y conviene ir a las recopilaciones reconocidas. Su forma de trabajo es coherente con su pensamiento: el saber como diálogo y como trabajo compartido, no como producto terminado."}
 ],
 cadena:{ titulo:"¿La paz es el fin del conflicto?", intro:"Un razonamiento en ramas sobre la idea central de Zuleta, a partir del Elogio de la dificultad y de «Sobre la guerra». Las ramas recorren la diferencia entre conflicto y guerra, la idealización y lo que eso significa para la paz en Colombia.", inicio:"n1", nodos:{
   n1:{ pregunta:"Después del acuerdo de paz de 2016, muchas personas dijeron que Colombia por fin podría vivir sin conflicto. ¿Qué es la paz?", opciones:[
     {texto:"La ausencia de conflicto: una sociedad reconciliada, donde todos estemos de acuerdo.", va:"n2a"},
     {texto:"Una manera de vivir el conflicto sin destruir al otro.", va:"n2b"} ]},
   n2a:{ pregunta:"Zuleta sostiene que donde hay personas distintas, hay intereses y deseos en tensión, y que una sociedad sin conflicto solo es posible si alguien calla o es callado. ¿Qué hacés con eso?", opciones:[
     {texto:"Acepto que el conflicto es inevitable, pero sigo pensando que la meta es eliminarlo.", final:{tipo:"revisar", texto:"Si el conflicto es constitutivo de la vida con otros, eliminarlo exige eliminar la diferencia, y ese es el ideal de felicidad que Zuleta critica: el que, al no realizarse, busca culpables y justifica la intolerancia. Volvé un paso y probá la otra respuesta."}},
     {texto:"Entonces el problema no es el conflicto, sino la manera de vivirlo.", va:"n3a"} ]},
   n3a:{ pregunta:"Si el problema es la manera de vivir el conflicto, ¿qué la vuelve destructiva?", opciones:[
     {texto:"La idealización: cuando cada grupo se ve como el bueno absoluto y convierte al otro en enemigo absoluto.", final:{tipo:"bien", texto:"Es la tesis de Zuleta en «Sobre la idealización». La idealización tiene un reverso, la satanización, que divide el mundo en buenos y malos absolutos y vuelve legítimo eliminar al otro. El antídoto es reconocer la ambivalencia: el otro tiene razones y uno también se equivoca. Lo que queda abierto es cómo se enseña eso en una sociedad marcada por décadas de violencia."}},
     {texto:"La desigualdad: los conflictos son destructivos cuando hay injusticias materiales que no se resuelven.", final:{tipo:"bien", texto:"Es una respuesta que Zuleta no rechazaría: leyó a Marx y sabía que las condiciones materiales importan. Pero agregaría que la desigualdad no basta para explicar la violencia: hay sociedades desiguales sin guerra, y guerras que se mantienen aunque cambien las condiciones. Hace falta mirar también la estructura psicológica de la idealización y del enemigo."}} ]},
   n2b:{ pregunta:"Si la paz es vivir el conflicto sin destruir al otro, ¿por qué es tan difícil?", opciones:[
     {texto:"Porque la guerra también ofrece algo: une contra un enemigo, simplifica el mundo y da un sentido.", va:"n3b"},
     {texto:"Porque la gente no conoce los horrores de la guerra; si los conociera, la rechazaría.", final:{tipo:"revisar", texto:"Zuleta sostiene lo contrario: mostrar los horrores de la guerra no alcanza, porque la guerra no es solo horror; también es una fiesta que une y simplifica. Muchos que la conocieron de cerca la siguieron deseando. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Si la guerra es, en parte, una fiesta, ¿qué hace falta para renunciar a ella?", opciones:[
     {texto:"Un pueblo maduro para el conflicto: capaz de soportar la complejidad, la duda y la ambivalencia sin necesitar un enemigo absoluto.", final:{tipo:"bien", texto:"Es la conclusión de «Sobre la guerra». La paz exige un trabajo sobre nosotros mismos, no solo un acuerdo entre armados: aceptar que el adversario tiene razones y que uno también se equivoca. La objeción es que es una tarea cultural de generaciones, y que mientras tanto hay que proteger a las personas con instituciones. Zuleta no lo negaría."}},
     {texto:"Un enemigo común que una a todos los colombianos.", final:{tipo:"revisar", texto:"Es exactamente la lógica de la guerra que Zuleta critica: unir a un grupo contra un enemigo. Cambiar de enemigo no es salir de esa lógica, sino reproducirla. Volvé un paso y probá la otra respuesta."}} ]}
 }},
 reconstruccion:[
   { titulo:"Elogio de la dificultad (1980)",
     consigna:"Reconstruí el argumento con que Zuleta critica los ideales de felicidad. Una pieza convierte su tesis en un elogio del sufrimiento: dejala afuera y ordená el resto.",
     piezas:[
       {id:"e1", texto:"Deseamos la facilidad: un amor sin conflictos, una sociedad reconciliada, un saber que no nos exija transformarnos.", tipo:"premisa"},
       {id:"e2", texto:"Esos ideales de felicidad excluyen la diferencia: suponen que el otro se ajustará a lo que esperamos.", tipo:"premisa"},
       {id:"e3", texto:"Cuando la realidad no se parece al ideal, buscamos un culpable y lo convertimos en enemigo.", tipo:"premisa"},
       {id:"e4", texto:"Así, el deseo de un paraíso sin dificultades termina justificando la intolerancia y, en el extremo, la violencia.", tipo:"premisa"},
       {id:"e5", texto:"Por lo tanto, hay que aceptar la dificultad —el conflicto, la diferencia, el esfuerzo— como condición de la libertad y del reconocimiento del otro.", tipo:"conclusion"},
       {id:"ex", texto:"Por lo tanto, el sufrimiento es bueno en sí mismo, y hay que buscarlo.", tipo:"distractor"}
     ],
     ordenCorrecto:["e1","e2","e3","e4","e5"],
     explicacion:"El argumento va del deseo (e1) a su consecuencia política (e4), por medio de un mecanismo psicológico: el ideal excluye al otro y, al fracasar, busca culpables (e2-e3). El punto débil es e3: no todo el que tiene un ideal de felicidad termina buscando enemigos, y Zuleta generaliza desde casos extremos. Un defensor de los ideales diría que sin ellos no hay transformación social. Zuleta respondería que no critica los ideales, sino los que excluyen la dificultad. La pieza sobrante confunde aceptar la dificultad con buscar el sufrimiento."},
   { titulo:"Contra la guerra (Sobre la guerra)",
     consigna:"Reconstruí el argumento de Zuleta sobre por qué es difícil combatir la guerra. Una pieza propone combatirla solo con la denuncia de sus horrores, que es lo que Zuleta considera insuficiente: dejala afuera.",
     piezas:[
       {id:"g1", texto:"El conflicto y la hostilidad son tan constitutivos del vínculo social como la cooperación y la interdependencia.", tipo:"premisa"},
       {id:"g2", texto:"La guerra no es solo horror: también es una fiesta, porque une a un grupo contra un enemigo y suprime las dudas y las ambivalencias.", tipo:"premisa"},
       {id:"g3", texto:"Por eso, mostrar los horrores de la guerra no basta para que una sociedad renuncie a ella.", tipo:"premisa"},
       {id:"g4", texto:"Por lo tanto, solo un pueblo maduro para el conflicto, capaz de vivirlo sin necesitar un enemigo absoluto, es un pueblo maduro para la paz.", tipo:"conclusion"},
       {id:"gx", texto:"Por lo tanto, basta con educar sobre los horrores de la guerra para que la gente la rechace.", tipo:"distractor"}
     ],
     ordenCorrecto:["g1","g2","g3","g4"],
     explicacion:"El argumento parte de una tesis sobre la sociedad (g1) y una sobre la guerra (g2), y concluye que la paz exige un cambio en la manera de vivir el conflicto (g4). El punto débil es g2: la idea de la guerra como fiesta describe bien la experiencia de algunos, pero no de las víctimas, para quienes la guerra no tiene nada de festivo. Zuleta habla sobre todo de quienes la hacen y la apoyan. La pieza sobrante es la estrategia que el argumento muestra como insuficiente."}
 ],
 dilemas:[
   { titulo:"La asamblea de padres",
     intro:"Zuleta sostuvo que la paz no es la ausencia de conflicto, sino la capacidad de vivirlo sin destruir al otro, y que la idealización de los propios y la satanización de los ajenos es la raíz de la violencia. Este caso lleva esas ideas a un colegio del Tolima, después del acuerdo de paz.",
     pasos:[
       { id:"p1", situacion:"Sos rectora de un colegio público en un municipio del Tolima. Este año llegan cinco estudiantes cuyos padres son firmantes del acuerdo de paz, en proceso de reincorporación. En la asamblea de padres, varios se oponen: dicen que sus hijos no deberían estudiar «con hijos de guerrilleros», y algunos son víctimas del conflicto. ¿Cómo empezás?", opciones:[
         {texto:"Les recuerdo que la ley garantiza el derecho a la educación y que la decisión no está en discusión.", consecuencia:"Tenés razón en lo legal, y los derechos de esos niños no se negocian. Pero cerrar la conversación así deja intacto el conflicto, y Zuleta diría que un conflicto reprimido no desaparece: vuelve.", va:"p2"},
         {texto:"Abro el espacio para que los padres expresen sus miedos y su dolor, antes de hablar de la decisión.", consecuencia:"Reconociste que el conflicto es real y que tiene razones, sobre todo en las víctimas. Es el primer paso que Zuleta pediría: no negar la dificultad, sino darle una forma para expresarse.", va:"p2"},
         {texto:"Les digo que los niños no tienen la culpa de lo que hicieron sus padres.", consecuencia:"Es verdad, y es un argumento importante. Pero puede sonar a que la rabia de los padres víctimas no tiene lugar. Zuleta diría que hay que sostener las dos cosas: el derecho de los niños y la legitimidad del dolor.", va:"p2"} ]},
       { id:"p2", situacion:"Una madre, víctima de desplazamiento por la guerrilla, dice llorando: «Esa gente nos quitó todo. ¿Ahora tengo que aceptar que sus hijos se sienten al lado de los míos?». Otro padre responde: «Usted es una resentida. La paz es olvidar». ¿Qué hacés?", opciones:[
         {texto:"Le doy la razón al segundo padre: hay que mirar hacia adelante.", consecuencia:"Pedir olvido a las víctimas es una forma de negar el conflicto, y el insulto de «resentida» es una satanización. Zuleta diría que la paz no es olvidar, sino aprender a vivir con lo que pasó sin convertir al otro en enemigo absoluto, en ninguna de las dos direcciones.", va:"p3"},
         {texto:"Detengo el insulto y digo que el dolor de la madre es legítimo, y que también lo es el derecho de los niños a estudiar.", consecuencia:"Sostuviste la ambivalencia que Zuleta pedía: dos cosas verdaderas a la vez, sin que una anule a la otra. Es difícil, y es exactamente la dificultad que él elogiaba.", va:"p3"},
         {texto:"Propongo un espacio de encuentro, con apoyo de profesionales, entre familias víctimas y familias de firmantes, para quienes quieran participar.", consecuencia:"Pasaste del conflicto en la asamblea a una forma de tramitarlo. No obligás a nadie, y das un lugar para que el otro deje de ser una abstracción. Es la idea de Zuleta: el conflicto necesita formas, no supresión.", va:"p3"} ]},
       { id:"p3", situacion:"Seis meses después, un estudiante hijo de firmante y otro hijo de víctimas terminan trabajando juntos en un proyecto de ciencias. Un periodista te pregunta si el colegio «logró la reconciliación». ¿Qué le respondés?", opciones:[
         {texto:"«Sí, ya no hay conflicto en el colegio.»", consecuencia:"Es el ideal de felicidad que Zuleta criticaba: imaginar que el conflicto se acabó. Probablemente sigue, de otras formas, y negarlo puede hacer que vuelva con más fuerza.", va:null},
         {texto:"«No hablaría de reconciliación. Hablaría de que aprendimos a vivir con el conflicto sin que nadie quedara afuera.»", consecuencia:"Es la idea de paz de Zuleta: no la ausencia de conflicto, sino la capacidad de tramitarlo. Es una respuesta más modesta y más verdadera.", va:null},
         {texto:"«Fue un éxito gracias a que impusimos la ley desde el principio.»", consecuencia:"La ley fue necesaria, pero no suficiente. Zuleta diría que lo que permitió el cambio fue el trabajo con la dificultad, no solo su prohibición.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar la diferencia entre conflicto y guerra en el pensamiento de Zuleta.",
       "Reconocí el dolor de las víctimas como legítimo, sin usarlo para negar los derechos de otros.",
       "Identifiqué las idealizaciones y satanizaciones que aparecían en la asamblea.",
       "Busqué formas de tramitar el conflicto en lugar de suprimirlo o negarlo.",
       "Sostuve dos cosas verdaderas a la vez, sin que una anulara a la otra.",
       "Evité presentar la paz como el fin del conflicto o como el olvido.",
       "Formulé la objeción más fuerte: que pedirles a las víctimas que convivan con el conflicto puede ser injusto si no hay verdad, justicia y reparación."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.zuleta = { lecturas:[
 {titulo:"Elogio de la dificultad y «Sobre la guerra»", fuente:"Síntesis de trabajo sobre Elogio de la dificultad (1980) y «Sobre la guerra»; para la vida y la obra, Wikipedia en español", url:"https://es.wikipedia.org/wiki/Estanislao_Zuleta",
  extracto:`En 1980, la Universidad del Valle le otorgó a Estanislao Zuleta un doctorado honoris causa en psicología. Zuleta había dejado el colegio a los dieciséis años y se había formado leyendo por su cuenta. Para la ocasión escribió un discurso breve, que se convirtió en uno de los textos más leídos de la filosofía colombiana: Elogio de la dificultad.

Su punto de partida es una observación sobre nuestros deseos. Deseamos la facilidad: un amor en el que el otro adivine lo que queremos, sin conflictos; una sociedad reconciliada, donde todos piensen igual; un saber que no nos exija esfuerzo ni transformación. Zuleta llama a estas imágenes ideales de felicidad, y muestra su lado oscuro: como la realidad nunca se parece a ellos, buscamos a alguien a quien culpar, y lo convertimos en enemigo.

Frente a eso, Zuleta propone aceptar la dificultad. No se trata de buscar el sufrimiento, sino de reconocer que vivir con otros que son distintos, pensar por cuenta propia y amar a alguien real son tareas difíciles, y que esa dificultad es la condición de la libertad y del reconocimiento mutuo.

Años después, en «Sobre la guerra», lleva esta idea a la violencia colombiana. La guerra, sostiene, no es solo horror: también es una fiesta, porque une a un grupo contra un enemigo, suprime las dudas y simplifica el mundo. Por eso no basta con mostrar sus horrores para combatirla. Hay que reconocer que el conflicto y la hostilidad son parte del vínculo social, tanto como la cooperación, y aprender a vivirlos sin aniquilar al otro. Un pueblo maduro para la paz, concluye, es un pueblo maduro para el conflicto.`,
  comentario:"Fijate en cómo Zuleta une tres planos que solemos separar: el amor, la política y el conocimiento. En los tres, la misma estructura —desear la facilidad y culpar a otro cuando no llega— produce efectos parecidos. Leé el texto pensando en Colombia: fue escrito en los años ochenta, en medio de la violencia política, y sigue siendo una referencia en las discusiones sobre la paz."}
], preguntasLectura:[
 {q:"¿Qué critica Zuleta en el Elogio de la dificultad?", opciones:["El esfuerzo académico","Los ideales de felicidad que excluyen la dificultad y terminan buscando culpables","La religión","El amor"], r:"Los ideales de felicidad que excluyen la dificultad y terminan buscando culpables", why:"Desear un paraíso sin conflictos lleva a convertir en enemigo a quien lo perturba."},
 {q:"¿Por qué, según Zuleta, mostrar los horrores de la guerra no basta para combatirla?", opciones:["Porque la gente no los cree","Porque la guerra también es una fiesta: une contra un enemigo y simplifica el mundo","Porque los horrores son exagerados","Porque la guerra es inevitable"], r:"Porque la guerra también es una fiesta: une contra un enemigo y simplifica el mundo", why:"La guerra ofrece algo que la vida en paz no ofrece, y por eso hay quienes la desean."},
 {q:"¿Qué significa que un pueblo maduro para la paz es un pueblo maduro para el conflicto?", opciones:["Que la paz requiere eliminar todos los conflictos","Que la paz es la capacidad de vivir el conflicto sin aniquilar al otro","Que el conflicto armado es necesario","Que la paz es imposible"], r:"Que la paz es la capacidad de vivir el conflicto sin aniquilar al otro", why:"El conflicto es constitutivo de la vida social; lo que cambia es la manera de vivirlo."}
]};
