/* ============================================================
   Ficha: arendt  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"arendt", trad:"europea", nombre:"Hannah Arendt", fechas:"1906–1975 · Alemania/EE. UU.", escuela:"Teoría política / fenomenología", icon:"🕯️", profundizada:true,
 tesis:"La política no es un medio para administrar la vida ni para realizar una idea de la historia: es el espacio donde seres plurales aparecen unos ante otros, hablan y actúan juntos, y donde puede empezar algo nuevo. El totalitarismo fue el intento de destruir ese espacio y de volver superfluos a los seres humanos. Y el mal más extremo del siglo XX no necesitó monstruos: le bastó con personas que dejaron de pensar lo que hacían. Por eso pensar, juzgar y actuar con otros no son lujos de intelectuales, sino las últimas defensas de un mundo común.",
 obras:[
   {t:"Los orígenes del totalitarismo (1951)", d:"Su primera gran obra, escrita en el exilio estadounidense, en tres partes: antisemitismo, imperialismo y totalitarismo. No es una historia de causas que conducirían inevitablemente al nazismo y al estalinismo, sino de los elementos que cristalizaron en una forma de dominación nueva, que no tenía precedentes en las tiranías conocidas. Allí aparecen sus tesis más citadas: el totalitarismo no busca solo obediencia, sino transformar la naturaleza humana; su instrumento es la combinación de terror e ideología; su laboratorio son los campos de concentración, donde se ensaya que todo es posible; y su condición previa es la masa de personas desarraigadas y superfluas. El capítulo sobre el fin de los derechos del hombre, escrito por una apátrida, es de los textos más leídos de la filosofía política del siglo XX."},
   {t:"La condición humana (1958)", d:"Su obra filosófica más sistemática. Distingue tres actividades de la vida activa: la labor, que responde a las necesidades del cuerpo y se consume en el mismo acto de vivir; el trabajo, que fabrica un mundo de objetos duraderos; y la acción, que ocurre entre las personas sin mediación de cosas y es la única que corresponde a la pluralidad humana. La tesis crítica es que la modernidad invirtió la jerarquía: convirtió a la sociedad en un conjunto de trabajadores y consumidores, y dejó a la acción política sin lugar. El libro introduce la natalidad como categoría central: cada nacimiento es un comienzo, y la acción es la capacidad de comenzar algo que no estaba previsto."},
   {t:"Eichmann en Jerusalén. Un informe sobre la banalidad del mal (1963)", d:"Nació como una serie de crónicas para The New Yorker sobre el juicio a Adolf Eichmann, responsable de organizar la deportación de millones de judíos a los campos de exterminio. Arendt esperaba encontrar a un monstruo y encontró a un funcionario ambicioso, lleno de frases hechas, incapaz de ponerse en el lugar de otro. De ahí la expresión del subtítulo: el mal puede ser extremo sin ser profundo. El libro provocó una de las polémicas más duras de la posguerra, por esa tesis y por sus páginas sobre la cooperación de los consejos judíos con los nazis. Gershom Scholem, amigo de Arendt, le reprochó falta de amor por el pueblo judío; ella respondió que no amaba a ningún pueblo, sino a sus amigos."},
   {t:"Entre el pasado y el futuro (1961) y Verdad y política (1967)", d:"Colección de ensayos que Arendt llamó ejercicios de pensamiento político, sobre la autoridad, la tradición, la libertad, la educación y la cultura. Su ensayo sobre la crisis de la educación sostiene que la escuela debe ser conservadora para que los nuevos puedan renovar el mundo: si se les entrega un mundo ya interpretado, se les quita la posibilidad de comenzar. En Verdad y política, escrito después de la polémica sobre Eichmann, distingue la verdad racional de la verdad de hecho, mucho más frágil, y advierte que la mentira política organizada no solo engaña: destruye el suelo común sobre el que se puede discutir."},
   {t:"La vida del espíritu (póstuma, 1978)", d:"Su última obra, inconclusa, iba a tener tres partes: pensar, querer y juzgar. Murió en 1975 con la tercera apenas empezada; la hoja con el título «Juzgar» seguía en su máquina de escribir. El punto de partida es Eichmann: si el mal puede cometerse sin malas intenciones, ¿puede el pensamiento, esa actividad que no produce resultados, impedir que se haga el mal? Arendt vuelve a Sócrates, que pensaba dialogando consigo mismo, y a la Crítica del juicio de Kant, de donde toma la idea de un juicio que no aplica reglas, sino que piensa el caso particular poniéndose en el lugar de los otros."}
 ],
 conceptos:[
   {t:"Totalitarismo", d:"Para Arendt, no es una tiranía más cruel, sino una forma de dominación nueva. La tiranía clásica quiere obediencia y deja en paz la vida privada; el totalitarismo quiere dominarlo todo, incluida la espontaneidad de las personas, y para eso combina el terror, que destruye el espacio entre los seres humanos, con una ideología que pretende explicar toda la historia a partir de una sola idea: la lucha de razas o la lucha de clases. Sus víctimas no son castigadas por lo que hicieron, sino por lo que son. Los campos de concentración son el núcleo del sistema: el lugar donde se demuestra que se puede convertir a seres humanos en cosas intercambiables. La tesis ha sido discutida por historiadores que critican que ponga en el mismo concepto al nazismo y al estalinismo."},
   {t:"El derecho a tener derechos", d:"Arendt fue apátrida durante catorce años, y desde esa experiencia escribió una de sus tesis más duras. Los derechos humanos se proclamaron como inalienables, propios de todo ser humano por el solo hecho de serlo; pero los refugiados y apátridas del período de entreguerras, que eran solo seres humanos, sin Estado que los protegiera, descubrieron que no tenían ninguno. La pérdida decisiva no fue la de un derecho particular, sino la de un lugar en el mundo donde las opiniones de uno cuenten y sus acciones tengan efecto. A eso lo llama el derecho a tener derechos: el derecho a pertenecer a una comunidad política. La tesis sigue siendo central para pensar a los migrantes y desplazados de hoy."},
   {t:"Labor, trabajo y acción", d:"Son las tres actividades de la vida activa en La condición humana. La labor responde a la necesidad biológica: comer, limpiar, reproducir la vida; sus productos se consumen y hay que volver a empezar. El trabajo fabrica cosas que duran —una mesa, una casa, un libro— y así construye un mundo más estable que la vida individual. La acción ocurre entre personas, sin mediación de cosas, por medio de la palabra y del gesto; no fabrica nada, pero revela quién es cada uno y puede iniciar procesos imprevisibles. La crítica de Arendt a la modernidad es que lo convirtió todo en labor: una sociedad de trabajadores y consumidores, donde la política se vuelve administración de necesidades."},
   {t:"Natalidad", d:"La filosofía occidental pensó al ser humano desde la mortalidad: somos los que vamos a morir. Arendt propone pensarlo desde el nacimiento: somos los que hemos llegado a un mundo que ya existía, y cada nacimiento introduce a alguien nuevo, que puede empezar algo que nadie esperaba. La acción política es la versión adulta de ese comienzo. Arendt cita a san Agustín: para que hubiera un comienzo fue creado el ser humano. La natalidad es el fundamento de su esperanza política, que no se apoya en ninguna ley de la historia, sino en la capacidad de los seres humanos de interrumpir lo que parecía inevitable."},
   {t:"Pluralidad y espacio público", d:"La pluralidad es la condición de la acción: no el Hombre en singular, sino seres humanos distintos que viven juntos. Cada persona es única, y solo se revela como quien es cuando aparece ante otros, hablando y actuando. El espacio público, o espacio de aparición, es el lugar donde eso ocurre: no un edificio, sino lo que surge cuando personas se reúnen para hablar y actuar en común. Arendt usa la imagen de una mesa: el mundo común relaciona y separa a la vez a quienes se sientan alrededor. Cuando el mundo común desaparece, las personas no quedan más unidas, sino aisladas o amontonadas en una masa."},
   {t:"La banalidad del mal", d:"Es la expresión más citada y más malentendida de Arendt. No dice que el mal sea trivial ni que los crímenes de Eichmann fueran pequeños: fueron monstruosos. Dice que su autor no lo era. No actuaba por odio fanático ni por una perversidad profunda, sino por ambición de carrera, obediencia y una incapacidad casi total de pensar desde el punto de vista de otro: hablaba con frases hechas, lenguaje burocrático y clichés. El mal, concluye, puede extenderse como un hongo sobre la superficie, sin raíces profundas. La tesis ha sido discutida: la historiadora Bettina Stangneth mostró, con documentos que Arendt no conoció, que Eichmann era un antisemita convencido que se presentó en el juicio como un burócrata."},
   {t:"Pensar y juzgar", d:"Después de Eichmann, Arendt se pregunta si pensar podría impedir el mal. Pensar, en su sentido, no es saber ni calcular: es el diálogo silencioso de uno consigo mismo, como hacía Sócrates, que prefería sufrir una injusticia antes que cometerla porque no quería vivir en compañía de alguien en desacuerdo consigo. Juzgar es otra cosa: pensar lo particular sin una regla general que lo resuelva de antemano. Para eso toma de Kant la mentalidad ampliada: juzgar poniéndose en el lugar de los otros, sin dejar de juzgar uno mismo. En las situaciones límite, dice, los que se negaron a colaborar no fueron los que tenían mejores principios, sino los que se preguntaron si podrían vivir consigo mismos después."},
   {t:"Poder y violencia", d:"En Sobre la violencia (1970) separa dos conceptos que la tradición confundía. El poder no es la capacidad de imponer la propia voluntad, sino la capacidad humana de actuar concertadamente: nunca pertenece a un individuo, sino a un grupo, y existe mientras el grupo se mantiene unido. La violencia es instrumental: necesita herramientas y puede ser ejercida por unos pocos contra muchos. Por eso no son grados de lo mismo, sino opuestos: donde uno domina por completo, el otro falta. La violencia puede destruir el poder, pero no puede crearlo. Un gobierno que necesita cada vez más violencia es un gobierno que está perdiendo el poder."},
   {t:"Promesa y perdón", d:"La acción tiene dos fragilidades: es irreversible, porque no se puede deshacer lo hecho, e imprevisible, porque no se sabe adónde llevará. Arendt encuentra en la misma acción los remedios. El perdón libera de las consecuencias de lo hecho, y permite que alguien no quede atado para siempre a un solo acto; la promesa crea islas de previsibilidad en el mar de la incertidumbre, y es la base de los pactos y de las constituciones. Atribuye el descubrimiento del perdón a Jesús de Nazaret, pero lo piensa en términos políticos. Y pone un límite: hay crímenes que no se pueden castigar ni perdonar, porque exceden la medida de lo humano."}
 ],
 conexion:"Fue alumna de <b>Heidegger</b> en Marburgo, y tuvieron una relación amorosa cuando ella tenía dieciocho años; él se afilió al partido nazi en 1933, el año en que ella huyó de Alemania, y aun así Arendt retomó el contacto con él después de la guerra, una decisión que todavía se discute. De Heidegger conserva la atención al mundo y a la aparición, pero rechaza su desconfianza hacia lo público. De Karl Jaspers, su director de tesis y amigo de toda la vida, toma la idea de comunicación. De <b>Kant</b> toma la teoría del juicio. Su crítica a la cooperación de los consejos judíos y su ensayo de 1959 sobre Little Rock, donde se opuso a que el gobierno federal impusiera la integración racial en las escuelas, le valieron críticas duras; Ralph Ellison le reprochó no entender la experiencia de los padres negros. Dialoga a la distancia con <b>Dussel</b>: los dos piensan desde los que quedaron fuera del mundo común, aunque Arendt no pensó el colonialismo con la misma radicalidad.",
 dialogo:{titulo:"«Solo cumplía órdenes»", lineas:[
   {quien:"Estudiante", texto:"Profesora, leí su libro sobre Eichmann y me indignó. Ese hombre organizó la deportación de millones de personas y usted dice que su mal era banal. ¿No lo está disculpando?"},
   {quien:"Arendt", texto:"Entiendo la indignación, porque fue la reacción de muchos. Pero leé el subtítulo con cuidado. Lo banal no son los crímenes: fueron los peores de la historia. Lo banal era él. Yo esperaba encontrar a un monstruo, a un Yago o a un Macbeth, y encontré a un funcionario que hablaba con clichés y que se ofendía si lo acusaban de odiar a los judíos."},
   {quien:"Estudiante", texto:"Pero si no era un monstruo, entonces no es tan culpable. Era una pieza del sistema."},
   {quien:"Arendt", texto:"Eso es exactamente lo que él quería que pensáramos, y lo que yo niego. La teoría del engranaje sirve para explicar cómo funciona una burocracia, no para juzgar a una persona. En el tribunal no se juzga a un sistema ni a una historia: se juzga a un hombre. Y cuando el engranaje dice «yo solo era un engranaje», el juez puede preguntarle: ¿y por qué aceptaste serlo?"},
   {quien:"Estudiante", texto:"Porque si se negaba, lo mataban. O lo reemplazaban por otro."},
   {quien:"Arendt", texto:"Lo segundo es casi siempre cierto, y no excusa a nadie: que otro lo hubiera hecho no cambia que lo hiciste vos. Lo primero, en el caso de Eichmann, es falso: los funcionarios que se negaron a participar rara vez pagaron con la vida. Y hubo quienes se negaron. En Dinamarca, casi toda la población judía fue salvada porque la gente, simplemente, no colaboró."},
   {quien:"Estudiante", texto:"Entonces, ¿qué tenían los que se negaron que no tenía Eichmann? ¿Mejores valores?"},
   {quien:"Arendt", texto:"Eso es lo que me sorprendió. No eran necesariamente los que tenían los principios más firmes: muchos de los respetables, con valores sólidos, cambiaron de valores de un día para otro cuando cambió el régimen. Los que se negaron se habían hecho una pregunta más simple: si hago esto, ¿podré seguir viviendo conmigo mismo? Para hacerse esa pregunta no hace falta ser un genio. Hace falta pensar."},
   {quien:"Estudiante", texto:"Pero hoy se sabe que Eichmann sí era un antisemita fanático. Leí que había documentos que usted no conoció."},
   {quien:"Arendt", texto:"Es una objeción seria, y la acepto como tal. Si Eichmann actuó en el juicio para parecer un burócrata, me engañó, como engañó a otros. Pero fijate lo que queda en pie aunque yo me haya equivocado sobre él: el exterminio necesitó a miles de funcionarios, maquinistas, contadores y secretarias que no eran fanáticos. Ellos son la banalidad del mal, aunque Eichmann no lo haya sido."},
   {quien:"Estudiante", texto:"¿Y por qué escribió también sobre los consejos judíos? Eso dolió mucho."},
   {quien:"Arendt", texto:"Porque era verdad, y porque me pareció que callarlo era una forma de no pensar. Sé que lo dije con un tono que hirió a muchos, y que hablé de víctimas con una dureza que quizá no correspondía. No me arrepiento de haberlo dicho, pero entiendo que haya quien no me lo perdone.", nota:"La polémica fue enorme y no está cerrada. Muchos sobrevivientes e historiadores consideran que Arendt juzgó con injusticia a quienes actuaron bajo una presión extrema, y que su tono irónico fue inapropiado. Otros sostienen que planteó una pregunta legítima. Vale la pena leer la carta de Gershom Scholem y la respuesta de Arendt."}
 ]},
 actividades:[
   {t:"El diálogo con uno mismo, por escrito", d:"Pensá en una situación real de tu vida —en el colegio, en el trabajo, en tu familia— en la que hiciste algo que no te parecía bien porque «todos lo hacían» o porque alguien con autoridad te lo pidió. Escribí primero qué pasó, con detalles concretos. Después escribí el diálogo que no tuviste en ese momento: una conversación entre vos y vos mismo, como la que Arendt atribuye a Sócrates, en la que una voz pregunta y otra responde. ¿Qué te habría preguntado la otra voz? ¿Podías seguir viviendo con lo que hiciste? Terminá con una reflexión de diez líneas: ¿qué te impidió pensar en ese momento: la prisa, el miedo, la costumbre o las frases hechas?"},
   {t:"Buscar clichés que impiden pensar", d:"Arendt notó que Eichmann hablaba con frases hechas, y que esas frases lo protegían de la realidad. Durante una semana, anotá frases hechas que escuches en tu entorno para justificar algo que hace daño: «así es el sistema», «yo solo cumplo», «eso no es problema mío», «siempre ha sido así». Elegí tres y analizalas por escrito: ¿qué ocultan?, ¿qué pregunta evitan?, ¿cómo sería decir lo mismo sin el cliché? Terminá con un párrafo sobre si el lenguaje burocrático de las instituciones que conocés —un colegio, una EPS, una oficina pública— funciona de la misma manera."},
   {t:"El derecho a tener derechos hoy", d:"Elegí un caso concreto de personas que hoy viven sin un lugar en una comunidad política: migrantes sin papeles, desplazados internos en Colombia, personas sin documento de identidad. Investigá con fuentes confiables —informes de organismos públicos o de derechos humanos— y escribí una página que responda: ¿qué derechos tienen en el papel?, ¿cuáles pueden ejercer en la práctica?, ¿qué les falta para que sus opiniones cuenten y sus acciones tengan efecto? Compará tu respuesta con la tesis de Arendt y decí si sigue siendo válida o si las instituciones posteriores, como el derecho internacional de los refugiados, la corrigieron."}
 ],
 cuestionario:[
   {q:"La expresión «banalidad del mal», ¿no relativiza la responsabilidad de los criminales?", p:"Es la objeción que más se le hizo, y conviene responderla con precisión. Arendt no dice que los crímenes fueran banales, sino que su autor no era un monstruo con motivaciones demoníacas. Y de esa tesis no saca una disminución de la responsabilidad, sino lo contrario: rechaza explícitamente la teoría del engranaje y defiende que se juzgue a cada persona por lo que hizo, aunque haya sido parte de una maquinaria. Su epílogo concluye que Eichmann merecía la horca porque apoyó y ejecutó una política que pretendía decidir quién podía habitar la Tierra. La banalidad agrava el problema en vez de aliviarlo: si el mal extremo no requiere monstruos, cualquier sociedad está expuesta a él. Lo que sí está en discusión es si Arendt acertó sobre Eichmann en particular: la investigación de Bettina Stangneth sobre sus escritos en Argentina muestra a un antisemita convencido que actuó en el juicio. Eso debilita el ejemplo, pero no necesariamente el concepto, que sigue siendo útil para pensar a los miles de colaboradores que no eran fanáticos."},
   {q:"¿Tiene sentido distinguir labor, trabajo y acción en una sociedad donde casi todo el mundo trabaja para vivir?", p:"La distinción no clasifica personas, sino actividades: la misma persona labora cuando cocina para comer, trabaja cuando construye una mesa y actúa cuando participa en una asamblea. La crítica de Arendt es que la modernidad tiende a reducirlo todo a la lógica de la labor —producir para consumir— y que eso vuelve irrelevante la acción: la política se convierte en administración de necesidades. Las objeciones son fuertes. Desde el marxismo y el feminismo se le reprocha que desprecie la labor, justamente la actividad históricamente asignada a mujeres y esclavos, y que su idealización de la polis griega olvide que ese espacio público dependía de que otros hicieran la labor. También se le critica que excluya de la política las cuestiones sociales, como la pobreza, cuando para muchos son el centro de la política. Una lectura más generosa diría que Arendt no pide abandonar esas cuestiones, sino evitar que la política se reduzca a ellas."},
   {q:"Arendt dice que el poder y la violencia son opuestos. ¿No es ingenuo, si todo Estado se apoya en última instancia en la fuerza?", p:"La tesis no niega que los Estados usen la fuerza, sino que su poder dependa de ella. Arendt observa que ningún gobierno, ni siquiera el más tiránico, se sostiene solo con violencia: necesita una base de apoyo, aunque sea la de la policía secreta. Cuando ese apoyo se retira, la violencia no alcanza, como lo mostraron los regímenes que cayeron sin que sus ejércitos fueran derrotados, porque los soldados se negaron a disparar. La objeción realista, de Weber en adelante, sostiene que el monopolio de la violencia legítima es lo que define al Estado. Arendt respondería que la palabra «legítima» ya supone algo que no es violencia: el reconocimiento de los otros. Para el caso colombiano la distinción es fértil: muestra por qué ningún grupo armado logró crear poder duradero a partir de la violencia, y por qué la paz no puede imponerse solo militarmente."},
   {q:"¿Qué valor tiene la tesis del derecho a tener derechos, si hoy existe el derecho internacional de los refugiados?", p:"El derecho internacional de los refugiados, posterior a la Segunda Guerra, puede leerse como una respuesta a lo que Arendt describió: un intento de garantizar protección a quienes no la reciben de su Estado. Pero su diagnóstico sigue vigente en dos sentidos. Primero, porque esa protección depende de que algún Estado acepte cumplirla, y los campos de refugiados, las fronteras cerradas y las personas sin documento muestran que muchos siguen sin un lugar donde sus opiniones cuenten. Segundo, porque Arendt no hablaba solo de protección física, sino de pertenencia política: un refugiado puede estar a salvo y seguir sin poder participar en las decisiones que lo afectan. La crítica a Arendt señala que su solución parece depender del Estado nacional, cuya crisis ella misma describió. La pregunta queda abierta: ¿qué comunidad política podría garantizar el derecho a tener derechos de todos?"},
   {q:"¿Es coherente que Arendt haya defendido la pluralidad y la acción común y, al mismo tiempo, se haya opuesto a la integración escolar forzada en Little Rock?", p:"Es una de las tensiones más discutidas de su obra. En 1959 sostuvo que el gobierno federal no debía imponer la integración en las escuelas, porque eso arrastraba a los niños a una lucha política que correspondía a los adultos, y porque distinguía entre la esfera política, donde debe regir la igualdad, y la esfera social, donde, según ella, la discriminación era inevitable. Ralph Ellison le respondió que no entendía la experiencia de los padres negros, que sabían que sus hijos iban a enfrentar ese conflicto de todos modos y que preferían que lo enfrentaran con la ley de su lado. Arendt reconoció después, en una carta, que Ellison tenía razón en algo que ella no había visto. El caso muestra los límites de su separación entre lo social y lo político, y la dificultad de juzgar una experiencia ajena desde afuera, que es justamente lo que su propia teoría del juicio pedía evitar."}
 ],
 cadena:{ titulo:"¿Era Eichmann un monstruo?", intro:"Un razonamiento en ramas sobre la tesis de Eichmann en Jerusalén (1963). Las ramas recorren la teoría del engranaje, la relación entre pensar y hacer el mal, y la objeción histórica más fuerte contra Arendt.", inicio:"n1", nodos:{
   n1:{ pregunta:"Eichmann organizó la deportación de millones de personas hacia la muerte. En el juicio parecía un funcionario mediocre, que hablaba con clichés y decía haber cumplido órdenes. ¿Cómo explicar que alguien así haya cometido crímenes de esa magnitud?", opciones:[
     {texto:"Era un monstruo que actuaba: detrás de la apariencia de burócrata había un fanático.", va:"n2a"},
     {texto:"Era una pieza de una maquinaria: cualquiera en su lugar habría hecho lo mismo.", va:"n2b"} ]},
   n2a:{ pregunta:"La historiadora Bettina Stangneth mostró en 2011, con escritos de Eichmann en Argentina que Arendt no conoció, que era un antisemita convencido. ¿Qué queda entonces de la «banalidad del mal»?", opciones:[
     {texto:"Nada: si Eichmann era un fanático, la tesis de Arendt era falsa.", final:{tipo:"revisar", texto:"La objeción derriba el ejemplo, pero no necesariamente el concepto. El exterminio necesitó, además de los fanáticos, a miles de funcionarios, maquinistas, contadores y secretarias que no lo eran. Esas personas, que hicieron posible el crimen sin odio especial y sin pensar en lo que hacían, siguen siendo el problema que Arendt nombró. Volvé un paso y probá otra respuesta."}},
     {texto:"El ejemplo falla, pero el concepto sirve para los miles de colaboradores que no eran fanáticos.", va:"n3a"} ]},
   n3a:{ pregunta:"Si el mal puede ser cometido por personas que no son fanáticas, ¿qué les faltó a esas personas?", opciones:[
     {texto:"Pensar: preguntarse, en el diálogo consigo mismas, si podrían seguir viviendo con lo que hacían.", final:{tipo:"bien", texto:"Es la respuesta de Arendt en La vida del espíritu. No dice que pensar garantice actuar bien, sino que la ausencia de pensamiento —el refugio en clichés, reglas y órdenes— deja a la persona disponible para cualquier cosa. La objeción es que muchos criminales pensaban mucho, y que la inteligencia no protegió a nadie. Arendt respondería que pensar, en su sentido, no es inteligencia, sino el hábito de examinarse, que cualquiera puede tener."}},
     {texto:"Mejores principios morales, que les habrían dicho claramente qué estaba mal.", final:{tipo:"bien", texto:"Es la respuesta intuitiva, y Arendt la discute con un dato inquietante: muchas personas respetables, con valores firmes, cambiaron de valores de un día para otro cuando cambió el régimen. Los principios funcionan como reglas, y las reglas se pueden reemplazar. Lo que resistió no fue tener buenas reglas, sino la capacidad de juzgar el caso sin ellas. Tu respuesta no es falsa, pero Arendt sospecharía de ella."}} ]},
   n2b:{ pregunta:"Eichmann se defendió diciendo que era un engranaje: si no lo hacía él, lo habría hecho otro. ¿Qué responde Arendt?", opciones:[
     {texto:"Que la teoría del engranaje explica cómo funciona una burocracia, pero no sirve para juzgar a una persona: en el tribunal no se juzga a un sistema.", va:"n3b"},
     {texto:"Que tiene razón: si el sistema era culpable, no tiene sentido castigar a las piezas.", final:{tipo:"revisar", texto:"Es justamente lo que Arendt rechaza. Para ella, la pregunta del tribunal no es si el sistema era criminal, sino si este hombre hizo lo que se le imputa. Y que otro lo hubiera hecho no cambia que lo hizo él. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Pero bajo una dictadura, negarse podía costar caro. ¿Se le puede exigir a alguien que no obedezca?", opciones:[
     {texto:"Sí: Arendt muestra que muchos de los que se negaron no pagaron con la vida, y que en Dinamarca casi toda la población judía se salvó porque la gente no colaboró.", final:{tipo:"bien", texto:"Es su argumento: la obediencia no es una fuerza natural irresistible. En «Responsabilidad personal bajo una dictadura» agrega que, en política, obedecer es apoyar: cuando un adulto obedece, presta su apoyo a la organización que le ordena. El costo de negarse varía, y Arendt no le pide heroísmo a nadie, pero sí que no se confunda el riesgo con la imposibilidad."}},
     {texto:"Depende del costo: no se le puede exigir a nadie que arriesgue su vida o la de su familia.", final:{tipo:"bien", texto:"Es una objeción razonable, y Arendt no la descarta: no le pide a nadie ser un mártir. Pero distingue: arriesgar la vida es una cosa; perder el puesto, la carrera o el respeto de los colegas, otra. La mayoría de los colaboradores no estaban en el primer caso. Tu respuesta te obliga a precisar, en cada caso, cuál era el costo real de negarse."}} ]}
 }},
 reconstruccion:[
   { titulo:"El derecho a tener derechos (Los orígenes del totalitarismo)",
     consigna:"Reconstruí el argumento de Arendt sobre los derechos humanos y los apátridas. Una pieza saca una conclusión que Arendt no sostiene: dejala afuera y ordená el resto.",
     piezas:[
       {id:"d1", texto:"Los derechos humanos se proclamaron como inalienables: propios de todo ser humano por el solo hecho de serlo, independientes de cualquier gobierno.", tipo:"premisa"},
       {id:"d2", texto:"Los refugiados y apátridas de entreguerras eran exactamente eso: solo seres humanos, sin un Estado que los reconociera.", tipo:"premisa"},
       {id:"d3", texto:"Sin embargo, fueron justamente ellos los que se quedaron sin ningún derecho efectivo: nadie estaba obligado a protegerlos.", tipo:"premisa"},
       {id:"d4", texto:"Lo que perdieron no fue un derecho particular, sino un lugar en el mundo donde sus opiniones contaran y sus acciones tuvieran efecto.", tipo:"premisa"},
       {id:"d5", texto:"Por lo tanto, el derecho fundamental es el derecho a tener derechos: el derecho a pertenecer a una comunidad política organizada.", tipo:"conclusion"},
       {id:"dx", texto:"Por lo tanto, los derechos humanos no existen y son solo una ficción jurídica.", tipo:"distractor"}
     ],
     ordenCorrecto:["d1","d2","d3","d4","d5"],
     explicacion:"El argumento usa una paradoja: los que más debían tener derechos humanos, porque eran solo humanos, fueron los que no tuvieron ninguno (d1-d3). La salida no es negar los derechos, sino desplazarlos: el derecho que importa es el de pertenecer (d4-d5). El punto débil es que la conclusión parece depender del Estado nacional, cuya crisis Arendt misma describió: ¿quién garantiza el derecho a pertenecer a quien ningún Estado acepta? La pieza sobrante es el escepticismo radical que Arendt no sostiene: ella critica una manera de fundar los derechos, no su valor."},
   { titulo:"Poder y violencia (Sobre la violencia, 1970)",
     consigna:"Reconstruí el argumento con que Arendt separa el poder de la violencia. Una pieza es la definición tradicional que Arendt discute: dejala afuera.",
     piezas:[
       {id:"p1", texto:"El poder es la capacidad humana de actuar concertadamente: nunca pertenece a un individuo, sino a un grupo, y existe mientras el grupo se mantiene unido.", tipo:"premisa"},
       {id:"p2", texto:"La violencia es instrumental: necesita herramientas, y unos pocos con armas pueden ejercerla contra muchos.", tipo:"premisa"},
       {id:"p3", texto:"Ningún gobierno se sostiene solo con violencia: incluso el más tiránico necesita una base que lo apoye.", tipo:"premisa"},
       {id:"p4", texto:"Cuando un gobierno pierde su apoyo, la violencia puede destruir lo que queda, pero no puede crear un poder nuevo.", tipo:"premisa"},
       {id:"p5", texto:"Por lo tanto, poder y violencia no son grados de lo mismo, sino opuestos: donde uno domina por completo, el otro falta.", tipo:"conclusion"},
       {id:"px", texto:"El poder es la capacidad de imponer la propia voluntad a otros, incluso contra su resistencia.", tipo:"distractor"}
     ],
     ordenCorrecto:["p1","p2","p3","p4","p5"],
     explicacion:"Arendt redefine el poder (p1) para separarlo de la violencia (p2) y muestra, con la experiencia histórica, que la fuerza sola no sostiene ni crea gobiernos (p3-p4). El punto débil es la definición de p1, que no es la del uso común ni la de la tradición: si se acepta la definición clásica —la de Weber, que es la pieza sobrante—, el argumento pierde su fuerza. Arendt no prueba que su definición sea la verdadera; muestra que permite ver algo que la otra oculta: por qué los regímenes caen cuando la gente deja de cooperar."}
 ],
 dilemas:[
   { titulo:"Las autorizaciones",
     intro:"Arendt sostuvo que el mal extremo no necesita monstruos: le basta con personas que dejan de pensar lo que hacen y se refugian en reglas, órdenes y frases hechas. Este caso no compara una oficina con un campo de exterminio, que no son comparables; pregunta cómo funciona, a escala cotidiana, la ausencia de pensamiento dentro de una institución.",
     pasos:[
       { id:"p1", situacion:"Trabajás en el área de autorizaciones de una EPS en Ibagué. Tu jefa te pide que, durante el próximo mes, rechaces por defecto ciertas solicitudes de procedimientos costosos, «porque hay que cuidar el presupuesto», aunque cumplan los requisitos. Sabés que muchos pacientes terminarán presentando tutelas, y que algunos no podrán esperar. ¿Qué hacés?", opciones:[
         {texto:"Cumplo la instrucción: no soy yo quien decide la política de la empresa.", consecuencia:"Es la teoría del engranaje: la responsabilidad está arriba, yo solo ejecuto. Arendt la discute de frente: obedecer, en un adulto, es apoyar. Si cada uno piensa que la decisión es de otro, nadie la toma y todos la ejecutan.", va:"p2"},
         {texto:"Pido la instrucción por escrito, con la justificación técnica y legal.", consecuencia:"No te negás, pero te negás a actuar sin pensar. Pedir por escrito obliga a la institución a decir en voz alta lo que hace, y a vos a leerlo. Es una forma modesta de romper el lenguaje de frases hechas.", va:"p2"},
         {texto:"Me niego a rechazar solicitudes que cumplen los requisitos.", consecuencia:"Es la negativa directa. Arendt no exige heroísmo, pero sí que no se confunda el costo de negarse con la imposibilidad de hacerlo. El costo aquí es real —tu puesto, tu relación con la jefa—, pero no es la vida.", va:"p2"} ]},
       { id:"p2", situacion:"Una compañera te dice: «No te compliqués. Si no lo hacés vos, lo hace otro, y te quedás sin trabajo por nada». ¿Qué le respondés?", opciones:[
         {texto:"«Tiene razón: no cambio nada negándome.»", consecuencia:"Es el argumento del reemplazo, que Eichmann también usó. Arendt responde que puede ser cierto y no excusa a nadie: que otro lo hubiera hecho no cambia que lo hiciste vos. Además, si todos razonan así, el reemplazo siempre aparece.", va:"p3"},
         {texto:"«Puede que lo haga otro. Pero no voy a poder vivir conmigo misma si lo hago yo.»", consecuencia:"Es la pregunta socrática que Arendt encontró en los que se negaron: no un principio abstracto, sino la imposibilidad de convivir con uno mismo después de hacer algo. No resuelve el problema de la empresa, pero decide lo que hacés vos.", va:"p3"},
         {texto:"«Busquemos a otros que piensen igual y hablemos juntos con la gerencia.»", consecuencia:"Pasaste de la conciencia individual al poder en el sentido de Arendt: la capacidad de actuar concertadamente. Lo que una persona sola no puede, un grupo sí puede, y una gerencia no se sostiene si sus empleados dejan de cooperar.", va:"p3"} ]},
       { id:"p3", situacion:"Meses después, un periodista investiga la práctica y te pregunta por qué los empleados la aplicaron. ¿Qué le respondés?", opciones:[
         {texto:"«Seguíamos instrucciones. El problema era de arriba.»", consecuencia:"Es cierto en parte, y Arendt no negaría que la responsabilidad mayor es de quien diseñó la política. Pero lo que el periodista escuchó es el cliché que Arendt analizó: una frase que protege de pensar en lo que uno hizo.", va:null},
         {texto:"«Nadie se preguntó qué les pasaba a los pacientes. Usábamos la palabra «presupuesto» para no ver a nadie.»", consecuencia:"Nombraste el mecanismo que Arendt describió: el lenguaje burocrático como manera de no ponerse en el lugar de otros. Es la banalidad del mal en una escala pequeña, que no necesitó a nadie malvado.", va:null},
         {texto:"«No me corresponde hablar de eso.»", consecuencia:"Puede ser una precaución legal. Pero si nadie habla, la práctica se vuelve invisible, y Arendt insistía en que la verdad de hecho, la más frágil, solo sobrevive si alguien la sostiene en público.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar qué significa la banalidad del mal sin confundirla con que el mal sea pequeño o trivial.",
       "Reconocí en mis respuestas la teoría del engranaje y el argumento del reemplazo, y puedo explicar por qué Arendt los rechaza.",
       "Distinguí entre el costo real de negarme y la imposibilidad de hacerlo.",
       "Pensé el caso poniéndome en el lugar de los pacientes, como pide el juicio en el sentido de Arendt.",
       "Consideré la acción con otros —el poder como acción concertada— y no solo la conciencia individual.",
       "Identifiqué las frases hechas que me ayudaban a no pensar.",
       "Formulé la objeción más fuerte: que comparar una oficina con los crímenes que estudió Arendt puede banalizar esos crímenes."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.arendt = { lecturas:[
 {titulo:"Eichmann en Jerusalén: la banalidad del mal", fuente:"Síntesis de trabajo sobre Eichmann en Jerusalén (1963) y «El pensar y las reflexiones morales» (1971); para la vida y la obra, Wikipedia en español", url:"https://es.wikipedia.org/wiki/Hannah_Arendt",
  extracto:`En 1961, Hannah Arendt viajó a Jerusalén para cubrir el juicio a Adolf Eichmann para la revista The New Yorker. Eichmann había sido el encargado de organizar el transporte de millones de judíos hacia los guetos y los campos de exterminio. Arendt, que había huido de Alemania en 1933 y había pasado catorce años como apátrida, esperaba encontrarse con un monstruo.

Lo que encontró fue otra cosa. Eichmann no parecía movido por un odio fanático ni por una perversidad profunda. Era un funcionario ambicioso, preocupado por su carrera, que hablaba con frases hechas y con el lenguaje oficial del régimen, y que mostraba una incapacidad notable para ver las cosas desde el punto de vista de otro. De ahí el subtítulo del libro: un informe sobre la banalidad del mal.

La expresión no quiere decir que los crímenes fueran pequeños. Quiere decir que el mal extremo no necesitó una maldad extrema en quien lo ejecutaba. En una carta posterior a Gershom Scholem, Arendt escribe que el mal nunca es radical, sino solo extremo, y que no tiene profundidad: puede extenderse sobre el mundo entero precisamente porque se propaga como un hongo en la superficie.

Arendt rechaza la defensa del engranaje. En el tribunal, dice, no se juzga a un sistema ni a una tendencia histórica, sino a una persona; y cuando el acusado responde que era solo una pieza, el juez puede preguntarle por qué aceptó serlo. Su epílogo concluye que Eichmann merecía la pena de muerte.

Años después, en «El pensar y las reflexiones morales», vuelve a la pregunta que el juicio le dejó: ¿podría la actividad de pensar —el diálogo silencioso de uno consigo mismo, como el de Sócrates— condicionar a las personas contra el mal? No propone una respuesta cerrada. Pero observa que quienes se negaron a colaborar con el régimen no fueron necesariamente los que tenían los principios más firmes, sino los que se preguntaron si podrían seguir viviendo consigo mismos después de actuar.`,
  comentario:"Fijate en que la tesis tiene dos partes que conviene separar: una descripción de Eichmann, que la investigación histórica posterior ha discutido, y un concepto —el mal sin profundidad— que puede valer aunque la descripción falle. Leé también qué no dice: Arendt no excusa a Eichmann, al contrario, rechaza la teoría del engranaje. El libro desató una polémica muy dura, sobre todo por sus páginas sobre los consejos judíos; no la saltees."}
], preguntasLectura:[
 {q:"¿Qué quiere decir Arendt con «banalidad del mal»?", opciones:["Que los crímenes nazis fueron menos graves de lo que se dice","Que el mal extremo no necesitó una maldad extrema ni profunda en quien lo ejecutaba","Que Eichmann no era responsable de lo que hizo","Que todo el mundo es igualmente culpable"], r:"Que el mal extremo no necesitó una maldad extrema ni profunda en quien lo ejecutaba", why:"Lo banal no son los crímenes, sino el criminal: un funcionario sin motivaciones demoníacas."},
 {q:"¿Qué responde Arendt a la defensa del «engranaje»?", opciones:["Que es correcta, porque el sistema era el verdadero culpable","Que en el tribunal se juzga a una persona, y que se le puede preguntar por qué aceptó ser una pieza","Que los engranajes deben ser perdonados","Que solo los jefes son responsables"], r:"Que en el tribunal se juzga a una persona, y que se le puede preguntar por qué aceptó ser una pieza", why:"Arendt rechaza que la pertenencia a una maquinaria disuelva la responsabilidad personal."},
 {q:"Según «El pensar y las reflexiones morales», ¿qué tenían en común quienes se negaron a colaborar?", opciones:["Tenían siempre los principios más firmes","Eran los más inteligentes","Se preguntaron si podrían seguir viviendo consigo mismos después de actuar","Pertenecían a la resistencia armada"], r:"Se preguntaron si podrían seguir viviendo consigo mismos después de actuar", why:"Es el diálogo de uno consigo mismo, a la manera de Sócrates, que Arendt asocia con pensar."}
]};
