/* ============================================================
   Ficha: aristoteles  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"aristoteles", trad:"europea", nombre:"Aristóteles", fechas:"384–322 a.C. · Estagira/Atenas", escuela:"Realismo, lógica, ética de la virtud", icon:"🦉", profundizada:true,
 tesis:"La forma no existe separada de la materia, sino en las cosas mismas (hilemorfismo). La felicidad (eudaimonía) es actividad del alma conforme a la virtud, alcanzada por hábito y término medio, no por conocimiento puro.",
 obras:[
   {t:"Ética a Nicómaco", d:"Diez libros de apuntes de clase que parten de una pregunta práctica —¿cuál es el fin último de la acción humana?— y responden con la eudaimonía, el florecimiento propio del ser humano. Sostiene que la virtud no se enseña como un teorema sino que se adquiere por hábito, como un oficio, y que consiste en un término medio determinado por la prudencia; cierra discutiendo la amistad y la vida contemplativa como cumbre del florecimiento."},
   {t:"Metafísica", d:"Colección de tratados que Aristóteles llamó 'filosofía primera' y que estudia el ser en cuanto ser, es decir, no un tipo particular de cosas sino lo que significa ser algo. Allí formula la doctrina de las cuatro causas, la distinción entre acto y potencia, la crítica frontal a las Formas separadas de Platón y el argumento del primer motor inmóvil que piensa el pensamiento."},
   {t:"Física", d:"Tratado sobre la naturaleza (physis) entendida como principio interno de movimiento y reposo: lo natural es aquello que tiene en sí mismo la fuente de su propio cambio, a diferencia de lo artificial. Analiza cuatro tipos de cambio, define el tiempo como 'número del movimiento según el antes y el después' y explica el movimiento como paso de la potencia al acto."},
   {t:"Política", d:"Estudio comparativo de constituciones reales que arranca de una tesis antropológica: el ser humano es zoon politikon, un viviente que solo alcanza su forma plena dentro de la pólis. Clasifica los regímenes en rectos y desviados según gobiernen para el bien común o para el propio, y defiende una politeia mixta apoyada en una clase media amplia como la forma más estable."},
   {t:"Órganon (tratados de lógica)", d:"Conjunto de seis escritos —entre ellos las Categorías y los Analíticos Primeros y Segundos— que constituyen el primer sistema formal de la historia: no una doctrina sobre el mundo, sino la herramienta (órganon) para razonar sobre cualquier cosa. Allí nace el silogismo, la distinción entre deducción e inducción y la exigencia de que toda ciencia parta de principios indemostrables."},
   {t:"Acerca del alma (De anima)", d:"Aplica el hilemorfismo al viviente: el alma no es un huésped atrapado en un cuerpo, sino la forma o el acto primero de un cuerpo organizado que tiene la vida en potencia. Distingue funciones vegetativa, sensitiva e intelectiva, y explica la percepción como la recepción de la forma sensible sin su materia, imagen que atravesará toda la escolástica."},
   {t:"Poética", d:"Tratado sobre la tragedia que define el arte como mímesis —imitación de acciones, no copia de cosas— y sostiene que la poesía es más filosófica que la historia porque muestra lo que puede ocurrir según lo verosímil, no solo lo que ocurrió. Introduce las nociones de trama, peripecia, reconocimiento y catarsis de las emociones de piedad y temor."}
 ],
 conceptos:[
   {t:"Hilemorfismo", d:"Toda sustancia concreta es la unión inseparable de una materia (aquello de lo que está hecha) y una forma (aquello que la hace ser lo que es). Contra Platón, la forma no habita un mundo aparte: la humanidad no está en un cielo de Formas, está en cada ser humano. Materia y forma no son dos piezas que se peguen, sino dos aspectos que solo el análisis distingue en una única cosa."},
   {t:"Acto y potencia", d:"Para explicar el cambio sin caer en la paradoja de Parménides —nada puede surgir de la nada— Aristóteles distingue lo que algo ya es (acto) de lo que puede llegar a ser (potencia). La semilla es árbol en potencia y semilla en acto; el cambio es el paso ordenado de una a otro. Con este par disuelve el problema del devenir que había empujado a Platón a postular un mundo inmutable aparte."},
   {t:"Las cuatro causas", d:"Explicar algo es responder cuatro preguntas distintas: de qué está hecho (causa material), qué estructura lo define (formal), qué lo produjo (eficiente) y para qué existe (final). Una estatua es bronce, es la figura de un atleta, la hizo un escultor y existe para honrar a alguien. La ciencia moderna conservó las dos primeras y la eficiente, pero expulsó la causa final del mundo natural: ahí está el núcleo del debate sobre el teleologismo."},
   {t:"Eudaimonía", d:"No es un estado de ánimo agradable sino el florecimiento de una vida entera: la actividad del alma conforme a la virtud, sostenida a lo largo del tiempo, porque 'una golondrina no hace verano'. Se define por el argumento de la función: así como un buen flautista es el que toca bien, el bien humano está en ejercer bien lo específicamente humano, la vida racional. Por eso puede haber placer sin eudaimonía y esfuerzo con eudaimonía."},
   {t:"Término medio", d:"La virtud ética es un medio entre dos vicios, uno por exceso y otro por defecto: el valor entre la temeridad y la cobardía, la generosidad entre la prodigalidad y la avaricia. Pero Aristóteles advierte que no es una media aritmética sino un medio 'relativo a nosotros', distinto para cada persona y situación, y que hay acciones que no admiten medio alguno —el homicidio o el robo son malos sin más, no por exceso—. La lectura popular de 'todo con moderación' es justamente la que él descarta."},
   {t:"Hábito (héxis)", d:"Las virtudes no son innatas ni se transmiten por argumento: se adquieren repitiendo los actos correspondientes, igual que uno se hace constructor construyendo y citarista tocando la cítara. El carácter es un depósito de decisiones pasadas, lo que convierte a la educación temprana en un asunto decisivo y no accesorio. De aquí sale la respuesta aristotélica a Sócrates: conocer el bien no basta, hay que haberlo practicado hasta que sea una segunda naturaleza."},
   {t:"Phronesis (prudencia)", d:"Es la virtud intelectual que delibera bien sobre lo que conviene hacer aquí y ahora, en situaciones particulares que ninguna regla general cubre por completo. No es episteme —saber universal y demostrativo— ni téchne —saber producir objetos—, sino el juicio que identifica dónde está el término medio en este caso concreto. Sin ella las virtudes del carácter quedan ciegas; sin virtudes del carácter, la prudencia se degrada en mera astucia."},
   {t:"Silogismo", d:"Estructura de razonamiento en la que de dos premisas se sigue necesariamente una conclusión, en virtud únicamente de su forma y no de su contenido. Aristóteles fue el primero en usar letras como variables para mostrar que la validez es independiente del tema del que se hable, y clasificó las figuras y modos válidos con un rigor que quedó en pie hasta el siglo XIX. Su límite es que solo captura inferencias sujeto-predicado, lo que la lógica de relaciones moderna terminaría desbordando."},
   {t:"Zoon politikon", d:"El ser humano es por naturaleza un viviente de la pólis: no se asocia solo por conveniencia, como las abejas o los rebaños, sino porque posee lógos y puede discutir sobre lo justo y lo injusto. De ahí que la comunidad política sea anterior al individuo en el orden de la naturaleza, como el cuerpo es anterior a la mano separada. Quien vive fuera de la pólis, dice, 'o es una bestia o es un dios'."}
 ],
 conexion:"<b>Tomás de Aquino</b> retomará su lógica y metafísica para construir la escolástica cristiana casi dieciocho siglos después.",
 dialogo:{titulo:"La lección del citarista", lineas:[
   {quien:"Estudiante", texto:"Ya entendí perfectamente en qué consiste ser generoso. ¿No debería alcanzar con eso para serlo?"},
   {quien:"Aristóteles", texto:"Decime: ¿alguien que entendió perfectamente en qué consiste tocar la cítara ya es citarista?"},
   {quien:"Estudiante", texto:"Claro que no. Tendría que ponerse a tocar, y mal, durante mucho tiempo."},
   {quien:"Aristóteles", texto:"Entonces ya respondiste. Nos hacemos justos practicando la justicia y moderados practicando la moderación. La virtud no es una conclusión que se acepta: es una héxis, una disposición que se construye repitiendo actos."},
   {quien:"Estudiante", texto:"Pero si la regla es el término medio, dígame el número. ¿Cuánto hay que dar para ser generoso y no pródigo?"},
   {quien:"Aristóteles", texto:"No hay número. El medio es relativo a nosotros, no a la aritmética. A un atleta que entrena seis horas le corresponde una ración que a vos te enfermaría; y el coraje que se le pide a un médico en una epidemia no es el que se le pide a un soldado.", nota:"Este es el punto que la lectura popular de 'todo con moderación' pierde: el medio no es una fórmula, es una determinación situada."},
   {quien:"Estudiante", texto:"Si no hay regla fija, entonces cualquiera puede justificar lo que quiera diciendo que ese era su medio."},
   {quien:"Aristóteles", texto:"Por eso hace falta la phronesis, y por eso no todos juzgan igual de bien. El criterio es lo que decidiría el hombre prudente, el que ya deliberó muchas veces en situaciones parecidas y acertó. No es un algoritmo: es un juicio educado."},
   {quien:"Estudiante", texto:"Suena circular. El prudente es el que encuentra el medio y el medio es lo que encuentra el prudente."},
   {quien:"Aristóteles", texto:"Es circular si buscás una demostración. Pero la ética no es una ciencia demostrativa: 'no hay que exigir el mismo rigor en todos los razonamientos'. En materia de acciones hay que contentarse con mostrar la verdad de un modo grueso y esquemático."},
   {quien:"Estudiante", texto:"¿Y no había un medio también en el robo o en el homicidio? Alguna cantidad justa."},
   {quien:"Aristóteles", texto:"Ninguna. Esas acciones no son malas por exceso o por defecto: son malas sin más. Buscarles un término medio sería como buscar el modo correcto de cometer adulterio.", nota:"Aristóteles marca aquí un límite explícito a su propia doctrina, algo que se suele omitir al resumirla."},
   {quien:"Estudiante", texto:"Su maestro Platón diría que todo esto se resuelve contemplando la Forma del Bien."},
   {quien:"Aristóteles", texto:"Soy amigo de Platón, pero más amigo de la verdad. Aunque existiera un Bien separado y eterno, sería inalcanzable para la acción humana: ningún tejedor ni ningún carpintero mejoraría su oficio contemplándolo. El bien que buscamos es el bien realizable, y está en las cosas, no arriba de ellas."}
 ]},
 actividades:[
   {t:"Las cuatro causas de un objeto cotidiano", d:"Elegí un objeto que tengas a mano (una silla, un celular, un libro) y respondé por escrito las cuatro causas: material, formal, eficiente y final. Después repetí el ejercicio con algo natural —un árbol, un corazón, una tormenta— y discutí en un párrafo si la causa final sigue teniendo sentido en el segundo caso o si la ciencia moderna tuvo razón en expulsarla."},
   {t:"Mapa de términos medios", d:"Armá una tabla de cinco filas con el formato vicio por defecto / virtud / vicio por exceso, usando situaciones de tu propia vida escolar o laboral (por ejemplo: callarse siempre / decir lo necesario / no poder callarse). Al lado de cada fila anotá qué cambiaría el medio si la persona fuera otra, y marcá si alguna de tus filas es en realidad una acción que no admite término medio."},
   {t:"Carta de Aristóteles a Platón", d:"Escribí una carta breve de Aristóteles a su maestro explicándole por qué rechaza las Formas separadas, usando solo argumentos que estén en esta ficha: el hilemorfismo, el acto y la potencia y la objeción del bien realizable. Después escribí la respuesta de Platón en tres o cuatro líneas, defendiendo por qué sin Formas no se explica el conocimiento de lo universal."}
 ],
 cuestionario:[
   {q:"Aristóteles dice que nos volvemos virtuosos practicando la virtud, no solo entendiéndola. ¿Puede alguien ser sabio sobre la ética sin ser bueno?", p:"Aristóteles distinguiría saber teórico (episteme) de sabiduría práctica (phronesis): esta última requiere experiencia y carácter formado, no solo argumento. Se puede ser experto en teorías morales y mal deliberador, igual que se puede saber medicina de memoria y no saber curar a este paciente."},
   {q:"Si el término medio es 'relativo a nosotros' y no una cantidad fija, ¿en qué se diferencia de decir que cada uno haga lo que le parezca?", p:"En la phronesis y en el criterio del hombre prudente: el medio no lo fija el deseo del agente sino el juicio educado de quien deliberó bien muchas veces. Vale discutir si eso alcanza como criterio o si, como objetan sus críticos, la ética de la virtud termina apoyada en un consenso social sobre quién cuenta como prudente."},
   {q:"¿Tiene sentido preguntar 'para qué' existe algo natural —un ojo, una especie, un río— o esa pregunta solo se aplica a lo fabricado?", p:"Aristóteles sostiene que la naturaleza obra por un fin inmanente: el ojo es para ver aunque nadie lo haya diseñado. La ciencia moderna eliminó la causa final de la física, pero la biología sigue hablando de funciones, así que el debate está lejos de cerrado."},
   {q:"Si el ser humano es 'animal político' por naturaleza, ¿qué hacemos con quien elige vivir al margen de toda comunidad?", p:"Aristóteles diría que no es una opción neutral: fuera de la pólis no se desarrolla la capacidad de deliberar sobre lo justo, y por eso quien vive sin ciudad 'o es una bestia o es un dios'. Un lector moderno puede replicar que esto confunde un hecho estadístico con una naturaleza, y que las comunidades pueden ser también el lugar de la opresión."},
   {q:"¿Por qué el argumento de la función (ergon) no comete el error de deducir cómo debemos vivir a partir de cómo somos?", p:"Aristóteles no distingue hecho y valor como lo hará Hume: para él la forma de una cosa ya incluye su fin, así que describir plenamente al ser humano es describir en qué consiste su plenitud. Justamente ese supuesto es lo que la filosofía moderna le discute, y reconstruirlo es el mejor ejercicio crítico sobre este módulo."}
 ],
 cadena:{ titulo:"¿Cómo sé que esto es el término medio?", intro:"Un razonamiento en ramas a partir de los libros II y VI de la Ética a Nicómaco. Retoma la objeción que el estudiante deja abierta en el diálogo: si el medio es relativo a nosotros, ¿qué impide llamar «medio» a lo que uno ya quería hacer? Cada rama desemboca en una pieza distinta de la ética aristotélica.", inicio:"n1", nodos:{
   n1:{ pregunta:"Una amiga te pide tu opinión franca sobre la novela que escribió durante tres años. Te parece floja. Le decís: «tiene cosas muy buenas, pero todavía le falta trabajo». Aristóteles ubicaría esto en la virtud del trato, un medio entre el adulador, que solo quiere agradar, y el pendenciero, al que no le importa causar dolor (EN IV.6). ¿Cómo sabés que tu frase fue el medio y no simplemente lo que te resultaba cómodo decir?", opciones:[
     {texto:"Porque evité los dos extremos: no le mentí diciendo que era genial ni la destruí diciendo que era mala.", va:"n2a"},
     {texto:"No lo sé con seguridad: me doy cuenta de que elegí la frase que menos me incomodaba a mí.", va:"n2b"} ]},
   n2a:{ pregunta:"Evitar los extremos es un buen comienzo, pero Aristóteles advierte que el medio no está a igual distancia de ellos: el valor, por ejemplo, queda más cerca de la temeridad que de la cobardía (EN II.8). En tu caso, ¿cómo sabés hacia qué lado estaba el medio?", opciones:[
     {texto:"Por la situación concreta: si ella va a mandar el manuscrito a editoriales la semana que viene, lo que la protege es más franqueza, no menos.", va:"n3a"},
     {texto:"Por una regla general: ante la duda, siempre conviene inclinarse hacia la suavidad.", final:{tipo:"revisar", texto:"Aristóteles sí da un consejo para los casos difíciles, pero no es ese: apartarse del extremo más opuesto al medio y vigilar hacia dónde nos arrastra nuestra propia inclinación, como quien endereza una madera torcida doblándola al revés (EN II.9, 1109a-b). Es decir, no «siempre suavidad» sino «corregí tu sesgo». Si tu tendencia es evitar el conflicto, la regla de la suavidad te empuja justo hacia tu vicio. Una regla fija para todo caso es lo que, según él, la ética no puede dar. Volvé un paso y mirá la situación."}} ]},
   n3a:{ pregunta:"Miraste los particulares: quién es ella, qué va a hacer, qué está en juego. Eso es lo que hace la phronesis, que según Aristóteles se ocupa de lo último y particular, casi como una percepción (EN VI.8). Pero vuelve la objeción del diálogo: ¿no podrías haberte contado cualquier historia sobre «la situación» para justificar lo que igual ibas a decir?", opciones:[
     {texto:"Podría. Lo que distingue al prudente del que se autoengaña es que tiene los deseos bien formados: su carácter no le deforma la percepción.", final:{tipo:"bien", texto:"Es la tesis de EN VI.12-13: la virtud hace recto el fin y la prudencia lo que conduce a él, y ninguna funciona sin la otra. Aristóteles agrega un detalle decisivo: el placer y el dolor no corrompen cualquier juicio —no el de que los ángulos del triángulo suman dos rectos— sino el juicio sobre qué conviene hacer (VI.5, 1140b). Por eso no hay un procedimiento que, en manos de cualquiera, garantice el medio: la garantía está en quien percibe. El círculo que el estudiante denunciaba no es un descuido lógico; es la tesis de que la ética se aprende viviendo, no deduciendo."}},
     {texto:"No: para evitar el autoengaño hace falta justificar la decisión con un principio que cualquiera pueda aplicar y controlar.", va:"n4a"} ]},
   n4a:{ pregunta:"Buscás un principio público. Aristóteles no desprecia las reglas —hay leyes, hay máximas de la experiencia—, pero observa que la ley habla siempre en universal y que hay casos en que eso la hace fallar. Cuando una regla aplicada al pie de la letra produce una injusticia en un caso que el legislador no previó, ¿qué hace falta?", opciones:[
     {texto:"Corregir la regla preguntándose qué habría dicho el legislador si hubiera estado presente en este caso.", final:{tipo:"bien", texto:"Es la epieikeia, la equidad (EN V.10, 1137b): una corrección de la ley allí donde falla por su universalidad. Aristóteles la compara con la regla de plomo de los constructores de Lesbos, que se dobla para adaptarse a la forma de la piedra. Acabás de llegar, por el camino de las reglas, al mismo lugar que querías evitar: incluso quien aplica principios necesita un juicio que no es otro principio. Tu búsqueda de un control público no era mala —es la que después hará Kant—, pero en Aristóteles el último control es la mirada del prudente."}},
     {texto:"Aplicarla igual: una regla que admite excepciones deja de proteger a nadie.", final:{tipo:"revisar", texto:"Es una posición seria —la de muchos juristas y, a su manera, la de Kant—, pero no la de Aristóteles, y vale la pena ver por qué. Para él la exactitud que se exige debe ajustarse a la materia (EN I.3): pedirle a la ética la precisión de la matemática es tan equivocado como aceptar del matemático razonamientos meramente persuasivos. Además, una regla aplicada sin mirar el caso no elimina el juicio: solo lo desplaza al momento en que alguien decidió qué casos cubría. Volvé un paso y probá la otra salida."}} ]},
   n2b:{ pregunta:"Reconocerlo ya es más de lo que hace la mayoría, y es justo lo que Aristóteles recomienda: observar hacia dónde nos arrastra nuestra propia inclinación (EN II.9). Ahora hay que decidir qué hacer con ese dato. ¿Cuál es el paso siguiente?", opciones:[
     {texto:"Tirar hacia el lado contrario: si tiendo a suavizar, esta vez digo algo más directo aunque me cueste.", va:"n3b"},
     {texto:"Desconfiar de mi propio juicio y preguntarle a alguien de afuera qué haría.", va:"n3c"} ]},
   n3b:{ pregunta:"Es el método del carpintero con la madera torcida. Pero te surge una duda: si hacés esto cada vez, ¿estás siendo franco o solo aplicando una corrección mecánica a un defecto tuyo?", opciones:[
     {texto:"Por ahora es una corrección; pero si la repito, decir lo que corresponde se va a volver una disposición.", final:{tipo:"bien", texto:"Es la doctrina de la héxis (EN II.1-4): uno se hace justo haciendo actos justos. Aristóteles da incluso un signo para saber si ya llegaste: el placer o el dolor que acompaña al acto (II.3). Mientras decirle la verdad a tu amiga te cueste y tengas que forzarte, sos continente, no todavía virtuoso. La continencia (enkráteia) es buena, pero es la excelencia de quien sigue peleando consigo mismo; la virtud es cuando el acto correcto ya no se siente como una derrota."}},
     {texto:"Si es mecánica no vale nada moralmente: solo cuenta lo que sale de manera espontánea.", final:{tipo:"revisar", texto:"Así se pierde la mitad de la ética aristotélica. Nadie nace con el carácter hecho: las virtudes no se dan por naturaleza ni contra la naturaleza, sino que la naturaleza nos da la capacidad de recibirlas y el hábito las perfecciona (EN II.1). Negarle valor a la corrección deliberada es negárselo a toda educación. Lo que sí es cierto es que Aristóteles distingue al continente del virtuoso, pero el primero está en camino al segundo, no fuera del juego. Volvé y probá la otra respuesta."}} ]},
   n3c:{ pregunta:"Aristóteles aprobaría la consulta, pero te preguntaría a quién. No a cualquiera: el criterio del medio es lo que determinaría el hombre prudente (EN II.6, 1107a). ¿Cómo elegís a quién preguntar?", opciones:[
     {texto:"Busco a alguien que haya mostrado buen juicio en situaciones parecidas, aunque no sepa explicar del todo sus razones.", final:{tipo:"bien", texto:"Es casi literal EN VI.11 (1143b): hay que atender a las opiniones indemostradas de los experimentados, de los mayores y de los prudentes no menos que a las demostraciones, porque la experiencia les dio un ojo con el que ven correctamente. Tu camino muestra el costado social de la phronesis: el medio no se descubre en soledad sino dentro de una comunidad donde algunos juicios ya probaron lo que valen. La pregunta que le hacen sus críticos queda abierta: ¿quién decide quién cuenta como prudente?"}},
     {texto:"Le pregunto a varias personas: si la mayoría coincide en qué sería lo adecuado, ese es el medio.", final:{tipo:"revisar", texto:"Aristóteles respeta los éndoxa —las opiniones de todos, de la mayoría o de los sabios— como punto de partida de la investigación ética. Pero punto de partida no es criterio: la mayoría, dice en el libro I, identifica la felicidad con el placer y elige una vida propia del ganado (EN I.5). El medio no se vota. Volvé un paso: el criterio no es cuántos opinan, sino quién."}} ]}
 }},
 reconstruccion:[
   { titulo:"El argumento de la función (Ética a Nicómaco I.7, 1097b-1098a)",
     consigna:"Reconstruí el argumento con el que Aristóteles pasa de «qué hace el ser humano» a «en qué consiste su bien». Una pieza pertenece a otra discusión del mismo libro: dejala afuera y ordená el resto.",
     piezas:[
       {id:"a1", texto:"Para todo lo que tiene una función propia —el flautista, el escultor, cualquier artesano—, su bien y su «hacerlo bien» residen en esa función.", tipo:"premisa"},
       {id:"a2", texto:"Sería absurdo que el carpintero y el zapatero tuvieran una función y el ser humano, en cuanto ser humano, no tuviera ninguna, como si hubiera nacido ocioso.", tipo:"premisa"},
       {id:"a3", texto:"Esa función no puede ser nutrirse y crecer, que compartimos con las plantas, ni percibir, que compartimos con los animales: tiene que ser lo propio, la actividad del alma según la razón.", tipo:"premisa"},
       {id:"a4", texto:"Y la función de un buen X es la misma que la de un X, pero ejercida con excelencia: la del citarista es tocar la cítara, la del buen citarista es tocarla bien.", tipo:"premisa"},
       {id:"a5", texto:"Por lo tanto, el bien humano es actividad del alma conforme a la virtud —y si hay varias, conforme a la mejor y más completa—, y además en una vida entera.", tipo:"conclusion"},
       {id:"ax", texto:"Como la forma no existe separada de las cosas, no hay una Idea del Bien común a todo lo bueno que pueda servirnos de guía para actuar.", tipo:"distractor"}
     ],
     ordenCorrecto:["a1","a2","a3","a4","a5"],
     explicacion:"El argumento tiene tres movimientos: una tesis general sobre funciones y bondad (a1), la extensión al ser humano como tal (a2), la identificación de su función por eliminación de lo que compartimos con otros vivientes (a3), y el paso de la función a su ejercicio excelente (a4). La cláusula final, «en una vida entera», es la de la golondrina que no hace verano. La pieza sobrante pertenece a la crítica a la Idea platónica del Bien de EN I.6: es del mismo libro, pero discute otra cosa. Dos puntos débiles para discutir: primero, que a3 identifica lo bueno con lo distintivo, y hay rasgos exclusivamente humanos —la crueldad planificada, por ejemplo— que nadie llamaría nuestro bien; segundo, que a2 supone que el ser humano tiene una función como la tiene un oficio, que es justamente el supuesto teleológico que la filosofía moderna le discute."},
   { titulo:"El primer motor inmóvil (Metafísica XII.6-7; Física VIII)",
     consigna:"Reconstruí el argumento que lleva de la eternidad del movimiento a un motor que mueve sin moverse. Una pieza contradice la conclusión aunque use vocabulario aristotélico: dejala afuera.",
     piezas:[
       {id:"m1", texto:"El movimiento no pudo empezar ni puede terminar: todo comienzo de cambio sería él mismo un cambio, y el tiempo, que es número del movimiento, no tiene principio.", tipo:"premisa"},
       {id:"m2", texto:"Ahora bien, todo lo que se mueve es movido por otro, y la serie de motores que mueven siendo movidos no puede extenderse al infinito.", tipo:"premisa"},
       {id:"m3", texto:"Luego ese movimiento eterno exige un primer motor que mueva sin ser movido.", tipo:"premisa"},
       {id:"m4", texto:"Y ese motor no puede tener potencia alguna, porque lo que está en potencia podría no actuar y el movimiento eterno no estaría asegurado: es acto puro y, por eso, sin materia.", tipo:"premisa"},
       {id:"m5", texto:"Por lo tanto, como no puede empujar ni tocar nada, mueve como mueve lo deseado y lo inteligible: como objeto de amor, sin moverse él mismo.", tipo:"conclusion"},
       {id:"mx", texto:"Así como la semilla contiene en potencia al árbol, el primer motor contiene en potencia todas las cosas que va a producir.", tipo:"distractor"}
     ],
     ordenCorrecto:["m1","m2","m3","m4","m5"],
     explicacion:"El argumento combina una tesis cosmológica (m1: el movimiento es eterno) con una tesis física (m2: no hay regreso infinito de motores movidos) para llegar a un primer motor (m3), y luego usa el par acto-potencia para deducir sus propiedades (m4) y su modo de causar (m5). La pieza sobrante invierte el punto central: si el primer motor tuviera potencia, podría no actuar, y por eso Aristóteles lo define como acto puro. Notá además el resultado sorprendente de m5: el primer motor es causa final, no creador; no hace el mundo ni lo conoce, sino que es pensamiento que se piensa a sí mismo y atrae como lo amado. Tomás de Aquino tomará este argumento como su primera vía, pero tendrá que separarlo de m1, porque la fe cristiana no admite un mundo eterno."}
 ],
 dilemas:[
   { titulo:"El informe sobre la colega",
     intro:"Aristóteles sostiene que la virtud es un medio entre dos vicios, pero un medio relativo a nosotros y a la situación, que solo la phronesis puede determinar. Este caso te pide encontrar ese medio donde franqueza, amabilidad y justicia tiran en direcciones distintas.",
     pasos:[
       { id:"p1", situacion:"Coordinás el área de Lengua en una escuela. Una colega nueva, entusiasta y muy querida por los chicos, tiene clases desordenadas: dos cursos llegan a fin de año sin haber visto contenidos básicos. La dirección te pide un informe para decidir si le renueva el contrato. ¿Cómo lo encarás?", opciones:[
         {texto:"Escribo un informe completo y sin atenuantes: los hechos son los hechos.", consecuencia:"Tenés razón en que los hechos importan y en que ocultarlos sería injusto con los estudiantes. Pero Aristóteles vería un riesgo del lado del exceso: la franqueza que no mide cuándo, cómo y ante quién se parece al vicio del pendenciero, al que no le importa causar dolor (EN IV.6). La pregunta no es solo si lo que decís es verdad, sino si lo decís como corresponde.", va:"p2a"},
         {texto:"Destaco lo positivo y menciono los problemas de pasada: es nueva y va a mejorar.", consecuencia:"Protegés a una persona y quizás acertás en que puede mejorar. Pero el informe no es para ella: es para quienes deciden sobre dos cursos de estudiantes. Aristóteles vería aquí un deslizamiento hacia el adulador, que agrada para ahorrarse algo —en este caso, un momento incómodo—. El vicio no está en la amabilidad sino en que la amabilidad decida en lugar del juicio.", va:"p2b"},
         {texto:"Antes de escribir nada, hablo con ella y le cuento lo que voy a informar.", consecuencia:"Agregaste un paso que nadie te pidió, y eso es típico de la phronesis: ver una posibilidad que la situación ofrece y que la consigna («hacé el informe») no mencionaba. Aristóteles insiste en que actuar bien es hacerlo cuando se debe, en lo que se debe, con quienes se debe, para lo que se debe y como se debe (EN II.6, 1106b). Hablar primero con ella cambia el «con quién» y el «cómo».", va:"p2c"} ]},
       { id:"p2a", situacion:"La dirección decide no renovarla. Ella lee el informe y te dice, dolida: «Nunca me dijiste nada en todo el año. Si me lo hubieras dicho en marzo, lo habría corregido». Es verdad que no le dijiste nada. ¿Qué hacés?", opciones:[
         {texto:"Le pido disculpas por no haber hablado antes, pero sostengo el informe.", consecuencia:"Separás dos cosas que Aristóteles también separaría: el informe, que puede ser correcto, y una omisión tuya anterior, que no lo fue. Reconocer la omisión sin retractar lo verdadero es la posición intermedia entre quien se defiende de todo y quien se derrumba ante el reproche.", va:"p3"},
         {texto:"Le explico que no era mi función: yo coordino, no hago tutorías.", consecuencia:"Formalmente puede ser cierto, pero Aristóteles desconfiaría de una definición del propio cargo que justo deja afuera lo incómodo. El prudente no pregunta solo qué le exige su puesto, sino qué pide la situación a alguien en su lugar. En ética también se falla por lo que se omite cuando se debía actuar.", va:"p3"} ]},
       { id:"p2b", situacion:"Tres meses después, una familia se queja formalmente: su hija pasó de año sin saber redactar un párrafo. La dirección revisa los informes y te pregunta por qué el tuyo no advirtió el problema. ¿Qué respondés?", opciones:[
         {texto:"Admito que suavicé el informe por afecto y que me equivoqué.", consecuencia:"Aristóteles distingue entre errar por ignorar algún particular y errar por una disposición torcida. Admitir que el afecto te inclinó es el primer paso de la corrección que él recomienda en EN II.9: saber hacia dónde tiende uno para tirar en sentido contrario la próxima vez.", va:"p3"},
         {texto:"Respondo que los problemas estaban mencionados; si no los leyeron con atención, no es responsabilidad mía.", consecuencia:"Técnicamente escribiste la verdad. Pero el informe estaba hecho para que su parte incómoda no se leyera. Aristóteles juzga la acción también por lo que uno busca con ella, y hay una manera de no mentir que se parece mucho a engañar. El veraz evita las dos.", va:"p3"} ]},
       { id:"p2c", situacion:"Hablás con ella. Te escucha, se angustia y te pide que le des un cuatrimestre antes de informar nada: dice que atraviesa problemas personales que no puede contar. ¿Qué hacés?", opciones:[
         {texto:"Acepto: informo solo lo positivo y me comprometo a acompañarla de cerca.", consecuencia:"Es un gesto generoso, y quizás de amistad en sentido aristotélico. Pero notá el desplazamiento: tu juicio depende ahora de información que no podés evaluar, y el costo lo pagan dos cursos que no estuvieron en la conversación. Lo justo, recuerda Aristóteles en el libro V, mira también a los terceros, no solo al vínculo entre dos.", va:"p3"},
         {texto:"Informo lo que vi, agrego que ella pidió acompañamiento y me ofrezco a darlo.", consecuencia:"Encontraste una acción que no es el promedio entre informar y callar, sino otra cosa: veraz en lo que afirma y generosa en lo que ofrece. Es un buen ejemplo de por qué el medio no es una media aritmética: no se obtiene partiendo la diferencia entre dos extremos sino viendo una posibilidad que ninguno de los dos contemplaba.", va:"p3"} ]},
       { id:"p3", situacion:"A fin de año te piden que dejes, para los futuros coordinadores, una sola regla sobre cómo escribir informes de colegas. ¿Qué escribís?", opciones:[
         {texto:"«Decí siempre toda la verdad, con tacto.»", consecuencia:"Es una buena regla general, y Aristóteles no desprecia las reglas: dice que la ética habla de lo que ocurre la mayoría de las veces. Pero la palabra «tacto» esconde todo el trabajo: cuánto, cuándo y cómo es justamente lo que la regla no puede fijar. Tu regla funciona porque presupone un lector que ya tiene phronesis.", va:null},
         {texto:"«No hay regla: antes de escribir el primero, consultá con alguien que ya haya hecho muchos bien.»", consecuencia:"Es la respuesta más aristotélica y tiene su costo: te deja sin un criterio controlable desde afuera. Aristóteles lo acepta; sus críticos modernos no. Queda la pregunta de qué pasa en una institución donde nadie con experiencia tiene buen juicio.", va:null},
         {texto:"«Escribí el informe que querrías que escribieran sobre vos.»", consecuencia:"Es una versión de la regla de oro, y no es aristotélica: pone el criterio en un intercambio de lugares y no en el carácter de quien juzga. Sirve como control contra el sesgo, pero Aristóteles notaría que alguien con el carácter mal formado puede desear para sí una indulgencia excesiva y aplicar la regla sin cometer ningún error.", va:null} ]}
     ],
     rubrica:[
       "En cada decisión identifiqué los dos vicios en juego, por exceso y por defecto, y no solo «lo correcto».",
       "Revisé si el medio que elegí estaba a igual distancia de los extremos o más cerca de uno de ellos, y por qué (EN II.8).",
       "Reconocí hacia qué lado tiende mi propio carácter en situaciones así y si eso influyó en mi elección (EN II.9).",
       "Tuve en cuenta las circunstancias que enumera Aristóteles —cuándo, con quién, para qué y cómo (EN II.6)— y no solo qué decir.",
       "Distinguí entre la amabilidad debida a mi colega y la justicia debida a los estudiantes y a la institución.",
       "Puedo explicar por qué mi decisión no es simplemente «lo que yo quería hacer» presentado como término medio.",
       "Puedo formular al menos una objeción seria a la ética de la virtud a partir de este caso (por ejemplo: ¿quién decide quién es prudente?)."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.aristoteles = { lecturas:[
 {titulo:"Ética a Nicómaco: la eudaimonía y el término medio", fuente:"Ramon Llull / alcoberro.info — Ética a Nicómaco (traducción castellana en PDF)", url:"http://www.alcoberro.info/pdf/nicomaco.pdf",
  extracto:`La Ética a Nicómaco abre con una tesis teleológica: «todo arte y toda investigación, y del mismo modo toda acción y elección, parecen tender a algún bien». Si hay fines que buscamos por otra cosa y fines que buscamos por sí mismos, tiene que haber un fin último. Aristóteles observa que casi todos coinciden en llamarlo eudaimonía — felicidad o, mejor, «florecimiento» — pero discrepan violentamente sobre en qué consiste: el vulgo la identifica con el placer, los hombres políticos con el honor, otros con la riqueza. Aristóteles descarta cada uno: el placer es una vida «propia de bestias»; el honor depende de quien lo otorga, no de quien lo recibe, y por tanto es demasiado superficial; la riqueza es claramente un medio.

Su método para definirla es el «argumento de la función» (ergon). Así como el bien del flautista está en tocar bien la flauta, el bien del ser humano debe estar en ejercer bien aquello que le es propio. Lo propio no es vivir (lo comparte con las plantas) ni sentir (lo comparte con los animales), sino «una actividad del alma según la razón o no sin la razón». De ahí la definición: la felicidad es «una actividad del alma conforme a la virtud perfecta», y añade «y si las virtudes son varias, conforme a la mejor y más perfecta; y además, en una vida completa», porque «una golondrina no hace verano, ni un solo día».

El Libro II introduce la virtud ética como hábito. Las virtudes no son innatas ni se adquieren por enseñanza teórica: «las adquirimos ejercitándolas primero, como ocurre con las demás artes; pues lo que hay que hacer después de haber aprendido, lo aprendemos haciéndolo: por ejemplo, nos hacemos constructores construyendo casas y citaristas tocando la cítara; así también, practicando la justicia nos hacemos justos, y practicando la moderación, moderados». La consecuencia pedagógica es explícita: «no es de poca importancia adquirir desde jóvenes tales o cuales hábitos; al contrario, es de muchísima importancia, o mejor, lo es todo».

Y de ahí la doctrina del término medio: la virtud es «un término medio entre dos vicios, uno por exceso y otro por defecto». El valor está entre la temeridad y la cobardía; la generosidad, entre la prodigalidad y la avaricia. Pero Aristóteles advierte dos veces contra la lectura aritmética: el medio es «relativo a nosotros», no una media matemática, y hay acciones y pasiones que no admiten medio —el adulterio, el robo, el homicidio— porque «no son malas por exceso o defecto, sino que son malas sin más». Quien decide dónde está el medio en cada caso concreto es la prudencia (phronesis), la virtud del hombre prudente que sabe deliberar.`,
  comentario:"Este pasaje explica por qué Aristóteles rompe con Platón: el bien no es una Forma separada que se contempla, es una actividad que se ejerce y un hábito que se construye. Prestá atención a la advertencia sobre el término medio — la lectura popular («todo con moderación») es justamente la que Aristóteles descarta. La conexión con phronesis responde directamente al cuestionario: se puede saber ética sin ser bueno, porque el saber práctico exige carácter formado."}
], preguntasLectura:[
 {q:"¿Por qué descarta Aristóteles el honor como candidato a bien supremo?", opciones:["Porque es propio de bestias","Porque depende más de quien lo otorga que de quien lo recibe","Porque es un medio para la riqueza","Porque no es agradable"], r:"Porque depende más de quien lo otorga que de quien lo recibe", why:"Aristóteles busca un fin autosuficiente y propio; el honor es demasiado dependiente de otros."},
 {q:"Según el texto, ¿cómo se adquieren las virtudes éticas?", opciones:["Por naturaleza, al nacer","Por contemplación de las Formas","Ejercitándolas, como se aprende un oficio","Por revelación divina"], r:"Ejercitándolas, como se aprende un oficio", why:"«Practicando la justicia nos hacemos justos» — la analogía con el constructor y el citarista es literal en el texto."},
 {q:"¿Qué advertencia hace Aristóteles sobre el término medio?", opciones:["Que es siempre una media aritmética exacta","Que es relativo a cada persona y que hay acciones que no admiten medio alguno","Que solo se aplica a la valentía","Que lo determina la ley escrita"], r:"Que es relativo a cada persona y que hay acciones que no admiten medio alguno", why:"El adulterio, el robo y el homicidio «son malos sin más», no por exceso o defecto."}
]};
