/* ============================================================
   Ficha: beauvoir  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"beauvoir", trad:"europea", nombre:"Simone de Beauvoir", fechas:"1908–1986 · Francia", escuela:"Existencialismo / feminismo filosófico", icon:"✒️", profundizada:true,
 tesis:"La existencia humana es libertad que se proyecta hacia el futuro, pero esa libertad siempre está en situación: en un cuerpo, una historia, una sociedad. Las mujeres no son lo que son por naturaleza, sino por una situación construida a lo largo de siglos, en la que el hombre se definió como el sujeto y la mujer como lo Otro. «No se nace mujer: se llega a serlo.» Y como mi libertad no puede realizarse sin la libertad de los demás, la moral no es la obediencia a valores dados, sino la tarea, siempre ambigua, de querer libres a los otros.",
 obras:[
   {t:"El segundo sexo (1949)", d:"Dos volúmenes, casi mil páginas, y uno de los libros más influyentes del siglo XX. El primero, «Los hechos y los mitos», examina lo que la biología, el psicoanálisis y el materialismo histórico dicen de la mujer, y muestra que ninguno explica por qué la mujer fue constituida como lo Otro; después recorre la historia y los mitos. El segundo, «La experiencia vivida», empieza con la frase más citada del libro y describe la formación de la mujer desde la infancia: la niña, la joven, la iniciación sexual, la esposa, la madre, la vejez, y las figuras de la narcisista, la enamorada y la mística. Termina con «La mujer independiente» y una apuesta por la liberación. El Vaticano lo incluyó en el Índice de libros prohibidos."},
   {t:"Para una moral de la ambigüedad (1947)", d:"Su ensayo filosófico más sistemático, y una respuesta a quienes decían que el existencialismo no podía fundar una ética. Parte de que el ser humano es ambiguo: libertad y facticidad, sujeto y objeto, conciencia y cuerpo, individuo y miembro de una comunidad. Las morales tradicionales intentaron suprimir esa ambigüedad; ella propone asumirla. Describe actitudes que huyen de la libertad —el hombre serio, que se somete a valores dados; el nihilista; el aventurero; el apasionado— y sostiene que querer ser libre implica querer libres a los otros. Su análisis de la acción política, que acepta la violencia en ciertos casos, es de lo más discutido del libro."},
   {t:"Pirro y Cineas (1944)", d:"Su primer ensayo filosófico, construido a partir de un diálogo de Plutarco: el rey Pirro planea conquistas, y su consejero Cineas le pregunta qué hará después de cada una; Pirro responde que descansará, y Cineas le pregunta por qué no descansa ahora. Beauvoir usa la pregunta para pensar el sentido de la acción: ningún fin último justifica todos los proyectos, pero eso no los vuelve inútiles, porque el ser humano es trascendencia, proyecto hacia adelante. El ensayo termina en la relación con los otros: mis proyectos solo tienen sentido si otros los retoman, y por eso necesito que haya otros libres."},
   {t:"Los mandarines (1954) y las memorias", d:"Beauvoir pensó también a través de la novela. Los mandarines, que ganó el premio Goncourt, retrata a los intelectuales de izquierda franceses después de la Liberación y sus dilemas ante el comunismo y los campos soviéticos. Sus memorias, empezando por Memorias de una joven formal (1958), reconstruyen cómo una muchacha de la burguesía católica llegó a ser escritora y filósofa. Son a la vez documento histórico y aplicación de su propio método: mostrar cómo una situación concreta forma a una persona sin determinarla por completo."},
   {t:"La vejez (1970)", d:"Un estudio tan amplio como El segundo sexo, dedicado a otro grupo convertido en lo Otro: los viejos. Beauvoir muestra que la vejez no es solo un hecho biológico, sino un estatuto social, y que las sociedades modernas, al medir a las personas por su productividad, tratan a los ancianos como restos. El libro es una de las primeras reflexiones filosóficas sistemáticas sobre el envejecimiento y sigue siendo pertinente en sociedades que envejecen, como la colombiana."}
 ],
 conceptos:[
   {t:"«No se nace mujer: se llega a serlo»", d:"Es la frase que abre el segundo volumen de El segundo sexo, y su sentido es preciso. Ningún destino biológico, psíquico o económico define la figura que la mujer tiene en la sociedad: es el conjunto de la civilización el que la elabora. Beauvoir no niega que haya diferencias biológicas; niega que ellas expliquen el lugar social de las mujeres. La niña aprende a ser mujer en la manera en que la visten, la educan, la limitan y le enseñan a esperar. La frase abrió la distinción posterior entre sexo y género, aunque Beauvoir no usó esa palabra, y autoras como Judith Butler llevaron su idea más lejos, al preguntar si el sexo mismo no es también una construcción."},
   {t:"La mujer como lo Otro", d:"En la introducción de El segundo sexo, Beauvoir toma de Hegel la idea de que la conciencia se constituye oponiéndose a otra. En la relación entre los sexos, esa oposición no fue recíproca: el hombre se definió como el sujeto, lo esencial, lo absoluto, y definió a la mujer en relación con él, como lo inesencial, lo Otro. Por eso, dice, un hombre nunca empieza presentándose como individuo de un sexo determinado: se da por supuesto que es hombre; una mujer, en cambio, tiene que declarar primero que es mujer. Lo singular del caso es que, a diferencia de otros grupos oprimidos, las mujeres no tienen un pasado común ni un territorio propio: viven dispersas entre los hombres, ligadas a ellos por el hogar, el trabajo y el afecto."},
   {t:"Situación", d:"Es el concepto que distingue a Beauvoir de un existencialismo abstracto. Sartre había insistido en que el ser humano es libertad absoluta; Beauvoir sostiene, ya desde los años cuarenta, que la libertad siempre está situada: en un cuerpo, una clase, una época, un sexo. La situación no determina lo que uno hace, pero sí define el campo de sus posibilidades. No es lo mismo la libertad de una mujer de la burguesía parisina que la de una obrera, ni la de una mujer en 1949 que en 2026. Esta insistencia la llevó a cuestionar a Sartre, y muchos lectores consideran que en este punto ella influyó en él más que él en ella."},
   {t:"Inmanencia y trascendencia", d:"La trascendencia es el movimiento de la existencia hacia el futuro: proyectar, crear, abrir posibilidades. La inmanencia es la repetición, el estancamiento, la vida que se mantiene sin superarse. Beauvoir sostiene que la condición femenina ha consistido en confinar a las mujeres en la inmanencia: el cuidado del hogar, la repetición de tareas que se deshacen cada día, una existencia definida por los proyectos de otros. El concepto ha sido criticado por devaluar el trabajo de cuidado, y la propia Beauvoir fue acusada de despreciar la maternidad; ella respondería que lo que critica no es el cuidado, sino que sea un destino impuesto."},
   {t:"Complicidad y mala fe", d:"Beauvoir no presenta a las mujeres solo como víctimas. Sostiene que muchas aceptan su situación porque ofrece ventajas: protección material, la comodidad de no tener que elegir, la justificación que viene de otro. Esta complicidad es una forma de mala fe: huir de la propia libertad haciendo como si no existiera. Es una de las tesis más incómodas del libro, y por eso mismo de las más discutidas. No culpa a las mujeres de su opresión, que tiene causas históricas, pero sí sostiene que la liberación exige renunciar a esas ventajas, y que nadie puede hacerlo por ellas."},
   {t:"Ambigüedad", d:"El ser humano es a la vez libertad y cosa, sujeto y objeto, conciencia y cuerpo, individuo y parte de una historia. Para Beauvoir, esa ambigüedad no es un defecto que la filosofía deba resolver, sino la condición humana misma. Las morales tradicionales intentaron negarla, sometiendo la libertad a valores eternos o a una idea de la historia; el resultado fue justificar la opresión en nombre de fines superiores. Su propuesta es asumir la ambigüedad: actuar sin la garantía de un valor absoluto, sabiendo que toda acción puede fracasar o tener consecuencias que no queríamos."},
   {t:"Querer libres a los otros", d:"Es el núcleo de su ética. Mi libertad no puede realizarse sola: mis proyectos solo tienen sentido si hay otros que los retomen, los discutan y los continúen, y solo pueden hacerlo si son libres. Por eso, querer ser libre implica querer libres a los otros. De aquí sale un criterio para juzgar las acciones: es condenable lo que reduce a otros a cosas, aunque lo haga en nombre de un ideal. Este criterio le permitió criticar tanto el colonialismo francés en Argelia —defendió a la militante argelina Djamila Boupacha, torturada por el ejército francés— como, más tarde, aspectos del comunismo."},
   {t:"El mito del eterno femenino", d:"La sociedad no solo oprime a las mujeres: las piensa a través de mitos. Beauvoir analiza cómo la literatura, la religión y el arte construyeron imágenes de la mujer como misterio, naturaleza, madre, tentación o musa: figuras que no describen a ninguna mujer real, sino lo que los hombres esperaban o temían. Estudia ese mito en cinco escritores, entre ellos D. H. Lawrence, Claudel y Stendhal. Su crítica es que el mito permite no ver a las mujeres concretas: si la mujer es un misterio, no hace falta escucharla."},
   {t:"La reciprocidad", d:"Beauvoir no propone invertir la jerarquía ni separar a los sexos. Su horizonte es una relación recíproca, en la que cada uno reconozca al otro como sujeto, como libertad. El amor auténtico, escribe en el capítulo sobre la enamorada, sería el de dos libertades que se reconocen, y no el de una que se pierde en la otra. Esa reciprocidad no niega las diferencias, sino la jerarquía. El final de El segundo sexo afirma que, cuando se suprima la esclavitud de la mitad de la humanidad, la relación entre los sexos podrá revelar su verdadera forma."}
 ],
 conexion:"Comparte con <b>Heidegger</b> y con Sartre el vocabulario de la existencia, pero lo corrige desde la situación concreta. Toma de <b>Hegel</b> la dialéctica del reconocimiento, y le reprocha haberla pensado como si el sujeto no tuviera sexo. Su vida tiene zonas que no conviene saltear: en 1943 fue suspendida de la enseñanza después de que la madre de una alumna la acusara de corromper a una menor; Bianca Lamblin, que fue su alumna, publicó en 1993 un libro en el que describe la relación con ella y con Sartre como un abuso; y en 1977 firmó, con Sartre y otros intelectuales, una petición pública en defensa de adultos procesados por relaciones sexuales con menores de quince años. Las críticas feministas posteriores, como las de bell hooks y el feminismo negro, le reprocharon pensar desde la experiencia de las mujeres blancas y burguesas. Su idea de la situación conecta con <b>Arendt</b> y su pregunta por quién cuenta como sujeto, y con <b>Sor Juana</b>, que defendió tres siglos antes el derecho de las mujeres al saber.",
 dialogo:{titulo:"¿Para qué el feminismo, si ya somos iguales?", lineas:[
   {quien:"Estudiante", texto:"Profesora, con todo respeto, su libro es de 1949. Hoy las mujeres votan, estudian, trabajan y hasta son presidentas. ¿No está ya superado?"},
   {quien:"Beauvoir", texto:"Ojalá lo estuviera. Pero contame algo: en tu casa, ¿quién cocina? ¿Quién se queda cuando un niño se enferma? ¿Quién deja el trabajo cuando hay que cuidar a un abuelo?"},
   {quien:"Estudiante", texto:"Mi mamá, casi siempre. Pero porque ella quiere. Nadie la obliga."},
   {quien:"Beauvoir", texto:"Es posible que quiera. La pregunta es de dónde viene ese querer. Desde chiquita le enseñaron que cuidar era lo suyo, la felicitaron cuando lo hacía y la miraron raro cuando no. Nadie la obligó con una ley, y por eso es más difícil de ver: la situación se convierte en carácter, y el carácter parece naturaleza."},
   {quien:"Estudiante", texto:"Pero entonces nadie elige nada. Todos somos lo que nos enseñaron."},
   {quien:"Beauvoir", texto:"No, y es justamente lo que quiero evitar. La situación no te determina: define el campo de tus posibilidades. Tu mamá puede elegir, pero elige dentro de un campo que no eligió. Si no ves ese campo, confundís sus elecciones con su naturaleza, y entonces no hay nada que cambiar."},
   {quien:"Estudiante", texto:"Usted dice también que muchas mujeres son cómplices. Eso suena a culpar a las víctimas."},
   {quien:"Beauvoir", texto:"Es lo más incómodo que escribí, y no lo retiro. La opresión tiene causas históricas que no dependen de ninguna mujer en particular. Pero también ofrece ventajas: la protección, la comodidad de no tener que decidir, la justificación que viene de otro. Renunciar a eso cuesta, y nadie puede hacerlo en tu lugar. No es culpa: es responsabilidad, que es otra cosa."},
   {quien:"Estudiante", texto:"Y los hombres, ¿qué ganan con todo esto? Porque si los hombres pierden privilegios, no van a querer."},
   {quien:"Beauvoir", texto:"Ganan algo que no saben que les falta: una relación con alguien libre. Quien domina solo tiene enfrente a alguien que obedece o finge. El reconocimiento de un igual es más difícil, pero es el único que vale. Y mi libertad no puede realizarse sin la de los otros."},
   {quien:"Estudiante", texto:"Leí que usted firmó una petición en 1977 que defendía a adultos acusados de relaciones con menores. ¿Cómo se concilia eso con querer libres a los otros?"},
   {quien:"Beauvoir", texto:"No se concilia bien, y no voy a pretender que sí. En esos años muchos de nosotros pensamos que estábamos defendiendo la libertad contra la moral burguesa, y no vimos, o no quisimos ver, que la libertad de un niño frente a un adulto no es la de un igual. Mi propio criterio —no reducir a otro a objeto— condenaba lo que firmé.", nota:"Este parlamento es una reconstrucción didáctica: Beauvoir no se retractó públicamente de la petición de 1977. Los hechos —la petición, la suspensión de 1943 y el testimonio de Bianca Lamblin— están documentados, y forman parte de la discusión actual sobre cómo leer su obra."}
 ]},
 actividades:[
   {t:"Llegar a ser: una biografía de los aprendizajes", d:"Escribí una página sobre cómo aprendiste a ser lo que socialmente se espera de tu género —mujer, hombre u otra identidad— a partir de recuerdos concretos: juguetes que te regalaron o te negaron, frases que escuchabas de niño o de niña, tareas que te asignaban en la casa, comentarios sobre tu cuerpo o tu ropa. Para cada recuerdo, preguntate si lo viviste como natural en ese momento y si hoy lo verías igual. Terminá con un párrafo que distinga, en tu propio caso, lo que es situación de lo que es elección."},
   {t:"Contar el trabajo invisible", d:"Durante una semana, registrá en una tabla todas las tareas domésticas y de cuidado que se hacen en tu casa —cocinar, lavar, cuidar a niños o mayores, hacer mercado, recordar citas médicas— y quién las hace, con el tiempo aproximado. Al final, sumá las horas por persona. Escribí una reflexión de una página: ¿qué muestra la tabla?, ¿coincide con lo que tu familia diría si le preguntaras?, ¿cómo leería Beauvoir ese reparto con los conceptos de inmanencia y trascendencia? Compará tus datos con la Encuesta Nacional de Uso del Tiempo del DANE, si podés consultarla."},
   {t:"Leer un mito del eterno femenino", d:"Elegí una canción, una telenovela, un comercial o una publicación en redes que presente una imagen de «la mujer» en general: la madre abnegada, la mujer misteriosa, la tentadora, la que se sacrifica por amor. Describí la imagen con detalle y analizala con Beauvoir: ¿qué espera o teme de las mujeres quien la produjo?, ¿qué mujer real queda oculta detrás de ella?, ¿quién habla y quién es hablada? Terminá proponiendo cómo podría representarse a esa misma mujer como sujeto y no como lo Otro."}
 ],
 cuestionario:[
   {q:"Si «no se nace mujer», ¿niega Beauvoir que existan diferencias biológicas entre los sexos?", p:"No las niega: les dedica el primer capítulo de El segundo sexo, y describe con detalle las diferencias en la reproducción, la fuerza muscular y los ciclos del cuerpo. Lo que niega es que esas diferencias expliquen el lugar social de las mujeres. Un mismo hecho biológico puede tener sentidos muy distintos según la sociedad: la menstruación puede ser motivo de vergüenza o de celebración, la maternidad puede ser un destino obligatorio o una elección. Para Beauvoir, el cuerpo no es una cosa, sino una situación: el modo en que vivimos nuestra relación con el mundo. Por eso dice que la biología no es un destino. La discusión posterior se dividió. Algunas feministas de la diferencia le reprocharon minimizar el valor de lo específicamente femenino; Judith Butler, en cambio, sostuvo que Beauvoir no fue lo bastante lejos, porque mantuvo la idea de un sexo natural sobre el cual se construye el género."},
   {q:"La tesis de la complicidad, ¿no culpa a las mujeres de su propia opresión?", p:"Es la objeción más fuerte, y hay que responderla con cuidado. Beauvoir sostiene que la opresión de las mujeres tiene causas históricas y económicas que no dependen de ninguna mujer en particular, y dedica la mayor parte del libro a describirlas. Pero agrega que esa opresión ofrece ventajas —protección material, comodidad, justificación externa— y que muchas mujeres las aceptan, lo que constituye una forma de mala fe. La diferencia entre culpa y responsabilidad es clave: culpa sería atribuir la causa de la opresión a las mujeres; responsabilidad es reconocer que la liberación requiere también que cada una asuma su libertad, y que eso no puede hacerlo nadie por ella. La crítica sigue en pie para muchos casos: hay situaciones en que la dependencia no es una ventaja elegida, sino la única forma de sobrevivir, y hablar ahí de complicidad puede ser injusto. Beauvoir pensaba sobre todo en mujeres de su clase."},
   {q:"¿Qué distingue la ética de Beauvoir de la de Sartre?", p:"Los dos parten de la libertad, pero Beauvoir insiste antes y con más fuerza en que la libertad está situada. Sartre, en El ser y la nada, había descrito una libertad absoluta: incluso el prisionero es libre de darle un sentido a su prisión. Beauvoir objeta que no todas las situaciones dejan el mismo margen: una mujer encerrada en el hogar, un esclavo o un colonizado no tienen las mismas posibilidades que un intelectual parisino. Por eso su ética no es solo la autenticidad individual, sino la exigencia de crear condiciones en que otros puedan ser libres. En Para una moral de la ambigüedad desarrolla una ética que Sartre nunca llegó a escribir del todo. Durante mucho tiempo se la leyó como discípula de Sartre; la investigación de las últimas décadas, que incluye sus diarios de juventud, muestra que varias ideas atribuidas a él aparecen antes en sus escritos."},
   {q:"¿Cómo leer la obra de Beauvoir a la luz de la petición de 1977 y del testimonio de Bianca Lamblin?", p:"Primero, con los hechos claros. En 1943 fue suspendida de la enseñanza después de una denuncia de la madre de una alumna. Bianca Lamblin, que fue su alumna y amante, publicó en 1993 un libro en el que describe la relación con Beauvoir y Sartre como una manipulación que la dañó. Y en 1977 Beauvoir firmó una petición en defensa de adultos procesados por relaciones con menores de quince años. Estos hechos plantean un problema real, porque su propia ética condena reducir a otro a objeto, y la asimetría entre un adulto y un menor, o entre una profesora y su alumna, es exactamente la que su teoría de la situación permite ver. No hace falta elegir entre descartar la obra y ocultar los hechos. Se puede usar su propia filosofía para juzgar su conducta, y reconocer que hay un desacuerdo entre lo que pensó y lo que hizo, como en tantos otros autores de esta app."},
   {q:"El segundo sexo, ¿habla de todas las mujeres o solo de algunas?", p:"Beauvoir pretendía describir la condición femenina en general, pero escribió desde una posición particular: la de una mujer blanca, europea, de origen burgués y con educación universitaria. Las críticas posteriores, sobre todo del feminismo negro y del feminismo latinoamericano y decolonial, señalaron que la experiencia de una mujer negra, indígena o pobre no se reduce a la de ser lo Otro del hombre: está atravesada también por la raza, la clase y la colonización. Bell hooks y otras autoras mostraron que, para muchas mujeres, el trabajo fuera de casa no fue una conquista, sino una necesidad de siempre. Beauvoir no ignoró del todo estas diferencias —compara a las mujeres con los judíos y los negros, y habla de la clase—, pero su análisis central toma como modelo a las mujeres de su medio. La crítica no anula el libro, pero obliga a leerlo como un punto de partida, no como la última palabra."}
 ],
 cadena:{ titulo:"¿Qué quiere decir «llegar a ser mujer»?", intro:"Un razonamiento en ramas sobre la frase más citada de El segundo sexo. Las ramas recorren la relación entre biología y situación, la crítica de Judith Butler y la pregunta por la libertad dentro de una situación que no se eligió.", inicio:"n1", nodos:{
   n1:{ pregunta:"«No se nace mujer: se llega a serlo.» ¿Qué afirma exactamente Beauvoir con esa frase?", opciones:[
     {texto:"Que las diferencias biológicas no existen: todo es cultural.", va:"n2a"},
     {texto:"Que la figura social de la mujer no se explica por la biología, sino por una situación que la civilización construyó.", va:"n2b"} ]},
   n2a:{ pregunta:"Beauvoir dedica el primer capítulo de El segundo sexo a la biología, y describe con detalle diferencias reales en la reproducción y en el cuerpo. ¿Qué hace con ellas?", opciones:[
     {texto:"Las usa para probar que las mujeres son naturalmente inferiores.", final:{tipo:"revisar", texto:"Es lo contrario de lo que sostiene. Beauvoir describe las diferencias biológicas para mostrar que, por sí solas, no explican nada: un mismo hecho del cuerpo adquiere sentidos muy distintos según la sociedad que lo interpreta. La biología, escribe, no es un destino. Volvé un paso y probá otra respuesta."}},
     {texto:"Las reconoce, pero muestra que no determinan el lugar social de las mujeres: el cuerpo es una situación, no un destino.", va:"n3a"} ]},
   n3a:{ pregunta:"Si el cuerpo es una situación que se vive de maneras distintas, ¿hasta dónde llega la construcción social?", opciones:[
     {texto:"Hasta el género, pero no hasta el sexo: hay un cuerpo sexuado sobre el cual la sociedad construye lo femenino.", final:{tipo:"bien", texto:"Es la lectura que dio origen a la distinción entre sexo y género, que el feminismo de los años setenta desarrolló a partir de Beauvoir. Ganás claridad: se puede discutir lo social sin negar lo biológico. El costo es que la frontera entre lo natural y lo social se vuelve difícil de trazar, y esa dificultad es la que aprovecha la crítica de Butler."}},
     {texto:"Hasta el sexo mismo: también la manera en que clasificamos los cuerpos es una construcción.", final:{tipo:"bien", texto:"Es la radicalización de Judith Butler en El género en disputa (1990), que lee a Beauvoir y le reprocha haber conservado la idea de un sexo natural. Ganás una crítica más profunda de las categorías. El costo es que hay que explicar qué lugar queda para la experiencia del cuerpo que Beauvoir describía con tanto detalle, y muchas feministas sostienen que Butler pierde ahí algo que Beauvoir tenía."}} ]},
   n2b:{ pregunta:"Si la situación de las mujeres es construida, ¿son las mujeres libres o están determinadas por esa situación?", opciones:[
     {texto:"Están determinadas: la sociedad las forma por completo, y no tienen responsabilidad en lo que son.", final:{tipo:"revisar", texto:"Beauvoir rechaza esa conclusión: la situación define el campo de las posibilidades, pero no elige por la persona. Si las mujeres estuvieran completamente determinadas, no habría liberación posible, ni ninguna razón para escribir El segundo sexo. Volvé un paso y probá la otra respuesta."}},
     {texto:"Son libres dentro de una situación que no eligieron: la situación limita sus posibilidades, pero no elige por ellas.", va:"n3b"} ]},
   n3b:{ pregunta:"Si las mujeres son libres dentro de su situación, ¿qué pasa cuando aceptan esa situación porque les conviene?", opciones:[
     {texto:"Es complicidad, una forma de mala fe: huir de la propia libertad aceptando las ventajas de la dependencia.", final:{tipo:"bien", texto:"Es la tesis incómoda de Beauvoir. Distingue entre culpa y responsabilidad: la opresión no es culpa de las mujeres, pero la liberación requiere que cada una asuma su libertad. La crítica más fuerte es que, para muchas mujeres pobres, la dependencia no es una ventaja elegida, sino una forma de sobrevivir. Beauvoir pensaba sobre todo en las mujeres de su propia clase."}},
     {texto:"No se puede hablar de conveniencia: si la situación es opresiva, aceptarla es solo sobrevivir.", final:{tipo:"bien", texto:"Es la objeción que se le hizo desde el feminismo negro y popular: hablar de complicidad supone un margen de elección que muchas mujeres no tienen. Ganás una atención más fina a las desigualdades entre mujeres. El costo es que, si nunca hay elección, tampoco hay nadie que pueda liberarse, y Beauvoir diría que esa conclusión también le conviene a la opresión."}} ]}
 }},
 reconstruccion:[
   { titulo:"La mujer como lo Otro (introducción de El segundo sexo)",
     consigna:"Reconstruí el argumento con que Beauvoir explica la situación de las mujeres a partir de la relación entre sujeto y Otro. Una pieza saca una conclusión que Beauvoir rechaza: dejala afuera y ordená el resto.",
     piezas:[
       {id:"o1", texto:"Toda conciencia se constituye oponiéndose a otra: el sujeto se afirma frente a lo que no es él, a lo Otro.", tipo:"premisa"},
       {id:"o2", texto:"En las relaciones entre grupos, esa oposición suele ser recíproca: cada grupo es el Otro para el otro grupo.", tipo:"premisa"},
       {id:"o3", texto:"Entre los sexos, la reciprocidad no se dio: el hombre se definió como el sujeto, lo esencial, y definió a la mujer en relación con él.", tipo:"premisa"},
       {id:"o4", texto:"Las mujeres, dispersas entre los hombres y ligadas a ellos por el hogar, el trabajo y el afecto, no constituyeron un grupo capaz de devolver la oposición.", tipo:"premisa"},
       {id:"o5", texto:"Por lo tanto, la mujer quedó constituida como lo Otro absoluto, sin reciprocidad, y esa es una situación histórica que puede transformarse.", tipo:"conclusion"},
       {id:"ox", texto:"Por lo tanto, la mujer es lo Otro por naturaleza, y su liberación es imposible.", tipo:"distractor"}
     ],
     ordenCorrecto:["o1","o2","o3","o4","o5"],
     explicacion:"Beauvoir toma de Hegel la estructura del reconocimiento (o1) y muestra que el caso de los sexos es una excepción a la reciprocidad (o2-o3), explicada por condiciones históricas, no naturales (o4). El punto débil es o1: si toda conciencia se constituye frente a un Otro, ¿es posible una relación sin jerarquía? Beauvoir confía en que la reciprocidad puede reemplazar a la dominación, pero su punto de partida hegeliano hace que eso dependa de una lucha. La pieza sobrante naturaliza lo que Beauvoir historiza: todo su libro existe para mostrar que esa situación puede cambiar."},
   { titulo:"Querer libres a los otros (Para una moral de la ambigüedad)",
     consigna:"Reconstruí el argumento que lleva de la libertad individual a la exigencia de la libertad de los otros. Una pieza confunde la libertad con hacer lo que uno quiere: dejala afuera.",
     piezas:[
       {id:"l1", texto:"El ser humano es libertad: un proyecto que se dirige hacia el futuro y le da sentido a lo que hace.", tipo:"premisa"},
       {id:"l2", texto:"Ningún proyecto se cierra en sí mismo: solo tiene sentido si otros lo retoman, lo discuten o lo continúan.", tipo:"premisa"},
       {id:"l3", texto:"Solo pueden retomar mis proyectos quienes son libres: un esclavo o una persona reducida a objeto no puede responderme como un igual.", tipo:"premisa"},
       {id:"l4", texto:"Por lo tanto, querer ser libre implica querer libres a los otros, y es condenable lo que reduce a otros a cosas, aunque se haga en nombre de un ideal.", tipo:"conclusion"},
       {id:"lx", texto:"Por lo tanto, cada uno es libre de hacer lo que quiera, mientras sea fiel a sí mismo.", tipo:"distractor"}
     ],
     ordenCorrecto:["l1","l2","l3","l4"],
     explicacion:"El argumento pasa de una descripción de la libertad (l1) a una exigencia ética (l4), por medio de la dependencia de nuestros proyectos respecto de otros (l2-l3). El punto débil es l2: alguien podría responder que sus proyectos no necesitan a otros libres, sino solo a otros obedientes, y que se satisface con eso. Beauvoir contesta que ese sentido es pobre, porque la obediencia no confirma nada; pero es una tesis sobre qué hace valioso un proyecto, no una demostración. La pieza sobrante confunde libertad con capricho: para Beauvoir, la autenticidad no es hacer lo que uno quiere, sino asumir la ambigüedad de actuar entre otros."}
 ],
 dilemas:[
   { titulo:"La beca de Laura",
     intro:"Beauvoir sostuvo que la libertad siempre está en situación, y que la liberación exige a la vez cambiar las condiciones y asumir la propia libertad, renunciando a las ventajas de la dependencia. Este caso pone esas ideas en una decisión de una joven del Tolima.",
     pasos:[
       { id:"p1", situacion:"Laura, de diecinueve años, vive en un municipio del Tolima. Ganó una beca para estudiar ingeniería en Bogotá. Su familia está orgullosa, pero su madre tiene una enfermedad crónica y Laura es quien la cuida, y su novio le dice que «una relación a distancia no funciona». Laura te pide consejo. ¿Qué le decís?", opciones:[
         {texto:"«Tu familia te necesita. Hay cosas más importantes que una carrera.»", consecuencia:"Es lo que muchas mujeres escucharon durante siglos, y Beauvoir lo llamaría inmanencia: una vida definida por el cuidado de otros, sin proyecto propio. Puede que la familia la necesite, pero fijate que nadie le diría lo mismo a un hermano varón con la misma beca.", va:"p2"},
         {texto:"«Andate. Tu vida es tuya y nadie puede decidir por vos.»", consecuencia:"Defendés su libertad, y Beauvoir estaría de acuerdo en el fondo. Pero tu consejo ignora la situación: la enfermedad de la madre es real, y la pregunta de quién la va a cuidar no desaparece porque Laura se vaya. Una libertad que no mira su situación es abstracta.", va:"p2"},
         {texto:"«Antes de decidir, veamos quién más podría cuidar a tu mamá y qué apoyos existen. Que la decisión no dependa de que solo vos puedas hacerlo.»", consecuencia:"Pusiste el foco en la situación: por qué el cuidado recae solo en Laura. Beauvoir diría que la liberación no es solo una decisión individual, sino también un cambio en el reparto de las cargas.", va:"p2"} ]},
       { id:"p2", situacion:"Laura habla con su familia. Su hermano mayor, que trabaja en Ibagué, dice que no puede ayudar con el cuidado «porque es hombre y no sabe de eso». Laura empieza a dudar: quedarse le evitaría el miedo a fracasar en Bogotá. ¿Qué le decís?", opciones:[
         {texto:"«Quedate: así no tenés que enfrentar el miedo.»", consecuencia:"Beauvoir llamaría a esto complicidad: aceptar la situación porque ofrece una ventaja, la de no arriesgarse. No es culpa de Laura que la carga recaiga en ella, pero sí es suya la decisión de usar esa carga como refugio.", va:"p3"},
         {texto:"«El miedo es normal. Pero preguntate si te quedás por tu mamá o porque es más fácil.»", consecuencia:"Le ayudaste a distinguir entre una razón y una excusa, que es lo que Beauvoir pedía: asumir la libertad sin la garantía de que todo va a salir bien.", va:"p3"},
         {texto:"«Tu hermano tiene que asumir su parte. Que «no sabe» no es una razón.»", consecuencia:"Señalaste el otro lado de la situación: la división del cuidado por género. «No sé» es el argumento con que se mantiene esa división. Beauvoir diría que no se trata de que Laura se sacrifique o se libere sola, sino de que la carga deje de recaer en ella por ser mujer.", va:"p3"} ]},
       { id:"p3", situacion:"Al final, Laura decide ir a Bogotá; su hermano asume parte del cuidado y contratan apoyo para la madre. Un año después, Laura te pregunta si hizo bien. ¿Qué le respondés?", opciones:[
         {texto:"«Sí, porque elegiste lo correcto.»", consecuencia:"Beauvoir desconfiaría de la palabra «correcto»: no hay un valor absoluto que garantice que una decisión fue buena. Lo que hay es una decisión asumida, con sus costos, en una situación ambigua.", va:null},
         {texto:"«No sé si fue lo correcto. Sé que fue tuya, y que no la tomaste sola: cambiaste también cómo se repartía el cuidado.»", consecuencia:"Es la respuesta de la moral de la ambigüedad: no hay garantía, pero sí una libertad asumida y una situación transformada, para ella y para los demás.", va:null},
         {texto:"«Si te fue bien, hiciste bien; si te hubiera ido mal, no.»", consecuencia:"Juzgás la decisión por el resultado. Beauvoir diría que el resultado nunca está garantizado, y que una decisión no se vuelve buena o mala por lo que pasó después, sino por cómo se asumió.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar con este caso qué quiere decir que la libertad siempre está en situación.",
       "Distinguí entre la situación de Laura (lo que no eligió) y sus elecciones dentro de ella.",
       "Reconocí cómo la división del cuidado por género formaba parte del problema.",
       "Puedo explicar la diferencia entre culpa y responsabilidad en la tesis de la complicidad.",
       "No confundí la libertad con hacer lo que uno quiere sin mirar a los demás.",
       "Pensé una salida que transformara la situación, no solo la decisión individual.",
       "Formulé la objeción más fuerte: que, para muchas mujeres pobres, hablar de elección o de complicidad puede ser injusto."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.beauvoir = { lecturas:[
 {titulo:"El segundo sexo: la mujer como lo Otro y «llegar a ser»", fuente:"Síntesis de trabajo sobre la introducción y el comienzo del segundo volumen de El segundo sexo (1949); para la vida y la obra, Wikipedia en español", url:"https://es.wikipedia.org/wiki/Simone_de_Beauvoir",
  extracto:`El segundo sexo empieza con una pregunta aparentemente simple: ¿qué es una mujer? Beauvoir observa que un hombre nunca empezaría un libro presentándose como individuo de un sexo determinado, porque se da por supuesto que es hombre. Una mujer, en cambio, tiene que declarar primero que es mujer. Esa asimetría es el punto de partida del libro.

Para explicarla, recurre a una idea que toma de Hegel: toda conciencia se constituye oponiéndose a otra. El sujeto se afirma frente a lo que no es él, frente a lo Otro. En muchas relaciones entre grupos esa oposición es recíproca, pero entre los sexos no lo fue: el hombre se definió como el sujeto, lo esencial, lo absoluto, y definió a la mujer en relación con él, como lo inesencial. Ella es lo Otro.

¿Por qué las mujeres no devolvieron la oposición, como lo hacen otros grupos? Beauvoir encuentra una razón histórica: las mujeres no tienen un pasado común ni un territorio propio. Viven dispersas entre los hombres, ligadas a ellos por el hogar, el trabajo, los intereses económicos y el afecto. Una burguesa se siente más cerca de los hombres de su clase que de las obreras.

El segundo volumen empieza con la frase más citada del libro: «No se nace mujer: se llega a serlo». Ningún destino biológico, psíquico o económico define la figura que la mujer tiene en la sociedad; es el conjunto de la civilización el que la elabora. Beauvoir describe entonces cómo ocurre: cómo se educa a la niña, cómo se la viste, qué se le permite y qué se le prohíbe, cómo aprende a esperar en lugar de proyectar.

El libro termina con una apuesta: cuando las mujeres puedan existir como sujetos, la relación entre los sexos podrá ser recíproca, una relación entre dos libertades que se reconocen.`,
  comentario:"Fijate en el uso de Hegel: Beauvoir no inventa la idea de lo Otro, la toma de la filosofía y muestra que esa filosofía no había pensado el caso de los sexos. Y fijate en lo que la frase central no dice: no niega la biología, niega que la biología explique la situación social. Leé este texto junto con las críticas posteriores —Butler, bell hooks— y con los hechos de su biografía que la ficha no oculta."}
], preguntasLectura:[
 {q:"¿Por qué, según Beauvoir, una mujer tiene que declarar primero que es mujer y un hombre no?", opciones:["Porque los hombres son más modestos","Porque el hombre se da por supuesto como el sujeto, y la mujer se define en relación con él","Porque la ley lo exige","Porque las mujeres son minoría"], r:"Porque el hombre se da por supuesto como el sujeto, y la mujer se define en relación con él", why:"La asimetría muestra que el hombre ocupa el lugar de lo universal y la mujer el de lo Otro."},
 {q:"¿Qué razón da Beauvoir para que las mujeres no hayan devuelto la oposición como otros grupos?", opciones:["Que son naturalmente pasivas","Que viven dispersas entre los hombres, sin pasado común ni territorio propio","Que no les interesa la política","Que la religión se los prohíbe"], r:"Que viven dispersas entre los hombres, sin pasado común ni territorio propio", why:"Es una explicación histórica y social, no natural."},
 {q:"¿Qué afirma la frase «No se nace mujer: se llega a serlo»?", opciones:["Que no existen diferencias biológicas","Que la figura social de la mujer la elabora la civilización, no un destino biológico","Que toda mujer elige libremente su destino","Que las mujeres son inferiores por educación"], r:"Que la figura social de la mujer la elabora la civilización, no un destino biológico", why:"Beauvoir reconoce las diferencias biológicas, pero niega que expliquen el lugar social de las mujeres."}
]};
