/* ============================================================
   Ficha: descartes  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"descartes", trad:"europea", nombre:"René Descartes", fechas:"1596–1650 · Francia/Países Bajos", escuela:"Racionalismo moderno", icon:"🪞", profundizada:true,
 tesis:"Para fundar el conocimiento con certeza hay que dudar de todo lo dudable hasta hallar algo indudable: el cogito. De ahí reconstruye el mundo, dividiendo la realidad en dos sustancias — pensante y extensa.",
 obras:[
   {t:"Meditaciones metafísicas", d:"Seis meditaciones escritas en primera persona, publicadas en 1641, que no exponen un sistema sino que hacen vivir al lector el itinerario completo de la duda: un meditador se sienta junto al fuego, decide derribar por una vez en la vida todas sus opiniones y va perdiendo, oleada tras oleada, los sentidos, el mundo exterior, el propio cuerpo y hasta la matemática. En el punto más bajo encuentra el cogito, y desde ahí reconstruye: primero la existencia de Dios, después la veracidad de las ideas claras y distintas, por último el mundo material y la distinción real entre alma y cuerpo. Descartes las publicó junto con siete series de Objeciones y Respuestas de teólogos y filósofos —entre ellos Hobbes, Arnauld y Gassendi—, de modo que la obra incluye sus propias refutaciones: leer las Objeciones es leer la primera y mejor crítica al cartesianismo."},
   {t:"Discurso del método", d:"Publicado en 1637 como prólogo a tres ensayos científicos (la Dióptrica, los Meteoros y la Geometría), es el primer gran texto filosófico escrito en francés y no en latín, decisión deliberada para que lo leyeran también quienes no pasaron por la universidad. Su forma es autobiográfica: cuenta cómo el joven Descartes descubrió que la erudición escolástica no daba certeza, cómo se lanzó al mundo a leer en el gran libro de la experiencia y cómo, encerrado en una habitación caldeada, dio con las cuatro reglas del método. Allí aparece por primera vez en público la fórmula pienso, luego existo, y también la moral provisional —obedecer las leyes del país, ser firme en las decisiones tomadas, vencerse a uno mismo antes que a la fortuna— con la que Descartes decide vivir mientras dure la reconstrucción del saber."},
   {t:"Principios de filosofía", d:"Tratado de 1644 escrito en latín y ordenado en artículos numerados, con la intención declarada de reemplazar los manuales escolásticos en las universidades. La primera parte resume la metafísica de las Meditaciones; las tres restantes despliegan una física completa donde la materia se identifica sin resto con la extensión, no hay vacío posible y todo movimiento se explica por contacto mecánico, mediante torbellinos de materia sutil que arrastran los planetas. Es la obra donde el dualismo muestra su rendimiento científico: si el cuerpo es solo extensión y movimiento, la naturaleza entera queda abierta a la geometría. También es donde la física cartesiana resulta más vulnerable, porque Newton la desplazará medio siglo después al introducir una fuerza que actúa a distancia."},
   {t:"Reglas para la dirección del espíritu", d:"Obra temprana e inacabada, escrita hacia 1628 y publicada recién después de su muerte, en la que Descartes intenta formular veintiuna reglas para la investigación y solo llega a redactar dieciocho. Es el laboratorio del método: allí distingue la intuición —la percepción indudable de una mente atenta— de la deducción, entendida como un encadenamiento continuo de intuiciones que la memoria debe recorrer sin saltos. Sostiene además la tesis de la unidad de la ciencia: no hay muchos saberes con métodos distintos sino una sola sabiduría humana, siempre la misma, como la luz del sol no cambia según los objetos que ilumina. Leerla junto al Discurso muestra que las cuatro reglas famosas son la compresión de un proyecto mucho más técnico."},
   {t:"Las pasiones del alma", d:"Su último libro, de 1649, nacido de la correspondencia con la princesa Isabel de Bohemia, que le había exigido explicar cómo puede una sustancia pensante mover un cuerpo extenso. Descartes responde con un tratado mitad fisiológico y mitad moral: describe la circulación de los espíritus animales, sitúa en la glándula pineal el punto de interacción entre alma y cuerpo, clasifica seis pasiones primitivas —admiración, amor, odio, deseo, alegría y tristeza— y sostiene que ninguna es mala en sí. La virtud no consiste en extirpar las pasiones sino en administrarlas mediante la generosidad, el conocimiento del propio libre albedrío unido a la firme resolución de usarlo bien. Es el texto que muestra al Descartes menos glacial y más consciente de que somos un compuesto, no un piloto en su nave."}
 ],
 conceptos:[
   {t:"Duda metódica", d:"No es escepticismo sino su instrumento invertido: el escéptico duda para quedarse en la duda, Descartes duda para salir de ella. La regla es tratar como falso todo aquello en lo que quepa imaginar la menor duda, no porque sea falso sino porque solo así se descubre si queda algo absolutamente firme. Y como examinar creencia por creencia sería un trabajo infinito, ataca los cimientos: derribado el fundamento, cae con él todo lo que se apoyaba encima. Es además una duda declaradamente provisional y teórica, que Descartes separa de la vida práctica mediante su moral provisional, porque en la acción no se puede esperar a la certeza."},
   {t:"Cogito ergo sum", d:"El punto arquimédico que la duda no puede mover: por mucho que un engañador me engañe, no podrá hacer que yo no sea nada mientras piense que soy algo. Descartes insiste en que no se trata de un silogismo con una premisa mayor oculta (todo lo que piensa existe), sino de una intuición inmediata que se capta de un solo golpe de vista. Hay que notar también hasta dónde llega exactamente: la proposición yo soy, yo existo es verdadera cada vez que la pronuncio o la concibo, es decir, dura lo que dura el acto de pensarla. De ahí que el paso siguiente —que ese yo sea una sustancia que persiste mientras duermo o no pienso— sea una tesis adicional, y el blanco preferido de Hume, Lichtenberg y los budistas madhyamaka."},
   {t:"Duda hiperbólica y genio maligno", d:"La duda avanza en tres oleadas de radicalidad creciente. Los sentidos engañan alguna vez, y quien engañó una vez no merece confianza plena; pero el argumento es débil, porque parece locura dudar de que estoy sentado junto al fuego. El sueño va más lejos: no hay señales ciertas para distinguir la vigilia del sueño, así que todo el mundo exterior queda en suspenso, aunque dos más tres sigan siendo cinco incluso soñando. Para alcanzar también la matemática, Descartes introduce la ficción de un genio maligno, no menos astuto que poderoso, que emplea toda su industria en engañarme. Es una hipótesis instrumental y exagerada —hiperbólica— cuya única función es forzar el descubrimiento de algo que resista incluso a ella."},
   {t:"Claridad y distinción", d:"Una vez hallado el cogito, Descartes se pregunta qué tiene esa certeza que las otras no tenían, y responde que la percibe con total claridad y distinción. De ahí extrae su criterio general de verdad: todo lo que concibo muy clara y distintamente es verdadero. Clara es la idea presente y manifiesta a una mente atenta, como un dolor que no se puede ignorar; distinta, la que está tan separada de las demás que no contiene nada que no le pertenezca. La sutileza es que una idea puede ser clara sin ser distinta —el dolor lo es, y por eso lo atribuimos confusamente al cuerpo—, y que el criterio no garantiza nada mientras no se demuestre que su autor no es un engañador."},
   {t:"Dios como garante y el círculo cartesiano", d:"Para validar el criterio de claridad y distinción hace falta eliminar al genio maligno, y para eso Descartes demuestra la existencia de un Dios perfecto: la idea de infinito que encuentro en mí no puede proceder de un ser finito, y un ser perfecto no puede ser engañador, porque engañar delata defecto. Con eso quedan garantizadas la memoria, la deducción y finalmente el mundo exterior. Pero Arnauld formuló ya en las Objeciones la dificultad más célebre de toda la obra: las pruebas de Dios se apoyan en ideas claras y distintas, mientras que la validez de las ideas claras y distintas se apoya en Dios. Descartes replica distinguiendo la intuición actual, que es indubitable mientras se la tiene, del recuerdo de haber demostrado algo, que es lo que necesita el respaldo divino; los lectores siguen discutiendo si eso rompe el círculo o solo lo estrecha."},
   {t:"Res cogitans y res extensa", d:"Sustancia es, para Descartes, aquello que existe sin necesitar ninguna otra cosa para existir, y hay exactamente dos clases creadas, definidas cada una por un atributo principal del que todo lo demás es modo. La res cogitans piensa, es decir, duda, entiende, afirma, niega, quiere, imagina y siente; es indivisible, no ocupa lugar y se conoce mejor a sí misma que a ningún cuerpo. La res extensa tiene longitud, anchura y profundidad, es infinitamente divisible y carece por completo de fines, cualidades sensibles o interioridad. El argumento de la distinción real se apoya en que puedo concebir clara y distintamente una sin la otra, lo que en el sistema basta para que sean realmente separables. La ganancia es enorme para la ciencia —la naturaleza queda enteramente geometrizable— y el costo también, porque a partir de aquí hay que explicar cómo dos cosas sin nada en común pueden afectarse."},
   {t:"Las cuatro reglas del método", d:"Evidencia: no admitir jamás como verdadera ninguna cosa que no se conozca evidentemente como tal, evitando la precipitación y la prevención. Análisis: dividir cada dificultad examinada en tantas partes como sea posible y necesario para resolverla mejor. Síntesis: conducir ordenadamente los pensamientos empezando por los objetos más simples y fáciles de conocer para ascender poco a poco hasta los más compuestos, suponiendo incluso un orden entre aquellos que no se preceden naturalmente. Enumeración: hacer recuentos tan completos y revisiones tan generales que se tenga la seguridad de no omitir nada. Descartes las presenta como la destilación de la geometría y el álgebra en un procedimiento aplicable a cualquier materia, y el punto discutible es exactamente ese: si un método extraído de las matemáticas puede trasladarse sin pérdida a la política, la medicina o la moral."},
   {t:"Ideas innatas, adventicias y facticias", d:"Descartes clasifica las ideas por su origen aparente: adventicias son las que parecen venir de fuera, como el calor del fuego; facticias las que yo mismo fabrico combinando otras, como una sirena o un hipogrifo; innatas las que no proceden ni de los sentidos ni de mi invención, sino que encuentro puestas en mí junto con mi propia facultad de pensar, como las de sustancia, duración, número, triángulo, yo mismo o Dios. Innato no significa consciente desde la cuna: significa que la mente posee la disposición a formarlas sin que ninguna experiencia se las dicte, del mismo modo en que una familia puede tener predisposición a una enfermedad sin padecerla. Esta tesis es el corazón del racionalismo y el blanco directo del primer libro del Ensayo de Locke, que negará que haya en la mente nada que no haya pasado antes por los sentidos."},
   {t:"La glándula pineal y la unión de las sustancias", d:"Si el alma no es extensa y el cuerpo no piensa, ¿cómo puede una decisión mover un brazo? La respuesta técnica de Las pasiones del alma es la glándula pineal, un pequeño órgano central y no duplicado del cerebro donde el alma ejerce sus funciones y desde donde, inclinándose levemente, dirige el curso de los espíritus animales por los nervios. La princesa Isabel de Bohemia le objetó con precisión devastadora que mover algo exige contacto y extensión, de modo que la solución repite el problema en miniatura. Descartes le concede en las cartas algo sorprendente: la unión de alma y cuerpo no se conoce por el entendimiento puro ni por la imaginación, sino por la vida misma y el trato ordinario con las cosas, y él mismo advierte en la Sexta Meditación que no estoy en mi cuerpo como un piloto en su nave, sino estrechísimamente unido y como mezclado con él."}
 ],
 conexion:"El dualismo abre el 'problema mente-cuerpo' que <b>Wittgenstein</b>, siglos después, intentará disolver mostrando que es un malentendido del lenguaje.",
 dialogo:{titulo:"El escéptico junto al fuego", lineas:[
   {quien:"Escéptico", texto:"Usted dice que duda de todo. Pero está sentado junto al fuego, con ese papel en la mano. ¿De verdad duda de eso?"},
   {quien:"Descartes", texto:"De eso precisamente. No porque lo crea falso, sino porque busco algo que resista incluso a la sospecha más exagerada. Y cuántas veces he soñado, de noche, que estaba en este mismo lugar, vestido, junto al fuego, cuando en realidad estaba desnudo en mi cama."},
   {quien:"Escéptico", texto:"Concedido: el mundo puede ser un sueño. Pero aun soñando, dos más tres siguen siendo cinco. Ahí tiene su fundamento."},
   {quien:"Descartes", texto:"Todavía no. Suponga un genio maligno, no menos astuto que poderoso, que ha empleado toda su industria en engañarme: nada le costaría hacer que me equivoque cada vez que sumo, dándome la misma sensación de evidencia."},
   {quien:"Escéptico", texto:"Entonces ya no queda nada. Se quedó sin mundo, sin cuerpo y sin aritmética."},
   {quien:"Descartes", texto:"Queda el que está siendo engañado. Que me engañe cuanto quiera: nunca podrá hacer que yo no sea nada mientras yo piense que soy algo. Esta proposición, yo soy, yo existo, es necesariamente verdadera cada vez que la pronuncio o la concibo."},
   {quien:"Escéptico", texto:"Cada vez que la pronuncia. Dijo bien. ¿Y entre una y otra? ¿Mientras duerme sin soñar, existe usted todavía?", nota:"El escéptico está señalando el límite exacto del cogito: garantiza la existencia durante el acto de pensar, no la de una sustancia que persiste. Hume y Lichtenberg harán de esta objeción su bandera; Lichtenberg dirá que lo único legítimo sería decir se piensa, como se dice llueve."},
   {quien:"Descartes", texto:"Concedo que ahí ya no hablo de lo mismo. Que soy una cosa que piensa lo veo con evidencia; que esa cosa sea una sustancia duradera lo sostengo por otro camino, y quien lo rechace debe atacar ese camino, no el primer paso."},
   {quien:"Escéptico", texto:"Vayamos entonces al camino. Usted se quedó encerrado en su propio pensamiento. ¿Cómo sale de ahí sin volver a confiar en lo que acaba de rechazar?"},
   {quien:"Descartes", texto:"Por Dios. Encuentro en mí la idea de un ser infinitamente perfecto, y yo, que soy finito, no pude fabricarla. Su causa debe tener al menos tanta realidad como la idea. Y un ser perfecto no puede ser engañador, porque el engaño delata defecto. Eliminado el genio, mis ideas claras y distintas vuelven a ser fiables."},
   {quien:"Escéptico", texto:"Ahí lo tengo. Usted prueba a Dios con ideas claras y distintas, y garantiza las ideas claras y distintas con Dios. Eso es un círculo.", nota:"Es la objeción que Arnauld le presentó en vida, en las Cuartas Objeciones, y que desde entonces se llama el círculo cartesiano. La respuesta de Descartes distingue la intuición actual, indudable mientras se la está teniendo, del recuerdo de haber demostrado algo, que sí necesita respaldo divino. Si eso rompe el círculo o solo lo estrecha sigue discutiéndose."},
   {quien:"Descartes", texto:"Mientras veo una demostración, no puedo dudar de ella aunque quiera. La necesidad de Dios aparece después, cuando ya no la tengo delante y solo recuerdo haberla hecho. Es la memoria, no la intuición, lo que pide garantía."},
   {quien:"Escéptico", texto:"Admitamos que recupera el mundo. Pero ahora tiene un problema peor: partió la realidad en dos y quedó con una mente que no ocupa lugar dentro de un cuerpo que solo es extensión. ¿Cómo mueve usted la mano?"},
   {quien:"Descartes", texto:"El alma ejerce sus funciones en una pequeña glándula del centro del cerebro, y desde allí inclina el curso de los espíritus hacia los nervios."},
   {quien:"Escéptico", texto:"Eso no explica nada: mover exige contacto, y el contacto exige extensión. Puso el mismo enigma en un lugar más pequeño. La princesa Isabel ya se lo dijo."},
   {quien:"Descartes", texto:"Y tuve que darle parte de razón. La unión del alma y el cuerpo no se conoce por el entendimiento puro, sino viviéndola. Por eso escribí que no estoy en mi cuerpo como un piloto en su nave, sino unido y como mezclado con él — aunque reconozco que esa frase describe el hecho más de lo que lo explica."}
 ]},
 actividades:[
   {t:"Someter una creencia propia a las tres oleadas", d:"Elegí una creencia que hoy tengas por firme y que importe de verdad (algo sobre tu trabajo, sobre una persona, sobre cómo funciona el mundo). Pasala por escrito por las tres oleadas de la Primera Meditación: qué queda de ella si los sentidos que la apoyan pudieron engañarte; qué queda si toda la escena en que la aprendiste pudo ser un sueño; qué queda si suponés un engañador sistemático. Anotá en qué oleada exacta cae y por qué. Después escribí un párrafo final sobre lo contrario: si no cayó en ninguna, decidí si eso es señal de solidez o señal de que la formulaste de un modo que ninguna evidencia podría refutar."},
   {t:"Las cuatro reglas contra un problema real", d:"Tomá un problema concreto de tu práctica —una unidad didáctica que no funciona, un conflicto de convivencia en un curso, una decisión personal pendiente— y aplicale las cuatro reglas por escrito, una por una: qué admitís sin duda razonable, en qué partes lo dividís, en qué orden ascendés de lo simple a lo compuesto, y qué recuento final hacés para asegurarte de no omitir nada. Al terminar, respondé la pregunta crítica: ¿qué parte del problema quedó fuera porque el método no sabía qué hacer con ella? Descartes prometía un procedimiento universal; tu respuesta es un dato sobre ese alcance."},
   {t:"Cartas entre Descartes e Isabel", d:"Escribí el intercambio en tres cartas breves. Primera: Isabel le pregunta cómo una sustancia que no es extensa puede determinar los espíritus corporales a moverse, insistiendo en que mover parece exigir contacto. Segunda: Descartes responde con la glándula pineal y la noción primitiva de la unión. Tercera: Isabel replica que no entiende la unión mejor que antes, y que le resultaría más fácil atribuir materia al alma que atribuir a algo inmaterial la capacidad de mover un cuerpo. Cerrá con un párrafo tuyo indicando cuál de las dos posiciones tomarías hoy, y con qué versión contemporánea del problema (fisicalismo, funcionalismo, dualismo de propiedades) la identificarías."}
 ],
 cuestionario:[
   {q:"El cogito garantiza que existo mientras dudo. ¿Garantiza también que soy la misma cosa que piensa mañana?", p:"Descartes salta de hay pensamiento a soy una sustancia persistente, y ese segundo paso no lo da la intuición del cogito sino su teoría de la sustancia. Hume responderá que al buscar ese yo solo encuentra percepciones sueltas, y Lichtenberg que lo único legítimo sería decir se piensa, como se dice llueve; el madhyamaka llega por otro camino a una conclusión parecida."},
   {q:"Si el criterio de verdad es la claridad y la distinción, ¿por qué hace falta demostrar además que Dios existe?", p:"Porque mientras no se descarte al genio maligno, la sensación de evidencia podría ser precisamente el modo del engaño: el criterio sería psicológicamente irresistible y metafísicamente vacío. El problema es que la demostración de Dios usa ese mismo criterio, lo que Arnauld denunció como círculo. La salida cartesiana —distinguir la intuición actual del recuerdo de la demostración— vale la pena discutirla en detalle, porque de ella depende que todo el edificio se sostenga o no."},
   {q:"Descartes afirma que puede concebir claramente su mente sin su cuerpo, y concluye que son realmente distintos. ¿Se sigue lo segundo de lo primero?", p:"Ese paso supone que lo concebible con claridad indica lo realmente posible, y que mi concepción de mí mismo es completa y no meramente parcial. Arnauld objetó con un ejemplo geométrico: alguien puede concebir un triángulo rectángulo sin concebir el teorema de Pitágoras, y sin embargo no son separables. Toda la discusión contemporánea sobre argumentos modales en filosofía de la mente —incluidos los zombis de Chalmers— sigue girando en torno a esta misma inferencia."},
   {q:"Si el cuerpo es pura extensión y movimiento, ¿qué pasa con el dolor, el hambre o el miedo, que no son ni pensamiento puro ni pura geometría?", p:"Descartes lo admite como un caso aparte: esas sensaciones no las tengo como un piloto que observa una avería en su nave, sino confusamente, porque estoy unido y como mezclado con mi cuerpo. Pero eso introduce una tercera noción primitiva, la unión, que no se deja reducir a ninguna de las dos sustancias. Sus críticos —empezando por Isabel de Bohemia— sostienen que ahí el sistema reconoce un hecho que no puede explicar."},
   {q:"La duda metódica es teórica y no afecta a la vida práctica, para la cual Descartes adopta una moral provisional. ¿Es una separación honesta o una manera de blindar la filosofía?", p:"Descartes argumenta que la acción no puede esperar a la certeza y que sería imprudente destruir la casa donde uno vive antes de tener otra. Dewey replicará que una duda que no nace de una situación real es artificial y no mueve ninguna investigación genuina. La pregunta interesante es si puede sostenerse una duda que uno mismo declara inoperante fuera del escritorio, y qué diferencia hay entre eso y no dudar."}
 ],
 cadena:{ titulo:"¿Hasta dónde llega el cogito?", intro:"A partir de la Segunda Meditación y de la pregunta que el escéptico le deja a Descartes en el diálogo: el cogito resiste al genio maligno, pero ¿qué prueba exactamente? Cada rama explora un límite distinto de esa certeza; ninguna es un callejón sin salida.", inicio:"n1", nodos:{
   n1:{ pregunta:"Suponé al genio maligno en plena actividad: todo lo que creés sobre el mundo, tu cuerpo y la aritmética podría ser un engaño. Pensás: «pienso, luego existo». ¿Qué te garantiza exactamente esa certeza?", opciones:[
     {texto:"Que existo ahora, mientras lo estoy pensando.", va:"n2a"},
     {texto:"Que existo como una cosa que piensa: una mente, distinta de un cuerpo.", va:"n2b"} ]},
   n2a:{ pregunta:"Descartes lo formula así: yo soy, yo existo, es verdadero cada vez que lo pronuncio o lo concibo; y agrega que quizás, si dejara de pensar, dejaría de existir (Med. II). Ahora bien: recordás que hace cinco minutos también estabas pensando. ¿El cogito te garantiza que eras vos, el mismo, hace cinco minutos?", opciones:[
     {texto:"Sí: recuerdo claramente haber pensado, y ese recuerdo es mío.", va:"n3a"},
     {texto:"No: el cogito vale para el acto presente. Que haya un sujeto que dura es otra tesis.", va:"n3b"} ]},
   n3a:{ pregunta:"Pero el recuerdo es justo lo que el genio maligno podría falsificar: nada le costaría ponerte ahora la sensación de haber pensado hace cinco minutos. ¿Qué te queda para confiar en tu memoria?", opciones:[
     {texto:"Nada, mientras el genio no esté descartado: necesito algo que garantice que mis facultades no me engañan de manera sistemática.", final:{tipo:"bien", texto:"Llegaste a la estructura exacta de la Tercera y la Quinta Meditación: la intuición presente se sostiene sola, pero todo lo que depende de la memoria —incluidas las demostraciones largas, que no pueden abarcarse de un solo golpe de vista— necesita la garantía de un Dios que no engaña. Es la respuesta de Descartes a Arnauld sobre el círculo: la memoria, no la intuición, es la que pide respaldo. Y ahora ves el precio completo: sin Dios, ni siquiera tu propia continuidad en el tiempo está asegurada."}},
     {texto:"La viveza del recuerdo: un recuerdo tan nítido no puede ser falso.", final:{tipo:"revisar", texto:"Descartes no acepta la viveza como criterio: los sueños también son vívidos, y justamente por eso la Primera Meditación los usa para derribar la confianza en los sentidos. La viveza es un rasgo psicológico de una representación; lo que Descartes busca es algo que resista incluso la hipótesis de un engaño total. Volvé un paso y pensá qué haría falta para confiar en tus facultades en general, no en este recuerdo en particular."}} ]},
   n3b:{ pregunta:"Entonces el cogito, en sentido estricto, te da algo como «hay pensamiento ahora». Lichtenberg irá más lejos: ni siquiera eso autoriza el «yo»; habría que decir «se piensa», como se dice «llueve». ¿Aceptás esa corrección?", opciones:[
     {texto:"Sí: el «yo» es un agregado de la gramática. Lo único indudable es que ocurre un pensamiento.", final:{tipo:"bien", texto:"Es la posición de Lichtenberg y, por otro camino, la de Hume, que al buscar dentro de sí solo encuentra percepciones sueltas y ningún yo. Kant la retomará con más cuidado: el «yo pienso» es la condición formal que acompaña a todas mis representaciones, no la intuición de una sustancia, y deducir de él una sustancia es un paralogismo. Llegaste a una conclusión más austera que la de Descartes y probablemente más fácil de defender. Su costo: con un «se piensa» anónimo cuesta reconstruir un sujeto que conoce, recuerda y responde por sus actos, que era precisamente lo que Descartes quería fundar."}},
     {texto:"No: no puede haber un pensamiento sin alguien que lo piense.", va:"n4b"} ]},
   n4b:{ pregunta:"Es lo que responde Descartes: es evidente por la luz natural que la nada no tiene propiedades, de modo que donde hay pensamiento hay una cosa que piensa (Principios I.11). Pero fijate qué clase de principio acabás de usar. ¿De dónde viene su certeza?", opciones:[
     {texto:"Es una verdad de razón evidente por sí misma, como que para pensar hay que existir.", final:{tipo:"bien", texto:"Es la respuesta cartesiana, y es coherente: en los Principios (I.10) Descartes admite que el cogito presupone nociones comunes como «para pensar hay que existir», aunque niega que funcionen como premisa mayor de un silogismo. Pero notá lo que eso implica: el cogito ya no está absolutamente solo; se apoya en axiomas generales, y esos axiomas son ideas claras y distintas, las mismas que el genio maligno podría poner en duda. Acabás de ver por qué el problema del círculo aparece antes de lo que parece, ya en la segunda página de la Segunda Meditación."}},
     {texto:"De la gramática: todo verbo necesita un sujeto.", final:{tipo:"revisar", texto:"Si la certeza viniera de la gramática, Lichtenberg tendría toda la razón: «llueve» tiene verbo y nadie que llueva. Descartes no puede apoyarse en la forma de una oración, porque la duda alcanzó incluso a la matemática; mucho menos resistiría una convención del idioma. Si hay salida cartesiana, está en la luz natural, no en la sintaxis. Volvé y probá la otra respuesta."}} ]},
   n2b:{ pregunta:"Descartes da ese paso en la misma Segunda Meditación: soy una cosa que piensa, es decir, que duda, entiende, afirma, niega, quiere, imagina y siente. Pero en este punto del recorrido, ¿sabés ya que no sos también un cuerpo?", opciones:[
     {texto:"No: por ahora solo sé que pienso; no sé si lo que piensa es además algo extenso.", va:"n3c"},
     {texto:"Sí: puedo dudar de que tengo cuerpo pero no de que tengo mente, así que son cosas distintas.", final:{tipo:"revisar", texto:"Es la inferencia que muchos le atribuyen a Descartes y que él evita cuidadosamente en la Segunda Meditación: de «puedo dudar de X pero no de Y» no se sigue que X no sea Y. Alguien puede dudar de que el lucero del atardecer sea Venus sin dudar de que Venus es Venus, y sin embargo son lo mismo. Descartes lo sabía: en el prefacio al lector aclara que en ese punto no excluía que el cuerpo le perteneciera, y deja la distinción real para la Sexta Meditación, con otro argumento. Volvé y seguí la otra rama."}} ]},
   n3c:{ pregunta:"Exacto: la distinción real llega en la Sexta Meditación y con otro argumento. Puedo concebir clara y distintamente mi mente sin mi cuerpo; todo lo que concibo clara y distintamente puede ser producido por Dios tal como lo concibo; luego mente y cuerpo pueden existir separados, y son realmente distintos. ¿Te convence?", opciones:[
     {texto:"Solo si concebir algo con claridad como separado prueba que puede existir separado.", final:{tipo:"bien", texto:"Identificaste la premisa que carga todo el peso: el paso de la concebibilidad a la posibilidad real. Arnauld la atacó en las Cuartas Objeciones con un triángulo rectángulo: se lo puede concebir con claridad sin concebir que el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos, y sin embargo esa propiedad es inseparable de él. Descartes respondió que su concepción de la mente es completa y la del triángulo no. Si esa réplica funciona sigue siendo el nudo de la discusión actual sobre argumentos modales, incluidos los zombis de Chalmers."}},
     {texto:"No: el hambre o el dolor me muestran que estoy mezclado con el cuerpo, no alojado en él.", final:{tipo:"bien", texto:"Es la objeción que el propio Descartes se formula en la Sexta Meditación, y la que Isabel de Bohemia le devolvió con precisión: si yo estuviera en mi cuerpo como un piloto en su nave, al herirme percibiría la herida con el entendimiento, como el piloto ve una avería, y no sentiría dolor. Descartes no abandona la distinción real, pero agrega una tercera noción primitiva, la unión, que se conoce viviéndola y no por el entendimiento puro. Llegaste por la experiencia al punto exacto donde el dualismo reconoce un hecho que no termina de explicar."}} ]}
 }},
 reconstruccion:[
   { titulo:"La idea de Dios y su causa (Tercera Meditación)",
     consigna:"Reconstruí el argumento causal con el que Descartes sale del cogito hacia Dios. Una pieza pertenece a la otra prueba de Dios de las Meditaciones: dejala afuera y ordená el resto.",
     piezas:[
       {id:"d1", texto:"Busco entre mis ideas alguna que no haya podido producir yo mismo, y encuentro la idea de Dios: una sustancia infinita, eterna, omnisciente y omnipotente.", tipo:"premisa"},
       {id:"d2", texto:"Ahora bien, es evidente por la luz natural que tiene que haber al menos tanta realidad en la causa eficiente y total como en su efecto: ¿de dónde sacaría el efecto su realidad si no de su causa?", tipo:"premisa"},
       {id:"d3", texto:"Este principio vale también para las ideas: lo que una idea representa —su realidad objetiva— exige una causa que tenga efectivamente al menos tanta realidad como la representada.", tipo:"premisa"},
       {id:"d4", texto:"Pero yo soy finito: dudo y deseo, y eso muestra que algo me falta. No puedo ser, entonces, la causa de la idea de un ser infinitamente perfecto.", tipo:"premisa"},
       {id:"d5", texto:"Por lo tanto, la causa de esa idea es un ser que tiene realmente toda la perfección que ella representa: Dios existe.", tipo:"conclusion"},
       {id:"dx", texto:"La existencia está contenida en la esencia de un ser sumamente perfecto, del mismo modo que en la esencia del triángulo está contenido que sus ángulos sumen dos rectos.", tipo:"distractor"}
     ],
     ordenCorrecto:["d1","d2","d3","d4","d5"],
     explicacion:"El argumento necesita dos cosas: un principio causal general (d2) y su extensión a las ideas mediante la distinción entre realidad objetiva, lo que una idea representa, y realidad formal, lo que algo es efectivamente (d3). Con eso, la idea de infinito se vuelve un efecto que un ser finito no alcanza a explicar (d4). La pieza sobrante es el argumento ontológico de la Quinta Meditación, que no pasa por ninguna causa: deduce la existencia de la esencia. Dos objeciones para discutir: el empirista dirá que formamos la idea de infinito negando lo finito, y Descartes responde que es al revés, que me sé finito porque ya tengo la idea de lo perfecto; y d2 es él mismo un principio claro y distinto, de modo que el argumento que debe garantizar la claridad y distinción la está usando, que es el núcleo del círculo cartesiano."},
   { titulo:"El trozo de cera (Segunda Meditación)",
     consigna:"Reconstruí el argumento de la cera, que muestra por qué hasta los cuerpos se conocen con el entendimiento y no con los sentidos. Una pieza pertenece a la Primera Meditación: dejala afuera.",
     piezas:[
       {id:"c1", texto:"Tomo un trozo de cera recién sacado del panal: conserva el sabor de la miel y el olor de las flores, tiene color, forma y tamaño; es duro, está frío y suena si lo golpeo.", tipo:"premisa"},
       {id:"c2", texto:"Lo acerco al fuego: el sabor y el olor se van, el color cambia, la forma se pierde, se vuelve líquido y caliente, ya no suena. Y sin embargo sigue siendo la misma cera.", tipo:"premisa"},
       {id:"c3", texto:"Luego lo que conocía de ella no era nada de lo que captaban los sentidos, porque todo eso cambió y la cera permanece.", tipo:"premisa"},
       {id:"c4", texto:"Tampoco la conozco por la imaginación, porque la cera es capaz de infinitos cambios de forma que nunca podría recorrer imaginándolos uno por uno.", tipo:"premisa"},
       {id:"c5", texto:"Por lo tanto, la cera se percibe solo por una inspección de la mente; y si así conozco un cuerpo, conozco todavía con más claridad mi propia mente, que es la que lo conoce.", tipo:"conclusion"},
       {id:"cx", texto:"Los sentidos me engañaron alguna vez, y no es prudente confiar del todo en quien nos engañó aunque sea una sola vez.", tipo:"distractor"}
     ],
     ordenCorrecto:["c1","c2","c3","c4","c5"],
     explicacion:"El argumento no busca probar que existen los cuerpos —eso llega recién en la Sexta Meditación— sino mostrar qué es conocer uno: lo que permanece a través del cambio (extensión, flexibilidad, mutabilidad) no es un dato sensible sino algo que capta el entendimiento. El remate cumple el título de la meditación: la mente es más fácil de conocer que el cuerpo, porque cada acto de conocer la cera confirma, además, que hay una mente que conoce. La pieza sobrante es la primera oleada de la duda, de la Primera Meditación: desconfía de los sentidos, pero no dice qué los reemplaza. Objeción para discutir, que ya le hizo Gassendi en las Quintas Objeciones: quizás lo que reconocemos como «la misma cera» no es una esencia captada por la mente sino la continuidad perceptiva del cambio, y el argumento presupone el concepto de sustancia que quería mostrar."}
 ],
 dilemas:[
   { titulo:"La evidencia que sospecha de sí misma",
     intro:"Para Descartes, todo lo que se percibe con total claridad y distinción es verdadero, y el error nace cuando la voluntad afirma más allá de lo que el entendimiento ve con claridad (Cuarta Meditación). Este caso pone a prueba ese criterio con una convicción que se siente evidente y quizás no lo es.",
     pasos:[
       { id:"p1", situacion:"Corregís el ensayo final de Tomás, un estudiante que entregó trabajos flojos todo el año. Este es excelente: argumentado, preciso, con un vocabulario que nunca le escuchaste. Se te impone una convicción inmediata y muy fuerte: no lo escribió él. No encontrás ninguna fuente copiada. ¿Qué hacés con esa convicción?", opciones:[
         {texto:"La trato como evidente: la veo con total claridad, y la claridad es mi criterio.", consecuencia:"Descartes te pediría que separes dos cosas que en la experiencia se confunden: la fuerza con que una idea se impone y su claridad y distinción. Clara es la idea presente a una mente atenta; distinta, la que no contiene nada que no le pertenezca. Tu convicción mezcla un dato (el salto de calidad) con una hipótesis (que no lo escribió él) y con algo más: lo que ya pensabas de Tomás. Eso es lo que la primera regla del método llama precipitación y prevención.", va:"p2a"},
         {texto:"Suspendo el juicio: si puedo imaginar un motivo para dudar, no la tomo como cierta.", consecuencia:"Aplicaste la regla de la Primera Meditación: tratar provisoriamente como falso lo que admita la menor duda. Pero Descartes separa esa duda teórica de la acción: la moral provisional existe porque en la vida hay que decidir antes de tener certeza. Y la nota tiene que salir el viernes.", va:"p2b"} ]},
       { id:"p2a", situacion:"Convocás a Tomás y le decís que sospechás que no escribió el ensayo. Se pone pálido y no logra explicar bien dos conceptos del texto. Tu convicción se vuelve todavía más intensa. ¿Eso la confirma?", opciones:[
         {texto:"Sí: su reacción y su falta de explicación son pruebas adicionales.", consecuencia:"Son datos, pero ambiguos: la palidez y la torpeza también son lo que produce una acusación en alguien que no la esperaba, y más si sabe que el docente lo considera flojo. Descartes diría que la voluntad, que es amplísima, se adelantó al entendimiento, que es limitado: afirmaste más de lo que percibías con claridad. Es su explicación del error en la Cuarta Meditación, y la tenés delante.", va:"p3"},
         {texto:"No necesariamente: mi convicción se intensificó, pero la intensidad no es evidencia.", consecuencia:"Es la distinción cartesiana en acción. El error no nace del entendimiento, que solo percibe, sino de la voluntad, que afirma. Que una creencia se vuelva más fuerte no la vuelve más clara: puede volverse más fuerte precisamente porque la estás defendiendo.", va:"p3"} ]},
       { id:"p2b", situacion:"Suspendés el juicio, pero la nota tiene que salir. Descartes tiene para esto una moral provisional: seguir las opiniones más moderadas de las personas más sensatas y, una vez decidido, ser firme, como el viajero perdido en un bosque que camina siempre en línea recta (Discurso, III). ¿Cómo la aplicás?", opciones:[
         {texto:"Pongo la nota que el ensayo merece y le pido a Tomás una defensa oral del trabajo, como a todos los demás.", consecuencia:"Encontraste una manera de actuar que no presupone la conclusión de la que dudás y que además produce evidencia nueva sin acusar a nadie. Es un uso fino de la moral provisional: decidir bajo incertidumbre sin fingir certeza. Y al aplicarlo a todos eliminaste la prevención: el trato especial a Tomás era parte del problema.", va:"p3"},
         {texto:"Pongo una nota intermedia: ni la que merece el ensayo ni un aplazo.", consecuencia:"Es «moderado» en un sentido literal, pero Descartes habla de seguir las opiniones de los más sensatos, no de promediar entre dos juicios. Una nota intermedia no es neutral: castiga una sospecha que no pudiste probar y premia de menos un trabajo que quizás es suyo. La moderación del Discurso es prudencia sobre qué creer, no un punto medio entre certezas.", va:"p3"} ]},
       { id:"p3", situacion:"Semanas después se aclara todo: Tomás escribió el ensayo él mismo, después de meses de trabajo con un tutor que le enseñó a argumentar. Tu convicción inicial, tan evidente, era falsa. ¿Qué concluís sobre tu criterio?", opciones:[
         {texto:"Que la claridad no sirve como criterio: me engañó.", consecuencia:"Es la conclusión escéptica, y Descartes la rechazaría por una razón precisa: lo que tuviste no era una idea clara y distinta sino una idea fuerte y confusa. Su criterio nunca fue «lo que siento como evidente es verdadero». Aun así tu objeción tiene fuerza: si desde adentro no puedo distinguir la claridad genuina de la aparente, ¿de qué me sirve el criterio? Es la crítica de Leibniz, y no es menor.", va:null},
         {texto:"Que tomé por claro y distinto algo que no lo era: mezclé lo que veía con lo que ya pensaba de él.", consecuencia:"Es la lectura cartesiana del error: no falló el criterio sino su aplicación, porque la voluntad afirmó antes de que el entendimiento distinguiera. El remedio de la Cuarta Meditación no es desconfiar de toda evidencia sino adquirir el hábito de no juzgar más que sobre lo que se percibe con claridad. Queda la pregunta incómoda: ¿cómo sabrás, la próxima vez, que no estás en el mismo caso?", va:null},
         {texto:"Que el prejuicio sobre Tomás fue la verdadera fuente del error.", consecuencia:"Descartes lo llamaría prevención, y la contaría entre las causas principales del error: los juicios formados por costumbre, antes de examinarlos, que después confundimos con evidencias (Principios I.71). Lo instructivo es que el prejuicio no se sentía como prejuicio: se sentía como algo que se veía con claridad. Esa es la lección más útil del caso.", va:null} ]}
     ],
     rubrica:[
       "En cada paso distinguí entre la fuerza con que una convicción se me imponía y su claridad y distinción en sentido cartesiano.",
       "Separé los datos que percibía (el salto de calidad, la reacción de Tomás) de las hipótesis que les agregaba.",
       "Identifiqué qué papel jugaron la precipitación y la prevención, las dos fuentes de error de la primera regla del método.",
       "Puedo explicar con este caso la teoría del error de la Cuarta Meditación: una voluntad que afirma más allá de lo que el entendimiento ve.",
       "Distinguí la duda teórica de la necesidad práctica de decidir, y usé la moral provisional de manera pertinente.",
       "Formulé la objeción más fuerte al criterio: que desde adentro puede no haber diferencia entre claridad genuina y claridad aparente.",
       "Revisé si mi decisión trataba a Tomás como trataría a cualquier otro estudiante en la misma situación."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.descartes = { lecturas:[
 {titulo:"Meditaciones metafísicas I y II: la duda y el cogito", fuente:"Internet Archive — Descartes, Meditaciones metafísicas y otros textos (Gredos)", url:"https://archive.org/details/rene-descartes-meditaciones-metafisicas-y-otros-textos-editorial-gredos-1991",
  extracto:`La Primera Meditación no duda de cada creencia una por una — Descartes aclara que eso sería «un trabajo infinito». Su estrategia es atacar los fundamentos: «bastará que encuentre en cada una alguna razón de duda para rechazarlas todas». Procede en tres oleadas de escepticismo, cada una más radical.

Primero, los sentidos: «todo lo que he admitido hasta ahora como más seguro y verdadero lo he aprendido de los sentidos o por los sentidos; ahora bien, he experimentado a veces que esos sentidos eran engañosos, y es prudente no fiarse nunca por entero de quienes nos han engañado una vez». Pero objeta él mismo que el engaño sensorial típico ocurre en condiciones desfavorables —objetos lejanos o pequeños— y que sería locura dudar de que estoy aquí, sentado junto al fuego, con este papel en las manos.

Segundo, el sueño: «cuántas veces me ha ocurrido soñar, por la noche, que estaba en este lugar, vestido, junto al fuego, cuando en realidad estaba desnudo en mi cama». Y la conclusión inquietante: «no hay indicios concluyentes ni señales bastante ciertas para distinguir claramente la vigilia del sueño». Esto derriba todas las creencias sobre el mundo exterior, pero Descartes nota que aun en sueños dos más tres siguen siendo cinco y un cuadrado sigue teniendo cuatro lados: la aritmética y la geometría parecen sobrevivir.

Tercero, el genio maligno. Para derribar también eso, Descartes supone «no un Dios óptimo, fuente soberana de verdad, sino cierto genio maligno, no menos astuto y burlador que poderoso, que ha empleado toda su industria en engañarme». Bajo esa hipótesis, hasta las verdades matemáticas podrían ser una ilusión implantada. La duda es ahora total — y es, subraya Descartes, deliberada y metódica, no una desesperación real: «no es que imite a los escépticos, que dudan por dudar».

La Segunda Meditación encuentra el punto fijo. Si el genio me engaña constantemente, «que me engañe cuanto quiera, nunca podrá hacer que yo no sea nada mientras yo piense que soy algo». De ahí la formulación: «esta proposición, yo soy, yo existo, es necesariamente verdadera cuantas veces la pronuncio o la concibo en mi espíritu». Nótese que la certeza es momentánea y ligada al acto de pensar.

La pregunta siguiente es qué es ese yo. Descartes descarta el cuerpo (podría ser ilusión del genio) y llega a: «una cosa que piensa. ¿Y qué es una cosa que piensa? Es una cosa que duda, que entiende, que afirma, que niega, que quiere, que no quiere, que imagina también y que siente». El pasaje de la cera cierra la meditación mostrando que ni siquiera el conocimiento de un cuerpo concreto viene de los sentidos: la cera cambia de color, forma, olor y estado al acercarse al fuego, y sin embargo la juzgamos la misma cera — lo cual solo puede hacerlo «una inspección del espíritu», no la vista ni el tacto.`,
  comentario:"Las tres oleadas de duda son el andamiaje completo del racionalismo: cada una elimina una fuente de certeza hasta dejar solo la que no puede eliminarse. Fijate en el pasaje de la cera — es allí, no en el cogito, donde Descartes gana su tesis de que el entendimiento conoce mejor que los sentidos. Y observá lo que el cogito NO prueba: que ese yo sea una sustancia que persiste en el tiempo, exactamente el salto que Hume y Nagarjuna atacarán."}
], preguntasLectura:[
 {q:"¿Por qué Descartes no duda de sus creencias una por una?", opciones:["Porque sería un trabajo infinito; ataca los fundamentos","Porque confía en la mayoría de ellas","Porque el genio maligno se lo impide","Porque la Iglesia lo prohibía"], r:"Porque sería un trabajo infinito; ataca los fundamentos", why:"Es el método explícito de la Primera Meditación: socavar los cimientos derriba todo el edificio."},
 {q:"¿Qué tipo de conocimiento sobrevive al argumento del sueño pero no al del genio maligno?", opciones:["El testimonio de otros","Las verdades matemáticas y geométricas","La existencia del propio cuerpo","La percepción de objetos cercanos"], r:"Las verdades matemáticas y geométricas", why:"Aun soñando, dos más tres son cinco; solo el genio maligno puede poner eso en duda."},
 {q:"Según la Segunda Meditación, ¿qué muestra el ejemplo de la cera?", opciones:["Que los sentidos son infalibles","Que conocemos los cuerpos por una inspección del espíritu, no por los sentidos","Que la cera no existe","Que el calor destruye la sustancia"], r:"Que conocemos los cuerpos por una inspección del espíritu, no por los sentidos", why:"Todas las cualidades sensibles cambian y seguimos juzgando que es la misma cera: eso lo hace el entendimiento."}
]};
