/* ============================================================
   Ficha: heidegger  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"heidegger", trad:"europea", nombre:"Martin Heidegger", fechas:"1889–1976 · Alemania", escuela:"Fenomenología existencial", icon:"🌫️", profundizada:true,
 tesis:"La filosofía occidental preguntó incansablemente por los entes —qué cosas hay, de qué están hechas, cómo se ordenan— y dejó sin plantear la pregunta previa: qué queremos decir cuando decimos que algo es. A ese descuido lo llama el olvido del ser, y su reparación exige un rodeo: interrogar primero al único ente para quien su propio ser es un problema, el Dasein, ese ser-ahí que ya está siempre arrojado en un mundo de significados, ocupándose de cosas y de otros. El análisis muestra que la existencia cotidiana transcurre normalmente en el modo impropio del «uno» impersonal, y que solo la angustia y la anticipación de la propia muerte pueden devolverle al Dasein la posibilidad de asumir su tiempo finito como suyo. En su obra tardía el mismo diagnóstico se vuelve hacia la técnica moderna, entendida no como un conjunto de máquinas sino como un modo de desocultar el mundo que convierte todo, incluido el ser humano, en existencia disponible.",
 obras:[
   {t:"Ser y tiempo", d:"Publicada en 1927 y dedicada a Husserl en señal de veneración y amistad, es el libro que reorganizó la filosofía continental del siglo XX y también uno de los grandes inacabados de la historia: de las dos partes proyectadas —seis secciones en total— Heidegger publicó apenas dos, y la sección decisiva sobre tiempo y ser nunca apareció. Lo que sí está es una analítica existencial del Dasein desplegada con un vocabulario deliberadamente nuevo, porque Heidegger sostiene que las palabras heredadas —sujeto, conciencia, yo, alma— ya traen incorporado el esquema cartesiano que quiere desarmar. El recorrido va del ser-en-el-mundo y el análisis del útil a la caída en el «uno», la angustia, el cuidado (Sorge) como sentido unitario de la estructura, el ser-para-la-muerte, la conciencia y la resolución, hasta la temporalidad como horizonte desde el cual se comprende el ser. Que el libro se interrumpa justo antes de responder su propia pregunta no es un accidente editorial: Heidegger llegó a considerar que el lenguaje de la metafísica no daba para decir lo que quería decir, y ese fracaso reconocido es el origen de su giro posterior. En español la traducción de referencia es la de Jorge Eduardo Rivera, que fija buena parte del vocabulario castellano del heideggerianismo."},
   {t:"¿Qué es metafísica?", d:"Lección inaugural pronunciada en Friburgo en 1929, ante todas las facultades reunidas, y pensada como una provocación calculada: ante un auditorio de científicos, Heidegger elige preguntar por aquello de lo que la ciencia no quiere saber nada, la Nada. Su punto de partida es que cada ciencia estudia una región de entes y nada más, y que ese «nada más» no es un giro retórico sino un indicio. La Nada no se alcanza por negación lógica —negar supone ya tener algo delante— sino en un temple de ánimo fundamental, la angustia, donde el conjunto de los entes se hunde en la insignificancia y queda al descubierto que hay ente y no más bien nada. De ahí su tesis más citada y más maltratada, la Nada nadea (das Nichts nichtet), que Rudolf Carnap eligió en 1932 como ejemplo perfecto de pseudoproposición sin sentido, abriendo con ello una de las fracturas más duraderas entre filosofía analítica y continental. Leída hoy, la conferencia es la mejor entrada breve a Heidegger: en veinte páginas conecta angustia, finitud y la pregunta por el ser, y muestra por qué considera que la metafísica no es una disciplina académica sino un acontecimiento del Dasein mismo."},
   {t:"Carta sobre el humanismo", d:"Escrita en 1946 como respuesta a una pregunta de Jean Beaufret —cómo devolver un sentido a la palabra humanismo— y publicada en 1947, es el texto que marca públicamente el giro (Kehre) de su pensamiento y su deslinde frontal del existencialismo francés. Sartre había proclamado que en el ser humano la existencia precede a la esencia y que eso era un humanismo; Heidegger responde que la fórmula, aun invertida, sigue siendo una tesis metafísica, porque sigue determinando al ser humano desde el par esencia/existencia en vez de pensarlo desde el ser. Allí introduce sus imágenes más conocidas: el lenguaje es la casa del ser, y el ser humano es el pastor del ser, no su señor ni su fabricante. También reformula lo que en Ser y tiempo se decía desde el Dasein: ya no es el Dasein el que proyecta sentido, es el ser el que se destina y el ser humano el que corresponde. El texto tiene además una dimensión biográfica insoslayable: es su primera intervención pública de peso después de la derrota alemana y de su suspensión de la docencia, y sus críticos señalan que en él rechaza el humanismo sin decir una palabra sobre lo que acababa de ocurrir."},
   {t:"El origen de la obra de arte", d:"Conferencias de 1935 y 1936, recogidas después en Caminos de bosque, donde Heidegger aplica su pregunta por el ser al arte y obtiene una de sus tesis más productivas fuera de la filosofía. Su planteo arranca de un círculo confeso: la obra sale del artista, pero el artista es artista por la obra, así que hay que entrar en el círculo en lugar de evitarlo. Contra la estética entendida como teoría de la vivencia del espectador, sostiene que la obra no representa ni decora: pone en obra la verdad, entendida como alétheia, desocultamiento. El análisis de un cuadro de Van Gogh con un par de zapatos de labriego y el del templo griego que, al erguirse, hace aparecer por primera vez la roca, la tormenta y el mundo del pueblo ilustran su fórmula central: la obra abre un mundo y a la vez deja emerger la tierra, ese fondo que se cierra y se niega a ser agotado por el sentido. Esa tensión entre mundo y tierra es para él el modo de ser de la obra. El texto arrastra una controversia célebre: Meyer Schapiro demostró documentalmente que los zapatos del cuadro eran del propio Van Gogh, un hombre de ciudad, y no de ninguna campesina, y Derrida convirtió después esa disputa en un ensayo sobre lo que Heidegger proyectó sobre la pintura sin mirarla."},
   {t:"La pregunta por la técnica", d:"Conferencia de 1953, reelaboración de un ciclo anterior de Bremen, y probablemente el texto suyo con más vigencia pública hoy. Su primera advertencia es metodológica: la esencia de la técnica no es nada técnico, de modo que ni un inventario de máquinas ni la definición corriente —la técnica es un medio para fines humanos— tocan el problema, aunque ambas sean correctas. Heidegger recupera la palabra griega téchne, que nombraba a la vez el arte y el oficio y era un modo de hacer aparecer algo, y muestra que la técnica moderna desoculta de otra manera: no cultiva ni acompaña, provoca y emplaza. El molino antiguo se entregaba al viento; la central hidroeléctrica emplaza al Rin a entregar energía, y el propio río pasa a ser un elemento del sistema, hasta el punto de que después reaparece como paisaje encargado a la industria del turismo. A ese modo de desocultar lo llama Gestell, y su rasgo peligroso no es la destrucción ni el riesgo tecnológico sino que todo, la naturaleza y también las personas, quede convertido en existencia disponible (Bestand), material a mano y calculable. El texto no propone rechazar la técnica ni volver atrás: cita a Hölderlin —donde está el peligro crece también lo que salva— y busca una relación libre con ella, que él llama serenidad (Gelassenheit) y que consiste en decir sí y no a la vez a los artefactos, usándolos sin dejar que definan lo que las cosas son."}
 ],
 conceptos:[
   {t:"Dasein", d:"Heidegger deja el término sin traducir en casi todas las lenguas porque su composición hace el trabajo: Da-sein es ser-ahí, y ese ahí no es una ubicación en el espacio sino la apertura misma en la que las cosas pueden mostrarse. Dasein no significa ser humano ni persona ni sujeto; nombra un modo de ser, el de aquel ente al que, en su ser, le va este mismo ser, según la fórmula que fija la traducción de Rivera. Dos consecuencias se siguen de inmediato. La primera es que el Dasein no tiene una esencia previa que después se realice: su esencia consiste en su existencia, es decir, en las posibilidades que asume o rehúye, de modo que no se lo describe con propiedades como a una piedra sino con modos de existir. La segunda es que no se pregunta por él como por un objeto interior, porque el Dasein ya está siempre afuera, ocupado con cosas y con otros. Heidegger evita a propósito el vocabulario de la conciencia porque toda la tradición que va de Descartes a Husserl empieza poniendo un sujeto de un lado y un mundo del otro, y la analítica existencial se propone mostrar que ese punto de partida ya es una abstracción de algo más originario."},
   {t:"Ser-en-el-mundo (In-der-Welt-sein)", d:"Es la estructura unitaria que reemplaza al par sujeto/objeto, y Heidegger insiste en escribirla con guiones para que no se la lea como tres piezas ensambladas. No se trata de que yo esté en el mundo como el agua está en el vaso o la silla en el aula: esa es la relación entre dos entes ante-los-ojos. El «en» que le interesa es el de habitar, estar familiarizado con, entender de algo, el mismo que usamos al decir que alguien está en la docencia o en el duelo. El mundo, a su vez, no es la suma de las cosas existentes sino una totalidad de remisiones significativas dentro de la cual algo puede aparecer como algo: el martillo remite al clavo, el clavo a la tabla, la tabla al refugio, y el refugio a una posibilidad del Dasein mismo. Por eso el conocimiento teórico no es la relación fundamental con el mundo sino un modo derivado, que surge cuando el trato ocupado se interrumpe. Y de aquí sale la crítica a Descartes que atraviesa el libro: el problema del mundo exterior —cómo saber si hay algo fuera de mi mente— no se resuelve, se disuelve, porque supone un sujeto sin mundo que nunca existió; el escándalo de la filosofía, escribe Heidegger, no es que falte esa demostración, sino que se la siga esperando."},
   {t:"La diferencia ontológica (ser y ente)", d:"Es la distinción sobre la que descansa todo el proyecto: los entes son las cosas que son —esta mesa, este número, este dios, esta persona—, y el ser es aquello en virtud de lo cual algo es y puede mostrarse como lo que es. El ser no es un ente supremo ni un género comunísimo ni una propiedad que las cosas tengan; no se lo encuentra buscando mejor entre las cosas, porque no es ninguna de ellas. La tesis histórica de Heidegger es que la metafísica occidental, de Platón a Nietzsche, respondió siempre a la pregunta por el ser nombrando algún ente privilegiado que hiciera de fundamento: la Idea, el acto puro, Dios creador, el sujeto, la voluntad de poder. A ese procedimiento lo llama onto-teo-logía, y al descuido de la diferencia misma, olvido del ser. Conviene notar la sutileza que hace difícil el punto: el olvido no es una distracción que baste señalar para corregir, porque el ser se da siempre en los entes y al mismo tiempo se retira detrás de ellos, de modo que ocultarse pertenece a su modo de darse. Esa es también la razón por la que los críticos analíticos sospechan del asunto: si el ser no es ninguna cosa, no tiene propiedades y no se deja definir, cabe preguntar en qué se distingue esa profundidad de una confusión gramatical con el verbo ser, que es exactamente lo que objetaron Carnap y buena parte de la tradición posterior."},
   {t:"Ser-para-la-muerte (Sein-zum-Tode)", d:"Heidegger no está haciendo consejería existencial ni recomendando pensar seguido en el final; está buscando un modo de captar al Dasein como un todo, y el problema es que mientras existe siempre le falta algo por delante. Su solución es que la muerte no debe entenderse como el último acontecimiento de una serie, el hecho biológico de dejar de funcionar, sino como una posibilidad presente que estructura toda la existencia: la posibilidad más propia, irrespectiva, insuperable, cierta en cuanto tal e indeterminada en cuanto a su cuándo. Cada término hace un trabajo distinto. Es la más propia porque nadie puede morir en mi lugar, y por eso es el punto exacto donde la sustitución anónima del «uno» se vuelve imposible. Es irrespectiva porque me desliga de todas mis relaciones y roles, que dejan de poder responder por mí. Es insuperable porque no es una posibilidad que pueda realizarse y superarse: es la posibilidad de la imposibilidad de toda otra posibilidad. Anticiparla (Vorlaufen) no significa desear morir ni meditar mórbidamente sobre el cadáver, sino sostener la conciencia de que mi tiempo es finito y no reemplazable, y de esa finitud asumida sale la urgencia de elegir posibilidades como propias en vez de dejarlas elegidas por el «uno». Frente a eso, la cotidianidad tranquiliza: se muere, se dice, con lo cual la muerte se vuelve un caso público que le ocurre a cualquiera y a nadie."},
   {t:"La angustia (Angst) frente al miedo", d:"La distinción es técnica y no psicológica, y perderla arruina toda la lectura del libro. El miedo tiene siempre un ante-qué determinado, un ente intramundano que amenaza: el perro, el examen, el diagnóstico, el despido. Por eso el miedo se orienta, se administra, se planifica y hasta se desactiva, porque uno puede alejarse de la cosa temida. La angustia, en cambio, no tiene objeto, y su aparente vaguedad no es una falla de precisión: aquello ante lo que la angustia se angustia es el ser-en-el-mundo mismo. En la angustia el conjunto de las significaciones familiares se hunde y las cosas dejan de ofrecer su respuesta habitual, de modo que el mundo se vuelve insignificante y uno queda ante su desnuda posibilidad de existir. Heidegger describe esa experiencia como un no sentirse en casa (Unheimlichkeit), y sostiene que es precisamente ahí donde el «uno» pierde su poder tranquilizador. De ahí su función en la arquitectura del libro: la angustia individualiza, es decir, devuelve al Dasein la pregunta por quién está eligiendo sus posibilidades. Hay que notar también la objeción más obvia y más seria: cuando Heidegger declara que un temple de ánimo raro revela una estructura ontológica, hay que explicar por qué ese estado ilumina más que la alegría, el aburrimiento o la confianza, y por qué su interpretación del estado es la correcta — la fenomenología contemporánea sigue discutiéndolo, aunque el propio Heidegger amplió después la lista de temples fundamentales incluyendo el aburrimiento profundo."},
   {t:"El das Man (el «uno», el «se» impersonal)", d:"Das Man es la sustantivación del impersonal alemán man, que en castellano corresponde al «se» de se dice, se hace, se usa, y Rivera lo traduce como el «uno». Nombra al sujeto real de la cotidianidad: gozamos y nos divertimos como se goza y se divierte, leemos y juzgamos sobre literatura y arte como se ve y se juzga, nos indignamos ante lo que resulta indignante. El «uno» no es una persona, ni la sociedad, ni la masa, ni un grupo identificable al que se pudiera resistir: es una estructura anónima, un cualquiera que no es nadie en particular y que precisamente por eso no puede responder de nada. Sus rasgos son la distancia media —el nivelamiento de toda posibilidad excepcional—, la habladuría que repite sin haber verificado, la avidez de novedades y la ambigüedad que impide distinguir lo comprendido de lo meramente oído. Su rendimiento es real y Heidegger lo subraya: el «uno» descarga al Dasein del peso de elegir y de responder, y por eso resulta cómodo. Dos precisiones evitan los dos malentendidos más comunes. La primera es que no se trata de una crítica moral ni de una queja aristocrática contra la vulgaridad, sino de la descripción de un existenciario, es decir, de una estructura constitutiva y no de un defecto evitable. La segunda es que la impropiedad no es un estado del que uno salga de una vez: lo propio no es otro lugar sino una modificación de esta misma cotidianidad, una manera de retomar lo que ya se está haciendo."},
   {t:"Comprensión, interpretación y círculo hermenéutico", d:"Comprender (Verstehen), en el sentido de Heidegger, no es una operación intelectual que se agregue a la percepción: es un modo de ser del Dasein, emparentado con lo que decimos cuando alguien entiende de motores o entiende de personas. Comprender es proyectar posibilidades, saber a qué atenerse, poder habérselas con algo. La interpretación (Auslegung) no añade un sentido a un dato neutro, sino que desarrolla lo que ya estaba proyectado en la comprensión, y por eso Heidegger sostiene que nunca percibimos primero una cosa pura y después le agregamos una función: vemos directamente una puerta, un aula, un problema. De ahí la estructura del como (etwas als etwas), que precede a todo enunciado. Toda interpretación se mueve además en una triple anticipación —haber previo, manera previa de ver y anticipación conceptual—, de modo que siempre se entiende desde algo ya entendido. Eso configura el círculo hermenéutico, y la respuesta de Heidegger a quien lo denuncia como petición de principio es célebre: lo decisivo no es salir del círculo sino entrar en él del modo correcto, porque el círculo no es un vicio lógico sino la forma en que se da toda comprensión. Gadamer convertirá este punto en el núcleo de Verdad y método, y a través de él la idea reaparece en la teoría literaria, en la historiografía y en las ciencias sociales."},
   {t:"Lo a-la-mano y lo ante-los-ojos (Zuhandenheit y Vorhandenheit)", d:"Es el análisis más concreto del libro y el que mejor muestra el método fenomenológico en acción. El martillo, mientras se martilla, no se presenta como un objeto con propiedades observables: desaparece en el uso, y cuanto mejor se lo maneja menos se lo mira. Ese modo de ser es el de lo a-la-mano (zuhanden), el del útil, que nunca está solo porque remite siempre a un plexo de otros útiles y de destinaciones. Lo ante-los-ojos (vorhanden) es en cambio el modo de la cosa meramente presente y contemplable, con propiedades que pueden describirse y medirse, el correlato del sujeto teórico. La tesis fuerte de Heidegger es que la prioridad tradicional está invertida: la tradición tomó lo ante-los-ojos como el modo de ser por excelencia y trató los usos como añadidos subjetivos, cuando en el trato efectivo con el mundo ocurre al revés. Lo interesante es cómo se pasa de uno a otro, y aquí su descripción es precisa: el útil se vuelve visible cuando falla, y falla de tres maneras distintas. Puede llamar la atención por estar roto o inservible, puede apremiar por faltar cuando se lo necesita, o puede rebelarse y estorbar el paso. En cualquiera de los tres casos el plexo entero, que era invisible por ser obvio, se ilumina de golpe. Es la razón por la que tantos lectores fuera de la filosofía —el diseño de interfaces, la robótica, la fenomenología de la discapacidad, Dreyfus en su crítica a la inteligencia artificial simbólica— trabajaron con este pasaje más que con ningún otro de Heidegger."},
   {t:"La técnica moderna como Gestell (imposición o emplazamiento)", d:"Gestell es una palabra corriente del alemán —el armazón, el bastidor, el estante— que Heidegger fuerza para nombrar el modo en que la técnica moderna hace aparecer las cosas; en castellano circula como imposición, estructura de emplazamiento o dispositivo. Su punto de partida es que la esencia de la técnica no es nada técnico, y que la definición instrumental —un medio para fines humanos— es correcta pero no verdadera, porque describe el uso sin decir nada del modo de ser que lo hace posible. La técnica antigua, la téchne, hacía aparecer algo acompañando lo que ya tendía a aparecer: el campesino confía la semilla a la tierra y la cuida. La técnica moderna provoca y emplaza: exige a la naturaleza que entregue energía almacenable y disponible, y el ejemplo del Rin es el que mejor lo muestra, porque la central no se instala en el río sino que el río queda instalado en la central, y después reaparece como paisaje por encargo de la industria del turismo. Lo que resulta de ese emplazar es la existencia disponible (Bestand): no ya objetos que están frente a nosotros, sino reservas calculables e intercambiables. El peligro que Heidegger señala no es un accidente ni un uso indebido, sino que el ser humano, convertido él mismo en recurso —lo que hoy se dice sin ironía al hablar de recursos humanos—, termine por no encontrar ya en ningún lado sino a sí mismo y deje de poder oír cualquier otro modo de que las cosas sean. Su respuesta no es ni tecnófoba ni optimista: cita a Hölderlin —donde está el peligro crece también lo que salva— y propone una serenidad (Gelassenheit) que use los artefactos sin dejar que decidan qué es real. La objeción persistente es que un diagnóstico formulado en ese nivel de generalidad no distingue una vacuna de una mina antipersonal ni ofrece criterio alguno para decidir políticas concretas."}
 ],
 conexion:"Su noción de existencia arrojada influye directamente en <b>Sartre</b>, aunque Heidegger rechazará esa lectura humanista en la Carta sobre el humanismo, sosteniendo que invertir el par esencia/existencia sigue siendo metafísica. Por otro lado, su crítica del sujeto cartesiano lo acerca a <b>Nishida</b> y a la Escuela de Kioto, que leyeron Ser y tiempo tempranamente y encontraron en la nada un punto de contacto con el budismo.",
 dialogo:{titulo:"El estudiante que pregunta por el «uno» y por 1933", lineas:[
   {quien:"Estudiante", texto:"Profesor, entendí la descripción del «uno» y me reconocí en ella. Pero entonces dígame cómo se sale. Me levanto, tomo el subte que toman todos, doy la clase con el programa que me dieron, opino lo que se opina. ¿La existencia propia exige abandonar todo eso?"},
   {quien:"Heidegger", texto:"No exige abandonar nada. Fíjese que escribí que la propiedad es una modificación de la cotidianidad, no un segundo mundo al lado de ella. El «uno» es un existenciario: pertenece a la constitución del Dasein y no se lo puede suprimir, igual que no se puede suprimir el estar arrojado."},
   {quien:"Estudiante", texto:"Entonces la diferencia no está en lo que hago sino en cómo lo hago. Eso suena peligrosamente cómodo: puedo seguir haciendo exactamente lo mismo y declararme auténtico."},
   {quien:"Heidegger", texto:"Es una objeción justa y conviene precisarla. La diferencia está en si las posibilidades que vive son suyas o están vividas por nadie. Cuando uno dice se hace así, no hay quien responda. La resolución no cambia el contenido de la vida, cambia quién la sostiene.", nota:"Este es el punto más discutido de la Segunda Sección. Como el criterio de propiedad es puramente formal —quién asume la posibilidad, no cuál—, sus críticos sostienen que el esquema es compatible con cualquier contenido, incluido uno atroz: se puede ser resueltamente cualquier cosa. Adorno lo atacó por eso en La jerga de la autenticidad, y Löwith lo señaló ya en los años treinta."},
   {quien:"Estudiante", texto:"¿Y qué me saca de ahí? Porque yo puedo estar de acuerdo con usted y seguir igual mañana."},
   {quien:"Heidegger", texto:"No un argumento. Un temple. En la angustia el mundo entero pierde su obviedad: las cosas dejan de ofrecer su respuesta habitual, y uno ya no se siente en casa. Ahí el «uno» no tiene nada que decir, porque su fuerza consiste justamente en que todo resulta evidente."},
   {quien:"Estudiante", texto:"Yo diría que eso es un mal día, o que hay que ir al médico."},
   {quien:"Heidegger", texto:"Puede ser las dos cosas y aun así mostrar algo. No confunda el temple con el estado psicológico que lo acompaña. La angustia no teme nada determinado; si teme algo, ya es miedo. Y lo que se hunde en ella no es su ánimo, es la significatividad del mundo."},
   {quien:"Estudiante", texto:"Vuelvo a lo mío. ¿Por qué la muerte y no otra cosa? Podría elegir el amor, el nacimiento de un hijo, la enfermedad de alguien."},
   {quien:"Heidegger", texto:"Porque ninguna otra posibilidad es tan mía. Alguien puede sufrir por mí, trabajar por mí, incluso morir en mi lugar en el sentido de sacrificarse por una causa. Pero nadie puede quitarme mi morir. Es el único lugar donde la sustitución anónima se rompe, y por eso la anticipación devuelve el yo."},
   {quien:"Estudiante", texto:"Quiero hacerle otra pregunta y no sé cómo hacerla con cortesía. En 1933 usted se afilió al partido nazi, aceptó el rectorado de Friburgo y pronunció un discurso llamando a la universidad al servicio del Estado. Después de la guerra no dijo casi nada. ¿Puedo usar su análisis del Dasein sin que eso me toque?"},
   {quien:"Heidegger", texto:"Era una pregunta que había que hacer. Sostuve que el error fue político, que duré diez meses en el cargo y que después me apartaron y me vigilaron. También dije que la esencia de la técnica moderna, que empieza a pensarse en esos mismos años, no es un asunto de partidos."},
   {quien:"Estudiante", texto:"Con todo respeto, eso no responde. Ni una palabra sobre los asesinados. Y en los Cuadernos negros hay pasajes antisemitas escritos por usted, no por su hermana ni por un editor."},
   {quien:"Heidegger", texto:"No voy a esconderme detrás de una manipulación póstuma. Esos cuadernos los escribí yo, con la intención de que se publicaran al final de mi obra completa, y ahí está lo que dicen sobre la judeidad mundial y el cálculo. El único silencio público que rompí fue en una entrevista que pedí que se publicara después de mi muerte.", nota:"Los hechos, en limpio: afiliación al NSDAP en mayo de 1933 y rectorado hasta abril de 1934; la entrevista con Der Spiegel, concedida en 1966 y publicada en 1976; y los Cuadernos negros, editados desde 2014, que contienen pasajes antisemitas de carácter no meramente biográfico. El debate es real y está abierto. Una posición —Farías, Faye— sostiene que el nazismo impregna la filosofía misma; otra —Arendt, que fue su alumna y su amante y volvió a tratarlo, o Gadamer— separa la obra de la conducta; una tercera, hoy mayoritaria entre especialistas, sostiene que hay que leerlo entero y con la mancha a la vista, porque ni el rechazo del humanismo ni la crítica de la técnica quedan indemnes. Lo que ningún lector serio hace ya es tratarlo como una anécdota."},
   {quien:"Estudiante", texto:"Entonces qué hago con Ser y tiempo, que es de 1927 y me sigue pareciendo verdadero."},
   {quien:"Heidegger", texto:"Léalo, y léalo con esa pregunta encima en lugar de dejarla afuera. Usted mismo señaló que mi criterio de propiedad no dice qué elegir. Esa objeción no es menos mía por incomodarme: es la que mejor explica por qué un análisis de la resolución pudo convivir con una decisión indefendible."},
   {quien:"Estudiante", texto:"Es la primera cosa que me dice hoy que suena a respuesta."},
   {quien:"Heidegger", texto:"Porque no lo es del todo. Y quizá sea lo único honesto que puedo ofrecerle: un pensamiento no queda refutado por la biografía de quien lo tuvo, pero tampoco queda absuelto por la calidad de sus páginas."}
 ]},
 actividades:[
   {t:"Diario del útil que se rompe", d:"Durante dos días llevá una libreta y anotá cada vez que una herramienta que usabas sin pensar se te vuelve visible: el teclado que deja de responder, el picaporte que gira en falso, la aplicación que se cuelga, el auto que no arranca, la lapicera que se seca. Para cada caso registrá tres cosas con precisión. Primero, cuál de los tres modos de falla que describe Heidegger ocurrió: el útil llamó la atención por estar dañado, apremió por faltar, o se rebeló estorbando. Segundo, qué propiedades del objeto notaste recién en ese momento y no antes, cuando funcionaba. Tercero, y esto es lo más importante, qué otras cosas se te hicieron visibles junto con esa: qué red de remisiones se iluminó de golpe —el trabajo que dependía de eso, la persona a la que ibas a escribirle, el plan de la tarde—. Cerrá con un párrafo respondiendo si el ejercicio te convenció de la tesis fuerte de Heidegger, es decir, de que el modo teórico y contemplativo de mirar las cosas es derivado y no originario."},
   {t:"Auditoría de una decisión propia frente al «uno»", d:"Elegí una decisión real y todavía abierta de tu vida —un cambio de trabajo, una carrera, una mudanza, una conversación que venís evitando, un compromiso que aceptaste sin querer— y armá tres columnas por escrito. En la primera anotá todas las razones que tenés para cada opción, tal como te salgan. En la segunda, al lado de cada razón, escribí quién la sostiene si no sos vos: se espera que a mi edad, en mi familia se hace así, un docente serio no, todo el mundo diría que. En la tercera reescribí únicamente las razones que quedaron sin dueño externo, poniéndolas en primera persona y asumiendo su costo completo. Después hacé la parte crítica, que es la que da valor al ejercicio: buscá al menos una razón que hayas puesto en la columna del «uno» y defendé que sigue siendo buena aunque venga de la tradición, la costumbre o el consejo ajeno. Heidegger sostiene que lo propio es una modificación de lo cotidiano y no un rechazo de lo heredado; este ejercicio sirve para comprobar si podés sostener esa distinción sin convertirla en una pose de originalidad."},
   {t:"Carta para leer dentro de un año, escrita desde la finitud", d:"Escribí una carta de una página dirigida a vos mismo dentro de un año, con una consigna estricta: nada de metas ni de listas de logros. La carta debe responder tres preguntas. La primera es qué estás haciendo hoy con tu tiempo que estarías haciendo igual si tuvieras mil años por delante, es decir, qué actividades solo se sostienen por el supuesto tácito de que siempre habrá tiempo. La segunda es qué postergaste por vergüenza, por comodidad o porque no es lo que se hace, y qué pasaría si dejaras de postergarlo. La tercera es qué cosas, si mirás con honestidad, te importan aunque nadie las considere importantes. Guardala cerrada con la fecha a la vista. Terminá el ejercicio, ahora, con un párrafo aparte de objeción: Heidegger afirma que la anticipación de la muerte individualiza y devuelve la existencia a quien la vive, pero también hay tradiciones enteras —el estoicismo, el budismo, el psicoanálisis, buena parte de la ética del cuidado— que sostienen que la finitud asumida nos vuelve más dependientes de los otros y no más singulares. Argumentá cuál de las dos lecturas describe mejor lo que te pasó al escribir la carta."}
 ],
 cuestionario:[
   {q:"¿Puede separarse la filosofía de Heidegger de su nazismo, o la afiliación de 1933 y los Cuadernos negros contaminan el pensamiento mismo?", p:"Conviene tener a la vista los hechos antes que las posiciones: afiliación al NSDAP en mayo de 1933, rectorado de Friburgo hasta abril de 1934, un discurso rectoral que pone la universidad al servicio de la misión del pueblo alemán, un silencio público casi total después de 1945 y, desde 2014, la publicación de los Cuadernos negros con pasajes antisemitas que él mismo destinó a su obra completa. Sobre eso hay tres lecturas. La primera, que va de Farías a Emmanuel Faye, sostiene que el nazismo no es un episodio sino que estructura la obra, y que términos como pueblo, destino, arraigo y resolución ya llevan esa carga. La segunda, defendida entre otros por Hannah Arendt y por Gadamer, separa la mediocridad política del hombre del rendimiento de los conceptos, y recuerda que Ser y tiempo es de 1927 y que sus lectores más fecundos fueron judíos, marxistas y feministas. La tercera, hoy dominante entre especialistas, rechaza las dos salidas limpias: no hay ni contaminación total ni compartimentos estancos, y lo que corresponde es leer preguntando en qué puntos exactos el sistema no ofreció resistencia. El dato incómodo para la segunda posición es que la objeción filosófica más seria —que el criterio de propiedad es formal y no dice qué elegir— es justamente la que explica cómo pudo ocurrir."},
   {q:"Si el Dasein solo alcanza la existencia propia individualizándose frente al «uno», ¿no termina Heidegger en un individualismo que su propia noción de ser-con contradice?", p:"La tensión es real y muchos lectores la consideran el defecto estructural de la Primera Sección. Heidegger establece que el ser-con (Mitsein) es una estructura originaria y no un agregado: el Dasein ya está siempre con otros, incluso en la soledad, que es un modo deficiente de estar con. Pero cuando llega el momento de describir la propiedad, el camino pasa por la angustia que aísla, por la muerte que nadie puede asumir en mi lugar y por una voz de la conciencia que me llama desde mí mismo. Los otros reaparecen sobre todo como aquello de lo que hay que recuperarse. Heidegger ofrece una salida en la solicitud anticipante, una forma de cuidado que no le quita al otro su asunto sino que se lo devuelve para que lo asuma —la diferencia entre hacerle la tarea a alguien y ponerlo en condiciones de hacerla—, pero le dedica un puñado de líneas. La crítica más fuerte vino desde fuera: Levinas sostuvo que el otro no aparece en Heidegger como un rostro que interpela y obliga, sino dentro de mi propio proyecto, y que esa omisión no es un descuido sino la marca de una filosofía que pone la ontología antes que la ética. La ética del cuidado y buena parte del feminismo filosófico agregaron que la dependencia, la crianza y el cuerpo vulnerable brillan por su ausencia en un análisis que se presenta como descripción de la existencia humana en general."},
   {q:"Después de cuatrocientas páginas, ¿Heidegger llega a decir qué es el ser, o la pregunta queda tan indefinida que no se puede evaluar si la respondió?", p:"La objeción es justa como observación y discutible como reproche. Es cierto que Ser y tiempo no define el ser, y hay una razón interna: definir consiste en situar algo bajo un género y una diferencia, y el ser no es una cosa entre cosas, así que definirlo sería tratarlo como el ente que precisamente no es. El libro, además, quedó inconcluso exactamente antes de la sección que debía responder, y Heidegger reconoció después que el lenguaje de la metafísica no le alcanzaba, lo que explica su giro hacia Hölderlin, la etimología y una escritura que sus críticos consideran directamente oracular. Ahí se abre la fractura con la filosofía analítica: Carnap usó en 1932 la frase la Nada nadea como ejemplo de enunciado sin sentido producido por la mala gramática, y esa acusación —que el ser de Heidegger es un efecto del verbo copulativo tratado como sustantivo— nunca fue del todo respondida. La defensa más sólida invierte la carga: Heidegger no busca una definición sino una transformación de la comprensión, y su criterio de éxito no es la precisión sino la capacidad de mostrar fenómenos que la descripción habitual pasaba por alto, como el útil, la angustia o el «uno». Si eso se acepta como criterio o se considera una manera elegante de volverse infalsable es, en el fondo, la pregunta que divide dos tradiciones filosóficas enteras."},
   {q:"Sartre sostiene que la existencia precede a la esencia y llama a eso un humanismo. ¿Por qué Heidegger rechaza la fórmula si parece decir lo que él mismo dijo primero?", p:"Heidegger reconoce el parentesco y por eso mismo el deslinde le resulta urgente. Su argumento en la Carta sobre el humanismo es que invertir el par esencia/existencia no sale del marco metafísico: se siguen usando las mismas categorías, solo que al revés, y el ser humano sigue siendo pensado desde sí mismo en vez de desde el ser. De ahí sus fórmulas del período tardío: el lenguaje es la casa del ser y el hombre es el pastor del ser, no su dueño. Las diferencias concretas son tres y conviene tenerlas ordenadas. Primera, el papel de la libertad: en Sartre el para-sí es una nada que elige y es absolutamente responsable de su elección; en Heidegger el Dasein está arrojado, es decir, recibe un mundo, una lengua y una historia que no eligió, de modo que la resolución es siempre situada. Segunda, la conciencia: Sartre conserva el vocabulario de la conciencia y el en-sí/para-sí, que Heidegger considera un residuo cartesiano. Tercera, el humanismo mismo: Sartre quiere fundar una ética, Heidegger sostiene que preguntar por una ética antes de haber pensado el ser es empezar por el final. La réplica sartreana, y la de sus lectores posteriores, es que la posición de Heidegger deja al ser humano en una pasividad receptiva —escuchar, corresponder, guardar— que no da ningún criterio para actuar, y que esa impotencia práctica no es ajena a su silencio político."},
   {q:"La crítica de la técnica es de 1953, antes de la computadora personal, internet y los modelos de inteligencia artificial. ¿Sigue diciendo algo, o envejeció como nostalgia de la vida campesina?", p:"Hay dos lecturas y las dos tienen material. A favor de su vigencia: la noción de existencia disponible describe con incomodidad exacta cosas que hoy damos por obvias, desde la expresión recursos humanos hasta la economía de la atención, donde el tiempo y la mirada de las personas se vuelven reservas medibles y vendibles; y la advertencia de que la técnica no es un conjunto de instrumentos neutrales sino un modo de hacer aparecer el mundo anticipa buena parte de lo que hoy se discute sobre datos, plataformas y automatización. Autores como Hubert Dreyfus usaron su análisis del trato práctico con el mundo para formular la crítica más influyente a la inteligencia artificial simbólica, y Andrew Feenberg o Don Ihde construyeron desde ahí filosofías de la tecnología menos totalizantes. En contra: el diagnóstico opera a un nivel de generalidad que no distingue una vacuna de un arma, no ofrece ningún criterio para decidir entre políticas tecnológicas concretas y desemboca en una serenidad que es más una actitud que una propuesta. Su frase de 1966 sobre que solo un dios puede aún salvarnos alimenta la sospecha de quietismo. Y hay un problema añadido que no conviene esquivar: cuando en una conferencia de 1949 puso la agricultura mecanizada y las cámaras de gas en la misma serie de fenómenos técnicos, mostró hasta qué punto ese nivel de abstracción puede volverse moralmente ciego."}
 ],
 cadena:{ titulo:"¿Hay que saber qué es el ser para poder preguntar por él?", intro:"Un razonamiento en ramas a partir de los parágrafos 1, 2 y 32 de Ser y tiempo. Heidegger reconoce que toda pregunta va guiada de antemano por lo que busca, y que para preguntar qué es el ser ya usamos la palabra «es». ¿Es eso un círculo vicioso, un pseudoproblema o el verdadero punto de partida? Cada rama lleva a una lectura distinta; ninguna es una trampa.", inicio:"n1", nodos:{
   n1:{ pregunta:"En el parágrafo 2 de Ser y tiempo Heidegger escribe que todo preguntar es un buscar, y que todo buscar está guiado de antemano por lo buscado. Si pregunto «¿qué es el ser?», ya estoy usando el «es» y moviéndome en alguna comprensión de lo que pregunto. ¿Qué concluís?", opciones:[
     {texto:"Que la pregunta presupone su propia respuesta: hay un círculo vicioso.", va:"n2a"},
     {texto:"Que presupone una comprensión, no una respuesta: sé usar «es» sin poder decir qué significa.", va:"n2b"} ]},
   n2a:{ pregunta:"Heidegger anticipa la acusación y la rechaza en el mismo parágrafo: no hay ahí un círculo en la demostración, porque no se trata de deducir nada, sino de sacar a la luz algo en lo que ya estamos; habla de una curiosa referencia «hacia atrás o hacia adelante» de lo preguntado sobre el preguntar. Supongamos que no te convence. Alguien te dice: el «es» de «el cielo es azul» es una cópula gramatical y nada más. ¿Qué hacés con eso?", opciones:[
     {texto:"Me quedo con esa respuesta: «ser» es una función lógica, y la pregunta de Heidegger es un pseudoproblema.", final:{tipo:"bien", texto:"Llegaste a la posición de Carnap, que en 1932 eligió la frase «la Nada nadea» como ejemplo de enunciado sin sentido producido por tratar un verbo como si nombrara una cosa. Es una posición coherente y seria, no un malentendido. Pero tiene una tarea pendiente: explicar por qué el «es» dice cosas tan distintas —existencia (hay dioses), identidad (Héspero es Fósforo), predicación (el cielo es azul), verdad (así es)— y si esa pluralidad tiene alguna unidad o es un accidente de las lenguas indoeuropeas. Esa pregunta no es de Heidegger: es la de Aristóteles, y fue la que lo puso a pensar a él."}},
     {texto:"Distingo: la cópula es uno de los usos de «es»; la pregunta es qué une todos esos usos.", va:"n3a"} ]},
   n3a:{ pregunta:"Aristóteles ya decía que el ser se dice de muchas maneras, y Heidegger contó que su camino empezó a los diecisiete años con la tesis de Brentano sobre ese tema. Si esos sentidos tienen alguna unidad, ¿dónde la buscás?", opciones:[
     {texto:"En un ente que sea plenamente, del que los demás dependan: la sustancia primera, el acto puro, Dios.", final:{tipo:"revisar", texto:"Es la respuesta que dio la tradición, y Heidegger la llama onto-teo-logía: responder a la pregunta por el ser nombrando un ente privilegiado que haga de fundamento. El problema es que así se contesta otra pregunta —cuál es el ente supremo— y se deja intacta la primera: qué quiere decir que ese ente, también él, es. Eso es lo que la diferencia ontológica intenta señalar. Volvé un paso y buscá la unidad en otro lugar."}},
     {texto:"En el único ente que comprende el ser y para quien su propio ser es una cuestión: el Dasein.", final:{tipo:"bien", texto:"Es el rodeo de Ser y tiempo: antes de preguntar por el sentido del ser en general, interrogar al ente que ya siempre se mueve en una comprensión del ser, porque le va su propio ser. Fijate el precio, que el propio Heidegger terminó pagando: al empezar por el Dasein, el proyecto corría el riesgo de volver a hacer del ser algo que depende de quien lo comprende, es decir, de recaer en la filosofía del sujeto que quería superar. Esa sospecha es una de las razones por las que el libro quedó inconcluso y por las que después habló de un giro (Kehre)."}} ]},
   n2b:{ pregunta:"Heidegger llama a eso la comprensión del ser vaga y de término medio: la tenemos, es un hecho, y sin embargo el sentido del ser sigue envuelto en oscuridad. En el parágrafo 1 discute tres prejuicios que declaran innecesaria la pregunta: que el ser es el concepto más universal, que es indefinible y que es evidente de suyo. ¿Qué te dice la tercera?", opciones:[
     {texto:"Que la pregunta es ociosa: si todos entendemos «es» sin problemas, no hay nada que aclarar.", final:{tipo:"revisar", texto:"Heidegger responde exactamente a esto: que algo sea obvio no lo vuelve claro, y el uso de lo evidente de suyo como argumento es, recordando a Kant, justamente lo que la filosofía tiene que examinar. Que entendamos «es» a cada rato y no sepamos decir qué entendemos muestra que la pregunta es necesaria, no que sobra. Volvé un paso y tomá la otra dirección."}},
     {texto:"Que esa evidencia es un dato: el Dasein ya está siempre en alguna relación con el ser, y por eso es el punto de partida.", va:"n3b"} ]},
   n3b:{ pregunta:"Pero la comprensión cotidiana está dominada por el «uno»: comprendemos el ser como se lo comprende, casi siempre como el ser de las cosas que están ahí delante. ¿Cómo evita la investigación repetir ese prejuicio?", opciones:[
     {texto:"Partiendo de la cotidianidad de término medio, sin inventar una situación ideal, y dejando que en ella se vea su propia estructura.", final:{tipo:"bien", texto:"Es el método de la Primera Sección: no buscar un punto de partida puro sino describir al Dasein tal como es de ordinario, ocupado con útiles y con otros. Heidegger lo formula en el parágrafo 32: lo decisivo no es salir del círculo, sino entrar en él de la manera correcta, porque toda comprensión se mueve desde algo ya comprendido. Por eso el análisis del útil y del «uno» no es un prólogo: es el lugar donde la pregunta por el ser empieza a tener contenido."}},
     {texto:"Buscando experiencias excepcionales —la angustia, la anticipación de la muerte— donde el «uno» calla y la pregunta se vuelve mía.", final:{tipo:"bien", texto:"Es el camino de la Segunda Sección, y es genuinamente heideggeriano. Pero cuidá dos cosas. La primera: Heidegger insiste en que la existencia propia no es un segundo mundo al que se huye, sino una modificación de la misma cotidianidad. La segunda: el criterio de lo propio que así se obtiene es formal —quién asume una posibilidad, no cuál—, y es la objeción que Löwith y Adorno le hicieron y que el diálogo deja abierta: se puede ser resueltamente cualquier cosa. Esa objeción no refuta el análisis, pero pesa sobre él, y ayuda a entender cómo pudo convivir con la decisión política de 1933."}} ]}
 }},
 reconstruccion:[
   { titulo:"Lo a-la-mano antes que lo ante-los-ojos (Ser y tiempo, §§15-16)",
     consigna:"Reconstruí el argumento con el que Heidegger invierte la prioridad tradicional de la cosa contemplada sobre el útil. Una pieza pertenece a otro análisis del libro: dejala afuera y ordená el resto.",
     piezas:[
       {id:"h1", texto:"En el trato cotidiano no encontramos primero cosas con propiedades, sino útiles: el martillo con que martillamos, el picaporte que giramos, el lápiz con que escribimos.", tipo:"premisa"},
       {id:"h2", texto:"Mientras el útil funciona, se retira: cuanto mejor se lo maneja, menos se lo mira. Su modo de ser es el estar a la mano, y se revela en el uso, no en la contemplación.", tipo:"premisa"},
       {id:"h3", texto:"Además, un útil nunca está solo: remite a otros útiles y a un para-qué —el clavo, la tabla, el refugio— y, en último término, a una posibilidad del Dasein mismo.", tipo:"premisa"},
       {id:"h4", texto:"Solo cuando el útil falla —está roto, falta o estorba— aparece como mera cosa ante los ojos, con propiedades observables, y con él se ilumina de golpe el plexo de remisiones que antes era invisible.", tipo:"premisa"},
       {id:"h5", texto:"Por lo tanto, el ser ante-los-ojos no es el modo originario de las cosas sino uno derivado, que surge de una interrupción del trato; la tradición, al tomar la cosa contemplada como modelo de todo ente, invirtió el orden fenomenológico.", tipo:"conclusion"},
       {id:"hx", texto:"En la angustia, en cambio, no falla ningún útil en particular: la totalidad de lo intramundano se hunde en la insignificancia y queda al descubierto el ser-en-el-mundo como tal.", tipo:"distractor"}
     ],
     ordenCorrecto:["h1","h2","h3","h4","h5"],
     explicacion:"El argumento es fenomenológico, no deductivo: describe cómo se nos dan las cosas y extrae de esa descripción una tesis sobre el orden de los modos de ser. h2 establece que el útil se retira en el uso; h3, que su ser es relacional; y h4 es el paso decisivo, porque muestra que la cosa con propiedades aparece precisamente cuando el trato se rompe, es decir, después y por privación. La pieza sobrante pertenece al parágrafo 40: también allí algo se hunde y algo se revela, pero lo que se revela es el mundo como tal y no un útil; confundir los dos análisis es perder la diferencia entre una falla intramundana y un temple fundamental. Para discutir: ¿prueba el argumento que lo teórico es derivado, o solo que no es lo primero en el orden de nuestra experiencia? Un físico podría conceder todo h1-h4 y negar h5, diciendo que el orden de la vivencia no decide el orden del ser."},
   { titulo:"La angustia revela el mundo como mundo (Ser y tiempo, §40)",
     consigna:"Reconstruí el argumento por el que Heidegger sostiene que la angustia, a diferencia del miedo, abre el ser-en-el-mundo mismo. Una pieza convierte el temple en un estado psicológico: dejala afuera.",
     piezas:[
       {id:"a1", texto:"El miedo tiene siempre un ante-qué determinado: un ente intramundano que amenaza desde una región y que puede acercarse o alejarse.", tipo:"premisa"},
       {id:"a2", texto:"En la angustia, en cambio, lo amenazante no está en ningún lado: no es ningún ente intramundano, y por eso la angustia no sabe qué es aquello ante lo que se angustia.", tipo:"premisa"},
       {id:"a3", texto:"En ella la totalidad de los útiles y de los entes intramundanos pierde toda significatividad: nada ofrece ya su respuesta habitual.", tipo:"premisa"},
       {id:"a4", texto:"Pero lo que se impone cuando todo lo intramundano se vuelve insignificante no es la pura nada, sino el mundo mismo en su mundanidad.", tipo:"premisa"},
       {id:"a5", texto:"Por lo tanto, aquello ante lo que la angustia se angustia es el ser-en-el-mundo mismo: la angustia abre el mundo como mundo y singulariza al Dasein, arrancándolo de la tranquilidad del «uno».", tipo:"conclusion"},
       {id:"ax", texto:"Así como un útil roto vuelve a funcionar cuando se lo repara, la angustia es un desajuste pasajero del ánimo que el tratamiento adecuado devuelve al trato normal con las cosas.", tipo:"distractor"}
     ],
     ordenCorrecto:["a1","a2","a3","a4","a5"],
     explicacion:"El argumento avanza por contraste: a1 fija el esquema del miedo, a2 muestra que la angustia no encaja en él, y a3-a4 describen qué ocurre cuando falta todo ante-qué intramundano: no queda nada en particular, pero queda el mundo. La conclusión tiene dos partes que conviene no separar: la angustia es reveladora (abre el mundo como tal) y es singularizante (me devuelve a mi propio poder-ser, porque el «uno» no tiene nada que decir donde nada es obvio). La pieza sobrante es la lectura que el estudiante del diálogo propone cuando dice que eso es un mal día o que hay que ir al médico. Heidegger no niega que exista la angustia clínica; sostiene que la estructura que el temple revela no depende de su psicología. Para discutir: ¿por qué la angustia y no la alegría o el aburrimiento? El propio Heidegger amplió después la lista con el aburrimiento profundo, lo que sugiere que el privilegio de la angustia no era tan exclusivo como parece en el parágrafo 40."}
 ],
 dilemas:[
   { titulo:"El estudio del tío",
     intro:"En el diálogo, Heidegger le dice al estudiante que la existencia propia no exige abandonar nada: la resolución no cambia el contenido de la vida, cambia quién la sostiene. Este caso pone esa tesis sobre una decisión de carrera real, y termina con la objeción que el propio diálogo deja abierta.",
     pasos:[
       { id:"p1", situacion:"Estás en tercer año de Derecho y te va bien. Tu familia, tus amigos y vos mismo dan por sentado que al recibirte vas a entrar al estudio de tu tío. Una noche, estudiando, te agarra algo que no es el miedo al examen: todo pierde peso, las razones no responden, la vida entera parece de otro. ¿Qué hacés con eso?", opciones:[
         {texto:"Lo tomo como estrés: dormir, salir el fin de semana, que se pase.", consecuencia:"Puede ser estrés, y Heidegger no te pediría que lo dramatices. Pero fijate en el gesto: le pusiste enseguida el nombre que se le pone, y ese nombre te tranquilizó. Es lo que Ser y tiempo describe como la huida del Dasein ante sí mismo hacia la tranquilidad del «uno»: no un error, sino el modo más habitual de no dejar que la pregunta llegue.", va:"p2a"},
         {texto:"Me quedo con eso: me pregunto qué de todo esto elegí yo.", consecuencia:"Es lo que la angustia hace posible, según Heidegger: no te da una respuesta, te quita la obviedad. La pregunta que te hiciste no es qué carrera es mejor, sino quién está eligiendo, y esa es exactamente la pregunta que el «uno» vuelve innecesaria.", va:"p2b"},
         {texto:"Decido dejar Derecho mañana mismo: si todo me lo eligieron otros, nada de esto es mío.", consecuencia:"Entendés que algo está en juego, pero cuidado: la resolución (Entschlossenheit) no es una decisión impulsiva ni un rechazo en bloque de lo heredado. Heidegger la describe como apertura a la situación concreta. Y quien hace lo contrario de lo que se espera sigue midiendo su vida con la vara de lo que se espera.", va:"p2c"} ]},
       { id:"p2a", situacion:"Pasan los meses y entrás al estudio. Un colega mayor te dice, amable: «Acá se trabaja así, no te hagas problema. Todos empezamos odiándolo y después uno se acostumbra». ¿Qué le respondés?", opciones:[
         {texto:"«Tiene razón: es lo que se hace, y funciona.»", consecuencia:"Tu colega no dijo nada falso, y esa es la fuerza de la habladuría: repite lo que se sabe sin que nadie tenga que haberlo verificado. «Uno se acostumbra» es una frase sin sujeto; nadie responde por ella. Heidegger subraya que el «uno» descarga y alivia, y por eso no es fácil ver lo que cuesta.", va:"p3"},
         {texto:"«¿Y qué hizo usted con ese odio del principio?»", consecuencia:"Convertiste una frase impersonal en una pregunta a una persona. Es un gesto pequeño y exactamente del tipo que Heidegger describe: lo propio no es otro mundo sino una manera distinta de estar en este, incluso en una conversación de oficina. Puede que tu colega no tenga respuesta; ya es algo que la pregunta tenga dueño.", va:"p3"} ]},
       { id:"p2b", situacion:"Hacés el ejercicio por escrito: todas tus razones para seguir en Derecho y, al lado, quién las sostiene. Casi todas son del «uno»: se espera, en mi familia se hace, es una carrera con salida. Pero una es tuya: te apasiona de verdad construir un argumento para defender a alguien. ¿Qué hacés?", opciones:[
         {texto:"Descarto todas las razones heredadas: solo vale la que es mía.", consecuencia:"Parece radical y es una ilusión. Heidegger insiste en que el Dasein está arrojado: recibe una lengua, una familia, una historia que no eligió. En el parágrafo 74 dice que la resolución retoma posibilidades heredadas y las asume como propias. Descartar todo lo heredado es suponer un sujeto sin mundo, el mismo que Heidegger reprocha a Descartes.", va:"p3"},
         {texto:"Sigo en Derecho, pero no por el estudio del tío: busco cómo ejercer esa parte que sí es mía.", consecuencia:"Es la tesis del diálogo puesta en práctica: el contenido puede ser el mismo y la existencia distinta, porque cambió quién la sostiene. Notá además que no rechazaste a tu familia: separaste lo que te daban de lo que asumís.", va:"p3"} ]},
       { id:"p2c", situacion:"Dejás Derecho y anunciás que vas a estudiar Cine. Tu grupo de amigos lo celebra: «¡Por fin sos vos mismo!». Te sentís liviano. ¿Te alcanza?", opciones:[
         {texto:"Sí: me liberé de lo que se esperaba de mí.", consecuencia:"Mirá quién habla ahora: tus amigos, con una frase hecha sobre ser uno mismo. El «uno» no es tu familia ni la sociedad; es una estructura anónima, y puede tener también la forma del grupo que celebra la ruptura. Heidegger diría que cambiaste de «se», no necesariamente de existencia.", va:"p3"},
         {texto:"No sé: me pregunto si elegí Cine o si elegí no ser abogado.", consecuencia:"Es la pregunta correcta. Una decisión definida solo por lo que niega sigue dependiendo de aquello que niega. Que la hayas hecho no invalida el cambio de carrera; lo vuelve posible de asumir.", va:"p3"} ]},
       { id:"p3", situacion:"Un profesor te comenta, con cierta dureza: «Heidegger te dice cómo elegir, no qué elegir. Con ese criterio se puede ser resueltamente cualquier cosa. Él mismo fue resuelto en 1933». ¿Qué respondés?", opciones:[
         {texto:"«Tiene razón: un criterio puramente formal no sirve para decidir nada que importe.»", consecuencia:"Es la objeción de Löwith y de Adorno, y el diálogo le da la razón en parte. El precio de aceptarla es que tenés que buscar en otro lado el criterio de contenido —una ética, una idea de justicia—, algo que Heidegger postergó una y otra vez. No es una refutación de Ser y tiempo, pero sí una advertencia sobre lo que el libro no puede darte.", va:null},
         {texto:"«La objeción confunde niveles: la propiedad no es una ética, es una descripción de la existencia.»", consecuencia:"Es la defensa más habitual y tiene base textual: Heidegger niega que su análisis sea una moral. Pero si la aceptás, tenés que conceder lo que el propio Heidegger del diálogo concede: que la falta de criterio no es un detalle académico, porque es la parte del sistema que no opuso resistencia a una decisión indefendible.", va:null},
         {texto:"«La resolución incluye el ser-con: decidir propiamente es también dejar a los otros ser en sus posibilidades, y eso excluye ciertos contenidos.»", consecuencia:"Es el intento de los lectores más simpatizantes de sacar una ética del libro, y tiene apoyo: la solicitud que libera al otro para su propio poder-ser (§26) y la frase según la cual el Dasein resuelto puede convertirse en conciencia de los otros (§60). Su debilidad es que Heidegger le dedica pocas líneas, y Levinas sostendrá que el otro nunca aparece allí como alguien que me obliga.", va:null} ]}
     ],
     rubrica:[
       "Distinguí entre miedo (ante algo determinado) y angustia (ante el ser-en-el-mundo mismo), y no reduje la experiencia de la primera decisión a ninguno de los dos sin argumentarlo.",
       "Identifiqué qué razones hablaban en el modo del «se» (se espera, se hace, uno se acostumbra) y me pregunté quién respondería por cada una.",
       "No confundí la existencia propia con hacer lo contrario de lo esperado: puedo explicar por qué el rebelde puede seguir en el «uno».",
       "Reconocí qué posibilidades heredadas podía retomar como propias en lugar de descartarlas por venir de otros.",
       "Puedo explicar por qué, para Heidegger, la propiedad es una modificación de la cotidianidad y no un segundo mundo al lado de ella.",
       "Formulé la objeción del formalismo —se puede ser resueltamente cualquier cosa— y dije si la considero fatal o subsanable, sin esquivar el caso de 1933.",
       "Tuve en cuenta a los otros de la historia (familia, colega, amigos) como algo más que presión anónima."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.heidegger = { lecturas:[
 {titulo:"Ser y tiempo: el Dasein, la caída en el «uno» y el ser-para-la-muerte", fuente:"Martin Heidegger, Ser y tiempo — traducción castellana de Jorge Eduardo Rivera (PDF completo, philosophia.cl)", url:"https://www.philosophia.cl/biblioteca/Heidegger/Ser%20y%20Tiempo.pdf",
  extracto:`Heidegger arranca Ser y tiempo denunciando un olvido: la metafísica occidental estudió incansablemente los entes, pero dejó sin plantear la pregunta por el sentido del Ser. A esa distinción entre el Ser y los entes la llama diferencia ontológica, y sostiene que toda la tradición, de Platón a Nietzsche, la pasó por alto al tratar el Ser como si fuera otro ente más (una sustancia, Dios, un fundamento).

Para replantear la pregunta necesita un punto de partida, y ese punto es el ente que se pregunta: el Dasein, «ser-ahí». En la traducción de Jorge Eduardo Rivera su rasgo definitorio se enuncia así: «a este ente le va en su ser este mismo ser». No tiene una esencia fija que después se realiza; su esencia está en su existencia, es decir, en las posibilidades que asume o rehúye, y por eso Heidegger escribe que «el Dasein se comprende siempre a sí mismo desde su existencia, desde una posibilidad de sí mismo». Por eso Heidegger evita palabras como «sujeto», «conciencia» o «yo»: todas cargan el esquema cartesiano de una cosa pensante frente a un mundo de cosas extensas, que es justamente lo que quiere desarmar.

En lugar de ese esquema propone el ser-en-el-mundo como estructura unitaria. El Dasein no está primero en su interioridad y después se relaciona con objetos: siempre ya está ocupándose de cosas en un mundo de significados. El análisis del útil es célebre: el martillo se nos da primariamente como algo «a la mano» (zuhanden) en un uso que no lo tematiza — solo cuando se rompe, falta o estorba pasa a ser un objeto «ante los ojos» (vorhanden) con propiedades observables. Heidegger invierte así la prioridad tradicional: el conocimiento teórico es un modo derivado, no fundamental, de estar en el mundo.

El Dasein es además siempre ser-con otros, y de ahí surge la figura del «uno» (das Man). En la cotidianidad no elijo yo, y el parágrafo 27 lo dice con una frase que conviene leer en voz alta: «gozamos y nos divertimos como se goza y se divierte; leemos, vemos y juzgamos sobre literatura y arte como se ve y se juzga». El «uno» no es una persona ni una masa: es una estructura anónima que libera al Dasein del peso de elegir y de responder por sus elecciones. A esta existencia dispersa la llama impropia o inauténtica — y aclara que no es un juicio moral, sino la forma normal y mayoritaria de existir.

Lo que puede sacar al Dasein de ahí es la angustia. A diferencia del miedo, que siempre teme algo determinado, la angustia no tiene objeto: «aquello ante lo que la angustia se angustia es el ser-en-el-mundo mismo». Al desmoronarse toda significación familiar, el mundo se vuelve insignificante y el Dasein queda ante su desnuda posibilidad de existir.

Esa revelación culmina en el ser-para-la-muerte. La muerte no es un hecho futuro sino una posibilidad presente y estructural: Rivera traduce la fórmula como «la posibilidad más propia, irrespectiva, insuperable» (y, en el desarrollo del parágrafo 52, cierta en cuanto tal e indeterminada en cuanto a su cuándo). Es irrespectiva porque nadie puede morir en mi lugar — ahí el «uno» se vuelve inútil. Anticiparla (Vorlaufen) no es obsesionarse con morir, sino asumir la finitud de mi tiempo y, con ella, la urgencia de elegir mis posibilidades como propias. Eso es la existencia auténtica.`,
  comentario:"Este texto muestra por qué Heidegger considera que ontología y existencia son la misma investigación: solo un ente para quien su ser es un problema puede abrir la pregunta por el Ser. La crítica del «uno» y la del útil son la misma operación — descentrar al sujeto teórico cartesiano. Sobre la pregunta del cuestionario: Heidegger insistiría en que la angustia no es un estado psicológico sino un temple ontológico que revela estructuras, aunque la distinción sigue siendo discutida."}
], preguntasLectura:[
 {q:"¿Qué es la «diferencia ontológica» según Heidegger?", opciones:["La diferencia entre cuerpo y alma","La distinción olvidada entre el Ser y los entes","La diferencia entre miedo y angustia","La distinción entre sujeto y objeto"], r:"La distinción olvidada entre el Ser y los entes", why:"La metafísica trató siempre al Ser como si fuera un ente más; Heidegger considera ese el olvido fundante."},
 {q:"En el análisis del martillo, ¿cuándo pasa el útil de «a la mano» a «ante los ojos»?", opciones:["Cuando lo compramos","Cuando se rompe, falta o estorba","Cuando lo usamos con destreza","Cuando alguien lo nombra"], r:"Cuando se rompe, falta o estorba", why:"Es el ejemplo con que Heidegger muestra que el conocimiento teórico es un modo derivado del estar-en-el-mundo."},
 {q:"¿Por qué la muerte es «irrespectiva» para Heidegger?", opciones:["Porque es indolora","Porque nadie puede morir en mi lugar","Porque no tiene fecha","Porque la niega el «uno»"], r:"Porque nadie puede morir en mi lugar", why:"Es el punto donde la estructura anónima del «uno» deja de poder sustituir al Dasein."}
]};
