/* ============================================================
   Ficha: kant  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"kant", trad:"europea", nombre:"Immanuel Kant", fechas:"1724–1804 · Königsberg", escuela:"Idealismo trascendental", icon:"⚖️", profundizada:true,
 tesis:"No conocemos las cosas en sí (noúmeno), sino cosas ya organizadas por las formas a priori de nuestra mente (fenómeno). En ética, una acción es moral si obedece a un deber universalizable (imperativo categórico), no a sus consecuencias.",
 obras:[
   {t:"Crítica de la razón pura", d:"Publicada en 1781 y reescrita en buena parte para la segunda edición de 1787, es el libro que parte en dos la historia de la filosofía moderna. Su pregunta no es qué hay en el mundo sino qué tiene que poner el sujeto para que haya experiencia posible: cómo son posibles los juicios sintéticos a priori, esos que amplían nuestro conocimiento y sin embargo valen con necesidad universal. La Estética trascendental muestra que el espacio y el tiempo no son cosas ni propiedades de las cosas, sino las formas con que intuimos; la Analítica trascendental deduce las doce categorías del entendimiento y prueba que sin ellas ninguna percepción llegaría siquiera a ser objeto; la Dialéctica trascendental desmonta las tres pretensiones clásicas de la metafísica —alma, mundo y Dios— mostrando que la razón, al aplicar las categorías más allá de toda experiencia posible, cae en paralogismos y antinomias, es decir, en demostraciones igualmente convincentes de tesis contradictorias. El resultado es doble y Kant lo enuncia sin rodeos: tuve que suprimir el saber para dejar sitio a la fe. La metafísica como ciencia de lo suprasensible resulta imposible, pero la ciencia natural queda fundada con una necesidad que Hume le había arrebatado."},
   {t:"Fundamentación de la metafísica de las costumbres", d:"Opúsculo breve de 1785, escrito antes que la segunda Crítica y pensado como la búsqueda y fijación del principio supremo de la moralidad, no como un tratado completo de deberes. Arranca de la experiencia moral común —nada es bueno sin restricción salvo una buena voluntad— y va elevándose por análisis hasta la fórmula que sostiene todo el edificio: obra solo según aquella máxima por la cual puedas querer al mismo tiempo que se convierta en ley universal. Allí distingue obrar conforme al deber de obrar por deber, separa los imperativos hipotéticos de los categóricos, presenta las tres grandes formulaciones del imperativo —ley universal, humanidad como fin en sí mismo, reino de los fines— y las pone a prueba con cuatro ejemplos célebres: el suicidio por hastío, la promesa falsa, el talento descuidado y la negativa a ayudar al necesitado. Es el texto de Kant más leído en el aula y también el más traicionado por los resúmenes, porque su tercera sección —donde intenta fundar el imperativo en la libertad de un ser racional— es la parte que él mismo consideró menos concluyente."},
   {t:"Crítica de la razón práctica", d:"De 1788, es el intento de fundar la moral no ya por análisis de la conciencia común sino desde el uso práctico de la razón misma. Invierte el orden de la primera Crítica: mientras allí la razón especulativa fracasaba al salir de la experiencia, aquí la razón práctica establece un hecho que Kant llama el hecho de la razón, la conciencia inmediata de estar sometido a la ley moral, y a partir de él deduce la realidad de la libertad. La libertad no se demuestra teóricamente ni se percibe: se sabe porque debemos, y el deber implica poder. De ahí salen también los dos postulados restantes —la inmortalidad del alma y la existencia de Dios—, que no son verdades demostradas sino condiciones que la razón práctica necesita suponer para que el bien supremo, la unión de virtud y felicidad merecida, no sea un absurdo. El libro cierra con una frase que Kant pidió para su tumba: dos cosas llenan el ánimo de admiración creciente, el cielo estrellado sobre mí y la ley moral en mí."},
   {t:"Crítica del juicio", d:"Tercera y última Crítica, de 1790, y la que Kant concibe como puente entre las otras dos: entre el reino de la naturaleza, donde todo está regido por causas, y el reino de la libertad, donde la voluntad se determina por la ley moral. Su primera parte analiza el juicio estético y sostiene que el juicio de gusto es desinteresado —no depende de que la cosa exista ni de que me sirva—, sin concepto y sin embargo con pretensión de validez universal: cuando digo que algo es bello no informo sobre mi agrado, reclamo el asentimiento de los demás sin poder probarlo. Introduce también lo sublime, ese sentimiento en que la imaginación fracasa ante lo desmesurado y ese mismo fracaso revela en nosotros una vocación que excede toda magnitud sensible. La segunda parte examina el juicio teleológico: por qué no podemos dejar de pensar los organismos como si tuvieran fines, aunque esa finalidad sea un principio regulativo de nuestra reflexión y no una propiedad demostrable de la naturaleza. Es el libro kantiano que más descendencia dejó en la estética, en la biología teórica y en el idealismo alemán posterior."},
   {t:"Sobre la paz perpetua", d:"Escrito en 1795 y publicado con la forma irónica de un tratado internacional, con artículos preliminares, artículos definitivos y hasta un artículo secreto, es la aplicación de la filosofía práctica kantiana a la política real. Sus artículos preliminares exigen suprimir las cláusulas secretas que preparan guerras futuras, abolir progresivamente los ejércitos permanentes y prohibir las hostilidades que destruyen la confianza mínima entre Estados. Los tres artículos definitivos son la columna del texto: que la constitución de cada Estado sea republicana, porque quien decide la guerra debe ser quien la paga y la sufre; que el derecho de gentes se funde en una federación de Estados libres y no en un Estado mundial, que Kant teme como despotismo universal; y que exista un derecho cosmopolita limitado a la hospitalidad, es decir, al derecho de todo ser humano a no ser tratado como enemigo al llegar a suelo ajeno. Kant no promete el paraíso: sostiene que la paz no es un estado natural sino una tarea, y que incluso una nación de demonios, si son racionales, tiene motivos para instituirla."}
 ],
 conceptos:[
   {t:"Revolución copernicana", d:"Hasta Kant se había supuesto que todo nuestro conocimiento debía regirse por los objetos, y sobre ese supuesto la metafísica no había avanzado un paso en dos mil años. Kant propone probar lo contrario, como hizo Copérnico cuando dejó de explicar el cielo suponiendo que los astros giraban alrededor del espectador: que los objetos se rijan por nuestro conocimiento. El sujeto deja de ser un espejo pasivo y pasa a ser el que impone las condiciones formales bajo las cuales algo puede aparecer como objeto. La consecuencia es exacta y no debe suavizarse: no se trata de que cada uno construya su realidad a gusto, sino de que las estructuras que hacen posible cualquier experiencia son universales y necesarias porque son las de todo sujeto racional finito. La ganancia es que la necesidad de las leyes naturales queda explicada; el costo es que solo conocemos lo que esas estructuras dejan aparecer."},
   {t:"Fenómeno y noúmeno", d:"Fenómeno es la cosa tal como se nos aparece, ya filtrada y organizada por las formas de la sensibilidad y las categorías del entendimiento. Noúmeno o cosa en sí es la cosa considerada con independencia de esa relación con nosotros. Kant insiste en dos precisiones que la divulgación suele perder. La primera es que no son dos mundos superpuestos, uno verdadero y otro aparente, sino dos modos de considerar lo mismo: el fenómeno no es una ilusión, es el único objeto real de la ciencia. La segunda es que el noúmeno cumple una función esencialmente negativa: marca el límite de nuestro conocimiento e impide que el entendimiento se crea capaz de alcanzarlo todo. De ahí la objeción más repetida contra el sistema, que ya le hizo Jacobi y que Hegel convertirá en programa: si nada podemos decir de la cosa en sí, ¿con qué derecho afirmamos que existe y que afecta nuestra sensibilidad, usando justamente la categoría de causa que Kant declaró válida solo dentro de la experiencia?"},
   {t:"Formas a priori de la sensibilidad: espacio y tiempo", d:"Kant sostiene que el espacio y el tiempo no son cosas que existan por su cuenta, como quería Newton, ni relaciones entre cosas, como quería Leibniz, sino las formas puras de nuestra intuición: los modos en que necesariamente ordenamos todo lo que recibimos. Su argumento es que podemos imaginar un espacio sin objetos pero no objetos sin espacio, y que las propiedades geométricas se conocen con necesidad sin ir a comprobarlas una por una, lo que sería imposible si el espacio fuera un dato empírico. El espacio es la forma del sentido externo y el tiempo la del sentido interno, pero como todo lo que percibimos pasa también por la conciencia, el tiempo es la forma universal de toda intuición sin excepción. De ahí se sigue la tesis más difícil de digerir del idealismo trascendental: el espacio y el tiempo son empíricamente reales, valen sin excepción para todo lo que pueda aparecernos, y a la vez trascendentalmente ideales, es decir, no son propiedades de las cosas en sí."},
   {t:"Categorías del entendimiento", d:"La sensibilidad recibe, pero por sí sola no piensa nada; el entendimiento piensa, pero no intuye nada. De esa complementariedad sale la frase más citada de la primera Crítica: los pensamientos sin contenido son vacíos, las intuiciones sin conceptos son ciegas. Las categorías son los doce conceptos puros del entendimiento —agrupados en cantidad, cualidad, relación y modalidad, e incluyendo sustancia, causalidad y necesidad— con los que unificamos lo dado en una experiencia objetiva. La deducción trascendental, el capítulo más arduo del libro, no pretende mostrar que tengamos esos conceptos, sino que sin ellos nada podría valer siquiera como objeto para nosotros. Esa es la respuesta de Kant a Hume: la causalidad no se descubre en la costumbre de ver dos hechos seguidos, sino que es una condición previa que hace posible que percibamos una sucesión como un orden objetivo y no como un desfile azaroso de impresiones. El precio es que esa necesidad vale solo dentro de la experiencia posible; aplicada más allá, produce ilusión."},
   {t:"Juicios sintéticos a priori", d:"Kant cruza dos distinciones que antes iban juntas. Un juicio es analítico si el predicado ya está contenido en el sujeto y basta analizarlo para verlo —todo cuerpo es extenso—, y sintético si añade algo nuevo. Y es a priori si vale con necesidad y universalidad, independientemente de la experiencia, o a posteriori si depende de ella. El empirismo suponía que todo lo sintético era a posteriori y todo lo a priori, analítico y por tanto vacío. Kant sostiene que existe una tercera casilla y que en ella está todo el conocimiento importante: siete más cinco es doce añade información y sin embargo no se comprueba contando casos; la recta es la línea más corta entre dos puntos mezcla cantidad con cualidad; todo cambio tiene una causa vale universalmente sin que ninguna experiencia pueda garantizarlo. La pregunta de toda la Crítica es cómo son posibles esos juicios, y su respuesta es que lo son porque las formas y las categorías que los hacen necesarios son aportadas por nosotros. Conviene saber que la casilla misma fue discutida después: Frege puso en duda que la aritmética sea sintética y Quine atacó de raíz la distinción analítico-sintético."},
   {t:"Yo trascendental y unidad de apercepción", d:"Para que un conjunto de percepciones sea experiencia de algo y no una dispersión, todas deben poder ser acompañadas por un mismo yo pienso. Esa unidad sintética de apercepción es, para Kant, el punto más alto de toda la filosofía trascendental: no un alma sustancial, no un objeto que se pueda observar por dentro, sino la condición formal de que haya un único campo de experiencia. Aquí se libra su discusión con Descartes. El cogito cartesiano concluía de la certeza del pensar la existencia de una sustancia pensante duradera; Kant llama paralogismo a ese paso y sostiene que solo tenemos conciencia de la actividad de unificar, no intuición de un yo sustancial. De ahí una consecuencia desconcertante y decisiva para su ética: incluso a mí mismo me conozco como fenómeno, tal como me aparezco en el tiempo del sentido interno, no como soy en mí. El yo noumenal, el que es libre y legisla la ley moral, no puede ser objeto de conocimiento — solo puede ser pensado."},
   {t:"Buena voluntad y el deber", d:"Kant abre la Fundamentación afirmando que nada puede ser considerado bueno sin restricción salvo una buena voluntad. La inteligencia, el coraje, la constancia, incluso la moderación pueden volverse peligrosos en manos de un canalla; hasta la felicidad sin buena voluntad resulta intolerable a un espectador imparcial. Y precisa que la buena voluntad no es buena por lo que logra, sino por el querer mismo: aunque una desgracia le impidiera cumplir cualquiera de sus propósitos, brillaría como una joya por sí misma. De ahí la distinción central entre obrar conforme al deber y obrar por deber. El comerciante que no estafa porque le conviene a su reputación hace lo correcto sin mérito moral; quien conserva la vida por inclinación natural tampoco muestra nada; solo cuando la inclinación falta o empuja en contra, y aun así se obra por respeto a la ley, la acción tiene valor moral pleno. Schiller lo satirizó con la queja del que sirve a sus amigos con gusto y sospecha por eso no ser virtuoso, y Kant admitió después que la inclinación no vuelve mala la acción: solo que no es lo que le da su valor."},
   {t:"Imperativo categórico y sus formulaciones", d:"Un imperativo hipotético manda condicionalmente —si querés aprobar, estudiá— y por eso su fuerza depende de un fin que uno puede abandonar. El imperativo categórico manda sin condición, porque no ordena un medio para algo sino la forma misma de una voluntad racional. Kant lo enuncia en tres formulaciones que declara equivalentes en el fondo aunque distintas en su modo de acercarlo a la intuición. La de la ley universal exige obrar solo según aquella máxima que pueda quererse como ley universal, y su prueba no es un cálculo de consecuencias sino un examen de coherencia: la máxima de la promesa falsa, universalizada, destruye la institución misma de prometer y se autodestruye. La de la humanidad como fin en sí manda no usar nunca a la humanidad, en uno mismo o en otro, solo como medio, y descansa en la distinción entre precio y dignidad: lo que tiene precio admite equivalente, lo que tiene dignidad no. La del reino de los fines pide obrar como miembro legislador de una comunidad ideal en la que cada uno es a la vez autor y súbdito de la ley. Kant distingue además dos modos de fallar la prueba: hay máximas que ni siquiera pueden pensarse como universales —deber perfecto— y otras que pueden pensarse pero no quererse sin contradecir lo que como seres necesitados queremos —deber imperfecto, como el de ayudar."},
   {t:"Autonomía frente a heteronomía", d:"Autonomía significa literalmente darse a sí mismo la ley. Para Kant, una voluntad es autónoma cuando el principio que la determina no proviene de ningún objeto deseado ni de ninguna autoridad exterior, sino de su propia razón en cuanto legisladora universal. Toda moral que fundamente el deber en otra cosa —la felicidad, el placer, la perfección, la voluntad de Dios, la costumbre de la comunidad— es heterónoma: manda desde fuera y, en el fondo, solo puede producir imperativos hipotéticos, porque siempre se podrá preguntar por qué me importa ese fin. Aquí se anudan la libertad y la ley moral en lo que Kant llama una relación recíproca: una voluntad libre no es una voluntad sin ley, que sería puro azar, sino una que se somete solo a la ley que ella misma da. De ahí también su definición de Ilustración como la salida del ser humano de una minoría de edad de la que él mismo es culpable, y su consigna: atrévete a servirte de tu propio entendimiento. La objeción persistente es si una ley puramente formal, sin contenido tomado de la experiencia, puede realmente decirnos qué hacer — es la crítica del formalismo vacío que Hegel convertirá en arma."}
 ],
 conexion:"<b>Hegel</b> acusará a Kant de dejar un noúmeno inaccesible fuera de la razón, e intentará superar esa frontera con la dialéctica.",
 dialogo:{titulo:"El asesino en la puerta", lineas:[
   {quien:"Estudiante", texto:"Profesor, tengo un caso. Alguien golpea mi puerta con un cuchillo y me pregunta si mi amigo está escondido adentro. Está adentro. ¿Debo decir la verdad?"},
   {quien:"Kant", texto:"Debés decir la verdad. La veracidad en las declaraciones es un deber formal hacia la humanidad entera, no un favor que se hace a quien lo merece."},
   {quien:"Estudiante", texto:"Entonces su ética entrega a mi amigo al cuchillo por respetar una regla."},
   {quien:"Kant", texto:"Fijate en qué dice exactamente el argumento. Si mentís, te volvés causa de todo lo que siga, incluso de lo imprevisible: quizá tu amigo salió por el fondo mientras hablabas y tu mentira lo pone justo en el camino del asesino. Si decís la verdad, el crimen sigue siendo del criminal."},
   {quien:"Estudiante", texto:"Eso es un cálculo de consecuencias, y usted dijo que las consecuencias no cuentan."},
   {quien:"Kant", texto:"Tenés razón en que suena así, y es la objeción que me hizo Benjamin Constant. Mi respuesta de fondo no es esa: es que la máxima me está permitido mentir cuando lo juzgo necesario no puede pensarse como ley universal sin destruir la confianza que hace posible cualquier declaración. Si eso cae, mentir tampoco sirve.", nota:"El ensayo de 1797 donde Kant sostiene esto es el texto suyo más rechazado, incluso por kantianos. Muchos sostienen que el propio sistema ofrece una salida: negarse a declarar, cerrar la puerta o callar no es mentir, y el asesino, al usarme como instrumento, ya rompió las condiciones de una declaración."},
   {quien:"Estudiante", texto:"¿Y la segunda formulación? El asesino me está usando como medio para encontrar a su víctima. ¿No tengo un deber más fuerte hacia mi amigo, que también es un fin en sí?"},
   {quien:"Kant", texto:"Esa es la pregunta seria, y es la que muestra que mi ética tiene un problema que yo traté con demasiada rigidez: qué hacer cuando dos deberes perfectos parecen chocar. Yo sostuve que un verdadero conflicto de deberes es imposible; mis lectores encontraron que el caso lo produce igual."},
   {quien:"Estudiante", texto:"Cambio de tema, entonces. Usted dice que soy libre. Pero también dice que todo lo que ocurre en el tiempo tiene una causa anterior, y mis decisiones ocurren en el tiempo."},
   {quien:"Kant", texto:"Ambas cosas son verdaderas y no se contradicen porque no hablan del mismo punto de vista. Como fenómeno, tu acción está enteramente determinada y un psicólogo con datos suficientes podría predecirla. Como noúmeno, sos el autor de tu carácter y por eso respondés por ella."},
   {quien:"Estudiante", texto:"Pero usted mismo escribió que del yo noumenal no podemos conocer absolutamente nada. ¿Cómo sé entonces que ese yo libre existe y que es el mío?"},
   {quien:"Kant", texto:"No lo sabés por conocimiento teórico; lo sabés porque debés. La conciencia de estar sometido a la ley moral es lo que llamo el hecho de la razón, y la libertad es su condición: sin ella el deber sería una quimera.", nota:"Este es el punto exacto donde el sistema se apoya en sí mismo. Si la libertad se prueba desde el deber, y el deber solo obliga a un ser libre, hay que decidir si es un círculo o un genuino punto de partida práctico — es la discusión abierta desde Schopenhauer hasta hoy."},
   {quien:"Estudiante", texto:"Un utilitarista diría que todo esto se resuelve preguntando qué acción produce menos sufrimiento, y que mi amigo vive."},
   {quien:"Kant", texto:"Y yo le preguntaría de dónde saca que el sufrimiento de cada uno cuenta igual, si no es de la dignidad que primero hay que reconocer a cada persona. Además, esa cuenta permite sacrificar a uno por muchos; la mía prohíbe usar a nadie solo como medio, aunque salga más barato."},
   {quien:"Estudiante", texto:"Prefiero su prohibición y desconfío de su ejemplo del asesino."},
   {quien:"Kant", texto:"Entonces hiciste exactamente lo que pido: no aceptaste la ley por mi autoridad sino que la examinaste con tu propia razón. Sapere aude. Eso, y no el acuerdo conmigo, es la mayoría de edad."}
 ]},
 actividades:[
   {t:"Pasar un dilema propio por la prueba de universalización", d:"Elegí una decisión real que estés postergando y que te tiente a hacer una excepción con vos mismo: copiar en algo, exagerar un mérito en un currículum, faltar a una promesa incómoda, no devolver un dinero que nadie reclama. Escribí primero la máxima en primera persona y con total honestidad, incluyendo el motivo (no vale formularla de modo que suene bien: cuando me convenga y nadie se entere, haré X). Después universalizala y preguntate dos cosas por separado: ¿puedo siquiera pensar un mundo donde todos actúen así, o la máxima se autodestruye como la de la promesa falsa? Y si puedo pensarlo, ¿puedo quererlo, sabiendo que alguna vez voy a estar del otro lado? Cerrá anotando si el resultado cambió tu decisión y, sobre todo, si tuviste que reformular la máxima varias veces hasta que la prueba diera lo que querías — eso último es el dato más interesante del ejercicio."},
   {t:"Cazar imperativos en el lenguaje de todos los días", d:"Durante un día anotá diez frases imperativas que escuches o digas: en el aula, en la publicidad, en casa, en las noticias. Clasificá cada una como imperativo hipotético —manda un medio para un fin que uno podría abandonar— o categórico —manda sin condición—. Vas a descubrir que casi todo lo que suena moral es en realidad hipotético encubierto: estudiá para tener futuro, sé honesto porque te conviene a la larga, no mientas que después se sabe. Reescribí tres de esas frases en versión estrictamente categórica y discutí en un párrafo qué pierden y qué ganan al perder el premio. Terminá con la pregunta incómoda: ¿alguna de tus diez frases sobrevive sin ninguna promesa de recompensa?"},
   {t:"Juicio al caso del asesino en la puerta", d:"Organizá un debate en tres bancas, con roles escritos de antemano. La primera defiende la posición literal de Kant en el ensayo de 1797: mentir es siempre ilícito y quien miente se hace responsable de lo imprevisible. La segunda defiende al utilitarista: la única pregunta relevante es qué acción produce menos daño, y la vida del amigo pesa más que la veracidad de una declaración. La tercera —la más difícil y la más productiva— defiende a Kant contra Kant: sostiene que el propio sistema permite negarse a declarar o cerrar la puerta sin mentir, y que el asesino, al usarme como instrumento para su fin, ha roto las condiciones de una declaración con valor jurídico. Al terminar, cada participante escribe media página respondiendo si la rigidez del deber absoluto es un defecto del sistema o justamente lo que lo hace capaz de resistir las excepciones cómodas que todos nos concedemos."}
 ],
 cuestionario:[
   {q:"Si el imperativo categórico es puramente formal y no toma ningún contenido de la experiencia, ¿puede realmente decirnos qué hacer?", p:"Kant sostiene que sí, porque la prueba de universalización no calcula resultados sino que detecta contradicciones en la máquina misma de la máxima: la promesa falsa universalizada anula la posibilidad de prometer. Hegel replicó que la forma sola es vacía y que la contradicción solo aparece si uno ya presupone la institución que quiere defender — si no existiera la propiedad, la máxima de robar no se contradiría. Vale la pena rehacer el ejercicio con una máxima cualquiera y ver cuánto trabajo hace la formulación elegida: casi siempre se puede describir la misma acción con una máxima que pasa la prueba y con otra que no."},
   {q:"¿El deber de no mentir sigue valiendo frente al asesino que pregunta dónde está tu amigo?", p:"Kant respondió que sí, en un ensayo de 1797 contra Benjamin Constant, y es la página suya que más lectores ha perdido. Su argumento tiene dos capas: una consecuencialista y débil —no podés prever qué produce tu mentira—, y otra formal y más fuerte —la máxima de mentir cuando lo juzgo necesario destruye la confianza que hace posible toda declaración—. Contra él se suele sostener que la segunda formulación protege a la víctima, que negarse a declarar no es mentir, y que el asesino ya rompió las condiciones de una declaración veraz. El caso obliga a decidir si la rigidez es un defecto corregible dentro del sistema o su rasgo constitutivo."},
   {q:"Si nunca accedemos a las cosas en sí, ¿en qué sentido sigue siendo conocimiento lo que tenemos, y con qué derecho afirmamos que el noúmeno existe?", p:"Kant respondería que ganamos necesidad y universalidad al precio de la metafísica tradicional: la física newtoniana queda fundada, la pretensión de conocer el alma, el mundo como totalidad y Dios queda cancelada. Pero la segunda mitad de la pregunta es la objeción de Jacobi, que pesa más: afirmar que la cosa en sí afecta nuestra sensibilidad usa la categoría de causa fuera de la experiencia, justamente lo que Kant prohíbe. Fichte y Hegel sacaron la conclusión radical de eliminar el noúmeno; otros lectores sostienen que basta entenderlo como concepto límite negativo, sin compromiso existencial alguno."},
   {q:"Kant sostiene que ni siquiera a vos mismo te conocés como sos en sí. ¿Qué queda entonces del yo libre que legisla la ley moral?", p:"Queda pensado, no conocido. En el sentido interno me aparezco en el tiempo y por tanto determinado como cualquier fenómeno; el yo trascendental no es un objeto sino la condición formal de que mis representaciones formen una experiencia unificada. La libertad se afirma desde el lado práctico, por el hecho de la razón: debo, luego puedo. El problema es evidente y sigue abierto: una libertad que no se manifiesta en ningún momento del tiempo no parece poder explicar por qué esta acción concreta, hoy, fue mía. Schopenhauer intentó salvarlo con un carácter inteligible elegido fuera del tiempo, y muchos consideran que ahí el kantismo paga su precio más alto."},
   {q:"Mill objeta que Kant, al probar sus ejemplos, en realidad muestra que las consecuencias de una máxima universalizada serían indeseables, no que sea lógicamente contradictoria. ¿Se sostiene la objeción?", p:"Se sostiene con fuerza en algunos ejemplos y no en otros. El caso de la promesa falsa parece genuinamente autodestructivo: si todos prometieran sin intención de cumplir, prometer dejaría de significar algo y la máxima no podría ni siquiera ejecutarse. Pero el del talento descuidado o el de no ayudar al necesitado funcionan distinto: Kant admite que pueden pensarse universalizados y que lo que falla es que no podemos quererlos, porque como seres necesitados vamos a requerir ayuda alguna vez — y eso ya es un argumento sobre lo que querríamos, no sobre coherencia pura. Esa grieta entre deberes perfectos e imperfectos es el mejor lugar para discutir si la frontera entre deontología y consecuencialismo es tan nítida como ambas partes suelen suponer."}
 ],
 cadena:{ titulo:"Cuando la ley universal parece chocar consigo misma", intro:"Un razonamiento en ramas sobre la pregunta que el propio Kant del diálogo reconoce como seria: ¿qué pasa cuando dos deberes que pasan la prueba de universalización parecen exigir cosas opuestas? Las ramas llevan a distintas respuestas kantianas —y a una que ya no lo es del todo—.", inicio:"n1", nodos:{
   n1:{ pregunta:"Tu amiga Clara te contó, bajo promesa de secreto, que dejó la carrera hace seis meses y que no se anima a decírselo a su familia. Su madre te llama preocupada y te pregunta directamente: «¿Clara sigue yendo a la facultad?». Tenés dos máximas a la vista: «cumplo mis promesas» y «no miento». Parecen chocar. ¿Por dónde empezás?", opciones:[
     {texto:"Examino cada máxima con la prueba de universalización, a ver cuál sobrevive.", va:"n2a"},
     {texto:"Reviso si de verdad chocan: quizás hay una acción que no viola ninguna de las dos.", va:"n2b"} ]},
   n2a:{ pregunta:"Universalizás. «Romper mis promesas cuando me conviene» se autodestruye: si todos lo hicieran, nadie aceptaría una promesa. «Mentir cuando me conviene» también: nadie creería ninguna declaración. Las máximas contrarias a los dos deberes fallan. ¿Qué concluís?", opciones:[
     {texto:"Que tengo dos deberes perfectos en conflicto real: haga lo que haga, violo uno.", va:"n3a"},
     {texto:"Que la prueba me dice qué no hacer, pero no qué hacer cuando todo parece prohibido.", va:"n3b"} ]},
   n3a:{ pregunta:"Kant niega que esto pueda ocurrir. En la Introducción a la Metafísica de las costumbres escribe que un conflicto de deberes es inconcebible: si dos reglas se oponen, una de ellas no es deber en ese caso. Lo que puede haber es un choque de fundamentos de obligación, y entonces prevalece el más fuerte. ¿Cuál es el más fuerte aquí?", opciones:[
     {texto:"El de no mentir: la veracidad es la condición de toda declaración, y sin ella ni siquiera las promesas valen algo.", final:{tipo:"bien", texto:"Es un razonamiento genuinamente kantiano: en el ensayo de 1797 contra Constant, la veracidad es el deber formal sobre el que descansan todos los contratos, incluida la promesa, así que romperla socava también aquello que querías proteger. Pero fijate lo que hiciste: jerarquizaste dos deberes con un argumento que Kant no ofrece en general. Él dice que prevalece el fundamento más fuerte y no dice cómo medirlo. W. D. Ross construirá sobre ese hueco su teoría de los deberes prima facie: varios deberes que valen en principio y un juicio que decide en cada caso. Hiciste ética rossiana con materiales kantianos."}},
     {texto:"El de la promesa: le di mi palabra a Clara y ella confió en mí.", final:{tipo:"revisar", texto:"La lealtad importa, pero pensá qué tendrías que hacer para cumplirla si la madre insiste: decirle que sí, que Clara sigue yendo. Eso es mentir, y para Kant una mentira nunca es el medio lícito para cumplir otro deber. Tu intuición de proteger a Clara es buena, pero no te obliga a mentir. Volvé al comienzo y probá la rama que busca una acción que no viole ninguno de los dos deberes."}} ]},
   n3b:{ pregunta:"Es, casi palabra por palabra, la objeción de Hegel al formalismo: la universalización filtra, pero no produce contenido. Kant tiene otra formulación, sin embargo. ¿Qué te dice la fórmula de la humanidad —tratar a toda persona siempre también como fin, nunca solo como medio— sobre este caso?", opciones:[
     {texto:"Que no puedo usar a la madre como medio mintiéndole, pero tampoco a Clara exponiéndola sin su consentimiento.", va:"n4b"},
     {texto:"Que la madre, al preguntarme, me usa como medio para vigilar a Clara, así que puedo mentirle.", final:{tipo:"revisar", texto:"Es tentador, y se parece al argumento que algunos kantianos usan contra el asesino en la puerta: quien me usa como instrumento para un fin injusto pierde el derecho a mi veracidad. Pero la madre no es el asesino: su pregunta es legítima y nace de la preocupación. Si la fórmula de la humanidad autorizara mentirle a cualquiera cuya pregunta nos incomoda, dejaría de restringir algo. Volvé un paso y probá la otra lectura."}} ]},
   n4b:{ pregunta:"Entonces tratás a las dos como fines. ¿Qué acción concreta lo logra?", opciones:[
     {texto:"Le digo a la madre que eso tiene que preguntárselo a Clara, y a Clara le digo que no voy a mentir por ella.", final:{tipo:"bien", texto:"Llegaste a la salida que muchos kantianos señalan: negarse a declarar no es mentir. Remitir a la fuente respeta la veracidad —no afirmás nada falso— y respeta la confianza de Clara, a la que además tratás como agente responsable de su propia verdad. El costo es real: la madre probablemente sospeche. Pero la ética kantiana nunca prometió que el deber salga gratis; prometió que no tendrías que volverte autor de un engaño para cumplirlo."}},
     {texto:"Le digo a la madre algo verdadero pero engañoso: «La vi hace poco con apuntes».", final:{tipo:"revisar", texto:"Es la verdad engañosa, y no es una salida limpia desde Kant. Aunque la frase no sea literalmente falsa, está calculada para producir en la madre una creencia que sabés falsa. La máxima «engaño sin decir nada falso» no se universaliza mejor que la de mentir, y la fórmula de la humanidad lo detecta todavía más rápido: la madre sigue siendo usada como medio, solo que con más habilidad. Volvé y probá la otra respuesta."}} ]},
   n2b:{ pregunta:"Buscás una acción que no viole ninguno de los dos. Es lo que Kant supone que siempre existe, puesto que un verdadero conflicto de deberes le parece inconcebible. ¿Cuál sería?", opciones:[
     {texto:"Reservarme: «Eso preguntáselo a Clara». No miento y no rompo la promesa.", va:"n3c"},
     {texto:"Una evasiva suave: «No sé bien, hace tiempo que no hablamos de eso».", final:{tipo:"revisar", texto:"Si es falso que no sabés, es una mentira aunque suene amable: afirmás algo que sabés falso con la intención de que la otra persona lo crea. Kant no tiene una categoría de mentira menor; la gravedad está en la forma de la máxima, no en el tamaño de la falsedad. Volvé y buscá una respuesta que no afirme nada falso."}} ]},
   n3c:{ pregunta:"La reserva no es mentira. Pero la madre insiste: «Si no me lo decís, es porque algo pasa». Tu silencio ya comunica algo. ¿Cambia eso tu deber?", opciones:[
     {texto:"No: soy responsable de lo que afirmo, no de lo que ella infiere de mi silencio.", final:{tipo:"bien", texto:"Es la distinción kantiana entre lo que declaro y lo que otros deducen. La veracidad es un deber sobre mis afirmaciones; si la madre saca conclusiones correctas de mi reserva, no hubo engaño y tampoco revelé lo que se me confió. El resultado para Clara puede ser el mismo que si hubieras hablado: Kant no promete que el deber proteja de las consecuencias, sino que te protege de convertirte en su autor mediante un acto ilícito. Si esto te parece frío, estás en buena compañía: es la objeción de Benjamin Constant."}},
     {texto:"Sí: si el silencio revela el secreto, igual lo rompí. Tendría que haber disimulado.", final:{tipo:"revisar", texto:"Disimular para que el silencio no delate es fingir, y fingir con palabras es mentir. Además, tu razonamiento supone que la promesa te obliga a garantizar un resultado —que la madre no se entere—, cuando lo que prometiste es no revelar. Los deberes kantianos regulan las máximas de tus acciones, no los estados del mundo que tendrías que asegurar a cualquier precio. Pensar la promesa como obligación de resultado es pensarla en clave consecuencialista. Volvé un paso."}} ]}
 }},
 reconstruccion:[
   { titulo:"La promesa falsa (Fundamentación, segunda sección)",
     consigna:"Reconstruí el ejemplo con el que Kant muestra cómo falla una máxima ante la prueba de la ley universal. Una pieza convierte el argumento en otra cosa: dejala afuera y ordená el resto.",
     piezas:[
       {id:"k1", texto:"Estoy en apuros y necesito dinero. Sé que nadie me lo prestará si no prometo devolverlo en un plazo fijo, y sé también que no podré devolverlo.", tipo:"premisa"},
       {id:"k2", texto:"Mi máxima sería: cuando creo necesitar dinero, lo pido prestado y prometo devolverlo, aunque sé que nunca lo haré.", tipo:"premisa"},
       {id:"k3", texto:"Pregunto entonces qué pasaría si esa máxima se volviera ley universal: que cualquiera que se crea en apuros pueda prometer lo que no piensa cumplir.", tipo:"premisa"},
       {id:"k4", texto:"En ese mundo nadie creería ninguna promesa: todos se reirían de ella como de un vano pretexto, y prometer se volvería imposible.", tipo:"premisa"},
       {id:"k5", texto:"Por lo tanto, la máxima no puede pensarse como ley universal sin destruirse a sí misma, porque depende de la misma confianza que anularía: hacer una promesa falsa es contrario al deber.", tipo:"conclusion"},
       {id:"kx", texto:"Además, si todos prometieran en falso habría más desconfianza, menos crédito y una economía peor, y eso sería perjudicial para todos.", tipo:"distractor"}
     ],
     ordenCorrecto:["k1","k2","k3","k4","k5"],
     explicacion:"El argumento no calcula daños: muestra una contradicción en la concepción. La máxima del que promete en falso es parasitaria: solo funciona si los demás siguen creyendo en las promesas, es decir, si él es una excepción. Universalizada, destruye la práctica de la que se alimenta y ni siquiera puede ejecutarse. La pieza sobrante es la lectura de Mill, que acusa a Kant de apelar en el fondo a consecuencias indeseables; ponerla dentro del argumento es cambiarlo por otro. Dos puntos para discutir: la prueba depende de cómo se describa la máxima —«prometer en falso para salvar a mi familia de la ruina» parece más difícil de rechazar—, y Hegel objetará que la contradicción solo aparece si ya se presupone la institución de la promesa."},
   { titulo:"De dónde sale la fórmula de la humanidad (Fundamentación, 428-429)",
     consigna:"Reconstruí cómo Kant llega a la exigencia de tratar a la humanidad siempre como fin. Una pieza pertenece a otra formulación del imperativo: dejala afuera y ordená el resto.",
     piezas:[
       {id:"h1", texto:"Si hay un imperativo categórico, tiene que haber algo cuya existencia tenga en sí misma un valor absoluto, un fin en sí, y no solo un valor condicionado por algún deseo.", tipo:"premisa"},
       {id:"h2", texto:"Los objetos de las inclinaciones no pueden serlo: valen solo porque alguien los desea, y las inclinaciones mismas están tan lejos de tener valor absoluto que todo ser racional querría librarse de ellas.", tipo:"premisa"},
       {id:"h3", texto:"Las cosas sin razón tampoco: tienen solo un valor relativo, como medios. Queda la naturaleza racional, que por eso se llama persona y no cosa.", tipo:"premisa"},
       {id:"h4", texto:"Y así se representa necesariamente cada ser humano su propia existencia; y todo otro ser racional se la representa del mismo modo, por el mismo fundamento racional que vale para mí.", tipo:"premisa"},
       {id:"h5", texto:"Por lo tanto: obrá de tal modo que uses la humanidad, tanto en tu persona como en la de cualquier otro, siempre al mismo tiempo como fin y nunca solo como medio.", tipo:"conclusion"},
       {id:"hx", texto:"Obrá como si la máxima de tu acción fuera a convertirse, por tu voluntad, en ley universal de la naturaleza.", tipo:"distractor"}
     ],
     ordenCorrecto:["h1","h2","h3","h4","h5"],
     explicacion:"El argumento avanza por eliminación: si ha de haber un mandato incondicionado, necesita un fin incondicionado (h1); no lo son los objetos del deseo ni las inclinaciones (h2), ni las cosas (h3); queda la naturaleza racional. El paso decisivo es h4: lo que cada uno se representa subjetivamente —mi existencia como fin— se vuelve principio objetivo porque descansa en un fundamento racional que vale igual para todos. La pieza sobrante es la fórmula de la ley de la naturaleza, que Kant declara equivalente en el fondo pero que se obtiene por otro camino, desde la forma de la ley y no desde la idea de un fin en sí. Notá el «solo» de la conclusión: usar al panadero como medio para conseguir pan no está prohibido; lo prohibido es tratarlo únicamente como medio. Y el punto débil para discutir está en h4: muchos lectores sostienen que el paso de «cada uno se valora a sí mismo» a «cada uno debe valorar a todos» es justamente lo que había que probar."}
 ],
 dilemas:[
   { titulo:"La pregunta del padre",
     intro:"En el diálogo, Kant sostiene que mentir es ilícito incluso ante el asesino en la puerta, y admite que su ética trató con demasiada rigidez el choque de deberes. Este caso pone la misma pregunta en una escuela: ¿se puede mentir para proteger a alguien, y si no, qué queda?",
     pasos:[
       { id:"p1", situacion:"Martín, de 16 años, te contó en confianza que es gay y que no se atreve a decírselo a su padre, que ya reaccionó con violencia ante un comentario suyo sobre el tema. Una tarde el padre aparece en la escuela, alterado: «Me dijeron que mi hijo anda diciendo cosas. ¿A usted le contó algo?». ¿Qué respondés?", opciones:[
         {texto:"«No, no me contó nada.»", consecuencia:"Mentiste para protegerlo, y casi cualquiera entiende por qué. Pero Kant te pediría formular la máxima con honestidad: «cuando juzgo que alguien podría hacer daño con una verdad, le miento». Universalizada, deja toda declaración bajo la sospecha de que el otro decidió que yo no merecía la verdad. Y hay algo más cercano: según el ensayo contra Constant, acabás de hacerte responsable de lo que siga de tu mentira.", va:"p2a"},
         {texto:"«Lo que los estudiantes me cuentan en confianza no se lo cuento a nadie. Si quiere saber algo, hable con él.»", consecuencia:"Es la reserva: no afirmás nada falso y no traicionás a Martín. Kant distingue con cuidado entre no decir y decir lo falso; lo primero puede ser lícito, lo segundo nunca. Pero el padre puede leer tu reserva como una confirmación.", va:"p2b"},
         {texto:"«Sí, me contó que es gay.»", consecuencia:"El enunciado es verdadero, pero Kant no exige decir todo lo que uno sabe: exige que lo que uno dice no sea falso. Revelar lo que te confiaron no es cumplir un deber de veracidad: es romper una confianza que también obliga, y tratar a Martín como medio para salir de una situación incómoda. La rigidez kantiana está en la prohibición de mentir, no en una obligación de contar.", va:"p2c"} ]},
       { id:"p2a", situacion:"El padre se va tranquilo. Dos semanas después se entera de todo por otro lado, vuelve furioso —«usted me mintió en la cara»— y le prohíbe a Martín seguir viniendo a la escuela. ¿Cómo evaluás lo que hiciste?", opciones:[
         {texto:"Hice lo correcto: lo que pasó después es responsabilidad del padre, no mía.", consecuencia:"Es el argumento de Kant, pero invertido. En el ensayo de 1797 sostiene que quien dice la verdad no responde por lo que otros hagan con ella, mientras que quien miente se vuelve responsable de todas las consecuencias, incluso de las imprevisibles. Por su lógica, tu mentira te hace cargar con parte de lo que siguió. Podés rechazar esa asimetría —muchos lo hacen—, pero tenés que decir por qué.", va:"p3"},
         {texto:"Me equivoqué, pero no por el resultado: por no haber buscado una salida que no fuera mentir.", consecuencia:"Es la autocrítica más kantiana posible: no la de quien lamenta el resultado sino la de quien revisa su máxima. Kant no dice que las consecuencias no importen; dice que no son lo que hace buena o mala a una voluntad. Tu revisión apunta exactamente ahí.", va:"p3"} ]},
       { id:"p2b", situacion:"El padre insiste y levanta la voz: «Si no me dice nada es porque sabe algo. Si me está ocultando algo, voy a hablar con la dirección». La reserva empieza a costarte. ¿Qué hacés?", opciones:[
         {texto:"Mantengo la reserva y aviso a la dirección y al equipo de orientación que Martín puede estar en riesgo.", consecuencia:"Sostuviste la veracidad y la confianza, y además cumpliste un deber que Kant llama imperfecto pero real: procurar el bien ajeno. Lo hiciste informando lo que vos observaste —el enojo del padre, el riesgo— y no lo que Martín te confió. La ética kantiana no se agota en abstenerse: también manda actuar.", va:"p3"},
         {texto:"Cedo un poco: «Me dijo que tiene dudas sobre algunas cosas, nada más».", consecuencia:"Es una media verdad diseñada para calmar al padre. Su propósito es que crea que no hay nada importante, cosa que sabés falsa. Desde la prueba kantiana, la máxima de «engañar sin decir nada literalmente falso» no se universaliza mejor que la de mentir, y además dejaste a Martín más expuesto que con la reserva.", va:"p3"} ]},
       { id:"p2c", situacion:"El padre se va sin decir nada. Al día siguiente Martín falta, y un compañero te cuenta que en su casa hubo gritos toda la noche. Martín te escribe: «¿Por qué le contaste?». ¿Qué le respondés?", opciones:[
         {texto:"«Porque no podía mentirle a tu padre.»", consecuencia:"Es falso que tus únicas opciones fueran mentir o contar: había una tercera, la reserva, y Kant te la habría señalado antes que nadie. Confundir la prohibición de mentir con un deber de revelar es uno de los malentendidos más comunes sobre su ética, y aquí el costo lo pagó otro.", va:"p3"},
         {texto:"«Me equivoqué. No tenía que mentir, pero tampoco tenía que contarlo.»", consecuencia:"Reconocés la distinción entre veracidad y revelación que se te escapó en el momento. La fórmula de la humanidad lo vuelve visible: al contar lo que Martín te confió, lo trataste como medio para salir del paso y no como alguien con derecho a decidir sobre su propia verdad.", va:"p3"} ]},
       { id:"p3", situacion:"Días después, en una reunión de docentes, alguien dice: «Kant es impracticable: con él, Martín estaría peor». ¿Qué respondés?", opciones:[
         {texto:"«Es cierto: en casos así hay que mentir, y una ética que no lo permite está equivocada.»", consecuencia:"Es la posición de Constant y de la mayoría de los lectores actuales, y es defendible. Pero tiene un precio que conviene decir en voz alta: si se puede mentir cuando uno juzga que el otro no merece la verdad, la pregunta pasa a ser quién juzga y con qué criterio, que es exactamente lo que Kant temía.", va:null},
         {texto:"«No es cierto: Kant prohíbe mentir, pero no obliga a revelar, y deja lugar a la reserva y a la protección activa.»", consecuencia:"Es la defensa de Kant contra la lectura rígida, y muestra que la alternativa entre mentir y delatar era falsa. Su debilidad es que hay casos —el asesino que ya sabe que estás ocultando algo— donde la reserva no protege a nadie, y ahí Kant sigue diciendo lo mismo.", va:null},
         {texto:"«Depende: Kant acierta en la regla, pero se equivoca al no admitir excepciones cuando está en juego la integridad de alguien.»", consecuencia:"Es una posición cercana a los deberes prima facie de Ross: la veracidad obliga en principio, pero puede ceder ante un deber más fuerte. No es kantiana en sentido estricto —Kant niega que un deber ceda ante otro—, pero muchos la consideran lo que queda del kantismo después del caso Constant. La tarea pendiente es decir qué vuelve «más fuerte» a un deber sin volver al cálculo de consecuencias.", va:null} ]}
     ],
     rubrica:[
       "Formulé por escrito la máxima de cada opción con honestidad, incluyendo el motivo, antes de evaluarla.",
       "Distinguí entre mentir (afirmar lo falso), reservarme (no declarar) y revelar lo confiado, y no traté el caso como una elección entre solo dos opciones.",
       "Apliqué la fórmula de la humanidad a las tres personas involucradas: Martín, su padre y yo.",
       "Puedo explicar la asimetría de responsabilidad que Kant sostiene en el ensayo contra Constant, y decir si la acepto y por qué.",
       "Identifiqué qué deberes eran perfectos (no mentir, no traicionar una confianza) y cuáles imperfectos (ayudar a Martín), y cómo se relacionaron.",
       "Separé el valor moral de mi decisión de sus consecuencias, sin por eso afirmar que las consecuencias no importan.",
       "Formulé al menos una objeción seria a mi propia respuesta final."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.kant = { lecturas:[
 {titulo:"Fundamentación de la metafísica de las costumbres: la buena voluntad y el imperativo categórico", fuente:"Biblioteca Virtual Miguel de Cervantes", url:"https://www.cervantesvirtual.com/obra-visor/fundamentacion-de-la-metafisica-de-las-costumbres--0/html/dcb0941a-2dc6-11e2-b417-000475f5bda5_3.html",
  extracto:`Kant abre con una de las frases más citadas de la filosofía moderna: «ni en el mundo, ni, en general, tampoco fuera de él, es posible pensar nada que pueda ser considerado como bueno sin restricción, a no ser tan sólo una buena voluntad». El talento, el ingenio, el valor, la riqueza o incluso la moderación pueden volverse malos si la voluntad que los usa es perversa. La buena voluntad «no es buena por lo que efectúe o realice, no es buena por su adecuación para alcanzar algún fin que nos hayamos propuesto; es buena sólo por el querer, es decir, es buena en sí misma».

De ahí sale la distinción entre obrar «conforme al deber» y obrar «por deber». El comerciante que no estafa a un cliente inexperto porque le conviene comercialmente actúa conforme al deber, pero no por deber: su acción no tiene valor moral. Kant fuerza el ejemplo hasta el caso extremo del hombre que conserva la vida sin ninguna inclinación a vivir — solo entonces, dice, «tiene su máxima un contenido moral».

El paso siguiente es a la ley. Si lo que da valor a la acción no son sus consecuencias, tiene que ser la forma del principio que la guía. Y una forma que vale con independencia de todo fin particular solo puede ser la universalidad. Así se formula el imperativo categórico: «obra sólo según aquella máxima por la cual puedas querer que al mismo tiempo se convierta en ley universal».

Kant lo somete a cuatro ejemplos. El de la promesa falsa es el más claro: alguien en apuros piensa pedir dinero prometiendo devolverlo sin intención de hacerlo. Universalizada, la máxima se autodestruye, «pues la universalidad de una ley que diga que cualquiera, después de creerse necesitado, puede prometer lo que se le ocurra con el propósito de no cumplirlo, haría imposible la promesa misma y el fin que con ella pudiera obtenerse». No es que el resultado sea malo: es que la máxima resulta contradictoria al pensarse como universal.

La segunda formulación introduce la dignidad: «obra de tal modo que uses la humanidad, tanto en tu persona como en la persona de cualquier otro, siempre como un fin al mismo tiempo y nunca solamente como un medio». Kant distingue aquí precio y dignidad: «aquello que tiene precio puede ser sustituido por algo equivalente; en cambio, lo que se halla por encima de todo precio y, por tanto, no admite nada equivalente, eso tiene una dignidad».

La tercera es la autonomía: la voluntad racional no recibe la ley de fuera sino que se la da a sí misma, y por eso el reino de los fines es una comunidad de legisladores. Obedecer una ley que uno mismo se dio racionalmente es, para Kant, la única forma de libertad compatible con la necesidad natural.`,
  comentario:"Este texto es el corazón de la ética deontológica: el valor moral se juega enteramente en el principio, nunca en el resultado. La prueba de universalización no es un cálculo de consecuencias sino una prueba de coherencia lógica — por eso el ejemplo de la promesa falsa habla de una máxima que «se autodestruye». Contrastalo con Aristóteles: donde uno pregunta «¿qué haría una persona virtuosa?», Kant pregunta «¿podría esta máxima ser ley para todos?»."}
], preguntasLectura:[
 {q:"Según Kant, ¿por qué es buena la buena voluntad?", opciones:["Por los buenos resultados que produce","Por el querer mismo, en sí misma","Porque la aprueba la comunidad","Porque maximiza la felicidad general"], r:"Por el querer mismo, en sí misma", why:"«Es buena sólo por el querer» — explícitamente no por su adecuación a ningún fin."},
 {q:"En el ejemplo de la promesa falsa, ¿qué falla al universalizar la máxima?", opciones:["Que produciría mucho sufrimiento","Que la máxima se autodestruye: haría imposible la promesa misma","Que sería ilegal","Que la mayoría no la aceptaría"], r:"Que la máxima se autodestruye: haría imposible la promesa misma", why:"Kant busca una contradicción lógica al pensar la máxima como ley universal, no un mal resultado."},
 {q:"¿Qué distinción introduce Kant entre precio y dignidad?", opciones:["El precio es alto y la dignidad baja","Lo que tiene precio admite equivalente; lo que tiene dignidad, no","Son sinónimos en su ética","La dignidad se compra con virtud"], r:"Lo que tiene precio admite equivalente; lo que tiene dignidad, no", why:"Es la base de la segunda formulación: tratar a la humanidad siempre también como fin, nunca solo como medio."}
]};
