/* ============================================================
   Ficha: nietzsche  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"nietzsche", trad:"europea", nombre:"Friedrich Nietzsche", fechas:"1844–1900 · Alemania", escuela:"Crítica genealógica de la moral", icon:"⚡", profundizada:true,
 tesis:"Los valores morales no son eternos ni caídos del cielo: tienen una historia, y esa historia puede rastrearse. La moral que Occidente llama simplemente moral nació, según Nietzsche, de una rebelión de los débiles contra los fuertes, y su motor no fue el amor sino el resentimiento. Cuando la fe que la sostenía deja de ser creíble —eso es la muerte de Dios— queda al descubierto un vacío de valores que él llama nihilismo, y que puede vivirse como agotamiento o como oportunidad. Su propuesta no es otra tabla de mandamientos sino una tarea: transmutar los valores desde una afirmación total de la vida, medida por la prueba del eterno retorno y encarnada en la figura del Übermensch.",
 obras:[
   {t:"Así habló Zaratustra", d:"Escrita entre 1883 y 1885 en cuatro partes —la cuarta impresa en apenas cuarenta ejemplares para amigos—, es la obra que Nietzsche consideraba su regalo más grande a la humanidad y también la más malentendida. No es un tratado sino un libro en prosa poética, deliberadamente construido con la cadencia del Lutero de la Biblia alemana: un profeta baja de la montaña después de diez años de soledad para anunciar algo, y descubre que nadie quiere escucharlo. Allí están las piezas centrales del Nietzsche tardío: las tres transformaciones del espíritu —camello, león, niño—, el anuncio del Übermensch, el desprecio por el último hombre que inventó la felicidad y parpadea, el pasaje de la visión y el enigma donde se formula el eterno retorno, y los discursos sobre los trasmundanos, los despreciadores del cuerpo y las tres cosas malvadas. Su forma no es un adorno: al escribir en parábolas y no en argumentos, Nietzsche obliga al lector a interpretar en lugar de aceptar conclusiones, lo cual es coherente con su tesis de que no hay hechos sino interpretaciones. También es la razón por la que se convirtió en el texto más fácil de citar fuera de contexto, y el más saqueado por lectores que nunca leyeron el resto."},
   {t:"Más allá del bien y del mal", d:"Publicada en 1886 con el subtítulo Preludio de una filosofía del futuro, es el regreso de Nietzsche a la prosa argumentativa después de Zaratustra, y funciona como la mejor puerta de entrada a su pensamiento maduro. Su primer capítulo es una demolición de los prejuicios de los filósofos: sostiene que todo gran sistema ha sido la confesión involuntaria de su autor, una autobiografía disfrazada de razonamiento, y que la voluntad de verdad nunca se preguntó a sí misma por qué la verdad y no la mentira. Desde ahí ataca la creencia en los opuestos de valor —como si lo verdadero no pudiera proceder de lo falso, o lo desinteresado del egoísmo—, la gramática del sujeto que nos hace suponer un yo detrás del pensar, y el concepto de causa como ficción útil. La segunda mitad introduce el perspectivismo, la distinción entre moral de señores y moral de esclavos, la crítica a la democracia y al socialismo como herederos secularizados del cristianismo, y algunas de sus páginas sobre las mujeres que hoy resultan indefendibles y que conviene leer sin coartadas. El título dice exactamente lo que promete: no ir más allá de lo bueno y lo malo, sino más allá de la oposición moral entre el Bien y el Mal."},
   {t:"La genealogía de la moral", d:"Aparecida en 1887 y presentada por su propio autor como un escrito polémico destinado a completar y aclarar el libro anterior, es la obra más sistemática de Nietzsche y la que más ha marcado a la filosofía posterior. Consta de tres tratados con una unidad de método: en lugar de preguntar qué es bueno, pregunta de dónde vienen nuestros juicios de valor y qué tipo de vida se expresa en ellos. El primer tratado opone bueno y malo a bueno y malvado, y describe la rebelión de los esclavos en la moral como una inversión de valores nacida del ressentiment. El segundo reconstruye el origen de la culpa a partir de la relación material entre acreedor y deudor —en alemán Schuld significa a la vez deuda y culpa—, explica el castigo como mnemotecnia y describe la mala conciencia como la crueldad que, impedida de descargarse hacia afuera, se vuelve contra uno mismo. El tercero examina el ideal ascético y llega a su conclusión más citada: el ser humano prefiere querer la nada a no querer. El método tiene un límite que conviene declarar: las etimologías de Nietzsche son con frecuencia inventadas y su historia no resiste el escrutinio filológico, de modo que el valor de la obra está en la hipótesis psicológica, no en la documentación."},
   {t:"El nacimiento de la tragedia", d:"Su primer libro, de 1872, escrito a los veintisiete años cuando era catedrático de filología clásica en Basilea, y el que arruinó su carrera académica: Ulrich von Wilamowitz-Moellendorff lo demolió en un panfleto por su falta de rigor filológico y los estudiantes dejaron de inscribirse en sus cursos. Su tesis es que la tragedia griega nació de la tensión entre dos impulsos que Nietzsche bautiza con nombres de dioses: lo apolíneo, principio de forma, medida, individuación y bella apariencia, y lo dionisíaco, principio de embriaguez, disolución del individuo y unión con el fondo doloroso de la existencia. Contra la imagen serena y blanca de Grecia que había heredado de Winckelmann, sostiene que los griegos fueron pesimistas que conocieron el horror de la vida y lo soportaron transfigurándolo en arte. La tragedia habría muerto a manos de Eurípides y, detrás de él, de Sócrates, el hombre teórico que creyó que el pensamiento puede llegar hasta el fondo del ser y corregirlo. Nietzsche mismo repudió después buena parte del libro en una Tentativa de autocrítica de 1886, donde lo llama mal escrito, pesado y afectado por la música de Wagner — pero conservó el par apolíneo y dionisíaco como su primera intuición decisiva."},
   {t:"Ecce Homo", d:"Escrito en las últimas semanas lúcidas de 1888 y publicado recién en 1908, es una autobiografía intelectual con capítulos titulados Por qué soy tan sabio, Por qué soy tan inteligente, Por qué escribo libros tan buenos y Por qué soy un destino. El tono desconcierta y ha alimentado la lectura de que allí ya se anuncia el derrumbe psíquico del año siguiente, pero leído con atención el libro hace dos cosas muy útiles. La primera es un repaso de toda su obra, uno por uno, en el que Nietzsche explica qué se propuso en cada libro y cómo quiere ser entendido — es la fuente más directa para saber qué entendía él por eterno retorno, por Übermensch o por transmutación de los valores. La segunda es una defensa preventiva contra la mala lectura: advierte expresamente que no quiere santos ni discípulos, y su fórmula para la grandeza humana es amor fati, no querer nada distinto de lo que es, ni hacia adelante ni hacia atrás. El texto tiene además un valor documental incómodo: fue el manuscrito más manipulado por su hermana Elisabeth, que controló el archivo durante décadas, suprimió pasajes durísimos sobre ella misma y sobre su madre, y construyó con ese material la imagen del Nietzsche precursor del nacionalismo alemán que él mismo había despreciado en vida."}
 ],
 conceptos:[
   {t:"La muerte de Dios", d:"El anuncio no aparece en boca de un ateo satisfecho sino de un loco que corre al mercado con una linterna encendida en plena mañana, en el aforismo 125 de La gaya ciencia, y que termina rompiendo la linterna contra el suelo ante gente que se ríe de él. Su frase completa importa: Dios ha muerto, nosotros lo hemos matado, y a continuación pregunta cómo nos consolaremos, quién nos limpiará la sangre y con qué agua podríamos purificarnos. No es una tesis sobre la existencia de Dios sino un diagnóstico cultural: la fe cristiana ha dejado de ser el fundamento efectivo de la ciencia, la moral y el derecho europeos, aunque las instituciones sigan funcionando por inercia. Y Nietzsche insiste en dos cosas que la divulgación suele perder. Primero, que el acontecimiento es enorme y todavía no llegó a los oídos de nadie: los rayos necesitan tiempo, dice el loco, esto todavía está en camino. Segundo, que la consecuencia no es alegre. Si cae el garante, caen con él las verdades que se apoyaban en él, y eso deja al ser humano, en su imagen, desatado de su sol y cayendo hacia atrás, hacia los costados, hacia todas las direcciones a la vez. El propio Nietzsche llama a esto el acontecimiento más grande y más terrible a la vez."},
   {t:"El Übermensch", d:"Zaratustra lo presenta en el prólogo con una fórmula que fija su sentido: el ser humano es algo que debe ser superado, una cuerda tendida entre el animal y el Übermensch, una cuerda sobre un abismo. Lo primero que hay que fijar es lo que no es. No es una raza, no es un tipo biológico, no es un superhombre en el sentido de un ejemplar más fuerte de la especie, y no es un programa eugenésico: Nietzsche lo opone a la selección natural tanto como a la moral del rebaño, y la traducción más honesta sería algo como el ultrahombre o el hombre que se sobrepasa. Es una figura de superación de sí, no de dominación de otros. Su contrafigura en el mismo prólogo lo aclara mejor que cualquier definición: el último hombre, que ya no sabe despreciar nada, que inventó la felicidad, que tiene su pequeño placer para el día y su pequeño placer para la noche, que parpadea y a quien la multitud aclama pidiendo ser ese. Frente a ese achatamiento sin grandeza, el Übermensch es quien puede crear valores propios sin necesitar un cielo que los garantice, quien es leal a la tierra y no inventa esperanzas ultraterrenas. Nietzsche nunca describe a ninguno en concreto, y esa vaguedad deliberada es al mismo tiempo la fuerza de la figura y el hueco por el que entraron sus peores intérpretes."},
   {t:"La voluntad de poder", d:"Es el concepto más ambicioso y más discutido de Nietzsche. En Más allá del bien y del mal lo propone como una hipótesis: si pudiéramos reducir toda la vida pulsional a una sola forma fundamental de voluntad, habría que llamarla voluntad de poder, y el mundo visto desde dentro sería eso y nada más. Su núcleo no es el deseo de mandar sobre otros sino la tendencia de todo lo vivo a crecer, a expandirse, a incorporar y a imponer forma; la dominación política es solo una de sus expresiones, y a menudo una expresión pobre. Contra Schopenhauer, que veía en el fondo del mundo una voluntad de vivir ciega y sufriente a la que hay que renunciar, Nietzsche sostiene que lo vivo no busca conservarse sino aumentar, y que la autoconservación es apenas una consecuencia. Contra Darwin, objeta que la lucha por la existencia explica la supervivencia pero no la creación de formas nuevas. Aquí aparece también la objeción más seria: una tesis que afirma qué es el mundo en su fondo parece exactamente el tipo de metafísica que Nietzsche denuncia en los demás, y Heidegger construirá sobre eso su lectura de Nietzsche como el último metafísico. Conviene saber además que el libro titulado La voluntad de poder no existe: es una compilación póstuma de fragmentos armada y ordenada por su hermana Elisabeth y por Peter Gast, con un orden que Nietzsche nunca aprobó."},
   {t:"El eterno retorno de lo mismo", d:"Nietzsche lo llama el pensamiento más pesado, y lo formula por primera vez en el aforismo 341 de La gaya ciencia con la forma de una escena: un demonio se desliza en tu soledad más solitaria y te dice que esta vida, tal como la viviste y la estás viviendo, tendrás que vivirla innumerables veces más, y que no habrá nada nuevo en ella, sino que cada dolor, cada alegría, cada pensamiento y suspiro volverán en el mismo orden y sucesión, incluida esta araña y este claro de luna entre los árboles. La pregunta que sigue es la que hace todo el trabajo: te arrojarías al suelo rechinando los dientes y maldiciendo al demonio, o le responderías que es un dios y que jamás oíste nada más divino. Hay un debate erudito genuino sobre el estatuto de la idea. En algunos fragmentos póstumos Nietzsche ensaya una demostración cosmológica —tiempo infinito, fuerza finita, luego repetición necesaria— que es físicamente endeble y que él nunca publicó. En los textos que sí publicó, el retorno funciona como prueba ética y existencial: una piedra de toque para medir si uno afirma su vida o la soporta. En Zaratustra, cuando el enano lo despacha diciendo que el tiempo mismo es un círculo, Zaratustra se enoja — señal de que reducirlo a cosmología es, para él, trivializarlo."},
   {t:"La transmutación de todos los valores", d:"Umwertung aller Werte es el proyecto que Nietzsche anunció como su obra capital y que nunca escribió como tal; lo que quedó son sus últimos libros, El anticristo entre ellos, y montañas de fragmentos. La palabra no significa invertir los valores, poniendo como bueno lo que se tenía por malo, aunque él mismo juegue con esa provocación. Significa cambiar el patrón con que se mide: dejar de preguntar si una acción es buena o mala según una tabla heredada y preguntar qué tipo de vida se expresa en ella, si una ascendente o una declinante. De ahí el orden del trabajo, que es el que da sentido a toda su obra tardía. Primero la genealogía, que muestra que los valores tienen historia y por lo tanto no son necesarios. Después la crítica, que los evalúa preguntando a qué forma de vida sirven. Recién entonces la creación, que es la parte que Nietzsche no completa y sobre la que es notablemente parco. Las tres transformaciones de Zaratustra ordenan exactamente esa secuencia: el camello carga la tradición, el león dice el sagrado No y conquista libertad, pero el propio Nietzsche advierte que el león no es capaz de crear valores nuevos — eso corresponde al niño, inocencia, olvido y un santo decir sí. La crítica sola sigue siendo reactiva, porque sigue definida por aquello que niega."},
   {t:"Moral de señores y moral de esclavos", d:"No son dos clases sociales ni dos épocas históricas sino dos maneras opuestas de generar valores, y Nietzsche observa que casi todas las morales reales las mezclan. En la moral de señores la valoración nace de sí misma y es afirmativa: el noble se llama bueno a sí mismo, y bueno significa aquí logrado, fuerte, veraz, capaz; lo malo, schlecht, es lo bajo, lo fallido, lo que despierta desprecio, y es un concepto derivado y casi indiferente. En la moral de esclavos la valoración nace de la reacción: empieza diciendo No a lo que está afuera, a lo otro, a lo que no es uno mismo, y construye primero la figura del malvado, böse —que es el noble, visto con miedo y odio—, para deducir después, como una ocurrencia posterior, un bueno que consiste en ser lo contrario de él: manso, humilde, paciente, inofensivo. La distinción más útil para llevarla a la práctica es esa asimetría en el orden: una moral empieza por afirmarse a sí misma, la otra empieza por negar al otro. Hay dos malentendidos que conviene desactivar. El primero es leer esto como una recomendación de comportarse como señor; Nietzsche está haciendo psicología histórica, no escribiendo un manual de conducta. El segundo es olvidar que él reconoce expresamente la enorme fecundidad de la moral de esclavos: la interiorización que produjo volvió al ser humano un animal interesante, profundo, capaz de historia y de arte."},
   {t:"Nihilismo activo y nihilismo pasivo", d:"Nihilismo, en su definición más seca, es que los valores supremos se desvalorizan y falta la respuesta al para qué. Nietzsche no es un nihilista que lo celebre: lo diagnostica como el estado inevitable al que llega Europa cuando la honestidad que el propio cristianismo cultivó se vuelve contra sus dogmas y los destruye. Su distinción decisiva es entre dos formas. El nihilismo pasivo es un declive de la fuerza del espíritu: uno reconoce que ya no hay sentido y se resigna, busca anestesias, se conforma con el pequeño placer y el confort, o se refugia en sucedáneos del absoluto —el nacionalismo, el cientificismo, cualquier fe de repuesto—. El nihilismo activo es la misma pérdida vivida como violencia destructiva: signo de fuerza acrecentada, destruye lo que ya no cree para dejar sitio libre, y es imprescindible pero no es todavía una salida, porque el que destruye sigue dependiendo de lo que destruye. La superación completa no es ninguno de los dos sino la creación de valores que no necesiten garante, lo que en Zaratustra corresponde al niño y no al león. Vale la pena notar la ambigüedad que Nietzsche mismo señala: el nihilismo puede ser un síntoma de agotamiento o un estado patológico intermedio, como el que atraviesa un convaleciente."},
   {t:"Lo apolíneo y lo dionisíaco", d:"Es su primera gran intuición y la que menos abandonó. Apolo es el dios de la forma, del contorno nítido, del sueño y de la bella apariencia; es el principio de individuación, lo que permite que haya cosas separadas, medida, escultura, epopeya. Dioniso es el dios de la embriaguez, de la música, de la fiesta en la que el individuo se disuelve y se reconcilia con la naturaleza y con los otros; su verdad es que debajo de toda forma hay un fondo que no tiene forma y que es a la vez creador y destructor. La tesis de El nacimiento de la tragedia es que el arte griego alcanza su cumbre no cuando uno vence al otro sino cuando ambos se acoplan: la tragedia da forma apolínea —personajes, diálogo, escena— a un contenido dionisíaco que de otro modo sería insoportable. De ahí su frase de que solo como fenómeno estético están eternamente justificados la existencia y el mundo. Su consecuencia polémica es la lectura de Sócrates como el punto de quiebre: con él aparece el hombre teórico que cree que el pensamiento puede llegar hasta el fondo del ser y corregirlo, y el optimismo de que la virtud es saber sustituye a la sabiduría trágica que soportaba el horror sin negarlo. Que esto sea historia de la cultura o mitología personal de Nietzsche es exactamente lo que le discutieron los filólogos de su tiempo."},
   {t:"Ressentiment y mala conciencia", d:"Son los dos mecanismos psicológicos que sostienen toda la genealogía, y Nietzsche los deja en francés y en alemán respectivamente porque ninguna traducción corriente los recoge. El ressentiment no es el enojo, que se descarga y se agota, sino el rencor de quien no puede responder con actos y por eso responde con una venganza imaginaria: incapaz de descargarse hacia afuera, la reacción se vuelve creadora de valores, inventa un malvado responsable de su desgracia y se consuela definiéndose a sí mismo como su contrario. El pasaje más agudo del primer tratado es el de los corderitos que odian a las aves de rapiña y concluyen que ser un cordero es bueno; Nietzsche observa que exigirle a la fuerza que no se manifieste como fuerza supone un sujeto detrás del hacer que la gramática nos hace imaginar, cuando no hay ningún ser detrás del hacer: el hacer es todo. La mala conciencia es el segundo movimiento y tiene lugar cuando el ser humano queda encerrado en la sociedad y en la paz: los instintos que no pueden descargarse hacia afuera se vuelven hacia adentro, y así nace el alma con profundidad, el hombre que se hace daño a sí mismo por falta de enemigos exteriores. Nietzsche la llama una enfermedad, pero una enfermedad como lo es el embarazo: dolorosa y fecunda. Con el ideal ascético el círculo se cierra, porque el sacerdote no elimina el sufrimiento, le da un sentido —sos vos el culpable— y con eso vuelve soportable lo insoportable al precio de dirigir el rencor contra uno mismo."}
 ],
 conexion:"<b>Heidegger</b> leerá a Nietzsche como el último metafísico de Occidente, el que invierte a Platón sin escapar del todo de su marco: al proclamar la voluntad de poder como el ser de todo lo que es, seguiría respondiendo a la vieja pregunta metafísica en lugar de abandonarla.",
 dialogo:{titulo:"El discípulo que quiere ser Zaratustra", lineas:[
   {quien:"Discípulo", texto:"Maestro, leí todo lo que escribió y decidí seguirlo. Dígame qué debo hacer y lo haré."},
   {quien:"Zaratustra", texto:"Acabás de deshacer en una frase todo lo que leíste. Si me seguís, sos un camello con un dueño nuevo; el dragón de las escamas doradas cambió de escamas, nada más."},
   {quien:"Discípulo", texto:"Pero usted anuncia valores. Alguien tiene que enseñarlos."},
   {quien:"Zaratustra", texto:"Yo derribo, que no es lo mismo. El león conquista libertad para un nuevo crear, pero el león no crea nada: su obra es el sagrado No. Crear corresponde al niño, y el niño no imita a nadie, porque es una rueda que se mueve por sí misma."},
   {quien:"Discípulo", texto:"Entonces déme al menos el criterio. Si Dios murió y no hay tabla, ¿cómo distingo un valor bueno de uno malo?"},
   {quien:"Zaratustra", texto:"Cambiá la pregunta. No preguntes si un valor es bueno: preguntá quién lo formuló, desde qué necesidad, y qué clase de vida se expresa en él. Una vida que asciende y quiere más, o una que ya no puede y por eso llama virtud a lo que no es capaz de hacer."},
   {quien:"Discípulo", texto:"Eso no es un criterio, es una sospecha. Y puede volverse contra usted: ¿qué clase de vida se expresa en su filosofía, un hombre enfermo, solo, sin cátedra y sin lectores?"},
   {quien:"Zaratustra", texto:"Buena estocada, y la merezco. Escribí que toda gran filosofía ha sido la confesión involuntaria de su autor; sería cómodo que la mía fuera la excepción. Pero fijate qué hiciste: usaste mi método contra mí. Eso es exactamente lo que pido."},
   {quien:"Discípulo", texto:"Entonces pruebe conmigo su pesa más pesada. Tengo que decidir algo que vengo postergando hace dos años."},
   {quien:"Zaratustra", texto:"Imaginá que un demonio se desliza esta noche en tu soledad más solitaria y te dice que esta vida, tal como la viviste y la estás viviendo, tendrás que vivirla una vez más e innumerables veces más, sin nada nuevo, cada dolor y cada alegría en el mismo orden, incluida esta conversación y esta araña en el rincón. ¿Te tirarías al suelo maldiciéndolo, o le dirías que nunca oíste nada más divino?"},
   {quien:"Discípulo", texto:"Con la decisión postergada dentro, lo maldeciría."},
   {quien:"Zaratustra", texto:"Entonces ya tenés tu respuesta, y no te la di yo. El eterno retorno no te dice qué elegir: te muestra qué estás soportando en lugar de querer."},
   {quien:"Discípulo", texto:"Una duda de otro tipo. ¿El demonio dice la verdad? ¿El mundo se repite realmente?"},
   {quien:"Zaratustra", texto:"Cuando el enano me contestó que el tiempo mismo es un círculo, me enojé con él. Convertirlo en astronomía es la manera más elegante de no tener que responderlo.", nota:"Hay un debate erudito genuino aquí: en fragmentos póstumos que nunca publicó, Nietzsche ensaya una prueba cosmológica del eterno retorno —fuerza finita en tiempo infinito—, físicamente endeble; en los textos publicados funciona como prueba ética. Quién es el Nietzsche auténtico sigue discutiéndose."},
   {quien:"Discípulo", texto:"Última pregunta, y es la que me da miedo hacerle. Hubo quienes tomaron su Übermensch y su voluntad de poder y construyeron con eso una doctrina de raza y de imperio."},
   {quien:"Zaratustra", texto:"Escribí que los antisemitas me daban náuseas, rompí con Wagner por ese motivo y me burlé de la embriaguez nacional alemana hasta quedarme sin amigos. Pero no me escondo detrás de eso: escribí en parábolas, dejé al Übermensch sin ningún contenido concreto y usé un vocabulario de amos y de dureza que sabía que era inflamable."},
   {quien:"Discípulo", texto:"Entonces algo de responsabilidad le toca."},
   {quien:"Zaratustra", texto:"Le toca al texto, que es lo único que queda de un autor. Por eso mi única orden es la que no obedeciste al llegar: perdedme a mí y encontraos a vosotros mismos, y solo cuando todos me hayáis negado volveré entre vosotros.", nota:"El caso histórico es concreto: su hermana Elisabeth Förster-Nietzsche, casada con un propagandista antisemita, controló el archivo después del derrumbe de 1889, compiló y ordenó los fragmentos publicados como La voluntad de poder —un libro que Nietzsche nunca escribió—, censuró cartas y entregó personalmente bastones y ediciones a Hitler. La filología del siglo XX, sobre todo la edición crítica de Colli y Montinari, deshizo buena parte de esa manipulación."}
 ]},
 actividades:[
   {t:"Someter una decisión real a la prueba del eterno retorno", d:"Elegí una decisión concreta que estés postergando o una rutina que sostengas por costumbre: un trabajo, una relación, una carrera, una mudanza que no hacés. Escribí en una página cómo es tu vida hoy con esa decisión sin tomar, con detalle sensorial y sin embellecerla. Después leelo imaginando la escena del aforismo 341: un demonio te informa que vas a vivir exactamente eso, sin una coma distinta, innumerables veces. Anotá cuál fue tu primera reacción física antes de cualquier argumento, porque ese dato es el que interesa. Terminá con dos preguntas críticas y contestalas por escrito: ¿la prueba te dijo qué hacer, o solo te mostró qué estás soportando en lugar de querer? Y la objeción más fuerte: ¿no es este test injusto con quien vive una vida que no eligió, marcada por la pobreza, la enfermedad o la violencia, a quien se le pediría afirmar lo que le fue impuesto?"},
   {t:"Diccionario de señores y esclavos en el habla de todos los días", d:"Durante tres días anotá quince frases valorativas que escuches en tu entorno, en las noticias, en redes o en tu propia boca. Clasificá cada una según el orden en que genera el valor, que es el criterio que da Nietzsche: las que empiezan afirmando algo propio —esto está logrado, esto es fuerte, así se hace bien— y las que empiezan negando a otro y recién después definen lo bueno como su contrario —no somos como ellos, por eso somos buenos—. Marcá cuántas de cada tipo encontraste y en qué contextos aparece cada una. Después hacé la parte incómoda: revisá si al clasificar tendiste a poner del lado señorial las frases que te caen simpáticas. Y respondé por escrito la objeción evidente: la denuncia de que el otro actúa por resentimiento es un arma retórica perfecta para desactivar cualquier reclamo justo de alguien que está abajo, así que ¿cómo se distingue un ressentiment genuino de una demanda legítima de justicia?"},
   {t:"Carta de un espíritu libre sobre un valor heredado", d:"Elegí un valor que recibiste sin haberlo elegido y que todavía gobierna tus decisiones: el sacrificio por la familia, la humildad, la puntualidad, la lealtad institucional, la productividad, el no molestar. Escribí una carta de tres partes. En la primera hacé la genealogía: de dónde te llegó, quién te lo enseñó, a quién le servía que vos lo tuvieras, y qué premios y castigos lo instalaron. En la segunda hacé la evaluación nietzscheana: ¿qué te permite y qué te impide hacer hoy ese valor?, ¿expresa una vida que quiere crecer o una que se protege? En la tercera, la más difícil, hacé el trabajo del niño y no el del león: si decidís conservarlo, reescribilo con tus propias palabras y por tus propias razones, de modo que ya no sea un Tú debes sino un Yo quiero; si decidís soltarlo, escribí con qué lo reemplazás, sin dejar el lugar vacío. Cerrá anotando cuál de las tres partes te costó más — casi siempre es la tercera, y eso es precisamente lo que Nietzsche señala cuando dice que el león no crea."}
 ],
 cuestionario:[
   {q:"Si toda filosofía es la confesión involuntaria de su autor y no hay hechos sino interpretaciones, ¿el perspectivismo no se refuta a sí mismo al afirmarse como verdadero?", p:"Es la objeción clásica de autorrefutación, y tiene fuerza: si toda tesis es solo una perspectiva, también lo es la tesis de que toda tesis es solo una perspectiva. Nietzsche no responde con un sistema sino cambiando lo que se le pide a una posición: no presenta el perspectivismo como una verdad sobre el mundo sino como una práctica de lectura, y llega a escribir que cuantos más ojos distintos sepamos usar para una misma cosa, más completo será nuestro concepto de ella — es decir, propone multiplicar perspectivas, no abolir el conocimiento. Sus defensores contemporáneos distinguen entre un perspectivismo global e insostenible y uno restringido a los juicios de valor, que sí puede sostenerse. Sus críticos replican que Nietzsche argumenta todo el tiempo como si sus genealogías fueran históricamente correctas, lo que ya supone un criterio que no es meramente perspectivo."},
   {q:"¿No es la voluntad de poder exactamente el tipo de metafísica que Nietzsche denuncia en los demás filósofos?", p:"La sospecha es seria y no es nueva. Decir que el mundo visto desde dentro es voluntad de poder y nada más es formular una tesis sobre el fondo último de lo real, es decir, precisamente lo que él acusa a Platón, a Schopenhauer y a los metafísicos de hacer. Heidegger construyó sobre esta grieta toda su lectura: Nietzsche invierte el platonismo —pone lo sensible arriba y lo suprasensible abajo— pero una inversión conserva el esquema que invierte, y por eso sería el último metafísico y no el primer pensador posmetafísico. En su descargo hay dos cosas. La primera es textual: en Más allá del bien y del mal la introduce expresamente como una hipótesis y como un ensayo de interpretación, no como una demostración. La segunda es filológica: el libro sistemático titulado La voluntad de poder no lo escribió él, lo compuso su hermana con fragmentos sueltos, de modo que buena parte del carácter doctrinario del concepto es un artefacto editorial."},
   {q:"¿El Übermensch conduce necesariamente a una política autoritaria, o esa lectura es una distorsión?", p:"Hay que separar tres capas. La primera es documental y favorece a Nietzsche: despreció el antisemitismo, rompió con Wagner por eso, se burló del nacionalismo alemán, y la apropiación nazi se apoyó en una compilación póstuma manipulada por su hermana Elisabeth, que entregó personalmente ediciones a Hitler. Walter Kaufmann y después la edición crítica de Colli y Montinari documentaron esa falsificación. La segunda capa es textual y no lo favorece: hay páginas suyas sobre el orden de rango, sobre la esclavitud como condición de una cultura elevada y sobre la dureza necesaria que no son inventadas por nadie, y que no se disuelven diciendo que son metáforas. La tercera es la pregunta filosófica de fondo, que sigue abierta: una figura deliberadamente vacía de contenido, que ordena crear valores propios sin ningún criterio compartido, ¿ofrece alguna resistencia conceptual a quien quiera llenarla con un contenido brutal? Quien defiende a Nietzsche debe explicar por qué la superación de sí excluye la dominación del otro, y esa explicación no está escrita en sus libros."},
   {q:"La genealogía explica de dónde viene un valor. ¿Eso muestra que el valor es falso, o es una falacia genética?", p:"Es la objeción más limpia que se le puede hacer, y hay que tomarla en serio: mostrar el origen innoble de una creencia no refuta su contenido, igual que el origen interesado de un descubrimiento científico no lo vuelve falso. Nietzsche tiene una respuesta parcial: él no pretende refutar la moral cristiana como se refuta un teorema, porque sostiene que en materia de valores no hay nada que refutar, solo tipos de vida que evaluar. Su pregunta no es si el valor es verdadero sino qué vale el valor, y para eso el origen sí es pertinente, porque revela la función que el valor cumplió y sigue cumpliendo. La discusión honesta queda entonces así: si se acepta que los valores no son el tipo de cosa que puede ser verdadera o falsa, la genealogía es legítima; si no se acepta, la genealogía comete efectivamente una falacia genética. Vale la pena notar que Foucault heredó el método completo y que sobre él pesa exactamente la misma objeción."},
   {q:"¿Qué hacer con las páginas de Nietzsche sobre las mujeres y con su desprecio por las culturas que llama débiles — se separan del resto de su filosofía?", p:"Las lecturas serias se reparten en tres posiciones y conviene conocerlas las tres. La primera sostiene que son escoria de época, prescindibles, y que el método genealógico sobrevive sin ellas; es la más cómoda y la más débil, porque esas páginas no son notas al pie sino que usan el mismo vocabulario de fuerza, rango y decadencia que sostiene el resto. La segunda sostiene lo contrario: que la retórica viril y jerárquica es constitutiva y arrastra consigo al sistema entero. La tercera, la más productiva, es la que practicaron feministas como Luce Irigaray, Sarah Kofman y Judith Butler, y pensadores poscoloniales que leyeron a Nietzsche a través de Foucault: usar sus herramientas contra sus propios contenidos, aplicando la genealogía a la construcción histórica del género o de la raza, es decir, mostrando que también la masculinidad y la superioridad europea que él da por naturales tienen una historia y un interés detrás. Es, de paso, exactamente lo que él pedía cuando escribió que quien se limita a seguirlo lo traiciona."}
 ],
 cadena:{ titulo:"¿Y si la voluntad de poder también es una fábula?", intro:"Un razonamiento en ramas sobre la objeción que el propio Nietzsche parece invitar: si toda filosofía es la confesión de su autor y toda metafísica un prejuicio, ¿qué estatuto tiene la voluntad de poder? Las ramas no desembocan en un veredicto único sino en distintos Nietzsches posibles, cada uno con su precio.", inicio:"n1", nodos:{
   n1:{ pregunta:"Nietzsche escribe que toda gran filosofía ha sido la confesión involuntaria de su autor (Más allá del bien y del mal, §6) y denuncia la creencia de los metafísicos en un fondo último de las cosas. Treinta parágrafos después escribe que el mundo visto desde dentro sería voluntad de poder y nada más (§36). ¿Hay aquí una contradicción?", opciones:[
     {texto:"Sí: está afirmando qué es el mundo en su fondo, que es exactamente lo que critica en los demás.", va:"n2a"},
     {texto:"No necesariamente: depende de cómo presenta esa tesis.", va:"n2b"} ]},
   n2a:{ pregunta:"Es la lectura de Heidegger: Nietzsche invierte el platonismo sin salir de él, y la voluntad de poder es su respuesta a la vieja pregunta por el ser de todo lo que es. Pero si aceptás eso, ¿qué pasa con la genealogía, que lee los valores como expresiones de voluntad de poder?", opciones:[
     {texto:"Cae con ella: sin la tesis metafísica, la genealogía no tiene de qué hablar.", va:"n3a"},
     {texto:"Se salva: la genealogía puede funcionar como psicología de los valores sin una tesis sobre el mundo entero.", final:{tipo:"bien", texto:"Es la estrategia de buena parte de la lectura anglosajona reciente: separar un Nietzsche naturalista, que formula hipótesis psicológicas sobre el origen de los valores y puede equivocarse en los detalles (Brian Leiter), de un Nietzsche cosmológico que especula en fragmentos que nunca publicó. Maudemarie Clark llega a sostener que §36 no expone la doctrina de Nietzsche sino que ilustra lo que hacen los filósofos cuando su voluntad de poder se vuelve teoría. Ganaste un Nietzsche más defendible; el precio es que queda más chico y menos ambicioso del que él creyó ser."}} ]},
   n3a:{ pregunta:"Entonces tendrías una filosofía que se destruye a sí misma. Pero antes de cerrar el caso: en §22 Nietzsche dice que la física es solo una interpretación del mundo, ofrece la suya, y agrega: «suponiendo que también esto sea solo interpretación —y ustedes estarán bastante ansiosos por objetarlo—, bueno, tanto mejor». ¿Cómo leés ese gesto?", opciones:[
     {texto:"Como una evasión: se blinda contra toda crítica declarando que su tesis es solo una interpretación.", final:{tipo:"revisar", texto:"Es una lectura posible, pero notá que no refuta el gesto, solo lo acusa de mala fe. La jugada de §22 tiene una estructura precisa: si su tesis es interpretación, también lo es la de sus adversarios, y la pregunta pasa a ser qué interpretación ve más, cuál es más rica, a qué vida sirve. Podés rechazar ese criterio, pero entonces tenés que decir desde qué lugar no interpretativo lo hacés. Volvé un paso y reconsiderá."}},
     {texto:"Como una apuesta: acepta que su tesis es interpretación y la ofrece como la que mejor da cuenta de los fenómenos.", final:{tipo:"bien", texto:"Es la lectura perspectivista coherente: la voluntad de poder no como verdad última sino como la hipótesis más fecunda disponible, que se mide por lo que permite ver. La objeción no desaparece —¿con qué criterio no perspectivista decidimos qué interpretación ve más?—, pero cambia de forma: deja de ser una contradicción lógica y se vuelve una pregunta abierta sobre cómo preferir entre interpretaciones. Es, de hecho, la pregunta en la que Nietzsche vivió."}} ]},
   n2b:{ pregunta:"Mirás el texto. §36 está escrito entero en condicional —«suponiendo que...», «suponiendo, finalmente, que...»— y Nietzsche lo presenta como un ensayo. ¿Qué cambia eso?", opciones:[
     {texto:"Mucho: no afirma una metafísica, ensaya una hipótesis que podría abandonar.", va:"n3b"},
     {texto:"Poco: una hipótesis que pretende explicar todo lo que existe sigue siendo una tesis sobre el todo.", final:{tipo:"revisar", texto:"Es una objeción válida, y muestra que el condicional por sí solo no salva a Nietzsche: una hipótesis universal sigue teniendo alcance universal. Pero antes de concluir que es metafísica en el sentido que él critica, fijate qué les reprocha a los metafísicos: no que hagan hipótesis generales, sino que inventen un mundo verdadero detrás de este, inmutable y opuesto al devenir. La voluntad de poder es, a su manera, lo contrario: devenir sin fondo estable. Seguí la otra rama para ver si esa diferencia se sostiene."}} ]},
   n3b:{ pregunta:"Si es una hipótesis, tiene que competir con otras. ¿Contra qué hipótesis la mide Nietzsche, y con qué criterio?", opciones:[
     {texto:"Contra la voluntad de vivir de Schopenhauer y la lucha por la existencia de Darwin: le parecen peores porque no explican el crecimiento ni la creación de formas nuevas.", final:{tipo:"bien", texto:"Exacto. En §13 escribe que la autoconservación es solo una de las consecuencias indirectas y más frecuentes de la voluntad de poder, no su principio; y contra Darwin sostiene que la lucha por la existencia describe situaciones de escasez, cuando lo corriente en la naturaleza es la abundancia y el derroche. Si la voluntad de poder es una hipótesis explicativa en competencia, puede discutirse en su terreno. Llegaste a un Nietzsche que argumenta, no que proclama, aunque el criterio de «explicar mejor» es uno que tendría que justificar sin apelar a la verdad que pone en cuestión."}},
     {texto:"Contra ninguna: su criterio es que esa hipótesis afirma la vida, y con eso basta.", va:"n4b"} ]},
   n4b:{ pregunta:"Si el criterio para aceptar una tesis es que afirme la vida, y no que sea verdadera, ¿qué pasaría si alguien encontrara una tesis falsa que afirmara la vida todavía mejor?", opciones:[
     {texto:"Nietzsche tendría que preferirla: él mismo dice que la falsedad de un juicio no es una objeción contra él.", final:{tipo:"bien", texto:"Es literal: en §4 escribe que la falsedad de un juicio no es todavía una objeción, y que la cuestión es hasta qué punto favorece y conserva la vida. Llegaste al punto más radical y más inquietante de Nietzsche: la verdad deja de ser el valor supremo y pasa a ser juzgada. El problema es que esa tesis se ofrece, a su vez, como verdadera sobre nuestra relación con la verdad. Nietzsche vivió dentro de esa tensión sin resolverla, y sus lectores todavía discuten si es un defecto o su tema."}},
     {texto:"La rechazaría: su honestidad intelectual le impide aceptar una mentira útil.", final:{tipo:"bien", texto:"También es Nietzsche. La probidad (Redlichkeit) es para él la virtud que queda en pie cuando caen las demás: la veracidad que el cristianismo cultivó y que termina volviéndose contra sus propios dogmas (Genealogía de la moral III, §27). Y ahí está la tensión: la voluntad de verdad es a la vez el arma con que Nietzsche desenmascara y lo que después pone bajo sospecha; la Genealogía termina preguntando qué sentido tiene la voluntad de verdad misma. No elegiste mal: elegiste el otro cuerno de un dilema que Nietzsche deja abierto."}} ]}
 }},
 reconstruccion:[
   { titulo:"La rebelión de los esclavos en la moral (Genealogía de la moral, tratado I)",
     consigna:"Reconstruí cómo, según Nietzsche, el ressentiment produce una moral nueva por inversión de los valores nobles. Una pieza pertenece al segundo tratado: dejala afuera y ordená el resto.",
     piezas:[
       {id:"g1", texto:"Originariamente, «bueno» fue la autodesignación de los nobles: se llamaban buenos a sí mismos —fuertes, logrados, veraces—, y «malo» (schlecht) era apenas un término derivado para lo bajo y vulgar.", tipo:"premisa"},
       {id:"g2", texto:"Los que estaban abajo, impedidos de responder con actos a la fuerza de los nobles, no podían descargar su reacción hacia afuera.", tipo:"premisa"},
       {id:"g3", texto:"Esa reacción contenida se volvió ressentiment, y el ressentiment se volvió creador: engendró valores como una venganza imaginaria.", tipo:"premisa"},
       {id:"g4", texto:"Su primer acto creador es un No a lo otro: concibe primero al «malvado» (böse), que es el noble mismo visto con odio y con miedo.", tipo:"premisa"},
       {id:"g5", texto:"Por lo tanto, el «bueno» de esta moral es un concepto derivado —ser lo contrario del malvado: manso, humilde, paciente—, y así nace la moral de esclavos, invirtiendo los valores nobles.", tipo:"conclusion"},
       {id:"gx", texto:"El deudor que no puede pagar interioriza su deuda como culpa, y así nace la mala conciencia: la crueldad vuelta contra uno mismo.", tipo:"distractor"}
     ],
     ordenCorrecto:["g1","g2","g3","g4","g5"],
     explicacion:"La clave del argumento es una asimetría en el orden de la valoración: la moral noble empieza afirmándose y el «malo» es un agregado secundario; la moral de esclavos empieza negando al otro (g4) y el «bueno» es lo que queda por contraste (g5). Entre ambas está el mecanismo psicológico: una reacción que no puede descargarse en actos (g2) se vuelve creadora de valores (g3). La pieza sobrante pertenece al segundo tratado, sobre la culpa y la mala conciencia: comparte el esquema de la interiorización, pero explica otra cosa. Para discutir: las etimologías en que Nietzsche apoya g1 son en buena parte discutibles, y sobre todo, mostrar que un valor nació del resentimiento no prueba que sea falso; si eso es una falacia genética o una evaluación legítima depende de si se acepta que los valores se juzgan por la vida que expresan."},
   { titulo:"El eterno retorno como prueba (La gaya ciencia 341; Zaratustra)",
     consigna:"Reconstruí el eterno retorno como prueba existencial, tal como lo presentan los textos que Nietzsche publicó. Una pieza viene de los fragmentos póstumos y le da al pensamiento otro estatuto: dejala afuera.",
     piezas:[
       {id:"e1", texto:"Suponé que un demonio te anuncia que esta vida, tal como la viviste y la estás viviendo, se repetirá innumerables veces, sin nada nuevo y en el mismo orden.", tipo:"premisa"},
       {id:"e2", texto:"La pregunta no es si el demonio dice la verdad sobre el cosmos, sino cómo recibirías el anuncio: maldiciéndolo o llamándolo divino.", tipo:"premisa"},
       {id:"e3", texto:"Si ese pensamiento se apoderara de vos, te transformaría o te aplastaría: sobre cada cosa que hicieras pesaría la pregunta «¿querés esto una vez más e innumerables veces más?».", tipo:"premisa"},
       {id:"e4", texto:"Y querer el retorno de un solo instante exige querer todo lo que lo hizo posible, porque nada está aislado: quien dijo sí a una sola alegría dijo sí también a todo dolor.", tipo:"premisa"},
       {id:"e5", texto:"Por lo tanto, el eterno retorno funciona como medida de la afirmación: una vida se mide por si uno podría quererla entera, sin descontar nada, que es lo que Nietzsche llama amor fati.", tipo:"conclusion"},
       {id:"ex", texto:"Como la fuerza del universo es finita y el tiempo infinito, todas las combinaciones posibles de estados tienen que haberse repetido y repetirse necesariamente.", tipo:"distractor"}
     ],
     ordenCorrecto:["e1","e2","e3","e4","e5"],
     explicacion:"El argumento convierte una hipótesis cosmológica en una pregunta práctica: lo decisivo no es si el retorno ocurre (e2) sino qué revela tu reacción ante él (e3). El paso que le da profundidad es e4, tomado de la Canción ebria de Zaratustra: no se puede afirmar un momento aislado, porque todas las cosas están encadenadas; por eso la prueba no admite una versión editada de la propia vida. La pieza sobrante es la prueba cosmológica que Nietzsche ensayó en fragmentos póstumos y nunca publicó: físicamente endeble y, sobre todo, ajena al uso ético del pensamiento; Zaratustra se enoja con el enano cuando este lo reduce a un círculo del tiempo. Para discutir: la prueba tiene una forma parecida a la universalización kantiana, pero en el tiempo en lugar de entre personas; y cabe preguntar si es justa con quien vive una vida que no eligió."}
 ],
 dilemas:[
   { titulo:"La pesa más pesada",
     intro:"En el diálogo, Zaratustra le dice al discípulo que el eterno retorno no le dice qué elegir, sino que le muestra qué está soportando en lugar de querer. Este caso pone esa prueba sobre una decisión dolorosa que ya no se puede deshacer, y sobre otra que todavía está abierta.",
     pasos:[
       { id:"p1", situacion:"Hace seis años rechazaste una beca de doctorado en el exterior para quedarte a cuidar a tu madre, que estaba enferma. Ella murió el año pasado. Hoy das clases en una escuela que te gusta a medias y a veces pensás en la vida que no tuviste. Una noche sin sueño te acordás del demonio del aforismo 341: esta vida, exactamente así, innumerables veces. ¿Cuál es tu primera reacción?", opciones:[
         {texto:"Lo maldigo: no querría repetir esos años de hospital ni la renuncia a la beca.", consecuencia:"Es la reacción honesta, y Nietzsche la valoraría más que una afirmación forzada. El demonio no pide que finjas; pide que veas qué estás soportando en lugar de querer. Lo que descubriste no es un fracaso moral sino un dato: hay una parte de tu vida con la que todavía no te reconciliaste.", va:"p2a"},
         {texto:"Lo acepto: fue lo correcto, y volvería a hacerlo.", consecuencia:"Puede ser genuino, pero mirá la forma de tu respuesta: justificaste la decisión («fue lo correcto»), y el demonio no preguntó eso. Preguntó si la querés, con cada día de hospital incluido. Nietzsche desconfiaría de una afirmación que pasa por el deber: puede ser resignación con buenos modales, el sí del asno de Zaratustra, que dice «I-A» a todo lo que le cargan.", va:"p2b"} ]},
       { id:"p2a", situacion:"Te quedás con la pregunta. Al día siguiente un amigo te dice: «No te castigues. No tuviste opción: hiciste lo que había que hacer». Te alivia. ¿Aceptás ese consuelo?", opciones:[
         {texto:"Sí: si no tuve opción, no tengo nada que reprocharme.", consecuencia:"Es un consuelo real, pero Nietzsche le vería un costo: convierte tu vida en algo que te pasó y no en algo que hiciste. El amor fati no es resignación ante la necesidad sino transformar el «así fue» en un «así lo quise» (Zaratustra, «De la redención»). Si no hubo elección, tampoco hay nada tuyo que afirmar: solo algo que soportar.", va:"p3"},
         {texto:"No: sí tuve opción, elegí quedarme, y tengo que poder hacerme cargo de eso.", consecuencia:"Es el paso que Zaratustra llama redención: la voluntad no puede querer hacia atrás, y por eso sufre del «fue»; la única salida es convertir todo «fue» en un «así lo quise». No significa aprobar cada momento, sino dejar de tratar el pasado como algo que te hicieron.", va:"p3"} ]},
       { id:"p2b", situacion:"Intentás ir más allá de «fue lo correcto» y repasás esos años uno por uno. Algunos momentos te dan orgullo; otros, rabia: contra tu madre, contra tus hermanos que no ayudaron, contra vos. ¿Qué hacés con la rabia?", opciones:[
         {texto:"La reprimo: no es justo sentir rabia contra alguien que se estaba muriendo.", consecuencia:"Es comprensible, y es exactamente el mecanismo que Nietzsche describe en la Genealogía: una reacción que no puede descargarse hacia afuera se vuelve hacia adentro y se convierte en mala conciencia. Él no te pediría que la descargues contra nadie; te pediría que no la escondas, porque lo que se niega así no desaparece: se vuelve culpa.", va:"p3"},
         {texto:"La incluyo: también fue parte de esos años, y si los afirmo, los afirmo con la rabia.", consecuencia:"Es lo que el eterno retorno exige: no un sí a una versión editada de tu vida, sino a la cadena entera, porque cada instante está atado a los otros. Afirmar no es aprobar la rabia ni justificarla; es dejar de necesitar que la vida hubiera sido otra para poder quererla.", va:"p3"} ]},
       { id:"p3", situacion:"Meses después te ofrecen otra oportunidad de doctorado, esta vez posible. Aceptarla implica dejar la escuela y a un grupo de estudiantes con los que estás a mitad de un proyecto. ¿Cómo decidís?", opciones:[
         {texto:"Me pregunto qué decisión podría querer innumerables veces, sabiendo lo que ya sé de mí.", consecuencia:"Es el uso práctico que Nietzsche le da al pensamiento más pesado: no una regla que dicta la respuesta sino una pregunta que se pone ante cada acción. Fijate que no te dice qué elegir. Te pide que elijas algo que puedas querer, no algo que puedas justificar.", va:null},
         {texto:"Acepto: esta vez no voy a sacrificarme por otros.", consecuencia:"Puede ser la decisión correcta, pero cuidado con el motivo: si elegís contra lo que hiciste antes, tu decisión sigue definida por aquello que niega. Es la figura del león, el sagrado No, y Nietzsche advierte que el león todavía no crea. La pregunta es si esta decisión la querés por sí misma o como revancha.", va:null},
         {texto:"La rechazo: ya aprendí que mi lugar está donde me necesitan.", consecuencia:"Puede ser una afirmación genuina o puede ser el camello, que carga lo que le ponen encima y lo llama virtud. Nietzsche no tiene nada contra quedarse; tiene todo contra quedarse porque «así debe ser». La prueba sigue siendo la misma: ¿lo querrías innumerables veces, o solo lo soportarías con dignidad?", va:null} ]}
     ],
     rubrica:[
       "Registré mi primera reacción ante el demonio antes de cualquier justificación, y la tomé como un dato y no como un error.",
       "Distinguí entre justificar una decisión («fue lo correcto») y afirmarla («la quiero de nuevo, entera»).",
       "Identifiqué si en algún paso reaccioné contra algo (el león) en lugar de afirmar algo (el niño).",
       "Reconocí emociones que tendía a reprimir y pude pensarlas con el concepto de mala conciencia de la Genealogía.",
       "Usé el eterno retorno como prueba existencial y no como una tesis sobre la estructura del cosmos.",
       "Puedo explicar qué es el amor fati y por qué no equivale a resignarse.",
       "Formulé la objeción más fuerte a la prueba: ¿es justo pedirle a alguien que afirme sufrimientos que no eligió?"
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.nietzsche = { lecturas:[
 {titulo:"Así habló Zaratustra: las tres transformaciones y el eterno retorno", fuente:"Textos.info — biblioteca digital abierta", url:"https://www.textos.info/friedrich-nietzsche/asi-hablo-zaratustra",
  extracto:`El primer discurso de Zaratustra, «De las tres transformaciones», condensa el programa entero: «Tres transformaciones del espíritu os menciono: cómo el espíritu se convierte en camello, y el camello en león, y el león, por fin, en niño».

El camello es el espíritu de carga, el que pregunta «¿qué es lo más pesado?» y se arrodilla para que lo carguen bien. Representa la moral del deber, la reverencia, la disciplina heredada: humillarse para mortificar la propia soberbia, amar a quienes nos desprecian, alimentarse de las bellotas y la hierba del conocimiento. No es despreciable — es una etapa necesaria de fortalecimiento.

Pero en el desierto más solitario ocurre la segunda transformación: el camello se hace león, «quiere conquistar su libertad y ser señor en su propio desierto». El león se enfrenta al gran dragón cuyas escamas doradas llevan escrito, en cada una, «Tú debes». El león opone su «Yo quiero». Nietzsche es preciso sobre los límites de esta figura: «Crear valores nuevos — tampoco el león es capaz de hacerlo: mas crearse libertad para un nuevo crear — eso sí es capaz de hacerlo el poder del león». El león destruye, no crea; su obra es el «sagrado No».

Por eso hace falta la tercera transformación: «El niño es inocencia y olvido, un nuevo comienzo, un juego, una rueda que se mueve por sí misma, un primer movimiento, un santo decir sí». Solo quien juega sin resentimiento contra lo antiguo puede crear valores nuevos. La crítica, por sí sola, sigue siendo reactiva: sigue definida por aquello que niega.

En «De la visión y el enigma», Zaratustra plantea el eterno retorno ante el enano que lo acompaña. Frente a un portón llamado «Instante», dos caminos infinitos se encuentran, uno hacia atrás y otro hacia adelante. Si todo lo que puede ocurrir ya ocurrió infinitas veces, y este instante arrastra tras de sí todas las cosas venideras, entonces todo tiene que volver, «y también este lento arañarse la piel a la luz de la luna». El enano lo despacha con ligereza —«todo lo recto miente, toda verdad es curva, el tiempo mismo es un círculo»— y Zaratustra se enoja: convertirlo en doctrina cosmológica es trivializarlo.

La versión decisiva está en La gaya ciencia: imaginá que un demonio te dice que vas a revivir esta vida «innumerables veces más», con cada dolor, cada alegría y cada pensamiento en el mismo orden. ¿Te arrojarías al suelo rechinando los dientes, o le responderías «eres un dios y jamás oí nada más divino»? El eterno retorno no es una tesis sobre el tiempo: es un test existencial sobre si afirmás tu vida.`,
  comentario:"Las tres transformaciones ordenan todo el proyecto nietzscheano: la genealogía de la moral es la obra del león, pero Nietzsche advierte explícitamente que destruir valores no equivale a crearlos. Eso responde en parte a la pregunta del cuestionario sobre en qué apoya su preferencia de valores: el criterio es el «santo decir sí» del niño, una afirmación estético-vital, no una demostración. El eterno retorno funciona como piedra de toque de esa afirmación."}
], preguntasLectura:[
 {q:"¿Qué es capaz de hacer el león y qué NO, según Zaratustra?", opciones:["Crea valores nuevos pero no puede destruir","Conquista libertad para crear, pero no crea valores nuevos","Obedece pero no lucha","Juega pero no recuerda"], r:"Conquista libertad para crear, pero no crea valores nuevos", why:"Nietzsche lo dice literalmente: el león logra el «sagrado No», la creación corresponde al niño."},
 {q:"¿Qué representa el gran dragón de escamas doradas?", opciones:["La muerte de Dios","El «Tú debes»: los valores heredados como mandato","El eterno retorno","El Übermensch"], r:"El «Tú debes»: los valores heredados como mandato", why:"Cada escama lleva escrito un «Tú debes» milenario al que el león opone su «Yo quiero»."},
 {q:"Según el texto, ¿cómo debe entenderse el eterno retorno?", opciones:["Como una teoría física sobre el tiempo circular","Como un test existencial sobre si afirmás tu vida","Como una doctrina religiosa de reencarnación","Como una predicción histórica"], r:"Como un test existencial sobre si afirmás tu vida", why:"Zaratustra se enoja con el enano justamente por reducirlo a cosmología; la versión de La gaya ciencia lo plantea como prueba de afirmación."}
]};
