/* ============================================================
   Ficha: platon  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"platon", trad:"europea", nombre:"Platón", fechas:"c. 427–347 a.C. · Atenas", escuela:"Idealismo clásico", icon:"🕳️", profundizada:true,
 tesis:"El mundo sensible es sombra de un mundo de Formas eternas e inmutables; conocer de verdad es recordar (anámnesis) esas Formas, no fiarse de los sentidos. La justicia en el alma y en la ciudad reflejan un mismo orden racional.",
 obras:[
   {t:"La República", d:"Diálogo en diez libros que arranca con una pregunta en apariencia modesta —¿qué es la justicia?— y que, ante el desafío de Trasímaco (la justicia es lo que conviene al más fuerte) y de Glaucón (nadie es justo por gusto: con el anillo de Giges, que vuelve invisible, cualquiera cometería injusticias), propone leer el alma «en letras grandes»: construir con palabras una ciudad justa para ver en ella qué es la justicia. De ese experimento salen la división de la ciudad en gobernantes, guardianes y productores, la tripartición del alma, el programa educativo de los guardianes, la tesis del filósofo-rey, las tres imágenes de los Libros VI y VII —el sol, la línea dividida y la caverna—, la crítica a la poesía imitativa y una tipología de regímenes degenerados en la que la democracia aparece como antesala de la tiranía. Cierra con el mito de Er, que devuelve la pregunta inicial al plano de la elección de una vida entera."},
   {t:"Fedón", d:"Ambientado en la cárcel el día de la ejecución de Sócrates y narrado por Fedón, que estuvo presente, discute por qué el filósofo no debe temer a la muerte: si filosofar es separar en lo posible el alma de las distracciones del cuerpo, morir es la culminación de esa práctica. Para sostenerlo, Sócrates ofrece cuatro argumentos a favor de la inmortalidad del alma —el de los contrarios, el de la reminiscencia, el de la afinidad del alma con las Formas invisibles y el final, según el cual el alma participa esencialmente de la Forma de la Vida— y enfrenta dos objeciones serias: la de Simmias, para quien el alma sería como la armonía de una lira, que se extingue con el instrumento, y la de Cebes, para quien sería como un tejedor que gasta muchos mantos y finalmente muere. Contiene además la «segunda navegación», el relato en que Sócrates explica por qué abandonó la física de Anaxágoras y se refugió en los razonamientos y en la hipótesis de las Formas."},
   {t:"El banquete", d:"Una cena en casa del poeta Agatón en la que cada invitado pronuncia un elogio de Eros; el más célebre es el mito de Aristófanes sobre los seres esféricos partidos en dos, que explica el amor como búsqueda de la mitad perdida. Sócrates no elogia: cuenta lo que le enseñó Diotima de Mantinea. Eros no es un dios bello sino un intermediario (daímon), hijo de Recurso y de Pobreza, que siempre desea lo que le falta, y por eso es filósofo: ni sabio ni ignorante, amante de una sabiduría que no posee. El amor es deseo de poseer el bien para siempre y se realiza «engendrando en la belleza». La escalera de Diotima asciende desde un cuerpo bello hasta la visión repentina de la Belleza misma. El final, con la irrupción de un Alcibíades borracho que elogia a Sócrates, pone en escena el contraste entre ese ascenso y el amor concreto por una persona."},
   {t:"Teeteto", d:"Diálogo dedicado a una sola pregunta —¿qué es el conocimiento (episteme)?— y al examen de tres respuestas del joven matemático Teeteto: que es percepción, que es opinión verdadera, y que es opinión verdadera acompañada de una explicación (lógos). La primera se vincula con la tesis de Protágoras de que el hombre es la medida de todas las cosas y con el flujo heracliteano, y Sócrates la refuta mostrando, entre otras cosas, que comparar y juzgar no es obra de ningún sentido particular sino del alma misma. La segunda cae porque un jurado bien persuadido puede tener una opinión verdadera sin saber. La tercera se desarma porque todas las lecturas posibles de «explicación» resultan insuficientes o circulares. El diálogo termina sin definición, y Sócrates —que aquí se presenta como partero de almas— trata esa aporía como un logro: Teeteto sale sabiendo que no sabe."},
   {t:"Menón", d:"Diálogo breve que empieza con la pregunta de Menón —¿se puede enseñar la virtud?— y que Sócrates desvía hacia otra previa: qué es la virtud. Cuando Menón, frustrado, compara a Sócrates con un pez torpedo que paraliza a quien lo toca, formula la paradoja de la indagación: no se puede buscar lo que no se sabe, porque no se lo reconocería al encontrarlo. La respuesta es la anámnesis, puesta a prueba con un esclavo que, solo respondiendo preguntas, descubre cómo duplicar el área de un cuadrado. El diálogo introduce además la distinción decisiva entre opinión verdadera y saber con la imagen del camino a Larisa: quien acierta el camino por opinión llega igual que quien lo sabe, pero las opiniones verdaderas son como las estatuas de Dédalo, que se escapan si no se las ata «con un razonamiento sobre la causa». Termina sugiriendo, con ironía, que los grandes políticos atenienses fueron virtuosos por inspiración divina y no por saber."}
 ],
 conceptos:[
   {t:"Teoría de las Formas", d:"Existen realidades eternas, inmutables e inteligibles —lo Igual, lo Bello, lo Justo, el Triángulo— de las que las cosas sensibles «participan» y son copias imperfectas: un acto es justo en un respecto e injusto en otro, dos palos son iguales para uno y desiguales para otro, mientras que la Justicia misma y la Igualdad misma no admiten esa oscilación. Platón llega a ellas por dos vías que conviene no confundir: una epistemológica —si hay saber estable, necesita un objeto estable, porque de lo que fluye solo hay opinión (doxa)— y otra semántica —cuando llamamos «bellas» a muchas cosas distintas, algo tiene que ser aquello por lo cual todas lo son—. Lo que se discute desde Aristóteles es la separación (chorismós): si las Formas existen aparte de las cosas, no se entiende bien cómo explican las cosas ni cómo llegamos a conocerlas."},
   {t:"Mito de la caverna", d:"Imagen del comienzo del Libro VII de la República que Platón presenta expresamente como figura de «nuestra naturaleza respecto de la educación y de la falta de ella». Prisioneros encadenados desde niños ven solo sombras de figuras que otros transportan delante de un fuego, y las toman por la realidad entera: su error no es ver mal, sino no saber de qué son sombras. Uno es liberado y obligado a subir; la luz le duele, prefiere lo que veía antes, y solo por etapas —sombras, reflejos, cosas, astros, el sol— llega a mirar el sol mismo. Al volver a bajar, torpe en la oscuridad, es ridiculizado, y los demás estarían dispuestos a matarlo. Tres rasgos suelen perderse al resumirlo: la violencia del ascenso (nadie sale solo), su gradualidad (no hay iluminación instantánea) y la obligación del retorno, que funda el deber político del filósofo."},
   {t:"Anámnesis", d:"Aprender es recordar lo que el alma conoció antes de encarnar, cuando contempló las Formas. Platón la introduce en el Menón para responder a la paradoja de la indagación —¿cómo buscar lo que no se sabe, si no se lo reconocería al encontrarlo?— y la ilustra con un esclavo que, sin que Sócrates le dé la respuesta, llega a duplicar el área de un cuadrado trazando la diagonal. En el Fedón la convierte en argumento: juzgamos que dos palos iguales «se quedan cortos» respecto de la Igualdad misma, y ese juicio exige conocer ya el modelo, que nunca vimos en lo sensible. Leída con ojos modernos, la anámnesis prueba como mucho que hay conocimiento no derivado de la experiencia; que ese conocimiento requiera un alma preexistente es un paso más, y es justamente el que Descartes (ideas innatas) y Kant (lo a priori sin reminiscencia) reformularán sin mito."},
   {t:"Alma tripartita", d:"En el Libro IV de la República Platón argumenta —no solo afirma— que el alma tiene tres partes: la razón (logistikón), el ánimo o espíritu (thymoeidés) y el apetito (epithymētikón). La premisa es un principio de no contradicción aplicado a la acción: una misma cosa no puede querer y rechazar lo mismo a la vez y en el mismo respecto; como el sediento que se niega a beber hace ambas cosas, en él hay dos principios distintos. El caso de Leoncio, que se enfurece consigo mismo por desear mirar unos cadáveres, muestra una tercera instancia, la indignación, que no es deseo ni cálculo. La justicia individual es que cada parte haga lo suyo: que la razón gobierne sabiendo lo que conviene al conjunto, que el espíritu la asista y que el apetito —«la parte más grande del alma»— no pretenda mandar. El paralelo con las tres clases de la ciudad es deliberado: la ciudad es el alma escrita en letras grandes."},
   {t:"La Idea del Bien y la analogía del sol", d:"Para Platón la Idea del Bien es «el estudio más importante», y Sócrates se niega a definirla: solo ofrece una imagen, la del sol como «hijo del Bien». Así como en lo visible no bastan el ojo y el color, sino que hace falta la luz del sol para que haya visión, en lo inteligible no bastan el intelecto y las Formas: el Bien es lo que da verdad a lo conocido y capacidad de conocer al que conoce. Y así como el sol no solo hace visibles las cosas sino que les da generación y crecimiento sin ser él mismo generación, el Bien da a las Formas su ser, aunque él no es ser sino que está «más allá del ser en dignidad y en poder» (República 509b). Esa frase alimentó toda la tradición neoplatónica, y explica por qué en Platón el saber más alto no es neutral: conocer plenamente algo es entender para qué es bueno."},
   {t:"La línea dividida", d:"Imagen de República VI que ordena los grados de realidad y de conocimiento en una línea cortada en dos segmentos desiguales —lo visible y lo inteligible—, cada uno cortado a su vez en la misma proporción. En lo visible están las imágenes (sombras, reflejos), captadas por la eikasía, y las cosas sensibles, objeto de la pístis o creencia; juntas forman la doxa. En lo inteligible, el tramo inferior es la diánoia, el pensamiento del matemático, que parte de hipótesis que no examina y se apoya en figuras visibles; el superior es la nóesis o dialéctica, que trata las hipótesis como peldaños para ascender hasta un principio no hipotético y luego desciende sin usar ninguna imagen. La diferencia entre diánoia y nóesis no es solo de objeto sino de método, y es la clave para entender por qué Platón pone la matemática por debajo de la filosofía aunque la exija como preparación."},
   {t:"El filósofo-rey", d:"«A menos que los filósofos reinen en las ciudades o que los que ahora se llaman reyes filosofen de verdad, no habrá fin de los males» (República 473c-d). La tesis no es que los intelectuales deban mandar, sino que solo quien conoce el Bien puede ordenar la ciudad hacia él, igual que solo quien sabe navegar debería pilotar el barco, y no quien mejor convence a la tripulación. Por eso exige una educación de décadas —gimnasia y música, luego matemáticas, luego dialéctica, luego quince años de práctica en cargos— y condiciones severas para los guardianes, sin propiedad privada ni familia propia, para que el interés particular no desvíe el juicio. La paradoja que el propio Platón subraya es que el mejor gobernante es el que menos desea gobernar, y que hay que obligarlo a volver a la caverna. Es la tesis más discutida de la República, desde Aristóteles hasta la crítica de Popper a la «sociedad cerrada»."},
   {t:"Eros y la escalera de Diotima", d:"En el Banquete, Sócrates atribuye a Diotima una teoría del amor que convierte el deseo en motor del conocimiento. Eros no es bello ni sabio: es un intermediario (daímon) que desea lo que le falta, y por eso es «filósofo», amante de una sabiduría que no posee. Lo que todo amor quiere, en el fondo, es poseer el bien para siempre, y como somos mortales busca «engendrar en la belleza»: hijos, obras, leyes, ideas. La escalera ordena ese deseo: de un cuerpo bello a la belleza de todos los cuerpos, de ahí a la de las almas, a la de las instituciones y las leyes, a la de los saberes, hasta que «de repente» se contempla la Belleza misma, que no nace ni perece ni es bella en un respecto y fea en otro. La escalera no pide despreciar lo que se deja atrás sino verlo en su lugar; el discurso de Alcibíades, que irrumpe al final, deja abierta la pregunta de qué queda del amor a una persona singular."},
   {t:"El argumento del tercer hombre", d:"En el Parménides el propio Platón pone en boca del viejo Parménides la objeción más fuerte contra su teoría, que Aristóteles bautizará «el tercer hombre». Si muchas cosas grandes lo son porque participan de la Forma de lo Grande, y la Forma misma es grande (autopredicación), entonces las cosas grandes y la Forma juntas forman un nuevo conjunto de cosas grandes, que exige una segunda Forma de lo Grande que explique lo que tienen en común; y así al infinito. El argumento depende de dos supuestos: que la Forma posee la propiedad que explica, y que nada es grande en virtud de sí mismo. Que Platón lo haya escrito sin darle una respuesta explícita es uno de los datos más interesantes de su obra: o lo consideraba refutable negando la autopredicación, o marca una revisión de la teoría en los diálogos tardíos. En cualquier caso muestra a un filósofo que somete su propia doctrina al examen que aplicaba a los demás."}
 ],
 conexion:"Su discípulo <b>Aristóteles</b> rechazará la separación entre Formas y cosas, iniciando el desacuerdo racionalismo/empirismo que atraviesa toda la tradición europea.",
 dialogo:{titulo:"Saliendo de la caverna", lineas:[
   {quien:"Estudiante", texto:"Si toda mi vida vi solo sombras en una pared, ¿por qué debería creerte que hay algo más afuera?"},
   {quien:"Platón", texto:"No te pido que me creas. Te pido que subas. Ninguna descripción de la luz del sol reemplaza haberla visto."},
   {quien:"Estudiante", texto:"¿Y si subo y no veo nada distinto? ¿Cómo sé que no me estás llevando a otra caverna, más grande?"},
   {quien:"Platón", texto:"Buena pregunta — y es exactamente la que hace que este no sea un dogma. La prueba no está en mi palabra: está en si, después de subir, las Formas te permiten explicar por qué reconocías un triángulo perfecto sin haber visto nunca uno."},
   {quien:"Estudiante", texto:"Pero si vuelvo a contarles a los demás lo que vi, dijiste que me van a ridiculizar."},
   {quien:"Platón", texto:"Sí. Y aun así hay que volver a bajar. El filósofo que se queda arriba, contemplando, abandona a la ciudad a su propia sombra.", nota:"Este último punto es clave en la República: el filósofo-rey gobierna a pesar de preferir la contemplación, no gracias a desearlo."}
 ]},
 actividades:[
   {t:"Reescribir el mito en clave contemporánea", d:"Elegí un fenómeno actual (algoritmos, cámaras de eco, publicidad) y reescribí el mito de la caverna manteniendo su estructura lógica exacta: encadenamiento, liberación forzada, deslumbramiento, contemplación y retorno rechazado."},
   {t:"Poner a prueba la anámnesis", d:"Buscá un ejemplo real de conocimiento que parezca 'no aprendido por los sentidos' y argumentá si eso apoya la anámnesis o si se explica igual de bien sin un alma preexistente."},
   {t:"Debate del filósofo-rey", d:"Escribí ambos lados: (a) debe gobernar quien menos desea el poder, o (b) esa condición hace impracticable el ideal. Pensá cómo llevar esto a un debate real en clase."}
 ],
 cuestionario:[
   {q:"Si alguien creciera viendo solo sombras, ¿qué evidencia lo convencería de que hay algo más real — y esa evidencia, es de otro tipo que la de los sentidos?", p:"Platón diría que ninguna evidencia sensible basta: hace falta un giro del alma hacia el razonamiento dialéctico. Vale la pena preguntar si eso no vuelve la tesis infalsable."},
   {q:"¿Puede existir un concepto perfecto (un triángulo exacto) sin que ninguna cosa sensible lo ejemplifique del todo?", p:"Esa es la intuición detrás de la Teoría de las Formas: si nunca vimos un triángulo perfecto y aun así lo entendemos, ese conocimiento no vino de los sentidos, según Platón."},
   {q:"Si el alma tiene tres partes que quieren cosas distintas, ¿quién decide finalmente actuar?", p:"Platón apuesta por un alma jerárquica: la justicia interior es que la razón tenga la autoridad habitual. Cuando el apetito gana, el alma está desordenada — no hay un cuarto juez."},
   {q:"¿Cómo identificamos y persuadimos a gobernar a alguien que, por ser el candidato ideal, no quiere el poder?", p:"Platón diseña una educación obligatoria de décadas para los guardianes: no los deja decidir libremente, los forma y luego los 'obliga' a bajar de nuevo a gobernar."},
   {q:"El Parménides formula contra las Formas el argumento del tercer hombre. ¿Qué supuesto habría que abandonar para escapar del regreso al infinito, y qué costaría abandonarlo?", p:"El regreso depende de la autopredicación —que la Forma de lo Grande sea ella misma grande— y de que nada sea grande en virtud de sí mismo. Negar la autopredicación permite decir que la Forma no es un ejemplar perfecto sino aquello en virtud de lo cual las cosas son grandes; pero entonces se debilita la imagen del modelo y la copia, que es la que sostiene el argumento de la reminiscencia del Fedón («los palos se quedan cortos respecto de la Igualdad»). Aristóteles tomó el argumento como prueba de que el universal no debe separarse de las cosas."}
 ],
 cadena:{ titulo:"¿Alcanza con tener razón para saber?", intro:"Un razonamiento socrático en ramas, a partir del Menón y del Teeteto. Ningún camino es una trampa: cada uno lleva a un lugar distinto del pensamiento de Platón.", inicio:"n1", nodos:{
   n1:{ pregunta:"Dos viajeros llegan a Larisa. Uno nunca hizo el camino: le indicaron el rumbo y acertó. El otro lo recorrió muchas veces y lo conoce. Los dos llegaron. ¿Hay alguna diferencia entre lo que tiene cada uno?", opciones:[
     {texto:"No, al menos para actuar: si los dos llegan, la opinión verdadera guía tan bien como el saber.", va:"n2a"},
     {texto:"Sí: el que recorrió el camino puede explicar por qué es ese y no otro.", va:"n2b"} ]},
   n2a:{ pregunta:"Sócrates te lo concede: para llegar a Larisa, la opinión verdadera no es peor guía que el saber (Menón 97b). Pero a mitad de camino alguien le asegura al primer viajero, con mucha convicción, que se equivocó de desvío. ¿Qué le pasa a su opinión?", opciones:[
     {texto:"Probablemente la abandone: no tiene cómo defenderla, porque nunca supo por qué era la correcta.", va:"n3a"},
     {texto:"La mantiene igual, por firmeza de carácter: no hace falta saber para ser constante.", final:{tipo:"revisar", texto:"La constancia sin razones no distingue al que acierta del que se equivoca: el viajero se aferraría con la misma firmeza a un rumbo falso. Por eso Sócrates no pide firmeza sino otra cosa. Volvé a empezar y seguí la otra opción: ahí aparece qué es lo que, según el Menón, vuelve estable una opinión verdadera."}} ]},
   n3a:{ pregunta:"Sócrates compara las opiniones verdaderas con las estatuas de Dédalo: valiosas mientras se quedan, pero se escapan si no se las ata. ¿Qué es lo que las ata y las convierte en saber?", opciones:[
     {texto:"Un razonamiento sobre la causa: poder dar razón de por qué son verdaderas.", final:{tipo:"bien", texto:"Es la tesis del Menón 98a: el saber es opinión verdadera «atada por un razonamiento sobre la causa», y Sócrates agrega que ese atar es la anámnesis. Partiste de que la opinión verdadera alcanzaba para actuar, y lo sostuviste bien; lo que descubriste es que alcanza solo mientras nadie la sacuda. La diferencia entre opinión y saber no está en el contenido —los dos dicen «por acá»— sino en su estabilidad."}},
     {texto:"La repetición y la costumbre, como cuando uno practica un oficio hasta dominarlo.", final:{tipo:"revisar", texto:"Esa es, casi palabra por palabra, la respuesta de Aristóteles para la virtud ética: el hábito (héxis) estabiliza una conducta. Pero no es la de Platón para el saber: un hábito puede estabilizar también un error, y no te permite explicar nada. Para Platón lo que ata la opinión es dar razón (lógon didónai). Buen hallazgo, de todos modos: acabás de tocar uno de los puntos donde maestro y discípulo se separan."}} ]},
   n2b:{ pregunta:"Entonces saber sería tener una opinión verdadera y además una explicación (lógos). Es exactamente la tercera definición del Teeteto. Pero ¿qué entendés por «explicación»?", opciones:[
     {texto:"Descomponer la cosa en sus elementos, como quien deletrea un nombre letra por letra.", va:"n3b"},
     {texto:"Poder decir qué la distingue de todas las demás cosas.", va:"n3c"} ]},
   n3b:{ pregunta:"Si conocer la sílaba «SO» es conocer sus letras, S y O, ¿cómo se conocen las letras, que ya no tienen partes en las que descomponerse?", opciones:[
     {texto:"Las letras no se conocen: solo se perciben. El saber aparece recién en lo compuesto.", final:{tipo:"revisar", texto:"Es el «sueño» de Teeteto, y Sócrates lo desarma (Teeteto 202d-206b): sería absurdo que lo compuesto fuera cognoscible y sus elementos no, y en la práctica aprendemos las letras con más claridad que las sílabas. La definición por descomposición termina en elementos de los que no hay explicación. Lo que ganaste es ver por qué Platón no puede poner lo simple en la base del saber: la teoría de las Formas lo pone en la cima, como algo inteligible."}},
     {texto:"Por una captación directa de la mente, sin necesidad de descomponerlas.", final:{tipo:"bien", texto:"Es la salida que el Teeteto no toma pero la República sí: en el tramo superior de la línea dividida, la nóesis capta el principio no hipotético sin imágenes y sin descomponer nada. Pero notá el precio: si lo último se conoce sin lógos, «opinión verdadera más explicación» ya no sirve como definición general del saber. Por eso el Teeteto termina en aporía: la pieza que falta no está en ese diálogo."}} ]},
   n3c:{ pregunta:"Pensá en Teeteto, que tiene la nariz chata y los ojos saltones, igual que Sócrates. Para tener siquiera una opinión verdadera sobre Teeteto —y no confundirlo con Sócrates—, ¿no necesitás ya captar lo que lo distingue?", opciones:[
     {texto:"Sí. Entonces agregar «lo que lo distingue» no agrega nada que la opinión verdadera no tuviera.", final:{tipo:"bien", texto:"Es la primera mitad de la aporía final del Teeteto (209a-d): la diferencia ya estaba incluida en la opinión correcta, así que exigirla de nuevo es, dice Sócrates, un consejo digno de un ciego: mandar a agregar lo que ya se tiene. El diálogo termina sin definición, y Platón trata eso como un resultado: Teeteto sale sabiendo que no sabe, que es la condición de toda búsqueda."}},
     {texto:"No del todo: la opinión puede ser vaga y la diferencia la vuelve precisa.", va:"n4c"} ]},
   n4c:{ pregunta:"De acuerdo: el lógos sería captar la diferencia con precisión. Última pregunta, y es la decisiva: esa diferencia, ¿hay que saberla u opinarla correctamente?", opciones:[
     {texto:"Saberla.", final:{tipo:"revisar", texto:"Entonces definiste el saber como «opinión verdadera más saber de la diferencia»: usaste la palabra que querías definir dentro de la definición. Es la segunda mitad de la aporía del Teeteto (209e-210a). La lección es valiosa: una definición circular puede sonar perfecta y no explicar nada."}},
     {texto:"Opinarla correctamente.", final:{tipo:"revisar", texto:"Entonces no agregaste nada de otro tipo: opinión verdadera más una opinión verdadera sobre la diferencia sigue siendo opinión. Sócrates concluye que sería una ingenuidad llamar a eso una definición del saber. Las dos respuestas posibles fallan, y ese dilema es exactamente donde el Teeteto deja al lector."}} ]}
 }},
 reconstruccion:[
   { titulo:"La reminiscencia a partir de lo Igual (Fedón 74a-75d)",
     consigna:"Reconstruí el argumento del Fedón según el cual aprender es recordar. Una de las piezas pertenece a otro argumento del mismo diálogo: dejala afuera. Ordená el resto de modo que cada paso se apoye en el anterior.",
     piezas:[
       {id:"r1", texto:"Juzgamos que dos palos o dos piedras son iguales, pero advertimos a la vez que «se quedan cortos» respecto de la Igualdad misma.", tipo:"premisa"},
       {id:"r2", texto:"Advertir que algo se queda corto respecto de un modelo presupone conocer ya ese modelo.", tipo:"premisa"},
       {id:"r3", texto:"Pero ese modelo no lo encontramos nunca en lo sensible: ningún par de cosas percibidas es perfectamente igual.", tipo:"premisa"},
       {id:"r4", texto:"Y como percibimos desde que nacemos, ese conocimiento que no viene de los sentidos tuvo que estar en nosotros antes de nacer.", tipo:"premisa"},
       {id:"r5", texto:"Por lo tanto, el alma adquirió el conocimiento de lo Igual antes de encarnar, y lo que llamamos aprender es recordar.", tipo:"conclusion"},
       {id:"rx", texto:"El alma es simple y semejante a lo invisible, y lo que no tiene partes no puede descomponerse ni perecer.", tipo:"distractor"}
     ],
     ordenCorrecto:["r1","r2","r3","r4","r5"],
     explicacion:"El argumento va de un juicio cotidiano (estos palos son iguales, pero no del todo) a una condición de posibilidad: para notar la deficiencia hay que tener ya el estándar. Como el estándar perfecto no aparece en la experiencia y la experiencia empieza con la vida, el estándar se adquirió antes. La pieza sobrante pertenece al argumento de la afinidad (Fedón 78b-80b), que prueba la inmortalidad por la semejanza del alma con las Formas, no por la reminiscencia. Punto débil para discutir: el paso de r3 a r4 supone que todo conocimiento no sensible tiene que haberse adquirido en algún momento; un innatista moderno diría que puede ser simplemente constitutivo de la mente."},
   { titulo:"La analogía del sol (República VI, 507b-509b)",
     consigna:"Reconstruí cómo Platón llega a decir que el Bien está «más allá del ser». Una pieza confunde esta imagen con otra de la República: dejala afuera y ordená el resto.",
     piezas:[
       {id:"s1", texto:"En lo visible, el ojo y el color no bastan para que haya visión: hace falta un tercer elemento, la luz que viene del sol.", tipo:"premisa"},
       {id:"s2", texto:"Además, el sol no solo hace visibles las cosas: también les da generación y crecimiento, sin ser él mismo generación.", tipo:"premisa"},
       {id:"s3", texto:"Pues bien: lo que el sol es en lo visible respecto de la vista y de lo visto, eso mismo es el Bien en lo inteligible respecto del intelecto y de las Formas.", tipo:"premisa"},
       {id:"s4", texto:"Por lo tanto, el Bien no solo hace cognoscibles las Formas sino que les da su ser, sin ser él mismo ser: está más allá del ser en dignidad y en poder.", tipo:"conclusion"},
       {id:"sx", texto:"Como los prisioneros de la caverna solo ven sombras, el Bien es la más brillante de las sombras que proyecta el fuego.", tipo:"distractor"}
     ],
     ordenCorrecto:["s1","s2","s3","s4"],
     explicacion:"Es un argumento por analogía en dos tiempos: primero se establecen las dos funciones del sol (hacer visible y hacer crecer) y después se trasladan, término por término, al Bien (hacer cognoscible y dar el ser). La conclusión solo se sigue si la proporción de s3 vale para las dos funciones, y ahí está el punto discutible. La pieza sobrante confunde el sol con el fuego de la caverna: en el mito, el fuego produce sombras dentro de lo visible; el sol, afuera, es la imagen del Bien."}
 ],
 dilemas:[
   { titulo:"El anillo de Giges en la sala de profesores",
     intro:"En República II, Glaucón cuenta que el pastor Giges encontró un anillo que lo volvía invisible, y que lo usó para apoderarse del reino. Su desafío: nadie es justo por gusto; cualquiera con ese anillo actuaría injustamente. Este caso te pone el anillo en la mano.",
     pasos:[
       { id:"p1", situacion:"Integrás el comité que corrige el examen final. Descubrís un error en el sistema de notas: podrías subirle dos puntos a un estudiante que se esforzó mucho y que quedó a un punto de aprobar, y nadie lo detectaría nunca. ¿Qué hacés?", opciones:[
         {texto:"Le subo los dos puntos: se lo ganó con esfuerzo y no perjudico a nadie.", consecuencia:"Acabás de usar el anillo. Tus razones son buenas —el esfuerzo existió, el daño no se ve—, pero son razones que nadie más va a examinar, porque nadie va a saber. Glaucón diría que eso prueba su tesis: con invisibilidad, hasta una persona decente hace lo que en público no haría.", va:"p2a"},
         {texto:"No lo toco, aunque nadie se enteraría.", consecuencia:"Te abstuviste sin testigos, que es exactamente lo que Glaucón dice que nadie hace. Pero abstenerse es solo la mitad: el error sigue ahí para cualquier otro.", va:"p2b"} ]},
       { id:"p2a", situacion:"Un mes después, un colega te confiesa que encontró el mismo error y lo usó para bajarle la nota a un estudiante que «lo provocaba en clase». Te pide silencio: «vos habrías hecho lo mismo en mi lugar, ¿no?». ¿Qué hacés?", opciones:[
         {texto:"Lo denuncio: lo suyo es un castigo arbitrario; lo mío fue un favor merecido.", consecuencia:"La diferencia que ves es real: dañar no es lo mismo que favorecer. Pero su criterio es idéntico al tuyo —«mi juicio basta y nadie lo va a saber»—, y denunciarlo te obliga a explicar por qué el anillo vale para vos y no para él. Platón diría que ahí se ve el problema: en las dos almas, lo que decidió no fue la razón sino una preferencia.", va:"p3"},
         {texto:"Me callo: no puedo exigirle lo que yo mismo no cumplí.", consecuencia:"Tu silencio es coherente, y eso es lo inquietante. Sócrates respondería que el costo no está afuera sino adentro: un alma donde la simpatía o el enojo deciden en lugar de la razón ya está desordenada, aunque nadie lo vea. La injusticia, para él, es primero una forma de estar hecho.", va:"p3"} ]},
       { id:"p2b", situacion:"No usaste el error, pero sigue abierto. Reportarlo implica admitir que lo viste hace días sin decir nada, y eso te expone a preguntas incómodas. ¿Qué hacés?", opciones:[
         {texto:"Lo reporto igual y explico la demora.", consecuencia:"Para Platón la justicia no es solo no dañar: es que cada parte cumpla su función, en el alma y en la ciudad. Tu función en el comité incluye cuidar que el sistema sea justo para todos, no solo que vos no lo uses. Pagás un costo de reputación —el que Glaucón decía que nadie acepta pagar—.", va:"p3"},
         {texto:"No lo reporto: ya cumplí con no usarlo.", consecuencia:"Es la posición de quien es justo para sí pero no se pregunta por la ciudad. El liberado de la caverna también podría quedarse arriba sin hacerle daño a nadie, y Platón le exige bajar. La pregunta que queda: ¿tu abstención es justicia o solo prudencia para no comprometerte?", va:"p3"} ]},
       { id:"p3", situacion:"Un estudiante se entera de la historia y te pregunta en clase: «Entonces, ¿usted es justo porque le conviene o porque sí?». ¿Qué le respondés?", opciones:[
         {texto:"Porque la justicia es buena en sí misma, y además por lo que produce.", consecuencia:"Es exactamente la respuesta que Sócrates se compromete a defender en República II (357b-358a): la justicia pertenece a la clase de bienes que se aman por sí mismos y por sus consecuencias. Todo el resto de la República es el intento de demostrarlo, empezando por el alma tripartita.", va:null},
         {texto:"Por sus consecuencias: la confianza, la reputación, evitar sanciones.", consecuencia:"Es la posición que Glaucón y Adimanto le piden a Sócrates que refute. Si la justicia vale solo por sus consecuencias, el anillo de Giges te deja sin razones para ser justo. Pensá qué te quedaría si las consecuencias desaparecieran.", va:null},
         {texto:"No lo sé todavía, y quiero averiguarlo con ustedes.", consecuencia:"Respuesta socrática, y honesta. Pero Platón no la dejaría ahí: el Sócrates de la República acepta el desafío y construye una ciudad entera para responderlo. La ignorancia reconocida es el punto de partida, no el lugar donde quedarse.", va:null} ]}
     ],
     rubrica:[
       "En cada decisión, distinguí si respondía a la pregunta «¿es justo?» o a la pregunta «¿me van a descubrir?».",
       "Puedo formular el desafío de Glaucón (República II) en su versión más fuerte antes de intentar responderlo.",
       "Relacioné mis elecciones con el alma tripartita: identifiqué qué parte —razón, ánimo o apetito— estaba decidiendo en cada paso.",
       "Distinguí la justicia como bien «en sí» de la justicia como bien «por sus consecuencias» (República 357b-358a).",
       "Consideré la dimensión política —el comité, la institución, los otros estudiantes— y no solo mi propia alma.",
       "Puedo señalar al menos una objeción seria a la respuesta de Platón (por ejemplo: el justo que sufre persecución, ¿es realmente más feliz?)."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.platon = { lecturas:[
 {titulo:"El mito de la caverna (República, Libro VII)", fuente:"Webdianoia — textos de Platón", url:"https://www.webdianoia.com/platon/textos/platon_caverna.htm",
  extracto:`Sócrates abre el pasaje con una orden extraña: «compara con la siguiente escena el estado en que, con respecto a la educación o a la falta de ella, se halla nuestra naturaleza». Pide a Glaucón que imagine una morada subterránea con una entrada abierta a la luz, y dentro, hombres encadenados desde niños por las piernas y el cuello, de modo que no pueden girar la cabeza. Detrás y arriba arde un fuego; entre el fuego y los prisioneros corre un camino elevado con un tabique, como el biombo de los titiriteros, y por allí pasan hombres llevando figuras de animales y objetos. Los prisioneros solo ven las sombras que el fuego proyecta sobre la pared del fondo, y solo oyen los ecos de las voces. Glaucón observa que son «una extraña escena y unos extraños prisioneros», y Sócrates responde: «son semejantes a nosotros».

La consecuencia es inmediata y decisiva: «no creerán que exista otra realidad que las sombras de los objetos fabricados». La sombra no es tomada por sombra — es tomada por la cosa misma. El error no es de percepción sino de ontología: los prisioneros perciben perfectamente lo que hay delante de ellos; lo que les falta es saber de qué son sombras.

Luego viene la liberación, y Platón insiste en que es dolorosa. Al desatarlo y obligarlo a volverse hacia la luz, el prisionero «sentiría dolores» y quedaría «demasiado deslumbrado para percibir aquellas cosas cuyas sombras había visto antes». Si alguien le dijera que lo que veía antes eran vaciedades y que ahora está más cerca del ser, «se hallaría en un aprieto y pensaría que las cosas que veía antes eran más verdaderas que las que se le muestran ahora». La primera reacción ante la verdad es preferir la mentira conocida — un punto que Platón subraya deliberadamente.

El ascenso es gradual: primero distinguiría las sombras, después las imágenes reflejadas en el agua, luego los objetos mismos, después los astros de noche, y finalmente el sol — «no ya en imágenes en el agua, sino en sí y por sí mismo, en su propio dominio». Y solo entonces podría razonar sobre él y concluir que «él es quien produce las estaciones y los años y todo lo gobierna en la región visible».

El retorno cierra el mito con un tono sombrío. El liberado que vuelve a bajar tendría los ojos «llenos de oscuridad», y al competir con los prisioneros en juzgar las sombras haría el ridículo: dirían de él «que por haber subido arriba ha vuelto con los ojos estropeados», y que no vale la pena intentar la ascensión. Sócrates añade la frase más dura del pasaje: «y si intentasen desatarlos y conducirlos arriba, ¿no lo matarían, si pudieran tenerlo en sus manos y matarlo?». La alusión al juicio de Sócrates es transparente.`,
  comentario:"Este texto es la escenificación completa de la Teoría de las Formas: la línea sombras→objetos→sol reproduce exactamente la jerarquía doxa/episteme. Fijate que Platón nunca argumenta aquí por las Formas — narra una experiencia de conversión, lo que explica por qué el propio diálogo admite que ninguna prueba sensible puede convencer a un prisionero. El retorno obligatorio del liberado es además la justificación del filósofo-rey: gobernar no es un premio sino un deber de quien vio el Bien."},
 {titulo:"La anámnesis y el esclavo del Menón", fuente:"Stanford Encyclopedia of Philosophy — Plato's Middle Period Metaphysics and Epistemology", url:"https://plato.stanford.edu/entries/plato-metaphysics/",
  extracto:`En el Menón, Sócrates enfrenta una objeción que hoy llamaríamos la «paradoja de la indagación»: si ya sabés lo que buscás, no necesitás buscarlo; si no lo sabés, no lo reconocerías al encontrarlo. Su salida es la anámnesis: el alma, inmortal y habiendo contemplado ya todas las cosas, no aprende sino que recuerda.

Para mostrarlo, Sócrates llama a un esclavo de la casa de Menón que nunca estudió geometría y le plantea el problema de duplicar el área de un cuadrado. El esclavo responde primero lo obvio — duplicar el lado — y Sócrates le muestra, sin corregirlo directamente, que eso cuadruplica el área. El esclavo queda perplejo, y Sócrates señala que esa perplejidad es un progreso: antes creía saber y no sabía; ahora sabe que no sabe, y por eso puede buscar. Guiado solo por preguntas y por el trazado de la diagonal, el esclavo llega a la solución correcta: el cuadrado construido sobre la diagonal tiene el doble de área.

El punto de Platón es que Sócrates nunca le transmitió la respuesta, solo preguntó. Si el conocimiento no entró por los sentidos ni por enseñanza verbal, tuvo que estar ya en el alma. La lectura contemporánea más común sostiene que el argumento prueba a lo sumo que hay conocimiento a priori o capacidades cognitivas innatas, no la preexistencia del alma — una distinción que Platón no traza, pero que vale la pena discutir en clase.

En el Fedón, la anámnesis se articula con la Teoría de las Formas de manera más explícita. Vemos dos palos «iguales» y los juzgamos iguales, pero también advertimos que se quedan cortos respecto de la Igualdad misma. Ese juicio de «quedarse corto» presupone que ya poseemos el estándar; y como el estándar perfecto nunca lo encontramos en el mundo sensible, debimos adquirirlo antes de nacer. Es el mismo movimiento que el mito de la caverna dramatiza: los sentidos nos ponen en contacto con copias, y la copia solo se reconoce como copia desde el original.`,
  comentario:"La anámnesis es el mecanismo epistemológico que hace falta para que la Teoría de las Formas sea algo más que una hipótesis metafísica: explica cómo podemos conocer lo que nunca percibimos. Poné este texto junto al de la caverna y vas a ver la misma estructura dos veces — perplejidad, giro, reconocimiento. La objeción moderna (innatismo sin alma preexistente) es un excelente ejercicio de crítica interna."},
 {titulo:"Las tres partes del alma y la justicia (República IV)", fuente:"Biblioteca Virtual Miguel de Cervantes — La República de Platón o Coloquios sobre la justicia", url:"https://www.cervantesvirtual.com/obra/la-republica-de-platon-o-coloquios-sobre-la-justicia/",
  extracto:`En el Libro IV Platón necesita un argumento, no un mito. La pregunta es si el alma tiene partes, y su prueba es lo que hoy llamaríamos el principio de no contradicción aplicado a la acción: «es evidente que una misma cosa no puede hacer ni padecer cosas contrarias al mismo tiempo, en el mismo sentido y con respecto a lo mismo». Si el alma fuera simple, no podría a la vez querer y no querer lo mismo.

Pero eso ocurre constantemente. Un hombre sediento a veces se niega a beber. Hay entonces algo que empuja hacia la bebida (lo apetitivo, epithymētikon) y algo que retiene (lo racional, logistikon). Platón busca después una tercera parte con el célebre ejemplo de Leoncio, que caminando junto al muro norte ve cadáveres de ajusticiados, siente a la vez deseo de mirarlos y asco de sí mismo, y termina abriendo los ojos a la fuerza gritando: «ahí tenéis, malditos, hartaos del hermoso espectáculo». La cólera contra el propio deseo no es deseo ni es razón: es el thymos, lo irascible o espiritual, aliado natural de la razón cuando la educación lo forma bien.

De ahí sale la definición de justicia individual que Platón venía buscando desde el Libro I. La justicia no es un conjunto de acciones externas sino un orden interno: «que cada una de estas partes ejerza la función que le es propia», que la razón gobierne por saber lo que conviene al conjunto, que el thymos obedezca y la asista, y que el apetito, «que es la parte más grande del alma de cada uno», no pretenda mandar. El hombre justo «se ordena a sí mismo, se hace amigo de sí mismo y armoniza las tres partes como si fueran tres notas de una escala».

El paralelo con la ciudad es exacto y deliberado: gobernantes, guardianes y productores corresponden uno a uno a razón, thymos y apetito. Por eso Platón podía decir en el Libro II que la ciudad es «el alma escrita en letras grandes» — la ciudad ideal no es un programa político independiente, es un dispositivo argumentativo para leer el alma.`,
  comentario:"Este pasaje muestra que Platón argumenta, no solo narra: el principio de no contradicción funciona como premisa lógica explícita. Conectalo con la pregunta del cuestionario sobre quién decide finalmente actuar — la respuesta platónica es que no hay un cuarto juez, solo una jerarquía bien o mal educada. Aristóteles retomará la tripartición pero disolverá la separación entre las partes."}
], preguntasLectura:[
 {q:"Según el texto de la caverna, ¿cuál es el error fundamental de los prisioneros?", opciones:["Perciben mal las sombras","Toman las sombras por la realidad misma","No pueden oír los ecos","Se niegan a hablar entre ellos"], r:"Toman las sombras por la realidad misma", why:"Platón aclara que perciben bien: el error es ontológico, no perceptivo — «no creerán que exista otra realidad que las sombras»."},
 {q:"En el relato, ¿cómo describe Platón la primera reacción del prisionero liberado ante la luz?", opciones:["Alegría inmediata","Indiferencia","Dolor y deslumbramiento, prefiriendo lo que veía antes","Comprensión instantánea del Bien"], r:"Dolor y deslumbramiento, prefiriendo lo que veía antes", why:"El texto insiste en que «sentiría dolores» y pensaría que «las cosas que veía antes eran más verdaderas»."},
 {q:"En el Menón, ¿qué muestra el episodio del esclavo y el cuadrado, según Platón?", opciones:["Que la geometría se aprende por repetición","Que el conocimiento estaba ya en el alma y solo se recuerda","Que los esclavos podían estudiar","Que los sentidos bastan para la matemática"], r:"Que el conocimiento estaba ya en el alma y solo se recuerda", why:"Sócrates solo pregunta, no transmite la respuesta: de ahí la conclusión de la anámnesis."},
 {q:"¿Qué premisa lógica usa Platón en República IV para probar que el alma tiene partes?", opciones:["El principio de razón suficiente","Que una misma cosa no puede hacer y padecer cosas contrarias a la vez y en el mismo sentido","La inmortalidad del alma","El testimonio de los sentidos"], r:"Que una misma cosa no puede hacer y padecer cosas contrarias a la vez y en el mismo sentido", why:"Es el principio de no contradicción aplicado a la acción: el sediento que se niega a beber prueba que hay más de una parte."}
]};
