/* ============================================================
   Ficha: wittgenstein  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"wittgenstein", trad:"europea", nombre:"Ludwig Wittgenstein", fechas:"1889–1951 · Austria/Reino Unido", escuela:"Filosofía del lenguaje", icon:"🗝️", profundizada:true,
 tesis:"Wittgenstein escribió dos filosofías y sostuvo que la primera estaba en lo esencial equivocada. En el Tractatus, la proposición tiene sentido porque es una figura lógica de un hecho posible: comparte con lo que representa una misma forma, y todo aquello que no puede figurarse —la ética, la estética, el sentido de la vida, la forma lógica misma— no puede decirse, solo mostrarse, de modo que el libro termina mandando callar y pidiendo que se tire la escalera por la que se subió. En las Investigaciones filosóficas ataca justamente esa imagen: no hay una esencia del lenguaje ni una forma lógica oculta bajo la gramática corriente, sino una multiplicidad de juegos de lenguaje entrelazados por semejanzas de familia, y el significado de una palabra es, en la enorme mayoría de los casos, su uso en esas prácticas. Lo que no cambia entre ambas etapas es el diagnóstico: los problemas filosóficos no son problemas empíricos ni teóricos, son confusiones que surgen cuando el lenguaje gira en vacío, fuera del trabajo que normalmente hace. Por eso la filosofía, para él, no construye teorías: describe usos, desarma nudos gramaticales y le muestra a la mosca la salida de la botella.",
 obras:[
   {t:"Tractatus Logico-Philosophicus", d:"Único libro que publicó en vida, escrito en buena parte en las trincheras de la Primera Guerra y en un campo de prisioneros italiano, y aparecido en 1921 en alemán y en 1922 con traducción inglesa y un prólogo de Russell que Wittgenstein consideró un malentendido completo. Su forma es tan decisiva como su contenido: siete proposiciones numeradas en un sistema decimal donde cada decimal indica el peso lógico del comentario, de modo que el libro puede leerse como un árbol y no como una argumentación continua. Va del mundo como totalidad de hechos y no de cosas, a la proposición entendida como figura lógica de un estado de cosas posible, y de ahí a la tesis de que toda proposición con sentido es una función de verdad de proposiciones elementales, con las tautologías y contradicciones de la lógica como casos límite que no dicen nada. El final es el pasaje más discutido de la filosofía del siglo XX: lo que puede decirse se dice claramente, lo místico se muestra, y las proposiciones del propio libro son sinsentidos que hay que descartar como se descarta la escalera una vez que se subió. Wittgenstein creía haber resuelto definitivamente los problemas de la filosofía y abandonó la disciplina para hacer de maestro rural, jardinero de monasterio y arquitecto de la casa de su hermana en Viena."},
   {t:"Investigaciones filosóficas", d:"Obra póstuma publicada en 1953 y compuesta a lo largo de casi veinte años de reescritura, cuyo prólogo confiesa que los intentos de fundir sus pensamientos en un todo continuo siempre fracasaron y que ese fracaso pertenece a la naturaleza misma de la investigación: el libro es un álbum de bosquejos, un recorrido en zigzag por un paisaje. Arranca citando a san Agustín describiendo cómo aprendió a hablar —los mayores nombraban objetos y él asociaba el nombre con la cosa— para mostrar que ahí hay una imagen tan natural como tramposa del lenguaje, la de que toda palabra es un nombre y todo significado un objeto. Contra eso despliega el ejemplo del albañil que grita losa, cubo, pilar, viga, los juegos de lenguaje, las semejanzas de familia, la crítica a la idea de que entender es un proceso mental, la discusión sobre seguir una regla y el llamado argumento del lenguaje privado con la parábola del escarabajo en la caja. No hay tesis positivas que memorizar y ese es el punto: el método es terapéutico, avanza por preguntas, ejemplos imaginarios y objeciones de un interlocutor anónimo que suele ser el propio Wittgenstein del Tractatus. La segunda parte, hoy editada aparte como Filosofía de la psicología, contiene el análisis del ver como, con la figura del pato-conejo."},
   {t:"Sobre la certeza", d:"Anotaciones de los últimos dieciocho meses de su vida, escritas ya enfermo de cáncer y con las últimas entradas fechadas dos días antes de morir, publicadas en 1969. Nacen de una discusión con G. E. Moore, que había pretendido refutar al escéptico levantando la mano y diciendo sé que esto es una mano. Wittgenstein no le da la razón al escéptico ni a Moore: sostiene que esas certezas no son conocimientos, porque donde no cabe la duda tampoco cabe el saber, y que funcionan más bien como el lecho de un río por el que corren las proposiciones que sí pueden ponerse a prueba. Son bisagras: la puerta gira porque ellas no giran. De ahí una imagen de la justificación que corta con el fundacionalismo clásico, porque el fondo no es un conjunto de verdades evidentes sino una práctica heredada, un modo de actuar que se aprende antes que cualquier razón —al final del camino, escribe, no está una intuición sino que simplemente actúo así—. Es el texto donde mejor se ve que el último Wittgenstein no es relativista sino algo más incómodo: quien duda de todo ni siquiera llega a dudar, porque la duda misma presupone un juego que ya está en marcha. Su influencia en la epistemología contemporánea, a través de la llamada epistemología de las bisagras, es hoy mayor que nunca."},
   {t:"Los cuadernos azul y marrón", d:"Apuntes dictados a sus alumnos de Cambridge entre 1933 y 1935 y circulados durante años como copias mecanografiadas antes de publicarse en 1958, encuadernados originalmente con tapas azules y marrones, de donde les viene el nombre. Son la mejor puerta de entrada al Wittgenstein tardío, porque conservan el pulso oral de la clase y dicen de manera directa lo que las Investigaciones prefieren mostrar por ejemplos. Aquí aparece por primera vez en forma acabada la fórmula de que el significado de una palabra es su uso en el lenguaje, aquí se introduce la expresión juego de lenguaje como forma primitiva y completa de lenguaje, y aquí está el ataque frontal a lo que llama el ansia de generalidad: el desprecio por el caso particular y la superstición de que detrás de un nombre común tiene que haber una propiedad común. El Cuaderno marrón despliega además una serie larga de juegos de lenguaje imaginarios, construidos como tribus con prácticas lingüísticas mínimas, que funcionan como objetos de comparación para ver lo que nuestra propia gramática tiene de contingente. Quien encuentra las Investigaciones demasiado elípticas suele entenderlas después de leer estos cuadernos."},
   {t:"Observaciones filosóficas", d:"Manuscrito compuesto en 1929 y 1930, al volver a Cambridge después de una década fuera de la filosofía, y presentado como informe de trabajo para renovar su beca en el Trinity College; se publicó recién en 1964. Su interés es casi clínico: es el laboratorio donde el Tractatus se rompe por dentro y todavía no hay nada armado que lo reemplace. El golpe decisivo es el llamado problema de la exclusión de los colores, que él mismo detecta: si un punto del campo visual no puede ser rojo y verde a la vez, y esa imposibilidad no es lógica en el sentido del Tractatus ni empírica, entonces las proposiciones elementales no son independientes entre sí, y con eso cae una pieza estructural del sistema. A partir de ahí empieza a hablar de sistemas de proposiciones, de espacios gramaticales, de la comparación de la proposición con la realidad como aplicación de una regla y no como espejo, y a tratar la filosofía como gramática. Leerlo junto al Tractatus y a las Investigaciones es el mejor antídoto contra la caricatura de dos Wittgenstein separados por un abismo: lo que se ve es un pensamiento que se corrige a sí mismo paso a paso, y que tarda años en encontrar el vocabulario nuevo."}
 ],
 conceptos:[
   {t:"La teoría figurativa o pictórica de la proposición", d:"Es el corazón del Tractatus y la anécdota de su origen es famosa: Wittgenstein leyó en una revista que en un juicio parisino por un accidente de tránsito se había usado una maqueta con muñecos y autitos para reconstruir el choque, y se le ocurrió que la maqueta podía representar el accidente porque las partes del modelo se relacionaban entre sí como las partes de lo representado. La proposición hace lo mismo: no es una lista de nombres ni un sonido asociado por costumbre a una cosa, es un modelo de la realidad, y lo que la vuelve capaz de representar es compartir con el hecho figurado una misma forma lógica. De ahí se sigue algo poderoso: una proposición con sentido puede ser falsa sin dejar de tener sentido, porque figura un estado de cosas posible, exista o no. Y se sigue también el límite del sistema: la forma lógica que la figura comparte con lo figurado no puede a su vez figurarse, porque para representarla habría que salirse fuera de la lógica y del mundo. Esa forma se muestra en la proposición, no se dice con ella, y en esa distinción se apoya todo lo que viene después."},
   {t:"Decir y mostrar: los límites del lenguaje", d:"La frase más citada de Wittgenstein —de lo que no se puede hablar hay que callar— casi siempre se lee al revés de como él la escribió. No es una invitación al misticismo vago ni un desprecio positivista por lo que no es ciencia: es la conclusión técnica de la teoría figurativa. Si tener sentido consiste en figurar un estado de cosas posible, entonces todo aquello que no es un hecho contingente cae fuera del lenguaje, y ahí caen la forma lógica, el sujeto, el valor, la ética, la estética y el sentido del mundo. Lo decisivo es el estatuto que Wittgenstein les da: no son tonterías desechables, son lo más importante, y por eso escribió a un editor que su libro constaba de dos partes, la escrita y la no escrita, y que la segunda era la que importaba. Lo que no puede decirse se muestra, y la carga de la frase está en el hay que: el silencio no es indiferencia sino respeto por una frontera. La tensión que el libro deja abierta es feroz y él la asume: si nada de esto puede decirse, tampoco puede decirlo el Tractatus, que por eso se declara a sí mismo sinsentido y se manda a tirar como una escalera. Los lectores resolutos, como Cora Diamond y James Conant, sostienen que hay que tomarse esa autodestrucción en serio; los tradicionales, que hay sinsentidos que sin embargo iluminan."},
   {t:"El solipsismo lógico del Tractatus", d:"En las proposiciones de la serie 5.6 aparece una de las tesis más extrañas del libro: los límites de mi lenguaje significan los límites de mi mundo. Wittgenstein sostiene que lo que el solipsista quiere decir es enteramente correcto, solo que no puede decirse, y agrega que el solipsismo, llevado con rigor hasta el final, coincide con el realismo puro. El argumento es este: el yo no es una cosa que se encuentre en el mundo, como no se encuentra el ojo dentro del campo visual, y sin embargo el campo visual está estructurado desde él. El sujeto filosófico no es parte del mundo sino su límite, y por eso no hay nada en la realidad que corresponda a la palabra yo tal como la usa la metafísica. La consecuencia es que el mundo del solipsista, una vez que se le quita el yo sustancial, es exactamente el mismo mundo que el del realista, y la disputa se disuelve. Es un movimiento que anticipa el método tardío: en vez de refutar una tesis metafísica, muestra que quien la sostiene no logró decir nada. La misma frontera aparece del lado ético, cuando escribe que el mundo del feliz es distinto del mundo del infeliz, no porque contenga otros hechos, sino porque cambia como totalidad."},
   {t:"Los juegos de lenguaje", d:"El término entra en los Cuadernos azul y marrón y organiza las Investigaciones, y conviene no aplanarlo: juego no significa acá algo frívolo ni un mero conjunto de reglas convencionales. Un juego de lenguaje es la totalidad formada por el lenguaje y las actividades con las que está entretejido, y Wittgenstein da una lista deliberadamente heterogénea para desarmar la ilusión de unidad: dar órdenes y obedecerlas, describir un objeto por su aspecto, informar un suceso, hacer conjeturas, inventar una historia, hacer un chiste, traducir, pedir, agradecer, maldecir, saludar, rezar. Su primer ejemplo es una tribu de albañiles cuyo idioma completo consta de cuatro palabras, losa, cubo, pilar y viga, y que sin embargo hacen con ellas algo que ninguna teoría del nombre explica: losa no nombra una losa, funciona como una orden entera. De ahí sale el segundo movimiento, más profundo: hablar un lenguaje forma parte de una actividad, de una forma de vida, de modo que entender una expresión no es captar un contenido mental sino saber jugar. Y de ahí el tercero: preguntar qué es el lenguaje en general es como preguntar qué es el juego en general, una pregunta que exige respuestas particulares y no una definición única."},
   {t:"El significado como uso", d:"La formulación es célebre y también la más citada fuera de contexto: para una gran clase de casos en que se emplea la palabra significado —aunque no para todos— puede explicarse así, el significado de una palabra es su uso en el lenguaje. Conviene notar las dos salvedades que casi siempre se borran al citarla: Wittgenstein habla de una clase de casos y no de todos, y está dando una regla práctica de método, no una teoría del significado que venga a sustituir a la referencial. Lo que ataca es un modelo mental: la idea de que además de la palabra hay un contenido interior, una imagen o un acto de entender, que sería el verdadero significado y del cual el uso sería solo el síntoma exterior. Su terapia consiste en invertir la dirección de la pregunta: en vez de preguntar qué significa realmente saber, esperar o entender, hay que mirar cómo se aprenden y se usan esas palabras, en qué circunstancias se dicen, qué cuenta como usarlas mal. La metáfora que ofrece es la de las herramientas de una caja: martillo, tenaza, sierra, cola, tornillos; las funciones son tan distintas como distintos son los objetos, y la uniformidad de las palabras escritas en fila engaña sobre la diversidad de lo que hacen."},
   {t:"Semejanzas de familia", d:"Frente a la exigencia de que todo concepto tenga una definición por condiciones necesarias y suficientes, Wittgenstein propone mirar en vez de pensar: mirá los juegos de mesa, de cartas, de pelota, olímpicos, los juegos de un chico solo tirando una pelota contra la pared, la ronda de rueda rueda. No busques lo que tienen en común, mirá si hay algo común. Lo que aparece es una red complicada de semejanzas que se superponen y se cruzan, a veces globales y a veces de detalle: algunos juegos tienen competencia, otros no; algunos tienen azar, otros destreza; algunos divierten, otros agotan. El nombre viene de los parecidos entre miembros de una familia, donde la nariz de uno reaparece en el segundo, los ojos del segundo en el tercero, y el primero y el tercero no se parecen en nada. El concepto se sostiene como una cuerda, cuya resistencia no viene de que una fibra la recorra entera sino del solapamiento de muchas fibras cortas. De esto se sigue que muchos conceptos tienen bordes borrosos y que eso no es un defecto que haya que reparar: un concepto de contornos difusos es a veces exactamente lo que se necesita, como una foto movida puede ser justo la que hace falta. La idea llegó lejos fuera de la filosofía, sobre todo a la psicología cognitiva de los prototipos de Eleanor Rosch."},
   {t:"El argumento del lenguaje privado", d:"Es el pasaje más discutido de las Investigaciones y también el peor entendido. Wittgenstein no niega que sintamos dolor ni que tengamos vida interior; pregunta algo más preciso: si sería posible un lenguaje cuyas palabras se refirieran a sensaciones que solo yo puedo conocer, de modo que nadie más pudiera entenderlo en principio. Su ejemplo es el del diario privado: alguien decide anotar una S cada vez que tiene cierta sensación, sin poder definirla con palabras públicas. El problema aparece al segundo día, cuando hay que decidir si esta sensación es la misma que aquella. No hay ningún criterio disponible aparte de que a uno le parezca la misma, y si lo único que puede distinguir lo correcto de lo incorrecto es que me parezca correcto, entonces la palabra correcto ya no hace ningún trabajo: en ese caso, escribe, no podemos hablar de correcto. Al costado pone la parábola del escarabajo en la caja: todos tenemos una caja que solo cada uno puede mirar y todos llamamos escarabajo a su contenido; si la palabra tiene un uso compartido, ese uso no puede depender de lo que hay en la caja, que incluso podría estar vacía o cambiar todo el tiempo. La conclusión no es conductista —Wittgenstein rechaza expresamente esa lectura— sino gramatical: el lenguaje de las sensaciones se aprende injertándose en conductas y reacciones naturales públicas, el quejido, el gesto, el consuelo, y por eso funciona."},
   {t:"Seguir una regla y la paradoja", d:"Wittgenstein observa algo simple y vertiginoso: ninguna regla determina por sí misma su propia aplicación, porque siempre puede encontrarse una interpretación de la regla que haga concordar con ella cualquier acción. Su ejemplo es el alumno al que se le enseña la serie sumá dos, que escribe correctamente hasta el 1000 y después continúa 1004, 1008, 1012; cuando se le corrige, insiste en que está haciendo lo mismo que antes, y no hay nada en el entrenamiento recibido ni en ningún estado mental pasado que excluya esa lectura. Esa es la paradoja del párrafo 201. Su respuesta consiste en cortar la cadena de interpretaciones: hay un modo de captar una regla que no es una interpretación sino que se muestra en lo que llamamos seguir la regla y contravenirla en los casos concretos, y por eso seguir una regla es una práctica, un uso, una costumbre, algo que uno hace ciegamente, sin más razones. De ahí también el argumento de que no puede seguirse una regla privadamente, porque entonces creer que la sigo y seguirla serían lo mismo. Saul Kripke leyó todo esto en 1982 como una paradoja escéptica con una solución escéptica de tipo comunitario, y la discusión sobre si ese Wittgenstein de Kripke es el verdadero o uno nuevo dividió a los especialistas durante cuarenta años."},
   {t:"Gramática filosófica y el lenguaje que gira en vacío", d:"Lo que Wittgenstein llama gramática no es la sintaxis escolar sino el conjunto de reglas que fijan qué tiene sentido decir: que el rojo es un color es una observación gramatical, no un descubrimiento, y por eso no se refuta con experimentos. Su diagnóstico de la filosofía se apoya entero en esto: los problemas filosóficos surgen cuando el lenguaje hace fiesta, cuando las palabras salen de vacaciones del trabajo que normalmente hacen y giran en vacío como una rueda que no engrana con nada. Preguntar dónde está el tiempo, qué es el significado en sí, dónde ocurre realmente el dolor, es tomar una forma de expresión prestada de un juego y usarla en otro donde no tiene empleo. De ahí su definición del método: la filosofía es una lucha contra el embrujamiento de nuestro entendimiento por medio del lenguaje, y el filósofo trata una pregunta como se trata una enfermedad. No hay un método único sino métodos, como hay terapias. Y la meta tampoco es una teoría: es una visión panorámica del uso de nuestras palabras, un ordenamiento de lo que ya sabemos, porque nada está oculto. Su imagen final, la más suya, es la del insecto que zumba contra el vidrio: ¿cuál es tu objetivo en filosofía? Mostrarle a la mosca la salida de la botella cazamoscas."}
 ],
 conexion:"Su giro hacia el uso ordinario conecta con el pragmatismo de <b>Dewey</b> y sobre todo con el neopragmatismo de <b>Rorty</b>, que leyó las Investigaciones como el certificado de defunción de la filosofía entendida como espejo de la naturaleza. Del otro lado, su diagnóstico de los pseudoproblemas lo enfrenta punto por punto con <b>Heidegger</b>: ambos sostienen que la tradición se enredó en su propio lenguaje, pero uno responde disolviendo la pregunta por el ser y el otro radicalizándola. Y su desconfianza hacia los conceptos fijos, junto con la idea del lenguaje como herramienta que hay que soltar cuando cumplió su función, lo acerca de manera inesperada a <b>Zhuangzi</b> y a <b>Nagarjuna</b>.",
 dialogo:{titulo:"El autor del Tractatus recibe una visita", lineas:[
   {quien:"Estudiante", texto:"Profesor, vengo del seminario y no entiendo nada. Leímos su Tractatus, donde dice que la proposición es una figura lógica del hecho. Después leímos las Investigaciones, donde dice más o menos que eso es un cuento. ¿Cuál de los dos libros tengo que creer?"},
   {quien:"Wittgenstein", texto:"Ninguno, si creer significa aceptar una doctrina. Pero le contesto derecho: desde hace dieciséis años vengo ocupándome de estos pensamientos y no puedo dejar de reconocer graves errores en lo que escribí en aquel primer libro. Eso lo puse en el prólogo, no me lo sacaron a la fuerza."},
   {quien:"Estudiante", texto:"Entonces el joven que escribió el Tractatus estaba equivocado."},
   {quien:"Wittgenstein", texto:"Estaba embrujado. Tenía una imagen delante y no podía salirse de ella, porque la imagen estaba en el lenguaje mismo y el lenguaje la repetía sin descanso. La imagen era esta: hablar es nombrar, y nombrar es tender un hilo entre una palabra y una cosa.", nota:"Wittgenstein pidió expresamente que las Investigaciones se publicaran junto al Tractatus, porque solo se entienden por contraste con él. La lectura de dos filosofías separadas por un abismo es cómoda pero discutida: intérpretes como Hacker subrayan la ruptura, mientras que otros —Diamond, Conant, Kremer— sostienen que el método terapéutico y el rechazo de las teorías filosóficas ya estaban en el libro de 1921."},
   {quien:"Estudiante", texto:"Pero era una imagen preciosa. Explicaba por qué una oración falsa igual tiene sentido, explicaba la lógica, explicaba los límites."},
   {quien:"Wittgenstein", texto:"Explicaba demasiado, que es el síntoma. Le pregunto algo. Un albañil le grita a su ayudante: ¡Losa! Y el otro le trae la losa. ¿Qué nombró ahí la palabra?"},
   {quien:"Estudiante", texto:"La losa, evidentemente."},
   {quien:"Wittgenstein", texto:"¿Sí? Entonces dígame qué agrega el grito. Si losa solo nombrara el objeto, el ayudante podría quedarse mirándolo con interés. Lo que ahí hay es una orden completa, un acto dentro de un trabajo. La palabra no cuelga de la cosa: funciona en una práctica."},
   {quien:"Estudiante", texto:"Bien, pero eso vale para las órdenes de los albañiles. Con las palabras serias —verdad, número, dolor, alma— tiene que haber algo más profundo debajo."},
   {quien:"Wittgenstein", texto:"Ese debajo es la enfermedad. No hay nada oculto: todo está a la vista y justamente por eso no lo vemos. Los aspectos más importantes de las cosas están escondidos por su simplicidad y su cotidianidad."},
   {quien:"Estudiante", texto:"Le pongo un caso mío entonces. Yo tengo una sensación rara en el pecho cuando voy a dar clase. Nadie más la conoce. Le pongo un nombre privado, la llamo S, y anoto cada vez que aparece. Ahí tengo un lenguaje que es solo mío."},
   {quien:"Wittgenstein", texto:"Anotó la S el lunes. Llega el jueves y siente algo. ¿Es la misma? Dígame con qué lo comprueba."},
   {quien:"Estudiante", texto:"Me acuerdo. Comparo con el recuerdo de la del lunes."},
   {quien:"Wittgenstein", texto:"Y si el recuerdo lo engaña, ¿con qué lo comprueba? Con otro recuerdo. Es como comprar un segundo ejemplar del mismo diario para verificar lo que dice el primero. Acá lo único que hay es que le parece la misma, y donde no se puede hablar de equivocarse tampoco se puede hablar de acertar.", nota:"Es importante no exagerar la conclusión: Wittgenstein no niega que usted sienta algo, ni sostiene una tesis conductista —la rechaza expresamente en el párrafo 307—. Lo que niega es que el significado de la palabra pueda descansar en un objeto interior al que nadie más tiene acceso. Kripke leyó este argumento como dependiente del de seguir una regla; otros intérpretes lo consideran independiente, y la disputa sigue abierta."},
   {quien:"Estudiante", texto:"Entonces mi sensación no importa."},
   {quien:"Wittgenstein", texto:"Importa muchísimo. Lo que no importa es como objeto: importa como parte de una vida donde usted se queja, hace una mueca, alguien le pregunta qué le pasa y usted contesta. Ahí aprendió la palabra, no mirando adentro."},
   {quien:"Estudiante", texto:"Me queda una duda incómoda. Si su método solo describe usos y no propone ninguna tesis, ¿qué gané yo viniendo hasta acá?"},
   {quien:"Wittgenstein", texto:"Nada, si esperaba una teoría. Todo, si el nudo se aflojó. La filosofía no descubre nada nuevo: deja todo como está y sin embargo, cuando funciona, uno deja de golpearse contra los límites del lenguaje. ¿Cuál es su objetivo en filosofía? Mostrarle a la mosca la salida de la botella."}
 ]},
 actividades:[
   {t:"Cazar una semejanza de familia en el terreno", d:"Elegí una categoría cotidiana y discutida —arte, deporte, trabajo, violencia, música, amistad, juego— y hacé el ejercicio en tres pasos, por escrito. Primero, antes de mirar nada, escribí la mejor definición por condiciones necesarias y suficientes que se te ocurra. Segundo, juntá quince casos reales y variados que todo el mundo llamaría con esa palabra, incluyendo casos incómodos: para arte, un fresco renacentista, un urinario firmado, un tatuaje, un jingle publicitario, una torta de cumpleaños decorada; para deporte, el ajedrez, el tiro con arco, el esquí de fondo, el automovilismo, el yoga. Tercero, pasá cada caso por tu definición y anotá cuáles quedan afuera y cuáles entran indebidamente. Después armá el mapa de semejanzas: qué rasgo comparte el caso uno con el dos, el dos con el tres, y verificá si el primero y el último comparten algo. Cerrá con un párrafo respondiendo la objeción obvia: si la definición falla, ¿eso muestra que no hay esencia, o solo que vos no la encontraste todavía?"},
   {t:"El diario privado de una sensación", d:"Durante tres días llevá el experimento del párrafo 258 en serio y no como metáfora. Elegí una sensación tuya, difusa y difícil de nombrar —la molestia antes de una reunión, cierta liviandad al despertarte bien, la puntada de vergüenza que aparece al recordar algo viejo— y ponele un signo arbitrario, una letra. Anotá la fecha y la hora cada vez que la sensación aparezca, sin usar ninguna palabra pública para describirla, ni dolor, ni ansiedad, ni cansancio. Al cuarto día escribí honestamente cómo decidiste en cada caso que era la misma sensación y no otra parecida, y qué habría contado como equivocarte. Después hacé la segunda mitad, que es la que vale: intentá explicarle esa sensación a alguien concreto, un amigo, un hermano, y registrá exactamente qué recursos usaste para lograrlo —comparaciones, situaciones típicas, gestos, el momento del día en que aparece—. La pregunta final es si esos recursos son públicos, y si podrías haber aprendido el nombre sin ellos."},
   {t:"Disolver un problema en vez de resolverlo", d:"Buscá un problema filosófico que te haya trabado alguna vez, sea de clase o propio: ¿qué es realmente el tiempo?, ¿tenemos libre albedrío?, ¿dónde está la mente?, ¿existe el yo?, ¿qué hace que algo sea realmente arte? Escribilo arriba de la hoja. Después prohibite la pregunta qué es en realidad y reemplazala por tres preguntas wittgensteinianas: cómo se le enseñó esta palabra a un chico, en qué situaciones concretas la usamos sin ningún problema, y qué contaría como usarla mal. Rastreá diez usos reales de la palabra sacados de conversaciones, noticias o mensajes, y fijate en cuál de esos usos aparece el problema. Casi siempre vas a descubrir que la pregunta nace al trasladar una expresión de un juego de lenguaje a otro, por ejemplo al preguntar dónde está el tiempo copiando la forma de dónde está la llave. Terminá con una autocrítica de una página: ¿el problema se disolvió de verdad, o simplemente decidiste dejar de hacerlo? Esa es exactamente la objeción que Russell le hizo a Wittgenstein, y merece que la contestes vos."}
 ],
 cuestionario:[
   {q:"Si el Wittgenstein tardío sostiene que no hay esencias y que la filosofía no debe proponer tesis, ¿no es eso mismo una tesis metafísica, y por lo tanto una autorrefutación?", p:"La objeción es vieja y sigue mordiendo. Wittgenstein la anticipa y responde que sus observaciones no son doctrinas sino recordatorios de cosas que ya sabíamos: no afirma que no existan esencias en el mundo, muestra que la búsqueda de una propiedad común detrás de cada nombre común no funciona en los casos que él examina. La defensa habitual es que el estatuto de sus afirmaciones es gramatical y no empírico: decir que el significado es el uso no describe un hecho oculto, propone una manera de mirar. Pero hay dos maneras de no quedar satisfecho. La primera es notar que la frase todo está a la vista, nada está oculto es difícilmente algo que esté a la vista. La segunda es que el rechazo de las teorías filosóficas convive con muchas afirmaciones generales y bastante fuertes sobre el lenguaje, las reglas y la mente; Hacker sostiene que se trata de gramática descriptiva y no de teoría, mientras que críticos como Russell y buena parte del naturalismo posterior contestan que eso es una teoría que se niega a pagar el costo de serlo."},
   {q:"La paradoja de seguir una regla, ¿lleva a un escepticismo devastador sobre el significado, como sostiene Kripke, o disuelve el problema, como sostiene Wittgenstein?", p:"Kripke, en 1982, leyó el párrafo 201 como la formulación del problema escéptico más radical que la filosofía haya visto: no hay ningún hecho —ni en mi conducta pasada, ni en mis estados mentales, ni en mis disposiciones— que determine que con más yo quería decir suma y no cuadición; en consecuencia, nadie ha querido decir nunca nada en particular. Su solución es escéptica al modo de Hume: se abandona la pregunta por el hecho que constituye el significado y se la reemplaza por condiciones de asertabilidad dentro de una comunidad que corrige. Contra esta lectura hay dos frentes. Los intérpretes ortodoxos señalan que el propio texto continúa diciendo que hubo ahí un malentendido, que existe un modo de captar la regla que no es interpretarla, de modo que la paradoja se presenta para ser disuelta y no para ser aceptada. McDowell agrega que Kripke solo se vuelve inevitable si uno mantiene el supuesto que Wittgenstein quiere abandonar, el de que la regla debe determinar de antemano cada aplicación desde afuera de la práctica. Queda además la objeción de que la salida comunitaria no ayuda: una comunidad entera puede desviarse del mismo modo que el alumno de la serie, y entonces vuelve a faltar un criterio."},
   {q:"¿Puede la idea del significado como uso dar cuenta de la matemática, donde las proposiciones parecen verdaderas con independencia de lo que hagan las comunidades humanas?", p:"Wittgenstein le dedicó a esto más páginas que a casi cualquier otro tema y su respuesta es la parte más resistida de su obra. Sostiene que una demostración no descubre una verdad preexistente en un reino platónico sino que instituye una regla nueva, que el matemático es un inventor y no un descubridor, y que la necesidad matemática expresa una decisión gramatical sobre qué vamos a contar como correcto. Sobre el teorema de incompletitud de Gödel escribió observaciones que muchos lógicos, empezando por Dummett y Kreisel, juzgaron confusas o directamente erróneas. La objeción central es fuerte: si la aritmética fuera solo nuestra práctica, resultaría inexplicable que funcione en la predicción de eclipses, en la ingeniería de puentes o en la física de partículas, y no se ve cómo un puro acuerdo comunitario obligaría a nadie a aceptar un resultado que nadie desea. La defensa contemporánea responde que Wittgenstein no es convencionalista en el sentido simple de que decidimos arbitrariamente, porque el entrenamiento, la regularidad de la naturaleza y nuestra forma de vida hacen que solo ciertas prácticas sean sostenibles; pero que el desacuerdo persista después de setenta años indica que la cuestión no está saldada."},
   {q:"¿Hay realmente dos Wittgenstein, o la ruptura entre el Tractatus y las Investigaciones se exagera?", p:"Los argumentos a favor de la ruptura están en el texto: el propio Wittgenstein escribió en el prólogo de 1945 que reconocía graves errores en su primer libro, abandonó la teoría figurativa, el atomismo lógico, la idea de una forma lógica única y la exigencia de análisis completo, y sustituyó el ideal de cristal de la lógica por el suelo áspero del uso ordinario, con su imagen de que sin fricción no se puede caminar. Pero la continuidad también está: en ambos períodos sostiene que los problemas filosóficos nacen de malentendidos de la lógica o de la gramática de nuestro lenguaje, que la filosofía es una actividad y no un cuerpo de doctrinas, que no hay que explicar sino clarificar, y que hay algo que solo puede mostrarse. Los llamados lectores resolutos, Diamond y Conant, llevan la continuidad más lejos y sostienen que el Tractatus ya era terapéutico y que su declaración de sinsentido debe tomarse literalmente; Hacker y Pears responden que eso borra la doctrina efectiva del libro temprano. Una posición intermedia razonable es que el período de 1929 a 1933 —el de las Observaciones filosóficas— muestra una corrección progresiva y no una conversión, y que hablar de dos filosofías es una comodidad pedagógica que conviene no confundir con una tesis histórica."},
   {q:"Si la filosofía deja todo como está y solo describe usos, ¿no se vuelve conservadora, incapaz de criticar o de revisar los conceptos que la sociedad ya tiene?", p:"Es la acusación de quietismo y tiene defensores serios. Marcuse y Gellner le reprocharon al análisis del lenguaje ordinario convertir el habla establecida en tribunal último, con lo cual el vocabulario heredado —incluidos sus prejuicios— queda blindado contra la crítica. Desde el pragmatismo, y a veces desde el propio Rorty, se agrega que si la filosofía no puede proponer conceptos mejores pierde la función reformadora que tuvo en Marx, en Dewey o en la teoría feminista, donde acuñar términos nuevos como acoso laboral o violencia simbólica cambió prácticas reales. La réplica tiene tres partes. Primero, que Wittgenstein describe usos pero también los compara con juegos de lenguaje imaginarios, y ese procedimiento sirve justamente para mostrar lo contingente de lo que parecía necesario. Segundo, que su método desarmó de hecho posiciones muy arraigadas, del dualismo cartesiano al mentalismo sobre el significado, lo que no parece conservador. Tercero, que Sobre la certeza describe las proposiciones bisagra como el lecho de un río que puede desplazarse con el tiempo, de modo que el fondo no es fijo. Lo que sí es cierto, y conviene concederlo, es que no ofrece ningún criterio para decidir cuándo un cambio conceptual es una mejora y cuándo es una pérdida."}
 ],
 cadena:{ titulo:"¿Qué estatuto tiene «hay que callar»?", intro:"Un razonamiento en ramas sobre el final del Tractatus. Si solo tienen sentido las proposiciones que figuran hechos posibles, la proposición 7 —de lo que no se puede hablar hay que callar— no figura ningún hecho. El propio libro lo admite en 6.54. Las ramas llevan a las grandes lecturas rivales del Tractatus, y una de ellas desemboca en las Investigaciones.", inicio:"n1", nodos:{
   n1:{ pregunta:"En 6.54 Wittgenstein escribe que sus proposiciones esclarecen porque quien lo entiende las reconoce al final como sinsentidos, después de haber subido por ellas como por una escalera. ¿Qué es entonces la proposición 7?", opciones:[
     {texto:"Un sinsentido más: según el criterio del propio libro, no figura ningún estado de cosas.", va:"n2a"},
     {texto:"Una indicación práctica y no una tesis: no dice cómo es el mundo, dice qué hacer.", va:"n2b"} ]},
   n2a:{ pregunta:"Si la proposición 7 es un sinsentido, también lo es la teoría figurativa que la fundamenta, y el resto del libro con ella. ¿Qué queda del Tractatus?", opciones:[
     {texto:"Nada que pueda afirmarse: sus sinsentidos no señalan verdades ocultas; el libro sirve para curarse del deseo de decirlas.", final:{tipo:"bien", texto:"Es la lectura resoluta de Cora Diamond y James Conant: el sinsentido es sinsentido sin más, y el Tractatus ya era terapéutico; lo que se tira con la escalera son también las supuestas doctrinas. Gana coherencia con 6.54 y con la continuidad metodológica que el diálogo menciona. Su precio es considerable: si el libro no sostenía ninguna doctrina, cuesta entender qué quiso decir Wittgenstein en 1945 al reconocer graves errores en lo que escribió allí. Hacker y Pears ven en eso la refutación de la lectura resoluta."}},
     {texto:"Algo que se muestra aunque no pueda decirse: son sinsentidos que iluminan la forma lógica.", va:"n3a"} ]},
   n3a:{ pregunta:"Es la lectura tradicional, la de Anscombe y Hacker: hay algo inefable que el libro intenta en vano decir y que sin embargo se muestra. Frank Ramsey, que tradujo el libro y lo discutió con Wittgenstein, objetó: «lo que no se puede decir no se puede decir, y tampoco se puede silbar». ¿Cómo respondés?", opciones:[
     {texto:"Ramsey tiene razón: si hablo de lo que «se muestra», ya lo estoy diciendo, y la frontera se viola.", final:{tipo:"bien", texto:"Sentiste la presión que termina rompiendo el sistema. Si la frontera entre decir y mostrar solo puede trazarse diciendo lo que cae del otro lado, el libro no puede sostenerse en sus propios términos. Es una de las razones por las que los lectores resolutos rechazan las verdades inefables, y una de las tensiones que Wittgenstein retoma al volver a Cambridge en 1929, cuando el Tractatus empieza a resquebrajarse por dentro."}},
     {texto:"Mostrar no es decir con otras palabras: la forma lógica se ve en el uso correcto de los signos, como la gramática de una lengua se ve al hablarla.", final:{tipo:"bien", texto:"Es la mejor defensa de la lectura tradicional, y tiene una consecuencia interesante: lo que se muestra se muestra en el funcionamiento de los signos, no en un contenido aparte. Si seguís ese hilo, llegás muy cerca del Wittgenstein tardío, para quien la gramática se exhibe en la práctica y no se describe desde afuera. Es un buen argumento a favor de la continuidad entre las dos filosofías."}} ]},
   n2b:{ pregunta:"En una carta de 1919 al editor Ludwig von Ficker, Wittgenstein escribió que su libro constaba de dos partes, la escrita y la no escrita, que la importante era la segunda y que el sentido del libro era ético. Si la proposición 7 es una exhortación, ¿a qué exhorta?", opciones:[
     {texto:"A no hablar de ética, religión ni sentido de la vida: son temas vacíos.", final:{tipo:"revisar", texto:"Es la lectura que hicieron los positivistas del Círculo de Viena, y es la que Wittgenstein rechazó con más fastidio. Para ellos lo que no es ciencia es palabrería; para él lo que no puede decirse es lo más importante, y el silencio es una forma de respeto, no de desprecio. La carta a Ficker lo dice con todas las letras. Volvé un paso y probá otra respuesta."}},
     {texto:"A dejar de buscar una teoría de lo más importante: la solución del problema de la vida se nota en que el problema desaparece (6.521).", va:"n3b"} ]},
   n3b:{ pregunta:"Pero una exhortación también está hecha de palabras. «Hay que callar» no figura ningún hecho y sin embargo parece decir algo sobre cómo vivir. ¿Qué concluís?", opciones:[
     {texto:"Que el marco del Tractatus era demasiado estrecho: el lenguaje hace mucho más que figurar hechos.", final:{tipo:"bien", texto:"Es el camino hacia las Investigaciones. En el parágrafo 23 Wittgenstein enumera la multiplicidad de juegos de lenguaje —ordenar, pedir, agradecer, maldecir, rezar— y lo contrasta explícitamente con lo que dijeron los lógicos, incluido el autor del Tractatus. La última frase del libro de 1921 pertenecía a un juego que ese libro no podía reconocer. Llegaste al punto en que el Tractatus se refuta a sí mismo no por contradicción, sino por la estrechez de su imagen del lenguaje."}},
     {texto:"Que no es una proposición sino un gesto, como señalar: y el silencio mismo es la respuesta.", final:{tipo:"bien", texto:"Es una lectura defendible y cercana a lo que Wittgenstein dijo en su Conferencia sobre ética de 1929: hablar de ética es arremeter contra los límites del lenguaje, algo perfectamente desesperanzado, pero es el documento de una tendencia del espíritu humano que él no podía dejar de respetar profundamente. El precio es que el gesto queda fuera de toda explicación: si tiene fuerza, esa fuerza no la da la teoría del libro. Y esa distancia entre lo que el libro hace y lo que su teoría permite es lo que después le hará abandonarla."}} ]}
 }},
 reconstruccion:[
   { titulo:"El diario privado (Investigaciones filosóficas, §258)",
     consigna:"Reconstruí el argumento del lenguaje privado tal como lo presenta el parágrafo 258. Una pieza atribuye a Wittgenstein una tesis que él no sostiene: dejala afuera y ordená el resto.",
     piezas:[
       {id:"w1", texto:"Supongamos que quiero llevar un diario sobre la repetición de cierta sensación: la asocio con el signo «S» y lo anoto en el calendario cada día que la tengo.", tipo:"premisa"},
       {id:"w2", texto:"No puedo definir «S» con palabras públicas; solo puedo concentrar la atención en la sensación, como si la señalara hacia adentro.", tipo:"premisa"},
       {id:"w3", texto:"Pero una definición sirve para fijar el significado de un signo: gracias a ella debería poder recordar después correctamente la conexión entre el signo y la sensación.", tipo:"premisa"},
       {id:"w4", texto:"Y en este caso no tengo ningún criterio de corrección: cualquier cosa que me parezca correcta será correcta, y eso solo quiere decir que aquí no se puede hablar de «correcto».", tipo:"premisa"},
       {id:"w5", texto:"Por lo tanto, la ceremonia privada no le da a «S» ningún significado: un signo cuyo uso correcto nadie —ni siquiera yo— podría distinguir de uno incorrecto no nombra nada, y el vocabulario de las sensaciones funciona por sus conexiones con la expresión natural y con criterios compartidos.", tipo:"conclusion"},
       {id:"wx", texto:"Además, como nunca puedo sentir la sensación de otro, no puedo saber si los demás sienten algo en absoluto: tal vez solo se comportan como si sintieran.", tipo:"distractor"}
     ],
     ordenCorrecto:["w1","w2","w3","w4","w5"],
     explicacion:"El centro del argumento es w4: donde lo único que decide si acerté es que me parezca que acerté, la distinción entre acertar y equivocarse se desploma, y con ella el significado. Por eso Wittgenstein compara el recurso a la memoria con comprar un segundo ejemplar del mismo diario para verificar lo que dice el primero (§265). La pieza sobrante es el escepticismo sobre las otras mentes, que es justamente lo que el argumento desarma: si el significado de «dolor» dependiera de un objeto privado, el escéptico tendría razón; como no depende, la pregunta pierde su base. Tampoco hay aquí conductismo: en §307 Wittgenstein rechaza ser un conductista disfrazado. Para discutir: ¿depende este argumento del de seguir una regla, como sostuvo Kripke, o se sostiene por sí solo?"},
   { titulo:"La paradoja de seguir una regla (Investigaciones filosóficas, §§185-202)",
     consigna:"Reconstruí cómo Wittgenstein llega de la paradoja del alumno a la tesis de que seguir una regla es una práctica. Una pieza expresa justamente la concepción que el argumento rechaza: dejala afuera.",
     piezas:[
       {id:"r1", texto:"Al alumno se le enseña la serie «sumar 2»; la continúa bien hasta 1000 y luego escribe 1004, 1008, 1012, y asegura que sigue haciendo lo mismo que antes.", tipo:"premisa"},
       {id:"r2", texto:"Nada en las instrucciones ni en los ejemplos que recibió excluye su lectura: toda serie finita de casos es compatible con infinitas reglas distintas.", tipo:"premisa"},
       {id:"r3", texto:"Si apelamos a una interpretación de la regla, esa interpretación es a su vez un signo que requiere ser interpretado, y así al infinito: cualquier acción podría hacerse concordar con la regla bajo alguna interpretación (§201).", tipo:"premisa"},
       {id:"r4", texto:"Eso muestra que hay una manera de captar una regla que no es una interpretación, sino que se manifiesta en lo que llamamos «seguir la regla» y «contravenirla» en los casos efectivos.", tipo:"premisa"},
       {id:"r5", texto:"Por lo tanto, seguir una regla es una práctica, una costumbre, un uso (§202); y por eso no se puede seguir una regla «privadamente», porque entonces creer que se la sigue sería lo mismo que seguirla.", tipo:"conclusion"},
       {id:"rx", texto:"Lo que fija qué regla sigo es un estado mental interior —mi intención de sumar 2—, que contiene de antemano, como en germen, todos los pasos de la serie.", tipo:"distractor"}
     ],
     ordenCorrecto:["r1","r2","r3","r4","r5"],
     explicacion:"El argumento tiene forma de reducción: r1-r3 muestran que ninguna fuente de determinación —ejemplos, instrucciones, interpretaciones— cierra la brecha entre la regla y su aplicación; r4 extrae la lección de que el problema estaba mal planteado, porque suponía que entender es interpretar. La conclusión conecta con el lenguaje privado: una práctica requiere la posibilidad de distinguir entre seguir la regla y creer que se la sigue. La pieza sobrante es la imagen que Wittgenstein ataca en §§187-188: la idea de que el acto de querer decir ya recorrió todos los pasos antes de darlos, como rieles tendidos al infinito. Para discutir: Kripke leyó r3 como una paradoja escéptica y propuso una solución comunitaria; los intérpretes ortodoxos sostienen que r4 disuelve la paradoja en lugar de aceptarla. La diferencia importa: en una lectura la comunidad fija el significado, en la otra solo es el lugar donde se ejerce."}
 ],
 dilemas:[
   { titulo:"¿Qué quiere decir «escribir»?",
     intro:"En el diálogo, Wittgenstein sostiene que el significado de una palabra no cuelga de un objeto interior sino que funciona en una práctica. Este caso pone esa tesis bajo presión: una regla escrita, un caso nuevo que nadie previó, una comunidad que la aplica de cierta manera y un individuo que sostiene que todos se equivocan.",
     pasos:[
       { id:"p1", situacion:"Sos parte del comité académico de tu facultad. El reglamento define plagio como «presentar como propio un texto que uno no escribió». Una estudiante, Lucía, entregó un ensayo cuyas ideas y borrador son suyos, pero le pidió a un programa de inteligencia artificial que reescribiera la prosa, párrafo por párrafo. Ella sostiene que eso es como usar un corrector ortográfico, que el reglamento siempre toleró. ¿Por dónde empezás?", opciones:[
         {texto:"Busco qué quisieron decir quienes redactaron el reglamento: eso fija el significado de «escribir».", consecuencia:"Es la intuición más natural, y Wittgenstein la examina en §§187-188: cuando el maestro enseñó la serie, ¿ya había pensado en el paso 1002? La intención de quien formula una regla no contiene, como en germen, todos sus casos. Vas a encontrar, como mucho, lo que los redactores pensaron; probablemente no pensaron en esto.", va:"p2a"},
         {texto:"Miro cómo se aplicó la regla hasta ahora: qué casos se sancionaron y cuáles no.", consecuencia:"Es el giro wittgensteiniano: en lugar de buscar el significado detrás de la regla, mirar su uso. Pero fijate lo que no te va a dar: la práctica pasada tampoco contiene el caso nuevo, igual que la serie hasta 1000 no contiene su continuación.", va:"p2b"},
         {texto:"Le pregunto a Lucía qué entiende ella por «escribir»: si actuó de buena fe, su interpretación vale.", consecuencia:"Su buena fe importa, y mucho, para decidir si hay culpa. Pero es otra pregunta. Si lo que ella entiende por la palabra decidiera qué significa, cualquier cosa que le pareciera correcta sería correcta: es exactamente la situación del diario privado, donde no se puede hablar de correcto.", va:"p2b"} ]},
       { id:"p2a", situacion:"Encontrás las actas. Los redactores discutieron sobre copiar de internet y sobre trabajos comprados; sobre programas que reescriben textos, nada. ¿Qué concluís?", opciones:[
         {texto:"Que el reglamento no dice nada sobre este caso: hay que absolver por falta de norma.", consecuencia:"Es jurídicamente prudente, pero supone que una regla es una tabla de casos previstos y que fuera de la tabla no hay nada. Wittgenstein diría que una regla nunca fue eso: siempre se aplica a casos que nadie enumeró, y la pregunta es cómo se sigue en ellos, no si alguien los anticipó.", va:"p3"},
         {texto:"Que hay que extender la regla por analogía con los casos previstos, y justificar la analogía.", consecuencia:"Es mirar semejanzas: el caso de Lucía se parece al corrector en algo y al trabajo comprado en otra cosa. No hay un hecho oculto que decida cuál semejanza pesa más; hay razones que se pueden dar y discutir. Eso es lo que Wittgenstein llama aplicar una regla sin interpretación final.", va:"p3"} ]},
       { id:"p2b", situacion:"La práctica es clara en los extremos: los correctores ortográficos siempre se permitieron; traducir automáticamente un texto ajeno siempre se sancionó. Pero hay un profesor, Ferreyra, que desde hace años sanciona cualquier uso de herramientas automáticas y dice que la comunidad está equivocada: «Escribir significa escribir, y eso no lo decide una votación». ¿Qué pensás?", opciones:[
         {texto:"Ferreyra no puede tener razón contra todos: el significado es el uso, y el uso es el de la comunidad.", consecuencia:"Es la lectura comunitaria que Kripke popularizó. Tiene un problema que conviene ver: si la comunidad decide sin más, una comunidad entera no podría nunca equivocarse sobre una palabra. Y Wittgenstein aclara en §241 que el acuerdo que importa no es de opiniones, sino en la forma de vida: una votación del claustro no es eso.", va:"p3"},
         {texto:"Ferreyra puede tener razón: una comunidad entera puede usar mal una palabra, como puede sumar mal.", consecuencia:"Es la objeción más fuerte contra Kripke. Pero entonces tenés que decir desde dónde se corrige a la comunidad. Una respuesta wittgensteiniana posible: desde el sentido de la práctica misma —para qué evaluamos lo que un estudiante escribe—, que es interno al juego y no un tribunal por encima de él.", va:"p3"} ]},
       { id:"p3", situacion:"El comité tiene que decidir hoy. ¿Qué proponés?", opciones:[
         {texto:"Sancionar: la prosa es parte de escribir, y la regla debe leerse según el propósito de la evaluación.", consecuencia:"Diste una razón que se puede discutir y que no pretende estar escrita de antemano en la regla. Su riesgo es la retroactividad: Lucía no podía saber que la práctica iba a extenderse en esa dirección.", va:null},
         {texto:"No sancionar esta vez y redactar una aclaración: la práctica no estaba fijada para este caso.", consecuencia:"Reconocés que el comité no está descubriendo lo que la regla ya decía, sino decidiendo cómo seguir. Es lo que Wittgenstein sostiene sobre la matemática, donde una demostración funciona como la adopción de una regla nueva. El costo es admitir en voz alta que la regla no bastaba.", va:null},
         {texto:"Dejar que cada profesor decida según su propio criterio.", consecuencia:"Parece respetuoso de la diversidad, pero vuelve a la regla privada: cada uno sigue lo que le parece, y ningún estudiante puede saber qué cuenta como seguir la regla. Wittgenstein diría que ahí ya no hay regla, solo una sucesión de impresiones.", va:null} ]}
     ],
     rubrica:[
       "Distinguí entre lo que el reglamento dice, lo que sus redactores tenían en mente y cómo se lo aplicó efectivamente.",
       "Puedo explicar por qué, según Wittgenstein, la intención de quien formula una regla no contiene de antemano todas sus aplicaciones.",
       "Identifiqué qué casos eran claros para la práctica y dónde empezaba el caso dudoso, sin fingir que la regla ya lo resolvía.",
       "Separé la interpretación personal de Lucía (que no puede fijar el significado) de su buena fe (que sí importa para juzgarla).",
       "Tomé en serio al disidente y dije qué haría falta para que una comunidad entera esté equivocada sobre una palabra.",
       "Distinguí entre el acuerdo de opiniones (una votación) y el acuerdo en una forma de vida (§241).",
       "Reconocí si mi decisión final descubría el significado de la regla o lo extendía, y dije cuál de las dos cosas hice."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.wittgenstein = { lecturas:[
 {titulo:"Tratado lógico-filosófico (Tractatus): el mundo, la figura y el silencio", fuente:"The Ludwig Wittgenstein Project — Tratado lógico-filosófico, traducción castellana de Alberto Buscató (texto íntegro, acceso libre)", url:"https://wittgensteinproject.org/w/index.php/Tratado_l%C3%B3gico-filos%C3%B3fico",
  extracto:`El Tractatus está escrito como un sistema numerado de proposiciones, y conviene leerlo así: cada número es una tesis, y los decimales son comentarios de la tesis anterior. La traducción castellana libre de Alberto Buscató permite seguir ese andamiaje en español palabra por palabra.

Las dos primeras proposiciones ya deciden la ontología del libro. «El mundo es todo lo que es el caso.» Y enseguida: «El mundo es la totalidad de los hechos, no de las cosas.» La diferencia es decisiva y es la primera lección del texto: lo que hay no son objetos sueltos sino situaciones, configuraciones de objetos; un inventario del universo no sería una lista de cosas sino una lista de hechos. Los objetos son lo que puede combinarse, y la proposición habla del mundo solo porque reproduce una de esas combinaciones posibles.

De ahí sale la teoría figurativa del significado, que el libro introduce con una fórmula casi visual: «Nosotros nos hacemos imágenes de los hechos», y precisa que «la imagen es un modelo de la realidad». La palabra alemana es Bild —figura, imagen, modelo—, y Wittgenstein la toma en serio: una figura representa porque sus elementos están dispuestos entre sí del mismo modo en que lo están los elementos del hecho figurado. Lo que la figura debe compartir con la realidad para poder representarla es la forma lógica. Trasladado al lenguaje, el resultado es la proposición 4.01: «La proposición es una imagen de la realidad.»

Y aquí aparece el límite que da al libro su tono. Si la proposición representa gracias a la forma lógica, entonces la forma lógica misma no puede ser representada por ninguna proposición: «La proposición no puede representar la forma lógica, ella se refleja en ella.» Lo que hace posible decir no puede, a su vez, decirse. Se muestra. Sobre esa distinción entre decir y mostrar descansa todo lo que el Tractatus excluye del lenguaje con sentido: la lógica, la ética, la estética, el valor de la vida, el sujeto metafísico.

El prólogo ya anticipa el programa y el desenlace: «lo que se puede decir en cualquier caso, se puede decir claramente; y de lo que no se puede hablar, de ello se debe guardar silencio». La proposición 7 repite esa última frase como única línea del último capítulo. Pero antes Wittgenstein da un paso que ha desconcertado a todos sus lectores: reconoce que sus propias proposiciones son sinsentidos, y que quien lo entiende debe descartarlas —la comparación célebre es la de la escalera que se arroja después de haber subido por ella—. El libro no enseña doctrinas: entrena una mirada y después se autoelimina.

Leído hoy, el Tractatus no es solo la obra de juventud que Wittgenstein después criticó. Es también el planteo más limpio de una idea que nunca abandonó: que casi todos los problemas filosóficos nacen de no entender la lógica de nuestro lenguaje.`,
  comentario:"Tener el texto en español permite ver que la teoría figurativa no es una metáfora vaga sino una tesis técnica: representar es compartir forma lógica. Fijate en la autodestrucción final del libro — es el mismo gesto terapéutico que reaparecerá, con otro método, en las Investigaciones. Y notá que la ética no queda degradada sino protegida: cae del lado de lo que se muestra, no de lo que se dice mal."},
 {titulo:"Las Investigaciones filosóficas: juegos de lenguaje, parecido de familia y seguir una regla", fuente:"Stanford Encyclopedia of Philosophy — Ludwig Wittgenstein", url:"https://plato.stanford.edu/entries/wittgenstein/",
  extracto:`Las Investigaciones filosóficas (póstumas, 1953) abren atacando la imagen misma que había sostenido el Tractatus: la de un lenguaje cuya función central es nombrar y representar. Wittgenstein cita a san Agustín describiendo cómo aprendió a hablar —los mayores nombraban objetos y él asociaba nombre y cosa— y responde que esa descripción contiene una imagen demasiado simple de la esencia del lenguaje: como si toda palabra fuera un nombre y todo significado, un objeto correlativo.

Contra eso introduce los juegos de lenguaje. Empieza con el ejemplo del albañil y su ayudante, que operan con cuatro palabras: «losa», «cubo», «pilar», «viga». ¿Es «losa» el nombre de un objeto, o una orden completa? La pregunta revela que el significado depende de la práctica en que la palabra está inserta. Y sigue una lista deliberadamente heterogénea de juegos: dar órdenes, describir un objeto, informar de un suceso, hacer conjeturas, inventar una historia, hacer un chiste, traducir, pedir, agradecer, maldecir, saludar, rezar. «Es interesante comparar la multiplicidad de las herramientas del lenguaje y de sus modos de empleo con lo que los filósofos han dicho sobre la estructura del lenguaje.»

De ahí la fórmula: «el significado de una palabra es su uso en el lenguaje». Y de ahí también el parecido de familia. ¿Qué tienen en común todos los juegos — de mesa, de cartas, de pelota, olímpicos? «No digas: tiene que haber algo común, pues de otro modo no se llamarían juegos, sino mira si hay algo común a todos ellos.» Lo que se encuentra es «una complicada red de parecidos que se superponen y entrecruzan», como los parecidos entre los miembros de una familia. Los conceptos no tienen fronteras nítidas, y no por eso son inservibles: «¿es acaso inutilizable una definición imprecisa? Una iluminación difusa puede bastar para el propósito».

El problema de seguir una regla lleva esto al límite. Toda regla puede interpretarse de modos que hagan compatible cualquier acción con ella, así que ninguna interpretación fija el uso correcto. La salida no es un hecho mental privado sino la práctica: «seguir una regla es una práctica», y «obedecer una regla, hacer una comunicación, dar una orden, jugar una partida de ajedrez son costumbres (usos, instituciones)». De ahí el argumento contra el lenguaje privado: donde no puede haber criterio público de corrección, no hay distinción entre seguir la regla y creer que se la sigue.

La consecuencia metafilosófica: los problemas filosóficos no se resuelven, se disuelven. Surgen «cuando el lenguaje hace fiesta», cuando sacamos una palabra de su juego habitual. La tarea es terapéutica: «mostrarle a la mosca la salida de la botella cazamoscas».`,
  comentario:"Leer las dos etapas juntas deja ver qué se conserva: en ambas, la filosofía tradicional es diagnosticada como confusión lingüística; lo que cambia es el remedio — de una lógica ideal a la descripción de prácticas reales. El parecido de familia es la herramienta conceptual más exportable del texto, útil para discutir cualquier definición esencialista. Y el argumento de seguir una regla responde a la pregunta del cuestionario: el criterio de corrección es comunitario, no metafísico."}
], preguntasLectura:[
 {q:"¿Qué sostiene la teoría figurativa del Tractatus?", opciones:["Que las palabras son imágenes mentales","Que la proposición representa un hecho posible por compartir con él una forma lógica","Que el significado es el uso","Que todo lenguaje es privado"], r:"Que la proposición representa un hecho posible por compartir con él una forma lógica", why:"«La proposición es una imagen de la realidad» (4.01): es la tesis central de la primera etapa, abandonada después en las Investigaciones."},
 {q:"Según la proposición 1.1 del Tractatus, ¿de qué está hecho el mundo?", opciones:["De la totalidad de las cosas","De la totalidad de los hechos, no de las cosas","De ideas en la mente","De proposiciones verdaderas"], r:"De la totalidad de los hechos, no de las cosas", why:"El inventario del mundo no es una lista de objetos sueltos sino de situaciones: por eso la proposición, que figura hechos, puede hablar del mundo."},
 {q:"¿Por qué el Tractatus dice que sus propias proposiciones deben descartarse?", opciones:["Porque contienen errores de cálculo","Porque hablan de la forma lógica, que solo puede mostrarse y no decirse","Porque Wittgenstein cambió de opinión en 1953","Porque son demasiado breves"], r:"Porque hablan de la forma lógica, que solo puede mostrarse y no decirse", why:"De ahí la imagen de la escalera que se arroja tras subir, y el cierre: de lo que no se puede hablar, hay que guardar silencio."},
 {q:"¿Qué muestra el ejemplo del albañil y su ayudante («losa», «cubo», «pilar», «viga»)?", opciones:["Que las palabras son siempre nombres de objetos","Que el significado depende de la práctica en que la palabra se usa","Que el lenguaje necesita gramática escrita","Que los obreros no filosofan"], r:"Que el significado depende de la práctica en que la palabra se usa", why:"«Losa» funciona como orden completa, no como mero nombre: por eso Wittgenstein habla de juegos de lenguaje."},
 {q:"Según el argumento de seguir una regla, ¿qué garantiza el uso correcto de una palabra?", opciones:["Un hecho mental privado","Una definición del diccionario","La práctica compartida de una comunidad","La forma lógica de la proposición"], r:"La práctica compartida de una comunidad", why:"«Seguir una regla es una práctica»; de ahí también el argumento contra el lenguaje privado."}
]};
