/* ============================================================
   Ficha: zambrano  ·  tradición: europea
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"zambrano", trad:"europea", nombre:"María Zambrano", fechas:"1904–1991 · España/exilio en América", escuela:"Razón poética", icon:"🌿", profundizada:true,
 tesis:"La filosofía occidental nació de una separación: el filósofo quiso poseer la verdad entera por medio del concepto, y dejó afuera al poeta, que se quedaba fiel a lo que aparece, a lo concreto y a lo que no se deja explicar. Esa razón que domina terminó desconociendo la vida de la que salió. Zambrano propone una razón poética: una razón que no renuncia a pensar, pero que piensa desde la escucha, la confesión y la experiencia, y que deja hablar a lo que la razón discursiva silenciaba —los sentimientos, los sueños, lo sagrado, la historia de los vencidos—. Pensar así es también una forma de vivir, y el exilio, que ella vivió durante cuarenta y cinco años, es su lugar privilegiado.",
 obras:[
   {t:"Filosofía y poesía (1939)", d:"Escrito y publicado en Morelia, México, en el primer año de su exilio, y el libro que plantea su problema central. Desde Platón, dice, filosofía y poesía se separaron: el filósofo buscó la unidad del ser por medio de la razón, con un esfuerzo que tiene algo de violencia sobre las apariencias, mientras el poeta se quedó con lo múltiple, lo sensible, lo que no se deja reducir a concepto. La filosofía ganó el poder y la poesía quedó como algo sospechoso, sin derecho a la verdad. Zambrano no propone elegir a la poesía contra la filosofía, sino buscar una reconciliación en la que la razón recupere lo que dejó afuera."},
   {t:"La confesión: género literario y método (1943)", d:"Un estudio de la confesión como forma de pensar, desde las Confesiones de san Agustín hasta Rousseau y los modernos. La confesión no es un relato de hechos ni un sistema de ideas: es la palabra de alguien que se busca a sí mismo y se expone ante otro, partiendo de su propia confusión. Para Zambrano es un método: una manera de llegar a la verdad que no se separa de la vida de quien la busca. El libro muestra por qué su filosofía tiene tantas veces la forma del ensayo, el diario o la meditación, y no la del tratado."},
   {t:"El hombre y lo divino (1955)", d:"Considerado su libro mayor. Recorre la historia de la relación entre los seres humanos y lo sagrado, desde los dioses griegos hasta la «muerte de Dios» proclamada por Nietzsche. Sostiene que lo sagrado no es una creencia entre otras, sino una dimensión de la experiencia humana que antecede a los dioses: el fondo oscuro, inquietante, del que surgen. Cuando la modernidad expulsó a los dioses, lo sagrado no desapareció: reapareció en formas degradadas, como la idolatría de la historia, del Estado o del progreso. El libro es una crítica del racionalismo que se creyó capaz de prescindir de lo que no entiende."},
   {t:"Persona y democracia (1958)", d:"Su libro político más importante, escrito con la experiencia de la guerra civil española, los fascismos y el estalinismo. Distingue al individuo, abstracto y aislado, de la persona, que es alguien concreto, con una historia y una intimidad que no se agota en ningún papel social. La historia occidental, dice, ha sido una historia sacrificial, en la que se inmolaba a las personas en nombre de ídolos. La democracia es la forma de sociedad en la que ser persona no solo está permitido, sino exigido: un orden que no pide sacrificios humanos. El libro es también una crítica de las utopías que, en nombre del futuro, justificaron el terror."},
   {t:"Claros del bosque (1977) y La tumba de Antígona (1967)", d:"Claros del bosque es su libro más poético y más difícil: una serie de fragmentos sobre la experiencia de que algo se revele de pronto, como un claro en medio del bosque, sin que lo busquemos. No se puede ir a buscar un claro; hay que dejarse encontrar por él. La tumba de Antígona reescribe la tragedia de Sófocles: Antígona no muere enseguida en su tumba, sino que habla, delira y piensa, y desde ese encierro entre la vida y la muerte se convierte en figura de todos los que sufren la guerra civil y el exilio. Zambrano escribió este texto pensando en su propia hermana, Araceli, que sufrió la persecución nazi en Francia."}
 ],
 conceptos:[
   {t:"Razón poética", d:"Es el nombre de su propuesta y su concepto más citado. No es una razón que renuncie a pensar para entregarse a la emoción, ni una poesía que pretenda reemplazar a la filosofía. Es una razón que acepta ser tocada por lo que intenta comprender: que escucha antes de definir, que parte de la experiencia concreta y que no se cree dueña de la realidad. Viene de la razón vital de Ortega y Gasset, su maestro, que había sostenido que la razón debía partir de la vida. Zambrano va más lejos: no basta con que la razón sirva a la vida, tiene que dejarse transformar por lo que la vida le muestra, incluso por lo que no se deja decir con conceptos."},
   {t:"La separación entre filosofía y poesía", d:"El punto de partida de su obra. Con Platón, la filosofía decidió que la verdad estaba en lo que no cambia, y miró con sospecha a la poesía, que se quedaba con las apariencias y las pasiones; en la República, los poetas son expulsados de la ciudad ideal. Para Zambrano, esa separación no fue solo una decisión teórica: definió una cultura entera, que valoró el dominio, la abstracción y la unidad, y despreció lo concreto, lo múltiple y lo frágil. La filosofía, dice, nace de una violencia, de un querer poseer el todo; la poesía, de una fidelidad, de un no querer renunciar a nada de lo que aparece."},
   {t:"Escuchar antes que dominar", d:"Es la actitud que la razón poética pide. La razón moderna, de Descartes en adelante, se pensó como un sujeto que se apodera del mundo y lo convierte en objeto de conocimiento. Zambrano propone una actitud receptiva: dejar que las cosas se muestren, prestar atención a lo que no encaja en las categorías previas, aceptar que hay realidades que solo se entregan a quien no las fuerza. Por eso usa tantas imágenes de luz tenue, de penumbra, de aurora: no la luz que lo ilumina todo de golpe, sino la que deja ver poco a poco."},
   {t:"La confesión como método", d:"Frente al sistema, que pretende una verdad impersonal, Zambrano reivindica la confesión: la palabra de alguien que parte de su propia vida y de su propia confusión, y se expone ante otro para encontrarse. San Agustín es su modelo. La confesión no busca demostrar, sino transparentar: hacer visible lo que uno es. Por eso no es solo un género literario, sino un método de conocimiento, especialmente para las verdades que no se pueden alcanzar desde afuera, como la verdad sobre uno mismo o sobre una historia vivida."},
   {t:"Lo sagrado", d:"Para Zambrano, lo sagrado no es lo mismo que los dioses ni que la religión institucional. Es una dimensión primaria de la experiencia: el fondo oscuro, inquietante e inagotable de la realidad, que se experimenta antes de que se lo nombre o se lo organice. Los dioses son la forma que los seres humanos le dieron a lo sagrado para poder relacionarse con él. Cuando la modernidad declaró que Dios había muerto, creyó haberse librado de lo sagrado, pero lo sagrado volvió en formas degradadas: el culto a la historia, al Estado o al líder. Es una de sus tesis más fuertes sobre el siglo XX."},
   {t:"Persona frente a individuo", d:"El individuo es una abstracción: una unidad intercambiable, contada en estadísticas, definida por sus derechos formales o por su función. La persona es alguien concreto, con una intimidad que no se agota en ningún papel, con una historia propia y con la capacidad de trascenderse. Zambrano sostiene que las grandes catástrofes del siglo XX ocurrieron cuando se trató a las personas como individuos, o como piezas de un proyecto histórico. La democracia, en su sentido, no es solo un procedimiento para elegir gobernantes, sino el orden que exige que cada uno pueda ser persona."},
   {t:"La historia sacrificial", d:"En Persona y democracia, Zambrano sostiene que la historia de Occidente ha sido una tragedia en la que se sacrificaba a seres humanos en el altar de ídolos: el imperio, la nación, la raza, la revolución, el progreso. Cada época creyó que su fin justificaba esos sacrificios. La salida no es abandonar toda esperanza histórica, sino dejar de pedirle a la historia que nos salve a costa de las personas. Su experiencia de la guerra civil española, en la que los dos bandos justificaron la violencia en nombre de un futuro, está detrás de este concepto."},
   {t:"El exilio", d:"Zambrano vivió exiliada desde enero de 1939, cuando cruzó la frontera con Francia junto a miles de republicanos, hasta 1984: México, Cuba, Puerto Rico, Italia, Francia, Suiza. El exilio no es en su obra solo un dato biográfico, sino una condición filosófica. El exiliado ha perdido su lugar y no tiene otro, y por eso ve lo que los instalados no ven: la fragilidad de toda pertenencia, la verdad de los vencidos. Escribió que el exilio fue su patria. Su obra es una de las grandes reflexiones sobre el desarraigo, y resulta muy cercana a la experiencia de los desplazados y migrantes de América Latina."},
   {t:"Los claros y la aurora", d:"Son sus imágenes centrales del conocimiento. Un claro del bosque es un lugar donde, de pronto, entra la luz entre los árboles; no se puede ir a buscarlo con un mapa, solo se lo encuentra. Así es, para Zambrano, la verdad más importante: no se conquista con un método, sino que se revela a quien está atento. La aurora es el momento en que la luz empieza, antes del día pleno: una luz que todavía no lo ilumina todo, y por eso deja ver lo que la luz del mediodía borra. Estas imágenes expresan su desconfianza ante la razón que pretende verlo todo claro de una vez."}
 ],
 conexion:"Fue alumna y discípula de <b>Ortega y Gasset</b>, de quien toma la razón vital para transformarla en razón poética, y estudió también con Xavier Zubiri y Manuel García Morente en Madrid. Discute con <b>Platón</b>, que expulsó a los poetas de la ciudad, y con <b>Descartes</b>, cuya razón dominadora critica. Comparte con <b>Heidegger</b> la sospecha sobre la metafísica occidental y la atención a la poesía, pero rechaza su tono heroico. Su idea de lo sagrado dialoga con <b>Nietzsche</b> y la muerte de Dios. Su experiencia del exilio la acerca a <b>Arendt</b>, que pensó la condición de los apátridas, y a la filosofía latinoamericana: vivió en México y en Cuba, donde influyó en el grupo de poetas de la revista Orígenes, con José Lezama Lima. Fue la primera mujer en recibir el Premio Cervantes, en 1988. Su obra fue criticada por oscura y poco argumentativa; ella respondía que hay verdades que no se dejan argumentar sin traicionarse.",
 dialogo:{titulo:"¿No es la poesía una forma de no pensar?", lineas:[
   {quien:"Estudiante", texto:"María, con respeto: a mí me enseñaron que la filosofía es argumentación. Usted escribe con imágenes, con claros del bosque y auroras. ¿No es eso poesía disfrazada de filosofía?"},
   {quien:"Zambrano", texto:"Tu pregunta es muy antigua; la hizo Platón cuando expulsó a los poetas de su república. Y la entiendo. Pero te devuelvo otra: ¿todo lo que importa se puede argumentar?"},
   {quien:"Estudiante", texto:"Si no se puede argumentar, no se puede saber. Sería solo opinión o sentimiento."},
   {quien:"Zambrano", texto:"Pensá en algo que sepas con certeza y que no podrías demostrar. Que tu madre te quiere, por ejemplo. ¿Lo sabés por un argumento?"},
   {quien:"Estudiante", texto:"No. Lo sé porque lo viví. Pero eso no es filosofía."},
   {quien:"Zambrano", texto:"Ahí está el problema. La filosofía decidió que solo valía como saber lo que se podía demostrar, y dejó afuera todo lo que se sabe viviendo. Ganó rigor, pero perdió el mundo del que había salido. Yo no quiero renunciar al rigor: quiero una razón que no se crea dueña de todo, que sepa escuchar."},
   {quien:"Estudiante", texto:"Pero entonces cualquiera puede decir que «sabe» algo porque lo siente, y no hay cómo discutir con él."},
   {quien:"Zambrano", texto:"Es un riesgo verdadero, y no lo niego. Por eso no hablo de sentimiento, sino de razón poética: una razón que piensa la experiencia, que la confiesa ante otros, que se deja corregir. La confesión no es el capricho de cada uno; es exponerse, y quien se expone puede ser contradicho."},
   {quien:"Estudiante", texto:"Usted vivió cuarenta y cinco años en el exilio. ¿Eso tiene que ver con su filosofía?"},
   {quien:"Zambrano", texto:"Todo. El exiliado perdió su lugar y no tiene otro. Desde ahí se ve lo que los instalados no ven: que toda pertenencia es frágil, que la historia la escriben los que ganaron. Llegué a decir que el exilio fue mi patria. No porque lo haya elegido, sino porque fue el lugar desde donde aprendí a mirar."},
   {quien:"Estudiante", texto:"¿Y qué le diría a alguien que hoy está desplazado, que tuvo que dejar su tierra?"},
   {quien:"Zambrano", texto:"Que su experiencia no es solo una desgracia que hay que olvidar, sino una forma de saber. Y que los que no la vivieron tienen la obligación de escucharla, no como estadística, sino como la palabra de una persona.", nota:"La frase «el exilio ha sido como mi patria» aparece, con variantes, en entrevistas y textos tardíos de Zambrano. El resto del diálogo es una reconstrucción didáctica de sus ideas."}
 ]},
 actividades:[
   {t:"Un claro: escribir lo que se revela", d:"Durante tres días, llevá un cuaderno y anotá momentos en que algo se te mostró de pronto, sin que lo buscaras: una idea que entendiste caminando, un recuerdo que volvió, una persona que viste de otra manera, un paisaje que te detuvo. Para cada momento, escribí qué pasó y qué te mostró. Al final, escribí una página comparando ese tipo de conocimiento con el que obtenés estudiando para un examen: ¿son dos formas de saber?, ¿una vale más que la otra?, ¿qué diría Zambrano?"},
   {t:"Una confesión filosófica", d:"Escribí una confesión en el sentido de Zambrano: no un diario de hechos, sino un texto que parta de una confusión real tuya —una pregunta sobre tu vida, una decisión que no entendés, algo que te duele— y que intente pensarla con honestidad ante un lector. No busques demostrar nada ni dar consejos; buscá transparentarte. Después, releelo y escribí un párrafo sobre qué entendiste al escribir que no entendías antes, y si ese entender es conocimiento."},
   {t:"Escuchar una historia de desarraigo", d:"Buscá a alguien de tu entorno que haya tenido que dejar su lugar: una persona desplazada por la violencia, un migrante, alguien que se fue del campo a la ciudad. Pedile permiso para conversar sobre su experiencia, con respeto y sin forzar lo que no quiera contar. Escribí después un texto que no sea una estadística ni un informe, sino el relato de una persona, cuidando su privacidad. Terminá con una reflexión: ¿qué supiste escuchando que no habrías sabido con datos?, ¿cómo cambia tu idea de la violencia o la migración?"}
 ],
 cuestionario:[
   {q:"¿No es la razón poética una manera de abandonar la exigencia de argumentar, que es lo propio de la filosofía?", p:"Es la objeción más frecuente, y Zambrano la conocía. Su respuesta es que no propone abandonar la razón, sino ampliarla. La razón discursiva, la que argumenta y demuestra, es legítima, pero se volvió excluyente: decidió que solo era conocimiento lo que se podía demostrar, y dejó afuera la experiencia vivida, los sentimientos, lo sagrado y la historia concreta de las personas. La razón poética no reemplaza el argumento, sino que lo precede y lo desborda: escucha lo que todavía no tiene concepto. La crítica sigue siendo seria: si no hay criterios de corrección, cualquier afirmación poética podría presentarse como verdad. Zambrano responde con la confesión como método, una palabra expuesta ante otros, que puede ser contradicha. Si eso alcanza para distinguir la razón poética de la mera opinión es una pregunta que su obra deja abierta, y que divide a sus lectores."},
   {q:"¿Qué diferencia hay entre la razón vital de Ortega y la razón poética de Zambrano?", p:"Ortega y Gasset, su maestro, sostuvo que la razón no debía ser pura ni abstracta, sino partir de la vida: la vida de cada uno, con su circunstancia, es la realidad radical. La razón vital es una razón al servicio de la vida, que la piensa desde adentro. Zambrano acepta ese punto de partida, pero cree que Ortega se quedó a mitad de camino: su razón seguía siendo una razón que entiende y organiza, que se apodera de la vida para comprenderla. La razón poética pide algo más: que la razón se deje transformar por lo que encuentra, que acepte lo que no entiende y que escuche antes de comprender. La diferencia se nota también en el estilo: Ortega es un ensayista brillante y seguro; Zambrano escribe desde la duda, la penumbra y la confesión. La relación entre ambos fue de afecto y de distancia: Ortega no apreció del todo el camino que ella tomó."},
   {q:"¿Cómo se relaciona el exilio de Zambrano con su filosofía?", p:"El exilio es para Zambrano más que un dato biográfico: es una condición desde la que se piensa. Salió de España en 1939, con la derrota de la República, y vivió fuera durante cuarenta y cinco años, en México, Cuba, Puerto Rico, Italia, Francia y Suiza. El exiliado ha perdido su lugar y no tiene otro: está fuera de la historia de los vencedores, y por eso puede ver lo que ellos no ven, la fragilidad de toda pertenencia y la verdad de los vencidos. Su crítica de la historia sacrificial y su defensa de la persona en Persona y democracia nacen de esa experiencia, igual que su reescritura de Antígona, encerrada entre la vida y la muerte. Para un lector colombiano, la reflexión de Zambrano dialoga con la experiencia del desplazamiento forzado: la pérdida del lugar no es solo una tragedia material, sino también una forma de conocer que la sociedad tiene la obligación de escuchar."},
   {q:"¿Qué entiende Zambrano por democracia, y en qué se diferencia del simple procedimiento electoral?", p:"En Persona y democracia, la democracia no es solo un conjunto de reglas para elegir gobernantes, sino una forma de sociedad en la que ser persona no solo está permitido, sino exigido. Su contraste es la historia sacrificial: durante siglos, las sociedades exigieron sacrificar a las personas en nombre de ídolos —el imperio, la nación, la raza, la revolución—. Una democracia verdadera es la que renuncia a esos sacrificios, y la que ve a cada uno como alguien concreto, con una intimidad que no se agota en su función ni en sus votos. Por eso critica tanto las dictaduras como las utopías que justificaron el terror en nombre del futuro. La objeción es que su concepto es más ético que político, y que no dice cómo organizar instituciones concretas. Ella respondería que ninguna institución funciona si la sociedad no ha renunciado antes a la lógica del sacrificio."},
   {q:"¿Puede una filosofía que valora lo sagrado y la poesía dialogar con una cultura científica y secularizada?", p:"Zambrano no defiende una religión ni pide volver a los dioses. Sostiene que lo sagrado es una dimensión de la experiencia humana —el fondo inquietante e inagotable de la realidad— que la modernidad creyó haber superado, y que, al negarlo, lo dejó reaparecer en formas degradadas: el culto al Estado, a la historia o al líder. Su tesis no es antiscientífica: no niega que la ciencia conozca, sino que la razón científica pueda dar cuenta de todo lo que importa. En ese sentido, su obra dialoga con críticas de la modernidad como las de Heidegger o la Escuela de Frankfurt, y con preguntas actuales sobre la necesidad de sentido en sociedades secularizadas. La objeción es que su lenguaje sobre lo sagrado es difícil de discutir racionalmente. Su aporte más defendible quizá sea el diagnóstico: que las ideologías políticas del siglo XX funcionaron como religiones sustitutas, que pidieron sacrificios humanos."}
 ],
 cadena:{ titulo:"¿Se puede pensar lo que no se puede demostrar?", intro:"Un razonamiento en ramas sobre la separación entre filosofía y poesía que Zambrano describe en Filosofía y poesía (1939). Las ramas recorren lo que la razón ganó y perdió con esa separación, la propuesta de la razón poética y la objeción de que todo puede volverse opinión.", inicio:"n1", nodos:{
   n1:{ pregunta:"Desde Platón, dice Zambrano, la filosofía decidió que solo era saber lo que se podía demostrar, y dejó a la poesía, que se quedaba con lo concreto y lo sensible, sin derecho a la verdad. ¿Fue una buena decisión?", opciones:[
     {texto:"Sí: sin demostración no hay conocimiento, solo opinión y sentimiento.", va:"n2a"},
     {texto:"No del todo: hay cosas que sabemos viviéndolas y que ningún argumento captura.", va:"n2b"} ]},
   n2a:{ pregunta:"Pensá en algo que sabés con certeza y no podrías demostrar: que alguien te quiere, que una situación es injusta antes de saber explicar por qué. ¿Eso no es saber?", opciones:[
     {texto:"No es saber: es una creencia que todavía no se ha justificado.", final:{tipo:"bien", texto:"Es la respuesta de la tradición racionalista, y tiene rigor: separa con claridad el conocimiento justificado de la convicción personal. Zambrano diría que ganás precisión, pero pagás un precio: una gran parte de lo que orienta la vida humana queda fuera de la filosofía, y la razón se vuelve incapaz de hablar de lo que más importa. Tu respuesta es coherente; tenés que decidir si ese precio vale la pena."}},
     {texto:"Es un saber de otro tipo: no demostrativo, pero no por eso falso.", va:"n3a"} ]},
   n3a:{ pregunta:"Si hay un saber no demostrativo, ¿cómo se distingue de una ocurrencia o de un prejuicio?", opciones:[
     {texto:"Por la confesión: una palabra que se expone ante otros, que puede ser corregida y que se hace cargo de su origen.", final:{tipo:"bien", texto:"Es la respuesta de Zambrano en La confesión: género literario y método. La confesión no es capricho, porque se expone a la mirada de otro y se responsabiliza de lo que dice. Ganás un criterio que no es la demostración pero tampoco es la arbitrariedad. La objeción es que el criterio es débil: un prejuicio también puede confesarse con sinceridad."}},
     {texto:"No se puede distinguir: por eso la filosofía hizo bien en exigir demostración.", final:{tipo:"bien", texto:"Es una conclusión honesta, y muchos críticos de Zambrano la comparten: sin un criterio público, la razón poética corre el riesgo de volverse una mística personal. Zambrano respondería que la exigencia de demostración también tiene sus excesos: dejó a la razón muda ante el sufrimiento, lo sagrado y la experiencia de los vencidos. Tu respuesta te obliga a decir qué hacés con eso."}} ]},
   n2b:{ pregunta:"Si hay cosas que solo se saben viviéndolas, ¿qué hace la filosofía con ellas?", opciones:[
     {texto:"Las abandona a la poesía y a la religión: no son asunto de la razón.", final:{tipo:"revisar", texto:"Es lo que Zambrano critica: la separación que dejó a la razón sin acceso a lo que más importa y a la poesía sin derecho a la verdad. Ella no quiere repartir los territorios, sino reconciliarlos. Volvé un paso y probá la otra respuesta."}},
     {texto:"Busca una razón distinta, que piense desde la experiencia y que sepa escuchar antes de definir.", va:"n3b"} ]},
   n3b:{ pregunta:"Esa razón distinta —la razón poética—, ¿en qué se diferencia de la razón vital de Ortega, maestro de Zambrano?", opciones:[
     {texto:"Ortega quería una razón al servicio de la vida; Zambrano quiere además que la razón se deje transformar por lo que encuentra, incluso por lo que no entiende.", final:{tipo:"bien", texto:"Es la diferencia central. La razón vital sigue siendo una razón que comprende y organiza la vida; la razón poética acepta ser tocada por lo que no se deja organizar. Por eso Zambrano escribe en penumbra, con imágenes de claros y auroras, y no con la seguridad de Ortega. Ortega no apreció del todo ese camino."}},
     {texto:"No se diferencian: son dos nombres para la misma idea.", final:{tipo:"revisar", texto:"Zambrano parte de Ortega, pero se aleja de él. La razón vital pide que la razón parta de la vida; la razón poética pide algo más radical: que la razón renuncie a apoderarse de lo que comprende. Volvé un paso y probá la otra respuesta."}} ]}
 }},
 reconstruccion:[
   { titulo:"La separación entre filosofía y poesía (Filosofía y poesía, 1939)",
     consigna:"Reconstruí el diagnóstico con que Zambrano explica la separación entre filosofía y poesía. Una pieza propone abandonar la razón, que no es lo que ella sostiene: dejala afuera y ordená el resto.",
     piezas:[
       {id:"f1", texto:"La filosofía nació de un querer poseer la unidad del ser por medio del concepto, un esfuerzo que tiene algo de violencia sobre las apariencias.", tipo:"premisa"},
       {id:"f2", texto:"La poesía, en cambio, se quedó fiel a lo que aparece: a lo concreto, lo múltiple y lo sensible, sin querer renunciar a nada.", tipo:"premisa"},
       {id:"f3", texto:"Desde Platón, la filosofía ganó el poder y declaró que solo era saber lo que se podía demostrar; la poesía quedó sin derecho a la verdad.", tipo:"premisa"},
       {id:"f4", texto:"Al separarse de la poesía, la razón perdió el contacto con la vida concreta de la que había salido.", tipo:"premisa"},
       {id:"f5", texto:"Por lo tanto, hace falta una razón poética: una razón que, sin renunciar a pensar, recupere lo que la filosofía dejó afuera.", tipo:"conclusion"},
       {id:"fx", texto:"Por lo tanto, hay que abandonar la filosofía y reemplazarla por la poesía.", tipo:"distractor"}
     ],
     ordenCorrecto:["f1","f2","f3","f4","f5"],
     explicacion:"Zambrano hace una genealogía (f1-f3) y un diagnóstico (f4) antes de proponer su salida (f5). El punto débil es f1: describir el origen de la filosofía como violencia y deseo de posesión es una interpretación muy discutible de Platón y de la tradición, y muchos filósofos dirían que la búsqueda de la unidad es un deseo de comprender, no de dominar. El argumento depende de que aceptemos esa lectura. La pieza sobrante invierte la propuesta: Zambrano no quiere reemplazar la filosofía por la poesía, sino reconciliarlas en una razón ampliada."},
   { titulo:"Persona y democracia (1958)",
     consigna:"Reconstruí el argumento con que Zambrano define la democracia a partir de la persona. Una pieza reduce la democracia a un procedimiento, que es lo que ella critica: dejala afuera.",
     piezas:[
       {id:"d1", texto:"La historia de Occidente ha sido, en buena parte, una historia sacrificial: se inmolaba a las personas en nombre de ídolos como el imperio, la nación o la revolución.", tipo:"premisa"},
       {id:"d2", texto:"Esos sacrificios fueron posibles porque se trató a los seres humanos como individuos intercambiables o como piezas de un proyecto, no como personas concretas.", tipo:"premisa"},
       {id:"d3", texto:"La persona es alguien concreto, con una intimidad y una historia que no se agotan en ninguna función ni en ningún proyecto colectivo.", tipo:"premisa"},
       {id:"d4", texto:"Por lo tanto, la democracia es la forma de sociedad en la que ser persona no solo está permitido, sino exigido: un orden que renuncia a pedir sacrificios humanos.", tipo:"conclusion"},
       {id:"dx", texto:"Por lo tanto, la democracia consiste en que la mayoría elija a sus gobernantes en elecciones periódicas.", tipo:"distractor"}
     ],
     ordenCorrecto:["d1","d2","d3","d4"],
     explicacion:"El argumento va de un diagnóstico histórico (d1-d2) a una definición ética de la democracia (d4), por medio de la distinción entre individuo y persona (d3). El punto débil es el paso de d3 a d4: la definición dice qué debería ser una democracia, pero no qué instituciones la harían posible, y por eso se le reprocha ser más ética que política. La pieza sobrante es la definición procedimental, que Zambrano no rechaza, pero considera insuficiente: una mayoría puede elegir democráticamente un orden sacrificial."}
 ],
 dilemas:[
   { titulo:"La memoria del barrio",
     intro:"Zambrano vivió casi medio siglo en el exilio y sostuvo que la experiencia de los desarraigados es una forma de saber que los demás tienen la obligación de escuchar, no como estadística, sino como palabra de una persona. Este caso lleva esa idea a un proyecto escolar en Ibagué, donde viven muchas familias desplazadas por el conflicto armado.",
     pasos:[
       { id:"p1", situacion:"Sos docente de ciencias sociales en un colegio de un barrio de Ibagué donde viven muchas familias desplazadas del sur del Tolima. Proponés un proyecto de memoria: los estudiantes recogerán las historias de sus familias. La coordinación sugiere presentarlo como un informe con cifras. ¿Qué forma le das?", opciones:[
         {texto:"Un informe con datos: cuántas familias, de dónde vienen, en qué años llegaron.", consecuencia:"Los datos son necesarios y dan una visión de conjunto. Pero Zambrano diría que la estadística convierte a las personas en individuos intercambiables, y que se pierde justamente lo que solo la persona puede decir: qué perdió, cómo lo vivió, qué sabe ahora.", va:"p2"},
         {texto:"Relatos en primera persona, recogidos con cuidado, con la voz de cada familia.", consecuencia:"Es la confesión como método: la palabra de alguien que se expone y se busca a sí mismo. Gana lo que la estadística pierde, pero exige un cuidado especial: no todos quieren contar, y contar puede doler.", va:"p2"},
         {texto:"Las dos cosas: un mapa con datos y, al lado, algunos relatos elegidos con las familias.", consecuencia:"Juntaste las dos razones que Zambrano quería reconciliar: la que da la visión de conjunto y la que escucha lo singular. La pregunta es quién decide qué relatos se cuentan.", va:"p2"} ]},
       { id:"p2", situacion:"Una madre acepta contar su historia, pero pide que no aparezca el nombre del grupo armado que la desplazó, por miedo. Un estudiante dice que, si no se nombra a los responsables, el proyecto es incompleto. ¿Qué hacés?", opciones:[
         {texto:"Respeto el pedido de la madre: su seguridad está antes que el proyecto.", consecuencia:"Pusiste a la persona por encima del proyecto, que es lo que Zambrano llamaría renunciar a la lógica del sacrificio. El estudiante tiene un punto, pero ninguna verdad histórica justifica exponer a quien la cuenta.", va:"p3"},
         {texto:"Le doy la razón al estudiante: sin responsables no hay memoria verdadera.", consecuencia:"La búsqueda de responsables es legítima, y es tarea de la justicia. Pero exponer a la madre para completar el proyecto sería sacrificarla a una idea de la verdad, que es justamente lo que Zambrano critica.", va:"p3"},
         {texto:"Respeto el pedido, y en clase discutimos por qué la madre tiene miedo de nombrarlo.", consecuencia:"Convertiste el silencio en una pregunta: el miedo también es un dato sobre el conflicto. Escuchar lo que no se puede decir es parte de la razón poética.", va:"p3"} ]},
       { id:"p3", situacion:"Al final, los estudiantes presentan el proyecto. Uno de ellos, cuya familia fue desplazada, dice que nunca había escuchado a su abuela contar esa historia. ¿Qué concluís?", opciones:[
         {texto:"«El proyecto sirvió para recoger información valiosa sobre el conflicto.»", consecuencia:"Es cierto, pero mirás el resultado como un informe. Zambrano diría que lo más importante no es la información recogida, sino que una historia que estaba callada encontró a alguien que la escuchara.", va:null},
         {texto:"«Lo más valioso fue que una abuela y su nieto se escucharon. Ese saber no estaba en ningún libro.»", consecuencia:"Es la idea de Zambrano: el saber de los desarraigados es una forma de conocimiento, y solo existe si alguien lo escucha como palabra de una persona.", va:null},
         {texto:"«Fue doloroso; quizá no deberíamos remover esas historias.»", consecuencia:"Es una preocupación seria: recordar puede doler. Pero Zambrano diría que el olvido impuesto es otra forma de exilio, y que la tarea es escuchar con cuidado, no dejar de escuchar.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar con este caso la diferencia entre tratar a alguien como individuo y como persona.",
       "Reconocí lo que se gana y lo que se pierde al contar una historia con datos o con relatos.",
       "Puse la seguridad y la voluntad de las personas por encima de los objetivos del proyecto.",
       "Pensé la confesión como una forma de conocimiento, con sus riesgos.",
       "Relacioné la experiencia del desplazamiento con la reflexión de Zambrano sobre el exilio.",
       "Escuché también lo que no se puede decir, como el miedo.",
       "Formulé la objeción más fuerte: que la razón poética puede volverse incapaz de distinguir la verdad histórica de la experiencia subjetiva."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.zambrano = { lecturas:[
 {titulo:"Filosofía y poesía: la separación y la razón poética", fuente:"Síntesis de trabajo sobre Filosofía y poesía (1939) y Persona y democracia (1958); para la vida y la obra, Wikipedia en español", url:"https://es.wikipedia.org/wiki/Mar%C3%ADa_Zambrano",
  extracto:`María Zambrano publicó Filosofía y poesía en 1939, en Morelia, México, pocos meses después de haber cruzado la frontera francesa con miles de republicanos derrotados en la guerra civil española. El libro plantea el problema que la acompañará toda su vida: por qué la filosofía y la poesía, que nacieron juntas, se separaron, y qué perdió la cultura occidental con esa separación.

Su diagnóstico parte de Platón. La filosofía, dice, nació de un deseo de poseer la verdad entera, la unidad de lo que es, por medio del concepto. Ese deseo tiene algo de esfuerzo violento sobre las apariencias: para llegar a lo que no cambia, el filósofo tiene que renunciar a lo que cambia, a lo sensible, a lo múltiple. El poeta, en cambio, no renuncia a nada: se queda fiel a lo que aparece, a lo concreto, a lo que no se deja reducir a una definición.

En la República, Platón expulsa a los poetas de la ciudad ideal. Para Zambrano, ese gesto no fue una anécdota: definió una cultura entera, que valoró la abstracción, el dominio y la demostración, y miró con sospecha todo lo que se sabe viviendo. La razón ganó el poder, pero perdió el contacto con la vida de la que había salido.

Zambrano no propone elegir a la poesía contra la filosofía. Propone una razón poética: una razón que no renuncie a pensar, pero que sepa escuchar antes de definir, que parta de la experiencia y que acepte ser transformada por lo que encuentra.

Años después, en Persona y democracia, lleva esta idea a la política. La historia de Occidente, sostiene, ha sido en buena parte sacrificial: se inmolaba a las personas en nombre de ídolos. La democracia es la sociedad en la que ser persona no solo está permitido, sino exigido.`,
  comentario:"Fijate en la estructura: primero una genealogía (cómo se separaron filosofía y poesía), después un diagnóstico (qué se perdió) y al final una propuesta (la razón poética). Leé con espíritu crítico la descripción de Platón: es una interpretación fuerte, que muchos discutirían. Y fijate en el contexto: Zambrano escribe en el primer año de un exilio que duraría cuarenta y cinco años."}
], preguntasLectura:[
 {q:"Según Zambrano, ¿de qué deseo nació la filosofía?", opciones:["Del deseo de entretener a la ciudad","Del deseo de poseer la verdad entera, la unidad de lo que es, por medio del concepto","Del deseo de imitar a la poesía","Del deseo de obedecer a los dioses"], r:"Del deseo de poseer la verdad entera, la unidad de lo que es, por medio del concepto", why:"Para llegar a lo que no cambia, el filósofo renuncia a lo sensible y múltiple."},
 {q:"¿Qué propone Zambrano frente a la separación entre filosofía y poesía?", opciones:["Abandonar la filosofía y quedarse con la poesía","Una razón poética, que piense sin dejar de escuchar lo que la razón discursiva dejó afuera","Volver a la religión","Prohibir la poesía, como Platón"], r:"Una razón poética, que piense sin dejar de escuchar lo que la razón discursiva dejó afuera", why:"No se trata de elegir entre filosofía y poesía, sino de reconciliarlas."},
 {q:"¿Cómo define Zambrano la democracia en Persona y democracia?", opciones:["Como el gobierno de la mayoría","Como la sociedad en la que ser persona no solo está permitido, sino exigido","Como un sistema económico","Como la ausencia de leyes"], r:"Como la sociedad en la que ser persona no solo está permitido, sino exigido", why:"Frente a la historia sacrificial, la democracia renuncia a sacrificar a las personas en nombre de ídolos."}
]};
