/* Ágora · banco del examen final integrador (todas las fichas).
   - seleccion: situación + pregunta + 4 opciones; `correcta` es el índice de la opción correcta.
     La app mezcla las opciones, así que la `explicacion` nombra cada opción por su contenido, nunca por su posición.
   - vf: afirmaciones de verdadero o falso, inequívocas para quien conoce las fichas.
   - emparejar: ideas cortas con la ficha (id) a la que pertenecen; cada intento arma una ronda de 6
     ideas de autores distintos y de al menos tres tradiciones.
   `fichas` lista las fichas que cubre cada pregunta (verificar.js comprueba que existan). */
const EXAMEN_FINAL = {
 seleccion:[
  { fichas:["descartes"],
    situacion:"Un programador sostiene que podríamos vivir dentro de una simulación informática indistinguible de la realidad, y que nada de lo que percibimos garantiza lo contrario.",
    pregunta:"Según el razonamiento de Descartes en la Meditación segunda, ¿qué quedaría en pie aunque eso fuera cierto?",
    opciones:["La existencia de quien piensa, mientras piensa, aunque esté siendo engañado.","Las verdades matemáticas, porque no dependen de los sentidos.","La existencia del propio cuerpo, porque se lo siente desde adentro.","Nada: la duda radical, una vez planteada, no tiene salida."],
    correcta:0,
    explicacion:"Si me engañan, yo existo: «yo soy, yo existo» es verdadero cada vez que lo pienso. Las matemáticas no quedan en pie: en la Meditación primera, el genio maligno podría engañarme incluso al sumar. El cuerpo tampoco: es de lo primero que se duda. Y la idea de que la duda no tiene salida es la del escéptico, justamente lo que Descartes quiere superar." },
  { fichas:["kant"],
    situacion:"Una empresa ofrece un bono a los empleados que donen a una fundación. Laura dona solo para recibir el bono. Pedro dona porque cree que es su deber ayudar, y el bono le resulta indiferente.",
    pregunta:"¿Qué evaluación haría Kant de las dos donaciones?",
    opciones:["Las dos valen igual, porque producen la misma consecuencia: más dinero para la fundación.","Solo la donación de Pedro tiene valor moral, porque se hace por deber y no solo conforme al deber.","La de Laura es mejor, porque es honesta sobre sus verdaderos motivos.","Ninguna tiene valor moral, porque toda acción busca en el fondo un beneficio propio."],
    correcta:1,
    explicacion:"Kant distingue actuar conforme al deber de actuar por deber: solo lo segundo tiene valor moral (Fundamentación, primera sección). Evaluar por las consecuencias es la lógica utilitarista que Kant rechaza como criterio moral. La honestidad sobre los motivos no vuelve moral una acción interesada. Y la tesis de que todos actuamos por interés es el egoísmo psicológico, que Kant no acepta." },
  { fichas:["hegel"],
    situacion:"En una empresa familiar, el dueño vive del trabajo de sus empleados y ya no sabe hacer nada del oficio. Los empleados, en cambio, dominan cada etapa de la producción.",
    pregunta:"¿Qué lectura de la situación corresponde a la dialéctica del amo y el esclavo de la Fenomenología del espíritu?",
    opciones:["La relación es natural: hay quienes nacen para mandar y quienes nacen para obedecer.","Los empleados solo serán libres si abandonan todo trabajo.","El amo depende del reconocimiento y del trabajo del siervo, y es el siervo quien, trabajando, transforma el mundo y llega a la autoconciencia.","La desigualdad desaparece en cuanto ambos se declaran iguales ante la ley, sin que haga falta ningún proceso."],
    correcta:2,
    explicacion:"En Hegel el amo queda dependiente: necesita el reconocimiento de alguien a quien no reconoce, y vive del trabajo ajeno, mientras el siervo, trabajando, se forma a sí mismo y forma el mundo. La idea de que unos nacen para mandar es la esclavitud natural de la Política de Aristóteles. Abandonar el trabajo invierte la tesis, porque en Hegel el trabajo es lo que libera. Y la igualdad declarada sin proceso ignora que, para Hegel, el reconocimiento se conquista históricamente." },
  { fichas:["nietzsche"],
    situacion:"Un estudiante afirma: «La humildad siempre fue una virtud. Está en la naturaleza humana».",
    pregunta:"¿Qué haría Nietzsche con esa afirmación?",
    opciones:["Reconstruiría su genealogía: mostraría que la humildad pasó a ser virtud por una inversión de valores nacida del resentimiento de los débiles.","La aceptaría, porque las virtudes cristianas expresan la naturaleza humana universal.","La demostraría a priori, a partir de la estructura de la razón práctica.","La defendería por su utilidad: la humildad conviene a la mayoría, según un cálculo de consecuencias."],
    correcta:0,
    explicacion:"La genealogía pregunta de dónde vienen los valores, y en La genealogía de la moral la moral de esclavos invierte la valoración aristocrática: lo débil, lo humilde y lo sufrido pasan a ser «buenos». Aceptar las virtudes cristianas como naturaleza humana es lo que Nietzsche ataca. La demostración a priori es el camino de Kant. Y el cálculo de utilidad es el utilitarismo, que Nietzsche desprecia." },
  { fichas:["heidegger"],
    situacion:"Julián llena su agenda para no quedarse nunca a solas. Opina lo que «se dice», hace lo que «se hace» y, cuando alguien menciona la muerte, responde: «Bueno, algún día todos nos vamos a morir».",
    pregunta:"¿Qué concepto de Ser y tiempo describe mejor esta manera de vivir?",
    opciones:["La akrasia: sabe lo que debe hacer y no lo hace.","La existencia impropia, absorbida en el «uno» (das Man), que encubre la muerte como algo impersonal.","La superposición: atribuye al yo lo que pertenece al cuerpo.","La experiencia pura, anterior a la división entre sujeto y objeto."],
    correcta:1,
    explicacion:"El «uno» impersonal —lo que se dice, lo que se hace— es la forma cotidiana de la existencia impropia, y el «se muere» convierte la muerte en un suceso de nadie. La akrasia es de Aristóteles, la superposición de Shankara y la experiencia pura de Nishida: conceptos reales, pero de otros problemas." },
  { fichas:["wittgenstein"],
    situacion:"Dos amigos discuten si el ajedrez por internet es «realmente» un juego. Para resolverlo, intentan encontrar la característica que comparten todos los juegos.",
    pregunta:"¿Qué les diría el segundo Wittgenstein, el de las Investigaciones filosóficas?",
    opciones:["Que deben encontrar la Forma del Juego, de la cual participan todos los juegos particulares.","Que la pregunta es un sinsentido y que, sobre lo que no se puede hablar, hay que callar.","Que no hay una característica común a todos los juegos, sino parecidos de familia, y que usar bien la palabra no exige una definición esencial.","Que un juego es lo que produce diversión, y que basta con medir ese efecto práctico."],
    correcta:2,
    explicacion:"Los parecidos de familia son el ejemplo central de las Investigaciones (§66-67): los juegos se parecen entre sí como los miembros de una familia, sin una esencia común. La Forma del Juego es el modelo de Platón. El «hay que callar» es la frase final del Tractatus, el libro que el segundo Wittgenstein discute. Y definir el juego por un único efecto es buscar otra vez una esencia." },
  { fichas:["confucio","laozi"],
    situacion:"Un alcalde recién elegido anuncia multas muy altas para reducir la corrupción de los funcionarios municipales.",
    pregunta:"¿Qué objetaría Confucio a esa estrategia?",
    opciones:["Que si se gobierna con leyes y castigos el pueblo evitará la falta, pero no tendrá vergüenza; si se gobierna con la virtud y los ritos, tendrá vergüenza y se corregirá.","Que el sabio gobierna sin actuar: lo mejor es no intervenir y dejar que las cosas sigan su curso.","Que las multas deben ser todavía más altas, porque el miedo es el único motor fiable de la conducta.","Que la corrupción es una ilusión que desaparece cuando se comprende que el yo no tiene naturaleza propia."],
    correcta:0,
    explicacion:"Es casi literal de las Analectas (2.3): el castigo produce obediencia sin vergüenza; la virtud y los ritos (lǐ) producen un pueblo que se corrige. No intervenir es el wú wéi de Laozi, que Confucio no comparte. La confianza en el miedo es la de la escuela legista, adversaria de los confucianos. Y disolver la corrupción en la vacuidad del yo confunde a Confucio con un budista." },
  { fichas:["laozi","wangyangming"],
    situacion:"La nueva directora de un colegio interviene en todo: crea reglamentos para cada detalle, castiga cada falta y revisa cada planeación. Al final del año, el clima escolar empeoró.",
    pregunta:"¿Qué lectura haría Laozi?",
    opciones:["Que le faltó pulirse en los asuntos: sus reglas eran correctas, pero no las practicó con la suficiente constancia.","Que cuantas más prohibiciones hay, más se empobrece el pueblo; el buen gobernante actúa sin forzar (wú wéi) y deja que las cosas se ordenen.","Que debió rectificar los nombres, para que cada cargo correspondiera a su función.","Que debió fundar cada regla en el imperativo categórico, para que valiera universalmente."],
    correcta:1,
    explicacion:"El Daodejing (capítulo 57) dice que cuantas más prohibiciones hay, más pobre es el pueblo, y que el sabio no actúa y el pueblo se transforma solo. Pulirse en los asuntos es Wang Yangming. La rectificación de los nombres es Confucio. El imperativo categórico es Kant." },
  { fichas:["zhuangzi"],
    situacion:"Dos estudiantes discuten durante horas quién tiene razón. Le piden a un tercero que decida, pero este responde que si coincide con uno ya no es imparcial, y si no coincide con ninguno no puede decidir.",
    pregunta:"¿De qué autor es este argumento, y qué busca mostrar?",
    opciones:["De Platón: que solo quien contempló las Formas puede juzgar con imparcialidad.","De Peirce: que la verdad es aquello en lo que convergerá la comunidad de investigadores.","De Zhuangzi: que no hay un juez fuera de toda perspectiva, porque cada uno juzga desde su propio «esto».","De Kant: que las disputas se resuelven aplicando las categorías del entendimiento."],
    correcta:2,
    explicacion:"El argumento del juez imparcial imposible está en el capítulo 2 del Zhuangzi (Qiwulun): cada cosa es «esto» desde sí misma y «aquello» desde otra. Platón sí cree en un saber que permite juzgar, el de las Formas. Peirce cree en la convergencia a largo plazo. Y Kant no resuelve disputas de opinión con las categorías." },
  { fichas:["nagarjuna"],
    situacion:"Un estudiante concluye después de una clase de budismo: «Si nada tiene esencia, nada existe, y entonces da igual lo que hagamos».",
    pregunta:"¿Cómo respondería Nagarjuna?",
    opciones:["Tiene razón: la vacuidad es la nada absoluta, y el sabio se retira del mundo.","Confunde vacuidad con inexistencia: las cosas surgen en dependencia, y sus efectos son reales en la verdad convencional; por eso las acciones importan.","Lo único real es Brahman, y el mundo es apariencia; pero mientras se vive en el mundo hay que cumplir los deberes de la casta.","Hay que suspender el juicio sobre todo, incluso sobre si da igual o no."],
    correcta:1,
    explicacion:"Nagarjuna enfrenta esta objeción en el capítulo 24: si las cosas tuvieran esencia, no podrían cambiar, y el sufrimiento no podría cesar. La vacuidad no es inexistencia, sino originación dependiente. La nada absoluta como fondo es una lectura que él rechaza. Brahman como única realidad es Shankara. Y la suspensión total del juicio es el escepticismo griego, no el Madhyamaka." },
  { fichas:["shankara"],
    situacion:"De noche, una mujer ve una serpiente enrollada en el patio y grita. Cuando prende la linterna, ve que era una manguera.",
    pregunta:"¿Para explicar qué usa Shankara un ejemplo como este?",
    opciones:["Que nada surge con naturaleza propia, ni de sí, ni de otro, ni sin causa.","Que la percepción nunca da conocimiento, y que solo la razón accede a las Formas.","La superposición: el error no crea nada, sino que encubre lo que ya está; así, el mundo múltiple es Brahman mal visto.","Que una creencia se fija cuando una duda genuina se resuelve con un método."],
    correcta:2,
    explicacion:"La cuerda vista como serpiente es el ejemplo canónico de la superposición (adhyāsa): al ver bien, la serpiente desaparece y la cuerda queda; del mismo modo, al conocer, el mundo múltiple se revela como Brahman. Las cuatro maneras de no surgir son Nagarjuna. La razón y las Formas son Platón. La fijación de la creencia es Peirce." },
  { fichas:["dogen"],
    situacion:"Un corredor entrena solo pensando en la medalla. Cuando pierde una competencia importante, deja de correr: dice que ya no tiene sentido.",
    pregunta:"¿Qué diagnóstico haría Dōgen de esa manera de practicar?",
    opciones:["Trata la práctica como un medio para un premio futuro; para Dōgen práctica y realización son una sola cosa, y la práctica no se sostiene en la espera de un resultado.","Le faltó estudiar en los libros el principio de la carrera antes de correr.","Debe someter su deseo de ganar a una máxima que pueda querer como ley universal.","Su error fue no tener una duda genuina que lo obligara a investigar."],
    correcta:0,
    explicacion:"Dōgen critica la práctica que espera un premio (taigo): para él, sentarse en zazen ya es la realización (shushō-ittō), y la práctica no se abandona cuando llega o no llega el resultado. Estudiar el principio en los libros es la imagen que Wang Yangming critica en Zhu Xi. La máxima universal es Kant. La duda genuina es Peirce." },
  { fichas:["nishida"],
    situacion:"Una pianista cuenta que, en los mejores momentos de un concierto, desaparecen ella y el piano: solo hay música. Recién al terminar piensa: «Toqué bien».",
    pregunta:"¿Qué concepto de Nishida describe ese momento?",
    opciones:["La superposición: la pianista confundió su yo con el instrumento.","La experiencia pura: anterior a la división entre sujeto y objeto, que aparece después, con la reflexión.","La existencia impropia: se perdió en la música como se pierde uno en lo que «se hace».","El cogito: la certeza de que existe quien toca."],
    correcta:1,
    explicacion:"La experiencia pura (junsui keiken) es el instante en que todavía no se separan el que experimenta y lo experimentado; el «toqué bien» llega después, con la reflexión. La superposición es Shankara y designa un error, no una plenitud. La existencia impropia es Heidegger. Y el cogito es justamente un acto reflexivo, lo que Nishida pone en segundo lugar." },
  { fichas:["wangyangming"],
    situacion:"Un concejal repite en cada discurso que la corrupción es el peor mal del país, y es descubierto recibiendo sobornos.",
    pregunta:"¿Qué diría Wang Yangming sobre lo que ese concejal «sabía»?",
    opciones:["Que lo sabía, pero le faltó fuerza de voluntad para actuar en consecuencia.","Que no lo sabía de verdad: un saber que no se vuelve acción es un saber de palabras, separado de la acción por el deseo egoísta.","Que nadie puede saber qué es la corrupción, porque toda definición depende de la perspectiva.","Que su saber era verdadero, porque se dejaba verificar en sus discursos."],
    correcta:1,
    explicacion:"Para Wang conocer y actuar son originalmente uno (zhīxíng héyī): quien sabe y no hace todavía no sabe. La explicación por la debilidad de voluntad es la que Wang rechaza, y se parece a la akrasia de Aristóteles. El perspectivismo es una lectura de Zhuangzi. Y la verificación como criterio de verdad es James." },
  { fichas:["peirce"],
    situacion:"Una bióloga nota que las abejas desaparecieron de una zona del Tolima. Antes de tener pruebas, propone que la causa es un pesticida que empezó a usarse ese año, y diseña muestreos para ponerlo a prueba.",
    pregunta:"¿Qué tipo de inferencia describió Peirce con ese primer paso?",
    opciones:["La deducción: extraer lo que ya está contenido en las premisas.","La inducción: generalizar a partir de muchos casos observados.","La abducción: proponer la hipótesis que haría esperable un hecho sorprendente, para ponerla a prueba.","El método de autoridad: aceptar la explicación de un experto reconocido."],
    correcta:2,
    explicacion:"La abducción va de un hecho sorprendente a una hipótesis que lo volvería esperable, y su conclusión es una sospecha que hay que poner a prueba. La deducción vendría después, al sacar consecuencias de la hipótesis; la inducción, al comprobarlas en los muestreos. El método de autoridad es uno de los cuatro métodos de fijar la creencia que Peirce critica." },
  { fichas:["james"],
    situacion:"Ana tiene que decidir si confía en un compañero nuevo de equipo antes de conocerlo bien. Si no confía, el equipo no va a funcionar. No hay manera de reunir pruebas antes de decidir.",
    pregunta:"¿Qué posición corresponde a William James en «La voluntad de creer»?",
    opciones:["Es incorrecto, siempre y en todas partes, creer algo con evidencia insuficiente: Ana debe suspender el juicio.","Es una opción viva, forzosa y trascendental que la evidencia no puede decidir: es legítimo que la confianza decida, y la confianza misma puede ayudar a crear el hecho.","Ana debe creer lo que la haga sentir mejor, porque lo verdadero es lo agradable.","Ana debe calcular qué decisión produce la mayor felicidad para el mayor número."],
    correcta:1,
    explicacion:"James defiende el derecho a creer cuando la opción es genuina y la evidencia no puede decidirla, y da precisamente el ejemplo de la confianza que crea el hecho. Suspender el juicio siempre es la regla de Clifford, a la que James responde. Creer lo agradable es la caricatura de Russell, que James rechazó. Y el cálculo de felicidad es el utilitarismo." },
  { fichas:["dewey"],
    situacion:"En el colegio A, los estudiantes memorizan los artículos de la Constitución para un examen. En el colegio B, investigan por qué el parque del barrio está abandonado, leen las normas sobre espacio público y presentan una propuesta a la junta de acción comunal.",
    pregunta:"¿Cuál sería la evaluación de Dewey?",
    opciones:["El colegio A hace lo correcto: la educación debe transmitir primero los contenidos y la experiencia vendrá después.","Los dos son equivalentes, porque lo que importa es que los estudiantes estén activos.","El colegio B tiene más posibilidades de ser educativo, siempre que la experiencia tenga continuidad e interacción, es decir, que abra experiencias posteriores y responda a las condiciones reales.","Ninguno es educativo, porque la educación debe buscar las verdades eternas, no los problemas del barrio."],
    correcta:2,
    explicacion:"Para Dewey se aprende reconstruyendo experiencias reales, y el criterio de una experiencia educativa son la continuidad y la interacción (Experiencia y educación). Transmitir contenidos para un uso futuro es el modelo tradicional que critica. Estar activo no basta: hay experiencias agradables y deseducativas. Y las verdades eternas son el ideal contemplativo que Dewey combate." },
  { fichas:["vasconcelos"],
    situacion:"Un ensayo de 1925 celebra el mestizaje latinoamericano contra las teorías que lo consideraban una degeneración, pero anticipa que, en el período estético, «por extinción voluntaria, las estirpes más feas irán cediendo el paso a las más hermosas».",
    pregunta:"¿Cuál es la evaluación más precisa de La raza cósmica?",
    opciones:["Es un texto plenamente antirracista; la frase citada es un adorno retórico sin consecuencias en el argumento.","Es una defensa de la pureza racial europea frente a la mezcla.","Invierte la jerarquía racial que condenaba el mestizaje, pero conserva una escala racial y un programa de selección estética.","Es una crítica del concepto de raza como construcción social sin base biológica."],
    correcta:2,
    explicacion:"Vasconcelos valora la mezcla contra el racismo europeo, pero su mecanismo —la ley del gusto— supone que unos tipos son superiores y otros deben desaparecer, y nombra a las personas negras como ejemplo de lo que podría «redimirse». La frase no es un adorno: es el mecanismo. No defiende la pureza europea: celebra la mezcla. Y no critica la idea de raza: la usa." },
  { fichas:["zea"],
    situacion:"Un profesor afirma: «En América Latina no hay filosofía: solo comentamos a autores europeos».",
    pregunta:"¿Cuál sería la respuesta de Leopoldo Zea?",
    opciones:["Que toda filosofía, también la europea, nace de una circunstancia, y que si pensamos con rigor nuestros problemas haremos filosofía sin más, sin adjetivos.","Que hay que rechazar toda herencia europea y volver a las filosofías anteriores a la conquista.","Que el profesor tiene razón: mientras haya dependencia económica, solo puede haber imitación.","Que la filosofía es griega por esencia, y que fuera de Europa solo hay sabiduría o religión."],
    correcta:0,
    explicacion:"Es la tesis de La filosofía americana como filosofía sin más (1969): la pregunta por si existe una filosofía latinoamericana presupone un modelo europeo que también nació de su circunstancia. Rechazar lo europeo es el extremo que Zea considera estéril. Que solo haya imitación mientras dure la dependencia es la posición de Salazar Bondy, a quien Zea responde. Y la filosofía griega por esencia es la tesis que Zea discute." },
  { fichas:["dussel","descartes"],
    situacion:"Un manual escolar afirma: «La modernidad nace en el siglo XVII, con Descartes y la ciencia moderna».",
    pregunta:"¿Qué objetaría Enrique Dussel?",
    opciones:["Que la modernidad nace en 1492, con la conquista de América, y que antes del «yo pienso» estuvo el «yo conquisto».","Que la modernidad nace con la Revolución francesa, cuando se proclaman los derechos del hombre.","Que la modernidad nunca existió: es una invención de los historiadores del siglo XX.","Que el manual tiene razón, y que América entró en la historia universal recién con la independencia."],
    correcta:0,
    explicacion:"Para Dussel, Europa se constituye como centro del mundo al conquistar su periferia, y el «ego conquiro» precede al «ego cogito» (1492: el encubrimiento del Otro). La Revolución francesa es otra fecha posible en los manuales, no la de Dussel. Negar que haya existido la modernidad no es su posición: él la critica, no la niega. Y la última opción es la tesis que discute." },
  { fichas:["rorty"],
    situacion:"Una fundación produce documentales con historias de familias migrantes, y se nota que los barrios donde se proyectan se vuelven menos hostiles hacia los recién llegados.",
    pregunta:"¿Cómo interpretaría Richard Rorty este efecto?",
    opciones:["Como prueba de que los seres humanos comparten una naturaleza racional que funda los derechos humanos.","Como educación sentimental: las historias amplían el «nosotros», y el progreso moral se hace más con relatos que con fundamentos.","Como una manipulación ilegítima, porque solo los argumentos racionales pueden cambiar las creencias morales.","Como una consecuencia de que los documentales copian fielmente la realidad, como un espejo."],
    correcta:1,
    explicacion:"En «Derechos humanos, racionalidad y sentimentalismo», Rorty sostiene que el progreso moral consiste en ampliar el círculo de quienes nos importan, y que lo logran sobre todo las historias. La naturaleza racional que funda derechos es el fundacionalismo que rechaza. Exigir solo argumentos es la posición que critica. Y el espejo es la metáfora que dedicó su obra a desmontar." },
  { fichas:["west"],
    situacion:"En un barrio con altas tasas de deserción escolar, un líder comunitario dice: «No sé si esto va a cambiar, pero vamos a seguir trabajando como si pudiera, y nadie va a quedar solo».",
    pregunta:"¿Qué actitud describe Cornel West con esas palabras?",
    opciones:["El optimismo: la expectativa, basada en la evidencia, de que las cosas van a mejorar.","El nihilismo: la experiencia vivida de la falta de sentido y de esperanza.","La esperanza trágica: mirar el mal de frente sin dejar que tenga la última palabra, sosteniéndose en la acción y no en la evidencia.","El fundamentalismo de mercado: la confianza en que el mercado resolverá el problema."],
    correcta:2,
    explicacion:"West distingue la esperanza del optimismo: el optimista espera porque la evidencia lo justifica; quien tiene esperanza actúa aunque no lo justifique. El nihilismo es lo contrario de la frase del líder. Y el fundamentalismo de mercado es lo que West critica." },
  { fichas:["aristoteles"],
    situacion:"Un estudiante quiere ser valiente. Lee todo lo que encuentra sobre la valentía, pero evita cualquier situación difícil.",
    pregunta:"¿Qué le diría Aristóteles?",
    opciones:["Que la virtud se adquiere por hábito: nos hacemos valientes haciendo actos valientes, y la valentía es un término medio entre la cobardía y la temeridad.","Que ya es valiente, porque conocer el bien es suficiente para practicarlo.","Que debe recordar la Forma de la Valentía, que su alma contempló antes de nacer.","Que la valentía es una máscara de la voluntad de poder, y que debe abandonarla."],
    correcta:0,
    explicacion:"Para Aristóteles, las virtudes éticas se adquieren por la práctica (Ética nicomaquea II, 1), y cada una es un término medio entre dos extremos. Que conocer el bien baste para practicarlo es la tesis socrática que Aristóteles discute. El recuerdo de la Forma es Platón. Y la sospecha sobre las virtudes es Nietzsche." },
  { fichas:["platon"],
    situacion:"Un arquitecto observa que ninguna casa real es perfecta, pero que todos los arquitectos juzgan los planos reales comparándolos con una idea de casa perfecta que nadie vio construida.",
    pregunta:"¿Qué filósofo encontraría en este hecho un apoyo para su tesis de que lo que mejor se conoce no está en lo sensible?",
    opciones:["Aristóteles, para quien la forma está en las cosas mismas y se abstrae de la experiencia.","Platón, para quien el verdadero objeto del saber son las Formas, que lo sensible solo imita imperfectamente.","Dewey, para quien las ideas son instrumentos que se evalúan por sus consecuencias prácticas.","Nagarjuna, para quien ni la casa ni la idea de casa tienen naturaleza propia."],
    correcta:1,
    explicacion:"Juzgar lo sensible por un modelo perfecto que no está en lo sensible es el razonamiento que Platón usa con lo Igual en el Fedón. Aristóteles explicaría el mismo hecho por abstracción, sin un mundo separado. Dewey vería la idea de casa perfecta como un instrumento, no como un objeto de saber. Nagarjuna disolvería las dos, la casa y la idea." },
  { fichas:["falacias"],
    situacion:"En un debate electoral, un candidato dice: «No hay que tomar en serio la propuesta de bajar los peajes del exalcalde: hace dos años lo multaron por parquear mal».",
    pregunta:"¿Qué falacia comete?",
    opciones:["Hombre de paja: deforma la propuesta del adversario para refutarla más fácilmente.","Ad hominem: ataca a la persona en lugar de responder a su argumento.","Petición de principio: supone en las premisas lo que quiere demostrar.","Falsa dicotomía: presenta solo dos opciones cuando hay más."],
    correcta:1,
    explicacion:"La multa por parqueo no dice nada sobre si conviene bajar los peajes: es un ataque a la persona. No hay hombre de paja, porque no se deforma la propuesta: directamente no se la discute. No hay petición de principio ni falsa dicotomía, porque no hay ni una premisa circular ni dos opciones presentadas como únicas." },
  { fichas:["falacias"],
    situacion:"Desde que el colegio instaló cámaras en los salones, el promedio de notas subió. El rector concluye: «Las cámaras mejoraron el rendimiento académico».",
    pregunta:"¿Qué error comete el rector?",
    opciones:["Apelación a la ignorancia: nadie demostró lo contrario.","Pendiente resbaladiza: anticipa una cadena de consecuencias inevitables.","Confundir correlación con causación: que una cosa venga después de otra no prueba que la cause.","Falacia del punto medio: toma la posición intermedia entre dos extremos."],
    correcta:2,
    explicacion:"Es un post hoc: el aumento de notas pudo deberse a otros cambios del mismo año —nuevos docentes, otro sistema de evaluación, otra cohorte—. No apela a la falta de pruebas, no anticipa una cadena de consecuencias y no busca un punto medio." },
  { fichas:["nagarjuna","nishida","descartes","shankara"],
    situacion:"En un seminario se comparan cuatro filósofos a partir de una pregunta: ¿hay un yo que exista antes y por debajo de la experiencia?",
    pregunta:"¿Qué par de filósofos coincide en negar que el yo sea una sustancia previa a la experiencia?",
    opciones:["Descartes y Shankara.","Nagarjuna y Nishida.","Descartes y Platón.","Shankara y Platón."],
    correcta:1,
    explicacion:"Nagarjuna sostiene que el yo es una designación dependiente, sin naturaleza propia, y Nishida que el individuo aparece dentro de la experiencia, no antes. Descartes afirma una sustancia pensante. Shankara afirma el atman, idéntico a Brahman, aunque no sea el yo individual. Platón afirma un alma que existe antes del cuerpo." },
  { fichas:["heidegger","zhuangzi","nietzsche","dogen"],
    situacion:"Una estudiante escribe en un ensayo: «Hay que aceptar la muerte de los seres queridos como un cambio más de la naturaleza, igual que el paso de las estaciones».",
    pregunta:"¿Con qué filósofo y con qué episodio se relaciona mejor esa idea?",
    opciones:["Con Heidegger, que describe el ser-para-la-muerte en la muerte de su esposa.","Con Nietzsche, que canta golpeando un cuenco cuando muere su madre.","Con Zhuangzi, que después del dolor canta golpeando un cuenco cuando muere su esposa, porque entiende la muerte como una transformación.","Con Dōgen, que llora durante años la muerte de su maestro Rujing."],
    correcta:2,
    explicacion:"El episodio está en el capítulo 18 del Zhuangzi: Hui Shi lo encuentra cantando y golpeando un cuenco tras la muerte de su esposa, y Zhuangzi le explica que la vida y la muerte se suceden como las estaciones. Las otras tres opciones atribuyen episodios que no existen: Heidegger trata la muerte como posibilidad propia, no a partir de un duelo; Nietzsche no tiene ese episodio; y Dōgen piensa la vida y la muerte como posiciones completas en el tiempo." },
  { fichas:["arendt"],
    situacion:"En el juicio por un crimen masivo, el acusado repite que solo cumplía órdenes, que habla con el lenguaje de los reglamentos y que, si no lo hubiera hecho él, lo habría hecho otro.",
    pregunta:"¿Qué respondería Hannah Arendt a esa defensa?",
    opciones:["Que tiene razón: si el sistema era criminal, el responsable es el sistema y no sus piezas.","Que en un tribunal se juzga a una persona, no a un sistema, y que obedecer, en un adulto, es apoyar.","Que la culpa es de la naturaleza humana, que es mala por esencia.","Que no se puede juzgar a nadie, porque cada uno actúa según su perspectiva."],
    correcta:1,
    explicacion:"Arendt rechaza la teoría del engranaje: en el tribunal se juzga a un hombre por lo que hizo, y que otro lo hubiera hecho no cambia que lo hizo él; en política, obedecer es apoyar. Responsabilizar solo al sistema es la defensa que ella discute. Atribuirlo a una maldad esencial contradice la banalidad del mal. Y el perspectivismo que impide juzgar no es su posición: ella defendió el juicio." },
  { fichas:["beauvoir"],
    situacion:"Una estudiante dice: «Mi mamá deja de trabajar cada vez que alguien en la familia se enferma, pero lo hace porque quiere, nadie la obliga».",
    pregunta:"¿Qué análisis haría Simone de Beauvoir?",
    opciones:["Que la madre actúa por naturaleza: el cuidado es una inclinación femenina biológica.","Que la madre es libre, pero elige dentro de una situación que no eligió y que le enseñó desde niña que cuidar es lo suyo.","Que la madre no tiene ninguna libertad: la sociedad decide todo por ella.","Que el cuidado no tiene importancia y que la madre debería dedicarse solo a su carrera."],
    correcta:1,
    explicacion:"Para Beauvoir, la libertad siempre está en situación: la madre elige, pero dentro de un campo de posibilidades que su educación y su sociedad formaron. Atribuirlo a la naturaleza es lo que «no se nace mujer» discute. Negar toda libertad es un determinismo que Beauvoir rechaza. Y despreciar el cuidado no es su tesis: critica que sea un destino impuesto, no que exista." },
  { fichas:["zambrano"],
    situacion:"Un filósofo sostiene que solo vale como conocimiento lo que se puede demostrar, y que la poesía, los sueños y la experiencia vivida son asunto de la literatura, no de la filosofía.",
    pregunta:"¿Cuál sería la respuesta de María Zambrano?",
    opciones:["Que tiene razón, y que la filosofía debe expulsar a los poetas, como hizo Platón.","Que hace falta una razón poética: una razón que, sin renunciar a pensar, escuche lo que la razón discursiva dejó afuera.","Que hay que abandonar la razón y entregarse a los sentimientos.","Que la experiencia vivida no existe, porque todo es lenguaje."],
    correcta:1,
    explicacion:"Zambrano critica la separación entre filosofía y poesía que empezó con Platón, y propone una razón poética que amplíe la razón, no que la abandone. Darle la razón al filósofo es aceptar la separación que ella discute. Entregarse a los sentimientos sin pensar no es su propuesta. Y negar la experiencia vivida es lo contrario de su filosofía." },
  { fichas:["sorjuana"],
    situacion:"En el siglo XVII, a una monja que estudia astronomía y teología le recuerdan la frase de san Pablo: «que las mujeres callen en la iglesia».",
    pregunta:"¿Cómo responde Sor Juana Inés de la Cruz en la Respuesta a sor Filotea?",
    opciones:["Rechaza la autoridad de san Pablo, porque las Escrituras no tienen valor para ella.","Interpreta que la frase se refiere a la predicación pública, no al estudio privado, y recuerda a las mujeres sabias que la Iglesia celebra.","Acepta la prohibición y abandona sus estudios de inmediato.","Sostiene que las mujeres deben predicar en las iglesias igual que los hombres."],
    correcta:1,
    explicacion:"Sor Juana no rechaza la autoridad de la Escritura: disputa su interpretación, y muestra que una prohibición general obligaría a condenar a las santas doctas. Rechazar a san Pablo no era su estrategia ni su creencia. En la Respuesta no abandona sus estudios; la renuncia llega años después, y su sentido se discute. Y no reclama el derecho a predicar, sino a estudiar y escribir." },
  { fichas:["zuleta"],
    situacion:"Después de un acuerdo de paz, un líder político dice: «Por fin vamos a vivir sin conflictos; ahora todos los colombianos estaremos unidos».",
    pregunta:"¿Qué objetaría Estanislao Zuleta?",
    opciones:["Que la paz solo es posible si se derrota militarmente a todos los enemigos.","Que la paz no es la ausencia de conflicto, sino la capacidad de vivirlo sin destruir al otro; un pueblo maduro para la paz es un pueblo maduro para el conflicto.","Que el conflicto es malo y hay que eliminarlo con más educación en valores.","Que la unidad nacional se logra encontrando un enemigo común."],
    correcta:1,
    explicacion:"Zuleta sostiene que el conflicto es constitutivo de la vida social, y que el ideal de una sociedad sin conflictos termina buscando culpables. La derrota militar del enemigo es la lógica de la guerra que critica. Eliminar el conflicto es el ideal de felicidad que discute. Y unir contra un enemigo común es precisamente la «fiesta» de la guerra." }
 ],
 vf:[
  { fichas:["aristoteles"], afirmacion:"Para Aristóteles, las formas existen separadas de las cosas sensibles, en un mundo aparte.", verdadero:false, explicacion:"Esa es la tesis de Platón que Aristóteles critica. Para Aristóteles la forma está en las cosas mismas, unida a su materia (hilemorfismo)." },
  { fichas:["kant"], afirmacion:"Kant sostiene que el espacio y el tiempo son formas a priori de la sensibilidad.", verdadero:true, explicacion:"Es la tesis de la Estética trascendental de la Crítica de la razón pura: no son propiedades de las cosas en sí, sino condiciones de nuestra intuición." },
  { fichas:["nagarjuna"], afirmacion:"Para Nagarjuna, la vacuidad es una sustancia sutil que está detrás de todas las cosas.", verdadero:false, explicacion:"La vacuidad no es una sustancia ni un fondo: es la ausencia de naturaleza propia, y ella misma está vacía. Convertirla en una sustancia es el error que Nagarjuna llama incurable." },
  { fichas:["wangyangming"], afirmacion:"Wang Yangming sostiene que el principio moral está en la mente-corazón (xīn) y que no hay que buscarlo en las cosas externas.", verdadero:true, explicacion:"Es su fórmula xīn jí lǐ, «la mente es el principio», contra la escuela de Zhu Xi, que buscaba el principio investigando las cosas una por una." },
  { fichas:["peirce","james"], afirmacion:"Peirce rebautizó su doctrina como «pragmaticismo» para distinguirla de la versión de James.", verdadero:true, explicacion:"Lo hizo en 1905, y dijo que era un nombre lo bastante feo como para que nadie quisiera robárselo." },
  { fichas:["dewey"], afirmacion:"Dewey sostuvo que la educación debe tener un fin fijo, exterior a ella, definido de antemano por el Estado.", verdadero:false, explicacion:"Para Dewey la educación no tiene un fin fuera de sí misma: su fin es el crecimiento, es decir, más y mejores experiencias (Democracia y educación)." },
  { fichas:["descartes"], afirmacion:"Según Descartes, la existencia del cuerpo es más cierta que la existencia del pensamiento.", verdadero:false, explicacion:"Es al revés: en la Meditación segunda, el pensamiento es lo primero y más cierto, y la existencia del cuerpo se establece mucho después." },
  { fichas:["laozi"], afirmacion:"Según el Daodejing, es el vacío del centro lo que hace útil a la rueda.", verdadero:true, explicacion:"Es el capítulo 11: treinta rayos convergen en un cubo, pero es su vacío lo que permite usar la rueda." },
  { fichas:["shankara"], afirmacion:"Shankara sostiene que el atman individual es una parte o una chispa de Brahman, distinta de él.", verdadero:false, explicacion:"Para Shankara el atman no participa de Brahman ni es una parte suya: es idénticamente Brahman. La distinción entre ambos es obra de la ignorancia." },
  { fichas:["dogen"], afirmacion:"Dōgen sostiene que se practica zazen para alcanzar la iluminación en el futuro.", verdadero:false, explicacion:"Para Dōgen práctica y realización son una sola cosa (shushō-ittō): sentarse ya es la realización, y esperar un premio futuro es el obstáculo." },
  { fichas:["nietzsche"], afirmacion:"En La gaya ciencia, Nietzsche presenta el eterno retorno como lo que un demonio le susurra a alguien en su soledad.", verdadero:true, explicacion:"Es el aforismo 341: el demonio anuncia que vas a vivir esta misma vida infinitas veces, y la pregunta es si lo maldecirías o lo bendecirías." },
  { fichas:["heidegger"], afirmacion:"Para Heidegger, el ser-para-la-muerte consiste en pensar todo el tiempo en que uno va a morir.", verdadero:false, explicacion:"Heidegger distingue la anticipación de la muerte de cavilar sobre ella. Anticiparla es dejar de encubrirla como algo impersonal, lo que «se muere», y asumirla como la posibilidad más propia." },
  { fichas:["wittgenstein"], afirmacion:"Para el segundo Wittgenstein, el significado de una palabra es, en muchos casos, su uso en el lenguaje.", verdadero:true, explicacion:"Es el §43 de las Investigaciones filosóficas, y marca su distancia con la teoría figurativa del Tractatus." },
  { fichas:["hegel"], afirmacion:"En sus Lecciones sobre la filosofía de la historia, Hegel considera a África una parte central de la historia universal.", verdadero:false, explicacion:"Hegel escribe lo contrario: que África no es una parte histórica del mundo y que no muestra movimiento ni desarrollo. Es uno de los ejemplos más citados de su eurocentrismo." },
  { fichas:["zea"], afirmacion:"Zea sostiene que la filosofía latinoamericana debe rechazar toda la herencia europea.", verdadero:false, explicacion:"Zea rechaza tanto el universalismo abstracto como el rechazo de lo europeo: hay que asumir la propia historia, incluida la colonial, no borrarla." },
  { fichas:["dussel"], afirmacion:"Dussel ubica el comienzo de la modernidad en 1492.", verdadero:true, explicacion:"Es la tesis de 1492: el encubrimiento del Otro: la modernidad se constituye con la conquista de América, no con Descartes." },
  { fichas:["rorty","dewey"], afirmacion:"Rorty se declaraba heredero de Dewey, a quien consideraba uno de los mayores filósofos del siglo XX.", verdadero:true, explicacion:"Rorty retoma a Dewey, aunque le quita la confianza en el método científico como modelo de toda investigación." },
  { fichas:["west"], afirmacion:"Cornel West usa la palabra «nihilismo» para nombrar una doctrina filosófica sobre la inexistencia de valores.", verdadero:false, explicacion:"West aclara que no usa el término en sentido filosófico: habla de la experiencia vivida de la falta de sentido, de esperanza y de amor." },
  { fichas:["falacias"], afirmacion:"La falacia de la falacia consiste en concluir que una afirmación es falsa porque el argumento que la defendía era falaz.", verdadero:true, explicacion:"Un argumento malo no prueba su conclusión, pero eso no la vuelve falsa. Tiene nombre latino: argumentum ad logicam." },
  { fichas:["confucio"], afirmacion:"Confucio sostiene que gobernar con leyes y castigos produce un pueblo que evita la falta pero no siente vergüenza.", verdadero:true, explicacion:"Es Analectas 2.3: frente a eso, gobernar con la virtud y los ritos produce un pueblo que siente vergüenza y se corrige." },
  { fichas:["zhuangzi"], afirmacion:"Según el Zhuangzi, cuando murió su esposa, Zhuangzi primero sintió dolor y después cantó golpeando un cuenco.", verdadero:true, explicacion:"Es el capítulo 18: le explica a Hui Shi que la vida y la muerte se suceden como las estaciones." },
  { fichas:["vasconcelos"], afirmacion:"Vasconcelos fue secretario de Educación Pública de México y promovió campañas de alfabetización y bibliotecas populares.", verdadero:true, explicacion:"Fue secretario entre 1921 y 1924, y su gestión incluyó alfabetización, bibliotecas, ediciones populares de clásicos y el impulso al muralismo." },
  { fichas:["james"], afirmacion:"James sostiene que es legítimo creer lo que uno quiera, aunque la evidencia disponible lo contradiga.", verdadero:false, explicacion:"La voluntad de creer vale solo para opciones vivas, forzosas y trascendentales que la evidencia no puede decidir. Donde la evidencia decide, James está de acuerdo con Clifford." },
  { fichas:["platon"], afirmacion:"Para Platón, de lo sensible solo hay opinión (doxa), y el saber verdadero tiene por objeto las Formas.", verdadero:true, explicacion:"Lo sensible cambia y admite propiedades contrarias; el saber (epistēmē) es de lo que no cambia." },
  { fichas:["arendt"], afirmacion:"Para Hannah Arendt, la expresión «banalidad del mal» significa que los crímenes nazis fueron poco graves.", verdadero:false, explicacion:"Lo banal no son los crímenes, que fueron monstruosos, sino el criminal: el mal extremo no necesitó una maldad profunda en quien lo ejecutaba." },
  { fichas:["beauvoir"], afirmacion:"La frase «No se nace mujer: se llega a serlo» abre el segundo volumen de El segundo sexo.", verdadero:true, explicacion:"Es la primera frase del segundo volumen, «La experiencia vivida», que describe cómo se forma la mujer desde la infancia." },
  { fichas:["zambrano"], afirmacion:"María Zambrano vivió en el exilio desde 1939 hasta 1984, en países como México, Cuba, Puerto Rico, Italia, Francia y Suiza.", verdadero:true, explicacion:"Salió de España con la derrota de la República y volvió en 1984; el exilio es una condición central de su pensamiento." },
  { fichas:["sorjuana"], afirmacion:"En la Respuesta a sor Filotea, Sor Juana sostiene que las mujeres no deben estudiar asuntos profanos.", verdadero:false, explicacion:"Sostiene lo contrario: que la inclinación a saber es natural y que estudió todas las ciencias como escalones para llegar a la teología." },
  { fichas:["zuleta"], afirmacion:"Estanislao Zuleta escribió el Elogio de la dificultad como discurso al recibir un doctorado honoris causa de la Universidad del Valle.", verdadero:true, explicacion:"Fue en 1980, en psicología; Zuleta nunca había terminado el bachillerato." }
 ],
 emparejar:[
  { mod:"platon", idea:"La alegoría de la caverna: lo que vemos son sombras de lo que verdaderamente es." },
  { mod:"aristoteles", idea:"La felicidad es una actividad del alma según la virtud." },
  { mod:"descartes", idea:"Pienso, luego existo." },
  { mod:"kant", idea:"Obrá solo según una máxima que puedas querer que se convierta en ley universal." },
  { mod:"hegel", idea:"Lo racional es real, y lo real es racional." },
  { mod:"nietzsche", idea:"Dios ha muerto, y nosotros lo hemos matado." },
  { mod:"heidegger", idea:"La existencia humana es un ser-en-el-mundo que se pregunta por el ser." },
  { mod:"wittgenstein", idea:"Los juegos no comparten una esencia, sino parecidos de familia." },
  { mod:"confucio", idea:"Gobernar con la virtud y los ritos, no con castigos." },
  { mod:"laozi", idea:"Actuar sin forzar (wú wéi), como el agua, que vence a lo duro sin pelear." },
  { mod:"zhuangzi", idea:"Soñé que era una mariposa, y ya no sé si soy un hombre que soñó ser mariposa o una mariposa que sueña ser hombre." },
  { mod:"nagarjuna", idea:"Lo que surge en dependencia es lo que llamamos vacuidad." },
  { mod:"shankara", idea:"El atman es Brahman: el mundo múltiple es una cuerda vista como serpiente." },
  { mod:"dogen", idea:"Práctica y realización son una sola cosa." },
  { mod:"nishida", idea:"No hay experiencia porque hay individuo, sino individuo porque hay experiencia." },
  { mod:"wangyangming", idea:"Saber y no hacer es todavía no saber." },
  { mod:"peirce", idea:"La verdad es la opinión en la que convergerían todos los que investigan." },
  { mod:"james", idea:"Hay hechos que no ocurren si nadie cree antes en ellos." },
  { mod:"dewey", idea:"La democracia es, antes que una forma de gobierno, una forma de vida." },
  { mod:"vasconcelos", idea:"En América Latina se formará la quinta raza, la raza cósmica." },
  { mod:"zea", idea:"La filosofía americana como filosofía sin más." },
  { mod:"dussel", idea:"Antes del «yo pienso» estuvo el «yo conquisto»." },
  { mod:"rorty", idea:"La ironista liberal duda de su vocabulario final, y cree que la crueldad es lo peor que hacemos." },
  { mod:"west", idea:"La esperanza no es optimismo: es no dejar que el mal tenga la última palabra." },
  { mod:"arendt", idea:"El mal extremo puede ser cometido por personas que dejaron de pensar lo que hacían." },
  { mod:"beauvoir", idea:"No se nace mujer: se llega a serlo." },
  { mod:"zambrano", idea:"Hace falta una razón poética, que escuche lo que la razón discursiva dejó afuera." },
  { mod:"sorjuana", idea:"Si Aristóteles hubiera guisado, mucho más hubiera escrito." },
  { mod:"zuleta", idea:"Un pueblo maduro para la paz es un pueblo maduro para el conflicto." }
 ]
};
