/* ============================================================
   Ficha: falacias  ·  tradición: metodo
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"falacias", trad:"metodo", nombre:"Taller de falacias", fechas:"Para todas las tradiciones", escuela:"Lógica informal", icon:"🧩", profundizada:true,
 tesis:"Un argumento puede fallar sin violar ninguna regla de la lógica formal: falla porque su fuerza persuasiva viene de otro lado que de sus razones. Eso es una falacia, y la definición estándar la describe con dos componentes inseparables — es un mal argumento y además parece uno bueno, porque si solo fuera inválido sería un error cualquiera y nadie caería en él. De ahí que estudiar falacias sea a la vez estudiar lógica y estudiar persuasión. Este taller es transversal: no expone el pensamiento de un autor sino una caja de herramientas que se aplica a todos los demás módulos y, antes que a ninguno, a los propios escritos del estudiante. Y viene con tres advertencias que valen tanto como la lista de nombres. La primera es que casi ninguna de estas formas es falaz siempre: apelar a un experto, advertir sobre consecuencias o señalar un conflicto de intereses pueden ser movimientos perfectamente razonables, y lo que hay que aprender es la condición exacta que separa el uso legítimo del abusivo. La segunda es que nombrar una falacia no refuta una tesis, solo muestra que ese argumento concreto no la sostiene, y creer lo contrario es a su vez una falacia. La tercera es que el catálogo rinde mucho más aplicado hacia adentro que usado como munición para ganar discusiones.",
 obras:[
   {t:"Sobre las refutaciones sofísticas", d:"Tratado breve de Aristóteles que cierra los Tópicos y que es el primer catálogo sistemático de falacias de la historia de la filosofía occidental. Su objeto declarado no es la lógica pura sino un oficio: cómo detectar y desarmar las refutaciones aparentes con que los sofistas ganaban discusiones públicas. Distingue trece tipos y los reparte en dos grupos que siguen siendo la mejor clasificación de partida. Las que dependen del lenguaje (in dictione) explotan ambigüedades reales del habla: la equivocación, que usa un término en dos sentidos dentro del mismo razonamiento; la anfibolía, que aprovecha una ambigüedad de construcción; la composición y la división, que trasladan al todo lo que vale para las partes o al revés; el acento y la forma de la expresión. Las que no dependen del lenguaje (extra dictionem) incluyen el accidente, la confusión entre lo dicho en absoluto y lo dicho en cierto respecto, la petición de principio, la falsa causa, la pregunta compleja y la ignoratio elenchi, que consiste en probar impecablemente algo distinto de lo que había que probar. Aristóteles subraya un punto que la tradición posterior suele perder: el sofista no engaña por azar sino porque el lenguaje natural ofrece de veras esos huecos, de modo que estudiar falacias es estudiar cómo funciona el lenguaje cuando argumenta."},
   {t:"Retórica a Herenio", d:"Manual latino anónimo de hacia el año 85 antes de nuestra era, atribuido durante siglos a Cicerón y todavía el tratado de retórica más antiguo conservado en latín. Interesa a este taller por dos razones. La primera es que dedica un apartado a los vicios de la argumentación: enumera de manera ordenada las maneras en que una prueba puede parecer sólida sin serlo, desde la premisa que no viene al caso hasta la conclusión que excede lo que las razones permiten, y lo hace desde el punto de vista de quien tiene que hablar en un juicio y no desde el de un lógico. La segunda es que trata sin rodeos los recursos que hoy llamaríamos apelaciones falaces — el llanto, la indignación, la invocación de la desgracia propia, el prestigio del orador — como técnicas que funcionan, y explica cómo producirlas. Esa doble cara lo vuelve un documento incómodo y muy útil: muestra que el catálogo de falacias no nació de la indignación moral contra el engaño sino del estudio técnico de la persuasión, y que quien quiera defenderse de estas maniobras necesita entender por qué convencen y no solo por qué fallan."},
   {t:"Fallacies, de Charles Hamblin", d:"Libro de 1970 que abre la discusión académica contemporánea sobre el tema y que conviene conocer aunque no se lo lea entero. Hamblin empieza con una acusación demoledora contra lo que llama el tratamiento estándar: los manuales de lógica del siglo XX despachaban las falacias en un capítulo final, mal argumentado, copiado de manual en manual desde hacía siglos, con ejemplos inventados que nadie había dicho nunca y con definiciones que no resistían el análisis. Su crítica más filosa apunta a la definición misma. Si una falacia es un argumento que parece válido sin serlo, entonces parecer válido es una propiedad psicológica y relativa a quién mira, de modo que la noción no se deja definir en términos puramente lógicos. De ahí sale el giro que domina el campo desde entonces: para evaluar un argumento no alcanza con mirar su forma, hay que mirar el contexto de la discusión en que se lo usa, quién carga con la prueba y qué compromisos asumió cada participante. Hamblin propone para eso una teoría de los sistemas dialécticos, con reglas explícitas de juego, que es el antecedente directo de la pragmadialéctica posterior."},
   {t:"Las claves de la argumentación, de Anthony Weston", d:"Publicado en inglés en 1986 como A Rulebook for Arguments y traducido al castellano como Las claves de la argumentación, es probablemente el manual breve más usado del mundo en cursos introductorios de pensamiento crítico. Su virtud es el formato: reglas cortas, numeradas y ejemplificadas, pensadas como un manual de estilo y no como un tratado, de modo que se consulta mientras se escribe en lugar de estudiarse de memoria. Empieza por lo que casi ningún texto sobre falacias hace, que es enseñar a construir un argumento antes de enseñar a destruirlo: identificar la conclusión, ordenar las premisas, exponer las ideas en un orden natural, partir de premisas fiables y usar un lenguaje concreto y consistente. Recién después aparecen las falacias, y aparecen como el reverso de esas mismas reglas. Weston agrega una recomendación que este taller adopta como criterio de trabajo: el objetivo de un argumento no es ganar sino averiguar qué posiciones se sostienen y cuáles no, y por eso la primera obligación es presentar la posición contraria en su mejor versión."},
   {t:"La pragmadialéctica de Van Eemeren y Grootendorst", d:"Programa de investigación desarrollado en Ámsterdam desde los años ochenta, expuesto entre otros libros en Argumentation, Communication and Fallacies de 1992, y hoy el marco de referencia dominante en teoría de la argumentación. Su movimiento central es cambiar la pregunta: en lugar de definir la falacia como una forma lógica defectuosa, la define como la violación de alguna de las reglas de una discusión crítica orientada a resolver una diferencia de opinión. Esas reglas son explícitas y por lo tanto discutibles — nadie puede impedir que el otro plantee o cuestione una postura, quien afirma algo debe estar dispuesto a defenderlo, hay que atacar la posición efectivamente sostenida y no otra, no se puede presentar como premisa compartida algo que no se acordó, y así hasta diez. Leída así, la falacia del hombre de paja deja de ser un error de razonamiento y pasa a ser una infracción concreta: se atacó algo que el otro no dijo. La ventaja del enfoque es que explica por qué la misma forma argumentativa resulta aceptable en un contexto e inaceptable en otro; su costo es que exige acordar de antemano qué cuenta como discusión crítica, y buena parte de la conversación pública no se parece a eso en absoluto."}
 ],
 conceptos:[
   {t:"Ad hominem y sus variantes", d:"Consiste en dirigir el ataque contra la persona que argumenta en lugar de hacerlo contra su argumento. La forma más burda es el insulto directo, pero las dos variantes interesantes son otras. El ad hominem circunstancial señala la situación o el interés de quien habla: trabaja para la empresa que financia el estudio, es candidato, le conviene que esto se apruebe. El tu quoque devuelve la acusación: vos también lo hacés, así que tu crítica no vale. Lo decisivo es que ninguna de las dos toca el contenido de lo afirmado, y un argumento correcto lo sigue siendo aunque lo formule alguien interesado o incoherente. Ahora bien, hace falta una precisión que casi todos los manuales escolares omiten. Señalar un conflicto de intereses es perfectamente legítimo cuando lo que está en juego no es un argumento sino un testimonio: si alguien me pide que le crea porque lo vio, su credibilidad es exactamente lo que corresponde evaluar. Y el tu quoque, aunque no refuta nada, puede mostrar de manera válida que quien acusa no sostiene en serio el criterio que invoca. La regla práctica es corta: si el otro ofrece razones verificables, hay que atender las razones; si el otro ofrece su palabra, hay que atender a quién la da."},
   {t:"Falacia del hombre de paja", d:"Consiste en reemplazar la posición del adversario por una versión deformada y más débil, y refutar esa. El ejemplo cotidiano es responder a la propuesta de regular ciertos usos de las redes con la acusación de querer censurar internet entero, o a la propuesta de revisar una partida del presupuesto con la acusación de querer cerrar el hospital. La deformación no siempre es deliberada: a menudo nace de no haber leído con cuidado, de citar un fragmento sin su contexto, o de discutir con la versión más torpe que uno escuchó alguna vez en lugar de con la que tiene enfrente. Hay una variante especialmente difícil de detectar, el hombre de paja hueco, que consiste en inventar un adversario que no existe: alguien dice que ciertos autores sostienen tal disparate, sin nombrar a ninguno. Su antídoto no es una regla lógica sino una disciplina: antes de objetar, reformular la posición contraria hasta que quien la sostiene reconozca que es la suya. Esa operación inversa se llama hombre de acero, y tiene una consecuencia práctica que conviene anunciar en el aula, porque desalienta a muchos: a veces uno descubre que la versión fuerte del argumento ajeno es mejor que la propia."},
   {t:"Falsa dicotomía", d:"Consiste en presentar como exhaustivas dos opciones que no agotan el campo, para forzar la elección de una. La fórmula clásica es «o estás con nosotros o estás con ellos», y su versión de aula es «o se aprueba esta reforma o todo sigue igual». La trampa no está en que las dos alternativas sean falsas, porque suelen ser bien reales, sino en que la lista está incompleta y el que la arma es el mismo que quiere ganar. Conviene distinguirla de dos cosas parecidas y legítimas. La primera es la disyunción genuina: hay casos donde efectivamente solo existen dos salidas, y afirmarlo no es falaz sino verdadero, aunque la carga de mostrarlo recae en quien lo afirma. La segunda es la simplificación deliberada con fines de decisión: un cuerpo colegiado que debe votar entre dos mociones no comete ninguna falacia al votar, siempre que el procedimiento haya dejado presentar otras. La pregunta que desarma el dilema es siempre la misma y hay que hacerla en voz alta: qué tercera opción se está quedando fuera, y a quién le conviene que no se mencione."},
   {t:"Pendiente resbaladiza", d:"Consiste en rechazar un primer paso alegando que conducirá inevitablemente a un desenlace extremo, sin mostrar el mecanismo que produciría esa cadena. Si se permite esta excepción no quedará ninguna regla en pie; si se admite esta figura legal, mañana se admitirá cualquier cosa. Lo que falla no es la forma del razonamiento sino la evidencia: cada eslabón de la cadena tiene una probabilidad menor que uno, y al multiplicarlas el resultado final suele ser remotísimo, mientras el argumento lo presenta como seguro. Por eso esta es la falacia donde más claramente se ve que la etiqueta no decide nada por sí sola. Una advertencia sobre consecuencias no es falaz cuando el mecanismo existe y puede exhibirse: los precedentes judiciales encadenan de verdad, los incentivos económicos se propagan de verdad, y hay procesos institucionales donde el primer paso efectivamente vuelve mucho más barato el segundo. La diferencia entre la advertencia responsable y el miedo disfrazado de argumento está en si se puede nombrar el eslabón intermedio y ofrecer algún caso real en que se haya recorrido."},
   {t:"Apelación a la autoridad", d:"Consiste en aceptar una afirmación por el prestigio de quien la hace y no por las razones que la sostienen. Este es el concepto peor enseñado de toda la lista, porque se lo suele presentar como si toda deferencia hacia un experto fuera un error de razonamiento, y eso es a la vez falso e impracticable: nadie puede verificar por su cuenta la seguridad de un medicamento, la datación de un manuscrito o el cálculo estructural de un puente, y confiar en quien sabe es una operación perfectamente racional. La versión útil de la regla enumera condiciones. La deferencia es legítima cuando la persona es efectivamente especialista en el campo del que habla, cuando la afirmación pertenece a ese campo y no a otro, cuando existe consenso entre los especialistas y no una controversia abierta, y cuando quien habla no tiene un interés personal decisivo en lo que afirma. Se vuelve falaz en cuanto falta alguna: el premio Nobel de física opinando sobre política monetaria, el actor que recomienda un tratamiento, la cita de un autor célebre fuera de su terreno, o el consenso invocado que en realidad no existe. Su hermana menor es la apelación a la mayoría, que sustituye al experto por el número: mucha gente lo cree, luego es verdad."},
   {t:"Petición de principio", d:"Consiste en incluir entre las premisas, de alguna forma, aquello mismo que la conclusión debía establecer. El caso de manual es circular y transparente — este texto dice la verdad porque él mismo afirma decirla — pero en esa forma no cae nadie. La versión peligrosa es la que ocurre en argumentos largos, donde la premisa que repite la conclusión aparece reformulada con otras palabras varios pasos antes y separada de ella por material intermedio que distrae. También se esconde en el vocabulario: llamar asesinato a lo que está justamente en discusión, o llamar liberación a la medida que se debate, mete la conclusión dentro de los términos y hace que el asunto parezca resuelto antes de empezar. Hay que registrar una sutileza que la vuelve filosóficamente interesante: un argumento circular es formalmente válido, porque si las premisas son verdaderas la conclusión lo es necesariamente. Lo que le falta no es validez sino fuerza probatoria, ya que nadie que dudara de la conclusión podría aceptar las premisas. Por eso esta falacia es el mejor ejemplo disponible de que la validez lógica no alcanza para que un argumento sirva de algo."},
   {t:"Falacia genética", d:"Consiste en evaluar una idea por su origen en lugar de por su contenido. Se rechaza una teoría porque su autor tenía creencias inaceptables en otro tema, se descarta un estudio porque lo financió una empresa, se desestima una propuesta porque la trajo el partido contrario, o se acepta una costumbre simplemente porque es antigua, porque la versión positiva también existe y es igual de falaz. El parentesco con el ad hominem es evidente y de hecho suelen aparecer juntos, pero no son lo mismo: el ad hominem apunta a la persona que argumenta ahora, y la falacia genética a la procedencia histórica o institucional de la idea. Como en los demás casos, el origen no es irrelevante en todos los usos. Saber quién financió un estudio es una razón excelente para revisarlo con más cuidado, para preguntar si se publicaron también los resultados negativos y para exigir replicación; lo que no es, es una razón para darlo por falso sin abrirlo. La formulación honesta separa dos cosas: el origen puede modificar cuánta confianza previa le doy a una afirmación, pero no puede reemplazar el examen de sus razones. Vale la pena notar que esta es exactamente la objeción que se le hace al método genealógico en filosofía."},
   {t:"Correlación y causación", d:"Consiste en inferir que una cosa causa otra a partir de que aparecen juntas o una después de la otra. La tradición distingue dos versiones. El cum hoc ergo propter hoc toma la simple asociación por causa: los meses de más venta de helado son los de más ahogamientos, luego el helado ahoga. El post hoc ergo propter hoc agrega el orden temporal: tomé esta infusión y al día siguiente se me fue el resfrío, luego la infusión lo curó. Las explicaciones alternativas que hay que descartar antes de afirmar una causa son siempre las mismas cuatro y conviene memorizarlas. La casualidad, porque en cualquier conjunto grande de datos aparecen coincidencias espectaculares. La causalidad inversa, porque quizá B causa A y no al revés. La variable oculta, que causa las dos cosas y explica que anden juntas, como el calor explica helados y ahogamientos. Y la regresión a la media, que hace que casi cualquier intervención sobre un caso extremo parezca funcionar. Nada de esto implica que la correlación no sirva: es la principal pista con que trabaja toda la investigación empírica. Implica que es el comienzo de una hipótesis y no el final de una demostración."},
   {t:"Generalización apresurada", d:"Consiste en extender a toda una clase lo que se observó en unos pocos casos, o en casos mal elegidos. El ejemplo cotidiano es el argumento por anécdota: mi abuelo fumó ochenta años y murió sano, conozco a alguien que hizo esto y le salió bien. Dos defectos distintos pueden producirla. Uno es el tamaño: tres casos no alcanzan para hablar de una tendencia, y la intuición humana es notoriamente mala calculando cuántos harían falta. El otro es más grave y menos visible: el sesgo de selección, que aparece cuando la muestra no es representativa porque el modo mismo de obtenerla favorece cierto resultado. Encuestar sobre el transporte público solo a quienes viajan en la hora pico, o evaluar una terapia solo con los pacientes que terminaron el tratamiento, produce conclusiones firmes y falsas por más grande que sea la muestra. Su versión especializada es el sesgo del superviviente, que consiste en estudiar únicamente los casos que llegaron hasta el final — las empresas que sobrevivieron, los aviones que volvieron — y extraer de ellos la receta del éxito, ignorando que los que fracasaron tenían los mismos rasgos y no están ahí para contarlo."},
   {t:"Falacia del francotirador", d:"Consiste en elegir los datos después de verlos y presentar el patrón resultante como si hubiera sido predicho. El nombre viene de una imagen que conviene contar entera porque se recuerda para siempre: alguien dispara al azar contra el costado de un granero, después dibuja la diana alrededor del grupo de balazos más apretado y sale a mostrar su puntería. La versión seria de esa maniobra tiene consecuencias reales. Si uno mide veinte variables y publica solo la que dio un resultado llamativo, la probabilidad de haber encontrado una coincidencia es altísima aunque cada cálculo esté bien hecho. Si uno decide dónde empieza y dónde termina un período después de mirar los datos, puede hacer que casi cualquier tendencia aparezca. Y si uno cuenta las profecías que se cumplieron y no las que fallaron, cualquier vidente resulta infalible. La defensa contra esta falacia es procedimental y no lógica: decir de antemano qué se va a medir y qué resultado contaría como refutación. Por eso el registro previo de las hipótesis se volvió un asunto central de la metodología científica contemporánea, y por eso es el ejercicio más útil que puede pedirse en clase antes de mirar cualquier dato."},
   {t:"Apelación a la naturaleza", d:"Consiste en tomar el hecho de que algo sea natural como razón suficiente para considerarlo bueno, o su carácter artificial como razón para considerarlo malo. Aparece a diario en la publicidad de alimentos y de terapias, y también en discusiones morales mucho más serias sobre qué formas de vida, de familia o de cuerpo serían las que corresponden. Su problema es doble. El primero es empírico: la categoría de lo natural es notablemente imprecisa, y cualquier inventario honesto de lo que la naturaleza produce incluye el arsénico, los terremotos y la mortalidad infantil, mientras el de lo artificial incluye las vacunas y los anteojos. El segundo es lógico y lo formuló Hume: de una descripción de cómo son las cosas no se sigue por sí sola ninguna conclusión sobre cómo deben ser, salvo que se añada una premisa valorativa que casi nunca se enuncia. Conviene no confundirla con la falacia naturalista que nombró Moore, que es un asunto distinto y más técnico, el de definir lo bueno mediante alguna propiedad natural como el placer o lo deseado. Y conviene registrar la maniobra inversa, menos comentada y exactamente igual de falaz, que consiste en considerar superior cualquier cosa por ser nueva, tecnológica o artificial."},
   {t:"Falacia del punto medio", d:"Consiste en concluir que la posición correcta está entre dos posiciones enfrentadas por el solo hecho de que estén enfrentadas. Si uno sostiene que la deuda es de mil y el otro que es de cero, la respuesta no es quinientos: es la que dicen los registros. La falacia se vuelve socialmente poderosa porque el término medio tiene prestigio, suena prudente y moderado, y porque quien lo adopta aparece como el adulto de la conversación sin haber examinado nada. Su consecuencia práctica más seria es que premia el extremismo: si el resultado va a ser siempre el promedio, a cada parte le conviene pedir mucho más de lo que quiere. En periodismo tiene nombre propio, el falso equilibrio, y consiste en presentar como dos posiciones equivalentes lo que en realidad es un consenso amplio frente a una postura marginal, con el argumento de que hay que dar voz a las dos partes. Conviene distinguirla con cuidado de dos cosas legítimas: del término medio aristotélico, que no es un promedio entre opiniones sino un juicio situado sobre la acción correcta, y de la negociación política, donde partir la diferencia no pretende encontrar la verdad sino cerrar un acuerdo, que es otra cosa y perfectamente respetable."},
   {t:"Apelación a la ignorancia", d:"Consiste en tomar la falta de pruebas en contra de algo como prueba a favor, o la falta de pruebas a favor como demostración de que es falso. Nadie demostró que esto no ocurra, luego ocurre; nadie pudo probarlo, luego es mentira. El error de fondo es confundir dos estados epistémicos muy distintos: no saber si algo es el caso y saber que no lo es. Su antídoto conceptual es la carga de la prueba, es decir, la pregunta de a quién le toca demostrar qué en esta discusión concreta, una noción que viene del derecho y que la teoría de la argumentación adoptó como pieza central. La regla habitual es que la carga recae en quien afirma la existencia de algo, porque es mucho más fácil aportar un caso que probar una ausencia universal. Hay sin embargo un matiz importante y a veces olvidado: la ausencia de evidencia sí es evidencia de ausencia cuando la evidencia debería haber aparecido. Si un tratamiento se estudió durante treinta años con muestras enormes y nunca se detectó el efecto anunciado, no saber nada ya no es una situación neutral. Lo falaz es aplicar el argumento allí donde nunca se buscó."},
   {t:"La falacia de la falacia", d:"Consiste en concluir que una afirmación es falsa porque el argumento que la defendía era falaz. Tiene nombre latino, argumentum ad logicam, y merece figurar en un taller de falacias precisamente porque es la que más cometen quienes acaban de aprender la lista. Un argumento pésimo puede tener una conclusión verdadera: si alguien defiende que fumar hace mal con un ad hominem contra las tabacaleras, su argumento no prueba nada y sin embargo fumar sigue haciendo mal. Detectar el error muestra que esa razón no sostiene la tesis, y deja la tesis exactamente donde estaba, sin apoyo por ese lado y sin refutar. La consecuencia pedagógica es incómoda y hay que decirla en voz alta, porque es el riesgo principal de enseñar este contenido. Un catálogo de etiquetas puede convertirse en un instrumento para no escuchar: se nombra la falacia, se declara ganada la discusión y no se examina nunca el asunto de fondo. La prueba de que alguien aprendió bien este módulo no es la velocidad con que etiqueta los argumentos ajenos, sino que después de nombrar la falacia siga preguntando si la conclusión es verdadera y qué argumento mejor podría sostenerla."}
 ],
 conexion:"El primer catálogo es de <b>Aristóteles</b>, que en las Refutaciones sofísticas escribe sobre todo contra los sofistas de su tiempo; leerlo junto a <b>Platón</b> muestra que la filosofía occidental nace en buena medida del intento de distinguir argumentar de convencer. La tradición latina y medieval agregó los nombres que todavía usamos, y Locke popularizó varias de esas etiquetas en el Ensayo sobre el entendimiento humano. En el siglo XX el tema se reabre con la crítica de Charles Hamblin al tratamiento de manual y con la pragmadialéctica de Van Eemeren y Grootendorst, que define la falacia por el contexto de la discusión y no por la forma del argumento. Hacia adelante, el taller conecta con casi todos los demás módulos: la falacia genética es exactamente la objeción que se le hace al método genealógico de <b>Nietzsche</b>, la exigencia de reconstruir la posición contraria en su mejor versión es la versión técnica del principio de caridad que <b>Dussel</b> reclama antes de discutir con el otro, y la sospecha de <b>Wittgenstein</b> hacia los problemas que nacen de un mal uso del lenguaje explica por qué tantas falacias son, en el fondo, ambigüedades no advertidas.",
 dialogo:{titulo:"Tres falacias y una trampa", lineas:[
   {quien:"Julián", texto:"Estoy en contra de prohibir los celulares durante la clase, y te digo por qué: la propuesta la firma gente que no pisa un aula hace veinte años."},
   {quien:"Marta", texto:"Eso puede ser cierto y todavía no es un argumento. Me dijiste quién firma, no qué está mal en lo que dice. Es un ad hominem circunstancial."},
   {quien:"Julián", texto:"No es un ataque personal, es un dato relevante. Si alguien no conoce el aula, su opinión sobre el aula vale menos."},
   {quien:"Marta", texto:"Ahí tenés razón a medias, y conviene separar los dos casos. Si la propuesta se apoya en que ellos vieron lo que pasa en las aulas, su experiencia es justamente lo que hay que evaluar. Si se apoya en tres estudios con datos, los datos no cambian según quién los cite.", nota:"Este es el matiz que la enseñanza escolar de las falacias suele borrar: el ad hominem circunstancial es falaz frente a un argumento y legítimo frente a un testimonio. Señalar un conflicto de intereses no refuta una tesis, pero sí es una razón válida para revisar con más cuidado a quien nos pide que le creamos."},
   {quien:"Julián", texto:"Está bien. Entonces lo digo de otro modo: lo que quieren es que los chicos no usen tecnología nunca."},
   {quien:"Marta", texto:"Eso ya no lo dijo nadie. La propuesta habla del uso libre durante la clase. Acabás de fabricar un hombre de paja: refutás una posición más fácil que la que tenés enfrente."},
   {quien:"Julián", texto:"Puede ser que haya exagerado. Pero mirá lo que viene después: primero el celular, después la computadora, y al final van a prohibir que los chicos hablen entre ellos."},
   {quien:"Marta", texto:"Nombrame el paso intermedio. No te pido que me demuestres que es imposible: te pido el mecanismo por el cual la primera medida haría más probable la segunda. Sin eso es una pendiente resbaladiza."},
   {quien:"Julián", texto:"Sin eso es miedo, ya sé. Aunque también hay pendientes reales: en mi colegio una excepción al reglamento se convirtió en la regla en dos años, y podría contarte paso por paso cómo pasó."},
   {quien:"Marta", texto:"Y si podés contarlo, entonces no es una falacia sino una advertencia con evidencia. Esa es toda la diferencia, y no es una diferencia de forma."},
   {quien:"Julián", texto:"Bien. Te concedo las tres. ¿Entonces hay que prohibir los celulares en clase?"},
   {quien:"Marta", texto:"Obviamente sí, ya que los tres argumentos que trajiste en contra eran falaces."},
   {quien:"Julián", texto:"Ahí te agarré. Acabás de hacer exactamente lo que enseñás a no hacer. Que mis argumentos fueran malos no vuelve verdadera tu conclusión."},
   {quien:"Marta", texto:"Es cierto y me lo merezco. Se llama falacia de la falacia, o argumentum ad logicam, y es la que más cometen los que recién aprenden la lista. Nombrar el error muestra que ese argumento no sostiene la tesis; no muestra que la tesis sea falsa.", nota:"Vale subrayarlo porque es el punto entero del taller. Un argumento falaz puede tener una conclusión verdadera, y una conclusión verdadera mal defendida sigue necesitando una defensa. Quien usa el catálogo para dar por terminada una discusión lo está usando exactamente al revés."},
   {quien:"Julián", texto:"Entonces volvamos al principio y sin etiquetas. ¿Vos qué sostenés, y con qué?"},
   {quien:"Marta", texto:"Sostengo que conviene restringir el uso durante la clase, y me apoyo en tres cosas que podés verificar: la investigación sobre atención dividida, lo que dicen los propios estudiantes en las encuestas internas, y el resultado de la prueba que hicimos el año pasado en dos cursos. Ninguna de las tres es concluyente por sí sola, y la tercera es la más discutible."},
   {quien:"Julián", texto:"Con eso ya podemos discutir. Y antes de responderte voy a hacer el ejercicio que me diste la semana pasada: reconstruir tu posición hasta que la reconozcas como tuya, y recién después buscarle el punto débil."}
 ]},
 actividades:[
   {t:"Tres falacias reales, con la reconstrucción incluida", d:"Durante una semana juntá tres argumentos falaces que hayas visto realmente — en una columna de opinión, en un debate parlamentario, en un hilo de red social, en una reunión de trabajo o en una conversación familiar — y guardá el texto exacto, con fecha y fuente, sin parafrasearlo de memoria. Para cada uno escribí cuatro cosas en este orden estricto. Primero, la conclusión que se defendía, formulada con las palabras del autor. Segundo, el nombre de la falacia y, sobre todo, la razón por la que ese caso concreto la comete, que es lo que se evalúa: no alcanza con poner la etiqueta. Tercero, la reconstrucción caritativa, es decir, el mejor argumento que esa misma persona podría haber dado a favor de la misma conclusión sin cometer el error. Y cuarto, el veredicto honesto sobre la conclusión: queda refutada, queda sin apoyo por ese lado, o te sigue pareciendo verdadera a pesar del mal argumento. Ese cuarto punto es el que impide que el ejercicio se convierta en una colección de trofeos, y suele ser el que más cuesta."},
   {t:"El argumento saboteado", d:"Escribí un argumento de entre quince y veinte líneas a favor de una posición que sostengas de verdad, con premisas explícitas y una conclusión clara, y hacelo tan sólido como puedas. Después escribí una segunda versión idéntica en apariencia pero con una sola falacia insertada deliberadamente, sin avisar cuál ni dónde, y cuidando que el texto siga sonando razonable: si el error se nota de entrada, el sabotaje fue torpe. Intercambiá las dos versiones con un compañero y pedile que encuentre la falacia, la nombre y explique por qué lo es. Cuando ambos hayan terminado, comparen los resultados y discutan tres preguntas. Cuál falacia resultó más fácil de esconder y por qué. Si hubo alguna que el otro señalara en la versión sana, es decir, un falso positivo, y qué lo produjo. Y la más útil de las tres: al escribir la versión saboteada, tuviste que inventar el error o descubriste que ya estaba en tu primer borrador. Ese último hallazgo es frecuente y vale más que todo el resto del ejercicio."},
   {t:"Ejercicio de hombre de acero", d:"Elegí una posición que te parezca claramente equivocada y sobre la que tengas opinión formada: puede ser política, pedagógica, religiosa o de tu propia disciplina. Buscá a quien la defienda mejor y no a quien la defienda peor, que es la parte que casi nadie hace, y leelo o escuchalo entero. Después escribí una página defendiéndola en primera persona, con sus mejores razones, sus datos y sus objeciones a tu propia postura, sin ironía, sin comillas de distancia y sin ningún gesto que le avise al lector que en realidad no estás de acuerdo. Mostrásela a alguien que efectivamente sostenga esa posición y pedile una sola cosa: que te diga si reconoce ahí lo que piensa. Si te corrige, corregí y volvé a mostrarlo, hasta que diga que sí. Recién entonces escribí media página con tu objeción, que ahora va a tener que ser mucho mejor que la que tenías al empezar. Cerrá anotando qué cambió: puede ser tu objeción, puede ser tu opinión, y puede ser simplemente que descubriste que el desacuerdo real estaba en otro punto del que creías."}
 ],
 cuestionario:[
   {q:"Si un argumento contiene una falacia, ¿queda refutada la conclusión que defendía?", p:"No, y confundir ambas cosas tiene nombre propio: falacia de la falacia, o argumentum ad logicam. Detectar un error en un argumento muestra exactamente una cosa, que esa razón no sostiene la tesis, y deja la tesis sin apoyo por ese lado y en el mismo estado en que estaba antes. Un ejemplo aclara por qué importa: alguien puede defender que conviene vacunarse con una apelación a la autoridad mal construida, y la conclusión sigue siendo correcta por razones que ese hablante no dio. La consecuencia práctica es que después de nombrar la falacia todavía queda trabajo por hacer, y es el trabajo interesante: preguntar si existe un argumento mejor para la misma conclusión, y ofrecerlo si lo hay. Conviene además notar una asimetría que suele pasar inadvertida. En una discusión con reglas claras, quien afirma algo carga con la prueba, así que si su único argumento falla la afirmación vuelve a quedar sin respaldo y nadie está obligado a aceptarla; eso es muy distinto de haberla refutado, y no conviene celebrarlo como si lo fuera."},
   {q:"¿Por qué confiar en un experto no es siempre una falacia, y cómo se distingue la deferencia razonable del argumento de autoridad?", p:"Porque la alternativa es impracticable: ninguna persona puede verificar por su cuenta la farmacología de un medicamento, la datación de un manuscrito y el cálculo estructural de un puente, de modo que casi todo lo que sabemos lo sabemos por testimonio de alguien. Tratar eso como un error de razonamiento volvería irracional la vida entera. La versión defendible de la regla es condicional y conviene enseñarla así: la deferencia es legítima cuando quien habla es efectivamente especialista en ese campo, cuando lo que afirma pertenece a ese campo, cuando hay consenso entre los especialistas y no una controversia abierta, y cuando no tiene un interés decisivo en la afirmación. La falacia aparece en cuanto falta alguna de esas condiciones, y el caso más frecuente no es el charlatán sino el experto genuino hablando fuera de su terreno. Queda una dificultad honesta que vale la pena dejar planteada en clase: para juzgar si hay consenso entre especialistas hace falta un mínimo de competencia en el campo, de modo que la regla no elimina del todo la circularidad, solo la vuelve manejable. Lo que sí ofrece son indicadores accesibles a cualquiera: quién financia, si hubo revisión por pares, si quienes disienten son especialistas o no, y si la afirmación cambia según a quién se le hable."},
   {q:"¿Entrenar a alguien en detectar falacias mejora realmente su razonamiento, o solo le da un vocabulario nuevo para descalificar al que piensa distinto?", p:"Hay razones para las dos sospechas y conviene no elegir la cómoda. A favor del entrenamiento: el catálogo funciona como una lista de verificación, y las listas de verificación mejoran el desempeño en tareas donde el error es sistemático y previsible; además nombrar un error lo vuelve discutible, y una conversación sobre si esto es o no un hombre de paja tiene mucha mejor calidad que un intercambio de acusaciones de mala fe. En contra: está bien documentado en psicología del razonamiento que la instrucción en pensamiento crítico aumenta mucho más la habilidad para encontrar defectos en los argumentos ajenos que en los propios, de modo que el resultado puede ser un razonador motivado más eficaz y no un razonador más honesto. Y la experiencia de cualquier aula lo confirma: la frase eso es un ad hominem se usa más veces para terminar una conversación que para mejorarla. De ahí tres decisiones pedagógicas que este taller adopta y que conviene justificar ante los estudiantes: aplicar el catálogo primero sobre los textos propios, exigir siempre la reconstrucción caritativa antes de la objeción, y evaluar no la velocidad de etiquetado sino la calidad del argumento que se ofrece después."},
   {q:"¿Cuál es la diferencia entre una falacia y una heurística que funciona casi siempre?", p:"Una heurística es un atajo de razonamiento que sacrifica precisión a cambio de rapidez y que, en el entorno donde se formó, acierta la mayoría de las veces: creerle a quien parece saber, desconfiar de quien tiene algo que ganar, suponer que lo que vino después fue causado por lo anterior, generalizar a partir de los pocos casos que uno vio. Varias de las formas de esta lista son exactamente eso mismo visto desde el otro lado. La diferencia no está en la estructura del razonamiento sino en el contexto y en la exigencia: un atajo es aceptable cuando hay que decidir rápido, cuando el costo de equivocarse es bajo y cuando no hay información mejor disponible, y se vuelve falacia cuando se lo presenta como razón concluyente en una discusión donde sí se podía averiguar. Esta manera de verlo es la que adoptan los enfoques contemporáneos, sobre todo la pragmadialéctica, que define la falacia por la violación de las reglas de una discusión crítica y no por la forma del argumento. Tiene una consecuencia que conviene aceptar aunque incomode: no existe una lista de argumentos malos en sí mismos, y decidir si algo es una falacia exige mirar qué se estaba haciendo con él, cosa que ninguna etiqueta resuelve sola."},
   {q:"¿Hay casos en que atacar a la persona sea legítimo, o el ad hominem es siempre un error?", p:"Hay que distinguir tres situaciones que la etiqueta única confunde. Cuando alguien ofrece razones verificables, su biografía es irrelevante: un argumento válido no se vuelve inválido porque lo formule un hipócrita, y ahí el ad hominem es falaz sin atenuantes. Cuando alguien ofrece su testimonio — lo vi, lo medí, confíen en mí —, su credibilidad es precisamente lo que corresponde evaluar, y señalar un conflicto de intereses, un historial de falsificaciones o una incompetencia demostrada no es un ataque personal sino el trabajo que hay que hacer; los tribunales y el periodismo funcionan así y no cometen ninguna falacia al hacerlo. Y cuando lo que está en discusión es si alguien debe ocupar un cargo, recibir un premio o ser tomado como modelo, su conducta es directamente el tema y no un desvío. El tu quoque merece una nota aparte: no refuta nada, pero puede mostrar de manera válida que quien acusa no sostiene en serio el criterio que invoca, lo cual es información relevante sobre la discusión aunque no sobre la tesis. La regla práctica que resume todo esto es corta: preguntarse si lo que el otro puso sobre la mesa son razones o es su palabra."},
   {q:"Hamblin acusó a los manuales de repetir durante siglos un catálogo de falacias mal definido. ¿Sigue siendo útil enseñar la lista?", p:"La crítica de 1970 es dura y sigue en pie en buena parte. Hamblin mostró que el capítulo de falacias de los manuales de lógica se copiaba de manual en manual con ejemplos inventados, definiciones inconsistentes y sin ninguna teoría que las unificara, y señaló además un problema de fondo: si una falacia es un argumento que parece válido sin serlo, entonces parecer es una propiedad psicológica y relativa a quién mira, de modo que la categoría no se deja definir en términos estrictamente lógicos. La respuesta contemporánea no fue abandonar la lista sino cambiarle el estatuto. En lugar de un catálogo de formas prohibidas, las falacias se entienden hoy como nombres de maniobras frecuentes dentro de una discusión, evaluables por su función y no por su estructura, que es el giro de la pragmadialéctica. Con eso la lista conserva dos usos que ningún marco teórico reemplaza: sirve como vocabulario compartido, porque discutir si esto es un hombre de paja resulta más productivo que discutir si el otro es deshonesto, y sirve como lista de verificación sobre los propios borradores. Lo que ya no puede hacerse honestamente es enseñarla como un algoritmo que decide, caso por caso y sin mirar el contexto, qué argumentos son inaceptables."}
 ],
 cadena:{ titulo:"¿Es falaz confiar en el médico?", intro:"Un razonamiento en ramas sobre la falacia peor enseñada de la lista: la apelación a la autoridad. Si toda apelación a la autoridad fuera falaz, casi todo lo que sabemos sería falaz, porque casi todo lo sabemos por otros. Las ramas recorren cuándo una apelación es legítima, cuándo no, y la trampa de la falacia de la falacia.", inicio:"n1", nodos:{
   n1:{ pregunta:"«La médica me dijo que este medicamento es seguro para mí, así que lo voy a tomar.» ¿Es una falacia de apelación a la autoridad?", opciones:[
     {texto:"Sí: acepto algo porque lo dice una autoridad, no por las razones.", va:"n2a"},
     {texto:"Depende: hay autoridades pertinentes y apelaciones razonables.", va:"n2b"} ]},
   n2a:{ pregunta:"Si eso es falaz, también lo es creer lo que dice un libro de historia, un mapa o una enciclopedia: no verificaste nada de eso por tu cuenta. ¿Se puede vivir sin confiar en lo que saben otros?", opciones:[
     {texto:"Sí: hay que comprobar todo por uno mismo.", final:{tipo:"revisar", texto:"Es imposible, y no por pereza: nadie puede comprobar personalmente la química de un medicamento, la historia de la independencia y la forma de la Tierra. El conocimiento humano está dividido entre muchos, y confiar en quienes saben es una condición del conocimiento, no un defecto. La pregunta no es si confiar, sino en quién y cómo. Volvé un paso y probá la otra respuesta."}},
     {texto:"No: entonces el problema no es apelar a una autoridad, sino a cuál y de qué manera.", va:"n3a"} ]},
   n3a:{ pregunta:"¿Qué tiene que cumplir una apelación a la autoridad para ser razonable?", opciones:[
     {texto:"Que la persona sea experta en ese tema preciso, que los expertos no estén en desacuerdo importante, que no tenga un interés que sesgue su juicio y que la afirmación se pueda verificar en principio.", final:{tipo:"bien", texto:"Son, en lo esencial, las preguntas críticas que propuso el lógico Douglas Walton para el argumento por opinión experta. Con ellas, la apelación a la autoridad deja de ser una falacia automática y pasa a ser un argumento que se evalúa: vale si responde bien a las preguntas, y su conclusión es plausible, no definitiva."}},
     {texto:"Que la persona tenga títulos y prestigio.", final:{tipo:"revisar", texto:"Los títulos y el prestigio no bastan: un premio Nobel de física que opina sobre vacunas habla fuera de su campo, y un experto pagado por una empresa puede tener un interés en juego. La pertinencia importa más que la fama. Volvé un paso y probá la otra respuesta."}} ]},
   n2b:{ pregunta:"Si hay apelaciones razonables, ¿cuándo se vuelve falaz?", opciones:[
     {texto:"Cuando la autoridad habla fuera de su campo, o cuando se la usa para cerrar la discusión en lugar de dar razones.", va:"n3b"},
     {texto:"Nunca, si la persona es reconocida.", final:{tipo:"revisar", texto:"El reconocimiento no protege contra el error ni contra el abuso: los expertos se equivocan, opinan fuera de su campo y a veces tienen intereses. Una apelación es falaz cuando reemplaza las razones en lugar de resumirlas. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Alguien cita a un actor famoso para defender que el agua es esencial para la vida. El argumento es una mala apelación a la autoridad. ¿Es falsa, entonces, la conclusión?", opciones:[
     {texto:"No: el argumento era malo, pero la conclusión puede ser verdadera por otras razones.", final:{tipo:"bien", texto:"Evitaste la falacia de la falacia (argumentum ad logicam): concluir que algo es falso porque el argumento que lo defendía era falaz. Una falacia muestra que un argumento no prueba su conclusión, no que la conclusión sea falsa. Es la falacia más frecuente entre quienes acaban de aprender las demás."}},
     {texto:"Sí: si se apoyó en una falacia, la conclusión no vale.", final:{tipo:"revisar", texto:"Esa es justamente la falacia de la falacia. Que un argumento sea malo dice algo sobre el argumento, no sobre la verdad de su conclusión: el agua es esencial para la vida aunque lo diga un actor. Volvé un paso y probá la otra respuesta."}} ]}
 }},
 reconstruccion:[
   { titulo:"La apelación a la autoridad bien hecha (esquema de Walton)",
     consigna:"Reconstruí la forma legítima del argumento por opinión experta, tal como la sistematizó Douglas Walton. Una pieza es la versión falaz que se suele confundir con ella: dejala afuera.",
     piezas:[
       {id:"a1", texto:"E es experta en el campo D.", tipo:"premisa"},
       {id:"a2", texto:"E afirma que A es verdadero.", tipo:"premisa"},
       {id:"a3", texto:"A pertenece al campo D, no a otro.", tipo:"premisa"},
       {id:"a4", texto:"Los expertos de D no están en desacuerdo importante sobre A, y E no tiene un interés que sesgue su juicio.", tipo:"premisa"},
       {id:"a5", texto:"Por lo tanto, es razonable aceptar A como plausible, mientras no aparezcan razones en contra.", tipo:"conclusion"},
       {id:"ax", texto:"E es famosa y respetada en muchos campos.", tipo:"distractor"}
     ],
     ordenCorrecto:["a1","a2","a3","a4","a5"],
     explicacion:"La diferencia entre este esquema y la falacia está en a3 y a4: la autoridad tiene que ser pertinente y no tener un interés en juego, y el consenso entre expertos importa. El punto débil del esquema es a4, que en la práctica es difícil de verificar: ¿cómo sabe un lego si hay desacuerdo entre expertos o si alguien tiene un interés oculto? Notá también que la conclusión es revisable: el argumento hace plausible a A, no la demuestra. La pieza sobrante es la versión falaz: la fama o el respeto general no son pertinencia."},
   { titulo:"La pendiente resbaladiza legítima",
     consigna:"No toda advertencia sobre consecuencias futuras es una falacia. Reconstruí la versión legítima del argumento de la pendiente resbaladiza. Una pieza es la versión falaz: dejala afuera.",
     piezas:[
       {id:"s1", texto:"Si se adopta la medida A, se crea un precedente P.", tipo:"premisa"},
       {id:"s2", texto:"Hay un mecanismo identificable por el cual P facilita la medida B: por ejemplo, un incentivo institucional o un criterio legal que ya no podrá negarse.", tipo:"premisa"},
       {id:"s3", texto:"Hay evidencia de que ese mecanismo operó en casos comparables.", tipo:"premisa"},
       {id:"s4", texto:"B es claramente indeseable.", tipo:"premisa"},
       {id:"s5", texto:"Por lo tanto, hay una razón —no concluyente— contra A, que debe pesarse con los beneficios de A.", tipo:"conclusion"},
       {id:"sx", texto:"Si se adopta A, inevitablemente llegará B, después C, y al final la catástrofe.", tipo:"distractor"}
     ],
     ordenCorrecto:["s1","s2","s3","s4","s5"],
     explicacion:"La pendiente resbaladiza es falaz cuando afirma una cadena inevitable sin mostrar el mecanismo (la pieza sobrante). Es legítima cuando identifica cómo un paso facilita el siguiente (s2) y aporta evidencia de que eso ocurre (s3). El punto débil, incluso en la versión legítima, es s3: los casos comparables nunca son idénticos, y quien argumenta puede elegir solo los que le convienen, que es la falacia del francotirador. Notá también la conclusión modesta: una razón para pesar, no un veredicto."}
 ],
 dilemas:[
   { titulo:"El debate de los celulares",
     intro:"Hamblin y la escuela pragmadialéctica sostienen que una falacia no es solo un error lógico: es una jugada que viola las reglas de una discusión razonable. Este caso pone a prueba esa idea en un debate escolar, y también el riesgo de que los nombres de las falacias se usen como armas.",
     pasos:[
       { id:"p1", situacion:"Moderás un debate en tu curso sobre prohibir los celulares en clase. Andrea dice: «Si dejamos el celular en clase, después lo van a querer en los exámenes y al final nadie va a estudiar». Mateo responde: «Vos decís eso porque sos la nerd del curso». ¿Qué hacés?", opciones:[
         {texto:"Señalo las dos falacias por su nombre: pendiente resbaladiza y ad hominem.", consecuencia:"Es correcto, pero nombrar no es lo mismo que enseñar. Los dos pueden quedarse con la etiqueta y sin saber qué tendrían que hacer distinto. Además, la jugada de Mateo es más grave: ataca a una persona.", va:"p2"},
         {texto:"Freno solo a Mateo: el ataque personal no se permite. Lo de Andrea es una opinión.", consecuencia:"Protegiste a Andrea, que es lo urgente. Pero dejaste pasar su argumento, que también tiene un problema: afirma una cadena sin mostrar el mecanismo. Tratar con cuidado a una persona no exige dejar de examinar su argumento.", va:"p2"},
         {texto:"Freno el ataque y le pido a cada uno que reconstruya su argumento: a Andrea, que muestre cómo un paso lleva al otro; a Mateo, que responda a lo que Andrea dijo y no a quién es.", consecuencia:"Convertiste las falacias en tareas: a cada una le corresponde qué habría que hacer para que el argumento sea bueno. Es la idea de la pragmadialéctica: corregir la discusión, no castigar al que se equivocó.", va:"p2"} ]},
       { id:"p2", situacion:"Camila interviene: «Si el argumento de Andrea es una falacia, entonces la prohibición es una mala idea». Varios aplauden. ¿Qué respondés?", opciones:[
         {texto:"«Exacto, el argumento de Andrea cayó.»", consecuencia:"Cayó un argumento, no la conclusión. Camila cometió la falacia de la falacia: puede haber buenas razones para prohibir los celulares que Andrea no dio. Validar eso enseña a usar las falacias para ganar, no para pensar.", va:"p3"},
         {texto:"«Un argumento malo no vuelve falsa su conclusión. ¿Alguien tiene una razón mejor a favor o en contra de la prohibición?»", consecuencia:"Corregiste la falacia de la falacia y devolviste la discusión al problema. Es lo que las falacias deberían hacer: mejorar la discusión, no terminarla.", va:"p3"},
         {texto:"No digo nada para no frenar el debate.", consecuencia:"El debate sigue, pero el curso aprende que señalar una falacia alcanza para ganar. Es el uso más dañino de este taller: los nombres de las falacias como armas.", va:"p3"} ]},
       { id:"p3", situacion:"Al terminar, un estudiante te dice: «Ahora en todas las discusiones del grupo le gritamos “¡ad hominem!” a cualquiera». ¿Qué le respondés?", opciones:[
         {texto:"«Bien: así aprenden a detectarlas.»", consecuencia:"Detectar es el primer paso, pero gritar el nombre suele ser otra forma de no escuchar. Una acusación de falacia también es un argumento, y también puede ser equivocada: no toda mención de la persona es un ad hominem.", va:null},
         {texto:"«Nombrar una falacia es el comienzo, no el final: después hay que decir qué haría falta para que el argumento fuera bueno.»", consecuencia:"Es la lección de este taller: una falacia es una jugada que se puede corregir, y su nombre sirve para orientar la corrección, no para ganar.", va:null},
         {texto:"«Entonces mejor no enseño más falacias.»", consecuencia:"El problema no es saber nombrar falacias, sino usarlas como armas. Dejar de enseñarlas deja a los estudiantes sin herramientas frente a quienes sí las usan para manipular.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar por qué no toda apelación a la autoridad ni toda pendiente resbaladiza es falaz.",
       "Distinguí entre proteger a una persona de un ataque y dejar de examinar su argumento.",
       "Reconocí la falacia de la falacia: un argumento malo no vuelve falsa su conclusión.",
       "Convertí cada falacia en una tarea: qué habría que hacer para que el argumento fuera bueno.",
       "Pensé el riesgo de usar los nombres de las falacias como armas para ganar discusiones.",
       "Puedo explicar la idea pragmadialéctica de que una falacia viola las reglas de una discusión razonable.",
       "Formulé la objeción más fuerte: que en la vida real casi nadie argumenta con premisas explícitas, y aplicar este análisis puede volverse pedante."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.falacias = { lecturas:[
 {titulo:"Qué es una falacia: de las Refutaciones sofísticas al debate contemporáneo", fuente:"Stanford Encyclopedia of Philosophy — Fallacies", url:"https://plato.stanford.edu/entries/fallacies/",
  extracto:`La definición estándar dice que una falacia es un argumento que parece válido pero no lo es. Los dos componentes importan: si solo fuera inválido, sería un mal argumento cualquiera; lo que lo vuelve falacia es que engaña, que tiene apariencia de corrección. Por eso la lógica informal se ocupa tanto de por qué persuaden como de por qué fallan.

Aristóteles inaugura el estudio sistemático en Sobre las refutaciones sofísticas, que cierra los Tópicos. Allí distingue trece falacias y las divide en dos grupos. Las que dependen del lenguaje (in dictione) incluyen la equivocación —usar un término en dos sentidos dentro del mismo argumento—, la anfibolía (ambigüedad sintáctica), la composición y la división (atribuir al todo lo que vale para las partes, o al revés), el acento y la forma de la expresión. Las que no dependen del lenguaje (extra dictionem) incluyen el accidente, la confusión entre lo absoluto y lo relativo, la petición de principio, la falsa causa, la pregunta compleja y —la primera aparición registrada de lo que hoy llamamos ignoratio elenchi— probar algo distinto de lo que había que probar.

Aristóteles ya advierte algo que la tradición posterior a menudo olvida: los sofistas no engañan por casualidad, sino explotando ambigüedades reales del lenguaje natural. Estudiar falacias es, por eso, estudiar cómo funciona el lenguaje argumentativo.

La tradición latina medieval y moderna amplió el catálogo con nombres que siguen vigentes: ad hominem (atacar a la persona en vez del argumento), ad baculum (apelar a la amenaza), ad misericordiam (apelar a la lástima), ad populum (apelar a la opinión mayoritaria), ad verecundiam (apelar a una autoridad indebida) y ad ignorantiam (tomar la falta de prueba en contra como prueba a favor). Locke fue quien popularizó varias de estas etiquetas en el Ensayo sobre el entendimiento humano.

La discusión contemporánea introdujo un matiz importante: muchas de estas formas no son siempre falaces. Apelar a una autoridad puede ser perfectamente razonable si la autoridad es genuina, está en su campo y hay consenso entre expertos; se vuelve falacia cuando falta alguna de esas condiciones. El argumento ad hominem circunstancial —señalar el conflicto de interés de quien habla— puede ser legítimo en un contexto donde se evalúa credibilidad, aunque no refute el argumento en sí. La pendiente resbaladiza es falaz solo si no se muestra un mecanismo causal plausible entre el primer paso y el resultado extremo. Por eso los enfoques pragmadialécticos (Van Eemeren y Grootendorst) prefieren definir la falacia como una violación de las reglas de una discusión crítica orientada a resolver una diferencia de opinión, y no como una forma lógica defectuosa.

Ese giro tiene una consecuencia pedagógica valiosa: aprender falacias no debería reducirse a memorizar etiquetas para ganar discusiones. El uso más productivo es el inverso — aplicarlas primero a los propios argumentos, y usarlas para reconstruir la versión más fuerte de la posición contraria (el «principio de caridad») antes de criticarla. Nombrar una falacia no refuta una tesis: solo muestra que ese argumento concreto no la sostiene.`,
  comentario:"Este texto le da al taller su marco: la falacia no es simplemente un error lógico, es un error persuasivo, y por eso hay que estudiar por qué convence. La distinción aristotélica entre falacias del lenguaje y del razonamiento sigue siendo la mejor clasificación de partida. Y la advertencia final es la más importante para el aula: señalar una falacia muestra que ese argumento falla, no que la conclusión sea falsa — confundir ambas cosas es a su vez una falacia (la falacia de la falacia)."},
 {titulo:"Argumentación informal y falacias: una unidad didáctica para el aula", fuente:"INTEF — Instituto Nacional de Tecnologías Educativas y de Formación del Profesorado, Ministerio de Educación de España. Recursos educativos abiertos para Bachillerato", url:"https://descargas.intef.es/recursos_educativos/RED_ES/04_Bachillerato/1/B_1_061_2025_0917/argumentacin_informal_y_falacias.html",
  extracto:`Este material no es un tratado sino una unidad didáctica de cuatro sesiones publicada en abierto por el Ministerio de Educación de España, y vale la pena leerla precisamente por eso: muestra cómo se enseña hoy este contenido en un aula de secundaria hispanohablante, con qué recortes y con qué actividades. Su tesis de partida es la misma que organiza este taller, enunciada en una sola frase: argumentar bien no siempre significa seguir las reglas de la lógica, porque una buena parte de lo que nos convence a diario no pasa por la forma del razonamiento.

La distinción de base que propone es entre falacias formales, que son errores en la estructura de la inferencia, y falacias informales, que fallan por el contenido, por la ambigüedad del lenguaje o por una apelación emocional engañosa. Es una distinción antigua —remite a la división aristotélica entre las que dependen del lenguaje y las que no— y sigue siendo la puerta de entrada más económica, aunque no la más precisa: las discusiones contemporáneas muestran que la mayoría de los casos interesantes no son errores formales en absoluto.

El catálogo que efectivamente trabaja es corto y deliberadamente doméstico: el ad hominem, entendido como atacar a quien habla en lugar de a lo que dice; la apelación a la autoridad, es decir aceptar algo por el estatus de quien lo afirma; la falsa causalidad, que confunde la sucesión temporal con la causa; la falsa analogía, que compara casos que no son comparables en lo que importa; la apelación a la mayoría; y la manipulación emocional en sentido amplio. No busca exhaustividad: busca que el estudiante reconozca seis maniobras en el material que ya consume.

Lo más interesante para un docente está en las actividades y no en el listado. La unidad propone analizar discurso real —publicidad y redes sociales, no ejemplos de manual— y culmina en un debate de aula donde los estudiantes tienen que detectar y refutar falacias del otro equipo respetuosamente, con la exigencia explícita de que la refutación no degenere en descalificación. Esa condición no es un adorno pedagógico: es el reconocimiento práctico de que el catálogo puede usarse para pensar mejor o para no escuchar, y de que la diferencia entre las dos cosas hay que enseñarla aparte.`,
  comentario:"Conviene leer esta unidad junto al texto de la Stanford Encyclopedia y no en su lugar: una da el marco teórico y la historia del problema, la otra muestra el recorte que sobrevive cuando el contenido baja al aula. La comparación es en sí misma un ejercicio. Fijate en qué desaparece al simplificar —las condiciones que vuelven legítima la apelación a la autoridad, la advertencia sobre la falacia de la falacia— y preguntate si eso se puede reponer sin volver la unidad impracticable. La exigencia de refutar sin descalificar, en cambio, es el mejor aporte del material y coincide punto por punto con la regla que este taller adopta como criterio de trabajo."},
], preguntasLectura:[
 {q:"¿Qué dos componentes tiene la definición estándar de falacia?", opciones:["Que sea larga y confusa","Que sea inválida y que además parezca válida","Que sea falsa y que ofenda","Que sea antigua y conocida"], r:"Que sea inválida y que además parezca válida", why:"Sin la apariencia de corrección sería simplemente un mal argumento, no una falacia."},
 {q:"¿Cómo divide Aristóteles las falacias en las Refutaciones sofísticas?", opciones:["Formales e informales","Las que dependen del lenguaje (in dictione) y las que no (extra dictionem)","Graves y leves","Orales y escritas"], r:"Las que dependen del lenguaje (in dictione) y las que no (extra dictionem)", why:"Trece falacias en total: equivocación, anfibolía, composición, división, acento y forma de expresión en el primer grupo."},
 {q:"¿Cuándo NO es falaz apelar a una autoridad?", opciones:["Nunca: siempre es falacia","Cuando la autoridad es genuina, habla dentro de su campo y hay consenso entre expertos","Cuando la autoridad es famosa","Cuando nadie puede contradecirla"], r:"Cuando la autoridad es genuina, habla dentro de su campo y hay consenso entre expertos", why:"La discusión contemporánea muestra que varias formas «falaces» son razonables bajo ciertas condiciones."},
 {q:"Según la advertencia final del texto, ¿qué muestra nombrar una falacia?", opciones:["Que la conclusión del otro es falsa","Que ese argumento concreto no sostiene la tesis, no que la tesis sea falsa","Que uno ganó la discusión","Que el otro miente deliberadamente"], r:"Que ese argumento concreto no sostiene la tesis, no que la tesis sea falsa", why:"Confundir ambas cosas es la llamada «falacia de la falacia»."},
 {q:"¿Qué distinción de partida propone la unidad didáctica del INTEF?", opciones:["Entre falacias graves y leves","Entre falacias formales, que fallan en la estructura de la inferencia, e informales, que fallan por contenido, ambigüedad o apelación emocional","Entre falacias orales y escritas","Entre falacias antiguas y modernas"], r:"Entre falacias formales, que fallan en la estructura de la inferencia, e informales, que fallan por contenido, ambigüedad o apelación emocional", why:"Es la versión escolar de la división aristotélica entre las que dependen del lenguaje y las que no."},
 {q:"¿Con qué actividad culmina la unidad del INTEF, y qué condición le pone?", opciones:["Con un examen escrito de definiciones","Con un debate de aula donde hay que detectar y refutar falacias del otro equipo respetuosamente, sin que la refutación degenere en descalificación","Con la memorización del catálogo completo","Con una exposición del docente"], r:"Con un debate de aula donde hay que detectar y refutar falacias del otro equipo respetuosamente, sin que la refutación degenere en descalificación", why:"La condición no es un adorno: reconoce que el catálogo puede servir para pensar mejor o para no escuchar."}
]};
