/* ============================================================
   Ficha: confucio  ·  tradición: asiatica
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"confucio", trad:"asiatica", nombre:"Confucio (Kǒng Fūzǐ)", fechas:"551–479 a.C. · China", escuela:"Confucianismo", icon:"🏮", profundizada:true,
 tesis:"El desorden del mundo no se arregla con más leyes ni con más castigos, sino formando personas capaces de conducirse bien: el orden político es una consecuencia del orden moral, y el orden moral se cultiva. Confucio no inventa una doctrina nueva —se presenta como un transmisor que ama lo antiguo— sino que reinterpreta las formas heredadas dándoles un fundamento interior: el lǐ, el rito, deja de ser etiqueta aristocrática y se vuelve la disciplina concreta con la que se aprende el rén, la humanidad benevolente. El resultado es una ética que empieza en la casa, en la relación con los padres y los hermanos, y se extiende en círculos concéntricos hasta el gobierno; una ética donde el ideal, el junzi, no se hereda con la sangre sino que se conquista con años de práctica, y donde gobernar bien consiste sobre todo en ser el tipo de persona a la que otros quieren parecerse.",
 obras:[
   {t:"Analectas (Lúnyǔ)", d:"No es un libro escrito por Confucio sino un mosaico de unos quinientos fragmentos —dichos sueltos, preguntas de discípulos, escenas mínimas, anotaciones sobre su carácter— reunido por sus seguidores y por los seguidores de sus seguidores a lo largo de generaciones después de su muerte. Su forma desordenada es parte de su enseñanza: Confucio responde de manera distinta a cada discípulo sobre la misma virtud, porque lo que a cada uno le falta es distinto, y ese casuismo deliberado impide convertir sus respuestas en una fórmula. La filología moderna, desde los estudios de Bruce y Taeko Brooks hasta la discusión actual, sostiene que los libros centrales —aproximadamente del III al IX— son el estrato más antiguo y probablemente el más cercano a la voz histórica, mientras que otros capítulos reflejan debates posteriores de las escuelas confucianas rivales; conviene leerlo sabiendo eso, sin fingir que se escucha una grabación del maestro. Aun así, ningún otro texto de la tradición china fue leído, memorizado y comentado con tanta intensidad durante tanto tiempo."},
   {t:"Da Xue (El Gran Saber)", d:"Breve capítulo del Libro de los Ritos que el neoconfucianismo de Zhu Xi extrajo en el siglo XII y elevó, junto con el Zhong Yong, a la categoría de clásico fundamental y primera lectura obligatoria del estudiante. Su núcleo es una cadena de condiciones encadenadas, una de las estructuras argumentativas más citadas del pensamiento chino: investigar las cosas lleva a extender el conocimiento, que lleva a hacer sincera la intención, que lleva a rectificar la mente-corazón, que lleva a cultivar la propia persona, que lleva a ordenar la familia, que lleva a gobernar bien el Estado y finalmente a pacificar el mundo. La tesis política queda así incorporada a la tesis moral sin ninguna costura: desde el Hijo del Cielo hasta el hombre común, dice el texto, todos tienen el cultivo de la persona como raíz. Su atribución tradicional a un discípulo de Confucio es legendaria y la datación real lo sitúa bastante después; su importancia histórica, en cambio, es enorme, porque durante seis siglos fue la puerta de entrada al examen imperial."},
   {t:"Zhong Yong (La Doctrina del Medio)", d:"Otro capítulo del Libro de los Ritos convertido en clásico por Zhu Xi, atribuido por la tradición a Zisi, nieto de Confucio, y en realidad compuesto por capas de distintas épocas. Es el más metafísico de los cuatro libros y el que más incomoda a quien espera del confucianismo solo consejos de conducta: allí el equilibrio deja de ser una recomendación práctica y se vuelve un principio cósmico, porque quien alcanza la sinceridad plena (chéng) forma una tríada con el Cielo y la Tierra y participa en la transformación de las cosas. El medio del que habla no es una mediocridad cautelosa ni un cálculo de distancias, sino la justeza sin desviación en cada situación concreta, algo tan difícil que el texto afirma que casi nadie logra sostenerlo un mes entero. Leerlo junto a la Ética a Nicómaco es un ejercicio productivo y también engañoso: ambos hablan de un medio y ninguno de los dos lo entiende como promedio, pero el medio aristotélico se fija por la prudencia del individuo y el chino se apoya en un orden del Cielo que no se discute."},
   {t:"Chūnqiū (Anales de Primavera y Otoño)", d:"Crónica escuetísima del Estado de Lu entre 722 y 481 a.C., compuesta por entradas de pocas palabras que registran eclipses, guerras, alianzas, muertes y sacrificios. La tradición sostiene que Confucio la compiló o la editó y que lo hizo introduciendo un sistema de calificaciones morales encubiertas, eligiendo con extremo cuidado cada verbo: matar no es lo mismo que asesinar, y llamar a alguien por su título o negárselo equivalía a absolverlo o condenarlo. A esa técnica la tradición la llamó el estilo de la alabanza y la censura, y Mencio afirmaba que después de que Confucio terminara los Anales los ministros rebeldes y los hijos desnaturalizados sintieron miedo. La erudición contemporánea duda seriamente de esa autoría y sospecha que buena parte del sentido moral fue puesto allí por los comentarios posteriores, sobre todo por el Zuo Zhuan; lo que no está en duda es su efecto histórico, porque instaló la idea de que escribir historia es un acto moral y de que el historiador es una especie de tribunal diferido. El vínculo con la rectificación de los nombres es directo: nombrar correctamente lo que pasó ya es una forma de justicia."},
   {t:"Shījīng (Libro de las Odas)", d:"Antología de trescientos cinco poemas —canciones populares, odas cortesanas e himnos rituales— que Confucio no escribió pero que, según la tradición, seleccionó, ordenó y sobre todo enseñó, y que aparece citada en las Analectas más que ningún otro texto. Su uso pedagógico es lo que interesa: Confucio le dice a su hijo Boyu que quien no estudia las Odas queda como alguien parado de cara a una pared, y afirma que sirven para estimular el ánimo, para observar las costumbres, para convivir con otros, para expresar el resentimiento de manera aceptable y hasta para aprender los nombres de los pájaros y las plantas. Es decir, las trata como una educación sentimental y social completa, no como literatura de adorno: quien tiene poemas disponibles en la memoria tiene formas cultivadas de decir lo difícil. Y resume el conjunto con una fórmula célebre por su brevedad: trescientos poemas, y en una frase, pensamientos sin desviación. La atribución de la selección a Confucio es dudosa —la antología probablemente ya circulaba estabilizada—, pero su lectura de ellas fundó la manera china de leer poesía durante dos milenios."}
 ],
 conceptos:[
   {t:"Rén (benevolencia, humanidad)", d:"Es la virtud que organiza todas las demás y, significativamente, Confucio nunca la define. El carácter está compuesto por los signos de persona y de dos, de modo que ya en su escritura señala lo que ocurre entre seres humanos: no es una cualidad que se posea a solas sino una manera de estar con otros. A Fan Chi le responde con dos palabras, amar a los hombres; a Yan Yuan, su discípulo predilecto, le da una versión mucho más exigente, dominarse a uno mismo y volver a los ritos; a Zhong Gong le da la regla negativa de reciprocidad. Que las respuestas difieran no es descuido: el rén no es un contenido que se aprenda sino una disposición que se cultiva, y cada persona tiene delante un obstáculo distinto. Confucio es además extremadamente cauto al atribuirlo: se niega a decir de sus mejores discípulos que lo hayan alcanzado y llega a afirmar que nunca vio a nadie que amara el rén como se aman las cosas agradables. Al mismo tiempo lo declara cercanísimo: si lo deseo, dice, el rén ya está aquí. Esa doble condición —inalcanzable como logro, disponible en cada acto— es lo que lo distingue de una meta que pudiera tacharse de una lista."},
   {t:"Lǐ (rito, decoro, forma debida)", d:"Antes de Confucio, lǐ nombraba sobre todo el protocolo del sacrificio y la etiqueta de la nobleza. Su operación consiste en ampliarlo y en interiorizarlo: pasa a designar todo el repertorio de formas con que una comunidad hace visible el respeto, desde la ceremonia funeraria hasta el modo de saludar, de entregar un objeto con las dos manos, de sentarse, de guardar silencio. Su tesis fuerte es que la disposición interior no precede a la forma sino que se educa en ella: uno no se vuelve respetuoso y luego saluda bien, aprende el respeto practicando el saludo, igual que se aprende un oficio con las manos antes que con la cabeza. De ahí la analogía frecuente con la música y con el lenguaje, que también son formas heredadas que no elegimos y que sin embargo nos permiten decir cosas propias. Pero Confucio pone un límite explícito y durísimo a su propia doctrina: un hombre sin rén, pregunta, qué tiene que ver con los ritos, qué tiene que ver con la música. El rito vacío de benevolencia no es virtud sino cáscara; el rito reducido a jade y seda, dice, no merece el nombre de rito. Esa advertencia es la que separa su posición del formalismo con que sus críticos, desde Zhuangzi hasta hoy, suelen identificarla."},
   {t:"Xiào (piedad filial)", d:"Es la raíz del sistema, y conviene entender por qué. Confucio sostiene que la capacidad de considerar a otros no se enseña en abstracto: se aprende primero donde el vínculo ya existe, en el trato cotidiano con los padres y los hermanos mayores, y desde ahí se extiende hacia afuera. Por eso un discípulo afirma que quien es filial y fraterno rara vez será alguien que se rebele contra sus superiores, y por eso la familia funciona como la escuela primera de toda ética pública. Pero la piedad filial confuciana no es obediencia sin más, y este punto se pierde en casi todas las divulgaciones. Confucio observa que hasta los perros y los caballos reciben cuidado, de modo que alimentar a un padre sin reverencia no es xiào en absoluto: lo que se exige es una calidad de atención, y agrega que lo difícil es la expresión del rostro. Y admite el conflicto: dice expresamente que al servir a los padres hay que amonestarlos con suavidad cuando se equivocan, y si no escuchan, seguir siendo respetuoso sin abandonar la propia posición. La obligación filial y la rectitud pueden chocar, y el texto no lo disimula: en el episodio del hijo que denuncia al padre que robó una oveja, Confucio responde que la rectitud está en que el padre encubra al hijo y el hijo al padre — una respuesta que sigue siendo el punto más discutido de toda su ética."},
   {t:"Jūnzǐ (la persona ejemplar)", d:"La palabra significaba literalmente hijo de señor y designaba una condición de nacimiento. La operación de Confucio consiste en arrebatársela a la aristocracia y convertirla en un logro moral: junzi es quien se ha cultivado, venga de donde venga, y su opuesto, el xiaoren u hombre pequeño, tampoco es un pobre sino alguien de miras cortas. El desplazamiento es tan radical que funda la posibilidad misma de una meritocracia moral, y Confucio lo practicó aceptando discípulos sin fortuna a cambio de un atado de carne seca, diciendo que enseñaba sin distinción de clases. Sus rasgos se dan siempre por contraste y siempre en pares: el junzi entiende lo que es justo y el hombre pequeño lo que es provechoso; el junzi busca en sí mismo y el otro busca en los demás; el junzi es sereno sin ser arrogante; el junzi armoniza sin uniformarse y el hombre pequeño se uniforma sin armonizar. Ese último par es especialmente fino, porque distingue el acuerdo genuino de la conformidad. Hay que notar además que el junzi no es un santo desapegado: se cuida de la elegancia, de la conversación, de la música y de comer bien, porque la cultura (wén) y la sustancia (zhì) deben equilibrarse — sustancia sin cultura resulta tosca, cultura sin sustancia resulta de escribiente."},
   {t:"Zhèngmíng (la rectificación de los nombres)", d:"Cuando Zilu le pregunta qué haría primero si un gobernante le confiara la administración, Confucio contesta algo que al discípulo le parece absurdo: lo primero sería rectificar los nombres. Y despliega una cadena que se ha vuelto uno de los argumentos más citados sobre lenguaje y política: si los nombres no son correctos, el lenguaje no concuerda con la realidad; si no concuerda, los asuntos no llegan a término; si los asuntos no llegan a término, los ritos y la música no florecen; si no florecen, los castigos no dan en el blanco; y si los castigos no dan en el blanco, el pueblo no sabe dónde poner los pies ni las manos. En otro pasaje lo dice de manera aún más compacta: que el gobernante sea gobernante, el ministro ministro, el padre padre y el hijo hijo. La tesis no es que las palabras deban definirse mejor, sino que cada nombre de una función trae consigo un conjunto de obligaciones, y que llamar gobernante a quien no gobierna es el primer paso de la corrupción: el desorden empieza siendo semántico y termina siendo judicial. Su límite es evidente y vale discutirlo: quien fija el contenido de cada nombre tiene un poder enorme, y una doctrina así puede usarse tanto para exigirle al poderoso que esté a la altura de su título como para exigirle al subordinado que no salga del suyo."},
   {t:"Gobernar por la virtud (dé) y no por el castigo", d:"Es la tesis política central y está formulada en oposición explícita a lo que después será el legalismo. Quien gobierna con virtud, dice, es como la estrella polar, que permanece en su lugar mientras las demás estrellas se orientan hacia ella. Y el argumento decisivo compara dos métodos por sus efectos sobre el carácter de los gobernados: si guías al pueblo con decretos y lo ordenas con castigos, evitará el castigo pero perderá el sentido de la vergüenza; si lo guías con la virtud y lo ordenas con los ritos, tendrá vergüenza y además se corregirá por sí mismo. La diferencia entre un orden que solo produce obediencia y uno que produce autocorrección es todo el punto. De ahí también su metáfora del viento y la hierba: la virtud del gobernante es viento, la del pueblo hierba, y la hierba se inclina hacia donde sopla el viento. Y de ahí la respuesta a Ji Kangzi, que le pregunta si conviene ejecutar a los que no siguen el camino: para qué usar la muerte en el gobierno, si vos deseás el bien el pueblo será bueno. La objeción histórica es contundente: los Estados que efectivamente unificaron China lo hicieron con el método opuesto, y la dinastía Qin aplastó a los confucianos antes de que la Han los adoptara como fachada de una administración legalista."},
   {t:"Yì (rectitud, lo que corresponde hacer)", d:"Es el criterio que impide que el confucianismo se reduzca a seguir la costumbre. Yì nombra lo apropiado en sentido moral, lo que corresponde hacer en esta situación por ser lo correcto y no por ser lo conveniente, y su contrario permanente en el texto es lì, el provecho. De ahí el contraste que define al junzi: entiende lo que es justo, mientras el hombre pequeño entiende lo que le conviene. Su formulación más interesante aparece cuando Confucio dice que el junzi, frente al mundo, no está predispuesto a favor ni en contra de nada, y sigue lo que es apropiado — es decir, no aplica una regla fija sino que juzga cada caso. Eso hace del yì la pieza que vuelve flexible al sistema: cuando el rito heredado y lo que corresponde hacer entran en conflicto, Confucio acepta apartarse del rito, como cuando admite el cambio de un gorro ceremonial de lino por otro de seda por razones de economía, pero se niega a aceptar el cambio de la reverencia al pie de la escalera porque ese cambio expresaría arrogancia. Distinguir qué formas se pueden modificar y cuáles no es exactamente el trabajo del yì, y ninguna regla lo resuelve por adelantado."},
   {t:"Zhì (sabiduría práctica) y la honestidad sobre lo que no se sabe", d:"La sabiduría confuciana no es teórica ni contemplativa: consiste en conocer a las personas, en saber a quién elevar y a quién apartar, en reconocer las situaciones y saber qué hacer en ellas. Su primera regla es epistemológica y sorprendentemente severa: cuando sepas algo, sostener que lo sabés; cuando no lo sepas, admitir que no lo sabés — eso es saber. De ahí su reserva famosa ante lo que excede la experiencia: no habla de prodigios, de violencia, de desórdenes ni de espíritus, y cuando Zilu le pregunta cómo servir a los espíritus responde que si todavía no sabemos servir a los hombres cómo vamos a servir a los espíritus, y ante la pregunta por la muerte contesta que si aún no conocemos la vida cómo vamos a conocer la muerte. No es ateísmo ni escepticismo: es una disciplina de la atención que devuelve el foco a lo que está al alcance de la acción. Zhì incluye también el aprendizaje continuo, que Confucio describe como inseparable de la reflexión: aprender sin pensar es trabajo perdido, pensar sin aprender es peligroso. Y su descripción de la propia vida, que a los quince puso el corazón en el estudio, a los treinta se sostuvo firme, a los cuarenta dejó de tener dudas, a los cincuenta conoció el mandato del Cielo, a los sesenta tenía el oído dócil y a los setenta pudo seguir los deseos del corazón sin transgredir la norma, describe la sabiduría como un itinerario de décadas y no como un estado."},
   {t:"Shù (reciprocidad) y la regla de oro en negativo", d:"Cuando Zigong le pide una sola palabra que sirva de guía para toda la vida, Confucio responde shù, reciprocidad, y la explica de inmediato: lo que no desees para vos, no se lo impongas a los demás. Es la formulación más antigua registrada de la regla de oro y, decisivamente, está en negativo, lo que la diferencia del mandato cristiano de hacer a los demás lo que quisiéramos que nos hicieran. La diferencia no es retórica. La versión negativa es más modesta y probablemente más robusta: no supone que lo que yo deseo sea lo que el otro desea, y por eso no autoriza a imponerle mi idea del bien; se limita a poner un freno, que es algo que cualquiera puede cumplir en cualquier situación. La versión positiva, en cambio, ordena actuar y puede derivar con facilidad en paternalismo. Shù aparece además emparejada con zhōng, la lealtad o la entrega sincera al propio deber, y un discípulo resume el camino entero del maestro con esas dos palabras. Vale notar la tensión que esto abre dentro del propio sistema: una regla de reciprocidad es universal y simétrica —vale entre cualquiera y cualquiera—, mientras que las cinco relaciones confucianas son jerárquicas y asimétricas. Cómo conviven exactamente esas dos cosas es una de las discusiones más vivas del confucianismo contemporáneo."}
 ],
 conexion:"<b>Zhuangzi</b> y la tradición taoísta serán sus críticos más agudos: donde Confucio ve en el rito la forma que educa la humanidad, ellos ven un artificio que sustituye la espontaneidad y que aparece justamente cuando el Tao ya se perdió. En la otra dirección, <b>Wang Yangming</b>, casi dos mil años después, revitalizará el confucianismo insistiendo en que conocimiento moral y acción son inseparables y en que el principio no está en los textos ni en las cosas sino en la mente-corazón. Y su idea de que la virtud se adquiere por hábito y de que no hay regla que sustituya al juicio situado lo acerca de manera notable a <b>Aristóteles</b>, con una diferencia que conviene no borrar: el medio aristotélico lo determina la prudencia del individuo, mientras el confuciano se apoya en formas heredadas y en un orden del Cielo.",
 dialogo:{titulo:"El discípulo que quiere el atajo y el forastero que se ríe de los ritos", lineas:[
   {quien:"Discípulo", texto:"Maestro, quiero ser un junzi. Deme la regla. Si me dice exactamente qué hacer en cada caso, la sigo y termino antes."},
   {quien:"Confucio", texto:"Si te diera esa lista te volverías hábil en cumplirla, y eso es otra cosa. Yo transmito, no invento; y lo que transmito son formas que hay que habitar muchos años, no atajos."},
   {quien:"Discípulo", texto:"Pero usted mismo dijo que si uno desea el rén, el rén ya está aquí. Si está al alcance de la mano, ¿por qué tardaría años?"},
   {quien:"Confucio", texto:"Porque las dos cosas son verdaderas. Cada acto concreto está a tu alcance ahora mismo; el carácter que sostiene todos esos actos, no. Yo puse el corazón en el estudio a los quince y recién a los setenta pude seguir los deseos de mi corazón sin pasarme de la norma. No te estoy pidiendo paciencia: te estoy diciendo qué clase de cosa es esto."},
   {quien:"Discípulo", texto:"Entonces mientras tanto, ¿qué hago?"},
   {quien:"Confucio", texto:"Empezá donde el vínculo ya existe. Serví a tus padres, y no con comida: hasta a los caballos se los alimenta. Lo difícil es la expresión del rostro. Si podés sostener eso con tu padre, tal vez algún día puedas sostenerlo con un desconocido."},
   {quien:"Forastero", texto:"Perdón que interrumpa. Vengo escuchando y me da risa. Ustedes practican reverencias, ordenan las mangas, miden los pasos al entrar en una sala. ¿No se dan cuenta de que están fabricando marionetas educadas?"},
   {quien:"Confucio", texto:"Decime primero qué proponés en su lugar."},
   {quien:"Forastero", texto:"Que cada uno siga su naturaleza. Los pájaros no ensayan el vuelo. Si hace falta enseñar la benevolencia es porque ya se perdió: el rito aparece cuando el Tao se fue, como el bastón aparece cuando la pierna falla."},
   {quien:"Confucio", texto:"Ahí decimos lo mismo y sacamos conclusiones opuestas. Yo también creo que el rito aparece porque algo se perdió. Pero no tengo otra manera de recuperarlo que practicándolo. Tu naturaleza espontánea, ¿en qué lengua piensa? Alguien te la enseñó, y no por eso lo que decís es falso."},
   {quien:"Forastero", texto:"Una lengua sirve para decir lo que uno quiere. Una reverencia solo sirve para que el de arriba siga arriba."},
   {quien:"Confucio", texto:"Esa objeción sí me pesa, y no la voy a esquivar. Por eso pregunté alguna vez: un hombre sin rén, ¿qué tiene que ver con los ritos? Cuando digo rito no estoy hablando de jade y de seda; cuando digo música no estoy hablando de campanas y tambores. Un rito sin benevolencia adentro no es un rito débil: no es un rito.", nota:"Esta es la respuesta interna de Confucio al formalismo, y es real: las Analectas contienen su propia crítica del ritualismo vacío. Pero conviene no cerrar la discusión ahí. La objeción del forastero —una versión de la crítica taoísta que Zhuangzi y el Daodejing desarrollarán— señala algo que el criterio interior no resuelve: quién decide, desde afuera, si una reverencia determinada expresa respeto o solo reproduce una jerarquía."},
   {quien:"Discípulo", texto:"Maestro, si el rito puede vaciarse, deme al menos cómo se reconoce el vacío."},
   {quien:"Confucio", texto:"En el duelo prefiero el dolor sincero a la ceremonia perfecta. En el sacrificio, sacrificar como si los espíritus estuvieran presentes; si no estoy presente yo, es como si no hubiera sacrificado. El criterio no está en la forma ni contra la forma: está en si hay alguien adentro de ella."},
   {quien:"Forastero", texto:"Bonito. Y sin embargo dentro de unos siglos van a enseñar sus frases de memoria para aprobar exámenes y ascender en la burocracia."},
   {quien:"Confucio", texto:"Si eso pasa, no me defiendan con mi autoridad. Yo pasé la vida viajando de un Estado a otro sin que ningún príncipe me diera un cargo de verdad; un guardia de frontera me describió como el que sabe que no puede lograrlo y sin embargo lo sigue intentando. El que use mi nombre desde el trono tendrá que explicar esa parte también.", nota:"El pronóstico del forastero se cumplió. Bajo la dinastía Han, sobre todo desde Wu Di y con la formulación de Dong Zhongshu, el confucianismo fue adoptado como ortodoxia estatal, fusionado con cosmología de yin-yang y de las cinco fases, y convertido después en el temario del examen imperial que durante casi dos mil años seleccionó a los funcionarios. Ese confucianismo institucional —con sus tres vínculos jerárquicos que subordinan el ministro al soberano, el hijo al padre y la esposa al marido— es en buena medida una construcción posterior, y usarlo para juzgar al Confucio de las Analectas es tan injusto como usar las Analectas para absolverlo."}
 ]},
 actividades:[
   {t:"Auditoría de un nombre propio: zhengming aplicado a un rol tuyo", d:"Elegí un rol que ocupes y que puedas nombrar con una sola palabra: estudiante, docente, hijo, hija, hermano, amigo, vecino, jefe, colega. Escribí primero, sin mirar tu conducta, qué obligaciones trae ese nombre según vos: qué hace efectivamente alguien que merece ser llamado así. Anotá entre cinco y ocho obligaciones concretas y verificables, nada de adjetivos vagos. Después llevá durante una semana un registro honesto de lo que hiciste en ese rol, con fechas y hechos. Al terminar, compará las dos listas y respondé tres preguntas por escrito. Primera: en qué puntos exactos el nombre y la conducta no coinciden. Segunda, y es la más incómoda: cuando aparece una brecha, ¿corresponde cambiar la conducta para que esté a la altura del nombre, o corresponde admitir que el nombre estaba mal puesto? Tercera: quién definió esas obligaciones —vos, tu familia, una costumbre, una institución— y qué pasa si no estás de acuerdo con esa definición. Esta última pregunta es donde se juega el límite político de la doctrina, porque quien fija el contenido de los nombres tiene el poder de decidir qué se le puede exigir a cada uno."},
   {t:"Probar la regla negativa contra un caso real reciente", d:"Buscá en tu memoria una situación concreta de las últimas semanas en la que hayas tenido poder sobre alguien, aunque fuera pequeño: pusiste una nota, diste una instrucción, decidiste por un hijo, dejaste a alguien esperando, elegiste no responder un mensaje. Escribí el episodio en diez líneas, con hechos y sin justificaciones. Después pasalo por las dos versiones de la regla de oro, por separado y por escrito. La confuciana, en negativo: lo que no desees para vos no se lo impongas a otro. ¿Qué habría cambiado si la aplicabas? La cristiana, en positivo: hacé a los demás lo que quisieras que te hicieran. ¿Da el mismo resultado? Terminá con la comparación filosófica, que es el objetivo real del ejercicio: buscá un caso —propio o imaginado— donde la versión positiva conduzca a imponerle a alguien un bien que esa persona no quiere, y donde la negativa lo evite. Después buscá el caso inverso, donde la regla negativa resulte demasiado pasiva y no baste para obligar a ayudar. El resultado no es que una gane: es entender exactamente qué hace cada una."},
   {t:"Una semana de lǐ observado: qué hacen realmente los pequeños ritos", d:"Durante siete días anotá todos los micro-rituales que atraviesen tu vida, sin filtrar por importancia: saludar al entrar, dar la mano, esperar a que todos se sienten antes de empezar a comer, pasar lista, la fórmula con que abrís un correo, apagar el teléfono en una reunión, pedir permiso para interrumpir, el modo de despedirte de tu familia. Anotá cada uno con tres datos: qué hiciste exactamente, qué habría pasado si lo omitías, y qué sentiste al hacerlo. Al octavo día elegí dos de esos ritos y hacé el experimento de omitirlos deliberadamente durante un día, en contextos donde eso no dañe a nadie, y registrá la reacción ajena y la tuya. Cerrá con dos páginas de análisis. La primera, a favor de Confucio: mostrá con tus propios datos qué hacen esas formas que no podría hacer una intención privada, y si alguna te formó una disposición que antes no tenías. La segunda, a favor del forastero taoísta: identificá al menos un rito de tu lista que no produzca ninguna virtud y que solo sostenga una jerarquía o un trámite, y argumentá por qué. La conclusión honesta casi nunca es que Confucio tenía razón en todo ni que no tenía ninguna."}
 ],
 cuestionario:[
   {q:"Una ética construida sobre roles fijos y relaciones jerárquicas, ¿puede ser otra cosa que conservadora, y no es opresiva para quien ocupa la posición subordinada?", p:"Hay que separar lo que dicen las Analectas de lo que hizo con ellas la historia. En el texto, la reciprocidad de las obligaciones es real: el padre debe ser padre tanto como el hijo debe ser hijo, un gobernante que no gobierna pierde el derecho al nombre, y Mencio llevará esa lógica hasta autorizar el derrocamiento del tirano, que ya no es un soberano sino un simple individuo. Además Confucio ordena amonestar al padre que se equivoca y niega que la obediencia baste. Pero la asimetría también es real y no se disuelve: las obligaciones del superior no son exigibles del mismo modo que las del inferior, no hay ninguna institución que las haga cumplir, y las mujeres quedan prácticamente fuera del sistema de cultivo, con un pasaje sobre las mujeres y los sirvientes que ningún lector honesto puede presentar como accidental. La versión imperial de los tres vínculos endureció todo esto hasta volverlo un aparato de subordinación. El debate contemporáneo —con autores como Tu Weiming, Chenyang Li o las lecturas confuciano-feministas— discute justamente si la jerarquía es separable del núcleo relacional de la ética, o si el confucianismo solo sobrevive volviéndose otra cosa."},
   {q:"Si la virtud se aprende practicando formas heredadas, ¿cómo se distingue a alguien virtuoso de alguien que simplemente cumple bien con la costumbre?", p:"Confucio previó la objeción y le dio un nombre: llamó al hombre de la aldea que agrada a todos el ladrón de la virtud, porque tiene todas las apariencias y ningún centro. Sus criterios son tres. El primero es la prioridad del contenido sobre la forma: en el duelo prefiere el dolor sincero a la ceremonia impecable, y sostiene que sacrificar sin estar presente equivale a no haber sacrificado. El segundo es el yì, la rectitud, que obliga a juzgar cada situación y por tanto a apartarse del rito cuando corresponde. El tercero es el contraste entre armonizar sin uniformarse y uniformarse sin armonía, que separa el acuerdo genuino de la conformidad. El problema es que los tres criterios son internos y el observador externo no tiene acceso a ellos: desde afuera, el hipócrita competente y el virtuoso hacen exactamente lo mismo. Kant tendría aquí una ventaja aparente, porque su criterio también es interno pero al menos es formulable como prueba; y Aristóteles compartiría el problema entero, ya que también hace depender el juicio del hombre prudente. Quizá la respuesta más sólida sea temporal: la costumbre sostenida sin centro se rompe cuando cuesta algo, y la virtud no."},
   {q:"Zhuangzi y el Daodejing sostienen que la benevolencia enseñada es señal de que el Tao se perdió, y que el rito fabrica conformismo en lugar de espontaneidad. ¿Quién tiene razón?", p:"La crítica taoísta es la objeción más fuerte que recibió el confucianismo y su fuerza está en el argumento del síntoma: cuando hay que predicar la benevolencia es porque ya no la hay, igual que nadie recomienda respirar. El Daodejing lo formula como una cascada de degradación —perdido el Tao aparece la virtud, perdida la virtud la benevolencia, perdida la benevolencia la rectitud, perdida la rectitud el rito, y el rito es la delgada corteza de la lealtad y el comienzo del desorden—, y Zhuangzi agrega la burla contra quienes miden los pasos mientras el mundo arde. La defensa confuciana tiene dos movimientos. El primero es conceder la premisa y rechazar la conclusión: sí, el rito aparece porque algo se perdió, pero no hay otro camino de vuelta que practicarlo. El segundo es preguntar qué es exactamente la espontaneidad invocada, dado que también la lengua materna, el gusto y el gesto son aprendidos, de modo que la alternativa no sería naturaleza contra cultura sino una cultura que se desconoce a sí misma. Quien quiera decidir la disputa tiene que responder algo concreto: ¿existe alguna disposición moral que se haya adquirido sin práctica alguna?"},
   {q:"Confucio dice que la rectitud está en que el padre encubra al hijo y el hijo al padre. ¿Es eso compatible con la justicia?", p:"El episodio es real y conocido: el gobernador de She presume de un súbdito tan recto que denunció a su propio padre por robar una oveja, y Confucio responde que entre los suyos la rectitud es otra cosa, y que consiste en que el padre encubra al hijo y el hijo al padre. La defensa más habitual sostiene que sin lealtades particulares no se forma ninguna capacidad moral, que una justicia que exige delatar a los propios destruye la fuente misma de la consideración por otros, y que la mayoría de los sistemas jurídicos modernos reconocen algo parecido al eximir a los familiares del deber de declarar. La objeción es igual de seria: una moral que privilegia el vínculo de sangre puede degenerar en nepotismo y corrupción, y esa acusación fue el centro de un debate muy áspero en la filosofía china contemporánea, con Liu Qingping sosteniendo que aquí está la raíz cultural del favoritismo y Guo Qiyong y otros defendiendo que la lealtad familiar está subordinada al yì. Vale además comparar el caso con el Eutifrón, donde Platón pone a un hijo denunciando al padre y lo trata como un problema filosófico y no como un mérito. La pregunta que hay que responder no es si la familia importa, sino qué debe ceder cuando el vínculo y la justicia se excluyen."},
   {q:"¿Hasta qué punto podemos distinguir lo que Confucio pensó de lo que dos mil años de ortodoxia estatal le hicieron decir?", p:"No del todo, y esa es la respuesta honesta. Hay dos capas de distorsión. La primera es textual: las Analectas se compilaron a lo largo de generaciones, la crítica filológica distingue estratos —los libros centrales suelen considerarse los más antiguos, otros reflejan polémicas posteriores entre escuelas— y ni siquiera existe un texto único, ya que las versiones de Lu y de Qi diferían. La segunda es política: bajo la dinastía Han, con Dong Zhongshu, el confucianismo fue adoptado como ortodoxia imperial, mezclado con cosmología de yin-yang y cinco fases, y codificado en los tres vínculos jerárquicos, que en las Analectas no aparecen con esa rigidez; después se volvió el temario del examen imperial y, por tanto, el lenguaje obligatorio de la carrera burocrática durante casi dos mil años. Ese Confucio institucional es el que atacaron el Movimiento del Cuatro de Mayo en 1919 y la campaña de crítica a Confucio de los años setenta, y es también el que el Estado chino actual reivindica en clave de armonía y estabilidad. Frente a eso caben dos actitudes malas y una buena: tratar todo uso posterior como traición y quedarse con un Confucio puro e inexistente; o juzgar al texto por sus usos y ahorrarse la lectura. La tercera es leer las Analectas con las capas a la vista, preguntando en cada pasaje qué ofreció resistencia al uso autoritario y qué no."}
 ],
 cadena:{ titulo:"¿Puede haber rito sin humanidad?", intro:"Un razonamiento en ramas sobre la pregunta que el forastero del diálogo le lanza a Confucio: si el rito puede practicarse sin rén, ¿no es solo una forma vacía? Las ramas recorren pasajes reales de las Analectas (3.3, 12.1, 9.3, 14.24, 17.13) y desembocan en distintas respuestas confucianas, y en una que ya es taoísta.", inicio:"n1", nodos:{
   n1:{ pregunta:"Tu vecino cumple impecablemente con todos los ritos: visita a sus padres en cada fiesta, saluda con la reverencia exacta, guardó el luto el tiempo debido. Pero todo el barrio sabe que desprecia a sus padres y que lo hace por reputación. ¿Qué diría Confucio de esos ritos?", opciones:[
     {texto:"Que no son ritos: «un hombre sin rén, ¿qué tiene que ver con los ritos?» (3.3).", va:"n2a"},
     {texto:"Que aun así valen algo: la forma puede ir educando lo que todavía no está.", va:"n2b"} ]},
   n2a:{ pregunta:"Entonces el rén es lo que le da valor al rito. Pero cuando Yan Hui le pregunta por el rén, Confucio responde: «dominarse a uno mismo y volver al rito es rén», y detalla: no mirar, no escuchar, no hablar y no moverse contra el rito (12.1). El rén se define por el rito y el rito vale por el rén. ¿Es circular?", opciones:[
     {texto:"Sí: no hay punto de apoyo, y la doctrina no puede explicar ninguna de las dos cosas.", final:{tipo:"revisar", texto:"La observación es aguda, pero fijate qué clase de círculo es. Aristóteles tiene el mismo: nos volvemos justos haciendo actos justos, y un acto es justo cuando se hace como lo haría el justo. Ninguno de los dos pretende definir una cosa por la otra en el vacío: describen un proceso de formación en el que práctica y disposición crecen juntas. Un círculo de ese tipo es un problema si se busca una definición, no si se describe un aprendizaje. Volvé un paso y probá la otra respuesta."}},
     {texto:"No es un círculo vicioso: es un círculo de formación, como en un oficio; la forma entrena la disposición y la disposición anima la forma.", va:"n3a"} ]},
   n3a:{ pregunta:"Si la forma entrena la disposición, desde afuera el que ya tiene rén y el que solo imita bien hacen lo mismo. ¿Cómo se los distingue?", opciones:[
     {texto:"No se los distingue del todo, y por eso Confucio desconfía del que agrada a todos: el «hombre respetable de la aldea» es el ladrón de la virtud (17.13).", final:{tipo:"bien", texto:"Es un pasaje durísimo y exacto: el xiangyuan tiene todas las apariencias de la virtud y ningún centro, y por eso es peor que el que falla abiertamente, porque falsifica el modelo. Mencio lo desarrolla después: no se le encuentra falta que reprochar, y sin embargo no se puede entrar con él en el camino de Yao y Shun. Llegaste a la admisión de que los criterios confucianos son en parte internos. El costo es que el observador externo queda sin prueba segura; la ganancia es que la doctrina no confunde conformidad con virtud."}},
     {texto:"Por los momentos en que el rito cuesta algo, o en que la rectitud (yì) pide apartarse de él.", final:{tipo:"bien", texto:"Hay un pasaje que lo muestra con precisión (9.3): Confucio acepta que el gorro ceremonial de lino se reemplace por uno de seda, más barato, y sigue a la mayoría; pero se niega a aceptar que la reverencia se haga arriba del estrado en lugar de abajo, aunque todos lo hagan, porque eso expresa arrogancia. El que solo imita sigue a la mayoría en los dos casos; el que tiene rén sabe cuál forma protege algo y cuál no. Ese discernimiento no se copia, y se ve justamente cuando cuesta."}} ]},
   n2b:{ pregunta:"Es la apuesta de toda pedagogía ritual. Pero pensá en el caso: tu vecino practica hace veinte años y nada cambió por dentro. ¿Qué te dice eso?", opciones:[
     {texto:"Que la forma sola no forma: hace falta aprender y además reflexionar sobre lo aprendido (2.15).", va:"n3b"},
     {texto:"Que la teoría falla: si veinte años de rito no producen benevolencia, el rito es solo la corteza delgada de la lealtad, como dice el Dao De Jing (38).", final:{tipo:"bien", texto:"Llegaste a la crítica taoísta, y no es una salida equivocada: es la objeción más fuerte que recibió el confucianismo. Pero un confuciano te contestaría con un pasaje preciso: «los antiguos aprendían para sí mismos; los de hoy aprenden para los demás» (14.24). Tu vecino practica para ser visto, y el rito practicado para otros no forma a nadie. Que el caso no pruebe contra Confucio no significa que pruebe a su favor: la pregunta de fondo, si hay virtudes que se adquieren sin ninguna práctica, queda abierta entre las dos escuelas."}} ]},
   n3b:{ pregunta:"Si hace falta reflexión, ¿sobre qué exactamente tendría que reflexionar tu vecino?", opciones:[
     {texto:"Sobre para quién practica: Confucio distingue entre aprender para uno mismo y aprender para los demás (14.24).", final:{tipo:"bien", texto:"Es el diagnóstico más confuciano posible. El problema del vecino no es el rito sino la dirección de su práctica: la hace hacia afuera, para la reputación, y por eso la forma nunca vuelve sobre él. Confucio no le pediría que abandone los ritos, sino que los practique sin público, que es exactamente lo que hace imposible practicarlos por reputación. Notá que esta respuesta no refuta al forastero del diálogo: le concede que el rito puede vaciarse y localiza el vacío en quien lo practica."}},
     {texto:"Sobre si los ritos de su época son los correctos: tal vez sus formas están vacías porque son malas formas.", final:{tipo:"bien", texto:"Es una pregunta que el propio texto permite: Confucio prefiere en los ritos la austeridad a la ostentación, y en el duelo el dolor a la ceremonia minuciosa (3.4), y en 9.3 acepta modificar una forma. Pero también se presenta como alguien que transmite y no inventa (7.1), y nunca ofrece un criterio general para saber qué ritos cambiar. Esa ausencia es la que los moístas aprovecharon al atacar el luto de tres años como despilfarro. Llegaste al punto donde el confucianismo necesita una teoría de la reforma que las Analectas no dan."}} ]}
 }},
 reconstruccion:[
   { titulo:"La rectificación de los nombres (Analectas 13.3)",
     consigna:"Reconstruí la cadena con la que Confucio le explica a Zilu por qué lo primero en el gobierno sería rectificar los nombres. Una pieza pertenece a otro pasaje sobre el gobierno: dejala afuera y ordená el resto.",
     piezas:[
       {id:"c1", texto:"Zilu pregunta qué haría primero el maestro si el señor de Wei le confiara el gobierno; Confucio responde que rectificaría los nombres, y Zilu le dice que eso es irse por las ramas.", tipo:"premisa"},
       {id:"c2", texto:"Si los nombres no son correctos, el lenguaje no concuerda con las cosas; y si el lenguaje no concuerda, los asuntos no se llevan a término.", tipo:"premisa"},
       {id:"c3", texto:"Si los asuntos no se llevan a término, los ritos y la música no florecen; y si los ritos y la música no florecen, los castigos no dan en el blanco.", tipo:"premisa"},
       {id:"c4", texto:"Y si los castigos no dan en el blanco, el pueblo no sabe dónde poner los pies ni las manos.", tipo:"premisa"},
       {id:"c5", texto:"Por lo tanto, el junzi se asegura de que los nombres que usa puedan decirse, y de que lo que dice pueda hacerse: en sus palabras no admite nada descuidado.", tipo:"conclusion"},
       {id:"cx", texto:"La virtud del gobernante es como el viento y la del pueblo como la hierba: cuando el viento sopla sobre la hierba, la hierba se inclina.", tipo:"distractor"}
     ],
     ordenCorrecto:["c1","c2","c3","c4","c5"],
     explicacion:"El argumento es una cadena de condiciones que va del lenguaje a la justicia penal: un desajuste semántico (c2) impide la acción coordinada, sin acción coordinada no hay orden ritual, sin orden ritual los castigos se vuelven arbitrarios (c3), y la arbitrariedad deja al pueblo sin saber a qué atenerse (c4). La objeción de Zilu en c1 no es decorativa: expresa la sospecha, todavía viva, de que ocuparse de palabras es evadir los problemas reales. El contexto que la tradición le atribuye lo vuelve concreto: en Wei gobernaba un príncipe que se había quedado con el trono contra su propio padre, de modo que «padre», «hijo» y «señor» ya no nombraban lo que debían (compárese 12.11: que el padre sea padre y el hijo, hijo). La pieza sobrante es de 12.19: también trata del gobierno, pero por la fuerza del ejemplo, no por la corrección del lenguaje. Para discutir: quien fija qué obligaciones trae cada nombre tiene un poder enorme, y la doctrina sirve tanto para exigirle al poderoso que esté a la altura de su título como para exigirle al subordinado que no salga del suyo."},
   { titulo:"Gobernar con la virtud y no con el castigo (Analectas 2.3)",
     consigna:"Reconstruí el argumento que compara dos maneras de gobernar por sus efectos sobre el carácter de los gobernados. Una pieza viene de la escuela rival: dejala afuera.",
     piezas:[
       {id:"g1", texto:"Si se guía al pueblo con decretos y se lo ordena con castigos, el pueblo procurará evitar el castigo.", tipo:"premisa"},
       {id:"g2", texto:"Pero evitar el castigo no es rechazar la falta: quien solo teme la pena hará lo que pueda hacer sin ser visto, y no sentirá vergüenza.", tipo:"premisa"},
       {id:"g3", texto:"Si en cambio se lo guía con la virtud y se lo ordena con los ritos, el pueblo aprende a sentir vergüenza de la falta misma.", tipo:"premisa"},
       {id:"g4", texto:"Y quien siente vergüenza no necesita vigilancia constante: se corrige a sí mismo.", tipo:"premisa"},
       {id:"g5", texto:"Por lo tanto, gobernar con la virtud y los ritos produce un orden más firme que gobernar con decretos y castigos, porque forma a los gobernados en lugar de solo contenerlos.", tipo:"conclusion"},
       {id:"gx", texto:"Y como el pueblo teme el castigo más de lo que ama la virtud, conviene que las penas sean graves y seguras: el temor bien administrado vuelve innecesaria la virtud.", tipo:"distractor"}
     ],
     ordenCorrecto:["g1","g2","g3","g4","g5"],
     explicacion:"El pasaje original es muy comprimido —guiados por decretos y castigos, el pueblo los evita y no tiene vergüenza; guiados por la virtud y los ritos, tiene vergüenza y además se corrige—, y g2 y g4 hacen explícito lo que el texto deja implícito. La clave es la vergüenza (chǐ): un orden sostenido por el miedo necesita vigilancia infinita, porque nadie interioriza la norma; uno sostenido por la vergüenza se reproduce solo. La pieza sobrante resume la posición legalista, que Han Fei desarrollará dos siglos después y que la dinastía Qin aplicó con éxito militar indiscutible. Ese dato es la mejor objeción a g5: el método que Confucio consideraba inferior fue el que efectivamente unificó China. Para discutir: ¿son excluyentes los dos métodos, o toda sociedad real combina ley y formación del carácter, y la pregunta es cuál sostiene a cuál?"}
 ],
 dilemas:[
   { titulo:"El paquete de la vecina",
     intro:"El pasaje es real (Analectas 13.18): el gobernador de She presume de un súbdito tan recto que denunció a su propio padre por quedarse con una oveja; Confucio responde que entre los suyos la rectitud es otra cosa: el padre encubre al hijo, el hijo encubre al padre, y en eso está la rectitud. Este caso traslada la escena a hoy y le agrega algo que el pasaje no tiene: un tercero inocente que paga.",
     pasos:[
       { id:"p1", situacion:"Un paquete con una tablet dirigido a la vecina llegó por error a tu casa, y tu padre se lo quedó. La empresa de envíos culpa al repartidor, Julián, y lo amenaza con descontarle el valor del sueldo. Una inspectora de la empresa recorre el barrio preguntando, y te pregunta a vos. ¿Qué hacés?", opciones:[
         {texto:"Le digo la verdad: el paquete lo tiene mi padre.", consecuencia:"Es lo que el gobernador de She llamaría rectitud, y Confucio no. Notá que el verbo del pasaje es «dar testimonio contra»: el problema no es que el hijo sepa, sino que se vuelva testigo contra su padre. Hay también un detalle filológico que conviene saber: varios comentaristas entienden que el padre no robó la oveja sino que se quedó con una que se metió en su corral, un caso muy parecido al tuyo.", va:"p2a"},
         {texto:"No le digo nada a la inspectora, y esa misma noche hablo con mi padre.", consecuencia:"Es la combinación más cercana a las Analectas: no declarar contra el padre (13.18) y amonestarlo con suavidad (4.18). Callar no es lo mismo que aprobar, y el texto confuciano nunca dice que el hijo deba estar de acuerdo con lo que el padre hizo.", va:"p2b"},
         {texto:"Le miento: «No sé nada de ningún paquete».", consecuencia:"Aquí conviene ser precisos con el texto: el verbo de 13.18, yǐn, significa ocultar, no declarar; no dice fabricar una versión falsa. Muchos lectores confucianos distinguen entre callar sobre un pariente y mentir activamente, que daña la confianza (xìn) que Confucio también exige. Protegiste a tu padre, pero con una herramienta que el pasaje no te da.", va:"p2b"} ]},
       { id:"p2a", situacion:"Tu padre devuelve la tablet y paga una multa, pero no te habla durante semanas. Tu madre te dice: «A un padre no se lo entrega». Julián conserva su trabajo. ¿Cómo evaluás lo que hiciste?", opciones:[
         {texto:"Hice lo justo: Julián era inocente y no tenía por qué pagar por mi padre.", consecuencia:"Es un argumento que el pasaje de las Analectas no enfrenta, porque en la historia de la oveja nadie más carga con la culpa. El Mencio sí enfrenta algo parecido (7A35): si el padre del emperador Shun matara a alguien, el juez debería arrestarlo y Shun no tendría derecho a impedirlo; lo que haría es abandonar el imperio y huir con su padre a cuestas. La tradición confuciana, en su mejor versión, no pide que otro pague por los tuyos.", va:"p3"},
         {texto:"Tuve razón en lo que buscaba y me equivoqué en el orden: tendría que haber hablado primero con él.", consecuencia:"Es una autocrítica confuciana en sentido estricto: no te reprochás el resultado sino haber saltado un paso. La amonestación suave (4.18) le daba a tu padre la posibilidad de reparar él mismo, que es distinto de ser expuesto.", va:"p3"} ]},
       { id:"p2b", situacion:"Hablás con tu padre. Se enoja: «Esa empresa es enorme, no les va a pasar nada. Y la vecina nunca nos saludó». No menciona a Julián. ¿Qué hacés?", opciones:[
         {texto:"Insisto con respeto, una y otra vez, y le pido que la devuelva él mismo.", consecuencia:"Es casi literalmente 4.18: al servir a los padres, amonestarlos con suavidad; si no escuchan, seguir siendo respetuoso sin desistir, y esforzarse sin resentimiento. El pasaje tiene una ambigüedad famosa —si «no oponerse» significa no desobedecer al padre o no abandonar el propio propósito—, y tu insistencia elige la segunda lectura.", va:"p3"},
         {texto:"Si no la devuelve, la devuelvo yo en secreto, sin denunciarlo.", consecuencia:"Encontraste una salida que protege a Julián sin volverte testigo contra tu padre, y muchos la considerarían la más sabia. Pero notá su costo desde el texto: actuás a espaldas de tu padre y contra su voluntad expresa. El yì puede exigirlo; el xiào lo resiente. Es un caso donde las dos virtudes no se armonizan del todo.", va:"p3"} ]},
       { id:"p3", situacion:"Semanas después, en clase, alguien dice: «Confucio justifica el nepotismo: con 13.18 se puede encubrir toda la corrupción familiar». ¿Qué respondés?", opciones:[
         {texto:"«Tiene razón: una ética que pone la familia antes que la justicia es la raíz del favoritismo.»", consecuencia:"Es la posición que Liu Qingping defendió en un debate muy áspero de la filosofía china de los años 2000. Tiene fuerza histórica real. Su riesgo es leer 13.18 como si dijera más de lo que dice: no autoriza a hacer pagar a un tercero ni a mentir ante un tribunal.", va:null},
         {texto:"«No: 13.18 habla de no declarar contra el padre, no de dejar que otro pague, y el Mencio muestra que ni el emperador puede impedir que se haga justicia con su padre.»", consecuencia:"Es la línea de Guo Qiyong y otros defensores, que subordinan la lealtad familiar al yì. Su punto débil está en el propio Mencio: Shun no impide el arresto, pero después ayuda a su padre a escapar, y eso también es sustraerlo a la justicia.", va:null},
         {texto:"«Es un conflicto real que el texto no disuelve: el xiào y el yì pueden excluirse, y hay que decidir en cada caso qué cede.»", consecuencia:"Es la respuesta más honesta con el texto y la más incómoda: renuncia a que Confucio tenga una solución y pide juicio situado. Es también lo que Confucio pide en general, cuando dice que el junzi no está predispuesto a favor ni en contra de nada y sigue lo que corresponde.", va:null} ]}
     ],
     rubrica:[
       "Puedo contar con precisión qué pasa en Analectas 13.18 —quién habla, qué hizo el hijo, qué responde Confucio— sin exagerarlo ni suavizarlo.",
       "Distinguí entre callar (no declarar contra el padre), mentir activamente y denunciar, y no traté el caso como una elección entre solo dos opciones.",
       "Tuve en cuenta que mi caso tiene un tercero perjudicado (Julián) que en 13.18 no aparece, y dije qué cambia eso.",
       "Usé la amonestación suave de 4.18 como parte de la respuesta, y no solo 13.18.",
       "Conozco la respuesta del Mencio sobre Shun y su padre (7A35) y qué solución ofrece al conflicto, con su propio costo.",
       "Formulé la objeción del nepotismo en su mejor versión y la respondí o la acepté con razones.",
       "Separé mis intuiciones culturales sobre la lealtad familiar de lo que el texto efectivamente dice."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.confucio = { lecturas:[
 {titulo:"Analectas (Lúnyǔ): rén, lǐ y la rectificación de los nombres", fuente:"Internet Archive — Analectas de Confucio (edición en español)", url:"https://archive.org/details/analectas-confucio_202606",
  extracto:`Las Analectas no son un tratado sino una colección de dichos breves, preguntas de discípulos y respuestas situadas. Esa forma es parte del contenido: Confucio responde distinto a cada discípulo sobre la misma virtud, porque lo que a cada uno le falta es distinto.

El libro abre con una frase sobre el aprendizaje que fija el tono de toda la obra: «Aprender y practicar a su tiempo lo aprendido, ¿no es acaso un placer? Que vengan amigos de lejanas tierras, ¿no es acaso una alegría? No ser reconocido por los demás y no sentir resentimiento, ¿no es acaso propio de un hombre superior?». Aprender aquí no es acumular información: es practicar hasta que se vuelve carácter.

Sobre el rén (benevolencia, humanidad), Confucio ofrece varias formulaciones complementarias. A Yan Yuan le responde: «dominarse a sí mismo y volver a los ritos constituye el rén. Si alguien pudiera dominarse a sí mismo y volver a los ritos por un solo día, el mundo entero se volvería hacia el rén». A Zhong Gong le da la versión negativa de la regla de oro: «no impongas a los demás lo que no deseas para ti». Y cuando Fan Chi pregunta simplemente qué es el rén, la respuesta es de dos caracteres: «amar a los hombres».

El lǐ (rito, decoro) no es formalismo vacío: es la forma concreta en que la benevolencia se vuelve conducta. Pero Confucio advierte contra su degeneración: «un hombre sin rén, ¿qué tiene que ver con los ritos? Un hombre sin rén, ¿qué tiene que ver con la música?». El rito sin virtud interior es cáscara; la virtud sin forma es informe. Por eso insiste en el sacrificio: «sacrificar a los espíritus como si estuvieran presentes».

El junzi —el «hombre superior» o persona noble— es el ideal ético, y Confucio lo desliga expresamente del linaje: se llega por cultivo. Sus contrastes son constantes: «el hombre superior entiende lo que es justo; el hombre vulgar entiende lo que es provechoso»; «el hombre superior es sereno y no arrogante; el vulgar, arrogante y no sereno»; «el hombre superior busca en sí mismo; el hombre vulgar busca en los demás».

La rectificación de los nombres (zhèngmíng) aparece en el Libro XIII, cuando Zilu pregunta qué haría Confucio si un gobernante le confiara la administración. La respuesta desconcierta al discípulo: «lo primero sería rectificar los nombres». Y el maestro explica la cadena: «si los nombres no son correctos, el lenguaje no concuerda con la realidad; si el lenguaje no concuerda, los asuntos no se llevan a término; si los asuntos no se llevan a término, los ritos y la música no florecen; si los ritos y la música no florecen, los castigos no son justos; si los castigos no son justos, el pueblo no sabe dónde poner pies y manos». Cuando a un gobernante que no gobierna se lo sigue llamando gobernante, el desorden empieza en el lenguaje y termina en la injusticia.

Sobre el gobierno, la tesis es antilegalista: «si gobiernas al pueblo con decretos y lo mantienes en orden con castigos, evitará los castigos pero perderá el sentido de la vergüenza; si lo guías con la virtud y lo mantienes en orden con los ritos, tendrá vergüenza y además se corregirá».`,
  comentario:"Este conjunto de pasajes ordena la ética confuciana de adentro hacia afuera y de afuera hacia adentro a la vez: el rén anima al lǐ, pero el lǐ practicado forma al rén. Eso es lo que responde la pregunta del cuestionario sobre si una forma externa puede generar sinceridad: para Confucio sí, porque el carácter se moldea por hábito ritualizado. La rectificación de los nombres es además una de las tesis políticas sobre el lenguaje más actuales de toda la tradición."}
], preguntasLectura:[
 {q:"¿Qué le responde Confucio a Zhong Gong sobre el rén?", opciones:["«Amar a los hombres»","«No impongas a los demás lo que no deseas para ti»","«Rectificar los nombres»","«Obedecer al soberano»"], r:"«No impongas a los demás lo que no deseas para ti»", why:"Es la versión negativa de la regla de oro; a Fan Chi, en cambio, le responde «amar a los hombres»."},
 {q:"Según la cadena de la rectificación de los nombres, ¿dónde termina el desorden lingüístico?", opciones:["En la mala poesía","En castigos injustos y un pueblo desorientado","En la pérdida de los libros","En la guerra entre reinos"], r:"En castigos injustos y un pueblo desorientado", why:"La cadena va de nombres incorrectos a lenguaje que no concuerda, asuntos inconclusos, ritos marchitos y castigos injustos."},
 {q:"¿Qué critica Confucio del gobierno por decretos y castigos?", opciones:["Que es demasiado caro","Que el pueblo evitará el castigo pero perderá el sentido de la vergüenza","Que requiere muchos funcionarios","Que contradice los ritos antiguos"], r:"Que el pueblo evitará el castigo pero perderá el sentido de la vergüenza", why:"Frente al legalismo, Confucio propone guiar con la virtud y ordenar con los ritos para que el pueblo se corrija a sí mismo."}
]};
