/* ============================================================
   Ficha: dogen  ·  tradición: asiatica
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"dogen", trad:"asiatica", nombre:"Dōgen", fechas:"1200–1253 · Japón", escuela:"Budismo Zen (Sōtō)", icon:"🧘", profundizada:true,
 tesis:"La práctica meditativa no es un medio para alcanzar una iluminación futura: zazen ya es, en su mismo ejercicio, la actualización de la naturaleza de Buda. Práctica y realización son una sola cosa (shushō-ittō), y por eso no hay nada que conseguir ni ningún lugar adonde llegar — solo este sentarse, este cocinar, este instante, cada uno completo en sí mismo porque el tiempo no contiene al ser: el tiempo es el ser (uji).",
 obras:[
   {t:"Shōbōgenzō (El tesoro del ojo de la verdadera ley)", d:"Su obra magna y uno de los textos filosóficos más densos escritos jamás en japonés: no un tratado sistemático sino una colección de fascículos independientes —entre setenta y cinco y noventa y cinco según la recensión— redactados a lo largo de más de veinte años como charlas a sus monjes y después reescritos con obsesión. Dōgen escribe en japonés y no en chino clásico, que era la lengua culta de la época, y fuerza el idioma hasta deformarlo: convierte sustantivos en verbos, lee frases chinas contra su gramática para extraerles un sentido inesperado, inventa compuestos. El resultado es un texto que casi nadie leyó durante siglos y que la filosofía japonesa del siglo XX redescubrió como un clásico. Lo decisivo es que su forma es su contenido: si cada instante es completo en sí mismo, no puede haber un sistema que progrese hacia una conclusión, sino ensayos que giran una y otra vez alrededor del mismo punto sin acumularlo."},
   {t:"Genjōkōan", d:"El fascículo más citado del Shōbōgenzō, escrito en 1233 como carta a un discípulo laico y colocado por el propio Dōgen al comienzo de la colección. En apenas unas páginas condensa todo su pensamiento con una estructura de cuatro movimientos: cuando todas las cosas son el dharma hay ilusión y realización, budas y seres; cuando las diez mil cosas están sin yo no hay ninguna de esas distinciones; el camino trasciende originalmente la abundancia y la carencia, y por eso hay otra vez nacimiento y muerte; y sin embargo las flores caen aunque las amemos y las malezas crecen aunque las detestemos. Ese cuarto movimiento —la vuelta a lo concreto después de la negación— es su firma: la iluminación no cancela el mundo ordinario, lo devuelve. Allí están también la fórmula sobre estudiarse y olvidarse a uno mismo, el ejemplo de la leña y la ceniza contra la idea de que el tiempo sea un tránsito, y la imagen de la luna entera reflejada en una gota de rocío."},
   {t:"Fukanzazengi (Reglas universales para la práctica de zazen)", d:"Su primer escrito al volver de China en 1227, un texto breve en chino clásico que funciona a la vez como manual técnico y como manifiesto. La parte técnica es minuciosa y sin misterio: dónde sentarse, cómo cruzar las piernas, dónde poner las manos, cómo respirar, cómo levantarse despacio al terminar. Pero la palabra clave es fukan, universal: contra la idea de que zazen sea una técnica para monjes avanzados o para gente con talento espiritual, Dōgen insiste en que es la puerta de todos. Y la frase que define su ruptura con el resto del budismo de su tiempo aparece ahí: zazen no es aprender a meditar ni un método para pacificar la mente, es la puerta del dharma del descanso y la dicha, la realización total ya presente. El detalle más importante para entenderlo es negativo: no hay una meta descrita en ninguna parte del texto."},
   {t:"Bendōwa (Discurso sobre la práctica del Camino)", d:"Escrito en 1231, cuando Dōgen era todavía un maestro sin monasterio ni protección institucional, es su defensa temprana y polémica de zazen como la única práctica que hace falta. Tiene una primera parte narrativa donde cuenta su búsqueda y su encuentro con Rujing, y una segunda organizada como dieciocho preguntas y respuestas que anticipan y contestan las objeciones de sus adversarios: si basta con sentarse, para qué sirven los sutras; si la naturaleza de Buda ya está presente, para qué practicar; si el zen chino tiene razón, qué pasa con las escuelas japonesas establecidas. Ahí formula por primera vez la unidad de práctica y realización y la noción de jijuyū zanmai, el samadhi del gozo de sí, y sostiene que cuando una sola persona se sienta en zazen todo el universo entero se ilumina con ella — la práctica no es un asunto privado."},
   {t:"Tenzo Kyōkun y Eihei Shingi (Instrucciones al cocinero y reglas monásticas)", d:"El Tenzo Kyōkun, de 1237, es un texto sobre el monje encargado de la cocina y es la mejor entrada práctica a su filosofía. Dōgen cuenta dos encuentros reales en China con viejos cocineros que le enseñaron más que ningún abad: uno que había viajado kilómetros a comprar hongos y se negó a quedarse a conversar de dharma porque tenía que volver a cocinar, y otro que secaba algas al sol de mediodía a los sesenta y ocho años y le contestó, cuando Dōgen le preguntó por qué no dejaba esa tarea a otro, que otro no es yo y que si no es ahora cuándo. De ahí salen las instrucciones concretas: no despreciar los ingredientes pobres ni entusiasmarse con los ricos, no dejar caer un grano de arroz, manipular el agua y las verduras con las propias manos. Junto con el resto del Eihei Shingi, que regula desde el uso del baño hasta el modo de lavar el cuenco, forma un cuerpo donde la distinción entre tarea doméstica y práctica espiritual simplemente no existe."}
 ],
 conceptos:[
   {t:"Shikantaza (solo sentarse)", d:"Zazen sin objeto, sin técnica de concentración, sin mantra, sin visualización, sin koan que resolver y —esto es lo difícil— sin finalidad ulterior. No se cuenta la respiración para calmarse, no se observa la mente para conocerla, no se busca una experiencia. El adverbio shikan significa solamente, y está puesto ahí para excluir todo lo demás, incluida la más razonable de las razones para meditar. Dōgen lo llama mushotoku, sin ganancia. La objeción salta de inmediato: sentarse sin ningún propósito parece o bien imposible o bien inútil, y la respuesta de Dōgen no consiste en negar la paradoja sino en localizarla en el lugar correcto — es la búsqueda misma la que produce la distancia respecto de lo buscado, de modo que lo único que puede hacerse con ella es soltarla, y soltarla tampoco es una técnica."},
   {t:"Genjōkōan (el koan que se actualiza)", d:"Genjō significa manifestarse plenamente, actualizarse, presentarse del todo; kōan, en el zen Rinzai, nombra el enigma que el maestro entrega al discípulo para quebrar su pensamiento discursivo. Dōgen junta las dos palabras y les cambia el sentido: el koan no es un acertijo que haya que resolver en la sala de entrevistas, es la realidad presente misma en tanto se manifiesta completa aquí y ahora. No hay que ir a buscarlo: esta taza, esta respiración, esta pierna dormida son el koan actualizándose. La consecuencia es un desplazamiento entero del centro de gravedad del zen — de la experiencia extraordinaria del kenshō a la plenitud de lo ordinario— y explica por qué Dōgen desconfió de las historias de despertares súbitos que circulaban como trofeos."},
   {t:"Shushō-ittō (unidad de práctica y realización)", d:"El núcleo de todo su pensamiento y el punto donde rompe con el sentido común religioso. La idea corriente es instrumental: uno practica ahora para iluminarse después, como uno estudia para aprobar. Dōgen sostiene que esa estructura es falsa de raíz, porque una iluminación que fuera el efecto de una práctica sería algo producido, y lo producido termina. Si la naturaleza de Buda ya está entera, la práctica no puede ser un medio para obtenerla: es su ejercicio, su expresión, su actualización. Por eso dice que en el budismo práctica y realización no son dos cosas, y que quien se sienta en zazen no está preparando nada — el sentarse de un principiante y el de un maestro no difieren en grado de acercamiento a una meta. Lo que cambia con los años no es la distancia: es el abandono del hábito de medirla."},
   {t:"Busshō (naturaleza de Buda)", d:"El fascículo homónimo contiene su lectura más audaz y más discutida. La frase canónica del Sutra del Nirvana dice, en su lectura habitual, que todos los seres tienen naturaleza de Buda. Dōgen lee el mismo texto chino forzando la gramática —la partícula u puede significar tener y también haber o ser— y obtiene: todos los seres son naturaleza de Buda, o incluso todo el ser es naturaleza de Buda. La diferencia no es sutileza filológica. Si los seres tienen naturaleza de Buda, esa naturaleza es una posesión interior, una semilla escondida que habría que desarrollar, y vuelve todo el esquema instrumental que él rechaza. Si los seres son naturaleza de Buda, no hay nada oculto adentro ni nada que desarrollar, y la práctica deja de ser extracción para volverse expresión. Los filólogos discuten si la lectura es legítima; lo que nadie discute es que es deliberada."},
   {t:"Uji (ser-tiempo)", d:"Su aporte más original a la filosofía y el que más atrajo a los lectores del siglo XX. La intuición ordinaria trata al tiempo como un recipiente vacío dentro del cual las cosas existen y por el cual se desplazan. Dōgen niega el recipiente: no hay tiempo aparte de los seres ni seres aparte del tiempo, el tiempo es existencia y la existencia es tiempo. De ahí su ejemplo célebre: la leña se vuelve ceniza y la ceniza no puede volver a ser leña, pero sería un error decir que la ceniza es el después y la leña el antes — la leña habita plenamente la posición de leña y la ceniza la de ceniza, cada una con su propio antes y su propio después. Lo mismo con las estaciones: no decimos que el invierno se convierte en primavera. Dōgen no niega la sucesión; niega que un instante sea el medio de otro, y por eso cada momento es completo, no un fragmento de una trayectoria."},
   {t:"Shinjin datsuraku (dejar caer cuerpo y mente)", d:"La fórmula con que resume su propia experiencia de despertar bajo el maestro Rujing en el monasterio del monte Tiantong, hacia 1225, cuando este reprendió a un monje que dormitaba en zazen diciéndole que la práctica del zen es dejar caer cuerpo y mente. Conviene desactivar dos malentendidos frecuentes. No es un trance en el que se pierda la conciencia del cuerpo, ni una ascesis que lo mortifique: datsuraku es el gesto de soltar, de que algo se desprenda solo, como la ropa que cae. Y no se trata de dejar caer el cuerpo por un lado y la mente por otro, sino de que se desprenda la unidad shinjin, ese conjunto al que llamamos yo y que tratamos como una cosa que posee experiencias. Lo que cae no es la existencia corporal: es el sujeto separado que la administra."},
   {t:"Estudiarse y olvidarse a uno mismo", d:"La secuencia del Genjōkōan es una de las frases más citadas del budismo entero y su orden es lo que importa: estudiar el camino del Buda es estudiarse a uno mismo, estudiarse a uno mismo es olvidarse de uno mismo, olvidarse de uno mismo es ser realizado por las diez mil cosas. Cada paso invierte al anterior. No se empieza por la disolución del yo —eso sería saltear el trabajo— sino por el examen más minucioso de la propia experiencia, y es ese examen llevado hasta el final el que descubre que no hay un yo separado que examinar. Y el tercer paso invierte la dirección de la actividad: uno no ilumina el mundo, es confirmado por él. Dōgen agrega la advertencia decisiva de que llevar el yo hacia las cosas para experimentarlas es ilusión, y que las cosas vengan y se realicen a través de uno es despertar."},
   {t:"Contra la iluminación como objeto", d:"Su crítica más insistente apunta a lo que llama taigo, esperar el despertar, y a la práctica que se sostiene en la expectativa de un premio. El problema no es que la meta sea lejana sino que es una meta: en cuanto la iluminación se representa como un estado futuro, distinto de este, se la ha convertido en un objeto, y un objeto es exactamente lo que está separado de quien lo busca. La búsqueda produce entonces aquello de lo que se queja. Esto explica su desconfianza del sistema Rinzai de koans usados como escalones verificables de progreso, y su famosa pregunta juvenil, la que lo empujó a viajar a China: si todos los seres ya poseen originalmente la naturaleza de Buda, por qué los budas del pasado tuvieron que despertar. Su respuesta madura no resuelve la pregunta: disuelve el marco que la hacía posible."},
   {t:"La cocina como práctica", d:"En la mayoría de las tradiciones religiosas hay una jerarquía tácita entre las tareas espirituales y las tareas de mantenimiento: primero se cocina y se limpia, y después, si sobra tiempo, se practica. Dōgen borra esa jerarquía y el cargo de tenzo, el cocinero del monasterio, es el caso de prueba. Preparar la sopa con la misma atención que un rito, revisar el arroz grano por grano, no despreciar el ingrediente humilde ni exaltar el costoso, ir a buscar el agua uno mismo: nada de eso es una preparación para la práctica ni una metáfora de ella, es la práctica entera. La razón es rigurosamente derivada de shushō-ittō: si nada de lo que se hace ahora es un medio para un después, entonces tampoco lavar los cuencos lo es, y el monje que cocina pensando en el zazen que vendrá luego ya perdió las dos cosas."}
 ],
 conexion:"Su punto de partida es el budismo Tendai del monte Hiei, donde la doctrina de la iluminación original (hongaku) le dejó la pregunta que ordenó su vida entera: si ya somos naturaleza de Buda, por qué practicar. La respuesta la encontró en China con <b>Rujing</b>, y consiste en negar el si previo — no es que ya seamos y por eso haya que practicar, es que la práctica es ese ser. Dentro de Asia, su ecuación entre samsara y nirvana es impensable sin <b>Nagarjuna</b>, aunque las direcciones difieren: donde el Madhyamaka disuelve argumentativamente toda naturaleza propia, Dōgen no argumenta sino que reenvía a lo concreto; y su paradoja del esfuerzo sin meta rima con el wu wei de <b>Laozi</b> y con la destreza absorta del cocinero de <b>Zhuangzi</b>, con la diferencia de que Dōgen la somete a una disciplina monástica minuciosa en vez de a la espontaneidad. En el siglo XX, <b>Nishida Kitarō</b> y la Escuela de Kioto lo convirtieron en interlocutor de la filosofía europea, y el uji fue leído junto al ser y tiempo de <b>Heidegger</b>: ambos niegan que el tiempo sea un recipiente neutro, pero donde Heidegger funda la temporalidad en el ser hacia la muerte, Dōgen sostiene que cada instante ya es completo y no obtiene su sentido de un futuro. Su desconfianza de las palabras convive con una obra verbal inmensa, y eso lo acerca por otro camino al <b>Wittgenstein</b> que escribe largamente sobre lo que no se puede decir.",
 dialogo:{titulo:"Para qué sirve sentarse", lineas:[
   {quien:"Monje nuevo", texto:"Maestro, llevo tres meses sentándome cada madrugada. Quiero preguntarle algo sin rodeos: ¿para qué sirve esto? ¿Qué voy a lograr?"},
   {quien:"Dōgen", texto:"Nada. Y esa no es una respuesta modesta ni una prueba de tu paciencia: es literal. Zazen no sirve para nada porque no es un medio."},
   {quien:"Monje nuevo", texto:"Pero entonces estoy perdiendo tres horas por día. Si me dijera que en cinco años voy a despertar, me siento diez años."},
   {quien:"Dōgen", texto:"Ya sé que te sentarías. Y por eso mismo estarías sentado en el lugar equivocado, aunque el cuerpo estuviera en el cojín correcto. Decime: mientras esperás el despertar de dentro de cinco años, ¿dónde está el despertar?"},
   {quien:"Monje nuevo", texto:"Adelante. En el futuro."},
   {quien:"Dōgen", texto:"Es decir, en otro lado. Lo pusiste lejos con tus propias manos y después te quejás de la distancia. Cuando yo tenía tu edad hice en el monte Hiei la misma pregunta que estás haciendo: si todos los seres ya son naturaleza de Buda, por qué los budas del pasado tuvieron que practicar. Nadie supo contestarme y crucé el mar para averiguarlo."},
   {quien:"Monje nuevo", texto:"¿Y qué le contestaron en China?"},
   {quien:"Dōgen", texto:"Rujing no me contestó la pregunta: me sacó el marco donde la pregunta se apoyaba. Una madrugada reprendió a un monje que cabeceaba y dijo que la práctica del zen es dejar caer cuerpo y mente. Ahí entendí que la pregunta suponía dos cosas, un ya somos y un todavía no, y que no hay dos.", nota:"Conviene no leer shinjin datsuraku como un trance ni como una mortificación del cuerpo. Datsuraku es soltar, desprenderse, como cae la ropa; y lo que cae no es el cuerpo por un lado y la mente por otro, sino esa unidad a la que llamamos yo y tratamos como dueña de la experiencia."},
   {quien:"Monje nuevo", texto:"En el monasterio de la montaña vecina entregan koans y hay entrevistas donde uno demuestra el avance. Al menos ahí sé si voy bien."},
   {quien:"Dōgen", texto:"Sé exactamente de qué hablás y no lo desprecio: yo mismo compilé trescientos de esos casos. Lo que no acepto es que se usen como escalones verificables, porque entonces el camino se convierte en una escalera y la práctica en su propia contabilidad. Para nosotros el kōan no es lo que te doy: es lo que está ocurriendo. Genjōkōan, el koan actualizándose. Esta pierna dormida que tenés ahora es el caso.", nota:"El contraste Sōtō y Rinzai es real pero suele exagerarse: Dōgen recopiló el Mana Shōbōgenzō, una colección de trescientos koans, y los cita constantemente. Su objeción no es al koan sino a la estructura de progreso medible que armaron alrededor de él."},
   {quien:"Monje nuevo", texto:"Entonces le hago la objeción al revés. Si sentarse ya es iluminación, ¿por qué me levanto a las tres de la mañana? Podría iluminarme durmiendo."},
   {quien:"Dōgen", texto:"Podrías, si dormir fuera sentarse. No lo es. La unidad de práctica y realización no dice que cualquier cosa da lo mismo: dice que esta cosa no es la moneda con que se paga otra. Nadie come por adelantado para no volver a tener hambre, y nadie dice por eso que comer sea inútil."},
   {quien:"Monje nuevo", texto:"Pero el hambre vuelve. Eso es justamente lo que me deprime."},
   {quien:"Dōgen", texto:"Te deprime porque querés una comida que sea la última. La leña se vuelve ceniza y no vuelve a ser leña; y sin embargo sería un error decir que la leña es el antes de la ceniza. La leña habita del todo su posición de leña. Este desayuno no es un adelanto del próximo ni una deuda del anterior."},
   {quien:"Monje nuevo", texto:"Mañana me toca la cocina y voy a perder la sesión de la tarde. ¿Puedo pedir que me reemplacen para no interrumpir la práctica?"},
   {quien:"Dōgen", texto:"En China conocí a un cocinero de sesenta y ocho años secando algas al sol del mediodía. Le pregunté por qué no dejaba esa tarea a un monje más joven, y me dijo dos cosas que todavía me sostienen: otro no es yo, y si no es ahora, cuándo. No vas a interrumpir nada. Vas a cocinar."},
   {quien:"Monje nuevo", texto:"Igual me queda el fondo de la pregunta sin contestar, maestro."},
   {quien:"Dōgen", texto:"Me alegro. Si te la hubiera contestado, te habría dado un objeto más para perseguir. Andá a sentarte."}
 ]},
 actividades:[
   {t:"Veinte minutos sin ganancia, y el registro honesto de lo que pasó", d:"Sentate veinte minutos con un cronómetro fuera de la vista, la espalda derecha y los ojos entreabiertos hacia el piso, sin contar la respiración, sin repetir nada, sin proponerte relajarte ni concentrarte ni observar la mente. La consigna es solamente sentarte. Apenas termines, y antes de hacer cualquier otra cosa, escribí dos páginas sin corregir sobre una única cuestión: cada vez que apareció la urgencia de que esto sirviera para algo, anotá qué forma tomó exactamente. Fue querer que pasara rápido, querer sentir algo especial, evaluarte a mitad de camino, calcular cuánto faltaba, decidir que lo estabas haciendo mal, o planear escribir después sobre lo bien que te salió. Marcá con un círculo las que sean formas encubiertas de estar buscando una meta, y fijate si la decisión de no buscar ninguna funcionó también ella como una meta. No arregles la conclusión: ese conflicto es el material."},
   {t:"Una tarea doméstica como práctica entera, no como antesala", d:"Elegí una tarea material y repetitiva que hagas de verdad esta semana —lavar los platos de una comida, cocinar algo desde cero, limpiar un cuarto, caminar hasta el trabajo— y hacela una vez siguiendo la regla del tenzo: sin música, sin auriculares, sin teléfono, sin conversación, y sobre todo sin la sensación de que es el obstáculo que hay que despachar antes de empezar con lo importante. Manipulá cada cosa con las manos, no desprecies lo feo ni te entusiasmes con lo lindo, no dejes caer un grano. Después escribí una página comparando esa vez con las veces habituales, y respondé con precisión a dos preguntas: qué parte de tu día vivís normalmente como corredor hacia otra parte del día, y qué quedaría de tu semana si le sacaras todo lo que hacés solamente para poder hacer otra cosa después."},
   {t:"Dos momentos, medidos con el criterio de uji", d:"Reconstruí por escrito dos momentos concretos y recientes de tu propia vida, con fecha y detalles reales. El primero, un momento que se haya sentido completo en sí mismo, que no pedía continuación ni recompensa: una conversación, una caminata, una tarea que te absorbió. El segundo, un momento que hayas vivido enteramente como trámite hacia lo que venía después: una espera, una obligación, un trayecto, un trabajo que hacías por el viernes. Describí los dos con el mismo nivel de detalle sensorial, sin idealizar el primero. Después respondé en un párrafo final la pregunta difícil: ¿la diferencia estuvo en lo que ocurría o en cómo lo mirabas? Y si fue lo segundo, ¿se puede decidir mirar así, o esa decisión es otra forma de instrumentalizar el instante?"}
 ],
 cuestionario:[
   {q:"Si práctica e iluminación son lo mismo, ¿qué motiva seguir practicando durante décadas? Parece que Dōgen le sacó a la práctica su única razón de ser.", p:"La objeción es la primera que le hicieron y él mismo la puso en boca de un adversario en el Bendōwa, así que conviene tomarla en serio. Su respuesta tiene tres capas. La primera es un argumento sobre el tipo de cosa que sería la iluminación: si fuera el efecto de la práctica, sería algo producido, y todo lo producido se deshace; una liberación que se gana se puede perder. La segunda es un desplazamiento de la pregunta por la motivación: quien pregunta qué gano supone que la práctica es un costo que hay que compensar, y esa suposición es exactamente el hábito que zazen deshace. Comer no se hace para dejar de comer, y sin embargo nadie dice que comer carezca de razón. La tercera es empírica y la usó siempre: los budas del pasado, ya despiertos, siguieron sentándose, lo cual muestra que la práctica no era el precio de nada. Pero hay que conceder que queda un problema real. Si todo hábito humano se sostiene en alguna forma de expectativa, entonces el monje que se levanta a las tres de la mañana durante cuarenta años está movido por algo, y describir ese algo sin volver a introducir una finalidad es difícil. La salida honesta de Dōgen es negar que la motivación tenga que ser una meta: uno se sienta como quien respira, y lo que cambia con los años no es la distancia a un punto sino la disminución del hábito de medirla. Un crítico dirá que eso es redescribir la motivación, no eliminarla."},
   {q:"Sentarse sin ninguna finalidad, ¿no es también una finalidad? Parece la misma paradoja que la del sabio de Zhuangzi que se esfuerza por no esforzarse.", p:"Es la objeción más fuerte y es estrictamente formal: la instrucción no busques nada tiene forma de instrucción, y cumplirla es alcanzar el estado que describe, es decir, buscarlo. Zhuangzi tropieza con lo mismo cuando recomienda la espontaneidad, y también el estoico que se propone la indiferencia. Hay tres respuestas posibles y ninguna es completa. La primera es pragmática: la paradoja es real en el nivel de la descripción pero se disuelve en el ejercicio, del mismo modo que la orden de no pensar en un oso blanco es imposible como orden y sin embargo hay actividades durante las cuales de hecho uno no piensa en osos; el error sería tratar shikantaza como una orden en vez de como algo que se hace. La segunda es estructural: Dōgen no dice que haya que eliminar el deseo de despertar —de hecho lo llama bodaishin y lo exige— sino que ese deseo no tiene que tomar la forma de un objeto futuro; hay una diferencia entre orientarse y perseguir. La tercera es que la paradoja es productiva y no hay que resolverla: es el motor mismo de la práctica, el lugar donde uno choca todos los días con su propio hábito de instrumentalizar, y un sistema que la resolviera de una vez habría convertido el despertar en una técnica. Con todo, un lector escéptico puede sostener con razón que esto salva la doctrina apelando a una experiencia que solo se verifica desde adentro, y eso es un costo epistemológico."},
   {q:"Si cada instante es completo en sí mismo, ¿qué pasa con la causalidad, con la memoria y con el karma? Dōgen parece quedarse sin poder explicar que las cosas se sigan unas de otras.", p:"Hay que separar dos tesis que la formulación popular confunde. Dōgen no niega la sucesión: dice explícitamente que la leña se vuelve ceniza y que la ceniza no puede volver a ser leña, y él mismo insiste en el fascículo sobre el karma en que la causalidad moral es rigurosa y que negarla es la peor de las desviaciones — rescata para eso el koan del zorro salvaje, donde un maestro pasa quinientas vidas convertido en animal por haber dicho que el iluminado no cae bajo la causa y el efecto. Lo que niega es algo más preciso: que un instante sea el medio de otro, es decir, que la leña sea meramente el antes de la ceniza y no plenamente leña. La distinción se puede formular así: rechaza la subordinación ontológica de los momentos, no su encadenamiento. Aun así quedan dificultades genuinas. Si cada momento es completo, no está claro qué hace que este momento sea el que sigue de aquel y no de cualquier otro, y Dōgen no da una teoría de la conexión — la imagen del kyōryaku, el pasaje del tiempo que va también en dirección inversa, es sugerente pero no es un mecanismo. Y la memoria queda en un estatus ambiguo, porque o bien el recuerdo es un momento presente completo, y entonces no es propiamente memoria de otro, o bien remite a otro y entonces no es completo. Un filósofo analítico diría que esto es poesía haciéndose pasar por metafísica; un lector más generoso responderá que Dōgen no está compitiendo con una teoría del tiempo sino describiendo cómo se da el tiempo a alguien que no lo está gastando."},
   {q:"¿En qué se distingue realmente de la vacuidad de Nagarjuna y del fluir de Zhuangzi, o es la misma idea con otro vocabulario?", p:"Los tres coinciden en desarmar la idea de sustancias fijas y en desconfiar de las oposiciones rígidas, y Dōgen es históricamente heredero del Madhyamaka a través del chan, así que el parecido no es casual. Pero las diferencias son de método y de dirección, y son decisivas. Nagarjuna procede por argumentación: toma la tesis del adversario, extrae sus consecuencias y muestra que se destruye sola, y su resultado es negativo por diseño, sin tesis propia que defender. Dōgen casi no argumenta; su procedimiento es la afirmación paradójica y el reenvío a lo concreto, y su movimiento característico es el cuarto del Genjōkōan, el regreso a las flores que caen después de la negación — donde el Madhyamaka termina en la disolución de las posiciones, Dōgen termina en la leña, la ceniza y el arroz. Con Zhuangzi la diferencia es casi opuesta: comparte con él la crítica al esfuerzo instrumental y el elogio de la absorción del artesano, pero Zhuangzi la formula como espontaneidad, vagabundeo y desconfianza de toda institución, mientras que Dōgen la encierra en una disciplina monástica que reglamenta el horario, la postura y hasta el modo de lavar el cuenco. Ese contraste es filosóficamente interesante y no meramente cultural: Zhuangzi cree que la naturalidad aparece cuando se quitan las reglas, Dōgen que la regla minuciosa es el lugar donde el yo calculador se queda sin trabajo. Y hay una diferencia de fondo con Nagarjuna que conviene no tapar: la vacuidad es una tesis sobre la falta de naturaleza propia, mientras que el uji afirma algo, la identidad de ser y tiempo, lo cual es un paso metafísico que un madhyamika ortodoxo miraría con sospecha."},
   {q:"El zen dice que la verdad es una transmisión directa, fuera de las escrituras y sin palabras. ¿Cómo se explica entonces que Dōgen haya escrito una de las obras más extensas y verbalmente elaboradas de la historia del budismo?", p:"La contradicción es aparente solo si uno toma el lema de la transmisión fuera de las escrituras como un rechazo del lenguaje, y Dōgen fue explícito en que no lo toma así. En el fascículo sobre los sutras sostiene que las escrituras no son un dedo que señala la luna desde afuera y que habría que descartar después, sino que la totalidad del universo es la escritura; y en otro pasaje dice que las palabras son la expresión del despertar, no su sucedáneo. Su práctica escrituraria lo confirma: no escribe para transmitir información sobre una experiencia previa, sino que fuerza la lengua japonesa hasta quebrarla —convierte sustantivos en verbos, lee frases chinas contra su gramática, inventa compuestos— de modo que el lector no obtenga una doctrina sino que tropiece. El lenguaje no describe la realización: la ejerce, igual que zazen. Su blanco, cuando desconfía de las palabras, no es la palabra sino su uso instrumental, el mismo que ataca en la práctica. Dicho esto, el problema no desaparece del todo. Una obra escrita se vuelve inevitablemente objeto de comentario, de erudición y de examen, y la historia posterior del Shōbōgenzō lo demuestra: fue guardado casi en secreto durante siglos y después convertido en material académico. Hay además una asimetría incómoda entre decir que cualquiera puede sentarse y escribir un texto que exige veinte años de formación para leerse, y un crítico puede sostener que la universalidad de Fukanzazengi y la dificultad del Shōbōgenzō conviven peor de lo que la escuela admite."}
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.dogen = { lecturas:[
 {titulo:"Genjōkōan (Shōbōgenzō): estudiarse a uno mismo es olvidarse de uno mismo", fuente:"Zen Center of Los Angeles — Eihei Dōgen's Genjōkōan (PDF)", url:"https://zcla.org/wp-content/uploads/2021/09/EiheiDogensGenjokoan.pdf",
  extracto:`El Genjōkōan es el ensayo más leído del Shōbōgenzō y abre con una estructura de cuatro movimientos que parece contradictoria: «Cuando todas las cosas son el Buddha-dharma, hay ilusión y realización, práctica, nacimiento y muerte, budas y seres sintientes. Cuando las diez mil cosas están sin yo, no hay ilusión ni realización, ni budas ni seres sintientes, ni nacimiento ni muerte. Como el camino del Buddha trasciende originalmente la abundancia y la carencia, hay nacimiento y muerte, ilusión y realización, seres y budas. Y sin embargo, aunque es así, las flores caen aun cuando las amamos, y las malezas crecen aun cuando las detestamos».

La secuencia importa: afirmación, negación, reafirmación, y finalmente el retorno a lo concreto. Dōgen no se queda en la negación budista de las distinciones; vuelve a las flores que caen y a las hierbas que crecen, porque la iluminación no cancela el mundo ordinario.

El pasaje más citado formula el método entero en cuatro líneas: «Estudiar el camino del Buddha es estudiarse a uno mismo. Estudiarse a uno mismo es olvidarse de uno mismo. Olvidarse de uno mismo es ser iluminado por las diez mil cosas. Ser iluminado por las diez mil cosas es dejar caer el cuerpo y la mente propios y los de los demás». Y agrega que la iluminación auténtica no deja rastro: «no queda traza alguna de realización, y esa traza sin traza continúa sin fin».

La inversión epistemológica es explícita: «llevar el yo hacia adelante para experimentar las diez mil cosas es ilusión; que las diez mil cosas vengan hacia adelante y experimenten al yo es iluminación». No es la mente la que ilumina el mundo: es el mundo el que ilumina a la mente cuando el yo deja de imponerse.

Sobre el tiempo, Dōgen usa el ejemplo de la leña y la ceniza contra la intuición ordinaria: «la leña se vuelve ceniza y no puede volver a ser leña. Pero no debemos decir que la ceniza es el después y la leña el antes. Sabé que la leña habita en la posición de leña, con su propio antes y su propio después; y aunque tiene antes y después, esas fases están claramente separadas. La ceniza habita en la posición de ceniza». Lo mismo con la vida y la muerte: «no decimos que el invierno se convierte en primavera, ni que la primavera se convierte en verano». Cada instante es completo en sí, no un tránsito hacia otro — esto es uji, «ser-tiempo».

La imagen final es una de las más bellas del corpus zen: «la iluminación es como la luna reflejada en el agua. La luna no se moja, el agua no se rompe. Aunque su luz es vasta y grande, se refleja en un charco de un palmo. La luna entera y el cielo entero se reflejan en una gota de rocío en la hierba».

Y el cierre recuerda por qué la práctica no termina: un monje pregunta al maestro Baoche, que se abanica, por qué se abanica si la naturaleza del viento es permanente y está en todas partes. El maestro responde: «sabés que la naturaleza del viento es permanente, pero no sabés el significado de que llegue a todas partes», y sigue abanicándose.`,
  comentario:"El koan del abanico es la respuesta exacta a la pregunta del cuestionario: la naturaleza búdica es permanente, pero sin la práctica no «llega». Fijate en la estructura de leña y ceniza — Dōgen no niega la sucesión, niega que un instante sea medio para otro, y eso es lo que sostiene su tesis de que práctica y realización son inseparables. La luna en la gota de rocío es la formulación poética de uji: el todo cabe entero en cada momento."}
], preguntasLectura:[
 {q:"Según el Genjōkōan, ¿qué es la iluminación?", opciones:["Llevar el yo hacia las cosas para experimentarlas","Que las diez mil cosas vengan hacia adelante y experimenten al yo","Abandonar el mundo ordinario","Memorizar los sutras"], r:"Que las diez mil cosas vengan hacia adelante y experimenten al yo", why:"Lo contrario —llevar el yo hacia adelante— es explícitamente definido como ilusión."},
 {q:"¿Qué sostiene Dōgen con el ejemplo de la leña y la ceniza?", opciones:["Que la materia se conserva","Que la leña habita su propia posición y la ceniza la suya: cada fase es completa en sí","Que el fuego es ilusorio","Que la ceniza puede volver a ser leña"], r:"Que la leña habita su propia posición y la ceniza la suya: cada fase es completa en sí", why:"Es la doctrina de uji: el instante no es un tránsito hacia otro, como el invierno no «se convierte» en primavera."},
 {q:"¿Qué responde el maestro Baoche al monje que pregunta por qué se abanica?", opciones:["Que hace calor","Que sabe que el viento es permanente pero no sabe qué significa que llegue a todas partes","Que el abanico es un símbolo ritual","Que la práctica es innecesaria"], r:"Que sabe que el viento es permanente pero no sabe qué significa que llegue a todas partes", why:"Es la justificación zen de por qué se sigue practicando aunque la naturaleza búdica ya esté presente."}
]};
