/* ============================================================
   Ficha: laozi  ·  tradición: asiatica
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"laozi", trad:"asiatica", nombre:"Laozi", fechas:"Siglo VI a.C. · China", escuela:"Taoísmo", icon:"🌊", profundizada:true,
 tesis:"Hay un fondo del que todo sale y al que todo vuelve, y ninguna palabra lo alcanza: el Dao, que la primera línea del libro declara indecible antes de decir nada más. De esa tesis negativa se sigue todo lo demás. Si el orden real no procede de una regla explícita, entonces la manera humana de acertar no es imponer un plan sino wú wéi, actuar sin forzar, dejando que cada cosa despliegue su ziran, aquello que es así por sí mismo. De ahí la extraña política del libro, que aconseja al gobernante hacer menos, legislar menos, ambicionar menos, y la extraña teoría del valor que prefiere lo blando a lo duro, lo bajo a lo alto, el vacío al lleno y el agua a la piedra. Y de ahí también la incomodidad honesta que conviene no disimular: casi nada de esto puede establecerse sobre la figura de un autor. La tradición cuenta que Lao Dan, archivero de la corte de Zhou y maestro ocasional de Confucio, harto de la decadencia del reino, partió hacia el oeste montado en un búfalo y, detenido en el paso fronterizo por el guardián Yin Xi, le dictó cinco mil caracteres antes de desaparecer para siempre. La erudición contemporánea, desde la biografía ya vacilante de Sima Qian hasta los manuscritos de Guodian y Mawangdui, considera que Laozi —literalmente el Viejo Maestro, que es un título y no un nombre— es más probablemente una figura compuesta, y el Dao De Jing una antología de dichos y aforismos de tradición oral sedimentados durante uno o dos siglos. El texto que leemos no es la confesión de un hombre: es el depósito de una corriente.",
 obras:[
   {t:"Dao De Jing: el texto recibido de Wang Bi", d:"El Dao De Jing —también transcrito Tao Te Ching— es la única obra atribuida a Laozi, y hablar de ella exige elegir primero qué versión se está leyendo. Durante casi dos mil años Occidente y China leyeron la recensión asociada al comentario de Wang Bi, un joven prodigio del siglo III que murió a los veintitrés años y cuya lectura filosófica, centrada en el wu (la nada, el no ser) como fondo del que emerge el ser, fijó el modo de entender el libro para toda la posteridad. Son ochenta y una secciones brevísimas, unos cinco mil caracteres en total, sin argumentación discursiva, hechas de aforismos rimados, imágenes naturales, paradojas y consejos al gobernante. Hay que subrayar un punto que las traducciones rara vez advierten: la división en ochenta y un capítulos es posterior al texto y probablemente numerológica (nueve por nueve), de modo que algunos cortes separan materiales que iban juntos y otros unen fragmentos independientes. Leer el libro como una obra con desarrollo es forzarlo; leerlo como una antología de dichos que se iluminan entre sí es más fiel a lo que es."},
   {t:"Los manuscritos de seda de Mawangdui", d:"En 1973, en una tumba sellada en el año 168 a.C. en Mawangdui, cerca de Changsha, aparecieron dos copias del texto escritas sobre seda, unos cuatro siglos y medio más antiguas que cualquier manuscrito conocido hasta entonces. Las diferencias son en su mayoría menores —variantes gráficas, partículas, algún carácter tabú sustituido por evitar el nombre de un emperador—, pero una es estructural y de gran consecuencia interpretativa: en ambas copias las secciones del De preceden a las del Dao, de modo que el libro empieza no con la metafísica de lo innombrable sino con el famoso capítulo 38 sobre la virtud superior que no se propone ser virtuosa. Eso invierte el énfasis: el orden recibido presenta primero un principio cósmico y después su aplicación; el orden de Mawangdui presenta primero una crítica de la moral deliberada, y el Dao aparece después como su fundamento. Ninguna de las dos ordenaciones es la original con certeza, y esa incertidumbre misma es la enseñanza filológica del hallazgo."},
   {t:"Las tiras de bambú de Guodian", d:"En 1993 se excavó en Guodian, provincia de Hubei, la tumba de un noble del Estado de Chu clausurada hacia el 300 a.C., y entre sus tiras de bambú aparecieron tres grupos de materiales que corresponden a poco más de un tercio del Dao De Jing recibido. Es el testimonio más antiguo del texto y obliga a repensar su formación: no hay ochenta y un capítulos, no hay división Dao/De, el orden es distinto y muchas secciones célebres simplemente no están. Más importante todavía es un detalle de contenido. En la versión recibida, el capítulo 19 ordena abandonar la benevolencia y la rectitud —rén y yì, las dos virtudes centrales de Confucio— para que el pueblo recupere la piedad filial; en la versión de Guodian ese mismo pasaje pide abandonar el artificio y el cálculo de la ventaja, sin atacar por nombre a las virtudes confucianas. Si Guodian es anterior, entonces la polémica antiConfuciana más filosa del libro no pertenece a su capa más antigua, sino que se agudizó después, cuando taoístas y confucianos ya competían como escuelas rivales. Es el argumento material más fuerte a favor de leer el Dao De Jing como una antología en crecimiento y no como la obra de un autor."},
   {t:"Dao Jing (capítulos 1-37): el libro del Camino", d:"La primera mitad del texto recibido se ocupa sobre todo del Dao mismo y de la actitud que le corresponde. Abre con la advertencia que condiciona todo lo demás —el dao que puede decirse no es el dao constante— y sigue con el par de capítulos que introducen la interdependencia de los opuestos y la enseñanza sin palabras. Allí están las imágenes que hicieron célebre al libro: el agua que beneficia a las diez mil cosas sin competir con ninguna (capítulo 8), el vacío del cubo de la rueda y del interior de la vasija (capítulo 11), el fuelle que se vacía y no se agota (capítulo 5), lo femenino que vence a lo masculino por quietud (capítulo 6 y 28), el retorno como movimiento propio del Dao. También aparece aquí la crítica temprana al gobierno que multiplica prohibiciones, y la figura del sabio que se sitúa detrás y por eso queda delante. Es la parte más contemplativa y más citada, y también la que más fácilmente se convierte en poesía descontextualizada si se la separa de la segunda mitad."},
   {t:"De Jing (capítulos 38-81): el libro de la virtud y del gobierno", d:"La segunda mitad se vuelve más política y más polémica, y empieza con uno de los pasajes decisivos de la filosofía china: la virtud superior no se propone ser virtuosa y por eso tiene virtud; la virtud inferior no quiere perderla y por eso carece de ella. De ahí sale la cascada de degradación que cayó como una acusación sobre el confucianismo entero: perdido el Dao aparece la virtud, perdida la virtud la benevolencia, perdida la benevolencia la rectitud, perdida la rectitud el rito, y el rito es la corteza delgada de la lealtad y el comienzo del desorden. Siguen las formulaciones más concretas sobre el poder: cuantas más prohibiciones hay, más pobre es el pueblo (capítulo 57); gobernar un reino grande es como freír un pez pequeño (capítulo 60); el mejor gobernante es aquel cuya existencia el pueblo apenas nota (capítulo 17). Y aquí está la utopía minimalista del capítulo 80, con aldeas pequeñas donde se oyen los gallos del vecino y nadie va a visitarlo — una imagen que hay que discutir en serio, porque es lo más parecido a un programa que el libro ofrece y también lo más difícil de defender."}
 ],
 conceptos:[
   {t:"El Dao (el Camino)", d:"Dao significa literalmente camino, y también hablar o guiar; el libro explota esa ambigüedad desde su primera línea, donde el segundo dao del verso funciona como verbo: el camino que puede ser dicho no es el camino constante. La afirmación no es que el Dao sea misterioso y difícil, sino que cualquier nombre lo recorta, porque nombrar es distinguir y el Dao es anterior a toda distinción. Por eso el texto solo puede hablar de él en negativo o por imágenes: lo llama vacío pero inagotable, lo compara con un valle, con una hembra, con agua, con un fuelle, con algo confusamente formado que existía antes que el cielo y la tierra, y admite expresamente que no sabe su nombre y que si lo fuerza lo llama Dao. Conviene no leerlo como un dios ni como una sustancia: no crea por decisión ni premia ni castiga, y el capítulo 5 es tajante al decir que el cielo y la tierra no son benevolentes y tratan a las diez mil cosas como perros de paja. Es más bien el modo en que las cosas se producen y se deshacen por sí solas, el patrón sin legislador. Y su rendimiento filosófico está justamente ahí: si el fondo del mundo no es una norma, entonces la sabiduría tampoco puede consistir en descubrir una norma y aplicarla."},
   {t:"Wú wéi (actuar sin forzar)", d:"La traducción habitual, no acción, es la puerta de entrada al malentendido más extendido sobre el taoísmo. El texto no aconseja quedarse quieto: el sabio del capítulo 2 actúa, solo que actúa sin actuar, y el capítulo 37 formula la paradoja central diciendo que el Dao no hace nada y nada queda sin hacer. Wú wéi nombra un modo de intervención, no su ausencia: la acción que no fuerza, que no se adelanta, que no impone una forma ajena sobre lo que ya tiene su propia tendencia. Los ejemplos que el propio libro elige son laborales y no místicos —el agua que erosiona la roca sin golpearla, el cocinero que aprovecha los intersticios, el gobernante que no revuelve el pez pequeño en la sartén—, y la analogía moderna más útil es la del oficio bien aprendido: el buen carpintero no vence a la madera, la lee. Zhuangzi lo llevará a su expresión más nítida con el carnicero cuyo cuchillo dura diecinueve años porque nunca corta hueso. Queda sin embargo una dificultad real que el libro no resuelve del todo: cómo distinguir en la práctica el wú wéi de la simple pasividad, dado que ambos se parecen mucho desde afuera y solo se diferencian por un discernimiento que no puede formularse como regla."},
   {t:"Ziran (lo que es así por sí mismo)", d:"Zi es sí mismo y ran es así, de modo que ziran significa literalmente así por sí mismo, y solo de manera secundaria naturaleza o espontaneidad. Es el concepto que le da contenido al wú wéi, porque explica hacia qué se hace espacio cuando uno deja de forzar: hacia la tendencia propia de cada cosa. El capítulo 25 lo coloca en la cima de una escala sorprendente —el hombre toma por norma a la tierra, la tierra al cielo, el cielo al Dao y el Dao a ziran—, lo que significa que ni siquiera el Dao obedece a algo exterior a sí mismo: su ley es no tener otra ley que ser lo que es. Aplicado a la política da la frase más citada del capítulo 17, donde el pueblo, bajo el mejor gobernante, dice que todo salió así por sí solo. Y aplicado a la educación o a la crianza produce una tesis difícil y discutible: que el crecimiento no se produce empujando sino retirando obstáculos. La objeción obvia es que muchas cosas humanas valiosas —una lengua, un instrumento, una disciplina— no brotan solas, y responderla obliga a preguntar si ziran excluye el aprendizaje o solo el aprendizaje impuesto contra la tendencia de quien aprende."},
   {t:"El agua como modelo de virtud", d:"El capítulo 8 propone la imagen que organiza toda la ética del libro: la bondad más alta es como el agua, que beneficia a las diez mil cosas sin competir con ninguna y se aloja en los lugares bajos que todos desprecian, y por eso está cerca del Dao. Lo interesante es cuántas tesis distintas condensa esa figura. Primero, una inversión del valor: lo que ocupa el lugar bajo no es lo derrotado sino lo que recibe, como el mar es rey de los cien ríos por estar debajo de ellos. Segundo, una teoría de la eficacia: el capítulo 78 observa que nada es más blando que el agua y sin embargo nada la supera para desgastar lo duro, porque la persistencia sin resistencia vence donde el choque frontal se rompe. Tercero, una teoría de la forma: el agua no tiene figura propia y por eso puede tomar cualquiera, lo que la vuelve el emblema de la adaptabilidad frente a la rigidez. Y el libro extiende la imagen a lo vivo en el capítulo 76, donde observa que el ser humano nace blando y muere rígido, y que las plantas nacen tiernas y mueren secas, de modo que lo duro y lo fuerte son compañeros de la muerte y lo blando y lo tierno, de la vida. Conviene tratar esto como una hipótesis discutible y no como un hecho: hay dominios donde lo duro efectivamente gana, y el capítulo no los menciona."},
   {t:"Pǔ (el tronco sin tallar)", d:"Pǔ designa el bloque de madera todavía no trabajado, y nombra el estado de simplicidad anterior a las distinciones, a los oficios y a los deseos fabricados. La imagen es precisa y vale detenerse en ella: el tronco sin tallar no es un objeto pobre sino uno que conserva todas sus posibilidades, mientras que cada corte que lo convierte en vasija lo vuelve útil para una cosa y lo inhabilita para todas las demás. Por eso el capítulo 28 dice que cuando el tronco se dispersa se hacen los recipientes, y que el sabio los usa pero permanece él mismo como tronco. La consecuencia práctica está en el capítulo 19, que aconseja manifestar lo simple y abrazar lo no tallado, reducir el egoísmo y disminuir los deseos, y en el 3, que sostiene que no exhibir lo deseable mantiene al corazón del pueblo sin agitación. Aquí aparece una tensión genuina con casi toda la tradición occidental de la cultura como perfeccionamiento, y también una objeción política seria que conviene no tapar: si la simplicidad se le prescribe al pueblo desde arriba, deja de ser simplicidad y se vuelve una técnica de administración."},
   {t:"Fǎn y fù: la reversión y el retorno", d:"El capítulo 40 lo dice en cuatro caracteres que resumen la física del libro: la reversión es el movimiento del Dao, la debilidad es su función. Fǎn significa a la vez volver, invertirse y lo contrario, y esa triple carga es deliberada. Por un lado describe un ciclo: todo lo que llega a su extremo se vuelca en su opuesto, la plenitud empieza a vaciarse, lo que sube empieza a caer, y por eso el capítulo 9 aconseja retirarse cuando la obra está cumplida. Por otro describe un regreso al origen: el capítulo 16 pide alcanzar el vacío extremo y sostener la quietud para ver cómo las diez mil cosas florecen y vuelven cada una a su raíz, y llama a ese volver a la raíz quietud, y a la quietud, retorno al destino propio. La consecuencia práctica es una estrategia del no extremo: no acumular hasta el borde, no tensar el arco al máximo, no llenar la copa hasta que se derrame. Y la consecuencia teórica es una crítica a la idea de progreso indefinido, que el libro considera simplemente imposible, porque nada crece sin límite dentro de un mundo cíclico."},
   {t:"La crítica del saber artificioso y del exceso de reglas", d:"Es la parte más agresiva del libro y la que más cuesta defender. El capítulo 48 contrapone dos itinerarios: quien se dedica al estudio aumenta cada día, quien se dedica al Dao disminuye cada día, y disminuye y vuelve a disminuir hasta la no acción. El capítulo 18 sostiene que la benevolencia y la rectitud aparecieron cuando el gran Dao se perdió, y que la piedad filial se predicó cuando las familias se desunieron; el 38 convierte eso en la cascada donde el rito, última estación de la caída, es la corteza delgada de la lealtad y el comienzo del desorden; y el 19 llega a proponer que se abandone la sabiduría y se descarte el conocimiento. El argumento de fondo es el del síntoma: que una virtud tenga que enseñarse es la prueba de que ya no está viva, igual que nadie recomienda respirar. Hay que hacer aquí dos precisiones honestas. La primera es filológica: la versión de Guodian, más antigua, no nombra a la benevolencia ni a la rectitud en ese pasaje, lo que sugiere que el ataque frontal al confucianismo se endureció con el tiempo. La segunda es conceptual: lo que se rechaza no parece ser todo conocimiento, sino el conocimiento como acumulación, cálculo y astucia — zhì en su sentido de habilidad para sacar ventaja. Aun así queda en pie la objeción que el texto se hace a sí mismo sin quererlo, porque también él es una enseñanza."},
   {t:"Los opuestos que se generan mutuamente", d:"El capítulo 2 formula la lógica que sostiene todo el libro: cuando todos en el mundo reconocen lo bello como bello, ya aparece lo feo; cuando todos reconocen lo bueno como bueno, ya aparece lo no bueno. Y enumera los pares: ser y no ser se engendran, difícil y fácil se completan, largo y corto se miden uno por otro, alto y bajo se inclinan uno hacia otro, sonido y voz se armonizan, antes y después se siguen. La tesis tiene dos filos. El primero es semántico: los términos valorativos no describen propiedades independientes sino que se instituyen de a pares, de modo que fabricar una distinción es fabricar simultáneamente su reverso. El segundo es práctico: exaltar un polo produce su contrario, y por eso el capítulo 3 sostiene que no ensalzar a los capaces evita la rivalidad. Aunque el libro no usa los términos yin y yang —que son del vocabulario cosmológico posterior, sistematizado sobre todo en el comentario al Yijing y en la escuela de Zou Yan—, el capítulo 42 los menciona al decir que las diez mil cosas llevan el yin a la espalda y abrazan el yang, y el esquema de la complementariedad polar quedó desde entonces asociado al taoísmo. Vale discutir si la tesis prueba demasiado: si toda distinción genera su opuesto, tampoco podría distinguirse el Dao de su pérdida, y sin embargo el libro lo hace constantemente."},
   {t:"El gobernante que gobierna sin gobernar", d:"La política del Dao De Jing es a la vez su parte más concreta y su parte más incómoda. Su escala de gobiernos, en el capítulo 17, va de mejor a peor: del mejor gobernante el pueblo apenas sabe que existe; al siguiente lo ama y lo elogia; al siguiente lo teme; al último lo desprecia — y cuando la obra está hecha, el pueblo dice que ocurrió así por sí solo. El mecanismo aparece en el capítulo 57: cuantas más prohibiciones hay en el reino, más pobre es el pueblo; cuantas más leyes se promulgan, más ladrones aparecen; por eso el sabio dice yo no actúo y el pueblo se transforma por sí mismo, amo la quietud y el pueblo se endereza por sí mismo. Y en el 66 se explica la posición del gobernante: los ríos y los mares son reyes de los cien valles porque están por debajo de ellos, de modo que quien quiere estar arriba debe ponerse abajo en sus palabras. Ahora bien, hay que leer también lo que incomoda. El capítulo 3 recomienda vaciar los corazones del pueblo y llenar sus estómagos, debilitar su voluntad y fortalecer sus huesos, y mantenerlo sin conocimiento ni deseo; y el capítulo 65 dice que los antiguos que sabían gobernar no ilustraban al pueblo sino que lo mantenían simple. Hay lecturas que ven allí una crítica al adoctrinamiento y otras que ven una receta de despolitización, y la historia posterior da munición a ambas, porque de esta misma raíz salió tanto el quietismo del Huang-Lao como el legalismo autoritario de Han Fei, que cita a Laozi con entusiasmo."}
 ],
 conexion:"<b>Zhuangzi</b> hereda el núcleo y le cambia el tono: donde el Dao De Jing aconseja al gobernante, él se ríe de los cargos, multiplica las parábolas y lleva el perspectivismo hasta poner en duda que haya un punto de vista privilegiado desde el cual juzgar. En dirección opuesta, <b>Confucio</b> es el interlocutor permanente y silencioso del libro: los capítulos 18, 19 y 38 son legibles como una réplica directa a la idea de que la virtud se cultiva por el rito, y el debate entre formar el carácter y no estorbar la naturaleza atraviesa toda la historia intelectual china. Su crítica del exceso de reglas y su preferencia por el fondo indecible lo acercan además, con todas las distancias del caso, al <b>Wittgenstein</b> del Tractatus que termina mandando callar sobre aquello de lo que no se puede hablar, y su desconfianza de la civilización lo puso en diálogo con lecturas modernas de la técnica como las de <b>Heidegger</b>, que leyó el texto con interés y llegó a intentar traducirlo.",
 dialogo:{titulo:"En el paso de la frontera", lineas:[
   {quien:"Yin Xi", texto:"No lo dejo pasar hasta que escriba algo. Si se va al oeste y se pierde entre las montañas, nadie va a saber qué pensaba."},
   {quien:"Laozi", texto:"Justamente por eso quería irme sin escribir. Lo que puede decirse del camino no es el camino. Si te dejo cinco mil caracteres, mañana alguien los va a memorizar y creerá que ya llegó."},
   {quien:"Yin Xi", texto:"Entonces escriba eso primero, en la primera línea, y que cada lector cargue con la advertencia."},
   {quien:"Laozi", texto:"Está bien. Pero sabé lo que estás pidiendo: un libro que pide abandonar el conocimiento y que es él mismo un objeto de estudio.", nota:"La escena es legendaria y proviene de la biografía que Sima Qian escribió cuatro siglos después, ya con dudas propias: el historiador ofrece tres candidatos distintos para el personaje y admite que no sabe cuál es. La leyenda, sin embargo, condensa un problema filosófico real y no decorativo, que es la autorrefutación aparente de una enseñanza contra las enseñanzas."},
   {quien:"Funcionario de Lu", texto:"Permítanme. Vengo de una corte donde se estudia el rito y me llegan sus frases. Dicen que la benevolencia apareció cuando el Dao se perdió. ¿Qué propone a cambio, que nadie enseñe nada?"},
   {quien:"Laozi", texto:"Propongo mirar de dónde salen tus virtudes. Nadie predica respirar. Cuando hay que insistir tanto en que los hijos honren a los padres, ya pasó algo con las familias."},
   {quien:"Funcionario de Lu", texto:"Eso es un diagnóstico, no un remedio. La enfermedad existe. Nosotros proponemos el rito para curarla. Usted propone quedarse quieto mientras se agrava."},
   {quien:"Laozi", texto:"No dije quedarse quieto. Dije no forzar. Son cosas distintas y las confunde todo el mundo. ¿Vos regás una planta tirándole de las hojas para que crezca más rápido?"},
   {quien:"Funcionario de Lu", texto:"Claro que no."},
   {quien:"Laozi", texto:"Y sin embargo la regás, la ponés al sol, la protegés del viento. Eso es wú wéi: intervenir siguiendo la tendencia, no contra ella. El que no hace nada y el que no fuerza se parecen desde afuera, pero uno abandona la planta y el otro la conoce."},
   {quien:"Funcionario de Lu", texto:"Bien. Ahora dígame cómo distingo un caso del otro sin tener que ser usted. Deme un criterio. Porque si no lo hay, cualquier cobarde va a llamar sabiduría a su comodidad."},
   {quien:"Laozi", texto:"No tengo un criterio que puedas aplicar sin haber mirado mucho. Si te lo diera, sería otra regla más, y las reglas son justamente lo que multiplica los ladrones.", nota:"Esta es la objeción más seria contra el wú wéi y el libro no la responde del todo. Un lector honesto debe registrar que aquí hay un problema abierto, compartido además con la phronesis aristotélica: toda ética que rechaza el algoritmo queda expuesta a que se la use como excusa. La diferencia es que Aristóteles al menos nombra un árbitro, el hombre prudente, mientras el Dao De Jing prefiere no nombrar a nadie."},
   {quien:"Yin Xi", texto:"Maestro, yo guardo un paso de montaña. Si aplico su consejo y dejo de revisar a los viajeros, entran las armas."},
   {quien:"Laozi", texto:"Entonces revisalos. Nunca dije que un guardia no guarde. Dije que el reino que agrega una prohibición por semana termina con más ladrones que antes, y eso lo podés verificar sin creerme."},
   {quien:"Funcionario de Lu", texto:"Y si el gobernante es un tirano, ¿también hay que dejar que las cosas sigan su curso?"},
   {quien:"Laozi", texto:"Lo duro y lo fuerte son compañeros de la muerte. Ninguna tensión extrema se sostiene: el arco demasiado tenso se rompe solo. Yo no aconsejo el golpe frontal, aconsejo el agua."},
   {quien:"Funcionario de Lu", texto:"El agua tarda siglos en perforar una piedra. Los que están debajo del tirano tienen una vida."},
   {quien:"Laozi", texto:"Esa es la mejor cosa que me dijiste. Anotala vos también, Yin Xi, junto a lo demás. Un libro que solo contenga lo que su autor piensa no sirve para nada."}
 ]},
 actividades:[
   {t:"Inventario de lo que se rompió por empujar", d:"Elegí dos episodios reales de tu vida de los últimos dos años, no hipotéticos. En el primero forzaste algo: insististe en una conversación, apuraste una decisión, corregiste a alguien antes de tiempo, presionaste por un resultado, y salió peor que si no hubieras intervenido. En el segundo cediste, esperaste, rodeaste el obstáculo o no dijiste nada, y funcionó mejor de lo esperado. Escribí cada uno en diez líneas, con hechos y fechas, sin moraleja. Después hacé el trabajo filosófico, que empieza recién ahora: buscá un tercer caso donde ceder fue claramente lo peor que pudiste hacer, y un cuarto donde forzar fue lo correcto. Con los cuatro casos delante, intentá formular por escrito qué rasgo tienen en común los dos primeros y qué rasgo tienen los dos últimos. Si no lográs formular ninguna diferencia clara, ese resultado también sirve y hay que anotarlo: es exactamente la objeción del funcionario en el diálogo, y dejarla en pie con honestidad vale más que fabricar un criterio que no tenés."},
   {t:"Quince minutos de agua, con el capítulo 8 al lado", d:"Buscá agua real y quedate mirándola quince minutos sin teléfono: un río, la lluvia sobre una vereda, el agua del lavabo cayendo sobre un plato, el mar, un charco que se escurre. Anotá durante ese rato todo lo que hace, en términos puramente descriptivos y sin usar la palabra Tao ni ninguna palabra elevada: por dónde pasa, qué rodea, qué arrastra, dónde se detiene, qué forma toma, cuánto tarda. Después abrí el capítulo 8 y el 78 y hacé dos columnas. En la primera anotá cada virtud que el texto le atribuye al agua: beneficiar sin competir, ocupar el lugar bajo que otros desprecian, ser lo más blando y vencer a lo más duro. En la segunda, anotá si tu observación la confirma, la matiza o la contradice. Terminá con un párrafo sobre lo que el texto no dice: el agua también inunda, erosiona lo que no debería, se estanca y se pudre. Preguntate si esas conductas también son parte del modelo o si el capítulo eligió solo las que le convenían, y qué implica eso para el método de pensar con imágenes."},
   {t:"Un día de tronco sin tallar", d:"Elegí una sola reacción automática tuya que puedas identificar con precisión: responder mensajes al instante, corregir un dato cuando alguien se equivoca, llenar los silencios en una conversación, opinar sin que te pregunten, chequear el teléfono al despertar, dar un consejo apenas alguien cuenta un problema. Durante un día entero, cada vez que aparezca el impulso, no lo ejecutes y anotá tres cosas en el momento: la hora, qué sentiste en el cuerpo y qué pasó después en la situación sin tu intervención. No se trata de reprimirse con esfuerzo heroico sino de observar el impulso y dejarlo pasar, que es la diferencia entre disciplina y wú wéi. Al final del día escribí dos páginas. La primera sobre lo que efectivamente se resolvió solo y lo que no. La segunda, más difícil y más interesante, sobre qué fue exactamente lo costoso: si te costó el silencio, si te costó no ser visto como útil, si te costó la incertidumbre de no controlar el resultado. Esa respuesta te dice qué está tallado en tu tronco y por quién."}
 ],
 cuestionario:[
   {q:"¿El wú wéi es compatible con alguna forma de acción política, o termina aconsejando quietismo frente a la injusticia?", p:"Hay que tomar la objeción en serio porque el propio texto la alimenta. El capítulo 3 aconseja mantener al pueblo sin conocimiento ni deseo, el 65 dice que los antiguos que sabían gobernar no ilustraban al pueblo sino que lo mantenían simple, y el 80 dibuja aldeas diminutas sin comercio ni viajes. De ahí salieron históricamente dos linajes opuestos: el Huang-Lao de comienzos de la dinastía Han, que tradujo el wú wéi en una política real de impuestos bajos y no intervención, y Han Fei, el gran teórico legalista, que comentó el Dao De Jing y usó la quietud del soberano como técnica de dominación insondable. La defensa disponible es que wú wéi no significa inacción sino acción no forzada, y que el libro contiene una crítica del poder excesivo tan filosa como cualquier otra en la Antigüedad: cuantas más leyes, más ladrones; el mejor gobernante es el que apenas se nota. El problema que queda en pie es que la doctrina se dirige siempre al que manda y casi nunca al que obedece: aconseja al gobernante hacer menos, no enseña al oprimido qué hacer. Quien quiera usar el taoísmo políticamente tiene que suplir esa ausencia, y lecturas contemporáneas de resistencia no violenta lo intentan; pero conviene reconocer que es una extensión y no una lectura literal."},
   {q:"Si el Dao no puede nombrarse y el libro aconseja descartar el conocimiento, ¿cómo puede escribirse y enseñarse sin contradecirse?", p:"Es la objeción de autorrefutación y admite al menos tres respuestas de distinta fuerza. La primera, tradicional, es la del dedo que señala la luna: el texto no describe el Dao sino que orienta hacia una experiencia, y una vez orientado el lector el texto sobra, como la trampa sobra una vez pescado el pez, según la formulación que dará Zhuangzi. La segunda es formal y más interesante: el Dao De Jing no argumenta, usa paradojas, rimas, imágenes y negaciones, precisamente porque el discurso descriptivo es lo que está en cuestión; su forma es parte de su tesis, igual que en Wittgenstein la escalera que se tira después de subir. La tercera es filológica y desinfla un poco el problema: lo que el capítulo 19 rechaza en su versión más antigua, la de Guodian, no es el conocimiento sino el artificio y el cálculo de ventaja, de modo que la contradicción sería en parte un efecto de la capa polémica posterior. Aun así la dificultad no desaparece del todo: quien lee cinco mil caracteres sobre la inutilidad de las palabras está haciendo exactamente lo que el libro desaconseja, y el libro lo sabe. Que lo sepa no lo exime; a lo sumo lo vuelve un problema deliberado en lugar de un descuido."},
   {q:"Confucio sostiene que la virtud se forma practicando ritos heredados; Laozi dice que el rito aparece cuando ya se perdió todo. ¿Es una oposición real o dos descripciones del mismo proceso?", p:"La oposición es real pero comparten la premisa, que es lo que la vuelve interesante. Los dos aceptan que el rito surge de una carencia: Confucio también sabe que se enseña la benevolencia porque falta. Difieren en la conclusión. Para Confucio no hay otro camino de vuelta que la práctica, porque el carácter se forma con las manos antes que con la cabeza y la espontaneidad invocada por los taoístas es también, mirada de cerca, una cultura que se desconoce a sí misma: la lengua materna tampoco se eligió. Para Laozi, la práctica del rito perpetúa la carencia en lugar de curarla, porque convierte en obligación externa lo que debía ser tendencia propia, y la cascada del capítulo 38 describe una degradación irreversible. Un modo productivo de no elegir apresuradamente es preguntar por dominios: en el aprendizaje de un oficio, de un instrumento o de una lengua, el confuciano parece tener claramente razón; en la sinceridad de un afecto o en la disposición a ayudar, la sospecha taoísta muerde más fuerte. Y conviene registrar que la historia china no los trató como excluyentes: el mismo funcionario podía ser confuciano en el cargo y taoísta al retirarse, y esa convivencia de siglos es un dato filosófico y no solo sociológico."},
   {q:"Lo blando vence a lo duro. ¿Es una tesis verdadera o una imagen bonita que solo retiene los casos favorables?", p:"Conviene tratarla como hipótesis y examinarla con dureza, que es lo contrario de lo que suele hacerse con ella. A favor hay casos genuinos y no triviales: el agua efectivamente desgasta la roca, las estructuras flexibles resisten los terremotos mejor que las rígidas, las artes marciales internas aprovechan la fuerza del otro en lugar de oponerle otra fuerza, las negociaciones que no exigen rendición incondicional suelen durar más, y los materiales que no ceden nada son los que se fracturan. En contra está el sesgo de selección, que es evidente: por cada roca perforada por el agua hay incontables gotas evaporadas sin dejar marca, y una represa detiene un río sin mayor dificultad. También hay un problema de escala temporal, y es el que plantea el funcionario al final del diálogo: si lo blando vence pero tarda siglos, la tesis puede ser verdadera y aun así inútil para quien vive ahora. La formulación más defendible es más modesta que la del texto: en sistemas donde la confrontación directa consume al que la ejerce, la persistencia flexible tiene mejor rendimiento a largo plazo. Eso es bastante menos poético y bastante más comprobable, y perder el verso a cambio de poder ponerla a prueba es un intercambio que vale la pena discutir en clase."},
   {q:"Si Laozi probablemente no existió como individuo y el Dao De Jing es una antología de siglos, ¿cambia eso en algo el valor del texto?", p:"Para evaluar los argumentos, poco o nada: una tesis sobre el wú wéi es tan fuerte o tan débil la haya escrito un archivero de Zhou o doscientos años de transmisión oral. Pero para leer bien, cambia bastante, y en tres sentidos concretos. Primero, deja de ser legítimo explicar una contradicción interna apelando a la evolución del pensamiento del autor, porque no hay un autor cuyo pensamiento evolucione: las tensiones del libro son más probablemente huellas de manos distintas y de discusiones sucesivas. Segundo, obliga a datar las capas antes de usarlas, y el caso de Guodian lo muestra bien, porque el ataque nominal a la benevolencia y la rectitud parece pertenecer a un estrato posterior, cuando taoístas y confucianos ya eran escuelas rivales; leer el capítulo 19 recibido como si fuera del siglo VI a.C. es un error histórico con consecuencias interpretativas. Tercero, pone en cuestión la idea misma de obra: el Dao De Jing se parece más a un caudal que a un edificio, y quizá sea el único texto clásico cuya forma de existir ilustra su propio contenido. La comparación con Homero y con las Analectas es útil, porque en los tres casos la crítica moderna disolvió a un autor único y en ninguno de los tres el texto perdió lectores. Lo que se pierde es la biografía; lo que se gana es dejar de confundir un libro con un hombre."}
 ],
 cadena:{ titulo:"¿No hacer es una manera de hacer?", intro:"Un razonamiento en ramas sobre la paradoja que el propio Dao De Jing pone en el centro: el Dao no actúa y nada queda sin hacer. Si el wú wéi da resultados, ¿no es simplemente una estrategia más astuta? Y si no persigue resultados, ¿para qué aconsejarlo? Las ramas llevan a lecturas históricas reales del libro, incluida la del legalista Han Fei.", inicio:"n1", nodos:{
   n1:{ pregunta:"El capítulo 37 dice que el Dao no actúa y nada queda sin hacer; el 48, que quien se dedica al Dao disminuye cada día hasta llegar al no actuar, y que no actuando nada queda sin hacer. ¿Cómo leés esa fórmula?", opciones:[
     {texto:"Como una estrategia: no forzar es el medio más eficaz para que todo se haga.", va:"n2a"},
     {texto:"Como una descripción: el Dao no persigue fines; que todo se haga no es su objetivo, es lo que ocurre cuando nadie fuerza.", va:"n2b"} ]},
   n2a:{ pregunta:"El capítulo 7 parece darte la razón: el sabio se pone detrás y queda delante, se pone afuera y se conserva; «¿no es porque no busca lo suyo que puede realizar lo suyo?». Ahora imaginá a alguien que se pone detrás para quedar delante. ¿Es lo mismo?", opciones:[
     {texto:"Sí: el resultado es el mismo, y el texto lo promete.", va:"n3a"},
     {texto:"No: el texto dice «porque», no «para». Quien se retira para ganar no se retiró de verdad.", final:{tipo:"bien", texto:"Leíste bien la gramática del capítulo 7: la ganancia aparece como efecto de no buscarla, no como su finalidad. Es una estructura que la filosofía occidental conoce como paradoja del hedonismo —quien persigue directamente la felicidad suele perderla— y que aquí se aplica a la eficacia misma. Fijate el problema que te queda: si el lector del libro ya sabe que no buscar produce resultados, ¿puede todavía no buscarlos? Esa es la pregunta de la otra rama."}} ]},
   n3a:{ pregunta:"Es exactamente como lo leyó Han Fei, el gran teórico legalista, que dedicó dos capítulos a comentar el Dao De Jing: el soberano que no muestra deseos ni preferencias para que nadie pueda manipularlo, y que desde esa quietud controla todo. Pero el capítulo 38 dice que la virtud superior no se propone ser virtuosa, y por eso tiene virtud. ¿Puede un no-hacer calculado seguir siendo wú wéi?", opciones:[
     {texto:"No: en cuanto el no-hacer se vuelve medio, es un hacer disfrazado, y el cálculo arruina lo que buscaba.", final:{tipo:"bien", texto:"Llegaste a lo que Edward Slingerland llamó la paradoja del wú wéi: si la espontaneidad es valiosa, intentar alcanzarla parece destruirla, y si no se la intenta, no se ve cómo llegar a ella. Tu respuesta toma en serio el capítulo 38 y rechaza la lectura de Han Fei, que convierte la quietud en técnica de dominación. El precio es que el libro queda sin instrucciones utilizables: aconseja un estado que no se puede buscar."}},
     {texto:"Sí: el cálculo puede estar al comienzo y desaparecer con la práctica, como en el aprendizaje de un oficio.", final:{tipo:"bien", texto:"Es una salida seria: la espontaneidad sería el punto de llegada de un entrenamiento, como el músico que ya no piensa en los dedos. Pero notá hacia dónde te lleva: esa es casi exactamente la tesis de Confucio, para quien la forma practicada durante décadas termina siendo naturaleza, y es la que el Dao De Jing ataca en los capítulos 18, 19 y 38. Si el wú wéi se aprende practicando, la distancia entre taoístas y confucianos se achica más de lo que ambos admitirían."}} ]},
   n2b:{ pregunta:"Si el Dao no persigue fines, ¿qué le queda al gobernante del libro, al que se le dan consejos todo el tiempo (capítulos 17, 57, 60)?", opciones:[
     {texto:"Aprender a no estorbar: casi todos sus consejos son negativos —menos prohibiciones, menos impuestos, menos exhibición—.", va:"n3b"},
     {texto:"Nada: si el libro da consejos, contradice su propia descripción, y el wú wéi es inaplicable.", final:{tipo:"revisar", texto:"Antes de declarar el wú wéi inaplicable, mirá el capítulo 64: actuá sobre las cosas antes de que existan, ordená antes de que haya desorden; el árbol que llena los brazos nació de un brote diminuto. El libro no aconseja la inacción sino una acción de cierto tipo: temprana, pequeña, sin forcejeo. Es una instrucción aplicable, aunque exija un discernimiento que no puede formularse como regla. Volvé un paso y tomá la otra opción."}} ]},
   n3b:{ pregunta:"Pero no estorbar también es una decisión, y el capítulo 64 pide actuar antes de que las cosas existan. ¿Cómo encaja eso con el Dao que no actúa?", opciones:[
     {texto:"Wú wéi no es no intervenir sino intervenir temprano y poco, cuando lo pequeño todavía es fácil.", final:{tipo:"bien", texto:"Es la lectura práctica más sólida: el problema no es la acción sino la acción tardía y forzada, la que tiene que vencer una resistencia que ella misma dejó crecer. Freír un pez pequeño sin revolverlo (capítulo 60) no es no cocinar. El precio es que el criterio queda en manos de quien sabe ver lo pequeño a tiempo, y el funcionario del diálogo tiene razón en reclamar que eso no se puede enseñar como una regla."}},
     {texto:"Encaja mal, y no hace falta que encaje: el libro es una antología de dichos, no un sistema.", final:{tipo:"bien", texto:"Es la lectura que toma en serio la filología: el Dao De Jing se formó durante uno o dos siglos, y los manuscritos de Guodian y Mawangdui muestran un texto todavía en movimiento. No todas sus frases tienen que decir lo mismo. La ventaja es que te libera de armonizaciones forzadas; el riesgo es usar la antología como excusa para no pensar la tensión, que en este caso es filosófica y no solo editorial: toda doctrina del no forzar necesita decir qué hacer mientras tanto."}} ]}
 }},
 reconstruccion:[
   { titulo:"La utilidad del vacío (Dao De Jing, capítulo 11)",
     consigna:"Reconstruí el argumento del capítulo 11, que va de tres objetos cotidianos a una tesis general sobre el ser y el no ser. Una pieza saca una conclusión que el texto no autoriza: dejala afuera.",
     piezas:[
       {id:"l1", texto:"Treinta radios convergen en un cubo: es en su vacío donde está la utilidad del carro.", tipo:"premisa"},
       {id:"l2", texto:"Se amasa arcilla para hacer una vasija: es en su vacío donde está la utilidad de la vasija.", tipo:"premisa"},
       {id:"l3", texto:"Se abren puertas y ventanas para hacer una habitación: es en su vacío donde está la utilidad de la habitación.", tipo:"premisa"},
       {id:"l4", texto:"En los tres casos, lo que se fabrica es lo lleno —los radios, la arcilla, los muros—, pero lo que se usa es el vacío que eso lleno delimita.", tipo:"premisa"},
       {id:"l5", texto:"Por lo tanto, lo que hay (yǒu) proporciona el beneficio, y lo que no hay (wú) proporciona la utilidad: el vacío no es lo que falta, sino lo que hace funcionar.", tipo:"conclusion"},
       {id:"lx", texto:"Y como lo que sirve es el vacío, conviene reducir al mínimo los radios, la arcilla y los muros: cuanto menos lleno, más útil.", tipo:"distractor"}
     ],
     ordenCorrecto:["l1","l2","l3","l4","l5"],
     explicacion:"El argumento es una inducción sobre tres casos (l1-l3) que l4 generaliza y l5 convierte en tesis. Lo decisivo de la conclusión es que es complementaria, no una inversión simple: yǒu y wú trabajan juntos, uno da el beneficio y el otro la función, igual que en el capítulo 2 los opuestos se generan mutuamente. La pieza sobrante toma solo la mitad de la tesis y la lleva al extremo: una vasija sin arcilla no tiene ningún vacío útil, porque el vacío solo existe delimitado. Para discutir: el capítulo parece hablar de objetos, pero se lee también en clave política —el gobernante que deja espacio— y en clave metafísica —el no ser del que surge el ser (capítulo 40)—, que es la que Wang Bi convirtió en el centro de su comentario. ¿Autoriza el ejemplo del carro esas extensiones?"},
   { titulo:"Lo blando vence a lo duro (Dao De Jing, capítulos 76 y 78)",
     consigna:"Reconstruí el argumento que va de la observación de lo vivo y lo muerto a la tesis de que lo blando vence a lo duro. Una pieza usa las palabras «fuerte» y «débil» en otro argumento del libro: dejala afuera.",
     piezas:[
       {id:"b1", texto:"El ser humano nace blando y flexible, y al morir queda duro y rígido.", tipo:"premisa"},
       {id:"b2", texto:"Las plantas y los árboles nacen tiernos y flexibles, y al morir quedan secos y quebradizos.", tipo:"premisa"},
       {id:"b3", texto:"Por eso lo duro y lo fuerte son compañeros de la muerte, y lo blando y lo débil, compañeros de la vida.", tipo:"premisa"},
       {id:"b4", texto:"Así, el ejército que se endurece no vence, y el árbol que se vuelve rígido es talado.", tipo:"premisa"},
       {id:"b5", texto:"Y nada en el mundo es más blando y débil que el agua, pero para atacar lo duro y lo fuerte nada la supera.", tipo:"premisa"},
       {id:"b6", texto:"Por lo tanto, lo débil vence a lo fuerte y lo blando vence a lo duro: todo el mundo lo sabe, y nadie lo pone en práctica.", tipo:"conclusion"},
       {id:"bx", texto:"Por eso el sabio, al gobernar, vacía los corazones del pueblo y llena sus estómagos, debilita su voluntad y fortalece sus huesos.", tipo:"distractor"}
     ],
     ordenCorrecto:["b1","b2","b3","b4","b5","b6"],
     explicacion:"El argumento combina dos observaciones naturales (b1-b2) en una generalización (b3), la aplica a la guerra y a la tala (b4), y la corona con el caso del agua (b5), que invierte la intuición: lo más blando es lo más eficaz contra lo duro. La conclusión del capítulo 78 agrega un matiz que suele omitirse: el problema no es que no se sepa, sino que no se practica. La pieza sobrante viene del capítulo 3 y también habla de fuerza y debilidad, pero en un sentido opuesto y políticamente inquietante: allí el sabio debilita la voluntad del pueblo, que es una técnica de gobierno, no una teoría de la eficacia de lo flexible. Para discutir: la inferencia de b1-b2 a b3 confunde correlación con causa —lo muerto es rígido, pero la rigidez no mata—, y b5 selecciona los casos favorables: una represa detiene al río sin dificultad."}
 ],
 dilemas:[
   { titulo:"El comedor que funciona solo",
     intro:"En el diálogo, el funcionario de Lu le pide a Laozi un criterio para distinguir el no forzar del no hacer nada, porque sin él cualquier cobarde llamará sabiduría a su comodidad; y Laozi admite que no tiene uno que pueda aplicarse sin haber mirado mucho. Este caso te pone en el lugar del gobernante, con una institución pequeña, reglas que se multiplican y un problema que no se resuelve solo.",
     pasos:[
       { id:"p1", situacion:"Asumís la coordinación de un comedor comunitario que funciona hace diez años con voluntarias. Tiene un desorden visible: los turnos se arreglan por mensajes, no hay registro de donaciones, cada una cocina a su manera. Pero en diez años nunca faltó la comida. La municipalidad, que aporta fondos, te pide «profesionalizarlo»: planillas, protocolos, controles. ¿Qué hacés la primera semana?", opciones:[
         {texto:"Implemento todo de una vez: planillas, turnos fijos, reglamento escrito.", consecuencia:"Es exactamente lo que el capítulo 57 describe: cuantas más prohibiciones, más pobre el pueblo; cuantas más leyes, más ladrones. Y el 60: gobernar un reino grande es como freír un pez pequeño, y el que lo revuelve mucho lo deshace. No sabés todavía qué hacía funcionar al comedor, y ya lo reemplazaste.", va:"p2a"},
         {texto:"No cambio nada la primera semana: miro cómo funciona de verdad.", consecuencia:"Es wú wéi en su forma más elemental: antes de actuar, leer la veta. No es no hacer nada; es posponer el forcejeo hasta saber contra qué forcejearías. El riesgo, que conviene tener presente, es que la observación se vuelva indefinida.", va:"p2b"},
         {texto:"Anuncio que no voy a intervenir en nada: el comedor se ordena solo.", consecuencia:"Es la confusión que Laozi le reprocha al funcionario: no forzar no es abandonar. En el diálogo lo dice sin rodeos: nunca dije que un guardia no guarde. Declarar de antemano que no vas a intervenir no es seguir la tendencia de las cosas; es renunciar a verla.", va:"p2b"} ]},
       { id:"p2a", situacion:"Dos voluntarias históricas renuncian: «Ahora esto parece una oficina». Otras se quedan pero dejan de proponer cosas. La municipalidad está conforme con las planillas. ¿Qué hacés?", opciones:[
         {texto:"Mantengo el sistema: la gente se acostumbra.", consecuencia:"Puede ser que se acostumbren. El capítulo 17 describe esa escala: del mejor gobernante el pueblo apenas sabe que existe; al siguiente lo ama; al siguiente lo teme. Un orden que funciona por cumplimiento es real, pero ya no es el que tenías: perdiste la parte que se ordenaba sola.", va:"p3"},
         {texto:"Retiro la mitad de las reglas y pregunto cuáles hacían falta de verdad.", consecuencia:"Es el movimiento del capítulo 48: disminuir y volver a disminuir. No es volver al punto de partida, porque ahora sabés qué reglas dañaban y cuáles cubrían una necesidad real. Reconocer un exceso propio también es parte del no forzar.", va:"p3"} ]},
       { id:"p2b", situacion:"Después de dos semanas mirando, ves que el sistema informal funciona sorprendentemente bien, salvo en una cosa: una voluntaria, Marta, controla de hecho todas las donaciones y hay indicios serios de que se lleva mercadería. Nadie dice nada, porque «así funcionó siempre». ¿Intervenís?", opciones:[
         {texto:"Sí, de frente: reunión general y denuncia.", consecuencia:"Tenés razón en que hay algo que no se resuelve solo. Pero el capítulo 58 describe al sabio como recto sin cortar, afilado sin herir: un choque frontal en una red de diez años puede romper mucho más que lo que querías reparar, y todavía no tenés certeza. Lo duro y lo fuerte, dice el 76, son compañeros de la muerte.", va:"p3"},
         {texto:"Sí, pero sin choque: cambio la estructura para que las donaciones las registren dos personas rotativas, sin acusar a nadie.", consecuencia:"Es la respuesta más taoísta: como el agua, rodeás el obstáculo y cambiás el cauce en lugar de golpear la piedra; actuás temprano y en pequeño (capítulo 64). Pero hacete la pregunta incómoda: si Marta efectivamente robó, ¿la comunidad no tiene derecho a saberlo? El wú wéi no dice nada sobre eso.", va:"p3"},
         {texto:"No: si el comedor funciona, no me corresponde tocar lo que funciona.", consecuencia:"Es lo que el funcionario de Lu temía: la comodidad disfrazada de sabiduría. El comedor funciona para quienes comen, pero no para los donantes cuya mercadería desaparece. No intervenir aquí no es seguir la tendencia de las cosas: es dejar que un desequilibrio crezca hasta que solo pueda resolverse con fuerza.", va:"p3"} ]},
       { id:"p3", situacion:"A fin de año, la municipalidad te pide un informe: ¿cuál fue tu mayor logro? ¿Qué respondés?", opciones:[
         {texto:"«Que casi no se notó que había una coordinadora.»", consecuencia:"Es literalmente el ideal del capítulo 17 y del capítulo 2: la obra cumplida no se atribuye. Pero notá la tensión institucional: un logro invisible es también un logro que no se puede evaluar ni financiar. El Dao De Jing le habla a un gobernante que no rinde cuentas a nadie; vos sí las rendís.", va:null},
         {texto:"Presento cifras: raciones servidas, donaciones registradas, protocolos implementados.", consecuencia:"Es lo que la institución puede leer, y no está mal. Pero preguntate si esas cifras describen lo que hizo funcionar al comedor o solo lo que se podía contar. El capítulo 3 advierte que exhibir lo deseable despierta la competencia por conseguirlo: si lo medido se vuelve la meta, el comedor empezará a trabajar para el informe.", va:null},
         {texto:"«No sé si fue mío: algunas cosas se ordenaron solas y otras las forcé. Te cuento cuáles.»", consecuencia:"Es la respuesta que mejor contesta la pregunta del funcionario: distinguir caso por caso qué se resolvió sin forzar y qué necesitó intervención. No es un criterio general, pero es el único tipo de saber que el libro considera posible, el que se obtiene mirando mucho.", va:null} ]}
     ],
     rubrica:[
       "Distinguí en cada paso entre no forzar (wú wéi) y no hacer nada, y puedo decir qué diferenció una cosa de la otra en mi caso.",
       "Observé cómo funcionaba el sistema antes de cambiarlo, y registré qué información me dio esa espera.",
       "Identifiqué qué reglas agregaban orden real y cuáles solo agregaban control (capítulo 57).",
       "Frente a la sospecha sobre Marta, no usé el wú wéi como excusa para evitar un conflicto que había que atender.",
       "Consideré intervenir temprano y en pequeño (capítulo 64) antes que tarde y con fuerza.",
       "Reconocí la tensión entre el gobernante que apenas se nota (capítulo 17) y la exigencia de rendir cuentas.",
       "Formulé la objeción del funcionario de Lu —sin criterio, cualquier comodidad se llama sabiduría— y dije si mi decisión la resiste."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.laozi = { lecturas:[
 {titulo:"Tao Te Ching: el Tao innombrable y el wú wéi", fuente:"Selfdefinition.org — Tao Te Ching, versión en español (PDF)", url:"https://selfdefinition.org/tao/Tao-te-ching-espanol.pdf",
  extracto:`El capítulo 1 pone una advertencia antes de cualquier doctrina: «El Tao que puede ser expresado no es el Tao eterno. El nombre que puede ser nombrado no es el nombre eterno. Lo que no tiene nombre es el principio del cielo y de la tierra; lo que tiene nombre es la madre de las diez mil cosas». El texto se declara insuficiente desde su primera línea: todo lo que sigue son señales, no definiciones.

El capítulo 2 introduce la interdependencia de los opuestos, que es la lógica de fondo del libro: «cuando todos en el mundo reconocen lo bello como bello, aparece lo feo; cuando todos reconocen lo bueno como bueno, aparece lo no bueno. Ser y no ser se generan mutuamente; difícil y fácil se completan; largo y corto se miden entre sí; alto y bajo se inclinan uno hacia otro». Las distinciones no describen el mundo: lo cortan. Por eso el sabio «actúa sin actuar y enseña sin palabras».

El wú wéi —la no acción— se explica mejor con las imágenes de agua y vacío que con definiciones. Capítulo 8: «la bondad suprema es como el agua; el agua beneficia a las diez mil cosas y no compite; se aloja en los lugares que todos desdeñan, y por eso está cerca del Tao». Capítulo 78: «nada en el mundo es más blando y débil que el agua, y sin embargo nada la supera para atacar lo duro y lo fuerte». El poder no está en la dureza sino en la flexibilidad que persiste.

El capítulo 11 hace el mismo movimiento con el vacío: «treinta radios convergen en el cubo de una rueda, y es el vacío del centro lo que hace útil al carro. Se moldea la arcilla para hacer una vasija, y es el hueco interior lo que la hace útil. Se abren puertas y ventanas en una casa, y es el espacio vacío lo que la hace habitable. Por eso, del ser viene el provecho, y del no ser, la utilidad».

La crítica al exceso de gobierno es una consecuencia directa. Capítulo 57: «cuantas más prohibiciones haya en el reino, más pobre será el pueblo; cuantas más leyes y decretos se promulguen, más ladrones y bandidos habrá». Y su formulación positiva: «yo no actúo y el pueblo se transforma por sí mismo; amo la quietud y el pueblo se rectifica por sí mismo». Capítulo 60: «gobernar un gran país es como freír un pez pequeño» — si lo revolvés demasiado, se deshace.

El capítulo 48 marca la diferencia con el ideal confuciano de aprendizaje acumulativo: «el que se dedica al estudio aumenta cada día; el que se dedica al Tao disminuye cada día. Disminuye y vuelve a disminuir, hasta llegar a la no acción. Con la no acción nada queda sin hacer».

Y el pǔ, la «madera sin tallar», nombra ese estado de simplicidad previa a las distinciones y al deseo fabricado: capítulo 19, «manifestá lo simple, abrazá lo natural, reducí el egoísmo, disminuí los deseos».`,
  comentario:"El Tao Te Ching no argumenta: opera por paradojas e imágenes, y eso es coherente con su primera línea sobre lo innombrable. Prestá atención a la relación entre los capítulos 2 y 57 — la crítica al lenguaje que fabrica opuestos y la crítica al gobierno que fabrica prohibiciones son la misma tesis aplicada dos veces. La pregunta del cuestionario sobre leer un libro que dice ser inefable se responde con la imagen tradicional del dedo que señala la luna."}
], preguntasLectura:[
 {q:"Según el capítulo 2, ¿qué ocurre cuando todos reconocen lo bello como bello?", opciones:["El mundo mejora","Aparece lo feo: los opuestos se generan mutuamente","Se pierde el Tao para siempre","Los gobernantes se vuelven justos"], r:"Aparece lo feo: los opuestos se generan mutuamente", why:"Es la tesis de la interdependencia de opuestos, base de la crítica taoísta a las distinciones fijas."},
 {q:"¿Qué muestran las imágenes de la rueda, la vasija y la casa (capítulo 11)?", opciones:["Que la artesanía es una virtud","Que la utilidad viene del vacío, no de la materia","Que hay que construir con simplicidad","Que el Tao creó los oficios"], r:"Que la utilidad viene del vacío, no de la materia", why:"«Del ser viene el provecho, y del no ser, la utilidad» — el vacío no es carencia sino condición de uso."},
 {q:"¿Qué contraste establece el capítulo 48 entre estudio y Tao?", opciones:["El estudio aumenta cada día; el Tao disminuye cada día","Ambos aumentan por igual","El Tao exige más lecturas","El estudio conduce naturalmente al Tao"], r:"El estudio aumenta cada día; el Tao disminuye cada día", why:"Es la diferencia explícita con el ideal confuciano de aprendizaje acumulativo, hasta llegar al wú wéi."}
]};
