/* ============================================================
   Ficha: nagarjuna  ·  tradición: asiatica
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"nagarjuna", trad:"asiatica", nombre:"Nagarjuna", fechas:"c. 150–250 d.C. · India", escuela:"Budismo Madhyamaka", icon:"⭕", profundizada:true,
 tesis:"Nada posee naturaleza propia (svabhava): todo lo que aparece surge en dependencia de causas, de partes y de designación, y por eso mismo está vacío de esencia intrínseca. Vacuidad y originación dependiente no son dos tesis sino una sola vista por dos lados, y esa identificación es exactamente el camino medio entre el eternalismo, que fija esencias, y el nihilismo, que niega toda existencia. La vacuidad no es un fundamento nuevo: también ella está vacía, y quien la convierte en una tesis metafísica más, dice Nagarjuna, es incurable.",
 obras:[
   {t:"Mūlamadhyamakakārikā (Versos fundamentales del camino medio)", d:"Su obra central: veintisiete capítulos de versos comprimidos hasta la aspereza, sin comentario propio, que examinan una por una las categorías que el budismo escolástico había ido cosificando —las condiciones, el movimiento, los agregados, los elementos, el fuego y el combustible, el agente y la acción, el tiempo, el karma, el yo, el nirvana, las cuatro nobles verdades— y muestran en cada caso que ninguna de ellas puede sostenerse si se le atribuye naturaleza propia. El procedimiento es siempre el mismo y es demoledoramente uniforme: se enumeran las alternativas posibles, se las lleva a todas al absurdo y no se concluye nada positivo. El capítulo 24 contiene el verso decisivo que identifica originación dependiente, vacuidad, designación dependiente y camino medio como cuatro nombres de lo mismo. La obra sobrevivió en sánscrito solo por las citas de sus comentaristas, y la enorme divergencia entre esos comentarios —Buddhapālita, Bhāvaviveka, Candrakīrti— es la raíz de las escuelas posteriores del Madhyamaka."},
   {t:"Vigrahavyāvartanī (La refutación de las objeciones)", d:"Obra breve y de estructura inusual: la primera mitad son las objeciones del adversario, formuladas con una fuerza que Nagarjuna no atenúa, y la segunda es su respuesta. La objeción central es la autorreferencial, y es la mejor que se le ha hecho nunca: si todas las cosas están vacías de naturaleza propia, entonces también lo está tu propia afirmación de que todo está vacío; y una afirmación vacía no tiene fuerza para negar nada, igual que un fuego irreal no quema. Nagarjuna responde que el adversario supone que una tesis solo puede refutar si posee svabhava, es decir, supone justamente lo que está en discusión. Su contestación más famosa es que él no tiene ninguna tesis propia (pratijñā) que defender, y que la vacuidad opera como un hombre mágicamente creado que detiene a otro hombre mágicamente creado. También discute allí el problema del criterio de conocimiento (pramāṇa): si los medios de conocimiento necesitan a su vez ser validados, la exigencia de fundamento entra en regreso infinito."},
   {t:"Śūnyatāsaptati (Setenta versos sobre la vacuidad)", d:"Setenta y tres versos conservados en tibetano que funcionan como la contracara práctica de los Versos fundamentales: en lugar de desmontar categorías metafísicas una por una, se ocupa de por qué el Buda habló de nacimiento, permanencia, destrucción, ser y no ser si nada de eso tiene naturaleza propia. La respuesta es que lo dijo en el nivel convencional y con intención terapéutica, no como descripción de esencias. Es el texto donde la relación entre vacuidad y lenguaje del Dharma queda más explícita, y donde mejor se ve que el blanco de Nagarjuna no es el budismo sino la tentación, interna al budismo mismo, de convertir los dharmas del Abhidharma en últimos ladrillos reales de la realidad."},
   {t:"Yuktiṣaṣṭikā (Sesenta versos de razonamiento)", d:"Sesenta versos dedicados a mostrar que quien comprende la originación dependiente no cae ni en la afirmación del ser ni en la del no ser, y que ambos extremos son en el fondo la misma enfermedad con signo cambiado. Aquí aparece con más claridad que en ningún otro lugar la tesis radical de la equivalencia entre samsara y nirvana: si el samsara tuviera naturaleza propia no podría cesar, y si el nirvana fuera una cosa aparte sería otro objeto condicionado. También es el texto que los comentaristas usan para argumentar que el Madhyamaka no es escepticismo: la meta declarada no es suspender el juicio sino extinguir el aferramiento, que es un fenómeno afectivo antes que epistémico."},
   {t:"Ratnāvalī (La guirnalda preciosa)", d:"Carta en verso dirigida a un rey —probablemente de la dinastía Sātavāhana— que desmiente por sí sola la caricatura del Madhyamaka como doctrina indiferente al mundo. Junto a la exposición de la vacuidad y de la carencia de yo, Nagarjuna da consejos administrativos concretos y sorprendentemente pormenorizados: fundar hospitales y casas de reposo para viajeros, mantener médicos y barberos públicos, tratar con clemencia a los presos e incluso liberarlos, no confiscar bienes, sostener a los mendigos y a los enfermos, evitar la guerra. Es la prueba textual de que, para él, la verdad convencional no es un nivel despreciable sino el lugar donde la ética y la política son plenamente vinculantes; un lector que sostenga que la vacuidad disuelve la responsabilidad tiene que explicar por qué el propio Nagarjuna escribió este libro."}
 ],
 conceptos:[
   {t:"Śūnyatā (vacuidad)", d:"El término se traduce por vacuidad y es el que más malentendidos ha producido, porque no nombra la nada ni un vacío físico ni una sustancia sutil detrás de las apariencias. Es siempre vacuidad de algo determinado: de svabhava, de naturaleza propia. Decir que una mesa es vacía no es decir que no hay mesa, es decir que no hay nada en la mesa que sea mesa por sí mismo, con independencia de sus partes, de su fabricación, de su uso y del concepto con que la recortamos del mundo. La formulación negativa es deliberada: Nagarjuna no describe cómo son las cosas, retira una atribución que hacemos sin darnos cuenta. Por eso el error simétrico al nihilismo es el más peligroso y el que él denuncia con más dureza, el de tomar la vacuidad por una realidad última positiva que quedaría cuando se han disuelto las demás."},
   {t:"Svabhāva y su crítica", d:"Svabhava significa literalmente ser propio, y en el Abhidharma designaba aquello que hace que un dharma sea lo que es, su carácter no prestado. Nagarjuna acepta la definición de sus adversarios y la usa contra ellos: algo tiene svabhava si es no fabricado, si no depende de otra cosa y si no cambia. Basta con sostener las tres condiciones a la vez para que la noción se desarme, porque todo aquello de lo que tenemos experiencia surge, depende y se altera. El golpe es doble, porque no ataca una teoría exótica sino la gramática espontánea con que pensamos: creemos que primero hay una cosa y después esa cosa entra en relaciones, cuando en rigor lo que llamamos la cosa es el nudo de esas relaciones. Toda la obra puede leerse como la aplicación paciente de este único martillo a una categoría tras otra."},
   {t:"Pratītyasamutpāda (originación interdependiente)", d:"Es la doctrina budista más antigua —esto siendo, aquello es; con el surgir de esto, surge aquello— y también el punto donde Nagarjuna hace su aporte más original. Antes de él, la originación dependiente se entendía sobre todo como una cadena temporal de causas y efectos entre entidades reales. Él la lee como dependencia estructural en tres sentidos simultáneos: dependencia de causas, dependencia de partes y, el más radical, dependencia de designación conceptual. Y da el paso decisivo: originación dependiente y vacuidad no son dos verdades relacionadas sino la misma tesis enunciada de dos maneras, una en clave positiva y otra en clave negativa. Lo que hace posible que las cosas surjan es precisamente que no tengan esencia, porque lo que tuviera naturaleza propia no podría empezar, cambiar ni terminar. Por eso puede decir que solo en un mundo vacío funcionan la causalidad, el sufrimiento, el camino y la liberación."},
   {t:"Madhyamaka (el camino medio)", d:"La escuela toma su nombre de un medio que no es una posición intermedia ni un equilibrio entre dos afirmaciones, como si se tratara de conceder un poco a cada bando. Es el rechazo de la pregunta que genera ambos extremos. El eternalismo (śāśvatavāda) supone que hay algo que permanece idéntico a sí mismo: un alma, una sustancia, un átomo, un dharma último. El nihilismo (ucchedavāda) niega que haya algo en absoluto, y con ello niega también el karma, la eficacia de la acción y el camino. Nagarjuna sostiene que las dos posturas comparten el mismo presupuesto, el de que existir de verdad significa existir con naturaleza propia; una lo afirma y la otra lo echa de menos. Quitado el presupuesto, ninguna de las dos tiene ya de qué hablar, y lo que queda es un mundo de apariciones dependientes que ni son sólidas ni son falsas."},
   {t:"Las dos verdades (saṃvṛti y paramārtha)", d:"La enseñanza se apoya en dos niveles: la verdad convencional o encubridora (samvriti-satya), que es el mundo de los nombres, las prácticas, las mesas, las personas y las obligaciones morales, y la verdad última (paramartha-satya), que es la vacuidad de naturaleza propia de todo eso. El punto delicado es que no se trata de dos mundos ni de una escala donde el segundo cancele al primero: samvriti significa literalmente lo que cubre, y sin embargo Nagarjuna afirma que sin apoyarse en lo convencional no puede enseñarse lo último, y que sin alcanzar lo último no hay nirvana. La verdad convencional no es una mentira piadosa: es el único lugar donde algo puede decirse, incluida la propia doctrina de la vacuidad. Aquí se juega la respuesta a la acusación de que el Madhyamaka destruye la ética, y también una de las grandes divergencias entre sus comentaristas, que discuten hasta hoy si lo convencional conserva alguna validez propia o es solo error compartido."},
   {t:"Catuṣkoṭi (la tétrada)", d:"Esquema heredado de la lógica india antigua que Nagarjuna convierte en instrumento de demolición. Ante cualquier cuestión se despliegan las cuatro posiciones exhaustivas —es, no es, ambas cosas, ninguna de las dos— y se las refuta una por una, incluida la cuarta, de modo que no queda residuo donde apoyarse. El capítulo 1 lo aplica al surgimiento: nada surge de sí mismo, porque ya sería; ni de otro, porque entonces cualquier cosa podría surgir de cualquier cosa; ni de ambos, que hereda los dos problemas; ni sin causa alguna, que contradice la experiencia. La cuestión de si esto viola el principio de no contradicción ha generado una literatura enorme, con lecturas que van desde tomarlo como lógica parametrizada (afirmar y negar en niveles distintos) hasta las reconstrucciones paraconsistentes contemporáneas; la lectura más sobria es que la tétrada no afirma cuatro cosas, sino que muestra que la pregunta presuponía svabhava y por eso ninguna respuesta funciona."},
   {t:"Prāsaṅga (reducción al absurdo)", d:"Es el método y, para buena parte de la tradición posterior, es también la única posición que Nagarjuna tiene. Consiste en no adelantar jamás una tesis propia, sino en tomar las premisas del adversario y derivar de ellas una consecuencia (prasanga) que él mismo no puede aceptar. La ventaja es que nunca hay que defender un compromiso metafísico; el precio es que quien argumenta así parece no decir nada. Siglos después, Bhāvaviveka objetará que esto es insuficiente y que el madhyamika debe formular silogismos autónomos, mientras Candrakīrti defenderá el prasanga puro, y de esa disputa nacen las dos ramas de la escuela. Leído así, Nagarjuna se parece menos a un metafísico que a un terapeuta de conceptos: no reemplaza las opiniones erróneas por opiniones correctas, desarma el mecanismo que las produce."},
   {t:"El análisis del movimiento y de la causalidad", d:"El capítulo 2 contiene el argumento más citado y más resistido. Si el movimiento tuviera naturaleza propia, tendría que estar en algún lado: o en el trecho ya recorrido, que ya no se recorre; o en el no recorrido, que todavía no se recorre; o en el que se está recorriendo, que no es más que el límite entre los dos anteriores y no tiene espesor propio. Y si se dice que el que se mueve se mueve, se duplica el movimiento, porque entonces habría uno en el sujeto y otro en el verbo; y si el que no se mueve se moviera, sería contradictorio. La lectura apresurada convierte esto en una negación del movimiento al estilo de Zenón, y no lo es: Nagarjuna no niega que caminemos, niega que exista un movimiento en sí separable del que camina, del trecho y de la designación. Es un argumento sobre la gramática de los sustantivos que fabricamos a partir de los verbos."},
   {t:"Nirvāṇa y saṃsāra", d:"Uno de los cuatro o cinco versos más radicales de la historia de la filosofía budista afirma que no hay la menor diferencia entre el samsara y el nirvana, y que el límite de uno es el límite del otro. El argumento es estrictamente consecuente: si el nirvana fuese una cosa, sería condicionado y compuesto como todas las cosas, y por tanto no sería liberación; y si el samsara tuviera naturaleza propia, sería eterno e incesable y no habría liberación posible. Ambos están igualmente vacíos, y esa vacuidad común es lo que hace posible el tránsito. Lo que cambia con la liberación no es el mundo sino la extinción del aferramiento a que el mundo tenga esencia. De aquí sale buena parte del budismo mahayana posterior, y también el reproche recurrente de que la doctrina, llevada al límite, vuelve indiferentes el esfuerzo y la práctica."},
   {t:"La vacuidad de la vacuidad", d:"Es la cláusula que impide que todo el edificio se convierta en su contrario. Si la vacuidad fuera algo, sería una naturaleza propia más, la última y la más difícil de desalojar, y el Madhyamaka quedaría refutado por sus propias armas. Por eso Nagarjuna insiste en que la vacuidad es la renuncia a todas las opiniones, y advierte que aquellos que hacen de la vacuidad misma una opinión son incurables. La imagen tradicional es médica: el purgante que expulsa los humores debe también expulsarse a sí mismo, porque la medicina que se queda en el cuerpo se vuelve veneno. La consecuencia es que la vacuidad no es una descripción del modo en que las cosas son realmente, sino una operación que se cancela al terminar; y la discusión sobre si esa cancelación es coherente o solo desplaza el problema un paso más atrás sigue abierta."}
 ],
 conexion:"Su blanco inmediato no es el hinduismo sino el propio Abhidharma budista, que había convertido el análisis del yo en una lista de dharmas últimos y reales; Nagarjuna aplica a esa lista el mismo procedimiento que el Buda había aplicado a la persona. Frente a <b>Shankara</b> el contraste es máximo y conviene no suavizarlo: donde el Advaita encuentra al final una realidad última sin atributos, el Madhyamaka sostiene que también esa realidad estaría vacía de naturaleza propia, de modo que no compiten por describir el absoluto, discuten si hay algo que describir. En la tradición europea, su crítica a la sustancia anticipa por más de mil años el ataque de <b>Hume</b> al yo como haz de percepciones y desmonta de antemano el paso que <b>Descartes</b> da del pienso a la sustancia pensante. Y el paralelo más discutido hoy es con <b>Wittgenstein</b>: ambos sostienen que los problemas filosóficos nacen de un mal uso del lenguaje, ambos escriben para disolver y no para fundar, y ambos usan la imagen de la herramienta que se abandona cuando cumplió su función — la escalera que se tira, la balsa que se deja en la orilla. La diferencia está en que Nagarjuna sí quiere sacar de esa disolución una consecuencia soteriológica, y esa asimetría es justamente lo que hace interesante la comparación. Dentro de Asia, su deflación de los opuestos fijos lo emparenta con <b>Zhuangzi</b> por otro camino, y el zen de <b>Dōgen</b> es impensable sin la ecuación entre samsara y nirvana.",
 dialogo:{titulo:"Un fuego irreal no quema", lineas:[
   {quien:"Objetor", texto:"Sostenés que todas las cosas están vacías de naturaleza propia. Entonces tus palabras también están vacías. Y lo que está vacío no tiene fuerza para negar nada: un fuego irreal no quema, un cuchillo irreal no corta. Tu refutación se refuta sola."},
   {quien:"Nagarjuna", texto:"La objeción está bien construida y no la voy a esquivar. Pero fijate en lo que hace falta suponer para que funcione: tenés que dar por sentado que una afirmación solo puede refutar algo si posee naturaleza propia. Eso es exactamente lo que discutimos. Estás usando mi conclusión negada como premisa."},
   {quien:"Objetor", texto:"No hace falta tanta sutileza. Si tu tesis es verdadera, se destruye; si es falsa, ya estamos de acuerdo. En cualquiera de los dos casos perdés."},
   {quien:"Nagarjuna", texto:"Perdería si tuviera una tesis. Yo no adelanto ninguna. Tomo lo que vos afirmás y te muestro adónde lleva. Si no propongo nada, no hay nada mío que pueda ser refutado."},
   {quien:"Objetor", texto:"Eso es una salida demasiado cómoda. Acabás de decir que nada tiene naturaleza propia, y eso es una afirmación sobre todo lo que existe. No me digas que no dijiste nada."},
   {quien:"Nagarjuna", texto:"Es una afirmación en la verdad convencional, que es el único lugar donde se habla. Pero no describe una propiedad que las cosas tendrían. Es como el hombre que un mago hace aparecer y que detiene a otro hombre igualmente aparecido: ninguno de los dos es real, y sin embargo uno detiene al otro.", nota:"Este es el corazón de la Vigrahavyavartani, y conviene notar hasta dónde llega: la respuesta no consiste en exceptuar la vacuidad de su propia regla, sino en negar que refutar exija poseer esencia. Quien exceptúa, pierde; quien niega el requisito, conserva la coherencia al precio de quedarse sin tesis."},
   {quien:"Objetor", texto:"Concedamos eso. Pero entonces sos un nihilista con buenos modales. Si nada tiene esencia, tampoco la tienen el sufrimiento, el camino, el karma ni el Buda. Acabás de demoler tu propia religión."},
   {quien:"Nagarjuna", texto:"Al revés, y este es el punto que más me interesa. Si el sufrimiento tuviera naturaleza propia, sería incesable, porque lo que es por sí mismo no puede dejar de ser. Si el camino tuviera naturaleza propia, no llevaría a ninguna parte, porque no podría producir nada nuevo. Solo en un mundo vacío hay enfermedad, cura y curación. Lo que vos llamás demolición es la condición de que algo funcione."},
   {quien:"Objetor", texto:"Sin embargo tu escuela habla de dos verdades, y una se llama encubridora. Si lo convencional encubre, es falso; y si es falso, mi objeción sigue en pie: la moral queda en el terreno de lo falso."},
   {quien:"Nagarjuna", texto:"Encubre en el sentido en que el nombre cubre el surgir dependiente, no en el sentido de mentir. Sin apoyarse en lo convencional no se enseña lo último, y sin lo último no hay liberación. El que descarta el nivel convencional cree haber ascendido y en realidad se cayó del otro lado."},
   {quien:"Objetor", texto:"Entonces decime de una vez cómo son las cosas realmente. Si hay una verdad última, tiene que haber algo que ella diga."},
   {quien:"Nagarjuna", texto:"Ahí es donde quería llegar. Si te respondiera eso, te estaría entregando una naturaleza propia nueva, más fina que las otras y por eso más difícil de soltar. La vacuidad no es el modo en que las cosas son: es el abandono de todas las opiniones. Los que hacen de la vacuidad una opinión son incurables."},
   {quien:"Objetor", texto:"Un purgante que se expulsa a sí mismo. Muy elegante. Pero no me resolviste el problema, lo corriste un paso: ahora la afirmación vacía de que la vacuidad está vacía pide a su vez otra cancelación, y así indefinidamente."},
   {quien:"Nagarjuna", texto:"Si buscás un punto donde apoyar el pie, tenés razón y no lo vas a encontrar conmigo. Pero no hay regreso infinito, porque no se trata de una serie de afirmaciones cada vez más verdaderas: se trata de una operación que termina cuando ya no queda aferramiento. El remedio no se repite indefinidamente, deja de tomarse cuando la fiebre pasó.", nota:"Aquí se abre la discusión que la erudición contemporánea mantiene sin resolver. Una lectura ve un escepticismo terapéutico emparentado con Sexto Empírico y con el Wittgenstein tardío: no hay doctrina, solo disolución de pseudoproblemas. Otra lectura, la quietista, sostiene que al final no queda ni siquiera una terapia, solo el silencio. Y una tercera, defendida por buena parte de la tradición tibetana y por varios intérpretes occidentales, insiste en que Nagarjuna sí hace una afirmación metafísica —que las cosas son realmente así, carentes de esencia— con lo cual la vacuidad amenaza con volverse el svabhava que él mismo prohíbe. Las tres lecturas pueden apoyarse en versos suyos, y esa es justamente la dificultad."},
   {quien:"Objetor", texto:"¿Y qué queda entonces, después de tu tratamiento? ¿Adónde se va el que se curó?"},
   {quien:"Nagarjuna", texto:"A ningún lado, porque no hay adónde. Entre el samsara y el nirvana no hay la menor diferencia: el límite de uno es el límite del otro. Lo que cambia no es el mundo, es que dejaste de agarrarlo."}
 ]},
 actividades:[
   {t:"Bajar un objeto hasta que la esencia se disuelva", d:"Elegí un objeto concreto y cotidiano que tengas delante —una taza, un cuaderno, el teléfono— y escribí en una hoja, en columna, todo aquello sin lo cual ese objeto no sería lo que es: sus materiales, los procesos que los produjeron, las personas que lo fabricaron, el transporte, el uso que le das, la palabra con que lo nombrás, la costumbre social que hace que ese uso tenga sentido. Seguí bajando un nivel más en cada renglón durante al menos quince minutos, sin permitirte parar cuando aparezca el aburrimiento, que es cuando el ejercicio empieza a funcionar. Después señalá con un círculo el punto exacto en el que esperabas encontrar algo que fuera la taza misma, no sus partes ni sus condiciones, y escribí un párrafo honesto sobre qué encontraste ahí. Repetí el ejercicio completo con algo que no sea un objeto sino una institución de la que formes parte: tu escuela, tu trabajo, tu barrio, una amistad de veinte años. Cerrá con la pregunta que decide todo: si en ninguno de los dos casos apareció un núcleo propio, ¿en qué sentido decís que la taza existe y en qué sentido decís que existe tu escuela, y son el mismo sentido?"},
   {t:"Una tétrada sobre una discusión real", d:"Buscá una discusión pública o privada que en este momento esté planteada como un dilema cerrado de dos opciones, del tipo o es libertad de expresión o es censura, o la responsabilidad es individual o es estructural, o el arte es objetivo o es subjetivo. Escribí las cuatro posiciones del catuskoti con todo el rigor que puedas: que sea A, que no sea A, que sea las dos cosas, que no sea ninguna de las dos, y dedicale a cada una un párrafo defendiéndola con su mejor argumento antes de refutarla. Cuando llegues a la cuarta, que es la que casi nadie formula, prestá atención a lo que sentís: la incomodidad de no tener dónde pararse es el dato del ejercicio, no un fracaso. El paso final es el más importante y es puro Nagarjuna: identificá qué supuesto compartido hacía que las cuatro parecieran las únicas opciones posibles y escribilo en una sola frase. Si lográs formularlo, vas a notar que la pregunta original no se responde sino que se desarma, y ese es exactamente el resultado que la escuela busca."},
   {t:"Inventario de lo convencionalmente real", d:"Elegí tres cosas que te importen de verdad y que no sean objetos: una promesa que hiciste, un vínculo familiar, tu nacionalidad, un compromiso político, un diagnóstico médico que cargás, un título que te costó años. Para cada una escribí dos textos de media página enfrentados. En el primero, defendé con la mayor seriedad posible que es real: qué cambia en el mundo porque exista, qué obligaciones genera, qué pasaría si desapareciera mañana. En el segundo, mostrá su dependencia hasta el final: de qué acuerdos, de qué documentos, de qué personas, de qué palabras y de qué instituciones depende para ser lo que es, y qué quedaría de ella si retirás todo eso. La consigna difícil es la tercera parte, y hay que resistirse a resolverla rápido: escribí por qué el segundo texto no cancela al primero. Si terminás concluyendo que entonces nada importa, no llegaste al camino medio sino al extremo nihilista, y conviene que lo digas explícitamente y vuelvas a empezar; si terminás concluyendo que hay algo en tu promesa que resiste todo análisis, llegaste al otro extremo. Anotá cuál de las dos caídas te resultó más tentadora, porque esa es tu inclinación filosófica de fondo."}
 ],
 cuestionario:[
   {q:"Si todo está vacío, la afirmación de que todo está vacío también lo está, y una afirmación vacía no puede refutar nada. ¿Cómo escapa Nagarjuna de esto?", p:"Es la objeción de la Vigrahavyavartani y hay que concederle toda su fuerza antes de responderla, porque es la mejor que se le ha hecho. Lo primero que conviene notar es cómo no responde: no se exceptúa a sí mismo. Decir que todo está vacío salvo esta frase sería el suicidio de la doctrina, y él lo ve con claridad. Su respuesta ataca el supuesto oculto del adversario: la objeción funciona solo si se acepta que para refutar algo hay que poseer naturaleza propia, y eso es justamente lo que está en discusión, de modo que el argumento da por establecido lo que debía probar. A eso agrega dos cosas. Una es la declaración de que él no tiene tesis propia: su método es tomar las premisas ajenas y mostrar su consecuencia absurda, y quien no afirma nada no tiene nada que defender. La otra es la imagen del ser creado por magia que detiene a otro ser igualmente creado, que ilustra cómo algo sin existencia intrínseca puede sin embargo ser eficaz. Ahora bien, conviene decir que la salida tiene un precio y que el debate no está cerrado: si la vacuidad no es ninguna tesis, hay que explicar por qué escribió veintisiete capítulos para establecerla, y si lo es, vuelve la objeción. Los intérpretes contemporáneos se reparten entre esas dos incomodidades."},
   {q:"Si nada tiene naturaleza fija, tampoco la tienen el bien y el mal. ¿Por qué actuar bien? ¿No colapsa la ética junto con la metafísica?", p:"La objeción es antigua y Nagarjuna la enfrenta de frente en el capítulo 24, donde el adversario le dice que su vacuidad destruye las cuatro nobles verdades, la comunidad y el propio Buda. Su respuesta invierte la acusación: si las cosas tuvieran naturaleza propia, entonces nada podría cambiar, el sufrimiento sería incesable, nadie podría pasar de la ignorancia al conocimiento y la acción moral no produciría absolutamente nada; una esencia fija es lo que congela el mundo, no lo que lo sostiene. La ética requiere justamente que las personas no estén selladas en lo que son. A esto se suma la doctrina de las dos verdades: el karma, la promesa y la responsabilidad pertenecen al nivel convencional, que no es el nivel de lo falso sino el único donde algo se dice y se hace. La prueba más contundente no es teórica sino textual, y es la Guirnalda preciosa, donde el mismo autor le recomienda a un rey que construya hospitales, mantenga médicos públicos y libere presos. Queda de todos modos una pregunta legítima y viva: si lo convencional es solo acuerdo compartido, ¿qué impide que un acuerdo compartido cruel sea igualmente válido? La respuesta estándar apela a la compasión que nace de ver la vacuidad, pero hay que reconocer que ese paso, de la ontología a la compasión, no está demostrado sino asumido."},
   {q:"¿No es el Madhyamaka nihilismo con vocabulario técnico? Negar que algo exista por sí mismo, negar el yo, negar la sustancia, negar incluso la diferencia entre samsara y nirvana.", p:"La diferencia es precisa y vale la pena tenerla clara, porque es el malentendido que más daño hizo a la recepción occidental de Nagarjuna en el siglo XIX, cuando los primeros indólogos lo leyeron como un nihilista oriental. El nihilista dice que no hay nada. Nagarjuna dice que hay exactamente todo lo que aparece, y que aparece porque está vacío. Vacío no es un predicado de inexistencia sino de no autosuficiencia: la ausencia que se afirma tiene un objeto específico, svabhava, y no la existencia en general. Que esto no sea una distinción verbal se prueba por la identificación del capítulo 24, donde vacuidad y originación dependiente son lo mismo: un nihilista no tendría ninguna necesidad de una doctrina de la originación dependiente, porque no habría nada que originar. Además, él clasifica explícitamente al nihilismo como uno de los dos extremos que su camino evita, y lo trata con más dureza que al eternalismo, porque el eternalista se equivoca y el nihilista además deja de practicar. Dicho todo esto, la sospecha tiene un residuo real que no conviene barrer: si toda descripción positiva queda excluida y toda la obra consiste en negaciones, un lector puede preguntar con razón en qué se distingue, en la práctica, de un nihilismo que se abstiene por prudencia de decir la última palabra."},
   {q:"Se lo compara con Wittgenstein, que también disuelve problemas en lugar de resolverlos. ¿Hasta dónde llega el paralelo y dónde se rompe?", p:"El paralelo es real y bastante profundo, y por eso se volvió un tema académico en sí mismo desde los años sesenta. Los dos sostienen que los grandes problemas filosóficos no son descubrimientos sino síntomas de un mal uso del lenguaje; los dos escriben para que el problema desaparezca, no para darle solución; los dos desconfían de las tesis y prefieren el procedimiento al sistema; los dos usan la misma imagen de la herramienta que se descarta al final, la escalera que se tira después de haber subido y la balsa que se deja en la orilla una vez cruzado el río. Incluso el diagnóstico coincide en el detalle: creemos que hay una cosa porque hay un sustantivo, exactamente el error que el análisis del movimiento desarma. Ahora, la ruptura es igual de importante. Wittgenstein quiere devolvernos al lenguaje ordinario y dejar todo como está; Nagarjuna quiere que el lector se libere del sufrimiento, y esa meta soteriológica lo compromete con algo más que una higiene conceptual. Wittgenstein no tiene doctrina de las dos verdades ni la necesita; Nagarjuna sí, porque debe conservar el nivel convencional intacto para que el camino sea practicable. Y hay una asimetría de temperamento que no es menor: el Madhyamaka despliega una maquinaria argumentativa formal, la tétrada, el prasanga, la refutación exhaustiva, mientras el segundo Wittgenstein desconfía precisamente de ese tipo de aparato. La comparación con el escepticismo griego funciona mejor en algunos puntos, sobre todo con Sexto Empírico y su suspensión del juicio como terapia, pero se rompe en otro: el escéptico suspende porque no sabe, y Nagarjuna sostiene que sí sabe algo, que no hay naturaleza propia."},
   {q:"La vacuidad de la vacuidad, ¿resuelve la autorreferencia o solo la posterga un paso más atrás?", p:"Es la pregunta correcta y merece una respuesta que no sea devota. La maniobra consiste en negar que la vacuidad sea una entidad o una propiedad última, con lo cual no queda ningún término final que pudiera tener naturaleza propia; la imagen médica del purgante que se expulsa junto con lo purgado es su formulación tradicional, y el verso sobre los que hacen de la vacuidad una opinión y por eso son incurables muestra que Nagarjuna vio el peligro con total claridad. Contra la acusación de regreso infinito hay una respuesta razonable: no se trata de una serie de afirmaciones metafísicas cada vez más altas, sino de una operación que se agota cuando cumple su función, y una operación no necesita ser fundada por otra operación. Pero quedan dos objeciones que siguen sobre la mesa. La primera es que, si el discurso sobre la vacuidad es solo convencional, entonces la doctrina no dice nada sobre cómo son las cosas, y cuesta entender por qué sería liberadora; si en cambio dice cómo son realmente las cosas, esa manera de ser sería una naturaleza última y estaríamos de nuevo en el problema. La segunda es que apelar a la eficacia terapéutica cambia de terreno: se pasa de justificar una afirmación a justificar una práctica, y un adversario puede aceptar que el remedio funciona sin conceder que la doctrina sea verdadera. La discusión entre lecturas antirrealistas, quietistas y metafísicas del Madhyamaka sigue viva por exactamente esta razón, y un estudiante honesto debería salir de este módulo con la pregunta abierta y no con una consigna."}
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.nagarjuna = { lecturas:[
 {titulo:"Mūlamadhyamakakārikā: vacuidad, originación dependiente y dos verdades", fuente:"Héctor Sevilla Godínez, «El camino medio en la filosofía de la vacuidad de Nāgārjuna», Enclaves del pensamiento XIII/26 (2019) — PDF en Dialnet", url:"https://dialnet.unirioja.es/descarga/articulo/7291322.pdf",
  extracto:`El blanco de Nagarjuna es una noción técnica: svabhāva, «naturaleza propia» o esencia intrínseca. Algo tendría svabhāva si existiera independientemente, sin depender de causas, partes o designación conceptual. La tesis central del Madhyamaka es que nada tiene svabhāva — y a esa ausencia se la llama śūnyatā, vacuidad. En la formulación del estudio de Sevilla Godínez, «los predicados carecen de naturaleza propia (svabhava) y tienen una existencia meramente convencional». Vacío no significa inexistente: significa vacío de esencia propia. Y el propio comentarista subraya el punto que más se malinterpreta: «afirmar la carencia de naturaleza propia en nosotros y en todo lo que nos rodea no tiene por qué significar nihilismo».

El argumento no es una afirmación dogmática sino un método de reducción al absurdo aplicado categoría por categoría. El capítulo 1, sobre la causalidad, examina las cuatro opciones posibles: una cosa surge de sí misma, de otra, de ambas o de ninguna. Si surgiera de sí misma, ya existiría y no habría surgimiento; si surgiera de algo enteramente otro, cualquier cosa podría surgir de cualquier cosa; la combinación hereda los dos problemas; y el surgimiento sin causa contradice la experiencia. La conclusión no es que no haya causalidad, sino que no hay causalidad con naturaleza propia: «ni de sí, ni de otro, ni de ambos, ni sin causa, surge cosa alguna, en ningún lugar».

El mismo esquema se aplica al movimiento (capítulo 2), donde muestra que ni el camino recorrido, ni el no recorrido, ni el que se está recorriendo pueden contener el movimiento sin contradicción; al fuego y al combustible; al agente y a la acción; al tiempo; y al propio yo.

La identificación decisiva está en el capítulo 24: «aquello que es originación dependiente, eso lo llamamos vacuidad; eso es una designación dependiente, y ése es el camino medio». Vacuidad y originación dependiente no son dos tesis sino la misma vista desde dos lados: las cosas existen (surgen dependientemente) y por eso mismo carecen de esencia (no existen por sí). Así se evitan los dos extremos: el eternalismo, que atribuye esencias fijas, y el nihilismo, que niega toda existencia.

Nagarjuna anticipa la objeción obvia — si todo es vacío, ¿no se derrumba la moral, el karma, el propio budismo? — y responde con la doctrina de las dos verdades: «la enseñanza del Dharma por los budas se apoya en dos verdades: la verdad convencional mundana y la verdad última. Quienes no comprenden la distinción entre estas dos verdades no comprenden la realidad profunda». La verdad convencional no es falsedad: es el nivel en que funcionan los nombres, las prácticas y la ética. Y añade la advertencia crucial: «sin apoyarse en lo convencional no se enseña lo último, y sin alcanzar lo último no se alcanza el nirvana».

Sobre la reflexividad —¿tiene esencia la tesis de la vacuidad?— la respuesta es que la vacuidad también es vacía. No es una nueva sustancia metafísica. El verso 13.8, en la versión castellana que recoge este estudio, lo dice sin rodeos: «Los victoriosos han anunciado que la vacuidad es el abandono de todas las conjeturas. Aquellos que caen presos de la conjetura de la vacuidad, ésos son incurables». La imagen tradicional es la del medicamento: la medicina que no se elimina a sí misma se vuelve veneno.`,
  comentario:"Fijate en que Nagarjuna no argumenta a favor de una tesis positiva sino que desmonta las cuatro alternativas posibles en cada caso — es una lógica de exhaución, no de demostración. La identificación entre vacuidad y originación dependiente es lo que impide leerlo como nihilista, y las dos verdades son lo que impide que la vacuidad destruya la ética. La respuesta sobre la vacuidad de la vacuidad contesta directamente la pregunta autorreferencial del cuestionario."}
], preguntasLectura:[
 {q:"¿Qué significa exactamente que algo sea «vacío» (śūnyatā) para Nagarjuna?", opciones:["Que no existe en absoluto","Que carece de naturaleza propia independiente (svabhāva)","Que es invisible","Que es una ilusión de los sentidos"], r:"Que carece de naturaleza propia independiente (svabhāva)", why:"Vacío no es inexistente: es vacío de esencia intrínseca, lo que permite evitar el nihilismo."},
 {q:"¿Qué identifica el capítulo 24 con la vacuidad?", opciones:["El nirvana","La originación dependiente","El sufrimiento","El yo"], r:"La originación dependiente", why:"«Aquello que es originación dependiente, eso lo llamamos vacuidad; y ése es el camino medio»."},
 {q:"Según el verso 13.8, ¿qué pasa con quien convierte la vacuidad en una conjetura más?", opciones:["Alcanza el nirvana antes","Es «incurable»: la medicina se vuelve veneno","Se convierte en maestro","Refuta a Nagarjuna"], r:"Es «incurable»: la medicina se vuelve veneno", why:"La vacuidad es «el abandono de todas las conjeturas»; si se reifica como nueva sustancia metafísica, pierde su función terapéutica."},
 {q:"¿Por qué insiste el texto en que la vacuidad no equivale al nihilismo?", opciones:["Porque Nagarjuna era creyente","Porque carecer de naturaleza propia no es lo mismo que no existir: las cosas surgen dependientemente","Porque el nihilismo es ilegal","Porque la vacuidad solo se aplica a las ideas"], r:"Porque carecer de naturaleza propia no es lo mismo que no existir: las cosas surgen dependientemente", why:"«Afirmar la carencia de naturaleza propia [...] no tiene por qué significar nihilismo»: por eso vacuidad y originación dependiente son la misma tesis vista de dos lados."}
]};
