/* ============================================================
   Ficha: nishida  ·  tradición: asiatica
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"nishida", trad:"asiatica", nombre:"Nishida Kitarō", fechas:"1870–1945 · Japón", escuela:"Escuela de Kioto", icon:"🌓", profundizada:true,
 tesis:"Antes de que haya un yo que percibe y un mundo percibido ya hay experiencia: la experiencia pura es el hecho primero y la división entre sujeto y objeto es un producto tardío de la reflexión, no su punto de partida. Lo que funda el conocimiento no es una sustancia ni un sujeto sino un lugar (basho), y el lugar último es el de la nada absoluta (zettai mu), que no es ausencia ni nihilismo sino el campo sin forma dentro del cual algo puede aparecer como determinado. En su formulación madura, lo real es una identidad absolutamente contradictoria: uno y muchos, mundo e individuo, permanencia y cambio a la vez, sin que ninguna síntesis superior cierre la tensión.",
 obras:[
   {t:"Zen no Kenkyū (Una investigación sobre el bien, 1911)", d:"Su obra fundacional y el primer libro de filosofía escrito en japonés que la tradición reconoce como original y no como exposición de doctrinas europeas. Nishida lo redactó durante sus años de profesor de secundaria en provincias, mientras practicaba zazen con intensidad, y su tesis inicial es una inversión del orden habitual de la epistemología: experimentar es conocer los hechos tal como son, dejando de lado por completo las elaboraciones del propio yo, de modo que la experiencia pura es el estado de experiencia sin la menor adición de deliberación ni discriminación. De ahí se sigue la frase que ordena el libro entero: no es que exista primero el individuo y después la experiencia, sino que existe primero la experiencia y después el individuo. El libro está organizado en cuatro partes que van de la experiencia pura a la realidad, de la realidad al bien y del bien a la religión, y su ética no es una lista de deberes sino una consecuencia metafísica: el bien es la realización de la personalidad, es decir, el despliegue de esa unidad originaria en la vida concreta. Fue un éxito inmediato entre los estudiantes japoneses de entreguerras, y es a la vez el texto más accesible de Nishida y el que él mismo consideró después insuficientemente riguroso, porque todavía describía en clave psicológica algo que después intentará fundar lógicamente."},
   {t:"Jikaku ni Okeru Chokkan to Hansei (Intuición y reflexión en la autoconciencia, 1917)", d:"La obra de transición y también la más ardua de leer: una sucesión de secciones breves escritas a lo largo de años, en las que Nishida se somete a la disciplina del neokantismo de Marburgo y de Heidelberg, discute con Cohen, Rickert, Husserl, Bergson y Fichte, y trata de responder a una objeción que él mismo se hace. Si la experiencia pura es anterior a toda reflexión, entonces el acto mismo de describirla la destruye, y toda la filosofía del primer libro se vuelve imposible por su propio enunciado. La salida que ensaya es el concepto de autoconciencia (jikaku) entendida a la manera de la intuición intelectual de Fichte: un acto que se refleja a sí mismo dentro de sí mismo, de manera que reflexión e intuición no son dos operaciones sucesivas sino dos caras de un mismo movimiento. Nishida cierra el libro reconociendo con franqueza que el intento fracasó y que quedó, según su propia expresión, en una especie de callejón sin salida. Ese fracaso declarado es filosóficamente fértil: lo obliga a abandonar el terreno de la conciencia y del sujeto, y lo empuja hacia la pregunta que abrirá su período central, que ya no es qué es la experiencia sino dónde ocurre."},
   {t:"Hataraku Mono kara Miru Mono e (Del que actúa al que ve, 1927)", d:"El libro donde nace su concepto más original y donde la filosofía de Nishida deja de ser una fenomenología de la conciencia para volverse una lógica del lugar. El título marca el desplazamiento: del sujeto que actúa sobre los objetos, al ver que no es el acto de nadie sino el campo mismo donde algo se hace visible. Allí aparece por primera vez basho, lugar o campo, y el argumento que lo introduce es técnico y no místico. En el juicio de la forma S es P, la lógica aristotélica busca el sujeto último, aquello que puede ser sujeto y nunca predicado; Nishida propone invertir la dirección y buscar el predicado último, el campo que contiene a todo sujeto posible y que jamás puede convertirse él mismo en sujeto de un juicio, igual que el campo visual no es nunca una de las cosas vistas. De ahí sale la estratificación de tres niveles que estructurará su obra posterior: el basho del ser, donde los objetos se determinan unos a otros; el basho de la nada oposicional o relativa, que es el campo de la conciencia, donde el sujeto se enfrenta a los objetos; y el basho de la nada absoluta, que hace posibles a los dos anteriores y que no admite objetivación de ninguna clase."},
   {t:"Bashoteki Ronri to Shūkyōteki Sekaikan (La lógica del lugar y la visión religiosa del mundo, 1945)", d:"Su último ensayo, terminado pocos meses antes de morir y mientras Japón se derrumbaba bajo los bombardeos, y el texto donde condensa cuarenta años de trabajo. Aquí la lógica del lugar ya no se aplica al conocimiento sino al mundo histórico y a la religión: lo real es el mundo que se autodetermina, y el individuo no es una pieza dentro de él sino un punto donde el mundo entero se expresa, de modo que mundo e individuo se determinan mutuamente en una relación que él llama identidad absolutamente contradictoria. El concepto religioso que articula el ensayo es el de gyakutaisō, la correspondencia inversa: lo absoluto y lo relativo se tocan justamente donde son más opuestos, y por eso el encuentro con lo absoluto ocurre en el punto de máxima negación del yo y no en su exaltación. Nishida se apoya en el budismo de la Tierra Pura tanto como en el zen, discute a Pablo, a Eckhart y a Kierkegaard, y sostiene que la religión no es un consuelo ni una moral sino la forma más rigurosa de la pregunta por el sí mismo. Junto con los textos de los años treinta sobre el mundo histórico y la acción-intuición, forma el cuerpo de su período tardío."},
   {t:"Nihon Bunka no Mondai y los ensayos de los años de guerra (1938–1943)", d:"El conjunto más incómodo de su obra y el que hay que leer con la mayor cautela, no saltearlo. El problema de la cultura japonesa, de 1940, surge de conferencias públicas donde Nishida intenta pensar la especificidad cultural japonesa con las categorías de su lógica del lugar; en 1943, presionado por el Ejército, redacta unos principios para un nuevo orden mundial destinados a fundamentar la política de la llamada Esfera de Coprosperidad de Asia Oriental, texto que los militares editaron y usaron de un modo que él objetó. Los historiadores discuten qué hacer con esto y hay evidencia para posiciones distintas: Nishida fue vigilado por la policía política, criticó por escrito el fanatismo del nacionalismo racial y el llamado imperio de ocho rincones bajo un techo, y sostuvo que ninguna cultura particular puede ser el centro del mundo porque el fundamento es la nada; pero también escribió sobre la casa imperial como identidad contradictoria del mundo histórico y prestó, voluntariamente o no, el prestigio de su vocabulario a una maquinaria de guerra. Sus discípulos de la Escuela de Kioto llegaron mucho más lejos en los simposios de 1941 y 1942 sobre la superación de la modernidad. Leer estos textos es la única manera de discutir en serio si una filosofía de la nada absoluta era estructuralmente vulnerable a ese uso o si fue capturada desde afuera."}
 ],
 conceptos:[
   {t:"Junsui keiken (experiencia pura)", d:"El concepto con el que arranca toda su filosofía. Es el instante de experiencia antes de que intervenga cualquier discriminación: escuchar un sonido antes de reconocerlo como una campana, ver un color antes de juzgar que es rojo, y sobre todo antes de que haya un yo que escucha y un objeto escuchado. Nishida toma el punto de partida de William James y de su empirismo radical, pero lo lleva a un lugar al que James no va: donde el psicólogo norteamericano describe un flujo de experiencias que pertenecen a alguien, Nishida quiere describir el flujo antes de que haya alguien, y convierte una tesis psicológica en una tesis metafísica sobre qué es lo primero que hay. Sus ejemplos preferidos son la absorción del músico que ejecuta sin pensar en sus dedos y la del pintor que desaparece en su obra: allí no hay un sujeto manejando un objeto sino una única actividad unificada. La objeción evidente llega de inmediato, y es la que la filosofía posterior formulará como el mito de lo dado: si la experiencia pura no tiene forma ni estructura, no puede fundar ningún juicio, y si la tiene, entonces ya está conceptualmente articulada y no es pura."},
   {t:"Basho (lugar)", d:"Su concepto más original y el que justifica que se lo lea como filósofo y no solo como intérprete del zen. Nishida parte de un problema técnico de la lógica del juicio: cuando decimos que S es P, la tradición aristotélica busca hacia abajo, hacia el sujeto último, la sustancia individual que puede ser sujeto y nunca predicado de nada. Nishida propone mirar en la dirección contraria y preguntar por el predicado último, es decir, por el campo dentro del cual el juicio puede formularse y que nunca aparece él mismo como uno de sus términos. Su imagen recurrente es el campo visual: todo lo que vemos aparece en él, pero el campo no es una de las cosas vistas y no puede serlo sin dejar de ser campo. Basho no es entonces un espacio físico ni un contenedor con paredes, sino la condición que permite que algo se determine, y por eso hay niveles de basho según qué tipo de determinación hagan posible. La consecuencia fuerte es que el fundamento deja de ser un algo y pasa a ser un dónde, lo cual desplaza el eje entero de la metafísica occidental de la sustancia."},
   {t:"Zettai mu (nada absoluta)", d:"El lugar último, el que hace posibles todos los demás y no está contenido en ninguno. Hay que desactivar de entrada dos malentendidos. No es el no-ser como opuesto del ser, porque eso sería una nada relativa, determinada por aquello que niega y por lo tanto todavía dentro del campo del ser; y no es el nihilismo, porque no afirma que nada valga nada sino que el fundamento no es una cosa. Es la traducción filosófica que Nishida propone de la śūnyatā budista al vocabulario de la filosofía europea: una apertura sin determinación desde la cual todo lo determinado emerge. El contraste que él mismo señala es explícito: la metafísica occidental, de Aristóteles a Heidegger, piensa el fundamento como ser, ya sea como sustancia primera, como acto puro o como la pregunta por el sentido del ser, mientras que el pensamiento del Asia oriental lo piensa como nada. La diferencia no es de humor filosófico sino de estructura: si el fundamento es ser, el conocimiento avanza determinando; si el fundamento es nada, avanza dejando de determinar, y el yo verdadero se encuentra haciéndose nada."},
   {t:"El lugar de la nada no es ausencia", d:"Conviene aislar este punto porque es donde más se malinterpreta a Nishida y donde su tesis es más precisa. Una ausencia es la falta de algo dentro de un marco que permanece: si no hay una silla en la habitación, la habitación sigue ahí. La nada absoluta no es la habitación vacía sino la habitación misma en tanto no es ninguno de los muebles. Es lo que hace posible que haya muebles, y precisamente por eso no puede ser encontrada entre ellos. Nishida usa también la analogía del espejo, con una corrección importante: el espejo no es ninguna de las imágenes que refleja, y un espejo que tuviera imagen propia no podría reflejar nada. El error de lectura habitual consiste en tratar la nada como un objeto negativo y preguntar dónde está, qué propiedades tiene, cómo se accede a ella; todas esas preguntas la convierten en un ser y la pierden. La consecuencia metodológica es que el discurso sobre el basho último es siempre indirecto, y de ahí viene tanto su fuerza como la sospecha, perfectamente razonable, de que un concepto que solo puede describirse por lo que no es termine sin poder explicar nada."},
   {t:"Zettai mujunteki jiko dōitsu (identidad absolutamente contradictoria)", d:"La fórmula de su período tardío y la más difícil de traducir sin deformarla. Dice que lo real es a la vez uno y muchos, mundo e individuo, permanencia y cambio, y que los términos no se concilian: la identidad es la contradicción sostenida, no su resolución. El contraste con Hegel es el modo más rápido de entenderla y Nishida lo hace explícito. En la dialéctica hegeliana la tesis y la antítesis son momentos parciales que una síntesis superior conserva y supera, y la serie avanza hacia el Espíritu Absoluto, de modo que la contradicción es un motor que se consume al funcionar. En Nishida no hay Aufhebung ni hay término final: el mundo determina al individuo y el individuo determina al mundo simultáneamente, y ninguno de los dos polos puede reducirse al otro ni ser absorbido por un tercero. Por eso su dialéctica ha sido llamada una dialéctica sin síntesis. La objeción lógica es obvia y hay que hacerla: o bien contradicción está usada en un sentido no lógico —tensión, polaridad, oposición viva— y entonces la fórmula es menos radical de lo que suena, o bien está usada en sentido estricto y entonces hay que explicar por qué no se derrumba todo el discurso."},
   {t:"Jikaku (autoconciencia)", d:"En la filosofía europea la autoconciencia suele pensarse como un sujeto que se toma a sí mismo por objeto, y ese modelo produce de inmediato una regresión: si el yo que se mira es distinto del yo mirado, hace falta un tercer yo que los vea a ambos, y así sin término. Nishida sostiene que ese esquema es un artefacto de haber puesto al sujeto como fundamento, y propone entender jikaku como un acto que se refleja dentro de sí mismo sin salir de sí, donde intuición y reflexión no son dos operaciones sucesivas sino dos aspectos de un mismo movimiento. En su período tardío la reformula en términos de lugar: la autoconciencia no es un yo que se contempla, es el lugar que se determina a sí mismo, y lo que llamamos yo es ese punto donde el mundo se autoexpresa. El costo de la maniobra es alto y él lo sabía, porque el libro de 1917 donde la ensaya termina con una confesión de fracaso; pero de ese fracaso sale el descubrimiento del basho, y en ese sentido es el concepto bisagra de toda su obra."},
   {t:"La lógica del predicado como inversión de Aristóteles", d:"Es la formulación más técnica de su proyecto y conviene tomarla en serio antes de decidir si funciona. Para Aristóteles, la sustancia primera es aquello que se dice siempre como sujeto y nunca como predicado de otra cosa: este hombre, este caballo. Toda la metafísica occidental de la sustancia se apoya en esa asimetría. Nishida acepta el análisis del juicio y le cambia el vector: lo verdaderamente universal no es el sujeto individual sino el campo de predicación, ese trasfondo que permite que cualquier S reciba cualquier P y que jamás puede ocupar el lugar del sujeto. Llama a eso el universal predicativo, y su límite, el predicado que ya no puede ser sujeto de nada, es la nada absoluta. Si el movimiento es legítimo, entonces la conciencia deja de ser una cosa entre cosas y pasa a ser un campo, y con eso se disuelve de un golpe el problema cartesiano de cómo una sustancia pensante se relaciona con una extensa. Si no lo es, la maniobra descansa en tratar una relación gramatical como si fuera una estructura del ser, y esa es exactamente la acusación que le hacen sus críticos analíticos."},
   {t:"Kōiteki chokkan (acción-intuición) y el mundo histórico", d:"El concepto con que Nishida sale de la sospecha de solipsismo que pesaba sobre la experiencia pura. Sostiene que no vemos primero el mundo y actuamos después sobre él, ni actuamos a ciegas para conocerlo luego: vemos actuando y actuamos viendo, y el caso ejemplar es el del artesano cuya mano descubre la forma en el material mientras la produce. De ahí que su período final ya no hable de conciencia sino de mundo histórico: un mundo hecho de cuerpos que trabajan, de técnicas, de instituciones y de tiempo, donde lo real se define como lo que se hace desde lo hecho hacia lo que hace. El individuo no es un espectador ni una sustancia, es el punto en que ese mundo se expresa a sí mismo y se transforma. Este giro acerca a Nishida al marxismo de sus críticos —Tosaka Jun, su discípulo comunista, le reprochaba precisamente que la historia le quedara sin conflicto de clases— y es también el terreno donde su vocabulario se volvió políticamente disponible en los años cuarenta."},
   {t:"La Escuela de Kioto y su ambición", d:"Nishida no fundó una escuela en sentido institucional, pero alrededor de su cátedra en la Universidad Imperial de Kioto se formó el primer grupo filosófico japonés con proyecto propio: Tanabe Hajime, que lo sucedió y lo criticó duramente con su lógica de la especie; Nishitani Keiji, que llevó la nada absoluta a un diálogo frontal con el nihilismo de Nietzsche; y también D. T. Suzuki, amigo de juventud y puente hacia el zen en Occidente. La ambición común era pensar el budismo con el rigor conceptual de la filosofía europea sin reducir ninguno de los dos términos, es decir, ni un orientalismo decorativo ni una simple recepción de Kant y Hegel. Esa ambición produjo obra filosófica de primer orden y, al mismo tiempo, una deuda histórica que no se puede administrar como nota al pie: varios de sus miembros participaron en los simposios de 1941 y 1942 sobre la superación de la modernidad, que dieron munición intelectual al expansionismo japonés. La discusión contemporánea —con trabajos como los de James Heisig, John Maraldo o Christopher Goto-Jones— no busca absolver ni condenar en bloque, sino identificar en qué puntos exactos el aparato conceptual ofreció poca resistencia."}
 ],
 conexion:"Su primer interlocutor es <b>William James</b>, de quien toma el flujo de conciencia y el empirismo radical para radicalizarlos: donde James describe experiencias que son de alguien, Nishida quiere el antes de ese alguien. Con <b>Hegel</b> la relación es de deuda y ruptura, porque acepta que lo real sea proceso y contradicción pero le quita la síntesis y el final. Frente a <b>Aristóteles</b> invierte el eje de la lógica del juicio, buscando el predicado último en lugar de la sustancia primera, y frente a <b>Heidegger</b> la simetría es notable y la divergencia también: los dos desconfían de la metafísica de la sustancia y los dos piensan la apertura previa a los entes, pero uno la nombra ser y el otro nada, y ambos —este es el punto que ningún lector honesto puede saltear— quedaron comprometidos con regímenes de su tiempo. Dentro de Asia, su nada absoluta es un intento explícito de traducir la śūnyatā de <b>Nagarjuna</b> al vocabulario europeo, aunque el madhyamika podría objetar que convertir la vacuidad en fundamento es justamente lo que la vacuidad prohíbe; y su formación en zazen lo conecta con <b>Dōgen</b>, a quien la Escuela de Kioto convirtió en clásico filosófico, especialmente por la afinidad entre el uji y la idea nishidiana del presente eterno.",
 dialogo:{titulo:"Lo que viene antes de las palabras, y lo que vino después de 1941", lineas:[
   {quien:"Estudiante", texto:"Profesor, vengo de leer a los neokantianos y su experiencia pura me suena imposible. Si de verdad no hay ninguna discriminación, no hay nada que experimentar: un puro esto sin ninguna determinación no se distingue de nada en absoluto."},
   {quien:"Nishida", texto:"Está bien planteado. Pero fíjese que usted argumenta desde el resultado hacia atrás. Le pido lo contrario: ese instante en que suena algo y usted todavía no dijo campana, ni dijo sonido, ni se puso a sí mismo como el que oye. ¿Diría que en ese instante no pasó nada?"},
   {quien:"Estudiante", texto:"Diría que pasó algo, sí, pero que ya venía ordenado. No oigo un caos y después lo clasifico: oigo directamente una campana. Lo que usted llama experiencia pura es una reconstrucción que hace la teoría, no un momento que yo haya vivido."},
   {quien:"Nishida", texto:"Entonces le hago otra pregunta. Cuando un músico ejecuta una pieza que domina, ¿dónde está el sujeto? No piensa en sus dedos, no representa las notas, no se observa tocando. Si usted me dice que ahí hay un yo que aplica conceptos a un material, le pido que me señale en qué momento del compás lo hace."},
   {quien:"Estudiante", texto:"Le concedo que no lo nota. Pero no notarlo no es que no esté. Un hábito automatizado sigue siendo conceptual, solo que dejó de ser consciente. Usted está confundiendo lo preconsciente con lo preconceptual."},
   {quien:"Nishida", texto:"Esa distinción es buena y no la voy a esquivar. Pero observe qué está suponiendo: que todo lo que tiene forma tiene que tener forma conceptual. Yo sostengo que hay una unidad activa que tiene forma sin ser todavía juicio, y que el juicio surge cuando esa unidad se quiebra, cuando algo no encaja y la reflexión aparece a reparar.", nota:"Esta objeción, que el estudiante formula en 1917, es la misma que Wilfrid Sellars convertirá en 1956 en la crítica al mito de lo dado: si lo dado carece de estructura conceptual no puede justificar ningún juicio, y si la tiene no es puramente dado. Nishida no la responde defendiendo un dato mudo, sino negando que toda estructura sea conceptual. Que esa respuesta alcance sigue siendo materia de discusión, y el propio Nishida abandonó el vocabulario psicológico del primer libro en parte por esta presión."},
   {quien:"Estudiante", texto:"Supongamos que se lo acepto. Igual queda un problema: si la experiencia pura es anterior a toda reflexión, entonces el libro que usted escribió sobre ella es imposible, porque describirla ya es reflexionar."},
   {quien:"Nishida", texto:"Tiene razón y me costó diez años admitirlo. El libro de 1917 termina confesando que no encontré la salida por ese camino. Fue ese fracaso el que me obligó a cambiar la pregunta: dejé de preguntar qué es la experiencia y empecé a preguntar dónde ocurre. Y lo que hace posible el juicio no puede ser un objeto del juicio, igual que el campo visual no es una de las cosas vistas. A eso lo llamé basho."},
   {quien:"Estudiante", texto:"Permítame cambiar de tema, porque si no, no me lo voy a animar. Usted dice que el fundamento es la nada, y que por eso ninguna cultura particular puede ponerse en el centro del mundo. En 1943 escribió un texto sobre los principios del nuevo orden mundial que el Ejército usó para justificar la Esfera de Coprosperidad. ¿Cómo conviven esas dos cosas?"},
   {quien:"Nishida", texto:"No conviven bien, y no le voy a ofrecer una coartada. Escribí bajo presión y creí, con una ingenuidad que hoy me pesa, que podía introducir mis propias categorías en un documento oficial y torcerlo desde adentro. Los militares editaron el texto. Yo protesté por escrito. Eso último no me absuelve de haberlo escrito."},
   {quien:"Estudiante", texto:"La pregunta más dura no es sobre su conducta, profesor. Es sobre la filosofía. ¿Había algo en la lógica del lugar que se prestara a ese uso, o fue capturada desde afuera por circunstancias que podrían haberle pasado a cualquiera?"},
   {quien:"Nishida", texto:"Es la pregunta correcta y merece que yo no me esconda detrás de mi biografía. Le señalo dónde está el punto débil: si el fundamento es la nada, ninguna particularidad puede ser absoluta, y eso funciona como crítica del nacionalismo racial, que yo ataqué por escrito. Pero mi lógica describe también cómo lo universal se expresa en lo particular, y una vez que se admite eso, alguien puede decir que su nación es el lugar privilegiado donde lo universal se expresa. La estructura no lo impide por sí sola.", nota:"Los hechos, sin adorno: Nishida fue vigilado por la policía política y criticó el fanatismo racial y el lema del imperio de ocho rincones bajo un techo, pero también redactó en 1943 un documento de fundamentación del nuevo orden asiático y escribió sobre la casa imperial en clave de identidad contradictoria. Sus discípulos fueron mucho más lejos en los simposios sobre la superación de la modernidad de 1941 y 1942. Hay tres lecturas vivas en la investigación actual: la que ve una filosofía intrínsecamente nacionalista, la que ve a un pensador universalista presionado por un régimen totalitario, y la que sostiene —hoy mayoritaria entre especialistas como Heisig, Maraldo o Goto-Jones— que ninguna de las dos salidas limpias funciona y que lo que corresponde es marcar en qué puntos exactos el aparato conceptual ofreció poca resistencia."},
   {quien:"Estudiante", texto:"Entonces, ¿tengo que descartar su obra?"},
   {quien:"Nishida", texto:"Si la descarta por esto, va a tener que descartar también a Heidegger, a buena parte de Hegel y a bastantes más. Y si la absuelve invocando que las ideas son inocentes, me está concediendo demasiado. Haga la tercera cosa, que es la más incómoda: use mis conceptos y pregúnteles dónde ceden. Un pensamiento que se sostiene solo mientras nadie lo interroga políticamente no vale gran cosa."},
   {quien:"Estudiante", texto:"Una última. Si el fundamento no es ser sino nada, ¿no está simplemente cambiando una palabra por otra y llamando fundamento a lo que no puede explicar?"},
   {quien:"Nishida", texto:"Ese riesgo es real y no lo niego. La prueba de que la nada no es un mero nombre no puede ser una definición, porque toda definición la convertiría en un ser. Es de otro orden: si al pensar desde ahí se disuelven problemas que desde la sustancia no tenían salida —cómo una cosa pensante toca una cosa extensa, cómo el sujeto está en el mundo que a la vez lo contiene—, entonces el desplazamiento hizo trabajo. Si no los disuelve, usted tiene razón y yo escribí poesía con aparato de lógica."}
 ]},
 actividades:[
   {t:"Cazar el instante anterior a la etiqueta", d:"Durante tres días llevá una libreta y proponete registrar seis episodios en los que hayas alcanzado a notar el intervalo entre percibir algo y reconocerlo: el segundo en que suena algo en la calle y todavía no es una moto, el momento en que ves una figura a lo lejos y todavía no es una persona conocida, el primer sorbo de algo antes de que aparezca la palabra amargo. Anotá cada episodio con dos columnas: qué hubo antes de la etiqueta y qué agregó la etiqueta. Después escribí una página respondiendo la pregunta difícil, sin arreglarla a favor de Nishida: al intentar atrapar ese intervalo, ¿lo encontraste o lo construiste? Registrá específicamente si el acto de estar buscándolo ya lo contaminaba, y si lo que recordás del instante previo es una experiencia o una reconstrucción posterior. Terminá tomando posición sobre si tu experimento apoya la experiencia pura, la refuta, o muestra que la tesis no es del tipo que pueda ponerse a prueba así."},
   {t:"Un mapa de la contradicción que no sintetizás", d:"Identificá una tensión real y actual de tu vida en la que dos cosas que querés de verdad se excluyen mutuamente y que, sin embargo, sostenés todos los días sin resolverla: cuidar a alguien y querer tiempo propio, pertenecer a un lugar y querer irte, defender una institución y criticarla desde adentro, ser docente que evalúa y compañero que acompaña. Escribí una página describiendo los dos polos con la misma honestidad y sin hacer trampa, es decir, sin debilitar uno para que el otro gane. Después probá tres descripciones distintas de lo que estás haciendo con esa tensión: la hegeliana, que busca la síntesis superior donde ambos se conserven superados; la nishidiana, que sostiene que la identidad es la contradicción misma y que resolverla sería perder lo real; y la escéptica, que dice que simplemente estás postergando una decisión y llamándolo filosofía. Cerrá diciendo cuál de las tres describe mejor tu caso y por qué, con evidencia de tu propia semana."},
   {t:"Encontrar un basho en tu vida cotidiana", d:"Elegí un campo real que haga posibles un montón de cosas sin ser él mismo una de esas cosas: tu lengua materna, la institución escolar donde trabajás o estudiás, el barrio, una amistad de años, el conjunto de reglas tácitas de tu familia. Escribí dos listas. En la primera anotá diez cosas concretas que ese campo hace posibles y que no existirían sin él. En la segunda, intentá describir el campo mismo sin nombrar ninguna de esas diez cosas, y registrá con qué dificultad concreta te topás al hacerlo. Para terminar, hacé el experimento que a Nishida le importa: probá convertir ese campo en objeto de estudio —analizar tu lengua desde afuera, describir tu familia como un sistema— y anotá qué se pierde en esa conversión y qué se gana, porque justamente ahí está la tesis en disputa. Cerrá con un párrafo sobre si la analogía entre un contexto cultural y el basho de la nada absoluta es iluminadora o si te parece que hace pasar por metafísica algo que es sociología."}
 ],
 cuestionario:[
   {q:"¿Es coherente hablar de una experiencia pura anterior a toda distinción, o el concepto introduce de contrabando la estructura que dice preceder?", p:"Es la objeción central y tiene una formulación clásica en la filosofía posterior: el mito de lo dado de Wilfrid Sellars. El dilema es limpio. Si la experiencia pura carece por completo de estructura, entonces no puede fundar ningún juicio ni justificar ninguna creencia, porque un puro indeterminado no da razones para decir una cosa antes que otra; y si tiene estructura, ya está articulada y no es pura. Nishida no elige ninguno de los dos cuernos: sostiene que hay una unidad activa dotada de forma sin que esa forma sea todavía conceptual, y que el juicio nace cuando esa unidad se quiebra por un desajuste. Hay algo a favor de esa respuesta: la fenomenología de la destreza —el músico, el artesano, el conductor experimentado— describe una organización de la conducta que no pasa por la representación explícita, y autores tan poco místicos como Merleau-Ponty o Hubert Dreyfus construyeron filosofías serias sobre eso. Hay también algo en contra que no conviene tapar: un crítico puede replicar que preconsciente no es lo mismo que preconceptual, y que todos los ejemplos de Nishida son de habilidades adquiridas, es decir, de conceptos sedimentados y no de una capa anterior a ellos. Conviene además notar que el propio Nishida se dio por insatisfecho: abandonó el vocabulario psicológico del primer libro justamente porque no lograba defenderlo, y ese abandono es la mejor prueba de que la objeción muerde."},
   {q:"El basho y la nada absoluta, ¿explican algo o son un nombre nuevo para el problema que no se resolvió?", p:"La sospecha es legítima y hay que darle su peso máximo: un principio que no puede ser objetivado, que no admite definición y que solo se describe por lo que no es, cumple todos los requisitos formales de una explicación vacía, porque no excluye nada y por lo tanto no se puede contrastar con nada. Lo que Nishida puede ofrecer no es una definición sino rendimiento, y hay que evaluarlo caso por caso. Su mejor carta es el problema de la conciencia: si la conciencia se piensa como una cosa entre cosas, aparecen los enigmas cartesianos clásicos —cómo la sustancia pensante toca la extensa, cómo el sujeto está dentro de un mundo que a la vez está dentro de él—, y pensarla como campo y no como objeto los disuelve en lugar de resolverlos. La analogía del campo visual es buena precisamente porque es empírica: el campo no es una cosa vista y sin embargo no es ficticio. Su peor carta es que el salto del campo visual al basho de la nada absoluta no está argumentado con el mismo rigor; el primero es una descripción fenomenológica constatable, el segundo una tesis metafísica sobre el fundamento del ser, y entre ambos hay un tramo que Nishida recorre por analogía. Un lector exigente dirá que la analogía hace el trabajo que debería hacer el argumento. Un lector benévolo responderá que ninguna filosofía del fundamento puede hacer otra cosa, porque fundamentar el fundamento sería no tenerlo."},
   {q:"La identidad absolutamente contradictoria, ¿es una lógica alternativa o una violación del principio de no contradicción disfrazada de profundidad?", p:"Hay que empezar por desambiguar el término contradicción, porque de eso depende todo. Si Nishida quisiera decir que la misma proposición es verdadera y falsa en el mismo sentido y al mismo tiempo, entonces cualquier cosa se seguiría de su sistema y el sistema no diría nada, que es el resultado clásico de la explosión lógica. Casi ningún intérprete lee así la fórmula. La lectura más sólida es que se trata de una oposición real entre polos que se determinan mutuamente y que no pueden reducirse el uno al otro —mundo e individuo, uno y muchos—, de modo que suprimir un polo destruye al otro. Bajo esa lectura la fórmula es coherente, pero es menos radical de lo que su nombre promete, y se parece bastante a lo que otros llaman polaridad, correlación o interdependencia. Ahí aparece el problema honesto: si es coherente, es menos original; si es original en el sentido fuerte, es incoherente. Vale además comparar con Hegel, porque Nishida se define contra él. Un hegeliano puede replicar que la Aufhebung tampoco elimina la contradicción sino que la conserva, y que Nishida pelea contra una versión de manual de la síntesis. Y quien conozca las lógicas paraconsistentes contemporáneas dirá que existen sistemas formales que toleran contradicciones sin explotar, pero que Nishida no construyó ninguno, así que la defensa técnica es posterior y ajena a él."},
   {q:"Los escritos de guerra y la Escuela de Kioto, ¿comprometen a la filosofía misma o son una desgracia biográfica que puede separarse de la obra?", p:"Primero los hechos, sin adorno ni dramatización. Nishida redactó en 1943, a pedido del Ejército, un documento de fundamentación de los principios del nuevo orden de Asia Oriental, que los militares editaron y utilizaron; escribió sobre la casa imperial en el vocabulario de su propia lógica; fue al mismo tiempo vigilado por la policía política, criticó por escrito el fanatismo racial y el lema del imperio de ocho rincones bajo un techo, y sostuvo que ninguna nación particular puede ser el centro del mundo. Sus discípulos llegaron mucho más lejos que él en los simposios sobre la superación de la modernidad de 1941 y 1942. Sobre esta base hay tres posiciones en la investigación actual. La primera sostiene que el nacionalismo está inscripto en la estructura del pensamiento y no es un accidente, porque una filosofía que describe cómo lo universal se expresa en lo particular ofrece un molde perfecto para que una nación se declare el lugar privilegiado de esa expresión. La segunda separa al hombre presionado por un régimen totalitario del contenido conceptual, y recuerda que su obra central es anterior y que sus lectores más fecundos fueron después de todo signo político. La tercera, hoy dominante entre especialistas como James Heisig, John Maraldo o Christopher Goto-Jones, rechaza las dos salidas limpias y propone leer identificando los puntos precisos donde el aparato no ofreció resistencia. El paralelo con Heidegger es inevitable y útil, con una diferencia que conviene registrar: Heidegger se afilió al partido y calló después de 1945; Nishida trabajó bajo presión, objetó la edición de su texto y murió antes del final de la guerra. Esa diferencia matiza el juicio sobre las personas, pero no cancela la pregunta sobre los conceptos, que es la que importa aquí."},
   {q:"¿La nada absoluta de Nishida es realmente lo mismo que la vacuidad de Nagarjuna, o la semejanza es superficial?", p:"El parentesco es real y buscado: Nishida entendía su obra como una traducción de la intuición budista al lenguaje de la filosofía europea, y ambos rechazan que haya sustancias con naturaleza propia. Pero las diferencias son estructurales y probablemente decisivas. La śūnyatā de Nagarjuna es estrictamente negativa por diseño: no nombra un fondo ni un campo, sino la ausencia de naturaleza propia en todo lo que hay, y el propio Nagarjuna advierte que quien convierte la vacuidad en una tesis es incurable, y aplica la vacuidad a la vacuidad misma para que no quede residuo donde apoyarse. La nada absoluta de Nishida, en cambio, hace un trabajo positivo: es aquello dentro de lo cual los entes se determinan, el lugar último, el predicado que no puede ser sujeto. Un madhyamika ortodoxo tiene aquí una objeción precisa y fuerte: eso es exactamente convertir la vacuidad en un fundamento, es decir, devolverle la naturaleza propia que la doctrina venía a disolver. Hay diferencias de método que apuntan en la misma dirección: Nagarjuna procede refutando tétradas, sin afirmar nada, mientras que Nishida construye una lógica y afirma una estructura del mundo histórico. Se puede defender a Nishida diciendo que basho no es una entidad sino una condición, y que una condición no tiene naturaleza propia; pero entonces habría que mostrar que hablar de lo que hace posible no reintroduce lo que se quería evitar. La comparación es fructífera justamente porque no se cierra, y funciona mejor como pregunta abierta que como puente confirmado."}
 ],
 cadena:{ titulo:"¿De quién es la experiencia pura?", intro:"Un razonamiento en ramas que parte de la tesis con que se abre Una investigación sobre el bien (1911): antes de que haya un yo y un mundo, hay experiencia. Las ramas siguen las dos salidas que Nishida mismo encontró —la lógica del lugar y la acción-intuición— y los malentendidos más frecuentes sobre la nada absoluta.", inicio:"n1", nodos:{
   n1:{ pregunta:"Nishida llama experiencia pura al instante de escuchar un sonido antes de reconocerlo como una campana, antes incluso de pensar «yo escucho». Esa experiencia, ¿es un estado mental de alguien?", opciones:[
     {texto:"Sí: es un estado psicológico, muy concentrado, de un sujeto que todavía no reflexiona.", va:"n2a"},
     {texto:"No: todavía no es de nadie; el sujeto aparece después, cuando la reflexión separa al que escucha de lo escuchado.", va:"n2b"} ]},
   n2a:{ pregunta:"En el prefacio del libro, Nishida invierte el orden habitual: no es que haya experiencia porque hay un individuo, sino que hay individuo porque hay experiencia. Y en el prefacio de la reedición de 1936 reconoce que el libro podía parecer demasiado psicologista. ¿Qué hacés con eso?", opciones:[
     {texto:"Tomo en serio la autocrítica: el punto de partida era psicológico, y Nishida pasó el resto de su obra buscando otra formulación.", va:"n3a"},
     {texto:"Concluyo que es solipsismo: si todo es experiencia, todo es mi experiencia.", final:{tipo:"revisar", texto:"Es la objeción más común y Nishida la previó: el solipsismo supone un yo que tiene experiencias, y la experiencia pura es justamente lo anterior a ese yo. Decir «todo es mi experiencia» ya introduce el «mi» que la tesis pone después. Que la tesis sea difícil de formular sin ese «mi» es otro problema, y real; pero no es el del solipsismo. Volvé un paso y probá la otra respuesta."}} ]},
   n3a:{ pregunta:"¿Hacia dónde se movió Nishida para salir del lenguaje de la conciencia individual?", opciones:[
     {texto:"Hacia la lógica del lugar (basho): lo primero no es un estado de conciencia, sino el campo en el que sujeto y objeto se sitúan y se determinan.", final:{tipo:"bien", texto:"Es el giro de Del que actúa al que ve (1927). La experiencia pura deja de ser un acontecimiento psíquico y pasa a ser pensada como lugar: aquello en lo cual algo es, sin ser a su vez una cosa entre las cosas. Ganás una formulación lógica y no psicológica. El costo: el concepto de lugar es más abstracto, y muchos lectores sienten que se perdió la inmediatez del sonido de la campana."}},
     {texto:"Hacia la acción-intuición y el mundo histórico: no vemos primero y actuamos después; vemos actuando y actuamos viendo, dentro de una historia.", final:{tipo:"bien", texto:"Es la respuesta del Nishida de los años treinta (kōiteki chokkan). El sujeto ya no es un contemplador, sino alguien que hace cosas en un mundo que también lo hace a él. Ganás historia, cuerpo y sociedad. El costo es que ese mismo mundo histórico es el que Nishida pensó en sus ensayos de guerra, con consecuencias políticas que conviene examinar sin apuro: el concepto no es culpable por sí solo, pero tampoco es inocente."}} ]},
   n2b:{ pregunta:"Si la experiencia no es de nadie, hace falta otra lógica para pensarla. Aristóteles había definido la sustancia como lo que es sujeto de un juicio y nunca predicado de otra cosa. Nishida mira en la dirección contraria. ¿Qué busca?", opciones:[
     {texto:"Lo que es predicado y nunca sujeto: no una cosa, sino el lugar donde las cosas son determinadas.", va:"n3b"},
     {texto:"Un sujeto más universal que todos los demás: Dios como la sustancia última.", final:{tipo:"revisar", texto:"Esa respuesta se queda en la lógica del sujeto que Nishida quiere invertir: sigue buscando una cosa, solo que la más grande. El lugar último, para él, no es un ente supremo, sino la nada absoluta, que no es una cosa entre las cosas. Cuando en su último ensayo (1945) habla de Dios, lo piensa también como algo que se niega a sí mismo, no como una sustancia en la cima. Volvé un paso y probá la otra respuesta."}} ]},
   n3b:{ pregunta:"Si se sigue en la dirección del predicado, se llega a un lugar que no está contenido en ningún otro. Nishida lo llama nada absoluta (zettai mu). ¿Qué es esa nada?", opciones:[
     {texto:"No es la ausencia de algo: es lo que hace lugar sin ser una cosa más, como el campo visual, que no aparece entre las cosas vistas.", final:{tipo:"bien", texto:"Es la lectura que evita el malentendido principal: la nada absoluta no se opone al ser, porque eso la convertiría en una nada relativa, otra cosa más. Notá el aire de familia con la vacuidad de Nagarjuna y con la naturaleza de Buda de Dōgen, que Nishida conocía bien. La crítica más seria vino de su sucesor Tanabe Hajime, que le reprochó una filosofía de la contemplación, casi neoplatónica, en la que todo emana del lugar último y la acción histórica queda en segundo plano."}},
     {texto:"Es un nombre filosófico para la experiencia mística del zen.", final:{tipo:"bien", texto:"Hay algo de verdad: Nishida practicó zazen durante años y su diario lo registra. Pero conviene no reducirlo a eso: él sostenía que su trabajo era filosofía, con argumentos discutibles por cualquiera, y por eso discute con Aristóteles, Kant, Hegel y James. Si la nada absoluta fuera solo una experiencia mística, no habría con qué discutirla. Elegiste una lectura que explica el origen; tenés que explicar también el argumento."}} ]}
 }},
 reconstruccion:[
   { titulo:"Hay individuo porque hay experiencia (Una investigación sobre el bien)",
     consigna:"Reconstruí el argumento con que Nishida pone la experiencia antes del sujeto. Una pieza saca de él una conclusión idealista que Nishida no sostiene: dejala afuera.",
     piezas:[
       {id:"e1", texto:"Distinguir entre un sujeto que conoce y un objeto conocido requiere un acto de reflexión.", tipo:"premisa"},
       {id:"e2", texto:"La reflexión llega después de la experiencia sobre la que reflexiona: primero se escucha el sonido, después se piensa «yo escucho una campana».", tipo:"premisa"},
       {id:"e3", texto:"En la experiencia original, entonces, todavía no estaban separados un «yo» y un «sonido»: había solo el escuchar.", tipo:"premisa"},
       {id:"e4", texto:"El individuo, con su interior y su exterior, se constituye dentro de la experiencia, cuando esta se divide al reflexionar.", tipo:"premisa"},
       {id:"e5", texto:"Por lo tanto, no hay experiencia porque hay individuo, sino individuo porque hay experiencia.", tipo:"conclusion"},
       {id:"ex", texto:"Por lo tanto, el mundo exterior no existe: todo es contenido de mi conciencia.", tipo:"distractor"}
     ],
     ordenCorrecto:["e1","e2","e3","e4","e5"],
     explicacion:"La conclusión es casi literal del prefacio del libro. El punto débil está en el paso de e2 a e3: que la reflexión llegue después no prueba que antes no hubiera sujeto; podría ser que la reflexión descubra algo que ya estaba. Además, toda descripción de la experiencia pura es ya una reflexión sobre ella, así que el argumento habla de algo que, por definición, no puede observar directamente. Nishida aceptaba parte de esta crítica, y por eso pasó a la lógica del lugar. La pieza sobrante reintroduce el «mi» que el argumento acababa de poner después: no es idealismo subjetivo, sino una tesis sobre lo que viene antes de la división entre sujeto y objeto."},
   { titulo:"La lógica del predicado: invertir a Aristóteles",
     consigna:"Reconstruí el argumento que lleva a Nishida desde la teoría del juicio hasta el lugar de la nada. Una pieza saca una conclusión más fuerte de la que el argumento autoriza: dejala afuera.",
     piezas:[
       {id:"l1", texto:"Para Aristóteles, la sustancia primera es lo que es sujeto y nunca predicado: «Sócrates» puede ser sujeto de muchos juicios, pero no se predica de nada.", tipo:"premisa"},
       {id:"l2", texto:"En todo juicio de la forma «S es P», el predicado es más universal que el sujeto y lo abarca: S queda situado en P, como en un lugar.", tipo:"premisa"},
       {id:"l3", texto:"Avanzando en la dirección del predicado, se encuentran lugares cada vez más universales, que contienen a los anteriores.", tipo:"premisa"},
       {id:"l4", texto:"El último lugar no puede ser una cosa ni un predicado determinado por otro: si fuera algo, estaría a su vez situado en otro lugar.", tipo:"premisa"},
       {id:"l5", texto:"Por lo tanto, el lugar último es la nada absoluta: no una cosa, sino el campo en el que se da toda determinación, el predicado que nunca es sujeto.", tipo:"conclusion"},
       {id:"lx", texto:"Por lo tanto, la sustancia aristotélica es una ilusión del lenguaje y debe eliminarse de la filosofía.", tipo:"distractor"}
     ],
     ordenCorrecto:["l1","l2","l3","l4","l5"],
     explicacion:"Es la formulación técnica de la lógica del lugar (basho). El punto débil es l2: tratar la predicación como inclusión espacial —el sujeto dentro del predicado— encaja bien con juicios de clasificación («el gato es un mamífero»), pero mucho peor con otros («Sócrates está sentado», «la reunión es mañana»). Un lógico puede aceptar la conclusión solo si acepta antes la metáfora del lugar. La pieza sobrante es demasiado: Nishida no elimina la lógica del sujeto, la funda; las cosas siguen siendo sujetos de juicios, pero esos juicios ocurren en un lugar que no es una cosa."}
 ],
 dilemas:[
   { titulo:"El documento",
     intro:"En 1943, Nishida escribió «El principio del nuevo orden mundial» a pedido de un grupo vinculado al gobierno japonés en guerra, con la esperanza de influir en el discurso oficial. El discurso no tomó sus ideas como él esperaba, y los historiadores todavía discuten si su texto moderaba la ideología imperial o la legitimaba. Este caso no pretende juzgar a Nishida desde afuera de su época, sino pensar una pregunta que sigue abierta: qué le toca hacer a quien piensa cuando el poder le pide que piense para él.",
     pasos:[
       { id:"p1", situacion:"Sos profesora de filosofía en una universidad pública. El Ministerio de Educación te pide un documento que fundamente filosóficamente una nueva política de «identidad nacional» en el currículo escolar. Algunos puntos de la política te parecen valiosos; otros, excluyentes con las comunidades indígenas y afro. ¿Qué hacés?", opciones:[
         {texto:"Rechazo el encargo: no le presto mi nombre a una política con la que no estoy de acuerdo.", consecuencia:"Preservás tu integridad y tu nombre. Pero el documento se va a escribir igual, y quizá lo escriba alguien a quien los puntos excluyentes no le preocupen. Es el dilema que se planteaban algunos miembros de la Escuela de Kioto: quedarse afuera también tiene consecuencias.", va:"p2"},
         {texto:"Acepto, para moderar la política desde adentro.", consecuencia:"Es, en esencia, la defensa que se hizo de Nishida: escribir en el lenguaje del poder para torcerlo. El riesgo es el inverso: que tu lenguaje termine sirviendo para legitimar lo que querías moderar, porque vos no controlás cómo se usa lo que escribís.", va:"p2"},
         {texto:"Acepto con condiciones: el texto se publica completo, con mi firma, y con las objeciones incluidas.", consecuencia:"Intentás cerrar el riesgo del uso selectivo. Es más difícil de negociar, y el Ministerio puede no aceptar. Pero dejás claro de entrada qué estás dispuesta a firmar.", va:"p2"} ]},
       { id:"p2", situacion:"Seis meses después, el Ministerio publica un resumen de tu documento. Las partes críticas no aparecen, y tu nombre figura como respaldo de los puntos excluyentes. ¿Qué hacés?", opciones:[
         {texto:"Nada: ya está publicado y meterse en una polémica pública no arregla nada.", consecuencia:"Es la salida más cómoda y la que más pesa después. Tu silencio queda como asentimiento. Con Nishida pasó algo parecido: sus críticas más finas estaban en textos que leían pocos, mientras sus palabras circulaban en otro registro.", va:"p3"},
         {texto:"Publico el documento completo y una carta que señala lo que se omitió.", consecuencia:"Asumís el costo político y dejás un registro público de tu posición. Puede que nadie lo lea, pero ya no podrán decir que lo respaldaste. Es la responsabilidad del que escribe por el uso de su nombre.", va:"p3"},
         {texto:"Escribo un artículo académico con las matizaciones, en una revista especializada.", consecuencia:"Corregís el registro, pero en un lugar donde casi nadie lo va a ver: el público que leyó el resumen no lee revistas especializadas. Es una forma de ambigüedad que la Escuela de Kioto practicó mucho, y que años después se le reprochó.", va:"p3"} ]},
       { id:"p3", situacion:"Diez años después, un estudiante te pregunta si te arrepentís de haber participado, o de no haberlo hecho. ¿Qué le respondés?", opciones:[
         {texto:"«Hice lo que pude con lo que sabía entonces.»", consecuencia:"Es honesto y puede ser cierto. Pero no responde a la pregunta del estudiante, que es si harías lo mismo hoy. El contexto explica una decisión; no la vuelve automáticamente correcta.", va:null},
         {texto:"«Aprendí que quien escribe para el poder no controla lo que el poder hace con su texto, y que eso también es responsabilidad de quien escribe.»", consecuencia:"Es la lección que muchos sacaron del caso de la Escuela de Kioto: la intención de moderar no exime de las consecuencias de haber prestado el nombre.", va:null},
         {texto:"«La filosofía no debe mezclarse nunca con la política.»", consecuencia:"Suena prudente, pero es otra posición política: dejarles el campo a otros. Además, la filosofía de Nishida sobre el mundo histórico decía lo contrario: que pensar y actuar dentro de una historia no se pueden separar.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar, con los hechos básicos y sin exagerar, qué hizo Nishida en 1943 y por qué los historiadores todavía lo discuten.",
       "No juzgué el caso de Nishida con criterios que ignoran la situación de un intelectual bajo un régimen en guerra, pero tampoco usé el contexto para cerrar la discusión.",
       "Distinguí entre la intención de quien escribe y el uso que el poder hace de lo escrito.",
       "Consideré las consecuencias de cada opción, incluidas las de quedarme afuera.",
       "Tuve en cuenta a quiénes afectaba la política: las comunidades indígenas y afro, no solo mi reputación.",
       "Relacioné el caso con la idea de Nishida de que se piensa y se actúa dentro de un mundo histórico.",
       "Formulé la objeción más fuerte a mi propia decisión."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.nishida = { lecturas:[
 {titulo:"Experiencia pura, basho y la nada absoluta", fuente:"Stanford Encyclopedia of Philosophy — Nishida Kitarō", url:"https://plato.stanford.edu/entries/nishida-kitaro/",
  extracto:`Nishida abre Un estudio sobre el bien (1911) con una definición que invierte el orden habitual de la epistemología: «experimentar significa conocer los hechos tal como son, dejando completamente de lado las elaboraciones del propio yo. Experiencia pura es el estado de experiencia sin la menor adición de deliberación o discriminación». Su ejemplo canónico es el instante de ver un color o escuchar un sonido antes de juzgar «esto es rojo» o «esto es una campana» — antes, incluso, de que haya un «yo» que perciba y un objeto percibido.

La tesis fuerte es que la distinción sujeto-objeto no es el punto de partida del conocimiento sino un producto tardío de la reflexión. «No es que exista primero el individuo y luego la experiencia, sino que existe primero la experiencia y luego el individuo.» Nishida toma de William James la noción de «flujo de conciencia» y el empirismo radical, pero los radicaliza desde la práctica zen: donde James describe un flujo de experiencias de alguien, Nishida quiere describir el flujo antes de que haya alguien.

Otro ejemplo que usa es el del músico experto que ejecuta una pieza sin pensar en los movimientos, o el del artista absorbido en su obra: allí no hay un sujeto que maneja un objeto, sino una actividad unificada. Esa unidad, y no la separación cartesiana, es para Nishida lo primario.

En su obra posterior desarrolla la lógica del basho, «lugar» o «campo». El problema que quiere resolver es el de la lógica occidental del juicio: cuando decimos «S es P», el sujeto gramatical no puede contener a todos sus predicados sin quedar determinado desde afuera. Nishida propone invertir el foco: todo juicio ocurre en un campo que lo hace posible y que nunca aparece él mismo como objeto del juicio, del mismo modo que el campo visual no es una de las cosas vistas.

Distingue tres niveles superpuestos. El basho del ser, donde los objetos se determinan unos a otros; el basho de la nada relativa u oposicional, que es el campo de la conciencia, donde el sujeto se opone a los objetos; y el basho de la nada absoluta (zettai mu), el fondo sin forma que hace posibles a los dos anteriores y que no puede objetivarse de ninguna manera.

Esa nada absoluta no es ausencia ni nihilismo. Es el término con que Nishida traduce filosóficamente la śūnyatā budista al lenguaje de la fenomenología: no un vacío, sino la apertura sin determinación desde la cual todo lo determinado emerge. Por eso puede decir que el yo verdadero se encuentra «haciéndose nada»: el sujeto auténtico no es una sustancia que persiste, sino el lugar donde el mundo se autodetermina.

De ahí su fórmula tardía de la «identidad autocontradictoria absoluta» (zettai mujunteki jiko dōitsu): lo real es a la vez uno y muchos, sujeto y mundo, permanencia y cambio, sin que la contradicción se resuelva en una síntesis superior. Es una crítica directa a Hegel: donde la dialéctica hegeliana avanza hacia el Espíritu Absoluto, Nishida sostiene una tensión que permanece abierta.`,
  comentario:"Nishida hace explícito lo que la Escuela de Kioto intenta en conjunto: pensar el budismo con las herramientas conceptuales de la fenomenología europea, sin reducir ninguno de los dos. Fijate en el contraste con Hegel al final — la «contradicción absoluta» que no se resuelve es lo que distingue su dialéctica de la Aufhebung. La pregunta del cuestionario sobre la coherencia de una «experiencia pura» sin sujeto es exactamente la objeción que Nishida admite como concepto límite."}
], preguntasLectura:[
 {q:"Según Nishida, ¿qué relación hay entre individuo y experiencia?", opciones:["Primero existe el individuo y luego experimenta","Primero existe la experiencia y luego el individuo","Ambos aparecen simultáneamente por convención","El individuo es una ilusión sin experiencia"], r:"Primero existe la experiencia y luego el individuo", why:"Es la inversión central de Un estudio sobre el bien: la distinción sujeto-objeto es un producto tardío de la reflexión."},
 {q:"¿Qué es el basho de la nada absoluta?", opciones:["Un estado de inconsciencia","El fondo sin forma que hace posibles los otros campos y no puede objetivarse","El vacío del universo físico","La muerte del sujeto"], r:"El fondo sin forma que hace posibles los otros campos y no puede objetivarse", why:"Nishida lo compara con el campo visual, que nunca es una de las cosas vistas; es su traducción filosófica de la śūnyatā."},
 {q:"¿En qué se diferencia la «identidad autocontradictoria absoluta» de la dialéctica hegeliana?", opciones:["En que usa tres momentos en vez de dos","En que la contradicción permanece abierta y no se resuelve en una síntesis superior","En que rechaza la historia","En que es puramente lógica"], r:"En que la contradicción permanece abierta y no se resuelve en una síntesis superior", why:"Es una crítica explícita al Espíritu Absoluto hegeliano como cierre del proceso."}
]};
