/* ============================================================
   Ficha: shankara  ·  tradición: asiatica
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"shankara", trad:"asiatica", nombre:"Adi Shankara", fechas:"c. 700–750 d.C. · India", escuela:"Advaita Vedanta", icon:"🕉️", profundizada:true,
 tesis:"Solo Brahman es real. El mundo múltiple y el yo individual no son otra cosa que Brahman mal visto, del mismo modo que una cuerda en la penumbra es una serpiente mal vista: la superposición (adhyasa) no crea nada, solo encubre lo que ya está ahí. La causa de esa superposición es avidya, una ignorancia sin comienzo que confunde al sujeto consciente con los atributos del cuerpo y del mundo, y el remedio no es una acción, un rito ni una conquista, sino un conocimiento: reconocer que atman ya es Brahman, lo que siempre fue el caso. Por eso la liberación no se produce, se descubre, y puede ocurrir en esta vida.",
 obras:[
   {t:"Brahmasutrabhashya (Comentario a los Brahma Sutras)", d:"Es su obra mayor y la única cuya autoría nadie discute: un comentario extenso a los quinientos y pico aforismos de Badarayana que, a fuerza de interpretarlos, construye el sistema entero del Advaita. La escala del comentario dice mucho — los sutras son a menudo dos o tres palabras, y Shankara escribe páginas sobre cada uno, de modo que el texto comentado funciona menos como autoridad que como percha. Abre con el Adhyasabhashya, unas pocas páginas independientes sobre la superposición que son probablemente lo más leído de toda la literatura vedántica y donde plantea el problema de raíz: sujeto y objeto son tan opuestos como la luz y la oscuridad, y sin embargo los mezclamos en cada frase que decimos. El resto del comentario es polémico de principio a fin: refuta al Samkhya, al Nyaya, a los vaisheshikas, a los mimamsakas ritualistas y, con particular encarnizamiento, a las escuelas budistas, a las que dedica una sección entera. Toda la historia posterior del Vedanta —Ramanuja, Madhva y el resto— consiste en escribir comentarios rivales a los mismos sutras para refutar este."},
   {t:"Comentarios a las Upanishads principales", d:"Bajo su nombre circulan comentarios a diez o doce Upanishads, y la crítica filológica acepta como seguros al menos los de la Brihadaranyaka, la Chandogya, la Taittiriya, la Aitareya, la Katha, la Isha, la Mundaka, la Prashna y la Mandukya. Son el corazón exegético del sistema, porque el Advaita no se presenta nunca como una filosofía nueva sino como la lectura correcta de lo que la revelación ya decía. Allí trabaja los mahavakyas o grandes dichos —tat tvam asi, eso eres tú; aham brahmasmi, yo soy Brahman; prajñanam brahma, la conciencia es Brahman— y demuestra que no son metáforas devocionales sino enunciados de identidad estricta. El comentario a la Brihadaranyaka es el más largo y el más rico filosóficamente, con el célebre neti neti y el diálogo de Yajnavalkya con Maitreyi; el de la Chandogya contiene la escena de Uddalaka enseñando a su hijo con la semilla del higo y la sal disuelta en el agua. Un detalle decisivo: para ordenar textos que se contradicen, Shankara jerarquiza la propia revelación, y asigna a buena parte del Veda ritual el rango de verdad de nivel inferior."},
   {t:"Bhagavadgitabhashya (Comentario al Bhagavad Gita)", d:"El comentario más antiguo que conservamos del Gita, y el que fijó para siempre el modo de leerlo. El problema es que el poema parece enseñar exactamente lo contrario de lo que enseña Shankara: Krishna le dice a Arjuna que actúe, que cumpla con su deber de guerrero, que la devoción es camino de salvación. Shankara lo resuelve con una jerarquía: la acción desinteresada y la devoción purifican la mente y son indispensables como preparación, pero no liberan; solo el conocimiento libera, y el karma yoga es para quien todavía no está en condiciones de renunciar. La maniobra es filosóficamente consecuente —si la liberación fuera un efecto producido por una acción, sería temporal como todo efecto— y al mismo tiempo es la que más discusión ha generado, porque muchos lectores sostienen que fuerza el texto. Ramanuja escribirá su propio comentario al Gita justamente para devolverle a la devoción el primer lugar, y el debate entre las dos lecturas sigue vivo en la India contemporánea."},
   {t:"Upadesasahasri (Mil enseñanzas)", d:"Su única obra independiente de autoría segura, es decir, la única que no es comentario de otro texto, y por eso la pieza donde mejor se oye su voz propia. Tiene dos partes, una en prosa y otra en verso, y está escrita con una finalidad práctica declarada: enseñar a un discípulo que ya cumple los requisitos previos, no convencer a un adversario. La parte en prosa es casi un manual pedagógico y contiene escenas de instrucción real, con el maestro corrigiendo una y otra vez al alumno que dice haber entendido la identidad con Brahman pero sigue hablando de sí mismo como de un cuerpo que sufre. Allí aparece el método completo —escucha del texto, razonamiento sobre él, meditación sostenida hasta la realización directa— y también el análisis más fino de la frase tat tvam asi, donde Shankara explica que la identidad se obtiene descartando lo incompatible de cada término y reteniendo lo que queda: ni el yo limitado ni el dios señor del mundo, sino la conciencia pura que ambos presuponen."},
   {t:"Vivekachudamani (La joya suprema del discernimiento)", d:"Es, con enorme diferencia, el texto advaita más popular y más traducido, un poema de unos quinientos ochenta versos que expone el camino entero: el discernimiento entre lo eterno y lo transitorio, el desapego, las cinco envolturas que recubren al atman, la figura del maestro, la descripción del jivanmukta. Vivekananda lo difundió en Occidente y buena parte de lo que hoy se llama vedanta en círculos de espiritualidad viene de aquí más que del Brahmasutrabhashya. Ahora bien, hay que ser honestos con el dato erudito: la atribución a Shankara es dudosa y la mayoría de los indólogos contemporáneos la rechazan, por razones de vocabulario, de estilo y sobre todo de contenido, ya que incorpora elementos yóguicos y devocionales y un tratamiento de la experiencia mística que no encaja con el intelectualismo severo del comentarista. Lo más probable es que provenga de la tradición monástica posterior, tal vez del siglo XIV o más tarde. Conviene leerlo sabiendo eso: es una espléndida síntesis del Advaita vivido, no necesariamente el pensamiento del autor histórico."}
 ],
 conceptos:[
   {t:"Brahman", d:"Es la única realidad que hay, y todo el sistema depende de tomar esa frase literalmente y no como una exageración piadosa. Brahman no es un ente supremo entre otros entes, ni una causa que produzca el mundo desde afuera: es ser, conciencia y plenitud (sat-chit-ananda), sin partes, sin cambio, sin relación con nada, porque toda relación exige dos. Shankara distingue dos modos de hablar de él. Nirguna Brahman, sin atributos, es lo último y solo admite descripción negativa, porque cualquier determinación lo convertiría en un objeto entre objetos. Saguna Brahman, con atributos —el Ishvara, el señor personal del mundo, creador y providente—, es Brahman tal como aparece bajo las condiciones de la ignorancia, y es plenamente válido dentro del nivel convencional: no es una mentira, es el máximo que puede decirse desde adentro de la dualidad. Esta jerarquía es la que permite a Shankara ser al mismo tiempo un no dualista radical y un comentarista ortodoxo del culto teísta, y también la que sus adversarios le reprochan como una degradación encubierta de Dios."},
   {t:"Atman es Brahman", d:"El corazón del Advaita no es una tesis sobre el mundo sino sobre el sujeto: lo que uno es en el fondo, el atman, no se parece a Brahman ni participa de él ni es una chispa suya, es idénticamente Brahman. Los mahavakyas lo dicen sin atenuantes —eso eres tú, yo soy Brahman— y Shankara insiste en que son enunciados de identidad y no de semejanza ni de unión, porque unirse supone dos. El argumento no es místico sino analítico: aquello que en vos es testigo de todo estado —vigilia, sueño con imágenes, sueño profundo sin objetos— no puede ser ninguno de esos estados ni ninguno de sus contenidos; no es el cuerpo, que cambia, ni la mente, que se interrumpe, ni la biografía, que se recuerda. Lo que queda cuando se retira todo lo que puede ser objeto es conciencia sin objeto, y conciencia sin objeto no admite plural: no hay modo de distinguir dos conciencias puras, porque toda distinción vendría de un contenido. De ahí que el yo individual (jiva) sea Brahman visto a través de un limitador, como el espacio dentro de una vasija es el mismo espacio de afuera."},
   {t:"Maya", d:"Es el poder por el cual lo Uno aparece como múltiple, y el término que más malentendidos genera cuando se traduce sin más por ilusión. Maya no significa que el mundo sea una alucinación privada ni que las cosas no estén ahí: significa que su modo de ser no es el de la realidad última. Shankara le da un estatuto técnico preciso y muy incómodo, anirvacaniya, indefinible: el mundo no es real, porque lo real no puede ser cancelado por un conocimiento posterior; y tampoco es irreal, porque lo irreal —el hijo de una mujer estéril, el cuerno de una liebre— ni siquiera aparece. Es una tercera cosa que la lógica no consigue clasificar, y Shankara lo admite en vez de disimularlo. La analogía que usa es la del mago que hace aparecer un ejército: el espectador ve, reacciona, se asusta, y sin embargo nada de eso tiene la solidez que aparenta. Vale notar que la elaboración más técnica de maya como potencia casi sustancial pertenece más al Advaita posterior —Mandana Mishra, Vachaspati, Padmapada— que a Shankara mismo, que usa sobre todo el vocabulario de la superposición y de la ignorancia."},
   {t:"Avidya", d:"La ignorancia metafísica no es falta de información sino un error activo y estructural: tomar lo relativo por absoluto, confundir al sujeto con el objeto, atribuir al yo consciente propiedades que pertenecen al cuerpo. Shankara pone ejemplos gramaticales, que son los mejores porque muestran que el error está en la lengua que hablamos sin pensar: yo soy gordo, yo estoy enfermo, yo soy ciego, yo nací, yo voy a morir. En ninguna de esas frases el yo que pronuncia es lo que se describe, y sin embargo no podemos hablar de otro modo. Esa avidya es anadi, sin comienzo — no se puede fechar su origen, porque el tiempo mismo pertenece al mundo que ella hace aparecer. La caracterización es deliberada y también es el punto donde el sistema recibe su objeción más dura, porque si Brahman es lo único que hay y es conciencia pura sin segundo, no se ve de quién es esa ignorancia ni dónde reside. Shankara responde que la pregunta pertenece al nivel de lo que se quiere explicar y no puede plantearse desde el nivel último, pero conviene reconocer que eso es un movimiento de defensa y no una explicación."},
   {t:"Adhyasa: la cuerda y la serpiente", d:"Adhyasa es la superposición, y Shankara la define como la aparición de algo visto antes en otro lugar bajo la forma de un recuerdo, allí donde no está. El ejemplo canónico es la cuerda tomada por serpiente en la penumbra, y conviene desmenuzar por qué funciona tan bien como modelo de todo el sistema. Primero: el miedo es real, el salto hacia atrás es real, el corazón late de verdad — el error produce efectos, de modo que no se puede decir que no pasa nada. Segundo: la serpiente nunca existió, ni siquiera un instante, y por eso al llegar la luz no se transforma en cuerda ni desaparece como desaparece una cosa, simplemente se revela que nunca hubo tal cosa. Tercero, y es el punto decisivo: a la cuerda no le ocurre absolutamente nada en todo el proceso, no fue afectada por el error ni mejora con su disolución. Traducido: el mundo produce efectos mientras dura la ignorancia, Brahman no se ve tocado por ello, y la liberación no cambia la realidad sino la lectura. Otro ejemplo que usa, aún más fino, es el nácar tomado por plata, donde el sustrato sí está presente y brillando: no es que no veamos nada, es que vemos algo real y le superponemos lo que no es."},
   {t:"Los tres niveles de verdad", d:"El Advaita ordena lo que aparece en tres grados, y la distinción es la herramienta que le permite negar la realidad última del mundo sin volverse absurdo. Paramarthika es el nivel absoluto: allí solo hay Brahman, y ninguna otra afirmación sobrevive. Vyavaharika es el nivel práctico o transaccional: el mundo compartido de las cosas, las personas, las leyes físicas, el karma, los deberes y la ética, que es perfectamente coherente y estable mientras dura, y donde todo lo que decimos y hacemos vale. Pratibhasika es el nivel meramente aparente: la serpiente de la cuerda, el sueño, el espejismo, la alucinación, errores privados que se cancelan dentro del propio nivel práctico. Lo que hace inteligible al sistema es la regla de cancelación: algo es menos real que otra cosa si un conocimiento posterior lo anula. El sueño se anula al despertar, la serpiente al encender la luz, el mundo entero al realizar Brahman. La objeción obvia es que asimilar el mundo público al sueño privado suprime demasiado, y por eso Shankara mantiene con firmeza la diferencia entre pratibhasika y vyavaharika: contra los idealistas budistas insiste en que el mundo de la vigilia es intersubjetivo, coherente y regular, y no puede reducirse a imágenes mentales."},
   {t:"Jivanmukti (liberación en vida)", d:"Una de las tesis más características y más audaces del Advaita: si la liberación es conocimiento y no un premio futuro, entonces ocurre en el momento en que el conocimiento ocurre, y el liberado sigue caminando, comiendo y enseñando. El jivanmukta es quien ya sabe que es Brahman y a quien, sin embargo, le queda cuerpo por gastar, porque el karma ya en curso —la flecha que salió del arco, dice la imagen tradicional— agota su impulso aunque ya no se generen nuevos frutos. La consecuencia práctica es notable: el liberado no se distingue por poderes ni por señales externas sino por la ausencia de identificación con lo que le pasa, y puede seguir sintiendo hambre y dolor sin decir ya yo tengo hambre en el sentido metafísico de la frase. Esta doctrina es lo que le permite al Advaita ser un camino y no una promesa, y es también lo que distingue su ideal del de otras escuelas vedánticas que reservan la liberación para después de la muerte. Ramanuja la rechazó por eso, y el problema que deja abierto es delicado: si el cuerpo del liberado persiste por efecto de la ignorancia ya desatada, la ignorancia parece sobrevivir a su propia destrucción."},
   {t:"Neti neti (ni esto, ni esto)", d:"La fórmula viene de la Brihadaranyaka Upanishad y es el método negativo por excelencia: ante cualquier cosa que se ofrezca como candidata a ser el atman o Brahman, se responde ni esto, ni esto. No es agnosticismo ni pereza descriptiva, es una consecuencia estricta de la premisa: todo lo que pueda ser señalado, nombrado o convertido en objeto de conciencia es, por eso mismo, objeto y no sujeto, y Brahman es lo que en ningún caso puede volverse objeto. Se aplica de afuera hacia adentro. No soy este cuerpo, porque lo percibo. No soy estas sensaciones, porque las noto aparecer y pasar. No soy estos pensamientos, ni estas emociones, ni esta historia que cuento sobre mí, porque también las observo. Lo llamativo es que el procedimiento nunca termina en un objeto encontrado: termina cuando no queda nada que descartar y sigue habiendo quien descarta. Esa es la única indicación posible. La objeción que hay que tener a mano es que un método puramente negativo no distingue entre haber llegado a la conciencia pura y no haber llegado a nada — exactamente el punto donde el budista dirá que Shankara reifica un residuo que no está."},
   {t:"Jnana, el gurú y la jerarquía de los caminos", d:"Frente al karma marga (la vía del rito y de la acción) y al bhakti marga (la vía de la devoción), Shankara sostiene que solo el jnana, el conocimiento, libera, y el argumento no es de preferencia espiritual sino lógico: toda acción produce un efecto, todo efecto está en el tiempo y todo lo que está en el tiempo termina; si la liberación fuera producida, sería perecedera, y no sería liberación. Además, y esto es lo más fino, moksha no es algo que se obtenga, porque uno ya es Brahman: lo que hace falta no es producir un estado nuevo sino remover un error, y los errores se remueven con conocimiento, no con esfuerzo. Ahora bien, ese conocimiento no es información que se aprenda leyendo: requiere requisitos previos (discernimiento, desapego, dominio de sí, deseo de liberación), requiere la palabra del maestro que transmite el texto en el momento en que el discípulo puede recibirlo, y requiere la triple disciplina de escuchar, razonar y meditar hasta que el saber deja de ser una proposición. De ahí la centralidad del gurú y del linaje, que es también lo que explica por qué un filósofo de la no dualidad fundó órdenes monásticas con reglas, sucesiones y sedes."}
 ],
 conexion:"Su interlocutor decisivo es <b>Nagarjuna</b>, y el contraste conviene formularlo con precisión y no como un eslogan: ambos sostienen que el mundo tal como lo tomamos no tiene el modo de ser que le atribuimos, ambos distinguen dos niveles de verdad y ambos hacen de la liberación un asunto cognitivo; pero donde el Madhyamaka concluye que no queda ningún fundamento y que también la vacuidad está vacía, el Advaita concluye que queda exactamente uno, conciencia sin segundo. Esa diferencia es la que los rivales vedantinos no vieron o no quisieron ver cuando lo llamaron pracchanna bauddha, budista encubierto. Dentro del propio Vedanta sus adversarios son <b>Ramanuja</b>, que sostiene una no dualidad cualificada donde las almas y el mundo son el cuerpo real de Brahman, y <b>Madhva</b>, abiertamente dualista, y la historia del pensamiento indio posterior se escribe en gran medida como discusión con él. En la tradición europea el paralelo más citado es con <b>Parménides</b>, por la tesis de que solo el ser es y de que el cambio pertenece a la opinión, y con el neoplatonismo de Plotino, aunque la emanación es justamente lo que Shankara no admite. Con <b>Descartes</b> comparte el arranque —buscar lo que no puede ser puesto en duda examinando quién es el que duda— y se separa en el desenlace, porque donde Descartes encuentra una sustancia pensante individual, Shankara sostiene que la individualidad era parte de lo que había que descartar. Y con <b>Kant</b> hay un aire de familia engañoso entre fenómeno y vyavaharika, con una asimetría central: la cosa en sí kantiana es incognoscible, mientras que Brahman no solo puede conocerse sino que es lo único que se conoce de verdad, porque es el conocedor.",
 dialogo:{titulo:"La acusación de budista encubierto", lineas:[
   {quien:"Vedantin rival", texto:"Maestro, te acuso con respeto y con pruebas. Decís que el mundo no es real, que el yo individual no es real, que lo último es indecible y que solo se llega por vía negativa. Eso ya lo dijeron los budistas. Sos un pracchanna bauddha, un budista encubierto con vocabulario védico."},
   {quien:"Shankara", texto:"La acusación es antigua y la escuché muchas veces. Empecemos por lo que sí concedo: el método de negación es parecido, y la desconfianza del rito nos acerca. Pero decime en qué punto exacto creés que coincidimos."},
   {quien:"Vedantin rival", texto:"En que ambos vacían el mundo. Ellos dicen que nada tiene naturaleza propia, vos decís que nada salvo Brahman es real. La diferencia es de nombre."},
   {quien:"Shankara", texto:"No lo es, y es la diferencia que decide todo. Ellos niegan que haya un sustrato. Yo sostengo que la negación misma exige uno. Cuando decís que la serpiente no está, ¿qué es lo que sigue estando en tu mano?"},
   {quien:"Vedantin rival", texto:"La cuerda."},
   {quien:"Shankara", texto:"Exactamente. No hay error sin algo sobre lo cual el error se superpone. Un espejismo aparece sobre arena, no sobre nada. Si retirás todo sustrato, no explicás la ilusión: la duplicás, porque ahora también la ilusión flota sin apoyo. Por eso yo digo que lo que queda cuando cae todo lo negado no es un vacío, es aquello ante lo cual todo se negó."},
   {quien:"Vedantin rival", texto:"El budista te contestaría que ese sustrato tuyo es una cosa más, la última y la más difícil de soltar, y que vos también deberías negarla."},
   {quien:"Shankara", texto:"Que la niegue. Pero fijate quién niega. Aquello que es testigo de la negación no puede ser negado por ella, porque toda negación lo presupone. No afirmo a Brahman como un objeto que habría encontrado al final de la búsqueda; sostengo que es el buscador, y que por eso no puede caer con lo buscado.", nota:"Aquí se juega la diferencia real y no meramente verbal entre Advaita y Madhyamaka: el Advaita sostiene que la conciencia es autoluminosa (svayamprakasha) y no necesita ser conocida por otra cosa, mientras que para Nagarjuna también esa conciencia surge dependientemente y está vacía. Ninguno de los dos refuta al otro sin apelar a su propia premisa, y esa es la razón por la cual el debate duró siglos sin desenlace."},
   {quien:"Vedantin rival", texto:"Y sin embargo tus críticos señalan que tu maestro Govinda fue discípulo de Gaudapada, y que Gaudapada escribe sobre el no surgimiento en términos que cualquier madhyamika firmaría."},
   {quien:"Shankara", texto:"El parecido de las palabras no es prueba de la doctrina. Yo dediqué al budismo la refutación más larga de mi comentario a los Brahma Sutras, y no por cortesía: sostengo contra los vijñanavadines que el mundo de la vigilia no puede reducirse a imágenes de la mente, porque es compartido, regular y no obedece a nuestro deseo, y sostengo contra los sarvastivadines que una serie de instantes sin sustrato no puede ni siquiera recordar. Un budista encubierto no escribe eso."},
   {quien:"Vedantin rival", texto:"Concedido. Cambio entonces de acusación y voy a una peor. Si el mundo es maya y la casta, el rito y la jerarquía pertenecen al nivel convencional que vos mismo relativizás, ¿por qué fundaste monasterios con reglas, con sucesión y con sedes, y por qué mantuviste las restricciones sobre quién puede estudiar la revelación?"},
   {quien:"Shankara", texto:"Porque relativizar un nivel no es abolirlo. Mientras haya alguien que se crea un cuerpo, hay deberes para ese cuerpo. El que ya sabe no necesita reglas, pero el que enseña necesita que haya quien enseñe dentro de cien años.", nota:"Conviene no dejar pasar esta respuesta sin tensión. Es la objeción más fuerte que se le hace hoy, sobre todo desde el pensamiento dalit y desde las lecturas críticas de Ambedkar en adelante: una metafísica que declara ilusoria toda diferencia convivió, en la práctica, con la defensa del orden social que jerarquiza esas diferencias. Shankara puede responder con la doctrina de los niveles, pero el argumento corta hacia los dos lados, porque el mismo razonamiento que justifica mantener el orden podría justificar suprimirlo."},
   {quien:"Vedantin rival", texto:"Última pregunta, y es la que nadie de tu escuela me responde. Si Brahman es lo único que hay y es conciencia pura, ¿de quién es la ignorancia? ¿Dónde se aloja avidya?"},
   {quien:"Shankara", texto:"Esa pregunta pertenece al nivel que la propia pregunta quiere explicar. Preguntar cuándo empezó el error es como preguntar en qué momento del sueño empezó el sueño: la respuesta sería parte del sueño. Por eso digo que avidya no tiene comienzo, y que la única salida no es explicarla sino terminarla."},
   {quien:"Vedantin rival", texto:"Eso no es una respuesta, maestro."},
   {quien:"Shankara", texto:"No lo es. Es el reconocimiento de que la pregunta no se responde desde adentro. Si te resulta insuficiente, tenés razón; pero fijate que cualquier respuesta que te diera pondría dos cosas donde sostengo que hay una, y entonces la habría perdido antes de empezar."}
 ]},
 actividades:[
   {t:"Neti neti durante quince minutos, por escrito", d:"Sentate con una hoja y hacé el procedimiento de verdad, no como resumen teórico. Escribí arriba la pregunta quién es el que está mirando esto, y debajo empezá a descartar en orden, dedicando al menos un renglón a cada descarte y explicando por qué se descarta: no soy este cuerpo, porque lo percibo desde algún lado; no soy este dolor de espalda, porque aparece y se va mientras yo sigo; no soy esta emoción, porque la noto llegar; no soy los pensamientos, porque los veo pasar; no soy mi nombre, mi trabajo, mi historia, porque los recuerdo y lo recordado no es el que recuerda. Seguí hasta que se te acaben los candidatos, y cuando eso ocurra —va a ocurrir antes de lo que pensás— no cierres el cuaderno: quedate ahí y anotá con precisión qué es lo que sigue habiendo, si es que hay algo, y si eso que queda puede a su vez ser descrito o solo señalado. Terminá con un párrafo escéptico obligatorio, porque el ejercicio sin él es autoengaño: argumentá en contra de tu propio resultado, sosteniendo que lo que quedó no es una conciencia pura sino simplemente el hábito de decir yo, y que un método que solo resta no puede probar que haya un resto. Comparar tu propio párrafo a favor y tu párrafo en contra es el ejercicio real."},
   {t:"Buscar tu propia cuerda tomada por serpiente", d:"Reconstruí por escrito un episodio real y verificable de tu vida en el que sostuviste durante un tiempo una creencia, un miedo o una interpretación que después se disolvió del todo al ver mejor: alguien que creías que te despreciaba, un síntoma que te convenciste de que era grave, un malentendido que sostuviste durante meses, un recuerdo de infancia que resultó no haber ocurrido así. Escribilo en cuatro partes, sin saltear ninguna. Primero, la descripción de lo que creías ver, con el detalle con que lo veías. Segundo, el inventario honesto de los efectos reales que produjo mientras duró: qué dejaste de hacer, qué le dijiste a quién, cómo dormiste, cuánto tiempo ocupó. Tercero, el momento del cambio, y acá la consigna precisa: describí si algo cambió en la situación misma o solo en tu modo de verla. Cuarto, la pregunta advaita: cuando el error cayó, ¿la serpiente se transformó en cuerda o resultó que nunca hubo serpiente, y qué diferencia práctica hay entre esas dos descripciones? Cerrá discutiendo si te parece legítimo que Shankara pase de este tipo de caso, que todos reconocemos, al caso del mundo entero, que nadie ha visto disolverse."},
   {t:"Mapa personal de los tres niveles", d:"Armá una tabla de tres columnas encabezadas paramarthika, vyavaharika y pratibhasika y ubicá en ella, con el mayor detalle posible, quince cosas de tu propia experiencia: un sueño de anoche, la mesa donde escribís, tu documento de identidad, un espejismo en la ruta, el dolor de una muela, el valor del dinero que tenés en el bolsillo, una deuda, tu nacionalidad, el enojo de esta mañana, una alucinación por fiebre, las leyes de la física, tu apellido. Vas a descubrir rápido que la columna difícil no es la primera sino la frontera entre las otras dos, y ahí está el ejercicio: el dinero y la nacionalidad no son alucinaciones privadas, pero tampoco son como la mesa. Escribí un párrafo sobre cada caso que te haya costado ubicar, explicando qué criterio usaste — el de Shankara es la cancelación: algo es menos real si un conocimiento posterior lo anula sin dejar rastro. Terminá con dos preguntas escritas. La primera: ¿qué diferencia real hay entre decir que algo pertenece al nivel convencional y decir simplemente que es una construcción social? La segunda, más incómoda: si todo lo de la segunda columna es cancelable en principio, ¿cambia eso en algo lo que vas a hacer mañana a la mañana, y si no cambia nada, en qué sentido creés de verdad en la doctrina?"}
 ],
 cuestionario:[
   {q:"Sus rivales vedantinos lo llamaron pracchanna bauddha, budista encubierto. ¿Cuánta sustancia tiene la acusación frente al Madhyamaka de Nagarjuna?", p:"La acusación no es un insulto tardío sino una objeción técnica que le hicieron Bhaskara, Ramanuja y buena parte de la tradición posterior, y tiene apoyos reales. Los parecidos son notorios: dos niveles de verdad, un método negativo, la tesis de que el mundo tal como lo tomamos no tiene el modo de ser que le atribuimos, la liberación como asunto cognitivo, y una herencia directa a través de Gaudapada, cuyo tratado sobre la Mandukya usa la noción de no surgimiento (ajativada) en términos que un madhyamika suscribiría casi sin cambios. Pero la diferencia es sustantiva y no verbal: Nagarjuna sostiene que no hay sustrato alguno y que también la vacuidad está vacía, mientras que Shankara sostiene que la negación exige algo sobre lo cual se produjo el error, y que la conciencia es autoluminosa, es decir, no necesita ser conocida por otra para estar dada. Dicho de otro modo: uno termina sin fundamento por principio, el otro termina con exactamente uno. Que esto no es retórica lo prueba el propio texto, porque el comentario a los Brahma Sutras dedica al budismo su refutación más extensa y hostil, argumentando contra el idealismo vijñanavada que el mundo de la vigilia es público, regular y resistente al deseo, y contra el atomismo momentaneísta que una serie de instantes sin sustrato no puede sostener la memoria ni la identidad. Ahora bien, el residuo de la acusación sigue ahí y conviene decirlo: un madhyamika replicaría que ese sustrato indispensable es justamente el aferramiento último, la esencia que Shankara no consigue soltar, y ninguno de los dos puede refutar al otro sin apelar a su propia premisa de partida."},
   {q:"Si el mundo es maya, ¿no queda devaluada la acción ética y política dentro de él?", p:"La respuesta interna del sistema es la doctrina de los niveles: en vyavaharika el karma opera, las obligaciones obligan, el sufrimiento del otro es sufrimiento y la conducta correcta es requisito previo del conocimiento, no un adorno — sin dominio de sí, veracidad y desapego el estudio ni siquiera empieza. Maya no significa que nada importe, significa que el modo de ser del mundo no es el de lo último; y como el error produce efectos reales, aliviar esos efectos es una tarea real. Puede agregarse que la identidad de atman en todos los seres funda una compasión más radical que cualquier altruismo, porque el otro no es otro. Hasta ahí la defensa, que es buena. Lo que hay que poner del otro lado es más pesado. Primero, una asimetría estructural: si la meta última es el conocimiento y la meta última está en otro nivel, la acción en el mundo queda siempre como preparatoria, jerárquicamente inferior, y eso tiene consecuencias sobre a qué se dedica una vida. Segundo, el dato histórico: el Advaita convivió sin conflicto con el orden de castas, y Shankara mismo defiende restricciones sobre quién puede estudiar la revelación, de modo que la doctrina de los niveles funcionó, de hecho, como conservadora del nivel convencional tal como estaba. La crítica de Ambedkar y de la tradición dalit apunta exactamente ahí. Tercero, la réplica más honesta a favor: Vivekananda y el neovedanta del siglo XX derivaron del mismo principio de identidad un programa de servicio social y de igualdad, lo que muestra que la doctrina no determina por sí sola una política, y que en ambos casos hace falta un paso adicional que no está en los textos."},
   {q:"Si Brahman es la única realidad y es conciencia pura sin segundo, ¿de quién es avidya y cómo surgió?", p:"Es el problema clásico del sistema y sigue abierto: se lo conoce como la cuestión del asraya y del ambito de la ignorancia. El dilema es limpio. Si avidya reside en Brahman, entonces lo último está manchado por la ignorancia y deja de ser pura conciencia. Si reside en el jiva, el yo individual, hay circularidad, porque el jiva es precisamente un producto de avidya y no puede ser anterior a lo que lo produce. Si reside en algún tercer lugar, ya hay dos cosas y el no dualismo se perdió antes de empezar. Las respuestas de la escuela son varias y ninguna satisface del todo. La de Shankara es la más sobria: avidya es anadi, sin comienzo, de modo que la pregunta por su origen presupone un tiempo que solo existe dentro de lo que ella produce, y la pregunta se cae por mal planteada; el error no se explica, se termina. El Advaita posterior fue más lejos con la categoría de anirvacaniya, indefinible: avidya no es real ni irreal, y precisamente por eso escapa a la disyunción. Vachaspati Mishra la sitúa en el jiva y Padmapada en Brahman, y la existencia misma de esa división interna muestra que el problema no se resolvió. Un crítico dirá, con razón, que llamar indefinible a lo que no se puede explicar es ponerle nombre al agujero. Vale recordar dos cosas en descargo: que casi todas las metafísicas monistas tienen una versión del mismo problema, incluido el neoplatonismo con la caída del alma y la teodicea cristiana con el origen del mal; y que el propio Shankara nunca pretendió deducir la ignorancia, porque en su sistema explicarla equivaldría a legitimarla."},
   {q:"Solo el conocimiento libera, dice Shankara. ¿Qué pasa entonces con la devoción, que es el corazón de la religiosidad hindú vivida?", p:"La tensión es real y es la que más consecuencias tuvo en la historia posterior. La posición de Shankara es jerárquica, no excluyente: la devoción y la acción desinteresada purifican la mente, concentran, disuelven el egoísmo y son preparación indispensable, pero no liberan, porque la liberación no es un efecto producido y todo lo que la devoción obtiene es obtenido y por tanto perecedero. Su argumento es fuerte y consecuente: si moksha fuera el resultado de una acción, de una gracia o de un mérito, estaría en el tiempo y terminaría. Además, uno ya es Brahman, así que no hay nada que conseguir, solo un error que remover, y los errores se remueven conociendo. El costo de esa coherencia es alto. Por un lado, obliga a leer el Bhagavad Gita a contrapelo de lo que parece decir, subordinando lo que el poema presenta como camino pleno. Por otro, deja a Ishvara, el dios personal, en el nivel de saguna Brahman, es decir, como verdad de rango inferior, lo cual para un devoto no es una jerarquía técnica sino una degradación de aquello a lo que le reza. Ramanuja construyó todo su Vishishtadvaita como respuesta a esto: una no dualidad cualificada donde las almas y el mundo son el cuerpo real de Brahman, donde la diferencia es verdadera y donde la devoción es el camino, no la antesala. Madhva fue más lejos aún hacia el dualismo. El dato sociológico es elocuente: la religiosidad hindú mayoritaria siguió a la bhakti y no al Advaita, aunque el Advaita se quedó con el prestigio filosófico, y esa división de aguas persiste hoy."},
   {q:"Si el yo individual es en última instancia irreal, ¿queda lugar para la responsabilidad moral personal?", p:"La objeción se puede formular con dureza: si no hay individuos, no hay agentes; si no hay agentes, no hay a quién imputar nada, y el asesino y su víctima son igualmente Brahman. La defensa advaita opera en dos tiempos. En el nivel vyavaharika, que es el único donde la pregunta tiene sentido, el jiva es plenamente agente, el karma funciona con rigor y la responsabilidad es entera — de hecho el sistema es más exigente que muchos, porque ningún acto queda sin fruto. En el nivel paramarthika no hay acción ni agente ni responsabilidad, pero tampoco hay nadie que pudiera aprovechar esa noticia para eximirse: quien invoca la irrealidad del yo para justificar un acto está hablando desde el yo cuya irrealidad invoca, y por eso mismo se contradice en el acto de hablar. Es una respuesta buena y vale la pena tenerla clara. Quedan dos problemas. El primero es que la asimetría entre los niveles no es simétrica en la práctica: el liberado ya no genera karma nuevo, y sobre qué obliga exactamente a un jivanmukta las fuentes dicen poco y a veces dicen que nada, lo que deja un margen incómodo. El segundo es más profundo y lo comparte con toda ética construida sobre la identidad: si el otro no es realmente otro, no está claro que quede espacio para la alteridad que la ética parece exigir — se puede fundar en la identidad una compasión muy amplia, pero no evidentemente un deber hacia alguien, porque el deber supone dos. Es exactamente la objeción que un lector de Levinas le haría, y también, desde el otro lado, la que le hace un budista: la compasión no necesita que el otro sea yo, le basta con que sufra."}
 ],
 cadena:{ titulo:"¿El mundo es un sueño?", intro:"Un razonamiento en ramas sobre la frase que más se repite del Advaita y que peor se entiende: solo Brahman es real, el mundo no lo es. Las ramas pasan por la discusión de Shankara con los budistas idealistas, el criterio de la cancelación, la relación entre Brahman y el mundo y el problema abierto de dónde se aloja la ignorancia.", inicio:"n1", nodos:{
   n1:{ pregunta:"Shankara dice que solo Brahman es real y que el mundo múltiple es una superposición, como la serpiente vista en la cuerda. ¿Qué estatuto le da eso al mundo de todos los días?", opciones:[
     {texto:"El mundo es una alucinación: en realidad no existe.", va:"n2a"},
     {texto:"El mundo es real a su nivel, el de la práctica (vyavahārika), pero no es la realidad última.", va:"n2b"} ]},
   n2a:{ pregunta:"Shankara rechazó con fuerza esa lectura cuando la defendían los budistas idealistas (vijñānavāda). En su comentario a los Brahma Sutras (2.2.28-29) sostiene que los objetos de la vigilia se perciben como externos y que la vigilia no es como el sueño. Entonces, ¿qué distingue a la vigilia del sueño?", opciones:[
     {texto:"Nada de fondo: la vigilia es un sueño más largo y más compartido.", final:{tipo:"revisar", texto:"Es justamente lo que Shankara niega. Lo que se sueña queda cancelado al despertar; lo que se percibe despierto no queda cancelado por ninguna otra experiencia de vigilia. Por eso el Advaita necesita tres niveles y no dos: lo ilusorio (pratibhāsika), como el sueño y la serpiente; lo práctico (vyavahārika), como la cuerda y el mundo; y lo absoluto (pāramārthika). Volvé un paso y pensá qué hace falta para cancelar el nivel práctico."}},
     {texto:"Que a la vigilia no la contradice ninguna otra experiencia de vigilia: solo la cancela el conocimiento de Brahman.", va:"n3a"} ]},
   n3a:{ pregunta:"El criterio es la cancelación (bādha): es real lo que ninguna experiencia posterior desmiente. Según eso, ¿por qué Brahman no podría ser cancelado a su vez?", opciones:[
     {texto:"Porque Brahman es la conciencia testigo (sākṣin) que está presente en toda cancelación: para negarla habría que suponerla.", final:{tipo:"bien", texto:"Es el argumento más filosófico del sistema, y se parece al cogito de Descartes sin ser igual: no prueba la existencia de un yo individual, sino de una conciencia sin dueño que acompaña toda experiencia, incluida la de dudar. Es la misma réplica que Shankara le da al budista en el diálogo de esta ficha. El costo: tenés que aceptar que la conciencia que testimonia y la realidad de las cosas son la misma, y ese paso no lo da el argumento, lo dan las Upanishads."}},
     {texto:"Porque las Upanishads lo enseñan, y son la única fuente válida para conocer a Brahman.", final:{tipo:"bien", texto:"Es fiel a Shankara y suele sorprender: para él, Brahman no se demuestra por razonamiento, sino que se conoce por la escritura (Brahma Sutras 1.1.3, «porque la escritura es su fuente»), y el razonamiento sin apoyo, dice, no tiene base firme (2.1.11). La razón sirve para defender y aclarar lo que la escritura enseña. Ganás precisión histórica; tenés que asumir que el sistema no es una filosofía que se sostiene sola, sino una exégesis, y explicar qué le dice a quien no acepta los Vedas."}} ]},
   n2b:{ pregunta:"Si el mundo es real a su nivel y Brahman es lo único último, falta decir cómo se relacionan. ¿Cómo «da origen» Brahman al mundo?", opciones:[
     {texto:"Como un alfarero hace vasijas: Brahman es el artesano que fabrica el mundo desde afuera.", final:{tipo:"revisar", texto:"Esa es la imagen de las escuelas dualistas, como el Nyāya, para las que Dios solo es causa eficiente y trabaja una materia distinta de él. Shankara la rechaza: Brahman es a la vez causa eficiente y causa material del mundo (Brahma Sutras 1.4.23). Si hubiera una materia aparte, habría dos realidades, y el sistema se llama justamente no-dual (advaita). Volvé un paso y probá otra imagen."}},
     {texto:"Como la arcilla y las vasijas: las vasijas son solo nombres y formas; lo real es la arcilla (Chandogya Upanishad 6.1.4).", va:"n3b"} ]},
   n3b:{ pregunta:"Si el mundo es Brahman visto con nombres y formas, lo que lo hace parecer múltiple es la ignorancia (avidyā). Pero si Brahman es lo único que hay y es pura conciencia, ¿de quién es esa ignorancia?", opciones:[
     {texto:"Del yo individual (jīva): es él quien ignora que es Brahman.", final:{tipo:"bien", texto:"Es la respuesta que desarrolló la escuela Bhāmatī, siguiendo a Vācaspati Miśra. Su dificultad es una circularidad: el yo individual es él mismo producto de la ignorancia, así que la ignorancia se apoya en algo que ella misma produce. Shankara no resolvió el problema y es honesto al respecto: en el comentario al Gita (13.2) responde, en sustancia, que la ignorancia es de quien la ve, de quien pregunta. Es una respuesta que reconoce que la pregunta no se contesta desde afuera."}},
     {texto:"De Brahman: lo Uno se oculta a sí mismo bajo la ignorancia.", final:{tipo:"bien", texto:"Es la respuesta de la escuela Vivaraṇa (Prakāśātman), que prefiere poner la ignorancia en Brahman para evitar la circularidad. Su dificultad es la opuesta: si Brahman es conciencia pura, ¿cómo puede ignorar algo? Rāmānuja convirtió esto en su objeción principal contra el Advaita. Elegiste una salida coherente; tenés que explicar cómo la luz puede cubrirse a sí misma."}} ]}
 }},
 reconstruccion:[
   { titulo:"La superposición: el comienzo del comentario a los Brahma Sutras",
     consigna:"Reconstruí el argumento con el que Shankara abre su obra mayor, antes de comentar un solo aforismo. Una pieza viene de la escuela rival y elimina el sustrato: dejala afuera.",
     piezas:[
       {id:"s1", texto:"El sujeto (lo que se dice «yo») y el objeto (todo lo que se le presenta como «otro») son de naturaleza opuesta, como la luz y la oscuridad: no pueden identificarse.", tipo:"premisa"},
       {id:"s2", texto:"Sin embargo, en la vida diaria los mezclamos todo el tiempo: decimos «yo estoy gordo», «yo soy sordo», «esto es mío», atribuyendo al sujeto rasgos del cuerpo, de los sentidos y de las cosas.", tipo:"premisa"},
       {id:"s3", texto:"Esa atribución de lo que es propio de una cosa a otra es una superposición (adhyāsa), del mismo tipo que ver una serpiente en una cuerda.", tipo:"premisa"},
       {id:"s4", texto:"Toda práctica de conocimiento ordinaria —percibir, inferir, cumplir los mandatos rituales— parte de un «yo» que conoce, actúa y tiene un cuerpo: presupone la superposición.", tipo:"premisa"},
       {id:"s5", texto:"Por lo tanto, la superposición, llamada avidyā, es natural y sin comienzo, y las Upanishads se estudian para removerla con el conocimiento de la unidad del atman, no para agregar acciones.", tipo:"conclusion"},
       {id:"sx", texto:"Como la serpiente nunca estuvo, tampoco la cuerda: lo único que hay es la superposición, sin nada debajo.", tipo:"distractor"}
     ],
     ordenCorrecto:["s1","s2","s3","s4","s5"],
     explicacion:"El argumento va de una oposición conceptual (s1) a un hecho de experiencia que parece contradecirla (s2), lo explica como superposición (s3), la generaliza a todo conocimiento ordinario (s4) y saca la tarea de las Upanishads (s5). El punto débil es s1: si sujeto y objeto se oponen como la luz y la oscuridad, ¿cómo pueden confundirse? Shankara lo admite casi de entrada, cuando dice que la superposición es natural (naisargika) aunque no debería ser posible, y Rāmānuja atacó por ahí. Notá también lo que s4 implica: la percepción, la ciencia y la moral son válidas, pero dentro de la ignorancia, y eso las rebaja de nivel sin anularlas. La pieza sobrante es la posición que Shankara le atribuye a los budistas: sin cuerda, dice, no hay ni siquiera error."},
   { titulo:"Por qué la acción no libera",
     consigna:"Reconstruí el argumento con el que Shankara sostiene que solo el conocimiento libera. Una pieza saca de él una consecuencia que Shankara rechaza: dejala afuera.",
     piezas:[
       {id:"j1", texto:"Toda acción tiene uno de cuatro resultados: produce algo, lo transforma, lo obtiene o lo purifica.", tipo:"premisa"},
       {id:"j2", texto:"Lo que resulta de una acción tiene comienzo, y lo que tiene comienzo tiene fin: es perecedero.", tipo:"premisa"},
       {id:"j3", texto:"La liberación (mokṣa) es eterna, y no es un estado nuevo: es la naturaleza misma del atman, que ya es Brahman.", tipo:"premisa"},
       {id:"j4", texto:"Lo que uno ya es no se puede producir, transformar, obtener ni purificar: solo se puede dejar de ignorarlo.", tipo:"premisa"},
       {id:"j5", texto:"Por lo tanto, la liberación no es el resultado del rito ni de las obras, sino del conocimiento que quita la ignorancia; la acción solo prepara la mente para ese conocimiento.", tipo:"conclusion"},
       {id:"jx", texto:"Por lo tanto, quien busca la liberación puede dejar de lado la ética, porque las obras no sirven para nada.", tipo:"distractor"}
     ],
     ordenCorrecto:["j1","j2","j3","j4","j5"],
     explicacion:"La lista de cuatro resultados posibles de la acción está en el comentario a los Brahma Sutras (1.1.4) y es el centro de la polémica de Shankara con la escuela ritualista (Mīmāṃsā), para la cual el sentido de los Vedas es mandar acciones. El punto débil es j3, que hace todo el trabajo: si la liberación fuera un estado nuevo, como sostienen muchas escuelas devocionales, el argumento no prueba nada. Por eso la discusión con Rāmānuja no es sobre lógica, sino sobre qué es la liberación. La pieza sobrante invierte a Shankara: para él la disciplina ética —el discernimiento, el desapego, el dominio de sí— es requisito para que el conocimiento pueda darse; lo que niega es que sea la causa de la liberación."}
 ],
 dilemas:[
   { titulo:"«Ya no soy nadie»",
     intro:"Para Shankara, el sufrimiento de fondo viene de la superposición: tomar por uno mismo lo que es del cuerpo, de la mente o de los papeles que uno cumple. Este caso pregunta qué hace esa idea frente a una crisis real, y dónde se vuelve una herramienta lúcida y dónde una evasión.",
     pasos:[
       { id:"p1", situacion:"Tu tío Martín, de cincuenta y dos años, fue despedido después de veinticinco años como gerente de una sucursal bancaria. Hace dos semanas que casi no sale. Una noche te dice: «Ya no soy nadie». ¿Qué le respondés?", opciones:[
         {texto:"«Sos mucho más que tu trabajo: sos padre, sos esposo, sos mi tío.»", consecuencia:"Es una respuesta generosa y probablemente lo ayude. Pero notá lo que hiciste en términos de Shankara: cambiaste un papel por otros papeles. El neti neti también se aplica a ellos —ni padre, ni esposo, ni tío— porque todos pueden perderse. Lo consolaste en el nivel práctico, que no es poco, sin tocar la superposición.", va:"p2"},
         {texto:"«Nada de eso eras vos. Lo que sos no se puede perder.»", consecuencia:"Es, palabra por palabra, la enseñanza del Advaita, y puede ser verdadera. Pero Shankara exige que el que escucha esté preparado para escucharla, y le asigna al maestro la tarea de enseñar según quién tiene enfrente. Dicha a alguien en duelo, a las dos semanas, puede sonar a que su pérdida no importa.", va:"p2"},
         {texto:"No hablo de identidad: lo ayudo a actualizar el currículum y a buscar contactos.", consecuencia:"Atendés el nivel práctico, donde las cuentas y el trabajo son perfectamente reales, y eso Shankara no lo desprecia. Pero la frase de Martín no era sobre el currículum: decía quién cree que es. Si solo encuentra otro puesto, la misma superposición queda lista para el próximo despido o para la jubilación.", va:"p2"} ]},
       { id:"p2", situacion:"Un mes después, Martín está más tranquilo. Empezó a leer sobre el Vedanta y te dice: «Si todo esto es maya, no tiene sentido buscar trabajo ni pagar las deudas. No es real». ¿Qué le respondés?", opciones:[
         {texto:"«Según lo que leíste, tenés razón.»", consecuencia:"No según Shankara. El nivel práctico obliga a quien vive en él: las deudas existen para quien las contrajo, y el liberado en vida sigue actuando. Shankara mismo fundó monasterios, escribió y viajó. Usar la palabra maya para no hacerse cargo es la lectura que sus críticos le reprochan al sistema, y que el sistema rechaza.", va:"p3"},
         {texto:"«Que algo no sea último no quiere decir que no te obligue. Las deudas son reales en el nivel en que las firmaste.»", consecuencia:"Usaste bien la doctrina de los niveles: relativizar no es abolir. Queda una objeción honesta, que conviene no esquivar: si el nivel práctico es al final una superposición, ¿por qué tomarse en serio sus obligaciones? La respuesta de Shankara es que mientras uno se crea un cuerpo, hay deberes para ese cuerpo.", va:"p3"},
         {texto:"«El Vedanta es una manera de evadirte. Dejá de leer eso.»", consecuencia:"Reaccionaste contra el uso evasivo, y la crítica tiene fuerza: muchos autores modernos, desde Vivekananda en adelante, insistieron en que el Vedanta tenía que volverse práctico y social para no ser una huida. Pero descartaste la lectura entera por un mal uso. Martín encontró ahí algo que lo sostuvo cuando el cargo dejó de hacerlo.", va:"p3"} ]},
       { id:"p3", situacion:"Seis meses después, Martín consiguió un trabajo de menor rango en una cooperativa. Te pregunta qué aprendiste vos de todo esto. ¿Qué le decís?", opciones:[
         {texto:"«Que uno no es su cargo, pero el cargo igual hay que hacerlo bien.»", consecuencia:"Es la distinción de niveles hecha vida cotidiana: el desapego no es indiferencia hacia la tarea, es no apoyar en ella lo que uno es.", va:null},
         {texto:"«Que todo es ilusión y no conviene apegarse a nada.»", consecuencia:"Es la versión popular del Advaita, y pierde lo más fino: el mundo no es ilusión como la serpiente, sino real a su nivel. Y la frase deja afuera lo que pasó de verdad: Martín sufrió, buscó, trabajó y fue ayudado.", va:null},
         {texto:"«Que no sé si lo que somos de fondo es Brahman, pero sí vi lo que pasa cuando uno cree que es su puesto.»", consecuencia:"Separaste el diagnóstico de Shankara —la superposición que hace sufrir— de su metafísica —la identidad del atman con Brahman—. Se puede aceptar lo primero sin lo segundo, aunque Shankara diría que el diagnóstico solo se cura del todo con lo segundo.", va:null} ]}
     ],
     rubrica:[
       "Puedo explicar con este caso qué es la superposición y por qué un papel social puede funcionar como la serpiente sobre la cuerda.",
       "Apliqué el neti neti también a los papeles que consuelan (padre, esposo), no solo a los que se pierden.",
       "Distinguí el nivel práctico del absoluto y no usé el segundo para desentenderme de las obligaciones del primero.",
       "Tuve en cuenta que, para Shankara, la enseñanza depende de quién la recibe y de cuándo.",
       "Evité que la palabra maya funcionara como excusa para no hacerse cargo.",
       "Separé el diagnóstico de Shankara (la superposición) de su tesis metafísica (atman es Brahman) y dije cuál de los dos acepto.",
       "Formulé la objeción más fuerte: que un sistema que relativiza el mundo puede servir para conformarse con él, como sus críticos señalaron respecto de las castas."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.shankara = { lecturas:[
 {titulo:"Advaita Vedanta: Brahman, atman, maya y la superposición", fuente:"Enrique Gallud Jardiel, «El maestro Shankara» — Instituto de Indología (semblanza y textos traducidos al español)", url:"https://institutodeindologia.es/index.php/articulos/filosofia/557-el-maestro-shankara-enrique-gallud-jardiel",
  extracto:`Shankara abre su comentario a los Brahma Sutras con un texto breve y decisivo, el Adhyāsa-bhāṣya, dedicado a un solo concepto: adhyāsa, «superposición». La define como «la aparición, en la forma del recuerdo, de algo visto antes en otro lugar». Como cuando vemos nácar y creemos ver plata, o vemos una cuerda en la penumbra y creemos ver una serpiente.

El punto de partida es que sujeto y objeto —el «yo» y el «tú», lo consciente y lo inconsciente— son tan opuestos como la luz y la oscuridad, y sin embargo los confundimos constantemente: decimos «yo soy gordo», «yo estoy enfermo», «yo soy ciego», atribuyendo al yo consciente propiedades del cuerpo. Esa confusión natural y beginningless es avidyā, la ignorancia metafísica de fondo, y es la raíz de todo el vyavahāra, el mundo de la práctica cotidiana.

La tesis positiva es la no dualidad, y el indólogo Enrique Gallud Jardiel la resume con precisión: en Shankara «existe una identidad estricta entre la realidad última, el Brahman, y el âtman o Yo, el alma individual». Brahman es la realidad última: sin partes, sin atributos, sin cambio, definida negativamente en las Upanishads con la fórmula «neti, neti» («ni esto, ni esto»), porque cualquier determinación lo limitaría. Y atman, el yo más profundo, no es una parte de Brahman ni una emanación: es idéntico a Brahman. Los mahāvākyas o «grandes dichos» lo formulan: «tat tvam asi» («eso eres tú»), «aham brahmāsmi» («yo soy Brahman»), «prajñānam brahma» («la conciencia es Brahman»).

Maya nombra el poder por el cual lo Uno aparece como múltiple. «Esta teoría acentúa la irrealidad del mundo fenoménico», resume Gallud Jardiel; pero Shankara es cuidadoso aquí: el mundo no es simplemente irreal. Su estatus es anirvacanīya, «indefinible» — ni real como Brahman ni irreal como el hijo de una mujer estéril. Es real mientras dura la ignorancia, del mismo modo que la serpiente es plenamente aterradora mientras creemos verla, y desaparece sin dejar rastro cuando llega la luz: «sólo la meditación nos lleva a saber que la serpiente ilusoria es en realidad una cuerda». Nada le ocurre a la cuerda en el proceso: el error no modifica la realidad, solo nos modifica a nosotros.

De ahí se sigue la doctrina de los dos niveles de verdad: el pāramārthika (último), donde solo Brahman es, y el vyāvahārika (convencional), donde valen los objetos, las personas, el karma y los deberes rituales. Shankara no invalida la vida práctica; la sitúa. La consecuencia fue audaz para su tiempo: «el maestro asignó a la mayor parte de los textos védicos el rango de verdad de nivel inferior», reservando el nivel último para los pasajes upanishádicos sobre la identidad de atman y Brahman.

La consecuencia soteriológica es la más peculiar de su sistema. Si atman ya es Brahman, la liberación (moksha) no puede ser algo que se produzca: no es un efecto de una acción, porque todo efecto sería temporal. Moksha es solo conocimiento — el reconocimiento de lo que siempre fue el caso. No se gana, se descubre: «la salvación sólo puede conseguirse por la vía del conocimiento, mediante el ejercicio del entendimiento», y «la auténtica liberación sólo llega mediante la percepción absoluta de la propia identidad con el âtman». Por eso el camino no consiste en rituales sino en escuchar los textos (śravaṇa), reflexionar sobre ellos (manana) y meditar hasta la realización directa (nididhyāsana).`,
  comentario:"El ejemplo de la cuerda y la serpiente hace todo el trabajo filosófico: explica a la vez por qué el mundo aparece, por qué no es del todo irreal y por qué la liberación es cognitiva y no productiva. Eso responde la pregunta del cuestionario: si moksha fuera un efecto de acciones, sería temporal como todo efecto. Y el contraste con Nagarjuna es máximo: donde Shankara encuentra una realidad última sin atributos, el Madhyamaka encuentra la vacuidad de toda naturaleza propia, incluida la de Brahman."}
], preguntasLectura:[
 {q:"¿Qué es adhyāsa (superposición) en Shankara?", opciones:["Una técnica de meditación","Atribuir a una cosa las propiedades de otra, como ver plata en el nácar","Un ritual védico","La unión del alma con Dios"], r:"Atribuir a una cosa las propiedades de otra, como ver plata en el nácar", why:"Es el concepto con que abre su comentario a los Brahma Sutras y la raíz de avidyā."},
 {q:"¿Cuál es el estatus del mundo según el Advaita?", opciones:["Plenamente real como Brahman","Totalmente irreal, como el hijo de una mujer estéril","Anirvacanīya: indefinible, ni real ni irreal","Un castigo por el karma"], r:"Anirvacanīya: indefinible, ni real ni irreal", why:"Es real mientras dura la ignorancia, como la serpiente vista en la cuerda."},
 {q:"¿Por qué moksha no puede ser el efecto de una acción?", opciones:["Porque las acciones están prohibidas","Porque todo efecto sería temporal, y la liberación no lo es","Porque solo los brahmanes pueden actuar","Porque el karma no existe"], r:"Porque todo efecto sería temporal, y la liberación no lo es", why:"Por eso moksha es conocimiento: «la salvación sólo puede conseguirse por la vía del conocimiento, mediante el ejercicio del entendimiento»."},
 {q:"¿Qué hizo Shankara con la mayor parte de los textos védicos rituales?", opciones:["Los rechazó como falsos","Les asignó el rango de verdad de nivel inferior, reservando el nivel último a la identidad atman-Brahman","Los declaró apócrifos","Los tradujo al sánscrito clásico"], r:"Les asignó el rango de verdad de nivel inferior, reservando el nivel último a la identidad atman-Brahman", why:"Es la aplicación de los dos niveles de verdad a la propia autoridad escritural: no invalida la práctica, la sitúa."}
]};
