/* ============================================================
   Ficha: zhuangzi  ·  tradición: asiatica
   Datos de la ficha (MODULES) y sus lecturas (LECTURAS).
   El orden de las fichas en la app lo define index.html.
   ============================================================ */

MODULES.push(
{id:"zhuangzi", trad:"asiatica", nombre:"Zhuangzi", fechas:"c. 369–286 a.C. · China", escuela:"Taoísmo", icon:"🦋", profundizada:true,
 tesis:"Toda afirmación se hace desde algún lugar, y no hay un lugar privilegiado desde el cual arbitrar entre lugares. Zhuangzi despliega esa tesis con parábolas en vez de demostraciones: el hombre duerme en lo húmedo y enferma, la anguila no; el mono se trepa donde el hombre tiembla; los peces huyen de las mujeres que los hombres consideran más bellas. De ahí no se sigue que nada sea verdad, sino que las disputas entre escuelas sobre esto y aquello —confucianos contra moístas, cada uno afirmando lo que el otro niega— se libran sobre distinciones que el lenguaje fabrica y que después se confunden con el mundo. La consecuencia práctica no es la parálisis sino el xiaoyaoyou, el vagar libre y sin rumbo de quien dejó de necesitar que el universo le dé la razón: el cocinero que corta siguiendo la veta, el árbol nudoso que vive mil años porque ningún carpintero lo quiere, el viudo que canta golpeando una vasija porque entendió que su mujer volvió a la gran transformación. Del hombre mismo, Zhuang Zhou, sabemos poco y conviene decirlo: un funcionario menor en un jardín de lacas en Meng, contemporáneo de Mencio, que según Sima Qian rechazó el cargo de primer ministro de Chu prefiriendo arrastrar la cola en el barro como una tortuga viva antes que ser venerado como un caparazón sagrado en un templo.",
 obras:[
   {t:"Neipian: los Capítulos Interiores (1-7)", d:"El libro que la tradición llama Zhuangzi llegó hasta nosotros en la edición de treinta y tres capítulos que Guo Xiang fijó en el siglo III d.C., recortando una compilación anterior de cincuenta y dos. De ese conjunto, solo los siete primeros —los Neipian o Capítulos Interiores— se atribuyen con alguna confianza al propio Zhuang Zhou: los une un vocabulario consistente, un humor reconocible, una estrategia argumentativa común y, según los estudios de estilo y de rima, una capa lingüística más antigua que la del resto. Sus títulos son frases y no etiquetas temáticas, cosa que en la literatura china antigua suele indicar composición deliberada: paseo libre y despreocupado, sobre la igualación de las cosas, las claves para nutrir la vida, el mundo de los hombres, la señal de la virtud completa, el gran maestro ancestral, responder a emperadores y reyes. No hay tratado ni sistema: hay anécdotas, diálogos con interlocutores inventados, animales que discuten, artesanos que saben más que los duques, personajes mutilados o deformes que resultan ser los más íntegros. El lector que busque tesis expuestas y defendidas se frustra; el que acepte el procedimiento descubre que la forma es parte del argumento, porque un libro contra las distinciones fijas que procediera por definiciones se refutaría a sí mismo en la primera línea."},
   {t:"Xiaoyaoyou: paseo libre y despreocupado (capítulo 1)", d:"El libro abre con un pez descomunal llamado Kun que se transforma en un pájaro llamado Peng, cuyo lomo mide no se sabe cuántos miles de li y que, para migrar al Lago Celestial del sur, necesita batir el agua durante noventa li y remontar un torbellino hasta noventa mil li de altura. Desde abajo, la cigarra y la pequeña codorniz se ríen: nosotras saltamos y llegamos a la rama, y si no llegamos caemos al suelo, para qué subir noventa mil li rumbo al sur. Zhuangzi comenta seco que el conocimiento pequeño no alcanza al grande, como el hongo de una mañana no conoce el ciclo de la luna. Pero el capítulo no se detiene ahí, y ese es su punto más fino: también el Peng depende, del viento acumulado bajo sus alas, de la estación, del torbellino, igual que Liezi, que cabalgaba el viento con fría destreza pero necesitaba viento. La libertad plena sería la de quien monta sobre lo que es así por sí mismo y no depende de nada. El capítulo cierra con la calabaza gigantesca que Huizi considera inútil y con el árbol nudoso que ningún carpintero tala, dos imágenes que convierten la inutilidad en condición del paseo. Lo que parecía una fábula sobre lo grande contra lo pequeño termina siendo una advertencia contra medir la libertad por tamaño."},
   {t:"Qiwulun: sobre la igualación de las cosas (capítulo 2)", d:"Es el capítulo filosóficamente más denso y el más discutido, y hasta su título es ambiguo: puede leerse como la igualación de las cosas o como la igualación de los discursos sobre las cosas, y la sintaxis china admite ambas lecturas. Empieza con Ziqi, que está sentado y dice haber perdido su propio yo, y con la imagen de las flautas de la tierra, del hombre y del cielo: el viento no tiene sonido propio, suena distinto en cada oquedad, y cada oquedad cree que el sonido es suyo. Sigue el núcleo polémico contra los debatientes profesionales de la época, con el argumento del juez imparcial —si quien nos arbitra coincide con vos no es imparcial, si coincide conmigo tampoco, si difiere de los dos no puede decidir, y si coincide con los dos no hay nada que decidir—, la parábola del cuidador que ofrece a sus monos tres castañas por la mañana y cuatro por la tarde y los enfurece, hasta que invierte el reparto a cuatro y tres y los deja contentos, y la serie de preguntas sobre el hábitat, el gusto y la belleza que ningún animal comparte con el hombre. El capítulo termina con el sueño de la mariposa. Quien quiera decidir si Zhuangzi es un relativista, un escéptico o un terapeuta del lenguaje tiene que hacerlo aquí, porque todas las lecturas rivales se apoyan en estas mismas páginas."},
   {t:"Yangshengzhu: el cocinero Ding y el arte de nutrir la vida (capítulo 3)", d:"El capítulo más breve de los Interiores contiene la parábola más citada del libro. El cocinero Ding descuartiza un buey delante del príncipe Wenhui con un ritmo tan preciso que el cuchillo silba en la danza; interrogado sobre su habilidad, responde que lo que le interesa no es la técnica sino el Dao. Al principio veía bueyes enteros; después de tres años ya no veía bueyes; ahora trabaja con la mente y no con los ojos, se mueve por los intersticios naturales, nunca toca un tendón, menos todavía un hueso grande. Un cocinero mediocre cambia de cuchillo cada mes porque golpea; uno bueno, cada año, porque corta; el suyo lleva diecinueve años y tiene el filo como recién salido de la piedra, porque las articulaciones tienen espacio y la hoja no tiene grosor. Y añade un detalle que suele omitirse en los resúmenes entusiastas: cuando llega a un lugar enredado, se detiene, mira fijo, va despacio, mueve apenas el cuchillo. El príncipe concluye que ha aprendido a nutrir la vida. El capítulo agrega dos escenas menos famosas y más incómodas —un hombre con un solo pie que acepta su estado como cosa del Cielo y el funeral de Lao Dan, donde llorar en exceso se juzga una huida de lo natural— que impiden leerlo como un simple elogio de la maestría profesional."},
   {t:"Waipian y Zapian: Capítulos Exteriores (8-22) y Misceláneos (23-33)", d:"Las dos terceras partes restantes del libro son obra de manos posteriores y de orientaciones que no siempre coinciden entre sí, y leerlas sin distinguirlas produce un Zhuangzi confuso. Desde los trabajos de Guan Feng y sobre todo desde la clasificación de A. C. Graham suele separarse por lo menos tres corrientes. Una es primitivista o próxima al yangismo, hostil a la civilización, que en los capítulos 8 a 11 ataca la benevolencia y la rectitud confucianas con una dureza que los Interiores nunca usan, sostiene que el pie palmeado y el dedo de más son tan sobrantes como las virtudes enseñadas, y sueña con una edad de la virtud perfecta anterior a los sabios. Otra es sincretista o Huang-Lao, en capítulos como el 12 al 15 y el 33, que integra el taoísmo con el vocabulario cosmológico y administrativo de la época y termina ofreciendo un programa de gobierno que al Zhuang Zhou de la tortuga en el barro le habría dado risa. Una tercera es continuadora genuina de los Interiores, y de ella salen algunas páginas espléndidas: el debate sobre la felicidad de los peces en el río Hao (capítulo 17), la muerte de la esposa (capítulo 18), la calavera que se niega a volver a la vida, el nadador de la catarata y el fabricante de ruedas que le dice a un duque que los libros de los sabios son las heces de los antiguos (capítulo 13). El capítulo 33 cierra el libro con el primer panorama de la filosofía china escrito desde dentro, y describe al propio Zhuangzi en tercera persona, lo que prueba que su autor no es él."}
 ],
 conceptos:[
   {t:"El sueño de la mariposa", d:"Zhuang Zhou sueña que es una mariposa que revolotea contenta consigo misma y no sabe nada de Zhou; despierta y ahí está Zhou, inconfundible y sólido; y ya no sabe si es Zhou que soñó ser mariposa o una mariposa que ahora sueña ser Zhou. El error más común es leerlo como una duda cartesiana sobre la realidad del mundo exterior, y el final del pasaje lo impide: entre Zhou y la mariposa, dice el texto, debe de haber alguna distinción, y a eso se lo llama la transformación de las cosas. No se niega la diferencia; se niega que podamos fijarla desde adentro de uno de los dos estados, porque cada estado viene con su propio criterio de lo real y mientras uno sueña el sueño es la vigilia. La diferencia con Descartes es instructiva: Descartes usa el sueño como amenaza y busca una certeza que lo derrote, Zhuangzi lo usa como modelo y lo que busca es que dejemos de pedir esa certeza. Y hay una tercera lectura, más cercana al vocabulario del libro, que no es epistemológica sino ontológica: si todo está en transformación permanente, la pregunta sobre cuál de los dos es el yo verdadero está mal planteada, como preguntar cuál es el agua verdadera de un río. Lo que queda en pie es una tesis fuerte sobre la identidad personal: el yo no es un núcleo que atraviesa los cambios, es uno de los cambios."},
   {t:"Qiwu: la igualación de las cosas y de los discursos", d:"El término da título al capítulo 2 y nombra la operación central del libro: poner al mismo nivel las perspectivas que el debate ordena jerárquicamente. El punto de partida son los pares de opuestos que el lenguaje produce, shi y fei, esto y aquello, así y no así, correcto e incorrecto. Zhuangzi observa que esto no puede nacer sin aquello, que cada uno es el aquello del otro, y que por eso la disputa nunca termina: cada escuela usa su propio criterio para medir el criterio ajeno. La salida que propone no es elegir un bando ni proclamar que todos tienen razón, sino situarse en lo que llama el eje del Dao, el punto donde el círculo de las alternativas deja de girar y uno puede responder sin agotarse. Hay que evitar dos malentendidos. El primero es tomar la igualación por indiferencia práctica: el propio texto distingue constantemente entre un cocinero hábil y uno torpe, entre una vida larga y una corta, entre una lectura obtusa y una lúcida. El segundo es tomarla por una tesis metafísica sobre que todo es lo mismo, cuando lo igualado son los puntos de vista en tanto pretensiones de validez absoluta, no las cosas en su textura concreta. Leído así, Zhuangzi no dice que da igual lo que hagas, dice que ninguna de las razones con que justificás lo que hacés tiene el rango cósmico que le atribuís."},
   {t:"Ziran y el fluir con el Dao", d:"Ziran, lo que es así por sí mismo, es el concepto que Zhuangzi hereda del taoísmo anterior, y compararlo con el uso de Laozi es la mejor manera de ver qué hizo con la herencia. En el Dao De Jing, ziran y wu wei funcionan sobre todo como consejo al gobernante: hacer menos, legislar menos, dejar que el pueblo se ordene solo. En Zhuangzi el centro de gravedad se desplaza del palacio al oficio y a la vida individual, y los ejemplos dejan de ser políticos para volverse artesanales y corporales: el cocinero, el nadador que se deja llevar por los remolinos porque sigue el camino del agua y no el suyo, el carpintero que encuentra en el bosque el árbol del que saldrá la campana, el cigarrero que atrapa cigarras con una vara como si recogiera cosas con la mano. Fluir con el Dao no es abandonarse: en todos esos casos hay años de práctica, atención extrema y una capacidad de detenerse ante lo difícil. La diferencia con Laozi tiene además un tono: donde el Dao De Jing es sentencioso y prescriptivo, Zhuangzi cuenta historias y se ríe, y esa preferencia por la anécdota sobre el aforismo es coherente con su desconfianza de las fórmulas. Conviene registrar también una continuidad real, para no exagerar el contraste: ambos piensan que la intervención forzada estropea lo que toca, y ambos ponen el ejemplo del cocinero."},
   {t:"Xiaoyao: el vagabundeo libre", d:"Xiaoyaoyou se traduce como vagar libre y sin rumbo, deambular sin destino, paseo despreocupado, y el matiz importa: no es la libertad como capacidad de elegir entre opciones ni como ausencia de coacción externa, sino como una relación distinta con las opciones mismas. El modelo es el paseo y no el viaje, porque el que viaja mide el trayecto por la llegada y el que pasea no tiene con qué fracasar. El capítulo 1 monta una escala aparente de grandezas —la codorniz, el Peng, Liezi cabalgando el viento— para desarmarla al final: todos dependen de algo, y la libertad que interesa a Zhuangzi es la de quien cabalga lo que es así por sí mismo y no necesita apoyo. Eso plantea una dificultad honesta, porque un ser humano siempre depende de comida, de cuerpo, de otros, y el texto no explica cómo sería esa independencia sin caer en una figura sobrehumana, la del hombre verdadero que atraviesa el fuego sin quemarse. La lectura más sobria, y la que sostienen buena parte de los estudios contemporáneos, es que el xiaoyao describe una transformación de la actitud y no de las condiciones: el mismo funcionario menor en el mismo jardín de lacas, con la diferencia de que ya no mide su vida con la vara del ascenso. Por eso el concepto se apoya en el anterior: se puede pasear cuando se dejó de creer que hay un lugar al que había que llegar."},
   {t:"El cocinero Ding: la destreza que sigue la veta", d:"La parábola del capítulo 3 es la respuesta de Zhuangzi a la pregunta de cómo se actúa bien sin una regla que lo garantice, y su respuesta es un modelo de habilidad y no de obediencia. Ding no aplica un método a la materia: la lee, entra por los intersticios, deja que la estructura del buey decida el recorrido del cuchillo. Tres detalles hacen de esto algo más que una metáfora bonita. El primero es el aprendizaje por etapas, que ocupa años y va de ver bueyes enteros a no verlos, es decir, de la percepción de objetos a la percepción de articulaciones y vacíos. El segundo es el criterio material de éxito, que el texto se molesta en dar: diecinueve años sin afilar la hoja, frente al mes del que golpea y el año del que corta, de modo que la destreza se comprueba en el desgaste y no en la sensación interior. El tercero, el más olvidado, es la pausa: ante un nudo difícil, Ding se detiene, mira, va despacio. Esa cláusula desmiente la lectura romántica del fluir como espontaneidad sin esfuerzo y la vuelve compatible con lo que la psicología contemporánea llamó experiencia de flujo, que también supone habilidad entrenada y desafío ajustado. La consecuencia ética es fuerte: para Zhuangzi el saber ejemplar no es el del que argumenta bien sino el del que hace bien, y esa inversión pone a los filósofos profesionales de su tiempo por debajo de un carnicero."},
   {t:"La utilidad de lo inútil", d:"El tema recorre el libro entero. Huizi se queja de una calabaza tan grande que no sirve de recipiente ni de cucharón, y Zhuangzi le sugiere atarla a la cintura y flotar con ella por ríos y lagos. Huizi se queja de un árbol enorme, retorcido y nudoso, que ningún carpintero mira, y Zhuangzi le contesta que lo plante en el campo de la nada, que se pasee a su lado y duerma a su sombra: el árbol no sufre por ser inútil, se salva por serlo. En el capítulo 4 aparece el caso extremo, el roble sagrado que llega a la vejez precisamente porque su madera pudre los barcos y agrieta los ataúdes, y el argumento se completa con los hombres deformes que se libran del reclutamiento militar mientras los sanos van a morir. Hay dos filos aquí. Uno es perspectivista y conecta con el resto del sistema: útil e inútil no son propiedades de las cosas sino de una relación con un fin, y cambiar el fin cambia la propiedad. El otro es una crítica social directa y bastante amarga, en un mundo de Reinos Combatientes donde ser valioso para el Estado significaba ser usado hasta gastarse: la inutilidad es una estrategia de supervivencia frente al poder. Y queda una objeción digna de discusión, porque el mismo libro elogia la excelencia del cocinero: si la destreza extrema es admirable, la inutilidad no puede ser una receta general, y hace falta distinguir entre no servirle a nadie y no servir para nada."},
   {t:"La muerte como transformación", d:"Al morir su mujer, Zhuangzi es encontrado por Huizi sentado con las piernas abiertas, golpeando una vasija y cantando. Huizi lo acusa: convivió con vos, crió a tus hijos, envejeció a tu lado, y no llorarla ya sería bastante, pero cantar es demasiado. La respuesta de Zhuangzi es el pasaje más serio del libro y no una humorada. Dice que al principio también él se afligió, pero que se puso a mirar el comienzo: no había vida, ni forma, ni siquiera aliento; en la mezcla confusa de lo indistinto algo cambió y hubo aliento, el aliento cambió y hubo forma, la forma cambió y hubo vida, y ahora hubo otro cambio y hay muerte. Es la misma sucesión que la de las cuatro estaciones. Y concluye que si se pusiera a sollozar a gritos junto a ella, estaría mostrando que no entiende el destino. Hay que notar que la consolación no consiste en prometer otra vida, sino en desactivar la idea de que algo se perdió: lo que había volvió a la gran fragua donde todo se refunde. En la misma línea van la calavera que rechaza volver a vivir y la escena en que Zhuangzi, moribundo, prohíbe a sus discípulos un funeral costoso porque el cielo y la tierra ya son su ataúd, y ante el argumento de que los cuervos se lo comerán responde que enterrarlo sería quitárselo a los cuervos para dárselo a los gusanos, y que preferir a unos sobre otros es puro partidismo. La objeción obvia queda abierta: no está claro que una tesis cosmológica correcta baste para atravesar un duelo real, y el propio relato admite que al principio él tampoco pudo."},
   {t:"El escepticismo epistemológico", d:"Un pasaje del capítulo 2 formula el problema con una precisión que sorprende: cómo sé que lo que llamo saber no es ignorancia, y cómo sé que lo que llamo ignorar no es saber. Y sigue con la serie de preguntas por los criterios, que funcionan como una reducción al absurdo del punto de vista único: quién sabe cuál es el hábitat correcto si el hombre enferma en lo húmedo y la anguila prospera, quién sabe cuál es el gusto correcto si los ciervos comen pasto y las lombrices tierra, quién sabe cuál es la belleza verdadera si los peces se hunden y los pájaros huyen ante las mujeres más celebradas. A esto se suma la sospecha contra la vigilia misma, en el relato de quien sueña un banquete y llora al despertar, y de quien sueña llantos y sale de caza al amanecer: estamos soñando y hasta que no despertemos no sabremos que soñábamos, y quizá haya un gran despertar después del cual sabremos que todo esto fue un gran sueño. Ahora bien, conviene no convertirlo en un escéptico académico. Zhuangzi no suspende el juicio por método ni construye argumentos para la imposibilidad del conocimiento: usa la incertidumbre como terapia contra la arrogancia del que discute, y sigue afirmando cosas con enorme confianza a lo largo de todo el libro. Esa tensión es real y es el problema interpretativo central de la erudición contemporánea sobre el texto, que se divide entre leerlo como relativista, como escéptico terapéutico o como defensor de un saber no proposicional, el del cocinero, que no compite con las tesis porque no es del mismo tipo."},
   {t:"La crítica al confucianismo y al moísmo", d:"La polémica tiene un blanco histórico preciso. En la época de Zhuangzi, confucianos y moístas se disputaban el terreno intelectual con tesis opuestas sobre casi todo: el rito elaborado y el luto de tres años contra la austeridad y el ahorro, el afecto graduado que empieza por la propia familia contra el amor sin distinciones, la música como educación contra la música como despilfarro. Los moístas, además, habían desarrollado una lógica incipiente para determinar cuándo un nombre se aplica correctamente. Zhuangzi no toma partido: observa que cada una afirma lo que la otra niega y niega lo que la otra afirma, y que ese es justamente el síntoma de que ambas operan con el mismo mecanismo, el de fijar un esto y expulsar un aquello. Su objeción no es que se equivoquen en el contenido, es que la forma misma de la disputa garantiza que no termine. De ahí la parábola de los monos, que aceptan cuatro y tres después de rechazar tres y cuatro sin que la suma haya cambiado, y que según el texto ilustra el modo en que el sabio armoniza con lo correcto y lo incorrecto sin dejarse capturar por ninguno. Hay que agregar una precisión que el propio libro vuelve difícil de ver: Confucio aparece constantemente en el Zhuangzi, a veces ridiculizado, pero muy a menudo como portavoz de doctrinas taoístas, enseñando el ayuno de la mente o el sentarse y olvidar. Ese uso irónico del adversario como personaje es un rasgo literario notable, y también una advertencia contra tomar cada anécdota del libro como testimonio de lo que sus figuras históricas pensaban."}
 ],
 conexion:"Su relación con <b>Laozi</b> es de herencia y desplazamiento: comparte el Dao, el ziran y la desconfianza de la acción forzada, pero cambia el consejo al gobernante por la parábola del artesano, el aforismo por la anécdota y la solemnidad por la risa, y lleva el perspectivismo hasta poner en duda que exista un punto de vista privilegiado desde donde arbitrar. Frente a <b>Confucio</b> es el crítico más agudo de la tradición china, aunque lo use como personaje de sus propios cuentos. Siglos después, su procedimiento de disolver pseudoproblemas y su imagen de las palabras como nasa que se abandona cuando el pez ya está atrapado lo acercan al <b>Wittgenstein</b> de la escalera que se tira después de subir; su deflación de las esencias fijas y su desconfianza de los pares de opuestos anticipan problemas que <b>Nagarjuna</b> tratará con otro método; y su sueño de la mariposa es la contracara exacta del sueño de <b>Descartes</b>, porque uno lo usa como amenaza que hay que vencer y el otro como imagen que hay que habitar. Dentro de la propia tradición, el chan y el zen de <b>Dōgen</b> son impensables sin su estilo de paradoja y sin su ideal de destreza absorta.",
 dialogo:{titulo:"En el puente sobre el río Hao", lineas:[
   {quien:"Zhuangzi", texto:"Mirá cómo salen los pececitos, sueltos y a su aire. Esa es la felicidad de los peces."},
   {quien:"Hui Shi", texto:"Vos no sos un pez. ¿De dónde sacás que los peces son felices?"},
   {quien:"Zhuangzi", texto:"Vos no sos yo. ¿De dónde sacás que yo no sé que los peces son felices?"},
   {quien:"Hui Shi", texto:"Muy bien, acepto mi parte: yo no soy vos y por eso no puedo saber lo que vos sabés. Pero entonces, por el mismo camino, vos no sos un pez y no podés saber nada de su felicidad. El argumento queda completo y en contra tuya."},
   {quien:"Zhuangzi", texto:"Volvamos al principio. Vos me preguntaste de dónde sacaba que los peces son felices. Al preguntarme de dónde, ya sabías que yo lo sabía. Lo sé desde acá, desde el puente sobre el Hao.", nota:"Este remate se discute desde hace siglos y conviene no taparlo. La lectura desfavorable es que Zhuangzi comete un juego de palabras: el chino an puede significar cómo y también dónde, y él responde a la pregunta por el fundamento como si fuera una pregunta por el lugar. La lectura favorable es que el juego es deliberado y va al fondo: si el principio de Hui Shi fuera válido —nadie puede saber nada de lo que no es él mismo—, entonces su propia pregunta sería imposible de formular, porque para pedirme razones tenía que suponer primero que yo sé algo. No es un truco: es mostrar que la objeción escéptica no sobrevive a su propia aplicación."},
   {quien:"Hui Shi", texto:"Sos hábil con las palabras. Pero seguís sin decirme qué ves cuando decís que un pez es feliz."},
   {quien:"Zhuangzi", texto:"Veo lo mismo que vos: que se mueven sueltos, que nadie los empuja, que van y vienen sin medir el trayecto. Vos eso lo llamás conducta y yo lo llamo felicidad. La diferencia no está en el pez, está en dónde ponemos la frontera entre lo que se ve y lo que se supone."},
   {quien:"Hui Shi", texto:"La frontera está donde empieza la fantasía. Yo describo movimientos, vos les prestás un estado de ánimo que no podés observar."},
   {quien:"Zhuangzi", texto:"¿Y cuando tu mujer entra por la puerta y sabés antes de que hable que tuvo un mal día? También ahí prestás algo que no observás. Si te lo prohibieras del todo, no podrías vivir entre personas."},
   {quien:"Hui Shi", texto:"Con personas comparto la forma de vida. Con un pez no comparto nada."},
   {quien:"Zhuangzi", texto:"Compartís el agua del mismo río, la mañana, el hambre, el miedo a la sombra grande que pasa por arriba. Que la lista sea más corta no la vuelve vacía. Lo que estás haciendo es fijar un límite y llamarlo naturaleza."},
   {quien:"Hui Shi", texto:"Reconocé al menos esto: si aceptamos tu criterio, cualquiera puede atribuirle lo que se le antoje a cualquier cosa. Mañana alguien va a decir que la piedra está contenta."},
   {quien:"Zhuangzi", texto:"Que lo diga y veamos. Yo no te pedí que creyeras cualquier cosa, te describí unos peces que están ahí abajo. Tu método, en cambio, no me pide ver mejor: me pide dejar de mirar."},
   {quien:"Hui Shi", texto:"Y sin embargo escribís libro tras libro diciendo que nadie puede saber cuál es el punto de vista correcto. Si nadie puede, tampoco vos con los peces."},
   {quien:"Zhuangzi", texto:"Ahí sí me apretaste, y no lo voy a esquivar. No digo que no haya saber, digo que no hay un tribunal por encima de los puntos de vista. Desde el puente sé algo de los peces; desde el agua, el pez sabría de mí cosas que yo no sé. Lo que no existe es el lugar desde el cual decidir cuál de los dos mira mejor.", nota:"Aquí queda a la vista la tensión que atraviesa todo el libro y que la erudición contemporánea todavía discute: Zhuangzi socava la posibilidad de un criterio último y al mismo tiempo afirma cosas con enorme confianza, capítulo tras capítulo. Las salidas propuestas son básicamente tres: que su escepticismo sea terapéutico y no doctrinal, dirigido contra la arrogancia del que debate y no contra el conocimiento; que lo que defiende sea un saber de tipo distinto, el del cocinero y el nadador, que no compite con las tesis porque no es proposicional; o que la contradicción sea real y deliberada, parte de un texto que prefiere desarmar al lector antes que convencerlo."},
   {quien:"Hui Shi", texto:"Entonces discutir con vos es inútil."},
   {quien:"Zhuangzi", texto:"Es inútil como mi calabaza gigante y como el árbol que nadie tala. Por eso seguimos acá, al sol, sin llegar a ningún lado, mirando los peces."}
 ]},
 actividades:[
   {t:"Tu propio cocinero Ding", d:"Elegí una habilidad real que tengas y que hayas practicado durante años, no una que admires: cocinar, un instrumento, manejar, un deporte, tejer, dar clase, escribir código, cortar el pelo. Escribí primero una descripción minuciosa de un momento concreto en que las cosas salieron solas, con la hora, el lugar y lo que hacían tus manos, prohibiéndote las palabras fluir, flow, zona y conexión: contá solamente qué percibías y qué decidías. Escribí después una descripción igual de minuciosa de un momento en que forzaste la misma actividad y salió mal. Con los dos textos delante, respondé tres preguntas con ejemplos y no con generalidades: qué estabas mirando en cada caso, cuánto tiempo de práctica hizo falta para que apareciera el primer estado, y cuál es tu equivalente del momento en que Ding se detiene ante el nudo difícil y va despacio. Terminá con una objeción contra vos mismo: buscá un caso de tu vida donde dejarte llevar por el oficio te llevó a un error que una regla explícita habría evitado."},
   {t:"Inventario de lo inútil", d:"Hacé una lista de cinco cosas de tu vida que alguien descartó por inútiles, incluyendo al menos dos donde ese alguien hayas sido vos: una carrera que no empezaste, un objeto que conservás sin uso, una amistad que no te aporta nada, una materia del colegio que jamás usaste, un rato del día que no rinde. Para cada una escribí en un párrafo para qué no sirve, con precisión, y en otro párrafo qué fin habría que cambiar para que sirviera, al modo de la calabaza que no es recipiente pero es bote. Después viene la parte difícil, que es donde se juega la seriedad del ejercicio: identificá quién fija el criterio de utilidad en cada caso, si sos vos, tu familia, un empleador o un mercado de trabajo, y qué gana esa instancia con que vos aceptes su vara. Cerrá con la objeción interna del libro: el mismo Zhuangzi elogia la destreza extrema del cocinero, así que escribí en diez líneas dónde ponés vos la diferencia entre no servirle a nadie y no servir para nada."},
   {t:"Cuarenta y ocho horas de mariposa", d:"Durante dos días, anotá en el teléfono, apenas ocurra, cada vez que digas o pienses la frase yo soy seguida de algo: yo soy desordenado, yo soy el que se ocupa de esto, yo soy mala para los números, yo soy alguien que no discute. Juntá al menos quince. Al final de los dos días, agarrá la lista y hacé tres columnas. En la primera anotá desde cuándo creés que eso es cierto de vos y quién lo dijo primero. En la segunda, un episodio real, con fecha, en que hiciste exactamente lo contrario. En la tercera, qué cambiaría en un día concreto de tu semana si la frase fuera falsa. El ejercicio no busca que concluyas que no tenés identidad, cosa que el texto tampoco dice: el relato termina afirmando que entre Zhou y la mariposa debe de haber alguna distinción. Busca que pruebes en material propio la tesis más fuerte del pasaje, que el yo no es el núcleo que atraviesa los cambios sino uno de los cambios. Escribí al final media página sobre cuál de las quince frases te costó más poner en duda, y por qué esa."}
 ],
 cuestionario:[
   {q:"Si ningún punto de vista es privilegiado, ¿esa misma afirmación no se derrumba sola, como todo relativismo que se aplica a sí mismo?", p:"Es la objeción clásica y hay que concederle su fuerza antes de responderla: quien dice que ninguna perspectiva vale más que otra está proponiendo una tesis que, o vale para todos y entonces no es una perspectiva más, o es una perspectiva más y entonces no obliga a nadie. La defensa más usada es distinguir entre relativismo y escepticismo terapéutico. Zhuangzi no afirma la tesis de que todas las perspectivas son iguales, la muestra: pone al hombre, la anguila y el mono a discutir sobre el hábitat correcto, y el efecto que busca no es que aceptemos una doctrina sino que aflojemos la pretensión de arbitrar. En esa lectura sus textos funcionan como la nasa que se abandona cuando el pez está atrapado, y la autorrefutación es un precio que paga a sabiendas. Una segunda respuesta, más técnica, distingue niveles: lo que se niega no es todo conocimiento, sino la existencia de un criterio neutral para dirimir entre criterios, y esa negación puede sostenerse sin declararse a sí misma neutral. Y queda una tercera vía, la que sostiene que el saber que le interesa a Zhuangzi es el del cocinero, no proposicional y por tanto fuera del alcance de la paradoja. Ninguna de las tres cierra el problema del todo, y conviene decirlo: la erudición contemporánea sigue dividida."},
   {q:"¿Se puede vivir con este escepticismo? Frente a un incendio o una urgencia médica hay que decidir en segundos y con un solo criterio.", p:"La objeción es buena y el propio libro ofrece material para responderla, siempre que se distinga entre dudar y titubear. El cocinero Ding no delibera: ve el intersticio y entra. El nadador de la catarata no se pregunta cuál es la corriente verdadera, sigue el agua. La propuesta de Zhuangzi es exactamente lo contrario de la parálisis: la duda apunta a los criterios que se invocan en la discusión, no a la percepción entrenada que actúa. Hay incluso una tesis implícita interesante, que la deliberación explícita es el modo torpe de actuar y que la competencia consiste en no necesitarla. Dicho esto, quedan dos problemas reales. El primero es que en una urgencia médica lo que salva es justamente un protocolo explícito, y un protocolo es una regla general aplicada sin atender al caso, es decir lo contrario del cuchillo que sigue la veta. El segundo es que la habilidad absorta funciona en dominios donde uno practicó miles de horas, y las decisiones difíciles de una vida —qué carrera, con quién vivir, si denunciar a un jefe— son justamente las que no se repiten lo suficiente como para desarrollar oficio. Un lector honesto debería conceder que Zhuangzi ilumina la acción experta y dice bastante poco sobre la decisión moral irrepetible."},
   {q:"¿En qué se diferencia realmente de Laozi, si ambos hablan del Dao, del ziran y de no forzar?", p:"Comparten el núcleo y se separan en tres cosas concretas. La primera es el destinatario: el Dao De Jing está escrito en buena medida para quien manda, con capítulos enteros sobre cómo gobernar un reino grande sin revolverlo, mientras que Zhuangzi rechaza los cargos, se ríe de los funcionarios y traslada el problema al individuo y a su oficio. La segunda es la forma, y no es un detalle decorativo: el aforismo sentencioso afirma, la anécdota muestra, y un pensamiento que desconfía de las fórmulas fijas encuentra en el relato un instrumento más coherente que en la máxima. La tercera es el alcance del perspectivismo: Laozi sostiene que los opuestos se generan mutuamente, pero conserva un fondo, el Dao, sobre el cual habla con autoridad y desde el cual recomienda lo blando sobre lo duro y lo bajo sobre lo alto; Zhuangzi radicaliza la duda hasta la pregunta de cómo sabemos que sabemos, y desconfía también de ese suelo. Hay además una diferencia histórica que conviene no borrar: la etiqueta taoísmo, daojia, la inventaron los bibliotecarios de la dinastía Han siglos después, agrupando textos que no se pensaban a sí mismos como una escuela, y los Capítulos Interiores casi no citan a Laozi. Lo que llamamos taoísmo filosófico es en parte una construcción retrospectiva."},
   {q:"El argumento de la felicidad de los peces, ¿es una respuesta sólida o un juego de palabras ingenioso?", p:"Las dos cosas, y ahí está lo interesante. El juego existe y es innegable: el carácter an significa cómo y también dónde, de modo que Zhuangzi contesta una pregunta por el fundamento como si fuera una pregunta por el lugar, y responde desde el puente sobre el Hao. Si el intercambio terminara ahí sería un sofisma elegante. Pero el remate contiene un movimiento lógico serio, que es lo que lo mantuvo vivo dos mil años: Hui Shi, al preguntar de dónde sabés, presupone que hay algo que saber y que el otro podría saberlo; si su principio fuera estricto —nadie puede conocer lo que no es él mismo—, entonces no podría haber formulado la pregunta ni entender la respuesta, y su propio escepticismo se desmonta antes de llegar a los peces. El argumento es, en rigor, una reducción al absurdo del criterio del adversario, y ese es un procedimiento perfectamente válido. Lo que no hace es demostrar que los peces sean felices, y conviene notar que Zhuangzi nunca lo intenta: su tesis es sobre dónde ponemos la frontera entre observar y suponer, no sobre psicología de los peces. El debate reaparece intacto en la discusión contemporánea sobre otras mentes y sobre la conciencia animal, y por eso funciona tan bien en clase."},
   {q:"Si solo los siete Capítulos Interiores son probablemente suyos, ¿qué queda en pie del Zhuangzi que se enseña?", p:"Queda bastante, pero hay que ordenarlo. La filología está razonablemente de acuerdo en atribuir los capítulos 1 a 7 a un mismo autor de fines del siglo IV a.C., por consistencia de vocabulario, de rima y de procedimiento, y en considerar los Exteriores y Misceláneos una compilación posterior que reúne por lo menos una corriente primitivista y antipolítica, una sincretista cercana al Huang-Lao que redacta programas de gobierno y una continuadora fiel al estilo de los Interiores. Eso tiene consecuencias prácticas para la lectura. Primero, algunas escenas famosísimas —la felicidad de los peces, la muerte de la esposa, la calavera, el fabricante de ruedas— están en los Exteriores, de modo que quien enseñe a Zhuangzi enseña casi siempre una antología de la escuela y no a un hombre; conviene decirlo en voz alta en lugar de disimularlo. Segundo, no es legítimo resolver una contradicción del libro apelando a la evolución de su autor, porque no hay un autor único cuyo pensamiento evolucione. Tercero, el ataque frontal a la benevolencia y la rectitud confucianas, mucho más agresivo en los capítulos 8 a 11, pertenece a una capa distinta y probablemente a otra escuela. La comparación con el caso del Dao De Jing y con el de Homero es útil: la disolución del autor único no empobreció ninguno de los tres textos, solo obligó a leerlos como caudales y no como edificios. Lo que se pierde es una biografía; lo que se gana es dejar de atribuirle a un hombre lo que dijo una tradición."}
 ],
 cadena:{ titulo:"¿Puede el perspectivismo decir que lo es?", intro:"Un razonamiento en ramas sobre la objeción que Hui Shi le hace a Zhuangzi al final del diálogo: si nadie puede saber cuál es el punto de vista correcto, tampoco vos. Las ramas recorren el capítulo 2 —el juez imparcial, Nie Que y Wang Ni, el sueño de la mariposa— y llevan a las tres grandes lecturas del libro: relativista, escéptica terapéutica y del saber práctico.", inicio:"n1", nodos:{
   n1:{ pregunta:"En el capítulo 2, cada cosa es «esto» desde sí misma y «aquello» desde otra, y ningún juez puede arbitrar entre dos que discuten: si coincide con uno, ya no es imparcial; si difiere de ambos, no puede decidir. Si eso es cierto, ¿qué estatuto tiene la afirmación de Zhuangzi de que ningún punto de vista es privilegiado?", opciones:[
     {texto:"Es una tesis más, y se refuta a sí misma: si vale para todos, es un punto de vista privilegiado.", va:"n2a"},
     {texto:"No es una tesis: Zhuangzi casi nunca afirma, pregunta.", va:"n2b"} ]},
   n2a:{ pregunta:"Zhuangzi parece anticipar la objeción. En el mismo capítulo escribe: «Ahora voy a decir algo. No sé si pertenece a la misma clase que lo que dicen los demás o no. Pero pertenezca o no, al fin es de la misma clase que ellos, y no se distingue de lo demás». ¿Qué hace con eso?", opciones:[
     {texto:"Se incluye a sí mismo en la crítica: acepta que su discurso tampoco tiene rango especial.", va:"n3a"},
     {texto:"Se escapa: si todo discurso vale lo mismo, puede decir cualquier cosa sin responder por nada.", final:{tipo:"revisar", texto:"Es la objeción de Hui Shi, y hay que tomarla en serio, pero el libro no la confirma. Zhuangzi distingue todo el tiempo entre el cocinero hábil y el torpe, entre una lectura obtusa y una lúcida, entre la vida del árbol nudoso y la del árbol talado. Lo que iguala no son todas las distinciones, sino las pretensiones de validez absoluta con que cada escuela defiende las suyas. Volvé un paso y probá la otra respuesta."}} ]},
   n3a:{ pregunta:"Si su propio discurso es uno más entre otros, ¿por qué habría que escucharlo?", opciones:[
     {texto:"Porque no pide que se lo crea: pide que se miren los efectos. El que se aferra a su «esto» sufre como los monos de las tres castañas.", final:{tipo:"bien", texto:"Es la lectura terapéutica. Después de la parábola de los monos, el capítulo 2 dice que el sabio armoniza lo correcto y lo incorrecto y descansa en el equilibrio del Cielo, y a eso lo llama «andar por dos caminos» (liǎng xíng). No propone una tesis mejor; propone dejar de sufrir por la necesidad de ganar la discusión. La autorrefutación deja de importar, porque el discurso nunca pretendió ser verdadero en el sentido de sus adversarios. El costo es que Zhuangzi queda sin armas contra quien le diga que su terapia es solo una preferencia más."}},
     {texto:"Porque, aun sin tribunal, algunas perspectivas ven más que otras: el gran pájaro Peng ve más que la codorniz.", final:{tipo:"bien", texto:"Es una lectura con apoyo en el capítulo 1: el conocimiento pequeño no alcanza al grande. Pero hay una lectura rival, famosa, que conviene conocer: Guo Xiang, el editor del libro en el siglo III, sostuvo que el Peng y la codorniz son igualmente libres cuando cada uno cumple su propia naturaleza, y que la escala de grandezas es otra ilusión. Y el mismo capítulo 1 muestra que el Peng también depende del viento. Elegiste una jerarquía de perspectivas; tenés que decir con qué criterio, sin volver al juez imparcial que el capítulo 2 declaró imposible."}} ]},
   n2b:{ pregunta:"Es verdad que el capítulo 2 está lleno de preguntas: ¿cómo sé que lo que llamo saber no es ignorancia? Pero una pregunta retórica puede afirmar tanto como una tesis. ¿Hay alguna diferencia real?", opciones:[
     {texto:"Sí: Zhuangzi deja la respuesta abierta incluso para sí mismo, como Wang Ni, que ni siquiera sabe si sabe que no sabe.", va:"n3b"},
     {texto:"No: la pregunta retórica es una tesis disfrazada, y el sueño de la mariposa termina afirmando algo.", final:{tipo:"bien", texto:"Leíste el final del pasaje con cuidado: entre Zhou y la mariposa, dice el texto, tiene que haber alguna distinción, y a esto se lo llama la transformación de las cosas (wù huà). No es un escéptico que suspende el juicio: afirma que todo está en transformación y que el yo es uno de esos cambios. Es la tercera lectura, más ontológica que epistemológica. Ganás un Zhuangzi con tesis; tenés que explicar cómo esa tesis escapa a la crítica que él mismo hace a toda tesis."}} ]},
   n3b:{ pregunta:"Nie Que le pregunta a Wang Ni si sabe en qué coinciden todas las cosas: «¿Cómo lo sabría?». Si sabe que no lo sabe: «¿Cómo lo sabría?». Si entonces nadie sabe nada: «¿Cómo lo sabría?». Pero en el capítulo siguiente el cocinero Ding sabe muchísimo. ¿Cómo encaja?", opciones:[
     {texto:"El saber de Ding no es proposicional: no afirma nada que pueda refutarse, sabe hacer.", final:{tipo:"bien", texto:"Es la lectura del saber práctico: la duda del capítulo 2 apunta a las tesis que se defienden en debate, no a la destreza que se ejerce. Ding no compite con Wang Ni porque no juegan el mismo juego. La distinción entre saber que y saber cómo, que la filosofía occidental formuló con Ryle en el siglo XX, ayuda a verlo. El precio aparece en las decisiones que no se repiten lo suficiente como para volverse oficio —qué carrera, si denunciar a un jefe—: ahí la destreza no ayuda y la duda sigue en pie."}},
     {texto:"No encaja: hay una tensión real entre el escéptico del capítulo 2 y el maestro del capítulo 3.", final:{tipo:"bien", texto:"Es una lectura honesta y tiene una consecuencia que conviene notar: los capítulos 2 y 3 pertenecen a los Capítulos Interiores, los que se atribuyen al propio Zhuang Zhou, así que no se puede resolver la tensión culpando a los compiladores posteriores. O la contradicción es deliberada —un texto que prefiere desarmar al lector antes que convencerlo— o hay que buscar una lectura que la disuelva. Quedarte en la tensión sin cerrarla es, quizás, lo más fiel al libro."}} ]}
 }},
 reconstruccion:[
   { titulo:"La felicidad de los peces (Zhuangzi, capítulo 17)",
     consigna:"Reconstruí como argumento la respuesta final de Zhuangzi a Hui Shi en el puente sobre el Hao. Una pieza mezcla este pasaje con otro del libro: dejala afuera y ordená el resto.",
     piezas:[
       {id:"f1", texto:"Hui Shi sostiene un principio: nadie puede saber lo que ocurre en un ser que no es él mismo; como Zhuangzi no es un pez, no puede saber si los peces son felices.", tipo:"premisa"},
       {id:"f2", texto:"Pero Hui Shi tampoco es Zhuangzi: aplicado con rigor, su principio le impide saber si Zhuangzi sabe o no sabe algo de los peces.", tipo:"premisa"},
       {id:"f3", texto:"Hui Shi acepta ese costo: admite que no sabe lo que Zhuangzi sabe, y sostiene que igual el principio basta para negar que Zhuangzi conozca a los peces.", tipo:"premisa"},
       {id:"f4", texto:"Sin embargo, al preguntar «¿cómo sabés que los peces son felices?», Hui Shi ya trató a Zhuangzi como alguien de quien podía saber algo: que afirmaba saber, y que podía dar razones.", tipo:"premisa"},
       {id:"f5", texto:"Por lo tanto, el principio de Hui Shi no puede sostenerse sin socavar su propia pregunta: si algo se sabe de otros, la cuestión no es si se puede saber, sino desde dónde; y Zhuangzi responde: desde aquí, sobre el Hao.", tipo:"conclusion"},
       {id:"fx", texto:"Además, como Zhuangzi soñó una vez que era una mariposa, conoce por experiencia propia lo que siente un animal.", tipo:"distractor"}
     ],
     ordenCorrecto:["f1","f2","f3","f4","f5"],
     explicacion:"El argumento es una reducción al absurdo del criterio de Hui Shi: f2 lo aplica a Hui Shi mismo, f3 muestra que él acepta aplicarlo a medias, y f4 muestra que su propia pregunta presupone lo que el principio niega. La conclusión tiene dos capas, y conviene separarlas. Una es un juego de palabras: el chino ān significa «cómo» y también «dónde», y Zhuangzi contesta la pregunta por el fundamento como si fuera por el lugar. La otra es un movimiento lógico serio: el escepticismo sobre otras mentes no puede formularse sin suponer que se sabe algo de otra mente. Notá lo que el argumento no hace: no demuestra que los peces sean felices, solo desarma el principio que prohibía decirlo. La pieza sobrante confunde el pasaje con el sueño de la mariposa, que no trata de conocer a otros animales sino de la inestabilidad del propio yo."},
   { titulo:"La utilidad de lo inútil: el roble del santuario (Zhuangzi, capítulo 4)",
     consigna:"Reconstruí el argumento que el gran roble le presenta en sueños al carpintero Shi, que lo había despreciado por inútil. Una pieza viene de otra parábola del libro y dice lo contrario: dejala afuera.",
     piezas:[
       {id:"u1", texto:"Los árboles frutales —el espino, el peral, el naranjo, el pomelo— son útiles: por eso, cuando dan fruto, les arrancan los frutos y les quiebran las ramas, y no llegan a vivir sus años.", tipo:"premisa"},
       {id:"u2", texto:"La madera del roble, en cambio, es inútil: los barcos hechos con ella se hunden, los ataúdes se pudren, las herramientas se rompen, las puertas rezuman savia.", tipo:"premisa"},
       {id:"u3", texto:"Precisamente por eso ningún carpintero lo taló, y llegó a ser tan grande que su sombra cubre a miles de bueyes.", tipo:"premisa"},
       {id:"u4", texto:"Lo que el carpintero llama «inútil» es inútil para sus fines; para el árbol, esa misma inutilidad es lo que le permitió vivir.", tipo:"premisa"},
       {id:"u5", texto:"Por lo tanto, la inutilidad fue la gran utilidad del roble: útil e inútil no son propiedades de las cosas sino relaciones con un fin, y quien lo mide todo con el fin del carpintero no puede ver la vida del árbol.", tipo:"conclusion"},
       {id:"ux", texto:"Así como el cuchillo del cocinero Ding dura diecinueve años gracias a su excelencia, el roble perdura gracias a la calidad superior de su madera.", tipo:"distractor"}
     ],
     ordenCorrecto:["u1","u2","u3","u4","u5"],
     explicacion:"El argumento contrasta dos destinos (u1 y u2-u3) y extrae de ellos una tesis relacional (u4-u5): la utilidad no está en la cosa, está en el fin con que se la mide. En el texto el roble agrega un golpe final contra el carpintero: los dos son cosas, ¿cómo puede una cosa juzgar a otra? Y vos, un hombre inútil a punto de morir, ¿qué sabés de árboles inútiles? El trasfondo histórico importa: en la época de los Reinos Combatientes, ser valioso para el Estado significaba ser reclutado, gravado y usado hasta gastarse, y el capítulo sigue con el jorobado que se libra de la leva. La pieza sobrante invierte el argumento: Ding dura por su excelencia, el roble por su falta de ella. Esa tensión es real y el libro la contiene: la destreza extrema es admirable y la inutilidad protege, así que hace falta distinguir entre no servirle a nadie y no servir para nada."}
 ],
 dilemas:[
   { titulo:"Arreglar a Tomás",
     intro:"Zhuangzi cuenta que los emperadores del Norte y del Sur quisieron agradecerle a Hundun, el emperador del Centro, su hospitalidad: como no tenía los siete orificios que todos tienen para ver, oír, comer y respirar, le perforaron uno por día; al séptimo día, Hundun murió (capítulo 7). Este caso pregunta cuándo corregir algo que parece defectuoso es ayudarlo, y cuándo es perforarlo.",
     pasos:[
       { id:"p1", situacion:"Tu hermano Tomás tiene quince años. Pasa horas dibujando historietas, aprueba las materias con lo justo, no tiene amigos en el colegio pero sí una comunidad de dibujantes en internet que lo respeta. Tus padres están preocupados y te piden ayuda para «arreglarlo»: profesor particular, deporte obligatorio, límite de pantallas. ¿Qué proponés?", opciones:[
         {texto:"Un plan completo: profesor, deporte, horario de pantallas. Es por su bien.", consecuencia:"Tus intenciones son buenas, como las de los emperadores con Hundun. En el capítulo 18 hay otra historia del mismo tipo: el marqués de Lu recibió un ave marina, la agasajó con vino, música solemne y carne de buey, y el ave murió de tristeza a los tres días, porque la trató como se trataría él mismo y no como se trata a un ave. El plan está hecho con tu medida de lo que es una buena vida.", va:"p2a"},
         {texto:"Primero pasar tiempo con él y entender qué hace ahí, antes de decidir si hay algo que arreglar.", consecuencia:"Es el comienzo del cocinero Ding: ver primero la estructura antes de cortar. No es no hacer nada; es negarse a cortar sin saber dónde están las articulaciones.", va:"p2b"},
         {texto:"Nada: es su naturaleza, cada uno es como es.", consecuencia:"Suena zhuangziano y tiene apoyo en un capítulo exterior (capítulo 8): alargar las patas cortas del pato lo haría sufrir, cortar las largas de la grulla le daría pena. Pero cuidado con congelar a Tomás en una naturaleza fija: para Zhuangzi todo está en transformación, y dejar ser no es desentenderse. Además, no sabés todavía qué hay en su vida.", va:"p2b"} ]},
       { id:"p2a", situacion:"Tomás acepta a regañadientes. A los dos meses, sus notas mejoraron algo, dejó de dibujar y está apagado; casi no habla en la mesa. Tus padres están contentos con el boletín. ¿Qué hacés?", opciones:[
         {texto:"Sigo con el plan: el ánimo es pasajero y las notas quedan.", consecuencia:"Es posible que el ánimo vuelva. Pero mirá lo que medís y lo que no: mejoró lo que se contaba en el boletín, y lo que no se contaba se está apagando. Hundun no murió de una sola perforación, sino de siete, cada una razonable.", va:"p3"},
         {texto:"Hablo con mis padres: lo que medimos mejoró, y lo que no medimos se está perdiendo.", consecuencia:"Es la tesis de la utilidad de lo inútil puesta en práctica: el dibujo es inútil para el boletín y quizá sea lo que sostenía a Tomás. No significa abandonar todo el plan, sino revisar con qué fin se lo diseñó.", va:"p3"} ]},
       { id:"p2b", situacion:"Pasás varias tardes con él. Descubrís que dibuja muy bien y que en su comunidad lo admiran. También descubrís dos cosas que no te gustan: duerme cinco horas por noche, y un adulto del foro le encarga dibujos «por la exposición» sin pagarle nunca. ¿Qué hacés?", opciones:[
         {texto:"Intervengo en lo del sueño y en lo del adulto, y dejo el dibujo en paz.", consecuencia:"Es el cuchillo de Ding: entra por los intersticios y, ante el nudo difícil, se detiene, mira y va despacio. No renunciaste a intervenir; elegiste dónde. Proteger a un menor de un adulto que lo usa no es forzar su naturaleza: es sacarle de encima una fuerza ajena.", va:"p3"},
         {texto:"No intervengo en nada: si le pongo límites, lo pierdo.", consecuencia:"Entendiste que la confianza de Tomás vale mucho, pero confundiste el no forzar con la indiferencia. El adulto que lo usa no es el curso natural de nada; es exactamente el tipo de uso que el roble del capítulo 4 evitaba. Zhuangzi critica al que perfora a Hundun, no al que lo protege.", va:"p3"},
         {texto:"Le cuento todo a mis padres para que decidan ellos.", consecuencia:"Es razonable: son adultos responsables de él. Pero sabés cómo lo miran: con el plan del profesor y el deporte. Entregarles la información sin tu lectura del caso puede terminar en el mismo arreglo general que querías evitar. Quizás lo que te toca es contarles también lo que viste que funciona.", va:"p3"} ]},
       { id:"p3", situacion:"Un año después, tu madre te pregunta: «¿Hicimos bien en no arreglarlo del todo?». ¿Qué le respondés?", opciones:[
         {texto:"«No hay desde dónde saberlo: cada uno ve a Tomás desde su lugar.»", consecuencia:"Es el argumento del juez imparcial, pero usado aquí se vuelve una manera de no responder. Recordá el puente sobre el Hao: Zhuangzi no dice que no se pueda saber nada de otro, dice que se sabe desde algún lugar. Tu madre te pregunta desde dónde lo ves vos.", va:null},
         {texto:"«Hicimos bien en lo que miramos antes de tocar, y mal en lo que tocamos sin mirar.»", consecuencia:"Es una respuesta a la manera del cocinero: el criterio no es intervenir o no intervenir, sino haber visto la estructura antes de cortar. No es una regla general; es un balance de este caso.", va:null},
         {texto:"«El problema no era arreglarlo: era creer que sabíamos cómo era un Tomás arreglado.»", consecuencia:"Es la lección del Qiwulun aplicada a una persona: la vara con que medíamos —boletín, deporte, amigos del colegio— era una perspectiva entre otras, presentada como si fuera la única. Notá que esto no te exime de haber intervenido en el sueño y en el abuso: la crítica apunta a la vara, no a toda acción.", va:null} ]}
     ],
     rubrica:[
       "Separé lo que parecía un defecto de Tomás de lo que era un defecto según la vara de otro (la escuela, mis padres, yo).",
       "Puedo contar la historia de Hundun o la del ave del marqués de Lu y explicar qué error de intervención ilustra cada una.",
       "No confundí la crítica de Zhuangzi a la intervención forzada con indiferencia: identifiqué dónde había un nudo que exigía detenerse y actuar con cuidado.",
       "Distinguí entre lo que mejoró según lo que medíamos y lo que se perdió sin que lo midiéramos.",
       "Tuve en cuenta que, para Zhuangzi, la naturaleza no es fija: todo está en transformación, y dejar ser no es congelar.",
       "Usé la utilidad de lo inútil para pensar el dibujo, sin convertirla en excusa para no atender el sueño o el abuso.",
       "Formulé la objeción más fuerte: que el perspectivismo, llevado al extremo, deja sin criterio a quien tiene que decidir por un menor."
     ] }
 ]}
);

/* ---------- Lecturas: textos fuente + preguntas de comprensión ---------- */
LECTURAS.zhuangzi = { lecturas:[
 {titulo:"El sueño de la mariposa y la igualación de las cosas", fuente:"Ciudad Seva — Biblioteca digital Luis López Nieves", url:"https://ciudadseva.com/texto/sueno-de-la-mariposa/",
  extracto:`El relato más famoso de la filosofía china cabe en pocas líneas: «Zhuang Zhou soñó una vez que era una mariposa, una mariposa que revoloteaba de aquí para allá, contenta consigo misma y haciendo lo que le placía. No sabía que era Zhuang Zhou. De pronto despertó, y allí estaba, Zhuang Zhou inconfundible y sólido. Pero no sabía si era Zhou que había soñado que era una mariposa, o una mariposa que soñaba que era Zhou. Entre Zhou y la mariposa debe de haber alguna distinción. A esto se le llama la transformación de las cosas».

Lo decisivo está en el cierre. Zhuangzi no dice que no haya distinción entre Zhou y la mariposa — dice que «debe de haber alguna». Lo que cuestiona no es que existan diferencias, sino nuestra capacidad de fijar desde dentro cuál es el punto de vista verdadero. Y en lugar de lamentarlo, lo nombra con un término positivo: transformación de las cosas.

El capítulo «Sobre la igualación de las cosas» (Qíwùlùn) desarrolla la tesis general. Cada escuela —confucianos, mohistas— afirma lo que la otra niega. «Cada una afirma lo que la otra niega y niega lo que la otra afirma. Si queremos afirmar lo que ellas niegan y negar lo que afirman, lo mejor es usar la claridad.» El problema, señala, es que para dirimir la disputa haría falta un juez; pero si el juez coincide conmigo no es imparcial, si coincide con vos tampoco, y si difiere de ambos no puede decidir. No hay tribunal neutral desde el cual juzgar entre perspectivas.

Su ejemplo más incisivo es el de los criterios: «los hombres duermen en lugares húmedos y terminan con dolor de espalda; ¿le pasa lo mismo a una anguila? Los hombres se encaraman a los árboles y tiemblan de miedo; ¿le pasa lo mismo a un mono? De los tres, ¿quién sabe dónde está el lugar adecuado para vivir?». Lo mismo con la belleza: Mao Qiang y Lady Li eran las mujeres más bellas para los hombres, «pero si los peces las vieran se hundirían en lo hondo, si los pájaros las vieran alzarían el vuelo». ¿Quién conoce entonces la belleza verdadera?

La consecuencia práctica es el xiāoyáoyóu, el «vagar libre y sin rumbo» que da título al primer capítulo. Allí el pájaro Peng se eleva noventa mil li y la cigarra se burla de él porque ella apenas llega a la rama más cercana: cada uno mide el mundo con su propia escala. Y está la parábola de la calabaza enorme que Huizi considera inútil porque es demasiado grande para servir de recipiente; Zhuangzi le responde que la ate a su cintura y flote con ella por los ríos y lagos — «¡qué obstruida está tu mente por la maleza!». La inutilidad, vista desde otra perspectiva, es libertad.

El texto cierra su crítica del lenguaje con una imagen que la tradición zen repetirá durante siglos: «la nasa sirve para atrapar peces; una vez atrapado el pez, olvidate de la nasa. Las palabras sirven para atrapar ideas; una vez atrapada la idea, olvidate de las palabras. ¿Dónde puedo encontrar a un hombre que haya olvidado las palabras, para poder hablar con él?».`,
  comentario:"Zhuangzi no es un escéptico que niegue el conocimiento: es un perspectivista que niega la existencia de un punto de vista privilegiado desde el cual arbitrar. El argumento del juez imparcial es lógicamente rigurosos y anticipa problemas contemporáneos de inconmensurabilidad. Y fijate en la conexión con Wittgenstein: ambos terminan diciendo que el lenguaje es una herramienta que hay que saber soltar cuando cumplió su función."}
], preguntasLectura:[
 {q:"¿Qué afirma exactamente el final del relato de la mariposa?", opciones:["Que no hay ninguna distinción entre Zhou y la mariposa","Que debe de haber alguna distinción, y a eso se lo llama transformación de las cosas","Que los sueños son falsos","Que la mariposa era una alucinación"], r:"Que debe de haber alguna distinción, y a eso se lo llama transformación de las cosas", why:"Zhuangzi no niega la diferencia: niega que podamos fijar desde dentro cuál es el punto de vista verdadero."},
 {q:"¿Qué muestra el argumento del juez en «Sobre la igualación de las cosas»?", opciones:["Que los jueces son corruptos","Que no hay tribunal neutral para dirimir entre perspectivas","Que hay que consultar a los ancianos","Que el confucianismo tiene razón"], r:"Que no hay tribunal neutral para dirimir entre perspectivas", why:"Quien coincida con una parte no es imparcial, y quien difiera de ambas no puede decidir."},
 {q:"¿Qué enseña la parábola de la calabaza enorme que Huizi consideraba inútil?", opciones:["Que hay que cultivar calabazas más pequeñas","Que la inutilidad, desde otra perspectiva, es libertad","Que Huizi era mejor filósofo","Que los objetos grandes son valiosos"], r:"Que la inutilidad, desde otra perspectiva, es libertad", why:"Zhuangzi le propone atarla a la cintura y flotar: el criterio de utilidad también es perspectivista."}
]};
